# AUTO-GENERATED by EventForge v0.9.0
# Source: res://eventsheet_addons/move_to_3d/move_to_3d_behavior.tres
# DO NOT EDIT — this file is regenerated on every compile.

@icon("res://eventsheet_addons/behavior.svg")
class_name MoveTo3DBehavior
extends Node

## The node this behavior acts on (its parent). Required host: Node3D.
var host: Node3D = null

func _enter_tree() -> void:
	host = get_parent() as Node3D
	if host == null:
		push_warning("MoveTo3DBehavior behavior requires a Node3D parent.")

## @ace_trigger
## @ace_name("On Arrived (3D)")
## @ace_category("Move To 3D")
signal arrived

@export var max_speed: float = 5.0
var moving: bool = false
var waypoints: Array = []

func _process(delta: float) -> void:
	if not moving or host == null or waypoints.is_empty():
		return
	var target: Vector3 = waypoints[0]
	host.position = host.position.move_toward(target, max_speed * delta)
	if host.position.distance_to(target) < 0.05:
		waypoints.pop_front()
		if waypoints.is_empty():
			moving = false
			arrived.emit()

## @ace_action
## @ace_name("Move To Position (3D)")
## @ace_category("Move To 3D")
## @ace_description("Replaces the queue and glides toward the point.")
## @ace_icon("res://eventsheet_addons/behavior.svg")
## @ace_codegen_template("$MoveTo3DBehavior.move_to_position_3d({x}, {y}, {z})")
func move_to_position_3d(x: float, y: float, z: float) -> void:
	waypoints = [Vector3(x, y, z)]
	moving = true

## @ace_action
## @ace_name("Add Waypoint (3D)")
## @ace_category("Move To 3D")
## @ace_description("Appends a stop to the queue.")
## @ace_icon("res://eventsheet_addons/behavior.svg")
## @ace_codegen_template("$MoveTo3DBehavior.add_waypoint_3d({x}, {y}, {z})")
func add_waypoint_3d(x: float, y: float, z: float) -> void:
	waypoints.append(Vector3(x, y, z))
	moving = true

## @ace_action
## @ace_name("Stop Moving (3D)")
## @ace_category("Move To 3D")
## @ace_description("Clears the queue without firing On Arrived.")
## @ace_icon("res://eventsheet_addons/behavior.svg")
## @ace_codegen_template("$MoveTo3DBehavior.stop_moving_3d()")
func stop_moving_3d() -> void:
	moving = false
	waypoints = []

# Move To 3D behavior (event-sheet-style): glides through a queue of Vector3 waypoints and fires On Arrived at the final stop.
