# Pack builder - canvas_surface (the shared 2D drawing runtime; run via build_sample_behaviors.gd).
@tool

const Lib := preload("res://tools/pack_builders/_lib.gd")


## CanvasSurface: the engine-level 2D drawing plumbing that the ACE vocabulary cannot express - an
## offscreen SubViewport render target, a drawer whose `draw` signal replays a command queue, the
## persistence clear-mode trick, coordinate mapping, and self-updating textured ribbons. It lives in a
## dedicated RUNTIME pack (still plain GDScript, still ships with eventsheet_addons/, still zero EDITOR
## dependency) so the Drawing Canvas behavior and the builtin Draw ACEs stay thin, first-class rows that
## just call CanvasSurface methods. One surface is created per host on demand and cached on the host.
static func build() -> bool:
	var sheet: EventSheetResource = EventSheetResource.new()
	sheet.host_class = "Node2D"
	sheet.custom_class_name = "CanvasSurface"
	sheet.addon_requires = PackedStringArray(["DrawingPrefabResource"])
	sheet.class_description = "Shared 2D drawing runtime for the Drawing Canvas behaviour and the Draw ACEs: an offscreen render target, a command queue, and self-updating ribbons. One per host, cached on the host - call CanvasSurface.for_node(host)."
	var block: RawCodeRow = RawCodeRow.new()
	block.code = "\n".join(PackedStringArray([
		"const META_KEY: String = \"__canvas_surface\"",
		"",
		"var canvas_width: int = 512",
		"var canvas_height: int = 512",
		"var auto_clear: bool = false",
		"var coordinates: String = \"world\"  # \"world\" (centered on the host) or \"canvas\" (raw texture pixels)",
		"var display_on_host: bool = true",
		"",
		"var _host: Node2D = null",
		"var _viewport: SubViewport = null",
		"var _drawer: Node2D = null",
		"var _display: Sprite2D = null",
		"var _commands: Array = []",
		"var _ribbons: Array = []",
		"var _paste_textures: Array = []  # keeps pasted node textures alive - a freed source node (bake decor then Destroy) must not leave the persistent canvas re-drawing a dangling texture as a white block",
		"",
		"## Returns the host's canvas surface, creating (and attaching) one on first use. Cached on the host",
		"## via metadata, so every \"... on {node}\" draw shares one surface. Null-safe.",
		"static func for_node(host: Node) -> CanvasSurface:",
		"\tif not (host is Node2D):",
		"\t\treturn null",
		"\tvar host_2d: Node2D = host as Node2D",
		"\tif host_2d.has_meta(META_KEY):",
		"\t\tvar existing: Variant = host_2d.get_meta(META_KEY)",
		"\t\tif is_instance_valid(existing):",
		"\t\t\treturn existing",
		"\tvar surface: CanvasSurface = CanvasSurface.new()",
		"\tsurface.name = \"CanvasSurface\"",
		"\tsurface._host = host_2d",
		"\thost_2d.set_meta(META_KEY, surface)",
		"\t# Deferred: for_node commonly fires from the host's own child-setup (a behavior's On Ready), when a",
		"\t# direct add_child to the host is rejected as 'parent busy'. Draws buffer until the surface's _ready",
		"\t# builds the drawer and flushes them, so an On-Ready-time draw is not lost.",
		"\thost_2d.add_child.call_deferred(surface)",
		"\treturn surface",
		"",
		"## Applies configuration (from the behavior's exports) and rebuilds the surface if it already exists.",
		"func configure(width: int, height: int, clear_each_frame: bool, coords: String, show_on_host: bool) -> void:",
		"\tcanvas_width = width",
		"\tcanvas_height = height",
		"\tauto_clear = clear_each_frame",
		"\tcoordinates = coords",
		"\tdisplay_on_host = show_on_host",
		"\tif _viewport != null:",
		"\t\t_viewport.size = Vector2i(maxi(canvas_width, 8), maxi(canvas_height, 8))",
		"\t\t_viewport.render_target_clear_mode = SubViewport.CLEAR_MODE_ALWAYS if auto_clear else SubViewport.CLEAR_MODE_NEVER",
		"",
		"func _ready() -> void:",
		"\t# Ribbons are the only thing this surface needs a frame for, and a fresh surface has none:",
		"\t# every other draw is queued and redrawn on demand rather than polled, so an ordinary canvas",
		"\t# costs nothing per frame until Start Ribbon asks for one.",
		"\tset_physics_process(false)",
		"\t_ensure()",
		"",
		"## The display sprite lives on the HOST, not on this surface, so freeing (or re-creating) the surface",
		"## would leave a stray Sprite2D parented to the host still pointing at a dead ViewportTexture. Take it",
		"## with us on the way out.",
		"func _exit_tree() -> void:",
		"	if is_instance_valid(_display):",
		"		_display.queue_free()",
		"	_display = null",
		"",
		"## Builds the offscreen render target once: a SubViewport holding the drawer whose draw signal",
		"## replays the queue. Clear mode is the whole persistence story - NEVER accumulates (paint), ALWAYS",
		"## wipes (live redraw), and clear() flips to ONCE.",
		"func _ensure() -> void:",
		"\tif _viewport != null or not is_inside_tree():",
		"\t\treturn",
		"\t_viewport = SubViewport.new()",
		"\t_viewport.size = Vector2i(maxi(canvas_width, 8), maxi(canvas_height, 8))",
		"\t_viewport.transparent_bg = true",
		"\t_viewport.render_target_update_mode = SubViewport.UPDATE_ALWAYS",
		"\t_viewport.render_target_clear_mode = SubViewport.CLEAR_MODE_ALWAYS if auto_clear else SubViewport.CLEAR_MODE_NEVER",
		"\tadd_child(_viewport)",
		"\t_drawer = Node2D.new()",
		"\t_viewport.add_child(_drawer)",
		"\t_drawer.draw.connect(_run_draw_commands)",
		"\tif display_on_host and _host != null:",
		"\t\t_display = Sprite2D.new()",
		"\t\t_display.texture = _viewport.get_texture()",
		"\t\t_host.add_child.call_deferred(_display)",
		"\tif not _commands.is_empty():",
		"\t\t_drawer.queue_redraw()  # flush draws buffered before the surface entered the tree",
		"",
		"## World position -> canvas pixels: the canvas is centered on the host, so the mapping is a",
		"## translation. In canvas coordinate mode points pass through untouched.",
		"func to_canvas(point: Vector2) -> Vector2:",
		"\tif coordinates != \"world\" or _host == null:",
		"\t\treturn point",
		"\treturn point - _host.global_position + Vector2(canvas_width, canvas_height) * 0.5",
		"",
		"func _run_draw_commands() -> void:",
		"\t# The styled shapes this frame can instance, and the keys those batches took - everything",
		"\t# else, styled or not, is drawn the raster way in the order it was queued. THE TWO HALVES DO",
		"\t# NOT INTERLEAVE: the instanced shapes are children of the SubViewport and the raster ones are",
		"\t# drawn by the drawer under them, so a texture queued AFTER an arc still lands beneath it. A",
		"\t# frame that needs one exact stacking order is a persistent canvas, which draws every shape",
		"\t# the raster way.",
		"\tvar batched: Array = []",
		"\tvar taken: Dictionary = {}",
		"\tif _use_batches():",
		"\t\tfor batch: Dictionary in plan_batches(_commands):",
		"\t\t\tif _batches.has(str(batch[\"key\"])):",
		"\t\t\t\tbatched.append(batch)",
		"\t\t\t\ttaken[str(batch[\"key\"])] = true",
		"\tfor command: Dictionary in plan_raster(_commands, taken):",
		"\t\tmatch str(command[\"kind\"]):",
		"\t\t\t\"line\":",
		"\t\t\t\t_drawer.draw_line(command[\"a\"], command[\"b\"], command[\"color\"], command[\"width\"])",
		"\t\t\t\"circle\":",
		"\t\t\t\t_drawer.draw_circle(command[\"at\"], command[\"radius\"], command[\"color\"])",
		"\t\t\t\"ring\":",
		"\t\t\t\t_drawer.draw_arc(command[\"at\"], command[\"radius\"], 0.0, TAU, 64, command[\"color\"], command[\"width\"])",
		"\t\t\t\"rect\":",
		"\t\t\t\t_drawer.draw_rect(command[\"rect\"], command[\"color\"])",
		"\t\t\t\"polygon\":",
		"\t\t\t\t_drawer.draw_colored_polygon(command[\"points\"], command[\"color\"])",
		"\t\t\t\"multiline\":",
		"\t\t\t\t_drawer.draw_multiline(command[\"points\"], command[\"color\"], command[\"width\"])",
		"\t\t\t\"stamp\":",
		"\t\t\t\tvar texture: Texture2D = command[\"texture\"]",
		"\t\t\t\tif texture != null:",
		"\t\t\t\t\t_drawer.draw_set_transform(command[\"at\"], command[\"rotation\"], Vector2.ONE * float(command[\"scale\"]))",
		"\t\t\t\t\t_drawer.draw_texture(texture, -texture.get_size() * 0.5)",
		"\t\t\t\t\t_drawer.draw_set_transform(Vector2.ZERO, 0.0, Vector2.ONE)",
		"\t\t\t\"node_stamp\":",
		"\t\t\t\tvar node_tex: Texture2D = command[\"texture\"]",
		"\t\t\t\tif node_tex != null:",
		"\t\t\t\t\t_drawer.draw_set_transform_matrix(command[\"xform\"])",
		"\t\t\t\t\tvar src_rect: Rect2 = command[\"src_rect\"]",
		"\t\t\t\t\tif src_rect.size.x > 0.0 and src_rect.size.y > 0.0:",
		"\t\t\t\t\t\t_drawer.draw_texture_rect_region(node_tex, command[\"dest_rect\"], src_rect, command[\"modulate\"])",
		"\t\t\t\t\telse:",
		"\t\t\t\t\t\t_drawer.draw_texture_rect(node_tex, command[\"dest_rect\"], false, command[\"modulate\"])",
		"\t\t\t\t\t_drawer.draw_set_transform_matrix(Transform2D.IDENTITY)",
		"\t\t\t\"arc\":",
		"\t\t\t\t_drawer.draw_arc(command[\"at\"], command[\"radius\"], command[\"from\"], command[\"to\"], RASTER_ARC_SEGMENTS, command[\"color\"], command[\"width\"])",
		"\t\t\t\"polyline\":",
		"\t\t\t\t_drawer.draw_polyline(command[\"points\"], command[\"color\"], command[\"width\"])",
		"\t\t\t\"text\":",
		"\t\t\t\tvar face: Font = ThemeDB.fallback_font",
		"\t\t\t\tif face != null:",
		"\t\t\t\t\t_drawer.draw_string(face, command[\"at\"], str(command[\"message\"]), HORIZONTAL_ALIGNMENT_LEFT, -1, int(command[\"size\"]), command[\"color\"])",
		"\t\t\t\"texture_rect\":",
		"\t\t\t\tvar drawn_texture: Texture2D = command[\"texture\"]",
		"\t\t\t\tif drawn_texture != null:",
		"\t\t\t\t\t_drawer.draw_texture_rect(drawn_texture, command[\"rect\"], false, command[\"color\"])",
		"\t_fill_batches(batched)",
		"\t_commands.clear()",
		"",
		"func _push(command: Dictionary) -> void:",
		"\t_ensure()",
		"\t_commands.append(command)  # buffered even before the drawer exists; _ensure flushes it",
		"	if str(command.get(\"kind\", \"\")) == \"node_stamp\" and command.get(\"texture\") != null and not _paste_textures.has(command[\"texture\"]):",
		"		_paste_textures.append(command[\"texture\"])",
		"\tif _drawer != null:",
		"\t\t_drawer.queue_redraw()",
		"",
		"# --- Public draw surface (called by the Drawing Canvas behaviour and the builtin Draw ACEs) ---",
		"",
		"func texture() -> Texture2D:",
		"\t_ensure()",
		"\treturn _viewport.get_texture() if _viewport != null else null",
		"",
		"func clear() -> void:",
		"\t_ensure()",
		"\t_commands.clear()",
		"\tif _viewport != null and not auto_clear:",
		"\t\t_viewport.render_target_clear_mode = SubViewport.CLEAR_MODE_ONCE",
		"\tif _drawer != null:",
		"\t\t_drawer.queue_redraw()",
		"",
		"func set_auto_clear(enabled: bool) -> void:",
		"\tauto_clear = enabled",
		"\tif _viewport != null:",
		"\t\t_viewport.render_target_clear_mode = SubViewport.CLEAR_MODE_ALWAYS if enabled else SubViewport.CLEAR_MODE_NEVER",
		"",
		"func set_display_visible(visible_now: bool) -> void:",
		"\tif _display != null:",
		"\t\t_display.visible = visible_now",
		"",
		"func line(from_x: float, from_y: float, to_x: float, to_y: float, width: float, color: Color) -> void:",
		"\t_push({\"kind\": \"line\", \"a\": to_canvas(Vector2(from_x, from_y)), \"b\": to_canvas(Vector2(to_x, to_y)), \"width\": width, \"color\": color})",
		"",
		"func circle(x: float, y: float, radius: float, color: Color) -> void:",
		"\t_push({\"kind\": \"circle\", \"at\": to_canvas(Vector2(x, y)), \"radius\": radius, \"color\": color})",
		"",
		"func ring(x: float, y: float, radius: float, width: float, color: Color) -> void:",
		"\t_push({\"kind\": \"ring\", \"at\": to_canvas(Vector2(x, y)), \"radius\": radius, \"width\": width, \"color\": color})",
		"",
		"func rect(x: float, y: float, width: float, height: float, color: Color) -> void:",
		"\t_push({\"kind\": \"rect\", \"rect\": Rect2(to_canvas(Vector2(x, y)), Vector2(width, height)), \"color\": color})",
		"",
		"func cone(x: float, y: float, facing_deg: float, fov_deg: float, radius: float, color: Color) -> void:",
		"\tvar center: Vector2 = to_canvas(Vector2(x, y))",
		"\tvar points: PackedVector2Array = PackedVector2Array([center])",
		"\tfor i: int in 33:",
		"\t\tvar angle: float = deg_to_rad(facing_deg - fov_deg * 0.5 + fov_deg * float(i) / 32.0)",
		"\t\tpoints.append(center + Vector2.from_angle(angle) * radius)",
		"\t_push({\"kind\": \"polygon\", \"points\": points, \"color\": color})",
		"",
		"func stamp(texture_res: Texture2D, x: float, y: float, scale_factor: float, rotation_deg: float) -> void:",
		"\t_push({\"kind\": \"stamp\", \"texture\": texture_res, \"at\": to_canvas(Vector2(x, y)), \"scale\": maxf(scale_factor, 0.01), \"rotation\": deg_to_rad(rotation_deg)})",
		"",
		"func line_of_sight(origin_x: float, origin_y: float, facing_deg: float, fov_deg: float, max_range: float, collision_mask: int, color: Color) -> void:",
		"\t_ensure()",
		"\tif _host == null or not is_inside_tree() or _drawer == null:",
		"\t\treturn",
		"\tvar space: PhysicsDirectSpaceState2D = _host.get_world_2d().direct_space_state",
		"\tif space == null:",
		"\t\treturn",
		"\tvar origin: Vector2 = Vector2(origin_x, origin_y)",
		"\tvar points: PackedVector2Array = PackedVector2Array([to_canvas(origin)])",
		"\tfor i: int in 49:",
		"\t\tvar angle: float = deg_to_rad(facing_deg - fov_deg * 0.5 + fov_deg * float(i) / 48.0)",
		"\t\tvar direction: Vector2 = Vector2.from_angle(angle)",
		"\t\tvar query: PhysicsRayQueryParameters2D = PhysicsRayQueryParameters2D.create(origin, origin + direction * max_range, collision_mask)",
		"\t\tif _host is CollisionObject2D:",
		"\t\t\tquery.exclude = [(_host as CollisionObject2D).get_rid()]",
		"\t\tvar hit: Dictionary = space.intersect_ray(query)",
		"\t\tvar end_point: Vector2 = hit[\"position\"] if not hit.is_empty() else origin + direction * max_range",
		"\t\tpoints.append(to_canvas(end_point))",
		"\t_push({\"kind\": \"polygon\", \"points\": points, \"color\": color})",
		"",
		"func prefab(prefab_res: Resource, x: float, y: float, scale_factor: float, rotation_deg: float) -> void:",
		"\tif prefab_res == null:",
		"\t\treturn",
		"\t# One expansion path fed by pre-typed entries (the resource's cached compiled_steps() when it",
		"\t# exposes one, else a raw parse) - the same circle/ring/rect/line/cone/stamp calls, minus the",
		"\t# per-step Color.from_string, so drawing a prefab 1000x per frame does not re-parse strings.",
		"\tvar entries: Array = _prefab_entries(prefab_res)",
		"\tif entries.is_empty():",
		"\t\treturn",
		"\tvar origin: Vector2 = Vector2(x, y)",
		"\tvar spin: float = deg_to_rad(rotation_deg)",
		"\tvar scale_by: float = maxf(scale_factor, 0.01)",
		"\tfor entry: Dictionary in entries:",
		"\t\tvar local: Vector2 = Vector2(entry[\"x\"], entry[\"y\"])",
		"\t\tvar at: Vector2 = origin + (local * scale_by).rotated(spin)",
		"\t\tvar p1: float = entry[\"p1\"]",
		"\t\tvar p2: float = entry[\"p2\"]",
		"\t\tvar p3: float = entry[\"p3\"]",
		"\t\tvar tint: Color = entry[\"color\"]",
		"\t\tmatch str(entry[\"kind\"]):",
		"\t\t\t\"circle\":",
		"\t\t\t\tcircle(at.x, at.y, p1 * scale_by, tint)",
		"\t\t\t\"ring\":",
		"\t\t\t\tring(at.x, at.y, p1 * scale_by, maxf(p2 * scale_by, 1.0), tint)",
		"\t\t\t\"rect\":",
		"\t\t\t\tvar corners: PackedVector2Array = PackedVector2Array()",
		"\t\t\t\tfor corner: Vector2 in [Vector2.ZERO, Vector2(p1, 0.0), Vector2(p1, p2), Vector2(0.0, p2)]:",
		"\t\t\t\t\tcorners.append(to_canvas(origin + ((local + corner) * scale_by).rotated(spin)))",
		"\t\t\t\t_push({\"kind\": \"polygon\", \"points\": corners, \"color\": tint})",
		"\t\t\t\"line\":",
		"\t\t\t\tvar to_point: Vector2 = origin + (Vector2(p1, p2) * scale_by).rotated(spin)",
		"\t\t\t\tline(at.x, at.y, to_point.x, to_point.y, maxf(p3 * scale_by, 1.0), tint)",
		"\t\t\t\"cone\":",
		"\t\t\t\tcone(at.x, at.y, p1 + rotation_deg, p2, p3 * scale_by, tint)",
		"\t\t\t\"stamp\":",
		"\t\t\t\tvar texture: Texture2D = entry[\"tex\"]",
		"\t\t\t\tif texture != null:",
		"\t\t\t\t\tstamp(texture, at.x, at.y, maxf(p1, 0.01) * scale_by, p2 + rotation_deg)",
		"",
		"## Typed draw entries for a prefab: the resource's cached compiled_steps() (parsed once, shared by",
		"## every draw) when it exposes one, else a raw parse of any Resource's steps into the same shape.",
		"func _prefab_entries(prefab_res: Resource) -> Array:",
		"\tif prefab_res.has_method(\"compiled_steps\"):",
		"\t\tvar compiled: Variant = prefab_res.compiled_steps()",
		"\t\tif compiled is Array:",
		"\t\t\treturn compiled",
		"\tvar raw: Variant = prefab_res.get(\"steps\")",
		"\tif not (raw is Array):",
		"\t\treturn []",
		"\treturn DrawingPrefabResource.compile_steps(raw)",
		"",
		"",
		"# --- Paste: bake a live node's visual (or a whole layer's) onto the canvas as a decal. Texture-bearing",
		"# CanvasItems (Sprite2D, AnimatedSprite2D, TextureRect, or anything exposing a `texture`) stamp at their",
		"# exact world transform - rotation, scale, flip, region/frame and modulate preserved. Non-destructive: the",
		"# original node stays, so pair with a Destroy/Hide action to truly flatten a layer for performance. ---",
		"",
		"## Bakes one node's current visual onto the canvas at its own world transform. No-op for a node with no",
		"## resolvable texture (a plain Node2D, a TileMap - nothing to paste).",
		"func paste_node(node: Node) -> void:",
		"\tvar command: Dictionary = _node_paste_command(node, null)",
		"\tif not command.is_empty():",
		"\t\t_push(command)",
		"",
		"## Bakes a node's visual at an EXPLICIT spot (x, y read the same way as the other draw actions), scaled",
		"## and rotated - decouples the stamp from the node's own transform (paste an off-screen template).",
		"func paste_node_at(node: Node, x: float, y: float, scale_factor: float, rotation_deg: float) -> void:",
		"\tif not (node is Node2D):",
		"\t\treturn",
		"\tvar placed: Transform2D = Transform2D(deg_to_rad(rotation_deg), Vector2.ONE * maxf(scale_factor, 0.01), 0.0, Vector2(x, y))",
		"\tvar command: Dictionary = _node_paste_command(node, placed)",
		"\tif not command.is_empty():",
		"\t\t_push(command)",
		"",
		"## Bakes every visible texture-bearing CanvasItem under `layer` that is currently ON SCREEN (its world",
		"## rect intersects the camera's visible rectangle). `layer` is any parent - a CanvasLayer, a container,",
		"## or the scene root.",
		"func paste_layer_on_screen(layer: Node) -> void:",
		"\tvar view_rect: Rect2 = _visible_world_rect()",
		"\tif view_rect.size == Vector2.ZERO:",
		"\t\treturn",
		"\t_paste_layer_in_rect(layer, view_rect)",
		"",
		"## Bakes every visible texture-bearing CanvasItem under `layer` whose world rect intersects the box",
		"## Rect2(x, y, width, height), in WORLD coordinates - flatten a region regardless of the camera.",
		"func paste_layer_in_box(layer: Node, x: float, y: float, width: float, height: float) -> void:",
		"\t_paste_layer_in_rect(layer, Rect2(x, y, width, height))",
		"",
		"func _paste_layer_in_rect(layer: Node, world_rect: Rect2) -> void:",
		"\tif layer == null:",
		"\t\treturn",
		"\tfor item: CanvasItem in _descendant_canvas_items(layer):",
		"\t\tvar item_rect: Rect2 = _node_world_rect(item)",
		"\t\tif item_rect.size.x <= 0.0 or item_rect.size.y <= 0.0:",
		"\t\t\tcontinue",
		"\t\tif world_rect.intersects(item_rect):",
		"\t\t\tpaste_node(item)",
		"",
		"## Depth-first collect of every VISIBLE CanvasItem under root, skipping this surface's own drawer/display/",
		"## viewport so a layer paste never re-bakes the canvas onto itself. An invisible node prunes its subtree.",
		"func _descendant_canvas_items(root: Node) -> Array:",
		"\tvar out: Array = []",
		"\tfor child: Node in root.get_children():",
		"\t\tif child == self or child == _display or child == _viewport:",
		"\t\t\tcontinue",
		"\t\tif child is CanvasItem and not (child as CanvasItem).visible:",
		"\t\t\tcontinue",
		"\t\tif child is CanvasItem:",
		"\t\t\tout.append(child)",
		"\t\tout.append_array(_descendant_canvas_items(child))",
		"\treturn out",
		"",
		"## The camera's visible world rectangle (the screen corners mapped back through the canvas transform).",
		"## Zero when there is no viewport yet.",
		"func _visible_world_rect() -> Rect2:",
		"\tif _host == null or not _host.is_inside_tree():",
		"\t\treturn Rect2()",
		"\tvar vp: Viewport = _host.get_viewport()",
		"\tif vp == null:",
		"\t\treturn Rect2()",
		"\treturn _enclosing_rect(vp.get_canvas_transform().affine_inverse(), vp.get_visible_rect())",
		"",
		"## The world-space AABB of a node's drawable rect (its texture rect run through its global transform).",
		"## Zero when the node has no texture to paste.",
		"func _node_world_rect(node: CanvasItem) -> Rect2:",
		"\tvar info: Dictionary = _node_texture_info(node)",
		"\tif info.is_empty():",
		"\t\treturn Rect2()",
		"\treturn _enclosing_rect(node.get_global_transform(), info[\"dest_rect\"])",
		"",
		"## Axis-aligned rectangle enclosing the four corners of local_rect transformed by xform.",
		"func _enclosing_rect(xform: Transform2D, local_rect: Rect2) -> Rect2:",
		"\tvar c0: Vector2 = xform * local_rect.position",
		"\tvar c1: Vector2 = xform * (local_rect.position + Vector2(local_rect.size.x, 0.0))",
		"\tvar c2: Vector2 = xform * (local_rect.position + local_rect.size)",
		"\tvar c3: Vector2 = xform * (local_rect.position + Vector2(0.0, local_rect.size.y))",
		"\tvar min_p: Vector2 = c0.min(c1).min(c2).min(c3)",
		"\tvar max_p: Vector2 = c0.max(c1).max(c2).max(c3)",
		"\treturn Rect2(min_p, max_p - min_p)",
		"",
		"## Composes a node's world transform into canvas space and returns a \"node_stamp\" draw command, or {}",
		"## when the node has no resolvable texture. A Transform2D override places the stamp explicitly instead",
		"## of at the node's own transform.",
		"func _node_paste_command(node: Node, world_xform_override: Variant) -> Dictionary:",
		"\tif not (node is CanvasItem):",
		"\t\treturn {}",
		"\tvar info: Dictionary = _node_texture_info(node as CanvasItem)",
		"\tif info.is_empty():",
		"\t\treturn {}",
		"\tvar world_xform: Transform2D = (node as CanvasItem).get_global_transform()",
		"\tif world_xform_override is Transform2D:",
		"\t\tworld_xform = world_xform_override",
		"\t# World -> canvas is a pure translation (canvas centered on the host) in world mode, identity in canvas",
		"\t# mode, so composing it just remaps the origin - rotation, scale and flip carry through untouched.",
		"\tvar canvas_xform: Transform2D = world_xform",
		"\tcanvas_xform.origin = to_canvas(world_xform.origin)",
		"\tif bool(info[\"flip_h\"]) or bool(info[\"flip_v\"]):",
		"\t\tvar flip: Transform2D = Transform2D(Vector2(-1.0 if info[\"flip_h\"] else 1.0, 0.0), Vector2(0.0, -1.0 if info[\"flip_v\"] else 1.0), Vector2.ZERO)",
		"\t\tcanvas_xform = canvas_xform * flip",
		"\treturn {\"kind\": \"node_stamp\", \"texture\": info[\"texture\"], \"xform\": canvas_xform, \"src_rect\": info[\"src_rect\"], \"dest_rect\": info[\"dest_rect\"], \"modulate\": info[\"modulate\"]}",
		"",
		"## Pulls a drawable texture, source region, LOCAL destination rect, tint and flip flags from a node.",
		"## Handles Sprite2D (centered/offset/region/hframes/vframes/frame/flip), AnimatedSprite2D (current",
		"## frame), TextureRect (its rect), and any CanvasItem exposing a `texture` (drawn centered). {} when",
		"## there is nothing to draw.",
		"func _node_texture_info(node: CanvasItem) -> Dictionary:",
		"\tvar tint: Color = node.self_modulate * node.modulate",
		"\tif node is Sprite2D:",
		"\t\treturn _sprite_info(node as Sprite2D, tint)",
		"\tif node is AnimatedSprite2D:",
		"\t\treturn _animated_sprite_info(node as AnimatedSprite2D, tint)",
		"\tif node is TextureRect and (node as TextureRect).texture != null:",
		"\t\tvar rect_node: TextureRect = node as TextureRect",
		"\t\treturn {\"texture\": rect_node.texture, \"src_rect\": Rect2(), \"dest_rect\": Rect2(Vector2.ZERO, rect_node.size), \"modulate\": tint, \"flip_h\": false, \"flip_v\": false}",
		"\tvar generic: Variant = node.get(\"texture\")",
		"\tif generic is Texture2D:",
		"\t\tvar generic_tex: Texture2D = generic",
		"\t\treturn {\"texture\": generic_tex, \"src_rect\": Rect2(), \"dest_rect\": Rect2(-generic_tex.get_size() * 0.5, generic_tex.get_size()), \"modulate\": tint, \"flip_h\": false, \"flip_v\": false}",
		"\treturn {}",
		"",
		"## Sprite2D current frame -> {texture, src_rect, local dest_rect (centered/offset applied), tint, flip}.",
		"func _sprite_info(sprite: Sprite2D, tint: Color) -> Dictionary:",
		"\tif sprite.texture == null:",
		"\t\treturn {}",
		"\tvar tex: Texture2D = sprite.texture",
		"\tvar frame_size: Vector2 = tex.get_size()",
		"\tvar src: Rect2 = Rect2()",
		"\tif sprite.region_enabled:",
		"\t\tsrc = sprite.region_rect",
		"\t\tframe_size = src.size",
		"\telif sprite.hframes > 1 or sprite.vframes > 1:",
		"\t\tvar cols: int = maxi(sprite.hframes, 1)",
		"\t\tvar rows: int = maxi(sprite.vframes, 1)",
		"\t\tframe_size = Vector2(tex.get_width() / float(cols), tex.get_height() / float(rows))",
		"\t\tvar cell: int = sprite.frame",
		"\t\tsrc = Rect2(Vector2(cell % cols, (cell / cols) % rows) * frame_size, frame_size)",
		"\tvar dest_pos: Vector2 = sprite.offset",
		"\tif sprite.centered:",
		"\t\tdest_pos -= frame_size * 0.5",
		"\treturn {\"texture\": tex, \"src_rect\": src, \"dest_rect\": Rect2(dest_pos, frame_size), \"modulate\": tint, \"flip_h\": sprite.flip_h, \"flip_v\": sprite.flip_v}",
		"",
		"## AnimatedSprite2D current frame -> the same info shape, read from the SpriteFrames.",
		"func _animated_sprite_info(sprite: AnimatedSprite2D, tint: Color) -> Dictionary:",
		"\tvar frames: SpriteFrames = sprite.sprite_frames",
		"\tif frames == null or not frames.has_animation(sprite.animation):",
		"\t\treturn {}",
		"\tvar tex: Texture2D = frames.get_frame_texture(sprite.animation, sprite.frame)",
		"\tif tex == null:",
		"\t\treturn {}",
		"\tvar frame_size: Vector2 = tex.get_size()",
		"\tvar dest_pos: Vector2 = sprite.offset",
		"\tif sprite.centered:",
		"\t\tdest_pos -= frame_size * 0.5",
		"\treturn {\"texture\": tex, \"src_rect\": Rect2(), \"dest_rect\": Rect2(dest_pos, frame_size), \"modulate\": tint, \"flip_h\": sprite.flip_h, \"flip_v\": sprite.flip_v}",
		"# --- Dashed shapes: ONE dash primitive turns any polyline into disjoint dash segments, drawn in a",
		"# single draw_multiline call. Line = 2 points, ring = a sampled circle, rect = 4 closed corners - the",
		"# same routine serves all three and any future dashed shape. ---",
		"",
		"## Walks a polyline by arc length, carrying the dash phase across vertices so the rhythm stays",
		"## continuous around ring and rect corners, and returns endpoint PAIRS for draw_multiline. dash_len",
		"## is floored at 0.5 and gap at 0 so a zero-gap value degrades to a solid stroke, never an infinite loop.",
		"static func _dash_polyline(points: PackedVector2Array, dash_len: float, gap_len: float) -> PackedVector2Array:",
		"\tvar out: PackedVector2Array = PackedVector2Array()",
		"\tvar d: float = maxf(dash_len, 0.5)",
		"\tvar g: float = maxf(gap_len, 0.0)",
		"\tvar period: float = d + g",
		"\tif points.size() < 2 or period <= 0.0:",
		"\t\treturn out",
		"\tvar phase: float = 0.0",
		"\tfor i: int in range(points.size() - 1):",
		"\t\tvar a: Vector2 = points[i]",
		"\t\tvar b: Vector2 = points[i + 1]",
		"\t\tvar seg: Vector2 = b - a",
		"\t\tvar seg_len: float = seg.length()",
		"\t\tif seg_len <= 0.0001:",
		"\t\t\tcontinue",
		"\t\tvar dir: Vector2 = seg / seg_len",
		"\t\tvar t: float = 0.0",
		"\t\twhile t < seg_len:",
		"\t\t\tvar pos: float = fmod(phase + t, period)",
		"\t\t\tif pos < d:",
		"\t\t\t\tvar t_end: float = minf(t + (d - pos), seg_len)",
		"\t\t\t\tout.append(a + dir * t)",
		"\t\t\t\tout.append(a + dir * t_end)",
		"\t\t\t\tt = t_end",
		"\t\t\telse:",
		"\t\t\t\tt += period - pos",
		"\t\tphase = fmod(phase + seg_len, period)",
		"\treturn out",
		"",
		"## Dashes a polyline and pushes the segments as one multiline command (a single draw call).",
		"func _push_dashes(points: PackedVector2Array, dash_length: float, gap_length: float, width: float, color: Color) -> void:",
		"\tvar segments: PackedVector2Array = _dash_polyline(points, dash_length, gap_length)",
		"\tif segments.is_empty():",
		"\t\treturn",
		"\t_push({\"kind\": \"multiline\", \"points\": segments, \"color\": color, \"width\": maxf(width, 0.5)})",
		"",
		"func dashed_line(from_x: float, from_y: float, to_x: float, to_y: float, dash_length: float, gap_length: float, width: float, color: Color) -> void:",
		"\t_push_dashes(PackedVector2Array([to_canvas(Vector2(from_x, from_y)), to_canvas(Vector2(to_x, to_y))]), dash_length, gap_length, width, color)",
		"",
		"func dashed_ring(x: float, y: float, radius: float, dash_length: float, gap_length: float, width: float, color: Color) -> void:",
		"\tvar center: Vector2 = to_canvas(Vector2(x, y))",
		"\tvar points: PackedVector2Array = PackedVector2Array()",
		"\tfor i: int in 65:",
		"\t\tpoints.append(center + Vector2.from_angle(TAU * float(i) / 64.0) * radius)",
		"\t_push_dashes(points, dash_length, gap_length, width, color)",
		"",
		"func dashed_rect(x: float, y: float, width: float, height: float, dash_length: float, gap_length: float, line_width: float, color: Color) -> void:",
		"\tvar o: Vector2 = Vector2(x, y)",
		"\tvar corners: PackedVector2Array = PackedVector2Array([to_canvas(o), to_canvas(o + Vector2(width, 0.0)), to_canvas(o + Vector2(width, height)), to_canvas(o + Vector2(0.0, height)), to_canvas(o)])",
		"\t_push_dashes(corners, dash_length, gap_length, line_width, color)",
		"",
		"# --- Ribbons: Line2D children refreshed every physics frame - this update runs HERE, so the",
		"# behaviour no longer carries a per-frame GDScript loop. ---",
		"",
		"func start_ribbon(follow: Node, point_count: int, width: float, color: Color) -> void:",
		"\t_ensure()",
		"\tif _drawer == null or not (follow is Node2D):",
		"\t\treturn",
		"\tstop_ribbon(follow)",
		"\tvar ribbon_line: Line2D = Line2D.new()",
		"\tribbon_line.width = width",
		"\tribbon_line.default_color = color",
		"\tribbon_line.joint_mode = Line2D.LINE_JOINT_ROUND",
		"\tribbon_line.begin_cap_mode = Line2D.LINE_CAP_ROUND",
		"\tribbon_line.end_cap_mode = Line2D.LINE_CAP_ROUND",
		"\t_drawer.add_child(ribbon_line)",
		"\t_ribbons.append({\"id\": follow.get_instance_id(), \"line\": ribbon_line, \"trail\": [], \"length\": maxi(point_count, 2)})",
		"\t# A ribbon is refreshed every physics frame, so the first one buys the tick back.",
		"\tset_physics_process(true)",
		"",
		"func set_ribbon_texture(follow: Node, texture_res: Texture2D) -> void:",
		"\tif follow == null:",
		"\t\treturn",
		"\tfor ribbon: Dictionary in _ribbons:",
		"\t\tif int(ribbon[\"id\"]) == follow.get_instance_id() and is_instance_valid(ribbon[\"line\"]):",
		"\t\t\t(ribbon[\"line\"] as Line2D).texture = texture_res",
		"\t\t\t(ribbon[\"line\"] as Line2D).texture_mode = Line2D.LINE_TEXTURE_STRETCH",
		"",
		"func stop_ribbon(follow: Node) -> void:",
		"\tif follow == null:",
		"\t\treturn",
		"\tvar kept: Array = []",
		"\tfor ribbon: Dictionary in _ribbons:",
		"\t\tif int(ribbon[\"id\"]) == follow.get_instance_id():",
		"\t\t\tif is_instance_valid(ribbon[\"line\"]):",
		"\t\t\t\t(ribbon[\"line\"] as Line2D).queue_free()",
		"\t\telse:",
		"\t\t\tkept.append(ribbon)",
		"\t_ribbons = kept",
		"\tif _ribbons.is_empty():",
		"\t\tset_physics_process(false)",
		"",
		"func _physics_process(_delta: float) -> void:",
		"\tif _ribbons.is_empty() or _drawer == null:",
		"\t\treturn",
		"\tvar kept: Array = []",
		"\tfor ribbon: Dictionary in _ribbons:",
		"\t\tvar followed: Node2D = instance_from_id(int(ribbon[\"id\"])) as Node2D",
		"\t\tvar ribbon_line: Line2D = ribbon[\"line\"]",
		"\t\tif followed == null or not is_instance_valid(ribbon_line):",
		"\t\t\tif is_instance_valid(ribbon_line):",
		"\t\t\t\tribbon_line.queue_free()",
		"\t\t\tcontinue",
		"\t\tkept.append(ribbon)",
		"\t\tvar trail: Array = ribbon[\"trail\"]",
		"\t\ttrail.append(followed.global_position)",
		"\t\twhile trail.size() > int(ribbon[\"length\"]):",
		"\t\t\ttrail.pop_front()",
		"\t\tvar mapped: PackedVector2Array = PackedVector2Array()",
		"\t\tfor point: Variant in trail:",
		"\t\t\tmapped.append(to_canvas(point))",
		"\t\tribbon_line.points = mapped",
		"\t_ribbons = kept",
		"\t# The last ribbon's followed node was freed: nothing is left to refresh, so stop paying for",
		"\t# the frame until another Start Ribbon.",
		"\tif _ribbons.is_empty():",
		"\t\tset_physics_process(false)"
	]))
	sheet.events.append(block)

	# The draw style and the shapes drawn in it: a stack the canvas keeps, eleven more shapes, and
	# the instanced path that draws them through the Vector Shapes pack's own shader when it is
	# installed. Its own row, because it is its own idea - the rows above carry their width and
	# colour, and these read them from the style in force.
	var styled: RawCodeRow = RawCodeRow.new()
	styled.code = "\n".join(PackedStringArray([
		"# --- The draw style, and the shapes drawn in it ---",
		"#",
		"# A raster row carries its own width and colour, which is right for one line and wrong for thirty.",
		"# The rows below take neither: the canvas keeps a STYLE, they draw in it, and Push and Pop nest one",
		"# inside another so a debug overlay is a style and then its shapes.",
		"#",
		"# HOW THEY DRAW. When the Vector Shapes pack is installed and the canvas is redrawing every frame,",
		"# each styled shape goes into a MultiMesh per shape kind - one draw call for every arc in the frame",
		"# however many there are - wearing the same distance-field shader a placed shape wears. Without that",
		"# pack, and in the persistent mode that bakes strokes into the raster once, exactly the same shapes",
		"# are drawn the raster way instead. Nothing else changes: the same rows, the same numbers.",
		"",
		"## Where the shape shader the batches wear lives once the Vector Shapes pack is installed. Its",
		"## absence is not a fault - it is the canvas drawing the same shapes the raster way.",
		"const BATCH_SHADER_PATH: String = \"res://eventsheet_addons/vector_shapes/vector_shape_batch.gdshader\"",
		"",
		"## The shape kinds one MultiMesh each is filled with, in the order the batch shader numbers them.",
		"## A kind NOT in this list is always drawn the raster way: a polygon and a polyline are meshes",
		"## rather than a distance field, and text and a texture are neither.",
		"const BATCH_KINDS: PackedStringArray = [\"arc\", \"pie\", \"rounded_rect\", \"regular_polygon\", \"grid\", \"cross\", \"arrow\"]",
		"",
		"## What a draw style says, and what the canvas draws with before anything sets one. The keys are",
		"## spelled the way a Shape Style file spells them, so a style tuned on a placed shape is read here",
		"## unchanged and a resource that carries only some of them leaves the rest alone.",
		"const STYLE_DEFAULTS: Dictionary = {",
		"\t\"thickness\": 2.0,",
		"\t\"caps\": \"round\",",
		"\t\"colour\": Color.WHITE,",
		"\t\"colour_b\": Color.WHITE,",
		"\t\"colour_mode\": \"single\",",
		"\t\"filled\": false,",
		"\t\"dashed\": false,",
		"\t\"dash_space\": \"count\",",
		"\t\"dash_snap\": \"tiling\",",
		"\t\"dash_size\": 12.0,",
		"\t\"dash_count\": 12,",
		"\t\"dash_spacing\": 0.5,",
		"\t\"dash_style\": \"plain\"",
		"}",
		"",
		"## The cap words, the colour modes, the dash snaps and the dash ends, each in the shader's own",
		"## order - the position in the list IS the number the shader is handed.",
		"const CAP_WORDS: PackedStringArray = [\"none\", \"square\", \"round\"]",
		"const COLOUR_MODE_WORDS: PackedStringArray = [\"single\", \"two\", \"radial\", \"angular\", \"gradient\", \"per corner\"]",
		"const DASH_SNAP_WORDS: PackedStringArray = [\"off\", \"tiling\", \"end to end\"]",
		"const DASH_STYLE_WORDS: PackedStringArray = [\"plain\", \"angled\", \"rounded\"]",
		"",
		"## How wide the fade at a drawn edge is, in pixels. One number on both sides of the wire: the quad a",
		"## shape is drawn on is grown by it here, and the shader fades over it there.",
		"const ANTIALIAS_WIDTH: float = 1.0",
		"",
		"## How many segments a raster arc is drawn with when there is no shader to solve it per pixel.",
		"const RASTER_ARC_SEGMENTS: int = 64",
		"",
		"## How many draws a batch may sit out before its node is shelved for re-use, and how many shelved",
		"## nodes are kept. Both are small on purpose: a canvas that has finished with two hundred styles",
		"## must not go on paying for two hundred nodes, and a style that comes back a frame later must not",
		"## pay to rebuild one.",
		"const BATCH_IDLE_DRAWS: int = 2",
		"const BATCH_SHELF_LIMIT: int = 8",
		"",
		"# The style stack. The last entry is the style in force; an empty stack is the defaults above.",
		"var _styles: Array = []",
		"",
		"# One MultiMeshInstance2D per kind-and-style being drawn, kept and re-filled rather than rebuilt.",
		"# A frame that draws two hundred arcs in one style builds no node and no material; what it does",
		"# build is the plan the fill reads, which is a list of small dictionaries and is deliberately data",
		"# so the batching decision can be checked without a canvas at all.",
		"var _batches: Dictionary = {}",
		"",
		"# How many draws each batch has sat out. A STYLE IS PART OF THE KEY, and a style can be a colour",
		"# being tweened or a thickness that moves every frame, so the set of keys a canvas has ever drawn",
		"# is unbounded while the set it is drawing right now is not. A batch nothing has drawn for",
		"# BATCH_IDLE_DRAWS goes back on the shelf below instead of sitting in the SubViewport for ever.",
		"var _batch_idle: Dictionary = {}",
		"",
		"# Retired batch nodes, kept to be handed straight back out. A style that changes every frame gives",
		"# one back and claims one each draw, so the canvas settles at a handful of nodes rather than",
		"# growing one per frame for the life of the game.",
		"var _batch_shelf: Array = []",
		"",
		"# The style the cached keys below were worked out for, and one key per shape kind in it. The style",
		"# in force is ONE dictionary shared by every shape drawn in it, so the key it makes is too: this is",
		"# what keeps a frame of two hundred arcs from sorting the same thirteen field names two hundred",
		"# times. A shape that overrides a style field (a filled rounded rect) has a style of its own and",
		"# takes the plain path.",
		"var _key_style: Dictionary = {}",
		"var _keys_by_kind: Dictionary = {}",
		"",
		"# The shader every batch wears, loaded once per session, and whether we have looked for it yet.",
		"static var _batch_shader: Shader = null",
		"static var _batch_shader_sought: bool = false",
		"",
		"# The unit quad every batch instances, built once per session.",
		"static var _batch_mesh: ArrayMesh = null",
		"",
		"## The style the next drawn shape will wear.",
		"func current_style() -> Dictionary:",
		"\tif _styles.is_empty():",
		"\t\treturn STYLE_DEFAULTS.duplicate()",
		"\treturn _styles[_styles.size() - 1]",
		"",
		"## Replaces the style in force. Every styled row after this one draws in it until it is replaced,",
		"## popped or reset. A null style is the canvas's own defaults.",
		"func set_draw_style(style: Resource) -> void:",
		"\tvar fields: Dictionary = style_fields(style)",
		"\tif _styles.is_empty():",
		"\t\t_styles.append(fields)",
		"\telse:",
		"\t\t_styles[_styles.size() - 1] = fields",
		"",
		"## Sets a style with the one in force kept underneath it, to come back on Pop Draw Style.",
		"func push_draw_style(style: Resource) -> void:",
		"\t_styles.append(style_fields(style))",
		"",
		"## Goes back to the style that was in force before the last Push Draw Style.",
		"func pop_draw_style() -> void:",
		"\tif not _styles.is_empty():",
		"\t\t_styles.remove_at(_styles.size() - 1)",
		"",
		"## Drops the whole stack: the canvas draws in its own defaults again.",
		"func reset_draw_style() -> void:",
		"\t_styles.clear()",
		"",
		"## One style resource read as the fields the canvas draws with. Read BY NAME rather than by class,",
		"## so a Shape Style file, a shape node's own style or a project's own resource with the same field",
		"## names all work, and a resource that has not got a field leaves that field alone.",
		"static func style_fields(style: Resource) -> Dictionary:",
		"\tvar fields: Dictionary = STYLE_DEFAULTS.duplicate()",
		"\tif style == null:",
		"\t\treturn fields",
		"\tfor key: String in STYLE_DEFAULTS:",
		"\t\tvar value: Variant = style.get(key)",
		"\t\tif value == null:",
		"\t\t\tcontinue",
		"\t\tif typeof(value) == typeof(fields[key]):",
		"\t\t\tfields[key] = value",
		"\t\telif (value is float or value is int) and (fields[key] is float or fields[key] is int):",
		"\t\t\tfields[key] = float(value) if fields[key] is float else int(value)",
		"\treturn fields",
		"",
		"## Draws an arc of a circle in the current style: a cooldown sweep, a health ring, a turn radius.",
		"func draw_arc_shape(x: float, y: float, radius: float, from_degrees: float, to_degrees: float) -> void:",
		"\t_push_shape(\"arc\", Vector2(x, y), 0.0, Vector4(radius, 0.0, deg_to_rad(from_degrees), deg_to_rad(maxf(to_degrees, from_degrees))), {})",
		"",
		"## Draws a filled wedge of a circle in the current style - the same two angles as an arc, filled in.",
		"func draw_pie(x: float, y: float, radius: float, from_degrees: float, to_degrees: float) -> void:",
		"\t_push_shape(\"pie\", Vector2(x, y), 0.0, Vector4(radius, 0.0, deg_to_rad(from_degrees), deg_to_rad(maxf(to_degrees, from_degrees))), {})",
		"",
		"## Draws a rectangle with rounded corners, from its CENTRE, filled or as an outline.",
		"func draw_rounded_rect(x: float, y: float, width: float, height: float, corner_radius: float, filled: bool) -> void:",
		"\t_push_shape(\"rounded_rect\", Vector2(x, y), 0.0, Vector4(width * 0.5, height * 0.5, maxf(corner_radius, 0.0), 0.0), {\"filled\": filled})",
		"",
		"## Draws a shape of N equal sides at a radius, from its centre - a hexagon grid cell, a warning",
		"## triangle, a stop sign.",
		"func draw_regular_polygon(x: float, y: float, radius: float, sides: int, angle_degrees: float, filled: bool) -> void:",
		"\t_push_shape(\"regular_polygon\", Vector2(x, y), 0.0, Vector4(radius, float(maxi(sides, 3)), deg_to_rad(angle_degrees), 0.0), {\"filled\": filled})",
		"",
		"## Draws a grid of rulings filling a box, from its centre - the level editor's floor, the debug",
		"## overlay's ruler.",
		"func draw_grid(x: float, y: float, width: float, height: float, cell_size: float) -> void:",
		"\t_push_shape(\"grid\", Vector2(x, y), 0.0, Vector4(width * 0.5, height * 0.5, maxf(cell_size, 1.0), 0.0), {})",
		"",
		"## Draws a cross - the marker on a spot, the \"no\" over a placement.",
		"func draw_cross(x: float, y: float, arm_length: float, angle_degrees: float) -> void:",
		"\t_push_shape(\"cross\", Vector2(x, y), deg_to_rad(angle_degrees), Vector4(maxf(arm_length, 0.01), 0.0, 0.0, 0.0), {})",
		"",
		"## Draws an arrow from one point to another, its head sized in pixels - a force, a facing, a route.",
		"func draw_arrow(from_x: float, from_y: float, to_x: float, to_y: float, head_size: float) -> void:",
		"\tvar from_point: Vector2 = Vector2(from_x, from_y)",
		"\tvar to_point: Vector2 = Vector2(to_x, to_y)",
		"\tvar span: Vector2 = to_point - from_point",
		"\tvar head: float = maxf(head_size, 1.0)",
		"\t_push_shape(\"arrow\", (from_point + to_point) * 0.5, span.angle(), Vector4(maxf(span.length() * 0.5, 0.01), head, head, 0.0), {})",
		"",
		"## Draws a closed outline through a list of positions, filled or hollow. A polygon is a mesh rather",
		"## than a distance field, so it is drawn the raster way whatever else the frame is doing.",
		"func draw_polygon_shape(points: Array, filled: bool) -> void:",
		"\t_push_shape(\"polygon\", Vector2.ZERO, 0.0, Vector4.ZERO, {\"filled\": filled, \"points\": _as_points(points)})",
		"",
		"## Draws a path through a list of positions, open or closed - a route preview, a drawn trail.",
		"func draw_polyline_shape(points: Array, closed: bool) -> void:",
		"\t_push_shape(\"polyline\", Vector2.ZERO, 0.0, Vector4.ZERO, {\"closed\": closed, \"points\": _as_points(points)})",
		"",
		"## Draws a line of text at a spot, in the style's own colour - a state name over an enemy, a number",
		"## over a tile.",
		"func draw_text(message: String, x: float, y: float, size: float) -> void:",
		"\t_push_shape(\"text\", Vector2(x, y), 0.0, Vector4(maxf(size, 1.0), 0.0, 0.0, 0.0), {\"message\": message})",
		"",
		"## Draws a texture stretched into a box, from its centre, tinted by the style's colour.",
		"func draw_texture_in_rect(texture_res: Texture2D, x: float, y: float, width: float, height: float) -> void:",
		"\t_push_shape(\"texture\", Vector2(x, y), 0.0, Vector4(width * 0.5, height * 0.5, 0.0, 0.0), {\"texture\": texture_res})",
		"",
		"## One styled shape, queued the way every other draw is. The style is COPIED onto the command, so a",
		"## shape drawn now and the same shape drawn after the style changed keep their own looks. Anything",
		"## in `extra` that a style speaks for joins the style; everything else (a list of points, a message,",
		"## a texture) rides the command, where it belongs to that one shape.",
		"func _push_shape(kind: String, at: Vector2, angle: float, numbers: Vector4, extra: Dictionary) -> void:",
		"\t_ensure()",
		"\t# The style in force rides the command AS IT IS. Nothing ever edits a stored style in place -",
		"\t# Set, Push, Pop and Reset each replace one - so a hundred shapes drawn in one style share the",
		"\t# one dictionary, and only a shape that has to CHANGE a field takes a copy of its own.",
		"\tvar style: Dictionary = _style_in_force()",
		"\tvar own_style: bool = false",
		"\tvar command: Dictionary = {\"kind\": kind, \"styled\": true, \"at\": to_canvas(at), \"angle\": angle, \"numbers\": numbers}",
		"\tfor key: String in extra:",
		"\t\tif STYLE_DEFAULTS.has(key):",
		"\t\t\tif not own_style:",
		"\t\t\t\tstyle = style.duplicate()",
		"\t\t\t\town_style = true",
		"\t\t\tstyle[key] = extra[key]",
		"\t\telse:",
		"\t\t\tcommand[key] = extra[key]",
		"\tcommand[\"style\"] = style",
		"\tif _use_batches() and BATCH_KINDS.has(kind):",
		"\t\t# Worked out once here and carried on the command, because the plan and the raster fallback",
		"\t\t# each ask for it again and a key is a sort and a dozen joins.",
		"\t\tvar shape_key: String = _batch_key_in_force(kind, style, own_style)",
		"\t\tcommand[\"batch_key\"] = shape_key",
		"\t\t_reserve_batch(shape_key)",
		"\t_push(command)",
		"",
		"## The style in force WITHOUT a copy, for the queueing path above. current_style() is the public",
		"## reading and still hands back a copy, because a caller that edited what it got back would be",
		"## editing the canvas's own defaults - which are a constant.",
		"func _style_in_force() -> Dictionary:",
		"\tif _styles.is_empty():",
		"\t\treturn STYLE_DEFAULTS",
		"\treturn _styles[_styles.size() - 1]",
		"",
		"## One shape's batch key, cached per style. The style in force is one dictionary shared by every",
		"## shape drawn in it, so its key per kind is worked out on the first shape and read by the rest; a",
		"## shape carrying a style of its own is spelled out the plain way, once.",
		"func _batch_key_in_force(kind: String, style: Dictionary, own_style: bool) -> String:",
		"\tif own_style:",
		"\t\treturn batch_key(kind, style)",
		"\tif not is_same(style, _key_style):",
		"\t\t_key_style = style",
		"\t\t_keys_by_kind.clear()",
		"\tif not _keys_by_kind.has(kind):",
		"\t\t_keys_by_kind[kind] = batch_key(kind, style)",
		"\treturn str(_keys_by_kind[kind])",
		"",
		"## A list of positions as points on the canvas, however the row spelled them.",
		"func _as_points(points: Array) -> PackedVector2Array:",
		"\tvar out: PackedVector2Array = PackedVector2Array()",
		"\tfor entry: Variant in points:",
		"\t\tif entry is Vector2:",
		"\t\t\tout.append(to_canvas(entry))",
		"\treturn out",
		"",
		"## Whether this frame's styled shapes go through the instanced path. Two things say yes: the Vector",
		"## Shapes pack is installed, so there is a shader to draw them with, and the canvas redraws every",
		"## frame - a PERSISTENT canvas bakes its strokes into the raster once, which is the whole point of",
		"## it, and a MultiMesh re-drawn into a surface that never clears would pile up on itself.",
		"func _use_batches() -> bool:",
		"\treturn auto_clear and batch_shader() != null",
		"",
		"## The shader every batch wears, loaded once per session. Null when the Vector Shapes pack is not",
		"## installed, which is what sends the same shapes down the raster path.",
		"static func batch_shader() -> Shader:",
		"\tif not _batch_shader_sought:",
		"\t\t_batch_shader_sought = true",
		"\t\tif ResourceLoader.exists(BATCH_SHADER_PATH):",
		"\t\t\t_batch_shader = load(BATCH_SHADER_PATH)",
		"\treturn _batch_shader",
		"",
		"## The unit quad every instanced shape is drawn on, from -1 to 1 with its UV over the same square,",
		"## built once per session. The instance transform scales it to the shape's own reach.",
		"static func batch_mesh() -> ArrayMesh:",
		"\tif _batch_mesh != null:",
		"\t\treturn _batch_mesh",
		"\tvar arrays: Array = []",
		"\tarrays.resize(Mesh.ARRAY_MAX)",
		"\tarrays[Mesh.ARRAY_VERTEX] = PackedVector2Array([Vector2(-1.0, -1.0), Vector2(1.0, -1.0), Vector2(1.0, 1.0), Vector2(-1.0, 1.0)])",
		"\tarrays[Mesh.ARRAY_TEX_UV] = PackedVector2Array([Vector2(0.0, 0.0), Vector2(1.0, 0.0), Vector2(1.0, 1.0), Vector2(0.0, 1.0)])",
		"\tarrays[Mesh.ARRAY_INDEX] = PackedInt32Array([0, 1, 2, 0, 2, 3])",
		"\t_batch_mesh = ArrayMesh.new()",
		"\t_batch_mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)",
		"\treturn _batch_mesh",
		"",
		"## Which batch a styled command belongs in: its kind and the style it was drawn in. Two arcs in one",
		"## style are one draw; the same two in two styles are two, because a style is shader uniforms.",
		"static func batch_key(kind: String, style: Dictionary) -> String:",
		"\tvar keys: Array = style.keys()",
		"\tkeys.sort()",
		"\tvar parts: PackedStringArray = PackedStringArray([kind])",
		"\tfor key: String in keys:",
		"\t\tparts.append(\"%s=%s\" % [key, style[key]])",
		"\treturn \"|\".join(parts)",
		"",
		"## This frame's instanced draws: one entry per kind-and-style, in the order the frame first drew",
		"## each, holding every instance of it. This is the whole of the batching decision, and it is a plain",
		"## reading of the queue so it can be checked without a canvas at all.",
		"static func plan_batches(commands: Array) -> Array:",
		"\tvar order: PackedStringArray = PackedStringArray()",
		"\tvar by_key: Dictionary = {}",
		"\tfor command: Dictionary in commands:",
		"\t\tif not bool(command.get(\"styled\", false)):",
		"\t\t\tcontinue",
		"\t\tvar kind: String = str(command.get(\"kind\", \"\"))",
		"\t\tif not BATCH_KINDS.has(kind):",
		"\t\t\tcontinue",
		"\t\tvar style: Dictionary = command.get(\"style\", {})",
		"\t\tvar key: String = str(command[\"batch_key\"]) if command.has(\"batch_key\") else batch_key(kind, style)",
		"\t\tif not by_key.has(key):",
		"\t\t\tby_key[key] = {\"key\": key, \"kind\": kind, \"kind_id\": BATCH_KINDS.find(kind), \"style\": style, \"instances\": []}",
		"\t\t\torder.append(key)",
		"\t\tvar instances: Array = by_key[key][\"instances\"]",
		"\t\tinstances.append({",
		"\t\t\t\"at\": command[\"at\"],",
		"\t\t\t\"angle\": float(command[\"angle\"]),",
		"\t\t\t\"numbers\": command[\"numbers\"],",
		"\t\t\t\"extent\": batch_extent(kind, command[\"numbers\"], style)",
		"\t\t})",
		"\tvar plan: Array = []",
		"\tfor key: String in order:",
		"\t\tplan.append(by_key[key])",
		"\treturn plan",
		"",
		"## How far a shape reaches from its own centre, in pixels: how big the quad it is instanced onto",
		"## has to be. THE BATCH SHADER WORKS THE SAME NUMBER OUT from the same four numbers, and the two",
		"## must agree - a quad smaller than its shape clips it.",
		"static func batch_extent(kind: String, numbers: Vector4, style: Dictionary) -> float:",
		"\tvar margin: float = maxf(float(style.get(\"thickness\", 2.0)), 0.01) * 0.5 + ANTIALIAS_WIDTH + 2.0",
		"\tif kind == \"rounded_rect\" or kind == \"grid\":",
		"\t\treturn maxf(absf(numbers.x), absf(numbers.y)) + margin",
		"\tif kind == \"arrow\":",
		"\t\treturn maxf(absf(numbers.x), absf(numbers.z)) + margin",
		"\treturn absf(numbers.x) + margin",
		"",
		"## This frame's raster draws, in the order they were queued: every command that is not a styled",
		"## shape exactly as it was pushed, and every styled shape turned into the one primitive that draws",
		"## it. `taken` holds the batch keys the MultiMesh path has already claimed this frame, so a shape",
		"## whose batch could not be built is still drawn rather than silently dropped.",
		"static func plan_raster(commands: Array, taken: Dictionary) -> Array:",
		"\tvar out: Array = []",
		"\tfor command: Dictionary in commands:",
		"\t\tif not bool(command.get(\"styled\", false)):",
		"\t\t\tout.append(command)",
		"\t\t\tcontinue",
		"\t\tvar key: String = str(command[\"batch_key\"]) if command.has(\"batch_key\") else batch_key(str(command.get(\"kind\", \"\")), command.get(\"style\", {}))",
		"\t\tif taken.has(key):",
		"\t\t\tcontinue",
		"\t\tvar drawn: Dictionary = raster_shape(command)",
		"\t\tif not drawn.is_empty():",
		"\t\t\tout.append(drawn)",
		"\treturn out",
		"",
		"## One styled shape as the raster primitive that draws it - the same shape, solved on the CPU. The",
		"## dash pattern the shader would have cut is walked by the shared dash primitive instead, so a",
		"## dashed arc is dashed either way.",
		"static func raster_shape(command: Dictionary) -> Dictionary:",
		"\tvar style: Dictionary = command.get(\"style\", {})",
		"\tvar colour: Color = style.get(\"colour\", Color.WHITE)",
		"\tvar width: float = maxf(float(style.get(\"thickness\", 2.0)), 0.5)",
		"\tvar filled: bool = bool(style.get(\"filled\", false))",
		"\tvar at: Vector2 = command.get(\"at\", Vector2.ZERO)",
		"\tvar numbers: Vector4 = command.get(\"numbers\", Vector4.ZERO)",
		"\tmatch str(command.get(\"kind\", \"\")):",
		"\t\t\"arc\":",
		"\t\t\tif bool(style.get(\"dashed\", false)):",
		"\t\t\t\treturn {\"kind\": \"multiline\", \"points\": dashed_walk(arc_points(at, numbers.x, numbers.z, numbers.w), false, style), \"width\": width, \"color\": colour}",
		"\t\t\treturn {\"kind\": \"arc\", \"at\": at, \"radius\": numbers.x, \"from\": numbers.z, \"to\": numbers.w, \"width\": width, \"color\": colour}",
		"\t\t\"pie\":",
		"\t\t\tvar wedge: PackedVector2Array = PackedVector2Array([at])",
		"\t\t\tfor step: int in 33:",
		"\t\t\t\twedge.append(at + Vector2.from_angle(lerpf(numbers.z, numbers.w, float(step) / 32.0)) * numbers.x)",
		"\t\t\treturn {\"kind\": \"polygon\", \"points\": wedge, \"color\": colour}",
		"\t\t\"rounded_rect\":",
		"\t\t\tvar outline: PackedVector2Array = rounded_rect_points(at, Vector2(numbers.x, numbers.y), numbers.z)",
		"\t\t\tif filled:",
		"\t\t\t\treturn {\"kind\": \"polygon\", \"points\": outline, \"color\": colour}",
		"\t\t\tif bool(style.get(\"dashed\", false)):",
		"\t\t\t\treturn {\"kind\": \"multiline\", \"points\": dashed_walk(outline, true, style), \"width\": width, \"color\": colour}",
		"\t\t\toutline.append(outline[0])",
		"\t\t\treturn {\"kind\": \"polyline\", \"points\": outline, \"width\": width, \"color\": colour}",
		"\t\t\"regular_polygon\":",
		"\t\t\tvar corners: PackedVector2Array = regular_polygon_points(at, numbers.x, int(numbers.y), numbers.z)",
		"\t\t\tif filled:",
		"\t\t\t\treturn {\"kind\": \"polygon\", \"points\": corners, \"color\": colour}",
		"\t\t\tif bool(style.get(\"dashed\", false)):",
		"\t\t\t\treturn {\"kind\": \"multiline\", \"points\": dashed_walk(corners, true, style), \"width\": width, \"color\": colour}",
		"\t\t\tcorners.append(corners[0])",
		"\t\t\treturn {\"kind\": \"polyline\", \"points\": corners, \"width\": width, \"color\": colour}",
		"\t\t\"grid\":",
		"\t\t\treturn {\"kind\": \"multiline\", \"points\": grid_points(at, Vector2(numbers.x, numbers.y), numbers.z), \"width\": width, \"color\": colour}",
		"\t\t\"cross\":",
		"\t\t\tvar arm: Vector2 = Vector2(numbers.x, 0.0).rotated(float(command.get(\"angle\", 0.0)))",
		"\t\t\tvar down: Vector2 = arm.orthogonal()",
		"\t\t\treturn {\"kind\": \"multiline\", \"points\": PackedVector2Array([at - arm, at + arm, at - down, at + down]), \"width\": width, \"color\": colour}",
		"\t\t\"arrow\":",
		"\t\t\treturn {\"kind\": \"multiline\", \"points\": arrow_points(at, float(command.get(\"angle\", 0.0)), numbers.x, numbers.y, numbers.z), \"width\": width, \"color\": colour}",
		"\t\t\"polygon\":",
		"\t\t\tvar points: PackedVector2Array = command.get(\"points\", PackedVector2Array())",
		"\t\t\tif points.size() < 3:",
		"\t\t\t\treturn {}",
		"\t\t\tif filled:",
		"\t\t\t\treturn {\"kind\": \"polygon\", \"points\": points, \"color\": colour}",
		"\t\t\tif bool(style.get(\"dashed\", false)):",
		"\t\t\t\treturn {\"kind\": \"multiline\", \"points\": dashed_walk(points, true, style), \"width\": width, \"color\": colour}",
		"\t\t\tvar ring: PackedVector2Array = points.duplicate()",
		"\t\t\tring.append(ring[0])",
		"\t\t\treturn {\"kind\": \"polyline\", \"points\": ring, \"width\": width, \"color\": colour}",
		"\t\t\"polyline\":",
		"\t\t\tvar path: PackedVector2Array = command.get(\"points\", PackedVector2Array())",
		"\t\t\tif path.size() < 2:",
		"\t\t\t\treturn {}",
		"\t\t\tvar loop: bool = bool(command.get(\"closed\", false))",
		"\t\t\tif bool(style.get(\"dashed\", false)):",
		"\t\t\t\treturn {\"kind\": \"multiline\", \"points\": dashed_walk(path, loop, style), \"width\": width, \"color\": colour}",
		"\t\t\tvar walk: PackedVector2Array = path.duplicate()",
		"\t\t\tif loop:",
		"\t\t\t\twalk.append(walk[0])",
		"\t\t\treturn {\"kind\": \"polyline\", \"points\": walk, \"width\": width, \"color\": colour}",
		"\t\t\"text\":",
		"\t\t\treturn {\"kind\": \"text\", \"at\": at, \"message\": str(command.get(\"message\", \"\")), \"size\": numbers.x, \"color\": colour}",
		"\t\t\"texture\":",
		"\t\t\treturn {\"kind\": \"texture_rect\", \"texture\": command.get(\"texture\"), \"rect\": Rect2(at - Vector2(numbers.x, numbers.y), Vector2(numbers.x, numbers.y) * 2.0), \"color\": colour}",
		"\treturn {}",
		"",
		"## An arc as points. The dash primitive walks points, and an arc the shader would have solved per",
		"## pixel has none, so the raster half samples one.",
		"static func arc_points(at: Vector2, radius: float, from_angle: float, to_angle: float) -> PackedVector2Array:",
		"\tvar out: PackedVector2Array = PackedVector2Array()",
		"\tfor step: int in RASTER_ARC_SEGMENTS + 1:",
		"\t\tout.append(at + Vector2.from_angle(lerpf(from_angle, to_angle, float(step) / float(RASTER_ARC_SEGMENTS))) * radius)",
		"\treturn out",
		"",
		"## One outline cut into dashes by the style in force - the SAME pattern the shader cuts, walked on",
		"## the CPU by the dash primitive the canvas already uses for its dashed line, ring and rect. In count",
		"## mode the period is the outline's own length divided by the count, which is what makes a dashed",
		"## ring of any radius carry the number of dashes it was asked for.",
		"static func dashed_walk(points: PackedVector2Array, closed: bool, style: Dictionary) -> PackedVector2Array:",
		"\tvar walk: PackedVector2Array = points.duplicate()",
		"\tif closed and walk.size() > 1:",
		"\t\twalk.append(walk[0])",
		"\tvar space: String = str(style.get(\"dash_space\", \"count\"))",
		"\tvar thickness: float = maxf(float(style.get(\"thickness\", 2.0)), 0.01)",
		"\tvar dash: float = maxf(float(style.get(\"dash_size\", 12.0)), 0.5)",
		"\tvar gap: float = maxf(float(style.get(\"dash_spacing\", 6.0)), 0.0)",
		"\tif space == \"count\":",
		"\t\tvar total: float = 0.0",
		"\t\tfor index: int in maxi(walk.size() - 1, 0):",
		"\t\t\ttotal += walk[index].distance_to(walk[index + 1])",
		"\t\tvar period: float = total / maxf(float(int(style.get(\"dash_count\", 12))), 1.0)",
		"\t\tgap = period * clampf(float(style.get(\"dash_spacing\", 0.5)), 0.0, 0.95)",
		"\t\tdash = maxf(period - gap, 0.5)",
		"\telif space == \"relative\":",
		"\t\tdash *= thickness",
		"\t\tgap *= thickness",
		"\treturn _dash_polyline(walk, dash, gap)",
		"",
		"## The outline of a rounded rectangle centred on a point, as points - what the raster half draws",
		"## when there is no shader to solve the corner per pixel.",
		"static func rounded_rect_points(at: Vector2, half_size: Vector2, corner: float) -> PackedVector2Array:",
		"\tvar out: PackedVector2Array = PackedVector2Array()",
		"\tvar radius: float = clampf(corner, 0.0, minf(half_size.x, half_size.y))",
		"\tvar centres: Array = [",
		"\t\tVector2(half_size.x - radius, half_size.y - radius),",
		"\t\tVector2(-half_size.x + radius, half_size.y - radius),",
		"\t\tVector2(-half_size.x + radius, -half_size.y + radius),",
		"\t\tVector2(half_size.x - radius, -half_size.y + radius)",
		"\t]",
		"\tfor quadrant: int in 4:",
		"\t\tvar start: float = float(quadrant) * PI * 0.5",
		"\t\tfor step: int in 5:",
		"\t\t\tout.append(at + centres[quadrant] + Vector2.from_angle(start + PI * 0.5 * float(step) / 4.0) * radius)",
		"\treturn out",
		"",
		"## The corners of a shape of N equal sides, centred on a point.",
		"static func regular_polygon_points(at: Vector2, radius: float, sides: int, angle: float) -> PackedVector2Array:",
		"\tvar out: PackedVector2Array = PackedVector2Array()",
		"\tvar count: int = maxi(sides, 3)",
		"\tfor corner: int in count:",
		"\t\tout.append(at + Vector2.from_angle(angle + TAU * float(corner) / float(count)) * radius)",
		"\treturn out",
		"",
		"## The rulings of a grid filling a box, as the endpoint pairs one draw call takes.",
		"static func grid_points(at: Vector2, half_size: Vector2, cell: float) -> PackedVector2Array:",
		"\tvar out: PackedVector2Array = PackedVector2Array()",
		"\tvar step: float = maxf(cell, 1.0)",
		"\tvar across: int = mini(int(half_size.x / step), 512)",
		"\tvar down: int = mini(int(half_size.y / step), 512)",
		"\tfor index: int in range(-across, across + 1):",
		"\t\tvar x: float = at.x + float(index) * step",
		"\t\tout.append(Vector2(x, at.y - half_size.y))",
		"\t\tout.append(Vector2(x, at.y + half_size.y))",
		"\tfor index: int in range(-down, down + 1):",
		"\t\tvar y: float = at.y + float(index) * step",
		"\t\tout.append(Vector2(at.x - half_size.x, y))",
		"\t\tout.append(Vector2(at.x + half_size.x, y))",
		"\treturn out",
		"",
		"## An arrow's shaft and the two sides of its head, as the endpoint pairs one draw call takes.",
		"static func arrow_points(at: Vector2, angle: float, half_length: float, head: float, head_width: float) -> PackedVector2Array:",
		"\tvar tip: Vector2 = at + Vector2(half_length, 0.0).rotated(angle)",
		"\tvar tail: Vector2 = at - Vector2(half_length, 0.0).rotated(angle)",
		"\tvar base: Vector2 = at + Vector2(half_length - head, 0.0).rotated(angle)",
		"\tvar side: Vector2 = Vector2(0.0, head_width * 0.5).rotated(angle)",
		"\treturn PackedVector2Array([tail, tip, base - side, tip, base + side, tip])",
		"",
		"## Makes sure a batch has somewhere to draw: one MultiMeshInstance2D per kind-and-style, taken off",
		"## the shelf if a retired one is waiting and built otherwise, then re-filled every draw after.",
		"## Called as a shape is QUEUED, never while the canvas is drawing, so nothing joins the tree",
		"## mid-draw.",
		"func _reserve_batch(key: String) -> void:",
		"\tif _batches.has(key) or _viewport == null:",
		"\t\treturn",
		"\tvar node: MultiMeshInstance2D = null",
		"\twhile node == null and not _batch_shelf.is_empty():",
		"\t\tvar shelved: Variant = _batch_shelf.pop_back()",
		"\t\tif is_instance_valid(shelved):",
		"\t\t\tnode = shelved",
		"\tif node == null:",
		"\t\tvar holder: MultiMesh = MultiMesh.new()",
		"\t\tholder.transform_format = MultiMesh.TRANSFORM_2D",
		"\t\tholder.use_custom_data = true",
		"\t\tholder.mesh = batch_mesh()",
		"\t\tnode = MultiMeshInstance2D.new()",
		"\t\tnode.multimesh = holder",
		"\t\tvar shaded: ShaderMaterial = ShaderMaterial.new()",
		"\t\tshaded.shader = batch_shader()",
		"\t\tnode.material = shaded",
		"\t\t_viewport.add_child(node)",
		"\tnode.visible = true",
		"\t_batches[key] = node",
		"\t_batch_idle[key] = 0",
		"",
		"## Fills this draw's batches, empties the ones it did not draw so a kind that has stopped being",
		"## drawn stops appearing, and RETIRES the ones nothing has drawn for a few draws in a row. That",
		"## last part is the whole reason this is not a dictionary that only grows: a batch is keyed by its",
		"## style's own values, so a colour being tweened onto Set Draw Style, or a Push Draw Style handed a",
		"## fresh resource each tick, mints a key a frame - and would otherwise leave a node behind in the",
		"## SubViewport for every one of them, for the life of the canvas.",
		"func _fill_batches(plan: Array) -> void:",
		"\tvar drawn: Dictionary = {}",
		"\tfor batch: Dictionary in plan:",
		"\t\tvar key: String = str(batch[\"key\"])",
		"\t\tif not _batches.has(key):",
		"\t\t\tcontinue",
		"\t\tdrawn[key] = true",
		"\t\tvar node: MultiMeshInstance2D = _batches[key]",
		"\t\t_push_style_uniforms(node.material, batch[\"style\"], int(batch[\"kind_id\"]))",
		"\t\tvar holder: MultiMesh = node.multimesh",
		"\t\tvar instances: Array = batch[\"instances\"]",
		"\t\tholder.instance_count = instances.size()",
		"\t\tfor index: int in instances.size():",
		"\t\t\tvar instance: Dictionary = instances[index]",
		"\t\t\tvar extent: float = float(instance[\"extent\"])",
		"\t\t\tholder.set_instance_transform_2d(index, Transform2D(float(instance[\"angle\"]), Vector2(extent, extent), 0.0, instance[\"at\"]))",
		"\t\t\tvar numbers: Vector4 = instance[\"numbers\"]",
		"\t\t\tholder.set_instance_custom_data(index, Color(numbers.x, numbers.y, numbers.z, numbers.w))",
		"\tfor key: String in _batches:",
		"\t\tif drawn.has(key):",
		"\t\t\t_batch_idle[key] = 0",
		"\t\t\tcontinue",
		"\t\t(_batches[key] as MultiMeshInstance2D).multimesh.instance_count = 0",
		"\t\t_batch_idle[key] = int(_batch_idle.get(key, 0)) + 1",
		"\tfor key: String in batches_to_retire(_batch_idle, drawn):",
		"\t\t_shelve_batch(key)",
		"",
		"## Which batches a draw retires: the ones it did not draw, once each has sat out more draws than",
		"## BATCH_IDLE_DRAWS. A plain reading of two dictionaries, and static, so the rule can be checked",
		"## without a canvas at all - which matters here, because the thing it prevents (one more node in",
		"## the SubViewport every frame, for ever) is invisible until a game has been running a while.",
		"static func batches_to_retire(idle: Dictionary, drawn: Dictionary) -> PackedStringArray:",
		"\tvar retired: PackedStringArray = PackedStringArray()",
		"\tfor key: String in idle:",
		"\t\tif not drawn.has(key) and int(idle[key]) > BATCH_IDLE_DRAWS:",
		"\t\t\tretired.append(key)",
		"\tretired.sort()",
		"\treturn retired",
		"",
		"## Takes a batch nothing is drawing off its key and puts its node on the shelf to be handed out",
		"## again. The node stays a child of the SubViewport - hidden and emptied - so claiming it back",
		"## costs nothing at all; past the shelf's limit it is freed instead, because a canvas that has",
		"## finished with two hundred styles should not go on holding two hundred nodes.",
		"func _shelve_batch(key: String) -> void:",
		"\tvar node: MultiMeshInstance2D = _batches[key]",
		"\t_batches.erase(key)",
		"\t_batch_idle.erase(key)",
		"\tif not is_instance_valid(node):",
		"\t\treturn",
		"\tnode.visible = false",
		"\tnode.multimesh.instance_count = 0",
		"\tif _batch_shelf.size() >= BATCH_SHELF_LIMIT:",
		"\t\tnode.queue_free()",
		"\t\treturn",
		"\t_batch_shelf.append(node)",
		"",
		"## Hands one batch's style to its material - the same uniforms a placed shape sets, so the two draw",
		"## the same dashes, the same caps and the same colour modes.",
		"func _push_style_uniforms(target: ShaderMaterial, style: Dictionary, kind_id: int) -> void:",
		"\tif target == null:",
		"\t\treturn",
		"\tvar thickness: float = maxf(float(style.get(\"thickness\", 2.0)), 0.01)",
		"\tvar space: String = str(style.get(\"dash_space\", \"count\"))",
		"\ttarget.set_shader_parameter(\"batch_kind\", kind_id)",
		"\ttarget.set_shader_parameter(\"thickness_px\", thickness)",
		"\ttarget.set_shader_parameter(\"aa_width\", ANTIALIAS_WIDTH)",
		"\ttarget.set_shader_parameter(\"filled\", bool(style.get(\"filled\", false)))",
		"\ttarget.set_shader_parameter(\"caps\", maxi(CAP_WORDS.find(str(style.get(\"caps\", \"round\"))), 0))",
		"\ttarget.set_shader_parameter(\"colour_a\", style.get(\"colour\", Color.WHITE))",
		"\ttarget.set_shader_parameter(\"colour_b\", style.get(\"colour_b\", Color.WHITE))",
		"\ttarget.set_shader_parameter(\"colour_mode\", maxi(COLOUR_MODE_WORDS.find(str(style.get(\"colour_mode\", \"single\"))), 0))",
		"\ttarget.set_shader_parameter(\"dashed\", bool(style.get(\"dashed\", false)))",
		"\ttarget.set_shader_parameter(\"dash_snap\", maxi(DASH_SNAP_WORDS.find(str(style.get(\"dash_snap\", \"tiling\"))), 0))",
		"\ttarget.set_shader_parameter(\"dash_style\", maxi(DASH_STYLE_WORDS.find(str(style.get(\"dash_style\", \"plain\"))), 0))",
		"\ttarget.set_shader_parameter(\"dash_offset\", 0.0)",
		"\ttarget.set_shader_parameter(\"dash_count\", int(style.get(\"dash_count\", 12)) if space == \"count\" else 0)",
		"\ttarget.set_shader_parameter(\"dash_gap_share\", clampf(float(style.get(\"dash_spacing\", 0.5)), 0.0, 0.95))",
		"\tvar size: float = maxf(float(style.get(\"dash_size\", 12.0)), 0.0)",
		"\tvar gap: float = maxf(float(style.get(\"dash_spacing\", 6.0)), 0.0)",
		"\ttarget.set_shader_parameter(\"dash_length_px\", size * thickness if space == \"relative\" else size)",
		"\ttarget.set_shader_parameter(\"dash_gap_px\", gap * thickness if space == \"relative\" else gap)"
	]))
	sheet.events.append(styled)

	return Lib.save_pack(sheet, "res://eventsheet_addons/canvas_surface/canvas_surface")
