# Pack builder - canvas_surface (the shared 2D drawing runtime; run via build_sample_behaviors.gd).
@tool

const Lib := preload("res://tools/pack_builders/_lib.gd")


## CanvasSurface: the engine-level 2D drawing plumbing that the ACE vocabulary cannot express - an
## offscreen SubViewport render target, a drawer whose `draw` signal replays a command queue, the
## persistence clear-mode trick, coordinate mapping, and self-updating textured ribbons. It lives in a
## dedicated RUNTIME pack (still plain GDScript, still ships with eventsheet_addons/, still zero EDITOR
## dependency) so the Drawing Canvas behavior and the builtin Draw ACEs stay thin, first-class rows that
## just call CanvasSurface methods. One surface is created per host on demand and cached on the host.
static func build() -> bool:
	var sheet: EventSheetResource = EventSheetResource.new()
	sheet.host_class = "Node2D"
	sheet.custom_class_name = "CanvasSurface"
	sheet.class_description = "Shared 2D drawing runtime for the Drawing Canvas behaviour and the Draw ACEs: an offscreen render target, a command queue, and self-updating ribbons. One per host, cached on the host - call CanvasSurface.for_node(host)."
	var block: RawCodeRow = RawCodeRow.new()
	block.code = "\n".join(PackedStringArray([
		"const META_KEY: String = \"__canvas_surface\"",
		"",
		"var canvas_width: int = 512",
		"var canvas_height: int = 512",
		"var auto_clear: bool = false",
		"var coordinates: String = \"world\"  # \"world\" (centered on the host) or \"canvas\" (raw texture pixels)",
		"var display_on_host: bool = true",
		"",
		"var _host: Node2D = null",
		"var _viewport: SubViewport = null",
		"var _drawer: Node2D = null",
		"var _display: Sprite2D = null",
		"var _commands: Array = []",
		"var _ribbons: Array = []",
		"",
		"## Returns the host's canvas surface, creating (and attaching) one on first use. Cached on the host",
		"## via metadata, so every \"... on {node}\" draw shares one surface. Null-safe.",
		"static func for_node(host: Node) -> CanvasSurface:",
		"\tif not (host is Node2D):",
		"\t\treturn null",
		"\tvar host_2d: Node2D = host as Node2D",
		"\tif host_2d.has_meta(META_KEY):",
		"\t\tvar existing: Variant = host_2d.get_meta(META_KEY)",
		"\t\tif is_instance_valid(existing):",
		"\t\t\treturn existing",
		"\tvar surface: CanvasSurface = CanvasSurface.new()",
		"\tsurface.name = \"CanvasSurface\"",
		"\tsurface._host = host_2d",
		"\thost_2d.set_meta(META_KEY, surface)",
		"\t# Deferred: for_node commonly fires from the host's own child-setup (a behavior's On Ready), when a",
		"\t# direct add_child to the host is rejected as 'parent busy'. Draws buffer until the surface's _ready",
		"\t# builds the drawer and flushes them, so an On-Ready-time draw is not lost.",
		"\thost_2d.add_child.call_deferred(surface)",
		"\treturn surface",
		"",
		"## Applies configuration (from the behavior's exports) and rebuilds the surface if it already exists.",
		"func configure(width: int, height: int, clear_each_frame: bool, coords: String, show_on_host: bool) -> void:",
		"\tcanvas_width = width",
		"\tcanvas_height = height",
		"\tauto_clear = clear_each_frame",
		"\tcoordinates = coords",
		"\tdisplay_on_host = show_on_host",
		"\tif _viewport != null:",
		"\t\t_viewport.size = Vector2i(maxi(canvas_width, 8), maxi(canvas_height, 8))",
		"\t\t_viewport.render_target_clear_mode = SubViewport.CLEAR_MODE_ALWAYS if auto_clear else SubViewport.CLEAR_MODE_NEVER",
		"",
		"func _ready() -> void:",
		"\tset_physics_process(true)",
		"\t_ensure()",
		"",
		"## Builds the offscreen render target once: a SubViewport holding the drawer whose draw signal",
		"## replays the queue. Clear mode is the whole persistence story - NEVER accumulates (paint), ALWAYS",
		"## wipes (live redraw), and clear() flips to ONCE.",
		"func _ensure() -> void:",
		"\tif _viewport != null or not is_inside_tree():",
		"\t\treturn",
		"\t_viewport = SubViewport.new()",
		"\t_viewport.size = Vector2i(maxi(canvas_width, 8), maxi(canvas_height, 8))",
		"\t_viewport.transparent_bg = true",
		"\t_viewport.render_target_update_mode = SubViewport.UPDATE_ALWAYS",
		"\t_viewport.render_target_clear_mode = SubViewport.CLEAR_MODE_ALWAYS if auto_clear else SubViewport.CLEAR_MODE_NEVER",
		"\tadd_child(_viewport)",
		"\t_drawer = Node2D.new()",
		"\t_viewport.add_child(_drawer)",
		"\t_drawer.draw.connect(_run_draw_commands)",
		"\tif display_on_host and _host != null:",
		"\t\t_display = Sprite2D.new()",
		"\t\t_display.texture = _viewport.get_texture()",
		"\t\t_host.add_child.call_deferred(_display)",
		"\tif not _commands.is_empty():",
		"\t\t_drawer.queue_redraw()  # flush draws buffered before the surface entered the tree",
		"",
		"## World position -> canvas pixels: the canvas is centered on the host, so the mapping is a",
		"## translation. In canvas coordinate mode points pass through untouched.",
		"func to_canvas(point: Vector2) -> Vector2:",
		"\tif coordinates != \"world\" or _host == null:",
		"\t\treturn point",
		"\treturn point - _host.global_position + Vector2(canvas_width, canvas_height) * 0.5",
		"",
		"func _run_draw_commands() -> void:",
		"\tfor command: Dictionary in _commands:",
		"\t\tmatch str(command[\"kind\"]):",
		"\t\t\t\"line\":",
		"\t\t\t\t_drawer.draw_line(command[\"a\"], command[\"b\"], command[\"color\"], command[\"width\"])",
		"\t\t\t\"circle\":",
		"\t\t\t\t_drawer.draw_circle(command[\"at\"], command[\"radius\"], command[\"color\"])",
		"\t\t\t\"ring\":",
		"\t\t\t\t_drawer.draw_arc(command[\"at\"], command[\"radius\"], 0.0, TAU, 64, command[\"color\"], command[\"width\"])",
		"\t\t\t\"rect\":",
		"\t\t\t\t_drawer.draw_rect(command[\"rect\"], command[\"color\"])",
		"\t\t\t\"polygon\":",
		"\t\t\t\t_drawer.draw_colored_polygon(command[\"points\"], command[\"color\"])",
		"\t\t\t\"stamp\":",
		"\t\t\t\tvar texture: Texture2D = command[\"texture\"]",
		"\t\t\t\tif texture != null:",
		"\t\t\t\t\t_drawer.draw_set_transform(command[\"at\"], command[\"rotation\"], Vector2.ONE * float(command[\"scale\"]))",
		"\t\t\t\t\t_drawer.draw_texture(texture, -texture.get_size() * 0.5)",
		"\t\t\t\t\t_drawer.draw_set_transform(Vector2.ZERO, 0.0, Vector2.ONE)",
		"\t_commands.clear()",
		"",
		"func _push(command: Dictionary) -> void:",
		"\t_ensure()",
		"\t_commands.append(command)  # buffered even before the drawer exists; _ensure flushes it",
		"\tif _drawer != null:",
		"\t\t_drawer.queue_redraw()",
		"",
		"# --- Public draw surface (called by the Drawing Canvas behaviour and the builtin Draw ACEs) ---",
		"",
		"func texture() -> Texture2D:",
		"\t_ensure()",
		"\treturn _viewport.get_texture() if _viewport != null else null",
		"",
		"func clear() -> void:",
		"\t_ensure()",
		"\t_commands.clear()",
		"\tif _viewport != null and not auto_clear:",
		"\t\t_viewport.render_target_clear_mode = SubViewport.CLEAR_MODE_ONCE",
		"\tif _drawer != null:",
		"\t\t_drawer.queue_redraw()",
		"",
		"func set_auto_clear(enabled: bool) -> void:",
		"\tauto_clear = enabled",
		"\tif _viewport != null:",
		"\t\t_viewport.render_target_clear_mode = SubViewport.CLEAR_MODE_ALWAYS if enabled else SubViewport.CLEAR_MODE_NEVER",
		"",
		"func set_display_visible(visible_now: bool) -> void:",
		"\tif _display != null:",
		"\t\t_display.visible = visible_now",
		"",
		"func line(from_x: float, from_y: float, to_x: float, to_y: float, width: float, color: Color) -> void:",
		"\t_push({\"kind\": \"line\", \"a\": to_canvas(Vector2(from_x, from_y)), \"b\": to_canvas(Vector2(to_x, to_y)), \"width\": width, \"color\": color})",
		"",
		"func circle(x: float, y: float, radius: float, color: Color) -> void:",
		"\t_push({\"kind\": \"circle\", \"at\": to_canvas(Vector2(x, y)), \"radius\": radius, \"color\": color})",
		"",
		"func ring(x: float, y: float, radius: float, width: float, color: Color) -> void:",
		"\t_push({\"kind\": \"ring\", \"at\": to_canvas(Vector2(x, y)), \"radius\": radius, \"width\": width, \"color\": color})",
		"",
		"func rect(x: float, y: float, width: float, height: float, color: Color) -> void:",
		"\t_push({\"kind\": \"rect\", \"rect\": Rect2(to_canvas(Vector2(x, y)), Vector2(width, height)), \"color\": color})",
		"",
		"func cone(x: float, y: float, facing_deg: float, fov_deg: float, radius: float, color: Color) -> void:",
		"\tvar center: Vector2 = to_canvas(Vector2(x, y))",
		"\tvar points: PackedVector2Array = PackedVector2Array([center])",
		"\tfor i: int in 33:",
		"\t\tvar angle: float = deg_to_rad(facing_deg - fov_deg * 0.5 + fov_deg * float(i) / 32.0)",
		"\t\tpoints.append(center + Vector2.from_angle(angle) * radius)",
		"\t_push({\"kind\": \"polygon\", \"points\": points, \"color\": color})",
		"",
		"func stamp(texture_res: Texture2D, x: float, y: float, scale_factor: float, rotation_deg: float) -> void:",
		"\t_push({\"kind\": \"stamp\", \"texture\": texture_res, \"at\": to_canvas(Vector2(x, y)), \"scale\": maxf(scale_factor, 0.01), \"rotation\": deg_to_rad(rotation_deg)})",
		"",
		"func line_of_sight(origin_x: float, origin_y: float, facing_deg: float, fov_deg: float, max_range: float, collision_mask: int, color: Color) -> void:",
		"\t_ensure()",
		"\tif _host == null or not is_inside_tree() or _drawer == null:",
		"\t\treturn",
		"\tvar space: PhysicsDirectSpaceState2D = _host.get_world_2d().direct_space_state",
		"\tif space == null:",
		"\t\treturn",
		"\tvar origin: Vector2 = Vector2(origin_x, origin_y)",
		"\tvar points: PackedVector2Array = PackedVector2Array([to_canvas(origin)])",
		"\tfor i: int in 49:",
		"\t\tvar angle: float = deg_to_rad(facing_deg - fov_deg * 0.5 + fov_deg * float(i) / 48.0)",
		"\t\tvar direction: Vector2 = Vector2.from_angle(angle)",
		"\t\tvar query: PhysicsRayQueryParameters2D = PhysicsRayQueryParameters2D.create(origin, origin + direction * max_range, collision_mask)",
		"\t\tif _host is CollisionObject2D:",
		"\t\t\tquery.exclude = [(_host as CollisionObject2D).get_rid()]",
		"\t\tvar hit: Dictionary = space.intersect_ray(query)",
		"\t\tvar end_point: Vector2 = hit[\"position\"] if not hit.is_empty() else origin + direction * max_range",
		"\t\tpoints.append(to_canvas(end_point))",
		"\t_push({\"kind\": \"polygon\", \"points\": points, \"color\": color})",
		"",
		"func prefab(prefab_res: Resource, x: float, y: float, scale_factor: float, rotation_deg: float) -> void:",
		"\tif prefab_res == null:",
		"\t\treturn",
		"\tvar steps: Variant = prefab_res.get(\"steps\")",
		"\tif not (steps is Array):",
		"\t\treturn",
		"\tvar origin: Vector2 = Vector2(x, y)",
		"\tvar spin: float = deg_to_rad(rotation_deg)",
		"\tvar scale_by: float = maxf(scale_factor, 0.01)",
		"\tfor step: Variant in steps:",
		"\t\tif not (step is Dictionary):",
		"\t\t\tcontinue",
		"\t\tvar entry: Dictionary = step",
		"\t\tvar at: Vector2 = origin + (Vector2(float(entry.get(\"x\", 0.0)), float(entry.get(\"y\", 0.0))) * scale_by).rotated(spin)",
		"\t\tvar p1: float = float(entry.get(\"p1\", 0.0))",
		"\t\tvar p2: float = float(entry.get(\"p2\", 0.0))",
		"\t\tvar p3: float = float(entry.get(\"p3\", 0.0))",
		"\t\tvar tint: Color = Color.from_string(str(entry.get(\"color\", \"white\")), Color.WHITE)",
		"\t\tmatch str(entry.get(\"kind\", \"\")):",
		"\t\t\t\"circle\":",
		"\t\t\t\tcircle(at.x, at.y, p1 * scale_by, tint)",
		"\t\t\t\"ring\":",
		"\t\t\t\tring(at.x, at.y, p1 * scale_by, maxf(p2 * scale_by, 1.0), tint)",
		"\t\t\t\"rect\":",
		"\t\t\t\tvar corners: PackedVector2Array = PackedVector2Array()",
		"\t\t\t\tfor corner: Vector2 in [Vector2.ZERO, Vector2(p1, 0.0), Vector2(p1, p2), Vector2(0.0, p2)]:",
		"\t\t\t\t\tcorners.append(to_canvas(origin + ((Vector2(float(entry.get(\"x\", 0.0)), float(entry.get(\"y\", 0.0))) + corner) * scale_by).rotated(spin)))",
		"\t\t\t\t_push({\"kind\": \"polygon\", \"points\": corners, \"color\": tint})",
		"\t\t\t\"line\":",
		"\t\t\t\tvar to_point: Vector2 = origin + (Vector2(p1, p2) * scale_by).rotated(spin)",
		"\t\t\t\tline(at.x, at.y, to_point.x, to_point.y, maxf(p3 * scale_by, 1.0), tint)",
		"\t\t\t\"cone\":",
		"\t\t\t\tcone(at.x, at.y, p1 + rotation_deg, p2, p3 * scale_by, tint)",
		"\t\t\t\"stamp\":",
		"\t\t\t\tvar texture_path: String = str(entry.get(\"texture\", \"\")).strip_edges()",
		"\t\t\t\tif not texture_path.is_empty() and ResourceLoader.exists(texture_path):",
		"\t\t\t\t\tstamp(load(texture_path) as Texture2D, at.x, at.y, maxf(p1, 0.01) * scale_by, p2 + rotation_deg)",
		"",
		"# --- Ribbons: Line2D children refreshed every physics frame - this update runs HERE, so the",
		"# behaviour no longer carries a per-frame GDScript loop. ---",
		"",
		"func start_ribbon(follow: Node, point_count: int, width: float, color: Color) -> void:",
		"\t_ensure()",
		"\tif _drawer == null or not (follow is Node2D):",
		"\t\treturn",
		"\tstop_ribbon(follow)",
		"\tvar ribbon_line: Line2D = Line2D.new()",
		"\tribbon_line.width = width",
		"\tribbon_line.default_color = color",
		"\tribbon_line.joint_mode = Line2D.LINE_JOINT_ROUND",
		"\tribbon_line.begin_cap_mode = Line2D.LINE_CAP_ROUND",
		"\tribbon_line.end_cap_mode = Line2D.LINE_CAP_ROUND",
		"\t_drawer.add_child(ribbon_line)",
		"\t_ribbons.append({\"id\": follow.get_instance_id(), \"line\": ribbon_line, \"trail\": [], \"length\": maxi(point_count, 2)})",
		"",
		"func set_ribbon_texture(follow: Node, texture_res: Texture2D) -> void:",
		"\tif follow == null:",
		"\t\treturn",
		"\tfor ribbon: Dictionary in _ribbons:",
		"\t\tif int(ribbon[\"id\"]) == follow.get_instance_id() and is_instance_valid(ribbon[\"line\"]):",
		"\t\t\t(ribbon[\"line\"] as Line2D).texture = texture_res",
		"\t\t\t(ribbon[\"line\"] as Line2D).texture_mode = Line2D.LINE_TEXTURE_STRETCH",
		"",
		"func stop_ribbon(follow: Node) -> void:",
		"\tif follow == null:",
		"\t\treturn",
		"\tvar kept: Array = []",
		"\tfor ribbon: Dictionary in _ribbons:",
		"\t\tif int(ribbon[\"id\"]) == follow.get_instance_id():",
		"\t\t\tif is_instance_valid(ribbon[\"line\"]):",
		"\t\t\t\t(ribbon[\"line\"] as Line2D).queue_free()",
		"\t\telse:",
		"\t\t\tkept.append(ribbon)",
		"\t_ribbons = kept",
		"",
		"func _physics_process(_delta: float) -> void:",
		"\tif _ribbons.is_empty() or _drawer == null:",
		"\t\treturn",
		"\tvar kept: Array = []",
		"\tfor ribbon: Dictionary in _ribbons:",
		"\t\tvar followed: Node2D = instance_from_id(int(ribbon[\"id\"])) as Node2D",
		"\t\tvar ribbon_line: Line2D = ribbon[\"line\"]",
		"\t\tif followed == null or not is_instance_valid(ribbon_line):",
		"\t\t\tif is_instance_valid(ribbon_line):",
		"\t\t\t\tribbon_line.queue_free()",
		"\t\t\tcontinue",
		"\t\tkept.append(ribbon)",
		"\t\tvar trail: Array = ribbon[\"trail\"]",
		"\t\ttrail.append(followed.global_position)",
		"\t\twhile trail.size() > int(ribbon[\"length\"]):",
		"\t\t\ttrail.pop_front()",
		"\t\tvar mapped: PackedVector2Array = PackedVector2Array()",
		"\t\tfor point: Variant in trail:",
		"\t\t\tmapped.append(to_canvas(point))",
		"\t\tribbon_line.points = mapped",
		"\t_ribbons = kept"
	]))
	sheet.events.append(block)
	return Lib.save_pack(sheet, "res://eventsheet_addons/canvas_surface/canvas_surface")
