# Pack builder - free_spot (a RUNTIME pack: plain GDScript the emitted code calls, shipped
# where the user's own files are; run via build_sample_behaviors.gd).
@tool

const Lib := preload("res://tools/pack_builders/_lib.gd")


## EventForgeFreeSpot is not a behaviour and publishes no verbs of its own: it is a library the
## SHIPPED vocabulary calls by name out of its templates, which is why it has to live where
## the user's own files live rather than inside the plugin. Deleting the editor addon must
## leave every emitted line still parsing, and a class declared under addons/ would not.
## Built exactly as the canvas surface beside it is: one host class, one verbatim block,
## no manifest, no verbs.
static func build() -> bool:
	var sheet: EventSheetResource = EventSheetResource.new()
	sheet.host_class = "RefCounted"
	sheet.custom_class_name = "EventForgeFreeSpot"
	sheet.class_description = "A place to put the next copy that nothing is already standing in - the roll-until-it-fits query the free-spot placement words and the free-spot spawn rows call."
	var block: RawCodeRow = RawCodeRow.new()
	block.code = "\n".join(PackedStringArray([
		"# A place to put the next copy, that nothing is already standing in.",
		"#",
		"# The other placement words are one expression each, because \"where\" is one measurement: a node's",
		"# own place, a point along a path, a point inside a shape. A FREE spot is not one measurement - it",
		"# is the same roll asked over and over until the answer is somewhere the copy actually fits - so it",
		"# is the one placement word that is a function rather than a line, and this is that function.",
		"#",
		"# WHAT \"FREE\" MEANS HERE, in the order the three questions are asked:",
		"#   inside      the point is rolled inside a shape somebody drew - the Area2D around the spawn",
		"#               zone, the collision shape on it, or a Control's own rectangle.",
		"#   apart       the point is at least the gap from every other copy of the same scene already in",
		"#               the world, which is what keeps a wave from landing on top of itself.",
		"#   clear of    the copy's OWN collision shape, put at that point, would not overlap anything in",
		"#               the named groups, or anything standing under something in them - a level is put in a",
		"#               group by its ROOT, and the body that answers a physics query is a child of that. That",
		"#               is a real physics query in the same space the game runs in, so a wall is a wall",
		"#               whatever drew it. A group whose members carry no collision",
		"#               shape at all cannot be asked that question, so those members are answered the only",
		"#               way they can be: the point has to be further than the gap from every one of them.",
		"#",
		"# AND IT ANSWERS NOTHING WHEN THERE IS NOTHING TO ANSWER. After the last try it returns null, which",
		"# is a real answer and not a failure: a full arena has no free spot in it, and a spawn row that",
		"# reads null spawns nothing and says so. Rolling for ever instead would be a hang.",
		"#",
		"# THE COST, said plainly. One call instantiates the scene once to read its collision shape and frees",
		"# it again, and walks the running scene once to find the copies already placed. Both are done ONCE",
		"# per call and reused across every try, so the price of raising the try count is the rolls",
		"# themselves. A spawn per frame is fine; a thousand spawns in one frame wants a pool.",
		"#",
		"# PLAIN GDSCRIPT, AND NOT THE PLUGIN'S. Nothing here touches an editor, a sheet or any class the",
		"# plugin declares, and this file is not one of the plugin's files: it ships beside the behaviour",
		"# packs, in the folder that is the project's own, so deleting the editor addon leaves every emitted",
		"# line that names it still parsing and still running. That is the whole reason the rows can call it.",
		"",
		"## How many points to roll before answering nothing. The rows offer their own field; this is what a",
		"## call that leaves it out uses.",
		"const DEFAULT_TRIES: int = 24",
		"",
		"## The ceiling on one clearance query. A point standing in a crowd is refused by the first hit, so",
		"## this only bounds the pathological case where a query is asked inside a pile.",
		"const MAX_HITS: int = 32",
		"",
		"",
		"## A point inside `inside` that nothing in `clear_of` is standing in and no other copy of `scene` is",
		"## within `gap` pixels of, or null after `tries` rolls. `inside` is a CollisionShape2D, an Area2D or",
		"## a Control; `clear_of` holds group names.",
		"static func in_2d(inside: Node, scene: PackedScene, clear_of: Array, gap: float,",
		"\t\ttries: int = DEFAULT_TRIES) -> Variant:",
		"\tif inside == null or not is_instance_valid(inside) or not inside.is_inside_tree():",
		"\t\treturn null",
		"\tif scene == null:",
		"\t\treturn null",
		"\tvar region: Dictionary = region_2d(inside)",
		"\tif region.is_empty():",
		"\t\treturn null",
		"\tvar world: World2D = inside.get_viewport().find_world_2d() if inside.get_viewport() != null else null",
		"\tvar space: PhysicsDirectSpaceState2D = world.direct_space_state if world != null else null",
		"\tvar shape: Shape2D = scene_shape_2d(scene)",
		"\tvar placed: Array[Node] = _copies_of(inside, scene)",
		"\tvar watched: Array[Node] = _members_without_shapes(inside, clear_of, \"CollisionShape2D\")",
		"\treturn roll_2d(region, tries, func(point: Vector2) -> bool:",
		"\t\tif not _far_enough_2d(point, placed, gap):",
		"\t\t\treturn false",
		"\t\tif not _far_enough_2d(point, watched, gap):",
		"\t\t\treturn false",
		"\t\treturn _clear_2d(space, shape, point, clear_of))",
		"",
		"",
		"## The same question in three dimensions, with the gap measured in metres. `inside` is a",
		"## CollisionShape3D or an Area3D.",
		"static func in_3d(inside: Node, scene: PackedScene, clear_of: Array, gap: float,",
		"\t\ttries: int = DEFAULT_TRIES) -> Variant:",
		"\tif inside == null or not is_instance_valid(inside) or not inside.is_inside_tree():",
		"\t\treturn null",
		"\tif scene == null:",
		"\t\treturn null",
		"\tvar region: Dictionary = region_3d(inside)",
		"\tif region.is_empty():",
		"\t\treturn null",
		"\tvar world: World3D = inside.get_viewport().find_world_3d() if inside.get_viewport() != null else null",
		"\tvar space: PhysicsDirectSpaceState3D = world.direct_space_state if world != null else null",
		"\tvar shape: Shape3D = scene_shape_3d(scene)",
		"\tvar placed: Array[Node] = _copies_of(inside, scene)",
		"\tvar watched: Array[Node] = _members_without_shapes(inside, clear_of, \"CollisionShape3D\")",
		"\treturn roll_3d(region, tries, func(point: Vector3) -> bool:",
		"\t\tif not _far_enough_3d(point, placed, gap):",
		"\t\t\treturn false",
		"\t\tif not _far_enough_3d(point, watched, gap):",
		"\t\t\treturn false",
		"\t\treturn _clear_3d(space, shape, point, clear_of))",
		"",
		"",
		"## THE LOOP ITSELF, with the questions handed in. `region` is what the two calls above measured of",
		"## the node somebody drew; `is_free` answers, for one point, whether the copy would fit there. It is",
		"## separated from the world-reading half above for a plain reason: everything about giving up after",
		"## a number of tries is true whatever the questions are, and a loop that can only be exercised with",
		"## a live physics space is a loop nobody can pin a value on.",
		"static func roll_2d(region: Dictionary, tries: int, is_free: Callable) -> Variant:",
		"\tif region.is_empty():",
		"\t\treturn null",
		"\tfor _attempt: int in range(maxi(tries, 1)):",
		"\t\tvar point: Vector2 = _roll_2d(region)",
		"\t\tif bool(is_free.call(point)):",
		"\t\t\treturn point",
		"\treturn null",
		"",
		"",
		"## The same loop in three dimensions.",
		"static func roll_3d(region: Dictionary, tries: int, is_free: Callable) -> Variant:",
		"\tif region.is_empty():",
		"\t\treturn null",
		"\tfor _attempt: int in range(maxi(tries, 1)):",
		"\t\tvar point: Vector3 = _roll_3d(region)",
		"\t\tif bool(is_free.call(point)):",
		"\t\t\treturn point",
		"\treturn null",
		"",
		"",
		"## The collision shape a copy of this scene would stand in, or null when it carries none. Read by",
		"## building the scene once and freeing it again, because a packed scene's shape is a property of the",
		"## node inside it and there is no cheaper honest way to ask.",
		"static func scene_shape_2d(scene: PackedScene) -> Shape2D:",
		"\tif scene == null or not scene.can_instantiate():",
		"\t\treturn null",
		"\tvar built: Node = scene.instantiate()",
		"\tvar found: Node = _first_of_class(built, \"CollisionShape2D\")",
		"\tvar shape: Shape2D = (found as CollisionShape2D).shape if found is CollisionShape2D else null",
		"\tbuilt.free()",
		"\treturn shape",
		"",
		"",
		"## The same, in three dimensions.",
		"static func scene_shape_3d(scene: PackedScene) -> Shape3D:",
		"\tif scene == null or not scene.can_instantiate():",
		"\t\treturn null",
		"\tvar built: Node = scene.instantiate()",
		"\tvar found: Node = _first_of_class(built, \"CollisionShape3D\")",
		"\tvar shape: Shape3D = (found as CollisionShape3D).shape if found is CollisionShape3D else null",
		"\tbuilt.free()",
		"\treturn shape",
		"",
		"",
		"# -- where the points are rolled ------------------------------------------------------------------",
		"",
		"",
		"## The region a node stands for, as the two answers this file can roll a point in: a rectangle",
		"## (`centre` and `half`) or a disc (`centre` and `radius`). An empty dictionary for a node that",
		"## draws no region, which is what makes the caller answer null rather than scatter copies over the",
		"## origin.",
		"static func region_2d(inside: Node) -> Dictionary:",
		"\tif inside is Area2D:",
		"\t\tvar child: Node = _first_of_class(inside, \"CollisionShape2D\")",
		"\t\treturn region_2d(child) if child != null else {}",
		"\tif inside is CollisionShape2D:",
		"\t\tvar holder: CollisionShape2D = inside as CollisionShape2D",
		"\t\tvar shape: Shape2D = holder.shape",
		"\t\tif shape is RectangleShape2D:",
		"\t\t\treturn {\"centre\": holder.global_position, \"half\": (shape as RectangleShape2D).size * 0.5}",
		"\t\tif shape is CircleShape2D:",
		"\t\t\treturn {\"centre\": holder.global_position, \"radius\": (shape as CircleShape2D).radius}",
		"\t\treturn {}",
		"\tif inside is Control:",
		"\t\tvar box: Control = inside as Control",
		"\t\treturn {\"centre\": box.global_position + box.size * 0.5, \"half\": box.size * 0.5}",
		"\treturn {}",
		"",
		"",
		"## The same in three dimensions: a box (`half` a Vector3) or a sphere (`radius`).",
		"static func region_3d(inside: Node) -> Dictionary:",
		"\tif inside is Area3D:",
		"\t\tvar child: Node = _first_of_class(inside, \"CollisionShape3D\")",
		"\t\treturn region_3d(child) if child != null else {}",
		"\tif inside is CollisionShape3D:",
		"\t\tvar holder: CollisionShape3D = inside as CollisionShape3D",
		"\t\tvar shape: Shape3D = holder.shape",
		"\t\tif shape is BoxShape3D:",
		"\t\t\treturn {\"centre\": holder.global_position, \"half\": (shape as BoxShape3D).size * 0.5}",
		"\t\tif shape is SphereShape3D:",
		"\t\t\treturn {\"centre\": holder.global_position, \"radius\": (shape as SphereShape3D).radius}",
		"\t\treturn {}",
		"\treturn {}",
		"",
		"",
		"## One point inside a 2D region. The disc takes the square root of the roll so points do not bunch",
		"## up in the middle, which is the same correction the shipped scatter expression makes.",
		"static func _roll_2d(region: Dictionary) -> Vector2:",
		"\tvar centre: Vector2 = region.get(\"centre\", Vector2.ZERO)",
		"\tif region.has(\"radius\"):",
		"\t\tvar radius: float = float(region[\"radius\"]) * sqrt(randf())",
		"\t\treturn centre + Vector2.RIGHT.rotated(randf() * TAU) * radius",
		"\tvar half: Vector2 = region.get(\"half\", Vector2.ZERO)",
		"\treturn centre + Vector2(randf_range(-half.x, half.x), randf_range(-half.y, half.y))",
		"",
		"",
		"## One point inside a 3D region. The sphere takes the cube root of the roll for the reason the disc",
		"## takes the square root: an even scatter through a volume needs it.",
		"static func _roll_3d(region: Dictionary) -> Vector3:",
		"\tvar centre: Vector3 = region.get(\"centre\", Vector3.ZERO)",
		"\tif region.has(\"radius\"):",
		"\t\tvar radius: float = float(region[\"radius\"]) * pow(randf(), 1.0 / 3.0)",
		"\t\tvar direction: Vector3 = Vector3(randfn(0.0, 1.0), randfn(0.0, 1.0), randfn(0.0, 1.0))",
		"\t\tif direction.length() <= 0.0:",
		"\t\t\tdirection = Vector3.UP",
		"\t\treturn centre + direction.normalized() * radius",
		"\tvar half: Vector3 = region.get(\"half\", Vector3.ZERO)",
		"\treturn centre + Vector3(randf_range(-half.x, half.x), randf_range(-half.y, half.y),",
		"\t\trandf_range(-half.z, half.z))",
		"",
		"",
		"# -- the three questions --------------------------------------------------------------------------",
		"",
		"",
		"## True when the copy's own shape, put at this point, overlaps nothing in the named groups. A scene",
		"## with no collision shape of its own, or a world with no space to ask in, answers true here and",
		"## leans entirely on the distance test beside it.",
		"static func _clear_2d(space: PhysicsDirectSpaceState2D, shape: Shape2D, point: Vector2,",
		"\t\tclear_of: Array) -> bool:",
		"\tif space == null or shape == null or clear_of.is_empty():",
		"\t\treturn true",
		"\tvar query: PhysicsShapeQueryParameters2D = PhysicsShapeQueryParameters2D.new()",
		"\tquery.shape = shape",
		"\tquery.transform = Transform2D(0.0, point)",
		"\tquery.collide_with_bodies = true",
		"\tquery.collide_with_areas = true",
		"\tfor hit: Dictionary in space.intersect_shape(query, MAX_HITS):",
		"\t\tif in_any_group(hit.get(\"collider\"), clear_of):",
		"\t\t\treturn false",
		"\treturn true",
		"",
		"",
		"## The same query in three dimensions.",
		"static func _clear_3d(space: PhysicsDirectSpaceState3D, shape: Shape3D, point: Vector3,",
		"\t\tclear_of: Array) -> bool:",
		"\tif space == null or shape == null or clear_of.is_empty():",
		"\t\treturn true",
		"\tvar query: PhysicsShapeQueryParameters3D = PhysicsShapeQueryParameters3D.new()",
		"\tquery.shape = shape",
		"\tquery.transform = Transform3D(Basis.IDENTITY, point)",
		"\tquery.collide_with_bodies = true",
		"\tquery.collide_with_areas = true",
		"\tfor hit: Dictionary in space.intersect_shape(query, MAX_HITS):",
		"\t\tif in_any_group(hit.get(\"collider\"), clear_of):",
		"\t\t\treturn false",
		"\treturn true",
		"",
		"",
		"## True when the point is at least `gap` from every node in the list. A gap of nothing asks nothing,",
		"## which is how a caller says it only cares about overlapping.",
		"static func _far_enough_2d(point: Vector2, others: Array[Node], gap: float) -> bool:",
		"\tif gap <= 0.0:",
		"\t\treturn true",
		"\tfor other: Node in others:",
		"\t\tif other is Node2D and point.distance_to((other as Node2D).global_position) < gap:",
		"\t\t\treturn false",
		"\treturn true",
		"",
		"",
		"## The same, in three dimensions.",
		"static func _far_enough_3d(point: Vector3, others: Array[Node], gap: float) -> bool:",
		"\tif gap <= 0.0:",
		"\t\treturn true",
		"\tfor other: Node in others:",
		"\t\tif other is Node3D and point.distance_to((other as Node3D).global_position) < gap:",
		"\t\t\treturn false",
		"\treturn true",
		"",
		"",
		"# -- what is already in the world -----------------------------------------------------------------",
		"",
		"",
		"## Every node already in the running scene that was made from this same scene file. Asked of the",
		"## node's own `scene_file_path`, which Godot fills in for anything instanced from a `.tscn`, so a",
		"## copy counts however it was made.",
		"static func _copies_of(inside: Node, scene: PackedScene) -> Array[Node]:",
		"\tvar found: Array[Node] = []",
		"\tvar wanted: String = scene.resource_path",
		"\tif wanted.is_empty() or inside.get_tree() == null:",
		"\t\treturn found",
		"\tvar root: Node = inside.get_tree().current_scene",
		"\tif root == null:",
		"\t\troot = inside.get_tree().root",
		"\t_collect_copies(root, wanted, found)",
		"\treturn found",
		"",
		"",
		"## The walk behind the list above, kept separate so the answer is one recursion with one condition",
		"## in it rather than a filter over the whole tree.",
		"static func _collect_copies(node: Node, wanted: String, into: Array[Node]) -> void:",
		"\tif node.scene_file_path == wanted:",
		"\t\tinto.append(node)",
		"\tfor child: Node in node.get_children():",
		"\t\t_collect_copies(child, wanted, into)",
		"",
		"",
		"## The members of the named groups that carry no collision shape - the ones a physics query cannot",
		"## answer for. They are what the distance test is really for: a marker, a waypoint, a bare Node2D",
		"## somebody dropped to say \"not here\".",
		"static func _members_without_shapes(inside: Node, groups: Array,",
		"\t\tshape_class: String) -> Array[Node]:",
		"\tvar found: Array[Node] = []",
		"\tif inside.get_tree() == null:",
		"\t\treturn found",
		"\tfor group: Variant in groups:",
		"\t\tfor member: Node in inside.get_tree().get_nodes_in_group(StringName(str(group))):",
		"\t\t\tif _first_of_class(member, shape_class) == null:",
		"\t\t\t\tfound.append(member)",
		"\treturn found",
		"",
		"",
		"## True when the object is a node belonging to any of the named groups, or standing UNDER one that",
		"## does. The walk up is not a nicety: a level is drawn as a scene, and a scene is put in a group by",
		"## its root, so the thing that answers a physics query - the StaticBody2D two levels down with the",
		"## shape on it - is almost never the node the group name was written on. Asking only the collider",
		"## answered \"nothing is standing here\" inside a wall whose root said otherwise.",
		"##",
		"## Public for the reason the two roll loops above are: the clearance test needs a live physics space",
		"## and this question does not, so this is the half of it that can be held to a value.",
		"static func in_any_group(collider: Variant, groups: Array) -> bool:",
		"\tvar node: Node = collider as Node",
		"\twhile node != null:",
		"\t\tfor group: Variant in groups:",
		"\t\t\tif node.is_in_group(StringName(str(group))):",
		"\t\t\t\treturn true",
		"\t\tnode = node.get_parent()",
		"\treturn false",
		"",
		"",
		"## The first node of a class at or under this one, in tree order, or null. Used to find the shape a",
		"## scene stands in and to ask whether a group member has one at all.",
		"static func _first_of_class(node: Node, wanted: String) -> Node:",
		"\tif node == null:",
		"\t\treturn null",
		"\tif node.is_class(wanted):",
		"\t\treturn node",
		"\tfor child: Node in node.get_children():",
		"\t\tvar found: Node = _first_of_class(child, wanted)",
		"\t\tif found != null:",
		"\t\t\treturn found",
		"\treturn null"
	]))
	sheet.events.append(block)
	return Lib.save_pack(sheet, "res://eventsheet_addons/free_spot", "")
