# Pack builder - moment_runner (a RUNTIME script beside the Juice pack: plain GDScript the
# emitted moments call; run via tools/build_sample_behaviors.gd).
@tool

const Lib := preload("res://tools/pack_builders/_lib.gd")


## MomentRunner is the ONE piece of code every home of a moment runs through: a Moment
## block's emitted coroutine, a moment FILE played by the Juice pack's Moment row, and the list a
## feedback node holds. Three places to write a moment down, one thing that plays it - so a beat
## behaves the same wherever it was written, and a fix lands once.
##
## It publishes no verbs. It is a library the emitted code names by class, which is why it ships
## where the user's own files live rather than inside the plugin: deleting the editor addon must
## leave every emitted line still parsing.
##
## And that is why the class is named for what it does rather than for the plugin that offered it.
## A pack's code is the user's after the editor is gone, so a line in their own folder calling a
## plugin-sounding name reads like a dependency it does not have. The look runtime beside it made
## the same move for the same reason.
static func build() -> bool:
	var sheet: EventSheetResource = EventSheetResource.new()
	sheet.host_class = "RefCounted"
	sheet.custom_class_name = "MomentRunner"
	sheet.class_description = "The one runner behind every moment: the waits a moment block is timed by, the strength an amount is scaled by, and the falloff that makes a far impact quieter."
	var block: RawCodeRow = RawCodeRow.new()
	block.code = "\n".join(_runner_lines())
	sheet.events.append(block)
	return Lib.save_pack(sheet, "res://eventsheet_addons/juice/moment_runner")


## The whole runner, as the shipped file reads it.
static func _runner_lines() -> PackedStringArray:
	return PackedStringArray([
		"# THE ONE RUNNER BEHIND EVERY MOMENT.",
		"#",
		"# A moment is a beat of feedback - the shake and the freeze and the flash of a hit - and this",
		"# project can write one down in three places: as a block of rows in a sheet (which compiles to a",
		"# coroutine calling the waits below), as a moment FILE the Juice pack's Moment row plays, and as",
		"# a list a node holds. All three run through this file, so a beat behaves the same wherever it",
		"# was written and a fix lands once instead of three times.",
		"#",
		"# WHAT IT KNOWS, and nothing else:",
		"#   the waits      at / then / hold, each on the clock the step chose. A moment's schedule is",
		"#                  worked out when the sheet compiles, so what arrives here is one number.",
		"#   the strength   what an amount really becomes once the play's strength has scaled it and the",
		"#                  no-flashing ceiling has held it down.",
		"#   the range      how much of the strength survives the distance between where the moment",
		"#                  happened and whoever is watching.",
		"#",
		"# PLAIN GDSCRIPT, AND NOT THE PLUGIN'S. Nothing here touches an editor, a sheet, or any class the",
		"# plugin declares. It allocates nothing per frame - a wait is one timer per step, and the strength",
		"# maths is arithmetic - so a moment costs the same on a phone and in a browser as it does on a",
		"# desktop.",
		"",
		"## The clock a wait is measured on. \"game\" follows Engine.time_scale, so a moment stretches with a",
		"## slowmo; \"real\" ignores it, which is what a step after a hitstop wants.",
		"const CLOCK_GAME: String = \"game\"",
		"const CLOCK_REAL: String = \"real\"",
		"",
		"## How the strength falls off between where the moment happened and the edge of its range.",
		"const FALLOFF_LINEAR: String = \"linear\"",
		"const FALLOFF_SMOOTH: String = \"smooth\"",
		"const FALLOFF_NONE: String = \"none\"",
		"",
		"## The project-wide answer to \"this player has asked for no flashing\", spelled the same here as",
		"## everywhere else that reads it.",
		"const NO_FLASHING_META: StringName = &\"no_flashing\"",
		"",
		"## The ceiling every amount a player SEES is held under while no flashing is on, and the floor",
		"## every one of those times is held over. Same numbers the moment layer already holds itself to:",
		"## the hit still hits, it just cannot strobe.",
		"const FLASH_CEILING: float = 0.3",
		"const FLASH_FLOOR_SECONDS: float = 0.4",
		"",
		"",
		"## Wait until `seconds` after the step above started - the At word. The number is the GAP the",
		"## compiler worked out, never the absolute time, so nothing here has to remember when a moment began.",
		"static func at(host: Node, seconds: float, clock: String = CLOCK_GAME) -> Signal:",
		"\treturn wait(host, seconds, clock)",
		"",
		"",
		"## Wait `seconds` after the previous step started - the Then word.",
		"static func then(host: Node, seconds: float, clock: String = CLOCK_GAME) -> Signal:",
		"\treturn wait(host, seconds, clock)",
		"",
		"",
		"## Wait for the slowest step above to finish, then `delay` - the Hold word. `longest` is how much",
		"## of that step is still to run when the Hold is reached, which the compiler folded out of the",
		"## durations the rows declared; a moment whose steps are all instant passes 0 and waits only the delay.",
		"static func hold(host: Node, longest: float, delay: float, clock: String = CLOCK_GAME) -> Signal:",
		"\treturn wait(host, maxf(longest, 0.0) + maxf(delay, 0.0), clock)",
		"",
		"",
		"## The one wait the three words go through. A zero wait is still a wait of one frame, which is what",
		"## makes a Hold a beat rather than a no-op.",
		"static func wait(host: Node, seconds: float, clock: String = CLOCK_GAME) -> Signal:",
		"\tvar tree: SceneTree = _tree(host)",
		"\tif tree == null:",
		"\t\tpush_warning(\"Moment: a step asked to wait with no scene tree to wait in - the wait was skipped.\")",
		"\t\treturn Signal()",
		"\treturn tree.create_timer(maxf(seconds, 0.0), true, false, clock == CLOCK_REAL).timeout",
		"",
		"",
		"## What one amount really becomes: scaled by the strength this play has, then held under the",
		"## ceiling while no flashing is on. ONE function, so no step can be the one that forgot.",
		"static func scaled(amount: float, strength: float) -> float:",
		"\tvar wanted: float = amount * maxf(strength, 0.0)",
		"\tif no_flashing():",
		"\t\treturn clampf(wanted, -FLASH_CEILING, FLASH_CEILING)",
		"\treturn wanted",
		"",
		"",
		"## And what one duration really becomes: never quicker than the floor while no flashing is on,",
		"## because a small amplitude arriving ten times a second is still a strobe.",
		"static func seconds_of(seconds: float) -> float:",
		"\tif no_flashing():",
		"\t\treturn maxf(seconds, FLASH_FLOOR_SECONDS)",
		"\treturn maxf(seconds, 0.0)",
		"",
		"",
		"## Whether this player has asked for no flashing.",
		"static func no_flashing() -> bool:",
		"\treturn bool(Engine.get_meta(NO_FLASHING_META, false))",
		"",
		"",
		"## The strength a play really has once the distance has been paid for: full strength with no range",
		"## and no place, less the further away the moment happened, and nothing at all past the edge.",
		"##",
		"## `from` may be a node or a point (Vector2 / Vector3). Who is watching is the active camera, and",
		"## the host itself when there is none - a game with no camera still hears its own hits.",
		"static func strength_at(host: Node, strength: float, from: Variant, within: float,",
		"\t\tfalloff: String = FALLOFF_LINEAR) -> float:",
		"\tif within <= 0.0:",
		"\t\treturn strength",
		"\tvar place: Variant = place_of(from)",
		"\tvar listener: Variant = place_of(listener_of(host))",
		"\tif place == null or listener == null:",
		"\t\treturn strength",
		"\tvar apart: float = _distance(place, listener)",
		"\tif apart < 0.0:",
		"\t\treturn strength",
		"\treturn strength * falloff_factor(apart, within, falloff)",
		"",
		"",
		"## How much of the strength survives one distance. Pure arithmetic, so it is the piece a test can",
		"## pin without a camera, a viewport or a frame: 1 at the middle, 0 at the edge and beyond, and the",
		"## smooth word rounds the shoulders of the line between.",
		"static func falloff_factor(distance: float, within: float, falloff: String = FALLOFF_LINEAR) -> float:",
		"\tif within <= 0.0:",
		"\t\treturn 1.0",
		"\tif distance >= within:",
		"\t\treturn 0.0",
		"\tif falloff == FALLOFF_NONE:",
		"\t\treturn 1.0",
		"\tvar near: float = clampf(1.0 - distance / within, 0.0, 1.0)",
		"\tif falloff == FALLOFF_SMOOTH:",
		"\t\treturn near * near * (3.0 - 2.0 * near)",
		"\treturn near",
		"",
		"",
		"## Where something is: a point is already the answer, a node is asked for its own place, and",
		"## anything else has none.",
		"static func place_of(what: Variant) -> Variant:",
		"\tif what is Vector2 or what is Vector3:",
		"\t\treturn what",
		"\tif what is Node2D:",
		"\t\treturn (what as Node2D).global_position",
		"\tif what is Node3D:",
		"\t\treturn (what as Node3D).global_position",
		"\tif what is Control:",
		"\t\treturn (what as Control).global_position",
		"\treturn null",
		"",
		"",
		"## Whoever the distance is measured to: the camera the player is looking through, or the host",
		"## itself when this game has none.",
		"static func listener_of(host: Node) -> Node:",
		"\tvar tree: SceneTree = _tree(host)",
		"\tif tree == null:",
		"\t\treturn host",
		"\tvar viewport: Viewport = host.get_viewport() if host != null and host.is_inside_tree() else tree.root",
		"\tif viewport == null:",
		"\t\treturn host",
		"\tvar camera_3d: Camera3D = viewport.get_camera_3d()",
		"\tif camera_3d != null:",
		"\t\treturn camera_3d",
		"\tvar camera_2d: Camera2D = viewport.get_camera_2d()",
		"\tif camera_2d != null:",
		"\t\treturn camera_2d",
		"\treturn host",
		"",
		"",
		"## The distance between two places, or -1 when they are not the same kind of place (a 2D moment",
		"## and a 3D camera cannot be measured against each other, and guessing would be worse than saying so).",
		"static func _distance(place: Variant, listener: Variant) -> float:",
		"\tif place is Vector2 and listener is Vector2:",
		"\t\treturn (place as Vector2).distance_to(listener as Vector2)",
		"\tif place is Vector3 and listener is Vector3:",
		"\t\treturn (place as Vector3).distance_to(listener as Vector3)",
		"\treturn -1.0",
		"",
		"",
		"## The tree a wait happens in: the host's own, or the running one when the host is not in it yet.",
		"static func _tree(host: Node) -> SceneTree:",
		"\tif host != null and host.is_inside_tree():",
		"\t\treturn host.get_tree()",
		"\treturn Engine.get_main_loop() as SceneTree",
	])
