# Pack builder - platformer_pathfinding (one pack per file; run via tools/build_sample_behaviors.gd).
@tool

const Lib := preload("res://tools/pack_builders/_lib.gd")


## Platformer pathfinding for a CharacterBody2D - the 2D jump-graph navigator:
## scans a TileMapLayer's physics tiles into standable nodes, connects them with WALK edges
## (adjacent cells, one step up/down - which is what makes stairs and tile slopes walkable),
## JUMP arcs, and FALL drops, then A*-routes over the graph. Jump reach is DERIVED from the
## sibling PlatformerMovement's move_speed/jump_velocity/gravity, and auto-control DRIVES that
## sibling through its ai_move_axis seam + jump() - pathfinding never reimplements movement.
## Manual mode (Set Auto Control off) exposes the same intents as expressions.
static func build() -> bool:
	var sheet: EventSheetResource = EventSheetResource.new()
	sheet.behavior_mode = true
	sheet.host_class = "CharacterBody2D"
	sheet.custom_class_name = "PlatformerPathfinding"
	sheet.addon_category = "Platformer Pathfinding"
	sheet.ace_expose_all_mode = "node"
	sheet.addon_tags = PackedStringArray(["movement", "platformer", "ai", "pathfinding"])
	sheet.variables = {
		"auto_control": {"type": "bool", "default": true, "exported": true,
			"attributes": {"tooltip": "Drive the sibling PlatformerMovement automatically. Off = paths still compute; read Path Move Axis / Path Wants Jump and steer yourself."}},
		"arrive_distance": {"type": "float", "default": 10.0, "exported": true,
			"attributes": {"tooltip": "How close (px, horizontally) counts as reaching a waypoint."}},
		"max_fall_distance": {"type": "float", "default": 320.0, "exported": true,
			"attributes": {"tooltip": "The furthest safe drop (px) the graph will route through."}},
		"jump_height_override": {"type": "float", "default": 0.0, "exported": true,
			"attributes": {"tooltip": "Max jump height in px (0 = derive it from the sibling PlatformerMovement's jump_velocity/gravity)."}},
		"jump_distance_override": {"type": "float", "default": 0.0, "exported": true,
			"attributes": {"tooltip": "Max jump distance in px (0 = derive it from the sibling PlatformerMovement's speed and air time)."}},
		"debug_draw": {"type": "bool", "default": false, "exported": true,
			"attributes": {"tooltip": "Draw the active path as a line in the world."}},
		"variable_jump": {"type": "bool", "default": true, "exported": true,
			"attributes": {"tooltip": "Release the jump at the height each arc actually needs (short hops for flat gaps, full rises for tall ledges) - smoother-looking movement. Off = every jump is full height."}},
		"ledge_restriction": {"type": "bool", "default": false, "exported": true,
			"attributes": {"tooltip": "Patrol discipline: routes may only WALK - no jumps, no portals, and no drops beyond Ledge Leniency. The agent stays on its platform."}},
		"ledge_leniency": {"type": "float", "default": 0.0, "exported": true,
			"attributes": {"tooltip": "With Ledge Restriction on, drops up to this many pixels are still allowed (0 = no drops at all)."}},
		"jump_positioning": {"type": "String", "default": "relaxed", "exported": true, "options": ["relaxed", "strict"],
			"attributes": {"tooltip": "relaxed: jump as soon as a jump leg starts. strict: walk onto the exact takeoff spot first - slower but precise on tight arcs."}},
		"coyote_time": {"type": "float", "default": 0.12, "exported": true,
			"attributes": {"tooltip": "Grace window (s) for AI jumps just after running off the takeoff ledge - a frame-late jump still fires."}},
		"repath_interval": {"type": "float", "default": 0.5, "exported": true,
			"attributes": {"tooltip": "While following a node (Find Path To Node), how often the route may refresh."}},
		"repath_threshold": {"type": "float", "default": 24.0, "exported": true,
			"attributes": {"tooltip": "The route only refreshes when the followed node has moved at least this many pixels from where the current path was aimed."}},
		"stuck_timeout": {"type": "float", "default": 1.5, "exported": true,
			"attributes": {"tooltip": "No progress toward the current waypoint for this long fires On Waypoint Stuck and re-routes from wherever the agent actually is."}},
		"fallback_move_speed": {"type": "float", "default": 200.0, "exported": true,
			"attributes": {"tooltip": "No movement sibling? The built-in fallback driver moves the CharacterBody2D itself at this speed."}},
		"fallback_jump_velocity": {"type": "float", "default": -400.0, "exported": true,
			"attributes": {"tooltip": "The fallback driver's jump velocity (negative = up). Also sizes jump arcs when nothing can be derived."}},
		"fallback_gravity": {"type": "float", "default": 980.0, "exported": true,
			"attributes": {"tooltip": "The fallback driver's gravity."}},
	}

	var about: CommentRow = CommentRow.new()
	about.text = "Platformer pathfinding: attach as a SIBLING of PlatformerMovement under a CharacterBody2D. Build Nav Graph from your TileMapLayer once, then Find Path To - the behavior derives jump reach from the movement pack and drives it through the ai_move_axis seam. Stairs and tile slopes walk (adjacent cells one step up/down are WALK edges); gaps and ledges route through jump arcs and fall drops."
	sheet.events.append(about)

	# Internal state + triggers + conditions + expressions + the graph/AStar helpers.
	var block: RawCodeRow = RawCodeRow.new()
	block.code = "\n".join(PackedStringArray([
		"# --- Internal state (the graph lives per agent in P1) ---",
		"var _tilemap: TileMapLayer = null",
		"var _movement: Node = null",
		"## Standable cells (the cell the agent's feet occupy) -> true.",
		"var _nodes: Dictionary = {}",
		"## cell -> Array of {\"to\": Vector2i, \"kind\": \"walk\"/\"jump\"/\"fall\", \"cost\": float}.",
		"var _edges: Dictionary = {}",
		"## The active path: Array of {\"world\": Vector2, \"action\": String}.",
		"var _path: Array = []",
		"var _path_index: int = 0",
		"var _jumped_this_segment: bool = false",
		"var _jump_released: bool = false",
		"var _jump_release_velocity: float = 0.0",
		"var _move_axis: float = 0.0",
		"var _debug_line: Line2D = null",
		"## Registered portals: {\"from\": Vector2, \"to\": Vector2, \"both\": bool} - survive regenerate.",
		"var _portals: Array = []",
		"# Follow mode (Find Path To Node): the tracked node + where the current path was aimed.",
		"var _follow_target: Node = null",
		"var _path_goal: Vector2 = Vector2.ZERO",
		"var _goal_mode: String = \"nearest\"",
		"var _repath_clock: float = 0.0",
		"# Coyote grace: seconds since the host last stood on the floor.",
		"var _floor_grace: float = 0.0",
		"# Stuck watchdog: best distance seen toward the current waypoint + time without progress.",
		"var _best_waypoint_distance: float = INF",
		"var _stuck_clock: float = 0.0",
		"# Budget-deferred request (this agent is queued for a later tick).",
		"var _path_pending: bool = false",
		"var _pending_goal: Vector2 = Vector2.ZERO",
		"var _pending_goal_mode: String = \"nearest\"",
		"# The SHARED path budget: statics are one value across every agent of this behavior, so",
		"# N chasers repathing at once spread their A* runs over frames instead of spiking one.",
		"static var _shared_max_paths_per_tick: int = 8",
		"static var _shared_tick_id: int = -1",
		"static var _shared_paths_this_tick: int = 0",
		"",
		"## @ace_trigger",
		"## @ace_name(\"On Portal Taken\")",
		"signal portal_taken",
		"",
		"## @ace_trigger",
		"## @ace_name(\"On Waypoint Stuck\")",
		"signal waypoint_stuck",
		"",
		"## @ace_trigger",
		"## @ace_name(\"On Repath\")",
		"signal repathed",
		"",
		"## @ace_condition",
		"## @ace_name(\"Is Path Pending\")",
		"func is_path_pending() -> bool:",
		"\treturn _path_pending",
		"",
		"## @ace_trigger",
		"## @ace_name(\"On Path Found\")",
		"signal path_found",
		"",
		"## @ace_trigger",
		"## @ace_name(\"On Path Failed\")",
		"signal path_failed",
		"",
		"## @ace_trigger",
		"## @ace_name(\"On Path Complete\")",
		"signal path_complete",
		"",
		"## @ace_trigger",
		"## @ace_name(\"On Waypoint Reached\")",
		"signal waypoint_reached",
		"",
		"## @ace_trigger",
		"## @ace_name(\"On Nav Graph Built\")",
		"signal nav_graph_built",
		"",
		"## @ace_condition",
		"## @ace_name(\"Has Path\")",
		"func has_path() -> bool:",
		"\treturn not _path.is_empty()",
		"",
		"## @ace_condition",
		"## @ace_name(\"Path Wants Jump\")",
		"func path_wants_jump() -> bool:",
		"\tif _path.is_empty() or _jumped_this_segment or host == null:",
		"\t\treturn false",
		"\tvar waypoint: Dictionary = _path[_path_index]",
		"\tif waypoint[\"action\"] == \"jump\":",
		"\t\treturn true",
		"\t# Step assist: a close-and-higher walk waypoint needs a hop on full-block stairs.",
		"\tvar tile: float = float(_tilemap.tile_set.tile_size.y) if _tilemap != null else 32.0",
		"\tvar target: Vector2 = waypoint[\"world\"]",
		"\treturn waypoint[\"action\"] == \"walk\" and target.y < host.global_position.y - 8.0 and absf(target.x - host.global_position.x) < tile * 1.5",
		"",
		"## @ace_expression",
		"## @ace_name(\"Path Move Axis\")",
		"func path_move_axis() -> float:",
		"\treturn _move_axis",
		"",
		"## @ace_expression",
		"## @ace_name(\"Waypoint Count\")",
		"func waypoint_count() -> int:",
		"\treturn _path.size()",
		"",
		"## @ace_expression",
		"## @ace_name(\"Current Waypoint Index\")",
		"func current_waypoint_index() -> int:",
		"\treturn _path_index",
		"",
		"## @ace_expression",
		"## @ace_name(\"Current Waypoint X\")",
		"func current_waypoint_x() -> float:",
		"\treturn (_path[_path_index][\"world\"] as Vector2).x if not _path.is_empty() else 0.0",
		"",
		"## @ace_expression",
		"## @ace_name(\"Current Waypoint Y\")",
		"func current_waypoint_y() -> float:",
		"\treturn (_path[_path_index][\"world\"] as Vector2).y if not _path.is_empty() else 0.0",
		"",
		"## @ace_expression",
		"## @ace_name(\"Current Path Action\")",
		"func current_path_action() -> String:",
		"\treturn str(_path[_path_index][\"action\"]) if not _path.is_empty() else \"\"",
		"",
		"## The sibling movement pack, duck-typed: any child of the host with a move_speed and a",
		"## jump() (PlatformerMovement, or your own driver with the same surface).",
		"## @ace_hidden",
		"func _find_movement() -> Node:",
		"\tif _movement != null and is_instance_valid(_movement):",
		"\t\treturn _movement",
		"\tif host == null:",
		"\t\treturn null",
		"\tfor child in host.get_children():",
		"\t\tif child != self and child.has_method(\"jump\") and child.get(\"move_speed\") != null:",
		"\t\t\t_movement = child",
		"\t\t\treturn _movement",
		"\treturn null",
		"",
		"## Jump reach in CELLS, derived from the movement pack's physics (the overrides win when",
		"## set): height = v^2/2g, distance = speed * full air time, both with a 0.9 safety margin.",
		"## @ace_hidden",
		"func _jump_reach_cells() -> Vector2i:",
		"\tvar tile: float = float(_tilemap.tile_set.tile_size.y)",
		"\tvar height_px: float = jump_height_override",
		"\tvar distance_px: float = jump_distance_override",
		"\tvar movement: Node = _find_movement()",
		"\tif movement != null:",
		"\t\tvar rise: float = absf(float(movement.get(\"jump_velocity\")))",
		"\t\tvar fall_pull: float = maxf(float(movement.get(\"gravity\")), 1.0)",
		"\t\tif height_px <= 0.0:",
		"\t\t\theight_px = rise * rise / (2.0 * fall_pull) * 0.9",
		"\t\tif distance_px <= 0.0:",
		"\t\t\tdistance_px = float(movement.get(\"move_speed\")) * (2.0 * rise / fall_pull) * 0.9",
		"\t# No sibling to derive from: size arcs from the fallback driver's own physics.",
		"\tvar fallback_rise: float = absf(fallback_jump_velocity)",
		"\tif height_px <= 0.0:",
		"\t\theight_px = fallback_rise * fallback_rise / (2.0 * maxf(fallback_gravity, 1.0)) * 0.9",
		"\tif distance_px <= 0.0:",
		"\t\tdistance_px = fallback_move_speed * (2.0 * fallback_rise / maxf(fallback_gravity, 1.0)) * 0.9",
		"\treturn Vector2i(maxi(int(ceil(distance_px / tile)), 1), maxi(int(ceil(height_px / tile)), 1))",
		"",
		"## The gravity the drive should reason with (the sibling's when present).",
		"## @ace_hidden",
		"func _drive_gravity() -> float:",
		"\tvar movement: Node = _find_movement()",
		"\tif movement != null and movement.get(\"gravity\") != null:",
		"\t\treturn maxf(float(movement.get(\"gravity\")), 1.0)",
		"\treturn maxf(fallback_gravity, 1.0)",
		"",
		"## The upward speed still needed to climb to `target` from here (plus a half-tile margin) -",
		"## variable jump releases the button once remaining velocity drops to this, so each hop",
		"## rises just as far as its arc requires.",
		"## @ace_hidden",
		"func _release_velocity_for(target: Vector2) -> float:",
		"\tvar rise: float = maxf(host.global_position.y - target.y, 0.0) + 20.0",
		"\treturn sqrt(2.0 * _drive_gravity() * rise)",
		"",
		"## Injects one portal into the built graph as a cheap \"portal\" edge between the standable",
		"## nodes nearest its endpoints.",
		"## @ace_hidden",
		"func _apply_portal(portal: Dictionary) -> void:",
		"\tvar from_node: Vector2i = _nearest_node(portal[\"from\"], 2)",
		"\tvar to_node: Vector2i = _nearest_node(portal[\"to\"], 2)",
		"\tif from_node == Vector2i.MAX or to_node == Vector2i.MAX:",
		"\t\treturn",
		"\t_add_edge(from_node, to_node, \"portal\", 2.0)",
		"\tif bool(portal[\"both\"]):",
		"\t\t_add_edge(to_node, from_node, \"portal\", 2.0)",
		"",
		"## @ace_hidden",
		"func _advance_waypoint() -> void:",
		"\t_jumped_this_segment = false",
		"\t_jump_released = false",
		"\t_best_waypoint_distance = INF",
		"\t_stuck_clock = 0.0",
		"\t_path_index += 1",
		"\twaypoint_reached.emit()",
		"\tif _path_index >= _path.size():",
		"\t\tstop_pathfinding()",
		"\t\tpath_complete.emit()",
		"",
		"## Coarse clearance for a jump/fall arc: the cells along the chord, lifted one cell for",
		"## the rise, must be free. Coarse on purpose - P1 favours routing in open layouts.",
		"## @ace_hidden",
		"func _arc_clear(from_cell: Vector2i, to_cell: Vector2i, solid: Dictionary) -> bool:",
		"\tif solid.has(from_cell + Vector2i(0, -1)) or solid.has(to_cell + Vector2i(0, -1)):",
		"\t\treturn false",
		"\tfor step in [0.25, 0.5, 0.75]:",
		"\t\tvar sample: Vector2 = Vector2(from_cell).lerp(Vector2(to_cell), step) + Vector2(0.0, -1.0)",
		"\t\tif solid.has(Vector2i(roundi(sample.x), roundi(sample.y))):",
		"\t\t\treturn false",
		"\treturn true",
		"",
		"## @ace_hidden",
		"func _add_edge(from_cell: Vector2i, to_cell: Vector2i, kind: String, cost: float) -> void:",
		"\tif not _edges.has(from_cell):",
		"\t\t_edges[from_cell] = []",
		"\t(_edges[from_cell] as Array).append({\"to\": to_cell, \"kind\": kind, \"cost\": cost})",
		"",
		"## The standable node nearest a world position (within max_cells), or Vector2i.MAX.",
		"## Tree-safe: outside a scene tree (tools, tests) the tilemap's own offset stands in for",
		"## the global transform.",
		"## @ace_hidden",
		"func _nearest_node(world: Vector2, max_cells: int) -> Vector2i:",
		"\tvar local: Vector2 = _tilemap.to_local(world) if _tilemap.is_inside_tree() else world - _tilemap.position",
		"\tvar around: Vector2i = _tilemap.local_to_map(local)",
		"\tvar best: Vector2i = Vector2i.MAX",
		"\tvar best_distance: float = float(max_cells) + 0.51",
		"\tfor cell in _nodes:",
		"\t\tvar cell_distance: float = Vector2(cell - around).length()",
		"\t\tif cell_distance < best_distance:",
		"\t\t\tbest_distance = cell_distance",
		"\t\t\tbest = cell",
		"\treturn best",
		"",
		"## @ace_hidden",
		"func _cell_world(cell: Vector2i) -> Vector2:",
		"\tvar local: Vector2 = _tilemap.map_to_local(cell)",
		"\treturn _tilemap.to_global(local) if _tilemap.is_inside_tree() else local + _tilemap.position",
		"",
		"## A* over the walk/jump/fall edges (jump edges already carry their cost premium, so the",
		"## router prefers walking a ramp over jumping it). Returns the cell path or [].",
		"## @ace_hidden",
		"func _astar(start: Vector2i, goal: Vector2i) -> Array:",
		"\tvar open: Array = [start]",
		"\tvar came_from: Dictionary = {}",
		"\tvar cost_so_far: Dictionary = {start: 0.0}",
		"\twhile not open.is_empty():",
		"\t\tvar best_index: int = 0",
		"\t\tfor index in range(1, open.size()):",
		"\t\t\tvar here: Vector2i = open[index]",
		"\t\t\tif cost_so_far[here] + Vector2(goal - here).length() < cost_so_far[open[best_index]] + Vector2(goal - (open[best_index] as Vector2i)).length():",
		"\t\t\t\tbest_index = index",
		"\t\tvar current: Vector2i = open.pop_at(best_index)",
		"\t\tif current == goal:",
		"\t\t\tvar cells: Array = [current]",
		"\t\t\twhile came_from.has(current):",
		"\t\t\t\tcurrent = came_from[current]",
		"\t\t\t\tcells.push_front(current)",
		"\t\t\treturn cells",
		"\t\tfor edge in (_edges.get(current, []) as Array):",
		"\t\t\tif not _edge_allowed(current, edge):",
		"\t\t\t\tcontinue",
		"\t\t\tvar next_cell: Vector2i = edge[\"to\"]",
		"\t\t\tvar next_cost: float = cost_so_far[current] + float(edge[\"cost\"])",
		"\t\t\tif not cost_so_far.has(next_cell) or next_cost < float(cost_so_far[next_cell]):",
		"\t\t\t\tcost_so_far[next_cell] = next_cost",
		"\t\t\t\tcame_from[next_cell] = current",
		"\t\t\t\tif not open.has(next_cell):",
		"\t\t\t\t\topen.append(next_cell)",
		"\treturn []",
		"",
		"## Ledge restriction's router filter: walking is always fine, drops only within the",
		"## leniency, jumps and portals never - the patrol stays on its platform.",
		"## @ace_hidden",
		"func _edge_allowed(from_cell: Vector2i, edge: Dictionary) -> bool:",
		"\tif not ledge_restriction:",
		"\t\treturn true",
		"\tvar kind: String = str(edge[\"kind\"])",
		"\tif kind == \"walk\":",
		"\t\treturn true",
		"\tif kind == \"fall\":",
		"\t\tvar tile: float = float(_tilemap.tile_set.tile_size.y) if _tilemap != null else 32.0",
		"\t\treturn float(((edge[\"to\"] as Vector2i).y - from_cell.y)) * tile <= ledge_leniency",
		"\treturn false",
		"",
		"## The edge kind walking cell A -> B on the found path (for the waypoint's action).",
		"## @ace_hidden",
		"func _edge_kind(from_cell: Vector2i, to_cell: Vector2i) -> String:",
		"\tfor edge in (_edges.get(from_cell, []) as Array):",
		"\t\tif edge[\"to\"] == to_cell:",
		"\t\t\treturn str(edge[\"kind\"])",
		"\treturn \"walk\"",
		"",
		"## @ace_hidden",
		"func _refresh_debug() -> void:",
		"\tif not debug_draw:",
		"\t\tif _debug_line != null and is_instance_valid(_debug_line):",
		"\t\t\t_debug_line.clear_points()",
		"\t\treturn",
		"\tif _debug_line == null or not is_instance_valid(_debug_line):",
		"\t\t_debug_line = Line2D.new()",
		"\t\t_debug_line.width = 3.0",
		"\t\t_debug_line.default_color = Color(0.2, 0.9, 0.5, 0.8)",
		"\t\t_debug_line.top_level = true",
		"\t\thost.add_child(_debug_line)",
		"\t_debug_line.clear_points()",
		"\tif _path.is_empty():",
		"\t\treturn",
		"\t_debug_line.add_point(host.global_position)",
		"\tfor index in range(_path_index, _path.size()):",
		"\t\t_debug_line.add_point(_path[index][\"world\"])"
	]))
	sheet.events.append(block)

	# Per-physics-tick drive: resolve the current waypoint into the {move_axis, want_jump}
	# intent, feed the sibling movement pack (auto) or just publish the expressions (manual).
	var tick: EventRow = EventRow.new()
	tick.trigger_provider_id = "Core"
	tick.trigger_id = "OnPhysicsProcess"
	var tick_body: RawCodeRow = RawCodeRow.new()
	tick_body.code = "\n".join(PackedStringArray([
		"if host == null:",
		"\treturn",
		"# Coyote bookkeeping: seconds since the host last stood on the floor (the jump gate",
		"# below accepts a frame-late takeoff within Coyote Time).",
		"if host.is_on_floor():",
		"\t_floor_grace = 0.0",
		"else:",
		"\t_floor_grace += delta",
		"# Budget-deferred retries and follow-mode refreshes run even without an active path.",
		"_repath_clock += delta",
		"if _path_pending:",
		"\tfind_path_to(_pending_goal.x, _pending_goal.y, _pending_goal_mode)",
		"elif _follow_target != null and is_instance_valid(_follow_target) and _follow_target is Node2D and _repath_clock >= repath_interval:",
		"\t_repath_clock = 0.0",
		"\tvar followed: Vector2 = (_follow_target as Node2D).global_position",
		"\tif followed.distance_to(_path_goal) > repath_threshold:",
		"\t\tfind_path_to(followed.x, followed.y, _goal_mode)",
		"\t\trepathed.emit()",
		"if _path.is_empty():",
		"\treturn",
		"var waypoint: Dictionary = _path[_path_index]",
		"var target: Vector2 = waypoint[\"world\"]",
		"# Portal traversal: the waypoint IS the exit - blink there and continue.",
		"if waypoint[\"action\"] == \"portal\":",
		"\thost.global_position = target",
		"\thost.velocity = Vector2.ZERO",
		"\tportal_taken.emit()",
		"\t_advance_waypoint()",
		"\treturn",
		"var dx: float = target.x - host.global_position.x",
		"_move_axis = clampf(dx / 24.0, -1.0, 1.0) if absf(dx) > 2.0 else 0.0",
		"var movement: Node = _find_movement()",
		"var tile: float = float(_tilemap.tile_set.tile_size.y) if _tilemap != null else 32.0",
		"# Jump on jump arcs, and STEP-ASSIST on raised walk waypoints: a full-block stair stops",
		"# a walking body, so a close-and-higher waypoint gets a hop (slope tiles just walk).",
		"var wants_jump: bool = waypoint[\"action\"] == \"jump\"",
		"if not wants_jump and waypoint[\"action\"] == \"walk\":",
		"\twants_jump = target.y < host.global_position.y - 8.0 and absf(dx) < tile * 1.5",
		"# Strict jump positioning: walk onto the exact takeoff spot before leaping (relaxed",
		"# leaps the moment the jump leg starts - faster, but looser on tight arcs).",
		"if waypoint[\"action\"] == \"jump\" and jump_positioning == \"strict\" and not _jumped_this_segment and _path_index > 0:",
		"\tvar takeoff_dx: float = (_path[_path_index - 1][\"world\"] as Vector2).x - host.global_position.x",
		"\tif absf(takeoff_dx) > 4.0:",
		"\t\t_move_axis = clampf(takeoff_dx / 24.0, -1.0, 1.0)",
		"\t\twants_jump = false",
		"if auto_control:",
		"\tvar start_jump: bool = wants_jump and not _jumped_this_segment and (host.is_on_floor() or _floor_grace <= coyote_time)",
		"\tif start_jump:",
		"\t\t_jumped_this_segment = true",
		"\t\t_jump_released = false",
		"\t\t_jump_release_velocity = _release_velocity_for(target)",
		"\t\t# An arc that needs (nearly) the whole jump must never be cut - releasing a",
		"\t\t# near-max jump on its first frames kills the climb. Variable jump only arms",
		"\t\t# when there is clear headroom.",
		"\t\tvar full_rise: float = absf(float(movement.get(\"jump_velocity\"))) if movement != null else absf(fallback_jump_velocity)",
		"\t\tif _jump_release_velocity >= full_rise * 0.85:",
		"\t\t\t_jump_release_velocity = 0.0",
		"\t# Variable jump: once remaining upward speed is just enough for THIS arc's rise,",
		"\t# release - flat gap hops stay low, tall ledges get the full jump.",
		"\tvar release_now: bool = variable_jump and _jumped_this_segment and not _jump_released and host.velocity.y < 0.0 and absf(host.velocity.y) <= _jump_release_velocity",
		"\tif movement != null:",
		"\t\t# The standard drive seam on the movement sibling - its accel, coyote time, and",
		"\t\t# jump feel all still apply under AI control.",
		"\t\tmovement.set(\"ai_controlled\", true)",
		"\t\tmovement.set(\"ai_move_axis\", _move_axis)",
		"\t\tif start_jump:",
		"\t\t\tmovement.jump()",
		"\t\tif release_now and movement.has_method(\"jump_released\"):",
		"\t\t\t_jump_released = true",
		"\t\t\tmovement.jump_released()",
		"\telse:",
		"\t\t# No movement sibling: the built-in fallback drives the CharacterBody2D itself,",
		"\t\t# so ANY body pathfinds out of the box (attach one behavior, done).",
		"\t\thost.velocity.y = minf(host.velocity.y + fallback_gravity * delta, 1000.0)",
		"\t\thost.velocity.x = _move_axis * fallback_move_speed",
		"\t\tif start_jump:",
		"\t\t\thost.velocity.y = fallback_jump_velocity",
		"\t\tif release_now:",
		"\t\t\t_jump_released = true",
		"\t\t\thost.velocity.y *= 0.45",
		"\t\thost.move_and_slide()",
		"if absf(dx) <= arrive_distance and absf(target.y - host.global_position.y) <= tile:",
		"\t_advance_waypoint()",
		"# Stuck watchdog: no progress toward the waypoint for Stuck Timeout -> On Waypoint Stuck",
		"# and a fresh route from wherever the agent actually is.",
		"else:",
		"\tvar waypoint_gap: float = host.global_position.distance_to(target)",
		"\tif waypoint_gap < _best_waypoint_distance - 1.0:",
		"\t\t_best_waypoint_distance = waypoint_gap",
		"\t\t_stuck_clock = 0.0",
		"\telse:",
		"\t\t_stuck_clock += delta",
		"\t\tif _stuck_clock >= maxf(stuck_timeout, 0.1):",
		"\t\t\t_stuck_clock = 0.0",
		"\t\t\t_best_waypoint_distance = INF",
		"\t\t\twaypoint_stuck.emit()",
		"\t\t\tfind_path_to(_path_goal.x, _path_goal.y, _goal_mode)",
		"\t\t\trepathed.emit()",
		"if debug_draw:",
		"\t_refresh_debug()"
	]))
	tick.actions.append(tick_body)
	sheet.events.append(tick)

	# ── Exposed actions ─────────────────────────────────────────────────────────────
	Lib.append_function(sheet, "build_nav_graph", "Build Nav Graph From Tilemap", "Platformer Pathfinding",
		"Scans a TileMapLayer's physics tiles into the navigation graph: standable cells become nodes, adjacent cells (one step up or down - stairs and tile slopes) become WALK edges, and jump arcs / fall drops connect the rest, sized to the sibling PlatformerMovement's real jump. Call once on ready; Regenerate after level edits. Fires On Nav Graph Built.",
		[["tilemap", "Node"]],
		"_tilemap = tilemap as TileMapLayer\nregenerate_nav_graph()")
	Lib.append_function(sheet, "regenerate_nav_graph", "Regenerate Nav Graph", "Platformer Pathfinding",
		"Rebuilds the graph from the same TileMapLayer (after runtime tile edits).",
		[],
		"\n".join(PackedStringArray([
			"_nodes.clear()",
			"_edges.clear()",
			"if _tilemap == null:",
			"\treturn",
			"var solid: Dictionary = {}",
			"for cell in _tilemap.get_used_cells():",
			"\tvar tile_data: TileData = _tilemap.get_cell_tile_data(cell)",
			"\tif tile_data != null and tile_data.get_collision_polygons_count(0) > 0:",
			"\t\tsolid[cell] = true",
			"# A standable node = a solid cell with two cells of headroom above it.",
			"for cell in solid:",
			"\tvar stand: Vector2i = cell + Vector2i(0, -1)",
			"\tif not solid.has(stand) and not solid.has(stand + Vector2i(0, -1)):",
			"\t\t_nodes[stand] = true",
			"# WALK edges: neighbours one cell over, up to one step up/down - stairs and slopes",
			"# included, at plain euclidean cost so ramps beat jumps in the router.",
			"for cell in _nodes:",
			"\tfor dx in [-1, 1]:",
			"\t\tfor dy in [-1, 0, 1]:",
			"\t\t\tvar to: Vector2i = cell + Vector2i(dx, dy)",
			"\t\t\tif _nodes.has(to):",
			"\t\t\t\t_add_edge(cell, to, \"walk\", Vector2(float(dx), float(dy)).length())",
			"# JUMP arcs + FALL drops within the derived reach, clearance-checked coarsely.",
			"var reach: Vector2i = _jump_reach_cells()",
			"var fall_cells: int = maxi(int(ceil(max_fall_distance / float(_tilemap.tile_set.tile_size.y))), 1)",
			"for cell in _nodes:",
			"\tfor dx in range(-reach.x, reach.x + 1):",
			"\t\tfor dy in range(-reach.y, fall_cells + 1):",
			"\t\t\tif absi(dx) <= 1 and absi(dy) <= 1:",
			"\t\t\t\tcontinue",
			"\t\t\tvar to: Vector2i = cell + Vector2i(dx, dy)",
			"\t\t\tif not _nodes.has(to) or not _arc_clear(cell, to, solid):",
			"\t\t\t\tcontinue",
			"\t\t\tvar kind: String = \"fall\" if dy > 0 and absi(dx) <= 2 else \"jump\"",
			"\t\t\tvar span: float = Vector2(float(dx), float(dy)).length()",
			"\t\t\t_add_edge(cell, to, kind, span * (1.5 if kind == \"jump\" else 1.1))",
			"# Registered portals survive every rebuild.",
			"for portal in _portals:",
			"\t_apply_portal(portal)",
			"nav_graph_built.emit()"
		])))
	Lib.append_function(sheet, "find_path_to", "Find Path To", "Platformer Pathfinding",
		"Routes to a world position and starts moving. Mode \"reach\" fails (On Path Failed) when the spot itself is unreachable; \"nearest\" never fails - it goes to the closest reachable node instead. Fires On Path Found / On Path Failed.",
		[["x", "float"], ["y", "float"], ["mode", "String"]],
		"\n".join(PackedStringArray([
			"# The shared budget: at most Max Paths Per Tick A* runs per physics tick ACROSS all",
			"# agents - extra requests defer to the next tick (Is Path Pending) instead of spiking.",
			"var frame: int = Engine.get_physics_frames()",
			"if frame != _shared_tick_id:",
			"\t_shared_tick_id = frame",
			"\t_shared_paths_this_tick = 0",
			"if _shared_paths_this_tick >= maxi(_shared_max_paths_per_tick, 0):",
			"\t_pending_goal = Vector2(x, y)",
			"\t_pending_goal_mode = mode",
			"\t_path_pending = true",
			"\treturn",
			"_shared_paths_this_tick += 1",
			"_path_pending = false",
			"if _tilemap == null or _nodes.is_empty():",
			"\tpush_warning(\"[PlatformerPathfinding] Find Path To called before the nav graph exists - call Build Nav Graph From Tilemap (usually On Ready) first.\")",
			"\tpath_failed.emit()",
			"\treturn",
			"if host == null:",
			"\tpath_failed.emit()",
			"\treturn",
			"var start: Vector2i = _nearest_node(host.global_position, 3)",
			"var goal: Vector2i = _nearest_node(Vector2(x, y), 2 if mode == \"reach\" else 1000000)",
			"if start == Vector2i.MAX or goal == Vector2i.MAX:",
			"\tstop_pathfinding()",
			"\tpath_failed.emit()",
			"\treturn",
			"var cells: Array = _astar(start, goal)",
			"if cells.is_empty():",
			"\tstop_pathfinding()",
			"\tpath_failed.emit()",
			"\treturn",
			"_path_goal = Vector2(x, y)",
			"_goal_mode = mode",
			"_path = []",
			"for index in range(cells.size()):",
			"\tvar action: String = \"walk\" if index == 0 else _edge_kind(cells[index - 1], cells[index])",
			"\t_path.append({\"world\": _cell_world(cells[index]), \"action\": action})",
			"_path_index = 0",
			"_jumped_this_segment = false",
			"_best_waypoint_distance = INF",
			"_stuck_clock = 0.0",
			"path_found.emit()"
		])))
	_default(sheet, "mode", "nearest")
	_param_options(sheet, "mode", ["nearest", "reach"])
	Lib.append_function(sheet, "find_path_to_node", "Find Path To Node", "Platformer Pathfinding",
		"Routes to another node's position AND keeps following it: the route auto-refreshes every Repath Interval once the node has moved Repath Threshold pixels (firing On Repath) - one call chases forever. Stop Pathfinding ends the follow.",
		[["target", "Node"], ["mode", "String"]],
		"if target is Node2D:\n\tfind_path_to((target as Node2D).global_position.x, (target as Node2D).global_position.y, mode)\n\t_follow_target = target\n\t_goal_mode = mode\n\t_repath_clock = 0.0\nelse:\n\tpath_failed.emit()")
	_default(sheet, "mode", "nearest")
	_param_options(sheet, "mode", ["nearest", "reach"])
	Lib.append_function(sheet, "stop_pathfinding", "Stop Pathfinding", "Platformer Pathfinding",
		"Clears the path and releases the movement pack back to the keyboard (ai_controlled off).",
		[],
		"\n".join(PackedStringArray([
			"_path = []",
			"_path_index = 0",
			"_move_axis = 0.0",
			"_jumped_this_segment = false",
			"_follow_target = null",
			"_path_pending = false",
			"_stuck_clock = 0.0",
			"_best_waypoint_distance = INF",
			"var movement: Node = _find_movement()",
			"if movement != null:",
			"\tmovement.set(\"ai_move_axis\", 0.0)",
			"\tmovement.set(\"ai_controlled\", false)",
			"if _debug_line != null and is_instance_valid(_debug_line):",
			"\t_debug_line.clear_points()"
		])))
	Lib.append_function(sheet, "set_auto_control", "Set Auto Control", "Platformer Pathfinding",
		"On (default): the behavior drives the sibling PlatformerMovement. Off: paths still compute - read Path Move Axis / Path Wants Jump / Current Waypoint X/Y and drive anything you like.",
		[["enabled", "bool"]],
		"auto_control = enabled\nif not enabled:\n\tvar movement: Node = _find_movement()\n\tif movement != null:\n\t\tmovement.set(\"ai_controlled\", false)")
	Lib.append_function(sheet, "set_ledge_restriction", "Set Ledge Restriction", "Platformer Pathfinding",
		"Patrol discipline: on, routes may only WALK - no jumps, no portals, and no drops beyond Ledge Leniency, so the agent stays on its platform. Applies from the next Find Path To.",
		[["enabled", "bool"]],
		"ledge_restriction = enabled")
	Lib.append_function(sheet, "set_ledge_leniency", "Set Ledge Leniency", "Platformer Pathfinding",
		"With Ledge Restriction on, drops up to this many pixels are still allowed (a patroller may hop down one step but never off the tower).",
		[["pixels", "float"]],
		"ledge_leniency = pixels")
	Lib.append_function(sheet, "set_jump_positioning", "Set Jump Positioning", "Platformer Pathfinding",
		"relaxed (default): leap the moment a jump leg starts. strict: walk onto the exact takeoff spot first - slower but precise on tight arcs.",
		[["mode", "String"]],
		"jump_positioning = mode")
	_default(sheet, "mode", "relaxed")
	_param_options(sheet, "mode", ["relaxed", "strict"])
	Lib.append_function(sheet, "set_coyote_time", "Set Coyote Time", "Platformer Pathfinding",
		"Grace window (s) for AI jumps just after running off the takeoff ledge.",
		[["seconds", "float"]],
		"coyote_time = seconds")
	Lib.append_function(sheet, "set_repath_interval", "Set Repath Interval", "Platformer Pathfinding",
		"While following a node, how often the route may refresh (chase freshness vs cost).",
		[["seconds", "float"]],
		"repath_interval = seconds")
	Lib.append_function(sheet, "set_repath_threshold", "Set Repath Threshold", "Platformer Pathfinding",
		"The route only refreshes when the followed node has moved at least this many pixels.",
		[["pixels", "float"]],
		"repath_threshold = pixels")
	Lib.append_function(sheet, "set_max_paths_per_tick", "Set Max Paths Per Tick", "Platformer Pathfinding",
		"The SHARED budget across every agent: at most this many route computations per physics tick - extras defer a tick (Is Path Pending) instead of spiking the frame. The difference between 20 chasers working and not.",
		[["count", "int"]],
		"_shared_max_paths_per_tick = count")
	Lib.append_function(sheet, "add_portal", "Add Portal", "Platformer Pathfinding",
		"Links two world positions as a PORTAL: an agent whose route uses it walks to the entrance and blinks to the exit (fires On Portal Taken). Bidirectional works both ways. Portals join the graph immediately and survive Regenerate - doors, teleporters, ladders, and elevators all model as portals.",
		[["from_x", "float"], ["from_y", "float"], ["to_x", "float"], ["to_y", "float"], ["bidirectional", "bool"]],
		"\n".join(PackedStringArray([
			"var portal: Dictionary = {\"from\": Vector2(from_x, from_y), \"to\": Vector2(to_x, to_y), \"both\": bidirectional}",
			"_portals.append(portal)",
			"if not _nodes.is_empty():",
			"\t_apply_portal(portal)"
		])))
	Lib.append_function(sheet, "clear_portals", "Clear Portals", "Platformer Pathfinding",
		"Removes every registered portal (takes effect on the next Regenerate Nav Graph).",
		[],
		"_portals = []\nregenerate_nav_graph()")
	Lib.append_function(sheet, "set_nav_debug_draw", "Set Nav Debug Draw", "Platformer Pathfinding",
		"Draws the active path as a line in the world (great while tuning a level).",
		[["enabled", "bool"]],
		"debug_draw = enabled\n_refresh_debug()")

	return Lib.save_pack(sheet, "res://eventsheet_addons/platformer_pathfinding/platformer_pathfinding_behavior")


## Pre-fills the last-appended ACE's parameter default (authoring-time metadata only).
static func _default(sheet: EventSheetResource, param_id: String, value: String) -> void:
	var fn: EventFunction = sheet.functions[sheet.functions.size() - 1]
	for parameter: ACEParam in fn.params:
		if parameter.id == param_id:
			parameter.default_value = value


## Sets the dropdown options[] on the last-appended ACE's parameter.
static func _param_options(sheet: EventSheetResource, param_id: String, choices: Array) -> void:
	var typed: Array[String] = []
	for choice: Variant in choices:
		typed.append(str(choice))
	var fn: EventFunction = sheet.functions[sheet.functions.size() - 1]
	for parameter: ACEParam in fn.params:
		if parameter.id == param_id:
			parameter.options = typed
