# Pack builder - stat_forge (one pack per file; run via tools/build_sample_behaviors.gd).
@tool

const Lib := preload("res://tools/pack_builders/_lib.gd")


## StatForge: modifiable stats as a per-node BUFF STACK - every modifier (weapon bonus,
## potion, curse, difficulty scale) is a named buff that targets one stat with one value and
## one mode (add / multiply / override), optionally for a duration. Reading the computed
## value is always one expression: Stat Total("speed"). Tags and sources group buffs for
## bulk operations, threshold rules fire when a stat crosses a value, and a StatSheetResource
## loads whole loadouts as .tres data. Complexity scales: two verbs run an RPG stat; the
## rest is there when you need it.
static func build() -> bool:
	var sheet: EventSheetResource = EventSheetResource.new()
	sheet.behavior_mode = true
	sheet.host_class = "Node"
	sheet.custom_class_name = "StatForge"
	sheet.class_description = "Real, modifiable stats for any node: every modifier that touches its numbers is a named buff that adds, multiplies, or overrides one stat, optionally tagged, sourced, and auto-expiring. Reading the computed result is always one expression - Stat Total."
	sheet.addon_category = "StatForge"
	sheet.addon_tags = PackedStringArray(["stats", "rpg", "data"])
	var about: CommentRow = CommentRow.new()
	about.text = "StatForge behavior: stats as a per-node buff stack. Add Buff targets a stat with a value and a mode - add / multiply / override (highest override wins) - with optional TAGS, a SOURCE, and a DURATION that expires on its own. Stat Total computes (base + adds) * multipliers, clamped or wrapped by the overflow knobs. Remove by id, tag, or source; pause and refresh timers; threshold rules fire On Threshold Crossed when a stat crosses a value. Load whole loadouts from a StatSheetResource (.tres). Two verbs run an RPG stat; the rest scales with your game. This pack is an event sheet - extend it by editing it."
	sheet.events.append(about)

	var block: RawCodeRow = RawCodeRow.new()
	block.code = "\n".join(PackedStringArray([
		"# --- Designer knobs (tune in the Inspector) ---",
		"## Temporary buffs count down automatically every frame. Off: drive time yourself",
		"## with Advance Timers (turn-based games advance per turn).",
		"@export var auto_tick: bool = true",
		"## What happens when a computed total leaves the min/max range: clamp stops at the",
		"## boundary, wrap loops around, none applies no limit.",
		"@export_enum(\"clamp\", \"wrap\", \"none\") var overflow_mode: String = \"clamp\"",
		"## The smallest allowed stat total (clamp/wrap modes).",
		"@export var min_value: float = -99999.0",
		"## The largest allowed stat total (clamp/wrap modes).",
		"@export var max_value: float = 99999.0",
		"",
		"# --- Internal state ---",
		"# buff id -> {stat, value, mode, tags: Array[String], source, active, time_left (-1 =",
		"# permanent), duration, paused}. Ids are unique per node: re-adding replaces.",
		"var _buffs: Dictionary = {}",
		"var _bases: Dictionary = {}",
		"# rule id -> {stat, value, direction, repeating, armed}",
		"var _rules: Dictionary = {}",
		"var _last_totals: Dictionary = {}",
		"var _last_expired: String = \"\"",
		"var _last_rule: String = \"\"",
		"",
		"## @ace_trigger",
		"## @ace_name(\"On Buff Added\")",
		"signal buff_added(buff_id: String, stat: String)",
		"",
		"## @ace_trigger",
		"## @ace_name(\"On Buff Removed\")",
		"signal buff_removed(buff_id: String, stat: String)",
		"",
		"## @ace_trigger",
		"## @ace_name(\"On Buff Expired\")",
		"signal buff_expired(buff_id: String, stat: String)",
		"",
		"## @ace_trigger",
		"## @ace_name(\"On Threshold Crossed\")",
		"signal threshold_crossed(rule_id: String, stat: String, total: float)",
		"",
		"## The stat computation: (base + active adds) * active multipliers - unless active",
		"## OVERRIDE buffs exist, where the HIGHEST override wins outright. Overflow applies",
		"## last (clamp / wrap / none).",
		"## @ace_expression",
		"## @ace_name(\"Stat Total\")",
		"func stat_total(stat: String) -> float:",
		"\tvar total: float = float(_bases.get(stat, 0.0))",
		"\tvar multiplier: float = 1.0",
		"\tvar best_override: float = -INF",
		"\tvar has_override: bool = false",
		"\tfor buff: Dictionary in _buffs.values():",
		"\t\tif str(buff[\"stat\"]) != stat or not bool(buff[\"active\"]):",
		"\t\t\tcontinue",
		"\t\tmatch str(buff[\"mode\"]):",
		"\t\t\t\"add\":",
		"\t\t\t\ttotal += float(buff[\"value\"])",
		"\t\t\t\"multiply\":",
		"\t\t\t\tmultiplier *= float(buff[\"value\"])",
		"\t\t\t\"override\":",
		"\t\t\t\thas_override = true",
		"\t\t\t\tbest_override = maxf(best_override, float(buff[\"value\"]))",
		"\tvar result: float = best_override if has_override else total * multiplier",
		"\tmatch overflow_mode:",
		"\t\t\"clamp\":",
		"\t\t\tresult = clampf(result, min_value, max_value)",
		"\t\t\"wrap\":",
		"\t\t\tif max_value > min_value:",
		"\t\t\t\tresult = fposmod(result - min_value, max_value - min_value) + min_value",
		"\treturn result",
		"",
		"## @ace_expression",
		"## @ace_name(\"Stat Base\")",
		"func stat_base(stat: String) -> float:",
		"\treturn float(_bases.get(stat, 0.0))",
		"",
		"## @ace_expression",
		"## @ace_name(\"Buff Value\")",
		"func buff_value(buff_id: String) -> float:",
		"\treturn float((_buffs.get(buff_id, {}) as Dictionary).get(\"value\", 0.0))",
		"",
		"## Seconds left on a timed buff (-1 = permanent or unknown).",
		"## @ace_expression",
		"## @ace_name(\"Buff Time Left\")",
		"func buff_time_left(buff_id: String) -> float:",
		"\treturn float((_buffs.get(buff_id, {}) as Dictionary).get(\"time_left\", -1.0))",
		"",
		"## @ace_expression",
		"## @ace_name(\"Buff Count\")",
		"func buff_count() -> int:",
		"\treturn _buffs.size()",
		"",
		"## @ace_expression",
		"## @ace_name(\"Buff Count With Tag\")",
		"func buff_count_with_tag(tag: String) -> int:",
		"\tvar count: int = 0",
		"\tfor buff: Dictionary in _buffs.values():",
		"\t\tif (buff[\"tags\"] as Array).has(tag):",
		"\t\t\tcount += 1",
		"\treturn count",
		"",
		"## The buff that expired most recently - read it inside On Buff Expired.",
		"## @ace_expression",
		"## @ace_name(\"Last Expired Buff\")",
		"func last_expired_buff() -> String:",
		"\treturn _last_expired",
		"",
		"## The rule that fired most recently - read it inside On Threshold Crossed.",
		"## @ace_expression",
		"## @ace_name(\"Last Threshold Rule\")",
		"func last_threshold_rule() -> String:",
		"\treturn _last_rule",
		"",
		"## Loops the event's actions once per applied buff id (a LOOPING condition: adding it",
		"## creates the loop) - read details per pass with Buff Value / Buff Time Left.",
		"## @ace_looping(buff_id)",
		"## @ace_name(\"For Each Buff\")",
		"func each_buff() -> Array:",
		"\treturn _buffs.keys()",
		"",
		"## @ace_condition",
		"## @ace_name(\"Has Buff\")",
		"func has_buff(buff_id: String) -> bool:",
		"\treturn _buffs.has(buff_id)",
		"",
		"## @ace_condition",
		"## @ace_name(\"Buff Is Active\")",
		"func buff_is_active(buff_id: String) -> bool:",
		"\treturn bool((_buffs.get(buff_id, {}) as Dictionary).get(\"active\", false))",
		"",
		"## @ace_condition",
		"## @ace_name(\"Has Buffs With Tag\")",
		"func has_buffs_with_tag(tag: String) -> bool:",
		"\treturn buff_count_with_tag(tag) > 0",
		"",
		"## @ace_condition",
		"## @ace_name(\"Has Buffs From Source\")",
		"func has_buffs_from_source(source: String) -> bool:",
		"\tfor buff: Dictionary in _buffs.values():",
		"\t\tif str(buff[\"source\"]) == source:",
		"\t\t\treturn true",
		"\treturn false",
		"",
		"## The beginner-friendly stat compare (Stat Total works in any expression too).",
		"## @ace_condition",
		"## @ace_name(\"Stat Is At Least\")",
		"func stat_is_at_least(stat: String, value: float) -> bool:",
		"\treturn stat_total(stat) >= value"
	]))
	sheet.events.append(block)

	# The verb surface, annotated raw block (typed params + option combos).
	var verbs: RawCodeRow = RawCodeRow.new()
	verbs.code = "\n".join(PackedStringArray([
		"## The one verb that runs the whole system: a named buff targeting a stat with a",
		"## value and a mode (add / multiply / override - highest override wins). Tags are",
		"## comma-separated labels for bulk ops, source names who applied it, duration in",
		"## seconds expires it (0 = permanent). Re-adding an id REPLACES that buff.",
		"## @ace_action",
		"## @ace_name(\"Add Buff\")",
		"## @ace_param_options(mode add, multiply, override)",
		"func add_buff(buff_id: String, stat: String, value: float, mode: String = \"add\", tags: String = \"\", source: String = \"\", duration: float = 0.0) -> void:",
		"\tif buff_id.is_empty() or stat.is_empty() or not mode in [\"add\", \"multiply\", \"override\"]:",
		"\t\treturn",
		"\tvar tag_list: Array[String] = []",
		"\tfor tag: String in tags.split(\",\", false):",
		"\t\ttag_list.append(tag.strip_edges())",
		"\t_buffs[buff_id] = {\"stat\": stat, \"value\": value, \"mode\": mode, \"tags\": tag_list, \"source\": source, \"active\": true, \"time_left\": duration if duration > 0.0 else -1.0, \"duration\": duration, \"paused\": false}",
		"\tbuff_added.emit(buff_id, stat)",
		"\t_check_thresholds()",
		"",
		"## Removes one buff by id (a no-op when absent).",
		"## @ace_action",
		"## @ace_name(\"Remove Buff\")",
		"func remove_buff(buff_id: String) -> void:",
		"\tif not _buffs.has(buff_id):",
		"\t\treturn",
		"\tvar stat: String = str((_buffs[buff_id] as Dictionary)[\"stat\"])",
		"\t_buffs.erase(buff_id)",
		"\tbuff_removed.emit(buff_id, stat)",
		"\t_check_thresholds()",
		"",
		"## Removes every buff carrying the tag - unequip all \"equipment\" in one action.",
		"## @ace_action",
		"## @ace_name(\"Remove Buffs By Tag\")",
		"func remove_buffs_by_tag(tag: String) -> void:",
		"\tfor buff_id: String in _buffs.keys().duplicate():",
		"\t\tif ((_buffs[buff_id] as Dictionary)[\"tags\"] as Array).has(tag):",
		"\t\t\tremove_buff(buff_id)",
		"",
		"## Removes every buff a source applied - clear one enemy's curses when it dies.",
		"## @ace_action",
		"## @ace_name(\"Remove Buffs By Source\")",
		"func remove_buffs_by_source(source: String) -> void:",
		"\tfor buff_id: String in _buffs.keys().duplicate():",
		"\t\tif str((_buffs[buff_id] as Dictionary)[\"source\"]) == source:",
		"\t\t\tremove_buff(buff_id)",
		"",
		"## Empties the whole stack (bases stay).",
		"## @ace_action",
		"## @ace_name(\"Clear Buffs\")",
		"func clear_buffs() -> void:",
		"\t_buffs.clear()",
		"\t_check_thresholds()",
		"",
		"## Sets a stat's base value - the number the buff math starts from.",
		"## @ace_action",
		"## @ace_name(\"Set Stat Base\")",
		"func set_stat_base(stat: String, value: float) -> void:",
		"\t_bases[stat] = value",
		"\t_check_thresholds()",
		"",
		"## Turns one buff on or off WITHOUT removing it - inactive buffs stay in the stack",
		"## but contribute nothing (a stance toggle, a disabled rune).",
		"## @ace_action",
		"## @ace_name(\"Set Buff Active\")",
		"func set_buff_active(buff_id: String, active: bool) -> void:",
		"\tif _buffs.has(buff_id):",
		"\t\t(_buffs[buff_id] as Dictionary)[\"active\"] = active",
		"\t\t_check_thresholds()",
		"",
		"## Bulk activation by tag - silence every \"aura\" buff in an antimagic zone.",
		"## @ace_action",
		"## @ace_name(\"Set Buffs Active By Tag\")",
		"func set_buffs_active_by_tag(tag: String, active: bool) -> void:",
		"\tfor buff: Dictionary in _buffs.values():",
		"\t\tif (buff[\"tags\"] as Array).has(tag):",
		"\t\t\tbuff[\"active\"] = active",
		"\t_check_thresholds()",
		"",
		"## Changes a live buff's value in place (a stacking poison that deepens).",
		"## @ace_action",
		"## @ace_name(\"Set Buff Value\")",
		"func set_buff_value(buff_id: String, value: float) -> void:",
		"\tif _buffs.has(buff_id):",
		"\t\t(_buffs[buff_id] as Dictionary)[\"value\"] = value",
		"\t\t_check_thresholds()",
		"",
		"## Restarts a timed buff's countdown (re-drinking the potion refreshes, not stacks).",
		"## @ace_action",
		"## @ace_name(\"Refresh Buff\")",
		"func refresh_buff(buff_id: String, duration: float) -> void:",
		"\tif _buffs.has(buff_id) and duration > 0.0:",
		"\t\tvar buff: Dictionary = _buffs[buff_id]",
		"\t\tbuff[\"time_left\"] = duration",
		"\t\tbuff[\"duration\"] = duration",
		"",
		"## Freezes/unfreezes one buff's countdown (cutscenes, pause-adjacent states).",
		"## @ace_action",
		"## @ace_name(\"Set Buff Timer Paused\")",
		"func set_buff_timer_paused(buff_id: String, paused: bool) -> void:",
		"\tif _buffs.has(buff_id):",
		"\t\t(_buffs[buff_id] as Dictionary)[\"paused\"] = paused",
		"",
		"## Advances every unpaused timer by the given seconds - the manual clock for",
		"## turn-based games (turn ends: Advance Timers 1).",
		"## @ace_action",
		"## @ace_name(\"Advance Timers\")",
		"func advance_timers(seconds: float) -> void:",
		"\tvar expired: Array[String] = []",
		"\tfor buff_id: String in _buffs:",
		"\t\tvar buff: Dictionary = _buffs[buff_id]",
		"\t\tif float(buff[\"time_left\"]) < 0.0 or bool(buff[\"paused\"]):",
		"\t\t\tcontinue",
		"\t\tbuff[\"time_left\"] = float(buff[\"time_left\"]) - seconds",
		"\t\tif float(buff[\"time_left\"]) <= 0.0:",
		"\t\t\texpired.append(buff_id)",
		"\tfor buff_id: String in expired:",
		"\t\tvar stat: String = str((_buffs[buff_id] as Dictionary)[\"stat\"])",
		"\t\t_buffs.erase(buff_id)",
		"\t\t_last_expired = buff_id",
		"\t\tbuff_expired.emit(buff_id, stat)",
		"\tif not expired.is_empty():",
		"\t\t_check_thresholds()",
		"",
		"## Watches a stat and fires On Threshold Crossed when its total crosses the value.",
		"## Direction rising / falling / both; a repeating rule re-arms once the stat is back",
		"## across, a one-shot stays spent until Re-Arm Threshold Rule.",
		"## @ace_action",
		"## @ace_name(\"Add Threshold Rule\")",
		"## @ace_param_options(direction rising, falling, both)",
		"func add_threshold_rule(rule_id: String, stat: String, value: float, direction: String = \"rising\", repeating: bool = true) -> void:",
		"\tif rule_id.is_empty() or stat.is_empty() or not direction in [\"rising\", \"falling\", \"both\"]:",
		"\t\treturn",
		"\t_rules[rule_id] = {\"stat\": stat, \"value\": value, \"direction\": direction, \"repeating\": repeating, \"armed\": true}",
		"\t_last_totals[stat] = stat_total(stat)",
		"",
		"## @ace_action",
		"## @ace_name(\"Remove Threshold Rule\")",
		"func remove_threshold_rule(rule_id: String) -> void:",
		"\t_rules.erase(rule_id)",
		"",
		"## Re-arms a spent one-shot rule so it can fire again.",
		"## @ace_action",
		"## @ace_name(\"Re-Arm Threshold Rule\")",
		"func rearm_threshold_rule(rule_id: String) -> void:",
		"\tif _rules.has(rule_id):",
		"\t\t(_rules[rule_id] as Dictionary)[\"armed\"] = true",
		"",
		"## Applies a StatSheetResource (.tres): its bases set stat bases, its buff rows Add",
		"## Buff one by one IN ORDER - whole loadouts, classes, and difficulty presets as data.",
		"## @ace_action",
		"## @ace_name(\"Load Stat Sheet\")",
		"func load_stat_sheet(stat_sheet: Resource) -> void:",
		"\tif stat_sheet == null:",
		"\t\treturn",
		"\tvar bases: Variant = stat_sheet.get(\"bases\")",
		"\tif bases is Array:",
		"\t\tfor row: Variant in bases:",
		"\t\t\tif row is Dictionary:",
		"\t\t\t\tset_stat_base(str((row as Dictionary).get(\"stat\", \"\")), float((row as Dictionary).get(\"value\", 0.0)))",
		"\tvar buffs: Variant = stat_sheet.get(\"buffs\")",
		"\tif buffs is Array:",
		"\t\tfor row: Variant in buffs:",
		"\t\t\tif row is Dictionary:",
		"\t\t\t\tvar entry: Dictionary = row",
		"\t\t\t\tadd_buff(str(entry.get(\"buff_id\", \"\")), str(entry.get(\"stat\", \"\")), float(entry.get(\"value\", 0.0)), str(entry.get(\"mode\", \"add\")), str(entry.get(\"tags\", \"\")), str(entry.get(\"source\", \"\")), float(entry.get(\"duration\", 0.0)))",
		"",
		"## Crossing detection: compares each watched stat's total to its last-seen value and",
		"## fires armed rules whose boundary sits between them. Runs after every mutation and",
		"## every timer expiry, so thresholds never miss a change.",
		"## @ace_hidden",
		"func _check_thresholds() -> void:",
		"\tif _rules.is_empty():",
		"\t\treturn",
		"\tvar new_totals: Dictionary = {}",
		"\tfor rule_id: String in _rules:",
		"\t\tvar rule: Dictionary = _rules[rule_id]",
		"\t\tvar stat: String = str(rule[\"stat\"])",
		"\t\tif not new_totals.has(stat):",
		"\t\t\tnew_totals[stat] = stat_total(stat)",
		"\t\tvar now: float = float(new_totals[stat])",
		"\t\tvar before: float = float(_last_totals.get(stat, now))",
		"\t\tvar edge: float = float(rule[\"value\"])",
		"\t\tvar rose: bool = before < edge and now >= edge",
		"\t\tvar fell: bool = before > edge and now <= edge",
		"\t\tvar crossed: bool = (rose and str(rule[\"direction\"]) != \"falling\") or (fell and str(rule[\"direction\"]) != \"rising\")",
		"\t\tif crossed and bool(rule[\"armed\"]):",
		"\t\t\tif not bool(rule[\"repeating\"]):",
		"\t\t\t\trule[\"armed\"] = false",
		"\t\t\t_last_rule = rule_id",
		"\t\t\tthreshold_crossed.emit(rule_id, stat, now)",
		"\tfor stat: String in new_totals:",
		"\t\t_last_totals[stat] = new_totals[stat]"
	]))
	sheet.events.append(verbs)

	# Auto-tick: temporary buffs count down every physics frame.
	var tick: EventRow = EventRow.new()
	tick.trigger_provider_id = "Core"
	tick.trigger_id = "OnPhysicsProcess"
	var tick_body: RawCodeRow = RawCodeRow.new()
	tick_body.code = "if auto_tick:\n\tadvance_timers(delta)"
	tick.actions.append(tick_body)
	sheet.events.append(tick)

	var persistence: RawCodeRow = RawCodeRow.new()
	persistence.code = "\n".join(PackedStringArray([
		"# Save-state seam: the Save System walks any node in its persist group (or targeted",
		"# by Save/Load Node State) and duck-types these two methods. Plain data only.",
		"## @ace_hidden",
		"func save_state() -> Dictionary:",
		"\treturn {",
		"\t\t\"bases\": _bases.duplicate(true),",
		"\t\t\"buffs\": _buffs.duplicate(true),",
		"\t\t\"rules\": _rules.duplicate(true),",
		"\t\t\"last_totals\": _last_totals.duplicate(true)",
		"\t}",
		"",
		"## @ace_hidden",
		"func load_state(state: Dictionary) -> void:",
		"\tif state.is_empty():",
		"\t\treturn",
		"\t_bases = (state.get(\"bases\", {}) as Dictionary).duplicate(true)",
		"\t_buffs = (state.get(\"buffs\", {}) as Dictionary).duplicate(true)",
		"\t_rules = (state.get(\"rules\", {}) as Dictionary).duplicate(true)",
		"\t# Restoring the last-seen totals keeps threshold rules from spuriously re-firing",
		"\t# on the first change after a load.",
		"\t_last_totals = (state.get(\"last_totals\", {}) as Dictionary).duplicate(true)"
	]))
	sheet.events.append(persistence)

	return Lib.save_pack(sheet, "res://eventsheet_addons/stat_forge/stat_forge_behavior")
