# AUTO-GENERATED by EventForge v0.9.0
# Source: res://eventsheet_addons/bullet/bullet_behavior.tres
# DO NOT EDIT — this file is regenerated on every compile.

class_name BulletBehavior
extends Node

## The node this behavior acts on (its parent). Required host: Node2D.
var host: Node2D = null

func _enter_tree() -> void:
	host = get_parent() as Node2D
	if host == null:
		push_warning("BulletBehavior behavior requires a Node2D parent.")

@export var acceleration: float = 0.0
@export var align_rotation: bool = true
var distance_travelled: float = 0.0
@export var enabled_movement: bool = true
@export var gravity: float = 0.0
var launched: bool = false
@export var speed: float = 300.0
var vel_x: float = 0.0
var vel_y: float = 0.0

func _process(delta: float) -> void:
	if host == null or not enabled_movement:
		return
	if not launched:
		vel_x = cos(host.rotation) * speed
		vel_y = sin(host.rotation) * speed
		launched = true
	var direction := Vector2(vel_x, vel_y).normalized()
	vel_x += direction.x * acceleration * delta
	vel_y += direction.y * acceleration * delta
	vel_y += gravity * delta
	var motion := Vector2(vel_x, vel_y) * delta
	host.position += motion
	distance_travelled += motion.length()
	if align_rotation and motion != Vector2.ZERO:
		host.rotation = motion.angle()

## @ace_action
## @ace_name("Set Bullet Speed")
## @ace_category("Bullet")
## @ace_description("Changes speed, keeping the current direction.")
## @ace_codegen_template("$BulletBehavior.set_bullet_speed({value})")
func set_bullet_speed(value: float) -> void:
	speed = value
	var direction := Vector2(vel_x, vel_y).normalized()
	if direction == Vector2.ZERO and host != null:
		direction = Vector2.from_angle(host.rotation)
	vel_x = direction.x * value
	vel_y = direction.y * value
	launched = true

## @ace_action
## @ace_name("Set Angle Of Motion")
## @ace_category("Bullet")
## @ace_description("Redirects the bullet (degrees).")
## @ace_codegen_template("$BulletBehavior.set_angle_of_motion({degrees})")
func set_angle_of_motion(degrees: float) -> void:
	vel_x = cos(deg_to_rad(degrees)) * speed
	vel_y = sin(deg_to_rad(degrees)) * speed
	launched = true

## @ace_action
## @ace_name("Set Bullet Enabled")
## @ace_category("Bullet")
## @ace_description("Pauses or resumes the movement.")
## @ace_codegen_template("$BulletBehavior.set_bullet_enabled({is_enabled})")
func set_bullet_enabled(is_enabled: bool) -> void:
	enabled_movement = is_enabled

# Bullet behavior (C3 parity): angle-of-motion movement with acceleration and gravity; tracks distance travelled (read $BulletBehavior.distance_travelled).
