# AUTO-GENERATED by EventForge v0.1.0
# Source: res://eventsheet_addons/bullet/bullet_behavior.tres
# DO NOT EDIT — this file is regenerated on every compile.

class_name BulletBehavior
extends Node

## The node this behavior acts on (its parent). Required host: Node2D.
var host: Node2D = null

func _enter_tree() -> void:
	host = get_parent() as Node2D
	if host == null:
		push_warning("BulletBehavior behavior requires a Node2D parent.")

@export var acceleration: float = 0.0
@export var align_rotation: bool = true
@export var gravity: float = 0.0
var launched: bool = false
@export var speed: float = 300.0
var vel_x: float = 0.0
var vel_y: float = 0.0

func _process(delta: float) -> void:
	if host == null:
		return
	if not launched:
		vel_x = cos(host.rotation) * speed
		vel_y = sin(host.rotation) * speed
		launched = true
	var direction := Vector2(vel_x, vel_y).normalized()
	vel_x += direction.x * acceleration * delta
	vel_y += direction.y * acceleration * delta + 0.0
	vel_y += gravity * delta
	host.position += Vector2(vel_x, vel_y) * delta
	if align_rotation and (vel_x != 0.0 or vel_y != 0.0):
		host.rotation = Vector2(vel_x, vel_y).angle()

## @ace_action
## @ace_name("Set Bullet Speed")
## @ace_category("Bullet")
## @ace_description("Changes speed, keeping the current direction.")
## @ace_codegen_template("$BulletBehavior.set_bullet_speed({value})")
func set_bullet_speed(value: float) -> void:
	speed = value
	var direction := Vector2(vel_x, vel_y).normalized()
	if direction == Vector2.ZERO and host != null:
		direction = Vector2.from_angle(host.rotation)
	vel_x = direction.x * value
	vel_y = direction.y * value
	launched = true

## @ace_action
## @ace_name("Set Angle Of Motion")
## @ace_category("Bullet")
## @ace_description("Redirects the bullet (degrees).")
## @ace_codegen_template("$BulletBehavior.set_angle_of_motion({degrees})")
func set_angle_of_motion(degrees: float) -> void:
	vel_x = cos(deg_to_rad(degrees)) * speed
	vel_y = sin(deg_to_rad(degrees)) * speed
	launched = true

# Bullet behavior (C3-style): moves at the host's angle of motion with acceleration and gravity.
