# EventSheets test - the Declare group and the declarations the Doctor can hear going unused.
#
# Two halves. The Add menu grows one "Declare" submenu offering every way to give something a
# name - each entry opening the SAME dialog its scattered sibling opens, so this pins the menu's
# structure and its routing rather than re-testing the dialogs. And the Doctor's tidiness sweep
# gains two pure judgements - an enum value nothing in the project ever names, and a signal
# announced but never heard - pinned here over plain text tables, never by planting a broken
# fixture in the repository (which would make the repo's own audit report the finding forever).
@tool
class_name DeclarationFamilyTest
extends RefCounted


class NoopUndoManager:
	extends RefCounted
	func create_action(_a = null) -> void: pass
	func add_do_method(_a = null, _b = null, _c = null, _d = null, _e = null) -> void: pass
	func add_undo_method(_a = null, _b = null, _c = null, _d = null, _e = null) -> void: pass
	func commit_action() -> void: pass
	func has_undo() -> bool: return false
	func has_redo() -> bool: return false


static func run() -> bool:
	var all_passed: bool = true

	# ── The Declare submenu: seven entries, pinned by label so a rename or a loss is named ──
	var editor: EventSheetEditor = EventSheetEditor.new()
	editor.setup(EventSheetResource.new())
	editor.set_undo_redo_manager(NoopUndoManager.new())
	var add_menu: MenuButton = editor._toolbar.find_child("EventSheetAddMenu", true, false) as MenuButton
	var declare_popup: PopupMenu = add_menu.get_popup().find_child("EventSheetDeclareMenu", true, false) as PopupMenu
	all_passed = _check("the Add menu carries a Declare submenu", declare_popup != null, true) and all_passed
	if declare_popup != null:
		var labels: PackedStringArray = PackedStringArray()
		for item_index: int in declare_popup.item_count:
			labels.append(declare_popup.get_item_text(item_index))
		all_passed = _check("Declare offers the seven declaration shapes", labels,
			PackedStringArray(["Variable…", "Constant…", "Node reference…", "Resource…",
				"Enum…", "Signal…", "Collection…"])) and all_passed
	# The submenu item on the Add menu itself, addressed by its own id (the explicit wiring the
	# menu-id test enforces).
	var add_popup: PopupMenu = add_menu.get_popup()
	all_passed = _check("the Declare submenu answers to its own id",
		add_popup.get_item_text(add_popup.get_item_index(11)), "Declare") and all_passed
	# Routing: every declare handler the submenu names must exist on the add-row helper, so a
	# renamed handler cannot leave a dead menu entry behind.
	for handler_name: String in ["on_declare_constant_requested", "on_declare_node_reference_requested",
			"on_declare_collection_requested", "on_declare_enum_requested", "on_declare_signal_requested"]:
		all_passed = _check("add-row helper answers %s" % handler_name,
			editor._add_rows.has_method(handler_name), true) and all_passed
	editor.free()

	# ── Dead enum values: parsed from both emitted shapes, judged against the corpus ──
	var generated: String = "# AUTO-GENERATED by EventForge\n" \
		+ "enum Mode { IDLE, RUN, HURT = 4 }\n" \
		+ "enum Phase {\n\tINTRO,\n\tBOSS,\n}\n"
	all_passed = _check("an unnamed value in each shape is found",
		EventSheetDoctorTidiness.dead_enum_values(generated,
			generated + "\nmatch mode:\n\tMode.IDLE:\n\t\tpass\nif phase == Phase.BOSS: pass"),
		PackedStringArray(["Mode.RUN", "Mode.HURT", "Phase.INTRO"])) and all_passed
	all_passed = _check("a value named anywhere in the corpus is not dead",
		EventSheetDoctorTidiness.dead_enum_values("enum Mode { IDLE }", "hud.gd says Mode.IDLE here"),
		PackedStringArray()) and all_passed
	all_passed = _check("the declaration alone never counts as a use",
		EventSheetDoctorTidiness.dead_enum_values("enum Mode { IDLE }", "enum Mode { IDLE }"),
		PackedStringArray(["Mode.IDLE"])) and all_passed
	all_passed = _check("a look-alike member of another enum does not excuse a dead one",
		EventSheetDoctorTidiness.dead_enum_values("enum Mode { IDLE }", "Other.IDLE"),
		PackedStringArray(["Mode.IDLE"])) and all_passed

	# ── Unheard signals: every way of listening counts, emitting does not ──
	var announcing: String = "signal hit(amount: int)\nsignal healed\nsignal drained\nsignal ignored\n"
	all_passed = _check("only the signal nothing listens to is unheard",
		EventSheetDoctorTidiness.unheard_signals(announcing,
			"boss.hit.connect(_on_hit)\nawait player.healed\nhit.emit(3)\nignored.emit()",
			"[connection signal=\"drained\" from=\".\" to=\"HUD\" method=\"_on_drained\"]"),
		PackedStringArray(["ignored"])) and all_passed
	all_passed = _check("emitting is announcing, never hearing",
		EventSheetDoctorTidiness.unheard_signals("signal hit", "hit.emit(1)\nhit.emit(2)", ""),
		PackedStringArray(["hit"])) and all_passed
	all_passed = _check("a name handed around as a string is given the benefit of the doubt",
		EventSheetDoctorTidiness.unheard_signals("signal hit", "connect(\"hit\", something)", ""),
		PackedStringArray()) and all_passed
	all_passed = _check("a longer name containing this one is not a connection to it",
		EventSheetDoctorTidiness.unheard_signals("signal hit", "on_hit.connect(_x)", ""),
		PackedStringArray(["hit"])) and all_passed

	return all_passed


static func _check(label: String, actual: Variant, expected: Variant) -> bool:
	if actual == expected:
		print("[PASS] declaration_family_test: %s" % label)
		return true
	print("[FAIL] declaration_family_test: %s" % label)
	print("  expected: %s" % str(expected))
	print("  actual:   %s" % str(actual))
	return false
