# Godot EventSheets - the Doctor check for a signal-backed trigger whose signal was never declared.
#
# On Failure Of, On Success Of, On Scene Spawned and On Data File Changed bind to a signal the SHEET
# declares. The compiler is careful about the missing case: it emits the handler but no connection,
# so nothing breaks and nothing runs. That is the failure worth a check - the row sits on the canvas
# looking finished, its recovery branch never fires, and the game gives no hint at all.
#
# Both halves are proved: the pure rule against hand-written sources, and the whole path through the
# REAL compiler - the same sheet built with the Signal row and without it.
@tool
class_name UndeclaredTriggerSignalDoctorTest
extends RefCounted

const HEADER := "# AUTO-GENERATED by EventForge v0.0.0\n"


static func run() -> bool:
	var passed: bool = true
	passed = _test_rule() and passed
	passed = _test_against_real_compiler_output() and passed
	return passed


## The rule itself: an unconnectable handler in GENERATED code is the finding, and a declaration -
## in any of its written forms - clears it.
static func _test_rule() -> bool:
	var orphan: String = HEADER + "extends Node\n\n\nfunc _on_verb_failed(verb_id: String, reason: String) -> void:\n\tprint(reason)\n"
	var passed: bool = _check("a trigger handler nothing can call is reported",
		str(EventSheetProjectDoctor.unconnected_trigger_signals(orphan)), "[\"verb_failed\"]")
	var declared: String = HEADER + "extends Node\n\nsignal verb_failed(verb_id: String, reason: String)\n\n\nfunc _ready() -> void:\n\tverb_failed.connect(_on_verb_failed)\n\n\nfunc _on_verb_failed(verb_id: String, reason: String) -> void:\n\tprint(reason)\n"
	passed = _check("declaring the signal clears it",
		EventSheetProjectDoctor.unconnected_trigger_signals(declared).is_empty(), true) and passed
	var argumentless: String = HEADER + "extends Node\n\nsignal scene_spawned\n\n\nfunc _on_scene_spawned(spawn_name: String, node: Node) -> void:\n\tprint(spawn_name)\n"
	passed = _check("an argumentless declaration counts as a declaration",
		EventSheetProjectDoctor.unconnected_trigger_signals(argumentless).is_empty(), true) and passed
	var emitter_only: String = HEADER + "extends Node\n\n\nfunc report() -> void:\n\tif has_signal(&\"verb_failed\"):\n\t\temit_signal(&\"verb_failed\", \"save_game\", \"nope\")\n"
	passed = _check("a guarded Report Failure on a sheet with no trigger is NOT a finding",
		EventSheetProjectDoctor.unconnected_trigger_signals(emitter_only).is_empty(), true) and passed
	# The false accusation this check must never make: someone's own script, connected from
	# elsewhere. Only generated output is judged, and the header is what tells the two apart.
	var hand_written: String = "extends Node\n\n\nfunc _on_verb_failed(verb_id: String, reason: String) -> void:\n\tprint(reason)\n"
	passed = _check("a hand-written handler in someone's own script is never accused",
		EventSheetProjectDoctor.unconnected_trigger_signals(hand_written).is_empty(), true) and passed
	# And the second false accusation, the one this file walked straight into: a script that merely
	# TALKS about the convention. The header has to be line ONE, not somewhere in the middle.
	var discusses_it: String = "# A guide to the convention.\n" + orphan
	passed = _check("a script that only mentions the header is not generated code",
		EventSheetProjectDoctor.unconnected_trigger_signals(discusses_it).is_empty(), true) and passed
	var several: String = HEADER + "extends Node\n\n\nfunc _on_verb_succeeded(verb_id: String) -> void:\n\tpass\n\n\nfunc _on_data_file_changed(path: String) -> void:\n\tpass\n"
	passed = _check("every dead trigger is named, not just the first",
		str(EventSheetProjectDoctor.unconnected_trigger_signals(several)), "[\"verb_succeeded\", \"data_file_changed\"]") and passed
	return passed


## The path that matters: what the compiler really emits for a sheet built both ways.
static func _test_against_real_compiler_output() -> bool:
	var with_declaration: String = _compile(true)
	var passed: bool = _check("the declared sheet connects its trigger in _ready",
		with_declaration.contains("verb_failed.connect(_on_verb_failed)"), true)
	passed = _check("and the Doctor finds nothing wrong with it",
		EventSheetProjectDoctor.unconnected_trigger_signals(with_declaration).is_empty(), true) and passed

	var without: String = _compile(false)
	passed = _check("the undeclared sheet still emits the handler",
		without.contains("func _on_verb_failed(verb_id: String, reason: String) -> void:"), true) and passed
	passed = _check("but connects nothing to it, which is why the event never runs",
		without.contains(".connect(_on_verb_failed)"), false) and passed
	passed = _check("it compiles anyway, so nothing else in the project complains", _parses(without), true) and passed
	passed = _check("and the Doctor names the signal that is missing",
		str(EventSheetProjectDoctor.unconnected_trigger_signals(without)), "[\"verb_failed\"]") and passed
	return passed


## `<Node> [/ signal verb_failed] / On Failure Of: remember the reason`.
static func _compile(declare: bool) -> String:
	var sheet: EventSheetResource = EventSheetResource.new()
	sheet.host_class = "Node"
	if declare:
		var declaration: SignalRow = SignalRow.new()
		declaration.signal_name = "verb_failed"
		declaration.params = PackedStringArray(["verb_id: String", "reason: String"])
		sheet.events.append(declaration)
	var variable: LocalVariable = LocalVariable.new()
	variable.name = "last_reason"
	variable.type_name = "String"
	variable.default_value = ""
	sheet.events.append(variable)
	var row: EventRow = EventRow.new()
	row.trigger_provider_id = "Core"
	row.trigger_id = "signal:verb_failed"
	row.trigger_args = "verb_id: String, reason: String"
	var action: ACEAction = ACEAction.new()
	action.provider_id = "Core"
	action.ace_id = "RawCode"
	action.codegen_template = "last_reason = reason"
	row.actions.append(action)
	sheet.events.append(row)
	return str(SheetCompiler.compile(sheet, "user://undeclared_trigger_signal.gd").get("output", ""))


static func _parses(source: String) -> bool:
	var script: GDScript = GDScript.new()
	script.source_code = source
	return script.reload() == OK


static func _check(label: String, actual: Variant, expected: Variant) -> bool:
	if actual == expected:
		print("[PASS] undeclared_trigger_signal_doctor_test: %s" % label)
		return true
	print("[FAIL] undeclared_trigger_signal_doctor_test: %s" % label)
	print("  expected: %s" % str(expected))
	print("  actual:   %s" % str(actual))
	return false
