# AUTO-GENERATED by EventForge v0.1.0
# Source: res://eventsheet_addons/drag_drop/drag_drop_behavior.tres
# DO NOT EDIT — this file is regenerated on every compile.

class_name DragDropBehavior
extends Node

## The node this behavior acts on (its parent). Required host: Node2D.
var host: Node2D = null

func _enter_tree() -> void:
	host = get_parent() as Node2D
	if host == null:
		push_warning("DragDropBehavior behavior requires a Node2D parent.")

var dragging: bool = false
@export var grab_radius: float = 48.0

## @ace_trigger
## @ace_name("On Drag Start")
## @ace_category("Drag & Drop")
signal drag_started

## @ace_trigger
## @ace_name("On Dropped")
## @ace_category("Drag & Drop")
signal dropped

func _process(delta: float) -> void:
	if host == null:
		return
	if Input.is_mouse_button_pressed(MOUSE_BUTTON_LEFT):
		var mouse := host.get_global_mouse_position()
		if not dragging and mouse.distance_to(host.global_position) <= grab_radius:
			dragging = true
			drag_started.emit()
		if dragging:
			host.global_position = mouse
	elif dragging:
		dragging = false
		dropped.emit()

## @ace_action
## @ace_name("Drop Now")
## @ace_category("Drag & Drop")
## @ace_description("Releases the drag immediately.")
## @ace_codegen_template("$DragDropBehavior.drop_now()")
func drop_now() -> void:
	if dragging:
		dragging = false
		dropped.emit()

# Drag & Drop behavior (C3-style): grab the host with the mouse within the grab radius; fires On Drag Start and On Dropped.
