# AUTO-GENERATED by EventForge v0.9.0
# Source: res://eventsheet_addons/timer/timer_behavior.tres
# DO NOT EDIT — this file is regenerated on every compile.

@icon("res://eventsheet_addons/behavior.svg")
class_name TimerBehavior
extends Node

## The node this behavior acts on (its parent). Required host: Node.
var host: Node = null

func _enter_tree() -> void:
	host = get_parent() as Node
	if host == null:
		push_warning("TimerBehavior behavior requires a Node parent.")

## @ace_trigger
## @ace_name("On Timer")
## @ace_category("Timer")
signal timer_finished

@export var duration: float = 1.0
var remaining: float = 0.0
@export var repeating: bool = false
var running: bool = false

func _process(delta: float) -> void:
	if running:
		remaining += -delta
		if remaining <= 0.0:
			timer_finished.emit()
			if repeating:
				remaining = duration
			else:
				running = false

## @ace_action
## @ace_name("Start Timer")
## @ace_category("Timer")
## @ace_description("Starts (or restarts) the countdown with the given duration.")
## @ace_icon("res://eventsheet_addons/behavior.svg")
## @ace_codegen_template("$TimerBehavior.start_timer({seconds})")
func start_timer(seconds: float) -> void:
	duration = seconds
	remaining = seconds
	running = true

## @ace_action
## @ace_name("Stop Timer")
## @ace_category("Timer")
## @ace_description("Stops the countdown without firing On Timer.")
## @ace_icon("res://eventsheet_addons/behavior.svg")
## @ace_codegen_template("$TimerBehavior.stop_timer()")
func stop_timer() -> void:
	running = false

# Timer behavior (event-sheet-style): Start Timer / Stop Timer from any sheet; the On Timer trigger fires when it elapses (repeats when 'repeating').
