# AUTO-GENERATED by EventForge v0.1.0
# Source: res://eventsheet_addons/move_to/move_to_behavior.tres
# DO NOT EDIT — this file is regenerated on every compile.

class_name MoveToBehavior
extends Node

## The node this behavior acts on (its parent). Required host: Node2D.
var host: Node2D = null

func _enter_tree() -> void:
	host = get_parent() as Node2D
	if host == null:
		push_warning("MoveToBehavior behavior requires a Node2D parent.")

@export var max_speed: float = 200.0
var moving: bool = false
var target_x: float = 0.0
var target_y: float = 0.0

## @ace_trigger
## @ace_name("On Arrived")
## @ace_category("Move To")
signal arrived

func _process(delta: float) -> void:
	if not moving or host == null:
		return
	var target := Vector2(target_x, target_y)
	host.position = host.position.move_toward(target, max_speed * delta)
	if host.position.distance_to(target) < 0.5:
		moving = false
		arrived.emit()

## @ace_action
## @ace_name("Move To Position")
## @ace_category("Move To")
## @ace_description("Starts gliding toward the point.")
## @ace_codegen_template("$MoveToBehavior.move_to_position({x}, {y})")
func move_to_position(x: float, y: float) -> void:
	target_x = x
	target_y = y
	moving = true

## @ace_action
## @ace_name("Stop Moving")
## @ace_category("Move To")
## @ace_description("Stops without firing On Arrived.")
## @ace_codegen_template("$MoveToBehavior.stop_moving()")
func stop_moving() -> void:
	moving = false

# Move To behavior (C3-style): glides the host to a target position and fires On Arrived.
