# AUTO-GENERATED by EventForge v0.1.0
# Source: res://eventsheet_addons/car/car_behavior.tres
# DO NOT EDIT — this file is regenerated on every compile.

class_name CarBehavior
extends Node

## The node this behavior acts on (its parent). Required host: CharacterBody2D.
var host: CharacterBody2D = null

func _enter_tree() -> void:
	host = get_parent() as CharacterBody2D
	if host == null:
		push_warning("CarBehavior behavior requires a CharacterBody2D parent.")

@export var acceleration: float = 300.0
@export var deceleration: float = 400.0
@export var max_speed: float = 400.0
var speed: float = 0.0
@export var steer_degrees: float = 180.0

func _physics_process(delta: float) -> void:
	if host == null:
		return
	var throttle := Input.get_axis(&"ui_down", &"ui_up")
	if throttle > 0.0:
		speed = minf(speed + acceleration * delta, max_speed)
	elif throttle < 0.0:
		speed = maxf(speed - acceleration * delta, -max_speed * 0.5)
	else:
		speed = move_toward(speed, 0.0, deceleration * delta)
	var steer := Input.get_axis(&"ui_left", &"ui_right")
	host.rotation += deg_to_rad(steer_degrees) * steer * delta * clampf(absf(speed) / max_speed, 0.0, 1.0) * signf(speed)
	host.velocity = Vector2.from_angle(host.rotation) * speed
	host.move_and_slide()

## @ace_action
## @ace_name("Stop Car")
## @ace_category("Car")
## @ace_description("Kills all momentum.")
## @ace_codegen_template("$CarBehavior.stop_car()")
func stop_car() -> void:
	speed = 0.0
	if host != null:
		host.velocity = Vector2.ZERO

# Car behavior (C3-style): accelerate/brake with up/down, steer with left/right (steering scales with speed).
