# AUTO-GENERATED by EventForge v0.8.0
# Source: res://eventsheet_addons/line_of_sight/line_of_sight_behavior.tres
# DO NOT EDIT — this file is regenerated on every compile.

class_name LOSBehavior
extends Node

## The node this behavior acts on (its parent). Required host: Node2D.
var host: Node2D = null

func _enter_tree() -> void:
	host = get_parent() as Node2D
	if host == null:
		push_warning("LOSBehavior behavior requires a Node2D parent.")

@export var collision_mask: int = 1
@export var cone_of_view_degrees: float = 360.0
@export var sight_range: float = 400.0

## @ace_condition
## @ace_name("Has Line Of Sight To")
## @ace_category("Line Of Sight")
## @ace_codegen_template("$LOSBehavior.has_los_to({point})")
func has_los_to(point: Vector2) -> bool:
	if host == null or host.global_position.distance_to(point) > sight_range:
		return false
	if cone_of_view_degrees < 360.0:
		var to_target := (point - host.global_position).angle()
		if absf(angle_difference(host.rotation, to_target)) > deg_to_rad(cone_of_view_degrees) * 0.5:
			return false
	return has_los_between(host.global_position, point)

## @ace_condition
## @ace_name("Has LOS Between")
## @ace_category("Line Of Sight")
## @ace_codegen_template("$LOSBehavior.has_los_between({from_point}, {to_point})")
func has_los_between(from_point: Vector2, to_point: Vector2) -> bool:
	if host == null:
		return false
	var query := PhysicsRayQueryParameters2D.create(from_point, to_point)
	query.collision_mask = collision_mask
	return host.get_world_2d().direct_space_state.intersect_ray(query).is_empty()

func _process(delta: float) -> void:
	pass

# Line of Sight behavior (C3 parity): raycast LOS with range and an optional cone of view (degrees; 360 = all around). Conditions: Has Line Of Sight To, Has LOS Between positions.
