# AUTO-GENERATED by EventForge v0.1.0
# Source: res://eventsheet_addons/line_of_sight/line_of_sight_behavior.tres
# DO NOT EDIT — this file is regenerated on every compile.

class_name LOSBehavior
extends Node

## The node this behavior acts on (its parent). Required host: Node2D.
var host: Node2D = null

func _enter_tree() -> void:
	host = get_parent() as Node2D
	if host == null:
		push_warning("LOSBehavior behavior requires a Node2D parent.")

@export var collision_mask: int = 1
@export var sight_range: float = 400.0

## @ace_condition
## @ace_name("Has Line Of Sight To")
## @ace_category("Line Of Sight")
## @ace_codegen_template("$LOSBehavior.has_los_to({point})")
func has_los_to(point: Vector2) -> bool:
	if host == null or host.global_position.distance_to(point) > sight_range:
		return false
	var query := PhysicsRayQueryParameters2D.create(host.global_position, point)
	query.collision_mask = collision_mask
	return host.get_world_2d().direct_space_state.intersect_ray(query).is_empty()

func _process(delta: float) -> void:
	pass

# Line of Sight behavior (C3-style): the Has Line Of Sight To condition raycasts against solids within range.
