# AUTO-GENERATED by EventForge v0.1.0
# Source: res://eventsheet_addons/orbit/orbit_behavior.tres
# DO NOT EDIT — this file is regenerated on every compile.

class_name OrbitBehavior
extends Node

## The node this behavior acts on (its parent). Required host: Node2D.
var host: Node2D = null

func _enter_tree() -> void:
	host = get_parent() as Node2D
	if host == null:
		push_warning("OrbitBehavior behavior requires a Node2D parent.")

var angle: float = 0.0
var center_captured: bool = false
var center_x: float = 0.0
var center_y: float = 0.0
@export var radius: float = 100.0
@export var speed_degrees: float = 90.0

func _process(delta: float) -> void:
	if host == null:
		return
	if not center_captured:
		center_x = host.position.x
		center_y = host.position.y
		center_captured = true
	angle += deg_to_rad(speed_degrees) * delta
	host.position = Vector2(center_x, center_y) + Vector2.from_angle(angle) * radius

## @ace_action
## @ace_name("Set Orbit Center")
## @ace_category("Orbit")
## @ace_description("Orbits around the given point from now on.")
## @ace_codegen_template("$OrbitBehavior.set_orbit_center({x}, {y})")
func set_orbit_center(x: float, y: float) -> void:
	center_x = x
	center_y = y
	center_captured = true

## @ace_action
## @ace_name("Set Orbit Speed")
## @ace_category("Orbit")
## @ace_description("Degrees per second (negative reverses).")
## @ace_codegen_template("$OrbitBehavior.set_orbit_speed({degrees_per_second})")
func set_orbit_speed(degrees_per_second: float) -> void:
	speed_degrees = degrees_per_second

# Orbit behavior (C3-style): circles the host around its starting point (or a set center).
