# AUTO-GENERATED by EventForge v0.9.0
# Source: res://eventsheet_addons/background_runner/background_runner_behavior.tres
# DO NOT EDIT — this file is regenerated on every compile.

## @ace_tags(performance, threading)
@icon("res://eventsheet_addons/behavior.svg")
class_name BackgroundRunner
extends Node

## The node this behavior acts on (its parent). Required host: Node.
var host: Node = null

func _enter_tree() -> void:
	host = get_parent() as Node
	if host == null:
		push_warning("BackgroundRunner behavior requires a Node parent.")

## @ace_trigger
## @ace_name("On Done")
## @ace_category("Background")
signal done(result: Variant)

# In-flight tasks as [task_id, call_id]; results keyed by call_id, written off-thread under _mutex.
var _tasks: Array = []
var _results: Dictionary = {}
var _next_id: int = 0
var _mutex: Mutex = null

func _ready() -> void:
	_mutex = Mutex.new()

func _process(delta: float) -> void:
	if _tasks.is_empty():
		return
	for __i: int in range(_tasks.size() - 1, -1, -1):
		var __entry: Array = _tasks[__i]
		if WorkerThreadPool.is_task_completed(__entry[0]):
			WorkerThreadPool.wait_for_task_completion(__entry[0])
			_mutex.lock()
			var __result: Variant = _results.get(__entry[1], null)
			_results.erase(__entry[1])
			_mutex.unlock()
			_tasks.remove_at(__i)
			done.emit(__result)

## @ace_action
## @ace_name("Run In Background")
## @ace_category("Background")
## @ace_description("Runs a PURE callable off the main thread; On Done(result) fires when it finishes. WARNING: the callable must NOT touch nodes / the scene tree / non-thread-safe resources — data in, data out only.")
## @ace_icon("res://eventsheet_addons/behavior.svg")
## @ace_codegen_template("$BackgroundRunner.run_in_background({work})")
func run_in_background(work: Callable) -> void:
	if _mutex == null:
		_mutex = Mutex.new()
	var __cid: int = _next_id
	_next_id += 1
	var __tid: int = WorkerThreadPool.add_task(_run_task.bind(work, __cid))
	_tasks.append([__tid, __cid])

## @ace_action
## @ace_name("Run Batch In Background")
## @ace_category("Background")
## @ace_description("Fans an array across worker threads: runs work.bind(item) for each item (On Done fires per item). The callable must be PURE.")
## @ace_icon("res://eventsheet_addons/behavior.svg")
## @ace_codegen_template("$BackgroundRunner.run_batch_in_background({items}, {work})")
func run_batch_in_background(items: Array, work: Callable) -> void:
	for __item: Variant in items:
		run_in_background(work.bind(__item))

## @ace_condition
## @ace_name("Is Running")
## @ace_category("Background")
## @ace_icon("res://eventsheet_addons/behavior.svg")
## @ace_codegen_template("$BackgroundRunner.is_running()")
func is_running() -> bool:
	return not _tasks.is_empty()

## @ace_expression
## @ace_name("Tasks Running")
## @ace_category("Background")
## @ace_icon("res://eventsheet_addons/behavior.svg")
## @ace_codegen_template("$BackgroundRunner.tasks_running()")
func tasks_running() -> int:
	return _tasks.size()

func _run_task(work: Callable, call_id: int) -> void:
	var result: Variant = work.call()
	_mutex.lock()
	_results[call_id] = result
	_mutex.unlock()

# Run In Background: hands a PURE function (no scene-tree access!) to a worker thread; On Done(result) fires on the main thread when it finishes. For heavy compute that would hitch even when spread across frames.
