# AUTO-GENERATED by EventForge v0.9.0
# Source: res://eventsheet_addons/eight_direction/eight_direction_movement_behavior.tres
# DO NOT EDIT — this file is regenerated on every compile.

@icon("res://eventsheet_addons/behavior.svg")
class_name EightDirectionMovement
extends Node

## The node this behavior acts on (its parent). Required host: CharacterBody2D.
var host: CharacterBody2D = null

func _enter_tree() -> void:
	host = get_parent() as CharacterBody2D
	if host == null:
		push_warning("EightDirectionMovement behavior requires a CharacterBody2D parent.")

@export var move_speed: float = 200.0

func _physics_process(delta: float) -> void:
	if is_instance_valid(host):
		var input_vector: Vector2 = Input.get_vector("ui_left", "ui_right", "ui_up", "ui_down")
		host.velocity = input_vector * move_speed
		host.move_and_slide()

## @ace_action
## @ace_name("Set Move Speed")
## @ace_category("Eight Direction")
## @ace_description("Changes the movement speed.")
## @ace_icon("res://eventsheet_addons/behavior.svg")
## @ace_codegen_template("$EightDirectionMovement.set_move_speed({speed})")
func set_move_speed(speed: float) -> void:
	move_speed = speed

# Top-down 8-direction movement: attach under a CharacterBody2D; moves with the ui_* input actions.
