# AUTO-GENERATED by EventForge v0.1.0
# Source: res://eventsheet_addons/platformer_movement/platformer_movement_behavior.tres
# DO NOT EDIT — this file is regenerated on every compile.

class_name PlatformerMovement
extends Node

## The node this behavior acts on (its parent). Required host: CharacterBody2D.
var host: CharacterBody2D = null

func _enter_tree() -> void:
	host = get_parent() as CharacterBody2D
	if host == null:
		push_warning("PlatformerMovement behavior requires a CharacterBody2D parent.")

@export var gravity: float = 980.0
@export var jump_velocity: float = -400.0
@export var move_speed: float = 200.0

## @ace_trigger
## @ace_name("On Jumped")
## @ace_category("Platformer")
signal jumped

func _physics_process(delta: float) -> void:
	if host == null:
		return
	var direction := Input.get_axis("ui_left", "ui_right")
	host.velocity.x = direction * move_speed
	if not host.is_on_floor():
		host.velocity.y += gravity * delta
	host.move_and_slide()

## @ace_action
## @ace_name("Jump")
## @ace_category("Platformer")
## @ace_description("Makes the host jump when it is on the floor.")
## @ace_codegen_template("$PlatformerMovement.jump()")
func jump() -> void:
	if host != null and host.is_on_floor():
		host.velocity.y = jump_velocity
		jumped.emit()

## @ace_action
## @ace_name("Set Move Speed")
## @ace_category("Platformer")
## @ace_description("Changes the horizontal move speed.")
## @ace_codegen_template("$PlatformerMovement.set_move_speed({speed})")
func set_move_speed(speed: float) -> void:
	move_speed = speed

# Platformer movement behavior: attach under a CharacterBody2D. Move with ui_left/ui_right; call Jump from any sheet.
