# AUTO-GENERATED by EventForge v0.1.0
# Source: res://eventsheet_addons/sine/sine_behavior.tres
# DO NOT EDIT — this file is regenerated on every compile.

class_name SineBehavior
extends Node

## The node this behavior acts on (its parent). Required host: Node2D.
var host: Node2D = null

func _enter_tree() -> void:
	host = get_parent() as Node2D
	if host == null:
		push_warning("SineBehavior behavior requires a Node2D parent.")

@export var active: bool = true
var base_captured: bool = false
var base_x: float = 0.0
var base_y: float = 0.0
@export var magnitude: float = 50.0
@export var movement: String = "horizontal"
@export var period: float = 4.0
var time: float = 0.0

func _process(delta: float) -> void:
	if not active or host == null:
		return
	if not base_captured:
		base_x = host.position.x
		base_y = host.position.y
		base_captured = true
	time += delta
	var offset := sin(time * TAU / period) * magnitude
	if movement == "horizontal":
		host.position.x = base_x + offset
	elif movement == "vertical":
		host.position.y = base_y + offset
	elif movement == "angle":
		host.rotation = offset * 0.0174533

## @ace_action
## @ace_name("Set Sine Active")
## @ace_category("Sine")
## @ace_description("Pauses or resumes the oscillation.")
## @ace_codegen_template("$SineBehavior.set_sine_active({is_active})")
func set_sine_active(is_active: bool) -> void:
	active = is_active

## @ace_action
## @ace_name("Reset Sine")
## @ace_category("Sine")
## @ace_description("Restarts the wave from the current position.")
## @ace_codegen_template("$SineBehavior.reset_sine()")
func reset_sine() -> void:
	time = 0.0
	base_captured = false

# Sine behavior (C3-style): oscillates the host around its starting position/angle. movement: horizontal, vertical or angle.
