# AUTO-GENERATED by EventForge v0.1.0
# Source: res://eventsheet_addons/follow/follow_behavior.tres
# DO NOT EDIT — this file is regenerated on every compile.

class_name FollowBehavior
extends Node

## The node this behavior acts on (its parent). Required host: Node2D.
var host: Node2D = null

func _enter_tree() -> void:
	host = get_parent() as Node2D
	if host == null:
		push_warning("FollowBehavior behavior requires a Node2D parent.")

@export var follow_speed: float = 5.0
@export var following: bool = true
@export var min_distance: float = 0.0
@export var target_path: String = ""

func _process(delta: float) -> void:
	if not following or host == null or target_path == "":
		return
	var target := host.get_node_or_null(NodePath(target_path))
	if not (target is Node2D):
		return
	if host.position.distance_to(target.position) <= min_distance:
		return
	host.position = host.position.lerp(target.position, clampf(follow_speed * delta, 0.0, 1.0))

## @ace_action
## @ace_name("Start Following")
## @ace_category("Follow")
## @ace_description("Follows the node at the given path.")
## @ace_codegen_template("$FollowBehavior.start_following({path})")
func start_following(path: String) -> void:
	target_path = path
	following = true

## @ace_action
## @ace_name("Stop Following")
## @ace_category("Follow")
## @ace_description("Stops trailing the target.")
## @ace_codegen_template("$FollowBehavior.stop_following()")
func stop_following() -> void:
	following = false

# Follow behavior (C3-style): smoothly trails another node (set the target path).
