# AUTO-GENERATED by EventForge v0.1.0
# Source: res://eventsheet_addons/follow/follow_behavior.tres
# DO NOT EDIT — this file is regenerated on every compile.

class_name FollowBehavior
extends Node

## The node this behavior acts on (its parent). Required host: Node2D.
var host: Node2D = null

func _enter_tree() -> void:
	host = get_parent() as Node2D
	if host == null:
		push_warning("FollowBehavior behavior requires a Node2D parent.")

var clock: float = 0.0
@export var delay: float = 0.4
@export var follow_speed: float = 5.0
@export var following: bool = true
var history: Array = []
@export var min_distance: float = 0.0
@export_enum("smooth", "delayed") var mode: String = "smooth"
@export var target_path: String = ""

func _process(delta: float) -> void:
	if host == null or target_path == "":
		return
	var target := host.get_node_or_null(NodePath(target_path))
	if not (target is Node2D):
		return
	clock += delta
	history.append([clock, target.position])
	while history.size() > 2 and float(history[0][0]) < clock - delay - 1.0:
		history.pop_front()
	if not following:
		return
	if mode == "delayed":
		var sample_time := clock - delay
		for entry: Array in history:
			if float(entry[0]) >= sample_time:
				host.position = entry[1]
				break
		return
	if host.position.distance_to(target.position) <= min_distance:
		return
	host.position = host.position.lerp(target.position, clampf(follow_speed * delta, 0.0, 1.0))

## @ace_action
## @ace_name("Start Following")
## @ace_category("Follow")
## @ace_description("Follows the node at the given path.")
## @ace_codegen_template("$FollowBehavior.start_following({path})")
func start_following(path: String) -> void:
	target_path = path
	following = true
	history = []

## @ace_action
## @ace_name("Stop Following")
## @ace_category("Follow")
## @ace_description("Stops trailing the target.")
## @ace_codegen_template("$FollowBehavior.stop_following()")
func stop_following() -> void:
	following = false

# Follow behavior (C3 parity): trails another node. mode smooth = lerp chase; mode delayed = replay the target's position history after a delay (C3's Follow).
