# AUTO-GENERATED by EventForge v0.9.0
# Source: res://eventsheet_addons/tween/tween_behavior.tres
# DO NOT EDIT — this file is regenerated on every compile.

## @ace_tags(motion, juice)
@icon("res://eventsheet_addons/behavior.svg")
class_name TweenBehavior
extends Node

## The node this behavior acts on (its parent). Required host: Node2D.
var host: Node2D = null

func _enter_tree() -> void:
	host = get_parent() as Node2D
	if host == null:
		push_warning("TweenBehavior behavior requires a Node2D parent.")

## @ace_trigger
## @ace_name("On Tween Finished")
## @ace_category("Tween")
signal tween_finished

## Seconds used when a tween call passes 0.
@export_range(0.01, 10, 0.01) var default_duration: float = 0.3
@export_enum("in", "out", "in_out", "out_in") var easing: String = "out"
@export_enum("linear", "sine", "quad", "cubic", "quart", "quint", "expo", "circ", "elastic", "back", "bounce", "spring") var transition: String = "sine"

var _active_tween: Tween = null

## @ace_action
## @ace_name("Tween Property")
## @ace_category("Tween")
## @ace_description("Tweens any host property (e.g. position:x) to a value.")
## @ace_icon("res://eventsheet_addons/behavior.svg")
## @ace_codegen_template("$TweenBehavior.tween_property_to({property_path}, {final_value}, {duration})")
func tween_property_to(property_path: String, final_value: float, duration: float) -> void:
	_start_tween(property_path, final_value, duration)

## @ace_action
## @ace_name("Tween Position")
## @ace_category("Tween")
## @ace_description("Moves the host to (x, y).")
## @ace_icon("res://eventsheet_addons/behavior.svg")
## @ace_codegen_template("$TweenBehavior.tween_position({x}, {y}, {duration})")
func tween_position(x: float, y: float, duration: float) -> void:
	_start_tween("position", Vector2(x, y), duration)

## @ace_action
## @ace_name("Tween Scale")
## @ace_category("Tween")
## @ace_description("Scales the host uniformly.")
## @ace_icon("res://eventsheet_addons/behavior.svg")
## @ace_codegen_template("$TweenBehavior.tween_scale({amount}, {duration})")
func tween_scale(amount: float, duration: float) -> void:
	_start_tween("scale", Vector2(amount, amount), duration)

## @ace_action
## @ace_name("Tween Rotation")
## @ace_category("Tween")
## @ace_description("Rotates the host to the given degrees.")
## @ace_icon("res://eventsheet_addons/behavior.svg")
## @ace_codegen_template("$TweenBehavior.tween_rotation({degrees}, {duration})")
func tween_rotation(degrees: float, duration: float) -> void:
	_start_tween("rotation_degrees", degrees, duration)

## @ace_action
## @ace_name("Tween Alpha")
## @ace_category("Tween")
## @ace_description("Fades the host's modulate alpha.")
## @ace_icon("res://eventsheet_addons/behavior.svg")
## @ace_codegen_template("$TweenBehavior.tween_alpha({alpha}, {duration})")
func tween_alpha(alpha: float, duration: float) -> void:
	_start_tween("modulate:a", clampf(alpha, 0.0, 1.0), duration)

## @ace_action
## @ace_name("Stop Tweens")
## @ace_category("Tween")
## @ace_description("Kills the running tween (host stays where it is).")
## @ace_icon("res://eventsheet_addons/behavior.svg")
## @ace_codegen_template("$TweenBehavior.stop_tweens()")
func stop_tweens() -> void:
	if _active_tween != null:
		_active_tween.kill()
		_active_tween = null

## @ace_condition
## @ace_name("Is Tweening")
## @ace_category("Tween")
## @ace_icon("res://eventsheet_addons/behavior.svg")
## @ace_codegen_template("$TweenBehavior.is_tweening()")
func is_tweening() -> bool:
	return _active_tween != null and _active_tween.is_running()

func _trans_id() -> int:
	match transition:
		"linear": return Tween.TRANS_LINEAR
		"quad": return Tween.TRANS_QUAD
		"cubic": return Tween.TRANS_CUBIC
		"quart": return Tween.TRANS_QUART
		"quint": return Tween.TRANS_QUINT
		"expo": return Tween.TRANS_EXPO
		"circ": return Tween.TRANS_CIRC
		"elastic": return Tween.TRANS_ELASTIC
		"back": return Tween.TRANS_BACK
		"bounce": return Tween.TRANS_BOUNCE
		"spring": return Tween.TRANS_SPRING
	return Tween.TRANS_SINE

func _ease_id() -> int:
	match easing:
		"in": return Tween.EASE_IN
		"in_out": return Tween.EASE_IN_OUT
		"out_in": return Tween.EASE_OUT_IN
	return Tween.EASE_OUT

func _start_tween(property_path: String, final_value, duration: float) -> void:
	if host == null:
		return
	var seconds: float = duration if duration > 0.0 else default_duration
	_active_tween = host.create_tween()
	_active_tween.tween_property(host, NodePath(property_path), final_value, seconds).set_trans(_trans_id()).set_ease(_ease_id())
	_active_tween.finished.connect(func() -> void: tween_finished.emit())

# Tweens, the behavior way: pick transition + easing in the Inspector, then call one action — Tween Position / Scale / Rotation / Alpha / any property.
