# AUTO-GENERATED by EventForge v0.9.0
# Source: res://demo/sheets/player.tres
# DO NOT EDIT — this file is regenerated on every compile.

extends CharacterBody2D

signal damage_taken(amount: int)

@export var health: int = 100
@export var speed: float = 200.0

func _ready() -> void:
	print("Player ready")
	health = 100

func _process(delta: float) -> void:
	if health < 50:
		print("Low health!")

func _on_body_entered(body: Node) -> void:
	if body.is_in_group("enemy"):
		health += -10
		damage_taken.emit(10)
