# AUTO-GENERATED by EventForge v0.1.0
# Source: res://demo/sheets/player.tres
# DO NOT EDIT — this file is regenerated on every compile.

extends CharacterBody2D

@export var health: int = 100
@export var speed: float = 200.0

func _ready() -> void:
	print("Player ready")
	health = 100

func _process(delta: float) -> void:
	if health < 50:
		print("Low health!")

func _physics_process(delta: float) -> void:
	if true:
		health = health - 1

func _on_damage_taken() -> void:
	print("Signal fired")
