# AUTO-GENERATED by EventForge v0.1.0
# Source: res://eventsheet_addons/spring/spring_behavior.tres
# DO NOT EDIT — this file is regenerated on every compile.

## @ace_tags(motion, juice)
class_name SpringBehavior
extends Node

## The node this behavior acts on (its parent). Required host: Node2D.
var host: Node2D = null

func _enter_tree() -> void:
	host = get_parent() as Node2D
	if host == null:
		push_warning("SpringBehavior behavior requires a Node2D parent.")

## 0 = oscillate forever, 1 = no overshoot.
@export_range(0, 1, 0.01) var default_damping: float = 0.85
## Distance + speed below which a spring counts as settled.
@export var default_precision: float = 0.01
## Spring force toward the target (higher = snappier).
@export_range(1, 1000, 1) var default_stiffness: float = 170.0
var springs: Dictionary = {}

## @ace_trigger
## @ace_name("On Spring Reached")
## @ace_category("Spring")
signal spring_reached(spring_name: String)

## @ace_condition
## @ace_name("Is Springing")
## @ace_category("Spring")
## @ace_codegen_template("$SpringBehavior.is_springing({spring_name})")
func is_springing(spring_name: String) -> bool:
	return springs.has(spring_name) and bool(springs[spring_name].get("active", false))

## @ace_expression
## @ace_name("Spring Value")
## @ace_category("Spring")
func spring_value(spring_name: String) -> float:
	return float(springs.get(spring_name, {}).get("value", 0.0))

## @ace_expression
## @ace_name("Spring Velocity")
## @ace_category("Spring")
func spring_velocity(spring_name: String) -> float:
	return float(springs.get(spring_name, {}).get("velocity", 0.0))

## @ace_expression
## @ace_name("Spring Progress")
## @ace_category("Spring")
func spring_progress(spring_name: String) -> float:
	var entry: Dictionary = springs.get(spring_name, {})
	var span: float = absf(float(entry.get("target", 0.0)) - float(entry.get("from", 0.0)))
	if span <= 0.0:
		return 1.0
	return clampf(1.0 - absf(float(entry.get("target", 0.0)) - float(entry.get("value", 0.0))) / span, 0.0, 1.0)

func _spring_entry(spring_name: String) -> Dictionary:
	if not springs.has(spring_name):
		springs[spring_name] = {"value": 0.0, "from": 0.0, "target": 0.0, "velocity": 0.0,
			"stiffness": default_stiffness, "damping": default_damping, "precision": default_precision, "active": false}
	return springs[spring_name]

# Host conveniences: springs with these names write straight onto the parent.
func _apply_to_host(spring_name: String, value: float) -> void:
	if host == null:
		return
	match spring_name:
		"__x": host.position.x = value
		"__y": host.position.y = value
		"__angle": host.rotation_degrees = value
		"__scale": host.scale = Vector2(value, value)

func _process(delta: float) -> void:
	# Semi-implicit integration; damping uses pow() so motion is framerate-independent.
	for spring_name: Variant in springs.keys():
		var entry: Dictionary = springs[spring_name]
		if not bool(entry.get("active", false)):
			continue
		entry["velocity"] = float(entry["velocity"]) + (float(entry["target"]) - float(entry["value"])) * float(entry["stiffness"]) * delta
		# Damping is the fraction of velocity LOST PER SECOND (framerate-independent).
		entry["velocity"] = float(entry["velocity"]) * pow(1.0 - float(entry["damping"]), delta)
		entry["value"] = float(entry["value"]) + float(entry["velocity"]) * delta
		if absf(float(entry["target"]) - float(entry["value"])) < float(entry["precision"]) and absf(float(entry["velocity"])) < float(entry["precision"]):
			entry["value"] = float(entry["target"])
			entry["velocity"] = 0.0
			entry["active"] = false
			spring_reached.emit(str(spring_name))
		_apply_to_host(str(spring_name), float(entry["value"]))

## @ace_action
## @ace_name("Spring To")
## @ace_category("Spring")
## @ace_description("Springs the named value toward a target.")
## @ace_codegen_template("$SpringBehavior.spring_to({spring_name}, {target})")
func spring_to(spring_name: String, target: float) -> void:
	var entry: Dictionary = _spring_entry(spring_name)
	entry["from"] = float(entry["value"])
	entry["target"] = target
	entry["active"] = true

## @ace_action
## @ace_name("Spring Between")
## @ace_category("Spring")
## @ace_description("Snaps to a start value, then springs to the end value.")
## @ace_codegen_template("$SpringBehavior.spring_between({spring_name}, {from_value}, {to_value})")
func spring_between(spring_name: String, from_value: float, to_value: float) -> void:
	var entry: Dictionary = _spring_entry(spring_name)
	entry["value"] = from_value
	entry["from"] = from_value
	entry["velocity"] = 0.0
	entry["target"] = to_value
	entry["active"] = true

## @ace_action
## @ace_name("Set Spring Value")
## @ace_category("Spring")
## @ace_description("Snaps the named spring (no motion).")
## @ace_codegen_template("$SpringBehavior.set_spring({spring_name}, {value})")
func set_spring(spring_name: String, value: float) -> void:
	var entry: Dictionary = _spring_entry(spring_name)
	entry["value"] = value
	entry["from"] = value
	entry["target"] = value
	entry["velocity"] = 0.0
	entry["active"] = false

## @ace_action
## @ace_name("Add Impulse")
## @ace_category("Spring")
## @ace_description("Kicks the named spring's velocity (instant juice).")
## @ace_codegen_template("$SpringBehavior.add_impulse({spring_name}, {amount})")
func add_impulse(spring_name: String, amount: float) -> void:
	var entry: Dictionary = _spring_entry(spring_name)
	entry["velocity"] = float(entry["velocity"]) + amount
	entry["active"] = true

## @ace_action
## @ace_name("Stop Spring")
## @ace_category("Spring")
## @ace_description("Freezes the named spring where it is.")
## @ace_codegen_template("$SpringBehavior.stop_spring({spring_name})")
func stop_spring(spring_name: String) -> void:
	if springs.has(spring_name):
		springs[spring_name]["active"] = false

## @ace_action
## @ace_name("Configure Spring")
## @ace_category("Spring")
## @ace_description("Per-spring stiffness/damping/precision overrides.")
## @ace_codegen_template("$SpringBehavior.configure_spring({spring_name}, {stiffness}, {damping}, {precision})")
func configure_spring(spring_name: String, stiffness: float, damping: float, precision: float) -> void:
	var entry: Dictionary = _spring_entry(spring_name)
	entry["stiffness"] = stiffness
	entry["damping"] = clampf(damping, 0.0, 1.0)
	entry["precision"] = precision

## @ace_action
## @ace_name("Spring Host X")
## @ace_category("Spring")
## @ace_description("Springs the host's X position.")
## @ace_codegen_template("$SpringBehavior.spring_host_x({target})")
func spring_host_x(target: float) -> void:
	var entry: Dictionary = _spring_entry("__x")
	if not bool(entry["active"]) and host != null:
		entry["value"] = host.position.x
	entry["from"] = float(entry["value"])
	entry["target"] = target
	entry["active"] = true

## @ace_action
## @ace_name("Spring Host Y")
## @ace_category("Spring")
## @ace_description("Springs the host's Y position.")
## @ace_codegen_template("$SpringBehavior.spring_host_y({target})")
func spring_host_y(target: float) -> void:
	var entry: Dictionary = _spring_entry("__y")
	if not bool(entry["active"]) and host != null:
		entry["value"] = host.position.y
	entry["from"] = float(entry["value"])
	entry["target"] = target
	entry["active"] = true

## @ace_action
## @ace_name("Spring Host Angle")
## @ace_category("Spring")
## @ace_description("Springs the host's rotation (degrees).")
## @ace_codegen_template("$SpringBehavior.spring_host_angle({degrees})")
func spring_host_angle(degrees: float) -> void:
	var entry: Dictionary = _spring_entry("__angle")
	if not bool(entry["active"]) and host != null:
		entry["value"] = host.rotation_degrees
	entry["from"] = float(entry["value"])
	entry["target"] = degrees
	entry["active"] = true

## @ace_action
## @ace_name("Spring Host Scale")
## @ace_category("Spring")
## @ace_description("Springs the host's uniform scale (squash & stretch!).")
## @ace_codegen_template("$SpringBehavior.spring_host_scale({target})")
func spring_host_scale(target: float) -> void:
	var entry: Dictionary = _spring_entry("__scale")
	if not bool(entry["active"]) and host != null:
		entry["value"] = host.scale.x
	entry["from"] = float(entry["value"])
	entry["target"] = target
	entry["active"] = true

# Numeric springing: snappy, physical motion for ANY number. Name a spring, set its target, read its value — or use the host helpers (x/y/angle/scale) for instant juice.
