# EventForge module — Collections (rich variables)
#
# Curated Dictionary/Array/JSON vocabulary — every op a direct GDScript one-liner.
# Module contract: see ace_factory.gd — ace_ids/templates are API (compatibility
# covenant); this file only changes where the descriptors are AUTHORED.
@tool
extends RefCounted
class_name EventForgeCollectionACEs

const F := preload("res://addons/eventforge/registration/ace_factory.gd")

static func get_descriptors() -> Array[ACEDescriptor]:
	var descriptors: Array[ACEDescriptor] = []

	# ── Collections (rich variables): curated Dictionary / Array / JSON vocabulary ──
	# C3 ships these as capability addons; here every op is a direct GDScript one-liner
	# (parity-safe) and the templates double as GDScript teachers. The long tail stays
	# one fx away. Variable params use "variable_reference:<Type>" so dropdowns offer
	# only matching (or Variant/untyped) variables.
	# Dictionary
	descriptors.append(F.make_descriptor("Core", "DictSetKey", "Set Key", ACEDescriptor.ACEType.ACTION, "{var_name}[{key}] = {value}", "", [F.make_param("var_name", "String", "dict", "Dictionary", "Dictionary variable to write into.", "variable_reference:Dictionary"), F.make_param("key", "String", "\"key\"", "Key", "Key expression.", "expression"), F.make_param("value", "String", "0", "Value", "Value expression.", "expression")], "Variables: Dictionary", "Set {var_name}[{key}] to {value}"))
	descriptors.append(F.make_descriptor("Core", "DictDeleteKey", "Delete Key", ACEDescriptor.ACEType.ACTION, "{var_name}.erase({key})", "", [F.make_param("var_name", "String", "dict", "Dictionary", "Dictionary variable.", "variable_reference:Dictionary"), F.make_param("key", "String", "\"key\"", "Key", "Key to remove.", "expression")], "Variables: Dictionary", "Delete key {key} from {var_name}"))
	descriptors.append(F.make_descriptor("Core", "DictClear", "Clear Dictionary", ACEDescriptor.ACEType.ACTION, "{var_name}.clear()", "", [F.make_param("var_name", "String", "dict", "Dictionary", "Dictionary variable.", "variable_reference:Dictionary")], "Variables: Dictionary", "Clear {var_name}"))
	descriptors.append(F.make_descriptor("Core", "DictMerge", "Merge Dictionary", ACEDescriptor.ACEType.ACTION, "{var_name}.merge({other}, true)", "", [F.make_param("var_name", "String", "dict", "Dictionary", "Destination dictionary.", "variable_reference:Dictionary"), F.make_param("other", "String", "{}", "Other", "Dictionary to merge in (overwrites).", "expression")], "Variables: Dictionary", "Merge {other} into {var_name}"))
	descriptors.append(F.make_descriptor("Core", "DictHasKey", "Has Key", ACEDescriptor.ACEType.CONDITION, "{var_name}.has({key})", "", [F.make_param("var_name", "String", "dict", "Dictionary", "Dictionary variable.", "variable_reference:Dictionary"), F.make_param("key", "String", "\"key\"", "Key", "Key to test.", "expression")], "Variables: Dictionary", "{var_name} has key {key}"))
	descriptors.append(F.make_descriptor("Core", "DictHasAllKeys", "Has All Keys", ACEDescriptor.ACEType.CONDITION, "{var_name}.has_all({keys})", "", [F.make_param("var_name", "String", "dict", "Dictionary", "Dictionary variable.", "variable_reference:Dictionary"), F.make_param("keys", "String", "[\"a\", \"b\"]", "Keys", "Array of keys that must all be present.", "expression")], "Variables: Dictionary", "{var_name} has all {keys}"))
	descriptors.append(F.make_descriptor("Core", "DictIsEmpty", "Dictionary Is Empty", ACEDescriptor.ACEType.CONDITION, "{var_name}.is_empty()", "", [F.make_param("var_name", "String", "dict", "Dictionary", "Dictionary variable.", "variable_reference:Dictionary")], "Variables: Dictionary", "{var_name} is empty"))
	descriptors.append(F.make_descriptor("Core", "DictGet", "Get Key (with default)", ACEDescriptor.ACEType.EXPRESSION, "{var_name}.get({key}, {default})", "", [F.make_param("var_name", "String", "dict", "Dictionary", "Dictionary variable.", "variable_reference:Dictionary"), F.make_param("key", "String", "\"key\"", "Key", "Key to read.", "expression"), F.make_param("default", "String", "0", "Default", "Fallback when the key is missing.", "expression")], "Variables: Dictionary", "{var_name}.get({key})"))
	descriptors.append(F.make_descriptor("Core", "DictSize", "Dictionary Size", ACEDescriptor.ACEType.EXPRESSION, "{var_name}.size()", "", [F.make_param("var_name", "String", "dict", "Dictionary", "Dictionary variable.", "variable_reference:Dictionary")], "Variables: Dictionary", "{var_name}.size()"))
	descriptors.append(F.make_descriptor("Core", "DictKeys", "Dictionary Keys", ACEDescriptor.ACEType.EXPRESSION, "{var_name}.keys()", "", [F.make_param("var_name", "String", "dict", "Dictionary", "Dictionary variable.", "variable_reference:Dictionary")], "Variables: Dictionary", "{var_name}.keys()"))
	descriptors.append(F.make_descriptor("Core", "DictValues", "Dictionary Values", ACEDescriptor.ACEType.EXPRESSION, "{var_name}.values()", "", [F.make_param("var_name", "String", "dict", "Dictionary", "Dictionary variable.", "variable_reference:Dictionary")], "Variables: Dictionary", "{var_name}.values()"))
	# Array
	descriptors.append(F.make_descriptor("Core", "ArrayAppend", "Append", ACEDescriptor.ACEType.ACTION, "{var_name}.append({value})", "", [F.make_param("var_name", "String", "list", "Array", "Array variable.", "variable_reference:Array"), F.make_param("value", "String", "0", "Value", "Value to append.", "expression")], "Variables: Array", "Append {value} to {var_name}"))
	descriptors.append(F.make_descriptor("Core", "ArrayInsert", "Insert At", ACEDescriptor.ACEType.ACTION, "{var_name}.insert({index}, {value})", "", [F.make_param("var_name", "String", "list", "Array", "Array variable.", "variable_reference:Array"), F.make_param("index", "String", "0", "Index", "Insertion index.", "expression"), F.make_param("value", "String", "0", "Value", "Value to insert.", "expression")], "Variables: Array", "Insert {value} at {index} in {var_name}"))
	descriptors.append(F.make_descriptor("Core", "ArrayRemoveAt", "Remove At", ACEDescriptor.ACEType.ACTION, "{var_name}.remove_at({index})", "", [F.make_param("var_name", "String", "list", "Array", "Array variable.", "variable_reference:Array"), F.make_param("index", "String", "0", "Index", "Index to remove.", "expression")], "Variables: Array", "Remove index {index} from {var_name}"))
	descriptors.append(F.make_descriptor("Core", "ArrayErase", "Erase Value", ACEDescriptor.ACEType.ACTION, "{var_name}.erase({value})", "", [F.make_param("var_name", "String", "list", "Array", "Array variable.", "variable_reference:Array"), F.make_param("value", "String", "0", "Value", "First matching value to remove.", "expression")], "Variables: Array", "Erase {value} from {var_name}"))
	descriptors.append(F.make_descriptor("Core", "ArrayClear", "Clear Array", ACEDescriptor.ACEType.ACTION, "{var_name}.clear()", "", [F.make_param("var_name", "String", "list", "Array", "Array variable.", "variable_reference:Array")], "Variables: Array", "Clear {var_name}"))
	descriptors.append(F.make_descriptor("Core", "ArraySort", "Sort Array", ACEDescriptor.ACEType.ACTION, "{var_name}.sort()", "", [F.make_param("var_name", "String", "list", "Array", "Array variable.", "variable_reference:Array")], "Variables: Array", "Sort {var_name}"))
	descriptors.append(F.make_descriptor("Core", "ArrayShuffle", "Shuffle Array", ACEDescriptor.ACEType.ACTION, "{var_name}.shuffle()", "", [F.make_param("var_name", "String", "list", "Array", "Array variable.", "variable_reference:Array")], "Variables: Array", "Shuffle {var_name}"))
	descriptors.append(F.make_descriptor("Core", "ArrayContains", "Contains", ACEDescriptor.ACEType.CONDITION, "{var_name}.has({value})", "", [F.make_param("var_name", "String", "list", "Array", "Array variable.", "variable_reference:Array"), F.make_param("value", "String", "0", "Value", "Value to look for.", "expression")], "Variables: Array", "{var_name} contains {value}"))
	descriptors.append(F.make_descriptor("Core", "ArrayIsEmpty", "Array Is Empty", ACEDescriptor.ACEType.CONDITION, "{var_name}.is_empty()", "", [F.make_param("var_name", "String", "list", "Array", "Array variable.", "variable_reference:Array")], "Variables: Array", "{var_name} is empty"))
	descriptors.append(F.make_descriptor("Core", "ArrayAt", "Value At", ACEDescriptor.ACEType.EXPRESSION, "{var_name}[{index}]", "", [F.make_param("var_name", "String", "list", "Array", "Array variable.", "variable_reference:Array"), F.make_param("index", "String", "0", "Index", "Index to read.", "expression")], "Variables: Array", "{var_name}[{index}]"))
	descriptors.append(F.make_descriptor("Core", "ArraySize", "Array Size", ACEDescriptor.ACEType.EXPRESSION, "{var_name}.size()", "", [F.make_param("var_name", "String", "list", "Array", "Array variable.", "variable_reference:Array")], "Variables: Array", "{var_name}.size()"))
	descriptors.append(F.make_descriptor("Core", "ArrayPickRandom", "Pick Random", ACEDescriptor.ACEType.EXPRESSION, "{var_name}.pick_random()", "", [F.make_param("var_name", "String", "list", "Array", "Array variable.", "variable_reference:Array")], "Variables: Array", "random of {var_name}"))
	# JSON (save/load workflows; XML is intentionally unsupported — JSON is the format)
	descriptors.append(F.make_descriptor("Core", "JsonStringify", "To JSON Text", ACEDescriptor.ACEType.EXPRESSION, "JSON.stringify({value})", "", [F.make_param("value", "String", "data", "Value", "Value to serialize.", "expression")], "Variables: JSON", "JSON.stringify({value})"))
	descriptors.append(F.make_descriptor("Core", "JsonParse", "From JSON Text", ACEDescriptor.ACEType.EXPRESSION, "JSON.parse_string({text})", "", [F.make_param("text", "String", "\"{}\"", "Text", "JSON text to parse (null when invalid).", "expression")], "Variables: JSON", "JSON.parse_string({text})"))
	descriptors.append(F.make_descriptor("Core", "JsonIsValid", "JSON Is Valid", ACEDescriptor.ACEType.CONDITION, "JSON.parse_string({text}) != null", "", [F.make_param("text", "String", "\"{}\"", "Text", "JSON text to validate.", "expression")], "Variables: JSON", "{text} is valid JSON"))
	descriptors.append(F.make_descriptor("Core", "FileExists", "File Exists", ACEDescriptor.ACEType.CONDITION, "FileAccess.file_exists({path})", "", [F.make_param("path", "String", "\"user://save.json\"", "Path", "File path to test (user:// is the writable export location).", "expression")], "Variables: JSON", "file {path} exists"))
	descriptors.append(F.make_descriptor("Core", "JsonSaveFile", "Save JSON File", ACEDescriptor.ACEType.ACTION, "FileAccess.open({path}, FileAccess.WRITE).store_string(JSON.stringify({value}, \"\\t\"))", "", [F.make_param("path", "String", "\"user://save.json\"", "Path", "File path (user:// is the writable location in exports).", "expression"), F.make_param("value", "String", "data", "Value", "Value to serialize and save.", "expression")], "Variables: JSON", "Save {value} as JSON to {path}"))
	descriptors.append(F.make_descriptor("Core", "JsonLoadFile", "Load JSON File", ACEDescriptor.ACEType.ACTION, "{var_name} = JSON.parse_string(FileAccess.get_file_as_string({path}))", "", [F.make_param("var_name", "String", "data", "Into Variable", "Variable receiving the parsed value (null when missing/invalid).", "variable_reference"), F.make_param("path", "String", "\"user://save.json\"", "Path", "File path to read.", "expression")], "Variables: JSON", "Load JSON {path} into {var_name}"))

	# Time (C3 System: Wait — handlers are implicit coroutines, await is safe anywhere)
	descriptors.append(F.make_descriptor("Core", "Wait", "Wait", ACEDescriptor.ACEType.ACTION, "await get_tree().create_timer({seconds}).timeout", "", [F.make_param("seconds", "String", "1.0", "Seconds", "How long to wait before the next action runs.", "expression")], "Time", "Wait {seconds} s"))
	descriptors.append(F.make_descriptor("Core", "AwaitSignal", "Wait For Signal", ACEDescriptor.ACEType.ACTION, "await {signal_expression}", "", [F.make_param("signal_expression", "String", "get_tree().process_frame", "Signal", "Signal to wait for (e.g. $Timer.timeout).", "expression")], "Time", "Wait for {signal_expression}"))
	descriptors.append(F.make_descriptor("Core", "CallAfterDelay", "Call After Delay", ACEDescriptor.ACEType.ACTION, "get_tree().create_timer({seconds}).timeout.connect({callable})", "", [F.make_param("seconds", "String", "1.0", "Seconds", "Delay before the call fires (does not suspend this event).", "expression"), F.make_param("callable", "String", "queue_free", "Callable", "Method/Callable to invoke after the delay (e.g. queue_free, _on_done).", "expression")], "Time", "Call {callable} after {seconds}s"))
	# Input expressions
	descriptors.append(F.make_descriptor("Core", "GetActionStrength", "Action Strength", ACEDescriptor.ACEType.EXPRESSION, "Input.get_action_strength(&{action})", "", [F.make_param("action", "String", F.default_input_action(), "Action", "Input action (analog strength 0..1).", "", F.input_action_options())], "Input", "strength of {action}"))
	descriptors.append(F.make_descriptor("Core", "GetInputAxis", "Input Axis", ACEDescriptor.ACEType.EXPRESSION, "Input.get_axis(&{negative}, &{positive})", "", [F.make_param("negative", "String", "\"ui_left\"", "Negative", "Action for the negative direction.", "", F.input_action_options()), F.make_param("positive", "String", "\"ui_right\"", "Positive", "Action for the positive direction.", "", F.input_action_options())], "Input", "axis {negative}/{positive}"))
	# ── Native-node providers (C3 coverage Lane 1: wrap NATIVE Godot features; the
	# engine maintains the implementation, we only maintain vocabulary). C3 names are
	# the display names; see docs/C3-MIGRATION-GUIDE.md for the lane mapping.
	# Tween (C3 Tween behavior -> Godot's built-in create_tween)
	descriptors.append(F.make_descriptor("Core", "TweenProperty", "Tween Property", ACEDescriptor.ACEType.ACTION, "create_tween().tween_property({target}, {property}, {value}, {duration}).set_trans({transition}).set_ease({ease})", "", [F.make_param("target", "String", "self", "Target", "Node whose property tweens.", "expression"), F.make_param("property", "String", "\"position\"", "Property", "Property path to animate."), F.make_param("value", "String", "Vector2(100, 0)", "To", "Final value expression.", "expression"), F.make_param("duration", "String", "0.5", "Duration", "Seconds.", "expression"), F.make_param("transition", "String", "Tween.TRANS_SINE", "Transition", "Curve shape.", "", ["Tween.TRANS_LINEAR", "Tween.TRANS_SINE", "Tween.TRANS_QUAD", "Tween.TRANS_CUBIC", "Tween.TRANS_QUART", "Tween.TRANS_ELASTIC", "Tween.TRANS_BACK", "Tween.TRANS_BOUNCE", "Tween.TRANS_EXPO", "Tween.TRANS_CIRC"]), F.make_param("ease", "String", "Tween.EASE_IN_OUT", "Ease", "In / out / in-out.", "", ["Tween.EASE_IN", "Tween.EASE_OUT", "Tween.EASE_IN_OUT"])], "Tween", "Tween {property} to {value} over {duration}s"))
	descriptors.append(F.make_descriptor("Core", "TweenCallback", "Tween Callback", ACEDescriptor.ACEType.ACTION, "create_tween().tween_callback({callable}).set_delay({delay})", "", [F.make_param("callable", "String", "queue_free", "Callable", "Method/Callable to invoke after the delay (e.g. a node method or a lambda).", "expression"), F.make_param("delay", "String", "1.0", "Delay", "Seconds before the call fires.", "expression")], "Tween", "Call {callable} after {delay}s"))
	# Scene flow (C3 System: layouts -> Godot scenes)
	descriptors.append(F.make_descriptor("Core", "ChangeScene", "Go To Scene", ACEDescriptor.ACEType.ACTION, "get_tree().change_scene_to_file({path})", "", [F.make_param("path", "String", "\"res://main.tscn\"", "Scene", "Scene file to switch to.", "expression")], "Scene", "Go to scene {path}"))
	descriptors.append(F.make_descriptor("Core", "ReloadScene", "Restart Scene", ACEDescriptor.ACEType.ACTION, "get_tree().reload_current_scene()", "", [], "Scene", "Restart the current scene"))
	descriptors.append(F.make_descriptor("Core", "QuitGame", "Quit Game", ACEDescriptor.ACEType.ACTION, "get_tree().quit()", "", [], "Scene", "Quit the game"))
	descriptors.append(F.make_descriptor("Core", "SetPaused", "Set Game Paused", ACEDescriptor.ACEType.ACTION, "get_tree().paused = {paused}", "", [F.make_param("paused", "String", "true", "Paused", "Pause state.", "", ["true", "false"])], "Scene", "Set paused to {paused}"))
	descriptors.append(F.make_descriptor("Core", "SpawnScene", "Spawn Scene Instance", ACEDescriptor.ACEType.ACTION, "add_child(load({path}).instantiate())", "", [F.make_param("path", "String", "\"res://enemy.tscn\"", "Scene", "Scene file to instance as a child.", "expression")], "Scene", "Spawn {path}"))
	descriptors.append(F.make_descriptor("Core", "IsPaused", "Is Game Paused", ACEDescriptor.ACEType.CONDITION, "get_tree().paused", "", [], "Scene", "Game is paused"))
	# Audio (AudioStreamPlayer / 2D / 3D share these members)
	descriptors.append(F.make_descriptor("Core", "PlayAudio", "Play Sound", ACEDescriptor.ACEType.ACTION, "play({from_position})", "", [F.make_param("from_position", "String", "0.0", "From", "Start position in seconds.", "expression")], "General Actions", "Play sound", "AudioStreamPlayer"))
	descriptors.append(F.make_descriptor("Core", "StopAudio", "Stop Sound", ACEDescriptor.ACEType.ACTION, "stop()", "", [], "General Actions", "Stop sound", "AudioStreamPlayer"))
	descriptors.append(F.make_descriptor("Core", "SetVolumeDb", "Set Volume (dB)", ACEDescriptor.ACEType.ACTION, "volume_db = {db}", "", [F.make_param("db", "String", "0.0", "Decibels", "0 = full volume, -80 = silent.", "expression")], "General Actions", "Set volume to {db} dB", "AudioStreamPlayer"))
	descriptors.append(F.make_descriptor("Core", "IsAudioPlaying", "Is Playing", ACEDescriptor.ACEType.CONDITION, "playing", "", [], "General Conditions", "Sound is playing", "AudioStreamPlayer"))
	descriptors.append(F.make_descriptor("Core", "GetPlaybackPosition", "Playback Position", ACEDescriptor.ACEType.EXPRESSION, "get_playback_position()", "", [], "General Expressions", "playback position", "AudioStreamPlayer"))
	# AnimatedSprite2D (C3 Sprite animations)
	descriptors.append(F.make_descriptor("Core", "PlaySpriteAnimation", "Play Sprite Animation", ACEDescriptor.ACEType.ACTION, "play(&{anim})", "", [F.make_param("anim", "String", "\"default\"", "Animation", "Animation name.")], "General Actions", "Play animation {anim}", "AnimatedSprite2D"))
	descriptors.append(F.make_descriptor("Core", "StopSpriteAnimation", "Stop Sprite Animation", ACEDescriptor.ACEType.ACTION, "stop()", "", [], "General Actions", "Stop animation", "AnimatedSprite2D"))
	descriptors.append(F.make_descriptor("Core", "SetSpriteFrame", "Set Frame", ACEDescriptor.ACEType.ACTION, "frame = {frame}", "", [F.make_param("frame", "String", "0", "Frame", "Frame index.", "expression")], "General Actions", "Set frame to {frame}", "AnimatedSprite2D"))
	descriptors.append(F.make_descriptor("Core", "SetFlipH", "Set Mirrored", ACEDescriptor.ACEType.ACTION, "flip_h = {flipped}", "", [F.make_param("flipped", "String", "true", "Mirrored", "Horizontal flip.", "", ["true", "false"])], "General Actions", "Set mirrored {flipped}", "AnimatedSprite2D"))
	descriptors.append(F.make_descriptor("Core", "IsSpriteAnimationPlaying", "Is Animation Playing", ACEDescriptor.ACEType.CONDITION, "is_playing()", "", [], "General Conditions", "Animation is playing", "AnimatedSprite2D"))
	descriptors.append(F.make_descriptor("Core", "GetSpriteAnimation", "Current Animation", ACEDescriptor.ACEType.EXPRESSION, "animation", "", [], "General Expressions", "current animation", "AnimatedSprite2D"))
	# Camera2D
	descriptors.append(F.make_descriptor("Core", "MakeCameraCurrent", "Make Camera Current", ACEDescriptor.ACEType.ACTION, "make_current()", "", [], "General Actions", "Make this camera current", "Camera2D"))
	descriptors.append(F.make_descriptor("Core", "SetCameraZoom", "Set Camera Zoom", ACEDescriptor.ACEType.ACTION, "zoom = {zoom}", "", [F.make_param("zoom", "String", "Vector2(1, 1)", "Zoom", "Zoom factor.", "expression")], "General Actions", "Set zoom to {zoom}", "Camera2D"))
	descriptors.append(F.make_descriptor("Core", "SetCameraOffset", "Set Camera Offset", ACEDescriptor.ACEType.ACTION, "offset = {offset}", "", [F.make_param("offset", "String", "Vector2(0, 0)", "Offset", "Offset from the followed position.", "expression")], "General Actions", "Set offset to {offset}", "Camera2D"))
	descriptors.append(F.make_descriptor("Core", "SetCameraLimits", "Set Camera Limits", ACEDescriptor.ACEType.ACTION, "limit_left = {left}\nlimit_top = {top}\nlimit_right = {right}\nlimit_bottom = {bottom}", "", [F.make_param("left", "String", "0", "Left", "Left bound (px).", "expression"), F.make_param("top", "String", "0", "Top", "Top bound (px).", "expression"), F.make_param("right", "String", "1920", "Right", "Right bound (px).", "expression"), F.make_param("bottom", "String", "1080", "Bottom", "Bottom bound (px).", "expression")], "General Actions", "Set camera limits", "Camera2D"))
	# Label / text (C3 Text object)
	descriptors.append(F.make_descriptor("Core", "SetLabelText", "Set Text", ACEDescriptor.ACEType.ACTION, "text = str({value})", "", [F.make_param("value", "String", "\"Hello\"", "Text", "Value to display (str()-converted).", "expression")], "General Actions", "Set text to {value}", "Label"))
	descriptors.append(F.make_descriptor("Core", "AppendLabelText", "Append Text", ACEDescriptor.ACEType.ACTION, "text += str({value})", "", [F.make_param("value", "String", "\"!\"", "Text", "Value to append.", "expression")], "General Actions", "Append {value}", "Label"))
	descriptors.append(F.make_descriptor("Core", "GetLabelText", "Get Text", ACEDescriptor.ACEType.EXPRESSION, "text", "", [], "General Expressions", "text", "Label"))
	# NavigationAgent2D (C3 Pathfinding behavior)
	descriptors.append(F.make_descriptor("Core", "SetNavTarget", "Find Path To", ACEDescriptor.ACEType.ACTION, "target_position = {position}", "", [F.make_param("position", "String", "Vector2(0, 0)", "Target", "World position to path toward.", "expression")], "General Actions", "Find path to {position}", "NavigationAgent2D"))
	descriptors.append(F.make_descriptor("Core", "IsNavFinished", "Has Arrived", ACEDescriptor.ACEType.CONDITION, "is_navigation_finished()", "", [], "General Conditions", "Arrived at destination", "NavigationAgent2D"))
	descriptors.append(F.make_descriptor("Core", "GetNextPathPosition", "Next Path Position", ACEDescriptor.ACEType.EXPRESSION, "get_next_path_position()", "", [], "General Expressions", "next path position", "NavigationAgent2D"))
	descriptors.append(F.make_descriptor("Core", "GetNavDistance", "Distance To Target", ACEDescriptor.ACEType.EXPRESSION, "distance_to_target()", "", [], "General Expressions", "distance to target", "NavigationAgent2D"))
	# Visibility / tint (CanvasItem)
	descriptors.append(F.make_descriptor("Core", "ShowNode", "Show", ACEDescriptor.ACEType.ACTION, "show()", "", [], "General Actions", "Show", "CanvasItem"))
	descriptors.append(F.make_descriptor("Core", "HideNode", "Hide", ACEDescriptor.ACEType.ACTION, "hide()", "", [], "General Actions", "Hide", "CanvasItem"))
	descriptors.append(F.make_descriptor("Core", "SetModulate", "Set Color Tint", ACEDescriptor.ACEType.ACTION, "modulate = {color}", "", [F.make_param("color", "String", "Color(1, 1, 1, 1)", "Color", "Tint (RGBA).", "color")], "General Actions", "Set tint to {color}", "CanvasItem"))
	descriptors.append(F.make_descriptor("Core", "SetSelfModulate", "Set Self Tint", ACEDescriptor.ACEType.ACTION, "self_modulate = {color}", "", [F.make_param("color", "String", "Color(1, 1, 1, 1)", "Color", "Tint for this node only (not children).", "color")], "General Actions", "Set self tint to {color}", "CanvasItem"))
	descriptors.append(F.make_descriptor("Core", "IsVisible", "Is Visible", ACEDescriptor.ACEType.CONDITION, "visible", "", [], "General Conditions", "Is visible", "CanvasItem"))
	# Math & random (C3 System expressions: random, choose, clamp, lerp, distance, angle)
	descriptors.append(F.make_descriptor("Core", "RandomRange", "Random", ACEDescriptor.ACEType.EXPRESSION, "randf_range({from}, {to})", "", [F.make_param("from", "String", "0.0", "From", "Lower bound.", "expression"), F.make_param("to", "String", "1.0", "To", "Upper bound.", "expression")], "Math & Random", "random({from}, {to})"))
	descriptors.append(F.make_descriptor("Core", "RandomInt", "Random Integer", ACEDescriptor.ACEType.EXPRESSION, "randi_range({from}, {to})", "", [F.make_param("from", "String", "0", "From", "Lower bound (inclusive).", "expression"), F.make_param("to", "String", "9", "To", "Upper bound (inclusive).", "expression")], "Math & Random", "random int({from}, {to})"))
	descriptors.append(F.make_descriptor("Core", "Choose", "Choose", ACEDescriptor.ACEType.EXPRESSION, "[{values}].pick_random()", "", [F.make_param("values", "String", "1, 2, 3", "Values", "Comma-separated values to pick from.", "expression")], "Math & Random", "choose({values})"))
	descriptors.append(F.make_descriptor("Core", "ClampValue", "Clamp", ACEDescriptor.ACEType.EXPRESSION, "clampf({value}, {min}, {max})", "", [F.make_param("value", "String", "0.0", "Value", "Value to clamp.", "expression"), F.make_param("min", "String", "0.0", "Min", "Lower bound.", "expression"), F.make_param("max", "String", "1.0", "Max", "Upper bound.", "expression")], "Math & Random", "clamp({value}, {min}, {max})"))
	descriptors.append(F.make_descriptor("Core", "LerpValue", "Lerp", ACEDescriptor.ACEType.EXPRESSION, "lerpf({from}, {to}, {weight})", "", [F.make_param("from", "String", "0.0", "From", "Start value.", "expression"), F.make_param("to", "String", "1.0", "To", "End value.", "expression"), F.make_param("weight", "String", "0.5", "Weight", "0..1 blend.", "expression")], "Math & Random", "lerp({from}, {to}, {weight})"))
	descriptors.append(F.make_descriptor("Core", "DistanceTo", "Distance To", ACEDescriptor.ACEType.EXPRESSION, "position.distance_to({to})", "", [F.make_param("to", "String", "Vector2(0, 0)", "To", "Target position.", "expression")], "Math & Random", "distance to {to}", "Node2D"))
	descriptors.append(F.make_descriptor("Core", "AngleToPoint", "Angle Toward", ACEDescriptor.ACEType.EXPRESSION, "position.angle_to_point({to})", "", [F.make_param("to", "String", "Vector2(0, 0)", "To", "Target position.", "expression")], "Math & Random", "angle toward {to}", "Node2D"))
	# More math idioms (movement / animation / AI reach for these constantly).
	descriptors.append(F.make_descriptor("Core", "Snapped", "Snap To Step", ACEDescriptor.ACEType.EXPRESSION, "snappedf({value}, {step})", "", [F.make_param("value", "String", "0.0", "Value", "Value to snap.", "expression"), F.make_param("step", "String", "1.0", "Step", "Snap increment (e.g. grid size).", "expression")], "Math & Random", "snap {value} to {step}"))
	descriptors.append(F.make_descriptor("Core", "InverseLerp", "Inverse Lerp", ACEDescriptor.ACEType.EXPRESSION, "inverse_lerp({from}, {to}, {value})", "", [F.make_param("from", "String", "0.0", "From", "Range start.", "expression"), F.make_param("to", "String", "1.0", "To", "Range end.", "expression"), F.make_param("value", "String", "0.5", "Value", "Value in the range.", "expression")], "Math & Random", "inverse lerp {value}"))
	descriptors.append(F.make_descriptor("Core", "Smoothstep", "Smoothstep", ACEDescriptor.ACEType.EXPRESSION, "smoothstep({from}, {to}, {value})", "", [F.make_param("from", "String", "0.0", "From", "Edge 0.", "expression"), F.make_param("to", "String", "1.0", "To", "Edge 1.", "expression"), F.make_param("value", "String", "0.5", "Value", "Value to ease.", "expression")], "Math & Random", "smoothstep({from}, {to}, {value})"))
	descriptors.append(F.make_descriptor("Core", "PingPong", "Ping-Pong", ACEDescriptor.ACEType.EXPRESSION, "pingpong({value}, {length})", "", [F.make_param("value", "String", "0.0", "Value", "Input value (often a timer).", "expression"), F.make_param("length", "String", "1.0", "Length", "Bounce length.", "expression")], "Math & Random", "pingpong({value}, {length})"))
	descriptors.append(F.make_descriptor("Core", "AngleDifference", "Angle Difference", ACEDescriptor.ACEType.EXPRESSION, "angle_difference({from}, {to})", "", [F.make_param("from", "String", "0.0", "From", "From angle (radians).", "expression"), F.make_param("to", "String", "0.0", "To", "To angle (radians).", "expression")], "Math & Random", "angle diff {from} -> {to}"))
	descriptors.append(F.make_descriptor("Core", "RotateTowardAngle", "Rotate Toward (angle)", ACEDescriptor.ACEType.EXPRESSION, "rotate_toward({from}, {to}, {delta})", "", [F.make_param("from", "String", "0.0", "From", "Current angle (radians).", "expression"), F.make_param("to", "String", "0.0", "To", "Target angle (radians).", "expression"), F.make_param("delta", "String", "0.1", "Delta", "Max step (radians).", "expression")], "Math & Random", "rotate {from} toward {to}"))
	descriptors.append(F.make_descriptor("Core", "LerpAngle", "Lerp Angle", ACEDescriptor.ACEType.EXPRESSION, "lerp_angle({from}, {to}, {weight})", "", [F.make_param("from", "String", "0.0", "From", "From angle (radians).", "expression"), F.make_param("to", "String", "0.0", "To", "To angle (radians).", "expression"), F.make_param("weight", "String", "0.5", "Weight", "0..1 blend.", "expression")], "Math & Random", "lerp angle {from} -> {to}"))
	descriptors.append(F.make_descriptor("Core", "DegToRad", "Degrees To Radians", ACEDescriptor.ACEType.EXPRESSION, "deg_to_rad({degrees})", "", [F.make_param("degrees", "String", "90.0", "Degrees", "Angle in degrees.", "expression")], "Math & Random", "deg2rad({degrees})"))
	descriptors.append(F.make_descriptor("Core", "RadToDeg", "Radians To Degrees", ACEDescriptor.ACEType.EXPRESSION, "rad_to_deg({radians})", "", [F.make_param("radians", "String", "0.0", "Radians", "Angle in radians.", "expression")], "Math & Random", "rad2deg({radians})"))
	descriptors.append(F.make_descriptor("Core", "PosMod", "Positive Modulo", ACEDescriptor.ACEType.EXPRESSION, "posmod({a}, {b})", "", [F.make_param("a", "String", "0", "A", "Dividend (int).", "expression"), F.make_param("b", "String", "1", "B", "Divisor (int).", "expression")], "Math & Random", "posmod({a}, {b})"))
	descriptors.append(F.make_descriptor("Core", "IsEqualApprox", "Is Equal (approx)", ACEDescriptor.ACEType.CONDITION, "is_equal_approx({a}, {b})", "", [F.make_param("a", "String", "0.0", "A", "First value.", "expression"), F.make_param("b", "String", "0.0", "B", "Second value.", "expression")], "Math & Random", "{a} ≈ {b}"))
	descriptors.append(F.make_descriptor("Core", "IsZeroApprox", "Is Zero (approx)", ACEDescriptor.ACEType.CONDITION, "is_zero_approx({value})", "", [F.make_param("value", "String", "0.0", "Value", "Value to test.", "expression")], "Math & Random", "{value} ≈ 0"))
	descriptors.append(F.make_descriptor("Core", "SeedRandom", "Seed Random", ACEDescriptor.ACEType.ACTION, "seed({value})", "", [F.make_param("value", "String", "0", "Seed", "Integer seed (same seed = same sequence).", "expression")], "Math & Random", "seed RNG with {value}"))
	descriptors.append(F.make_descriptor("Core", "RandomizeSeed", "Randomize Seed", ACEDescriptor.ACEType.ACTION, "randomize()", "", [], "Math & Random", "randomize seed"))

	# Color math — hit flashes, fades, and tints without dropping to GDScript. The colour params
	# are full expressions (a literal, `modulate`, or another colour ACE), so they compose.
	descriptors.append(F.make_descriptor("Core", "ColorLighten", "Lighten Color", ACEDescriptor.ACEType.EXPRESSION, "({color}).lightened({amount})", "", [F.make_param("color", "String", "Color(1, 1, 1, 1)", "Color", "Base colour.", "color"), F.make_param("amount", "String", "0.2", "Amount", "0..1 toward white.", "expression")], "Color", "lighten {color} by {amount}"))
	descriptors.append(F.make_descriptor("Core", "ColorDarken", "Darken Color", ACEDescriptor.ACEType.EXPRESSION, "({color}).darkened({amount})", "", [F.make_param("color", "String", "Color(1, 1, 1, 1)", "Color", "Base colour.", "color"), F.make_param("amount", "String", "0.2", "Amount", "0..1 toward black.", "expression")], "Color", "darken {color} by {amount}"))
	descriptors.append(F.make_descriptor("Core", "ColorLerp", "Lerp Color", ACEDescriptor.ACEType.EXPRESSION, "({from}).lerp({to}, {weight})", "", [F.make_param("from", "String", "Color(1, 1, 1, 1)", "From", "Start colour.", "color"), F.make_param("to", "String", "Color(1, 0, 0, 1)", "To", "End colour.", "color"), F.make_param("weight", "String", "0.5", "Weight", "0..1 blend.", "expression")], "Color", "lerp {from} -> {to}"))
	descriptors.append(F.make_descriptor("Core", "ColorWithAlpha", "Color With Alpha", ACEDescriptor.ACEType.EXPRESSION, "Color({color}, {alpha})", "", [F.make_param("color", "String", "Color(1, 1, 1, 1)", "Color", "Base colour.", "color"), F.make_param("alpha", "String", "0.5", "Alpha", "New alpha 0..1.", "expression")], "Color", "{color} @ alpha {alpha}"))
	descriptors.append(F.make_descriptor("Core", "ColorFromHSV", "Color From HSV", ACEDescriptor.ACEType.EXPRESSION, "Color.from_hsv({h}, {s}, {v}, {a})", "", [F.make_param("h", "String", "0.0", "Hue", "0..1.", "expression"), F.make_param("s", "String", "1.0", "Saturation", "0..1.", "expression"), F.make_param("v", "String", "1.0", "Value", "0..1.", "expression"), F.make_param("a", "String", "1.0", "Alpha", "0..1.", "expression")], "Color", "hsv({h}, {s}, {v})"))
	descriptors.append(F.make_descriptor("Core", "ColorFromHex", "Color From Hex", ACEDescriptor.ACEType.EXPRESSION, "Color.html({hex})", "", [F.make_param("hex", "String", "\"#ff8800\"", "Hex", "HTML colour string.", "expression")], "Color", "color {hex}"))
	descriptors.append(F.make_descriptor("Core", "ColorInverted", "Invert Color", ACEDescriptor.ACEType.EXPRESSION, "({color}).inverted()", "", [F.make_param("color", "String", "Color(1, 1, 1, 1)", "Color", "Colour to invert.", "color")], "Color", "invert {color}"))

	# Expressions
	descriptors.append(F.make_descriptor("Core", "GetVar", "Get Variable", ACEDescriptor.ACEType.EXPRESSION, "{var_name}", "", [F.make_param("var_name", "String", "var", "Variable", "Variable to read.", "variable_reference")], "Variables", "{var_name}"))
	descriptors.append(F.make_descriptor("Core", "GetDelta", "Get Delta", ACEDescriptor.ACEType.EXPRESSION, "delta", "", [], "General Expressions", "delta"))
	descriptors.append(F.make_descriptor("Core", "GetPosition2D", "Get Position", ACEDescriptor.ACEType.EXPRESSION, "position", "", [], "General Expressions", "position", "Node2D"))
	descriptors.append(F.make_descriptor("Core", "GetVelocity2D", "Get Velocity", ACEDescriptor.ACEType.EXPRESSION, "velocity", "", [], "General Expressions", "velocity", "CharacterBody2D"))
	descriptors.append(F.make_descriptor("Core", "GetLinearVelocity2D", "Get Linear Velocity", ACEDescriptor.ACEType.EXPRESSION, "linear_velocity", "", [], "General Expressions", "linear_velocity", "RigidBody2D"))
	descriptors.append(F.make_descriptor("Core", "GetMonitoring", "Get Monitoring", ACEDescriptor.ACEType.EXPRESSION, "monitoring", "", [], "General Expressions", "monitoring", "Area2D"))
	descriptors.append(F.make_descriptor("Core", "GetTimerTimeLeft", "Get Time Left", ACEDescriptor.ACEType.EXPRESSION, "time_left", "", [], "General Expressions", "time_left", "Timer"))
	descriptors.append(F.make_descriptor("Core", "GetCurrentAnimation", "Get Current Animation", ACEDescriptor.ACEType.EXPRESSION, "current_animation", "", [], "General Expressions", "current_animation", "AnimationPlayer"))

	# ── More Array helpers (make list manipulation easy without dropping to code) ──
	descriptors.append(F.make_descriptor("Core", "ArrayFront", "First Item", ACEDescriptor.ACEType.EXPRESSION, "{var_name}.front()", "", [F.make_param("var_name", "String", "list", "Array", "Array variable.", "variable_reference:Array")], "Variables: Array", "{var_name}.front()"))
	descriptors.append(F.make_descriptor("Core", "ArrayBack", "Last Item", ACEDescriptor.ACEType.EXPRESSION, "{var_name}.back()", "", [F.make_param("var_name", "String", "list", "Array", "Array variable.", "variable_reference:Array")], "Variables: Array", "{var_name}.back()"))
	descriptors.append(F.make_descriptor("Core", "ArrayFind", "Index Of", ACEDescriptor.ACEType.EXPRESSION, "{var_name}.find({value})", "", [F.make_param("var_name", "String", "list", "Array", "Array variable.", "variable_reference:Array"), F.make_param("value", "String", "0", "Value", "Value to find (-1 if missing).", "expression")], "Variables: Array", "{var_name}.find({value})"))
	descriptors.append(F.make_descriptor("Core", "ArrayCount", "Count Of", ACEDescriptor.ACEType.EXPRESSION, "{var_name}.count({value})", "", [F.make_param("var_name", "String", "list", "Array", "Array variable.", "variable_reference:Array"), F.make_param("value", "String", "0", "Value", "Value to count.", "expression")], "Variables: Array", "{var_name}.count({value})"))
	descriptors.append(F.make_descriptor("Core", "ArrayReverse", "Reverse Array", ACEDescriptor.ACEType.ACTION, "{var_name}.reverse()", "", [F.make_param("var_name", "String", "list", "Array", "Array variable.", "variable_reference:Array")], "Variables: Array", "Reverse {var_name}"))
	descriptors.append(F.make_descriptor("Core", "ArrayPushFront", "Push To Front", ACEDescriptor.ACEType.ACTION, "{var_name}.push_front({value})", "", [F.make_param("var_name", "String", "list", "Array", "Array variable.", "variable_reference:Array"), F.make_param("value", "String", "0", "Value", "Value to prepend.", "expression")], "Variables: Array", "Push {value} to front of {var_name}"))
	descriptors.append(F.make_descriptor("Core", "ArrayPopBack", "Pop Last", ACEDescriptor.ACEType.EXPRESSION, "{var_name}.pop_back()", "", [F.make_param("var_name", "String", "list", "Array", "Array variable (removes + returns last).", "variable_reference:Array")], "Variables: Array", "{var_name}.pop_back()"))
	descriptors.append(F.make_descriptor("Core", "ArrayPopFront", "Pop First", ACEDescriptor.ACEType.EXPRESSION, "{var_name}.pop_front()", "", [F.make_param("var_name", "String", "list", "Array", "Array variable (removes + returns first).", "variable_reference:Array")], "Variables: Array", "{var_name}.pop_front()"))
	descriptors.append(F.make_descriptor("Core", "ArrayAppendArray", "Append Array", ACEDescriptor.ACEType.ACTION, "{var_name}.append_array({other})", "", [F.make_param("var_name", "String", "list", "Array", "Destination array.", "variable_reference:Array"), F.make_param("other", "String", "[]", "Other", "Array whose items are appended.", "expression")], "Variables: Array", "Append {other} to {var_name}"))
	descriptors.append(F.make_descriptor("Core", "ArraySlice", "Slice", ACEDescriptor.ACEType.EXPRESSION, "{var_name}.slice({from}, {to})", "", [F.make_param("var_name", "String", "list", "Array", "Array variable.", "variable_reference:Array"), F.make_param("from", "String", "0", "From", "Start index.", "expression"), F.make_param("to", "String", "1", "To", "End index (exclusive).", "expression")], "Variables: Array", "{var_name}.slice({from}, {to})"))
	descriptors.append(F.make_descriptor("Core", "ArrayJoin", "Join To Text", ACEDescriptor.ACEType.EXPRESSION, "{separator}.join({var_name})", "", [F.make_param("var_name", "String", "list", "Array", "Array of strings.", "variable_reference:Array"), F.make_param("separator", "String", "\", \"", "Separator", "String between items.", "expression")], "Variables: Array", "join {var_name} with {separator}"))
	descriptors.append(F.make_descriptor("Core", "ArrayMax", "Array Max", ACEDescriptor.ACEType.EXPRESSION, "{var_name}.max()", "", [F.make_param("var_name", "String", "list", "Array", "Array variable.", "variable_reference:Array")], "Variables: Array", "{var_name}.max()"))
	descriptors.append(F.make_descriptor("Core", "ArrayMin", "Array Min", ACEDescriptor.ACEType.EXPRESSION, "{var_name}.min()", "", [F.make_param("var_name", "String", "list", "Array", "Array variable.", "variable_reference:Array")], "Variables: Array", "{var_name}.min()"))
	descriptors.append(F.make_descriptor("Core", "ArrayDuplicate", "Copy Array", ACEDescriptor.ACEType.EXPRESSION, "{var_name}.duplicate()", "", [F.make_param("var_name", "String", "list", "Array", "Array variable to copy.", "variable_reference:Array")], "Variables: Array", "{var_name}.duplicate()"))
	descriptors.append(F.make_descriptor("Core", "ArrayResize", "Resize Array", ACEDescriptor.ACEType.ACTION, "{var_name}.resize({size})", "", [F.make_param("var_name", "String", "list", "Array", "Array variable.", "variable_reference:Array"), F.make_param("size", "String", "0", "Size", "New length.", "expression")], "Variables: Array", "Resize {var_name} to {size}"))
	descriptors.append(F.make_descriptor("Core", "ArrayFill", "Fill Array", ACEDescriptor.ACEType.ACTION, "{var_name}.fill({value})", "", [F.make_param("var_name", "String", "list", "Array", "Array variable.", "variable_reference:Array"), F.make_param("value", "String", "0", "Value", "Value to fill every slot with.", "expression")], "Variables: Array", "Fill {var_name} with {value}"))

	# ── More Dictionary helpers ──
	descriptors.append(F.make_descriptor("Core", "DictDuplicate", "Copy Dictionary", ACEDescriptor.ACEType.EXPRESSION, "{var_name}.duplicate()", "", [F.make_param("var_name", "String", "dict", "Dictionary", "Dictionary variable to copy.", "variable_reference:Dictionary")], "Variables: Dictionary", "{var_name}.duplicate()"))
	descriptors.append(F.make_descriptor("Core", "DictHasValue", "Has Value", ACEDescriptor.ACEType.CONDITION, "{var_name}.values().has({value})", "", [F.make_param("var_name", "String", "dict", "Dictionary", "Dictionary variable.", "variable_reference:Dictionary"), F.make_param("value", "String", "0", "Value", "Value to look for.", "expression")], "Variables: Dictionary", "{var_name} has value {value}"))

	# ── Vector helpers (Vector2/Vector3 manipulation) ──
	descriptors.append(F.make_descriptor("Core", "MakeVector2", "Make Vector2", ACEDescriptor.ACEType.EXPRESSION, "Vector2({x}, {y})", "", [F.make_param("x", "String", "0.0", "X", "X component.", "expression"), F.make_param("y", "String", "0.0", "Y", "Y component.", "expression")], "Variables: Vector", "Vector2({x}, {y})"))
	descriptors.append(F.make_descriptor("Core", "MakeVector3", "Make Vector3", ACEDescriptor.ACEType.EXPRESSION, "Vector3({x}, {y}, {z})", "", [F.make_param("x", "String", "0.0", "X", "X component.", "expression"), F.make_param("y", "String", "0.0", "Y", "Y component.", "expression"), F.make_param("z", "String", "0.0", "Z", "Z component.", "expression")], "Variables: Vector", "Vector3({x}, {y}, {z})"))
	descriptors.append(F.make_descriptor("Core", "VectorLength", "Vector Length", ACEDescriptor.ACEType.EXPRESSION, "{vector}.length()", "", [F.make_param("vector", "String", "Vector2.ZERO", "Vector", "Vector expression.", "expression")], "Variables: Vector", "{vector}.length()"))
	descriptors.append(F.make_descriptor("Core", "VectorNormalized", "Normalized", ACEDescriptor.ACEType.EXPRESSION, "{vector}.normalized()", "", [F.make_param("vector", "String", "Vector2.ZERO", "Vector", "Vector expression.", "expression")], "Variables: Vector", "{vector}.normalized()"))
	descriptors.append(F.make_descriptor("Core", "VectorDistanceTo", "Distance Between", ACEDescriptor.ACEType.EXPRESSION, "{a}.distance_to({b})", "", [F.make_param("a", "String", "Vector2.ZERO", "From", "First point.", "expression"), F.make_param("b", "String", "Vector2.ZERO", "To", "Second point.", "expression")], "Variables: Vector", "{a}.distance_to({b})"))
	descriptors.append(F.make_descriptor("Core", "VectorDirectionTo", "Direction To", ACEDescriptor.ACEType.EXPRESSION, "{a}.direction_to({b})", "", [F.make_param("a", "String", "Vector2.ZERO", "From", "Start point.", "expression"), F.make_param("b", "String", "Vector2.ZERO", "To", "Target point.", "expression")], "Variables: Vector", "{a}.direction_to({b})"))
	descriptors.append(F.make_descriptor("Core", "VectorAngle", "Vector Angle", ACEDescriptor.ACEType.EXPRESSION, "{vector}.angle()", "", [F.make_param("vector", "String", "Vector2.ZERO", "Vector", "Vector2 expression (radians).", "expression")], "Variables: Vector", "{vector}.angle()"))
	descriptors.append(F.make_descriptor("Core", "VectorDot", "Dot Product", ACEDescriptor.ACEType.EXPRESSION, "{a}.dot({b})", "", [F.make_param("a", "String", "Vector2.ZERO", "A", "First vector.", "expression"), F.make_param("b", "String", "Vector2.ZERO", "B", "Second vector.", "expression")], "Variables: Vector", "{a}.dot({b})"))
	descriptors.append(F.make_descriptor("Core", "VectorRotated", "Rotated", ACEDescriptor.ACEType.EXPRESSION, "{vector}.rotated({radians})", "", [F.make_param("vector", "String", "Vector2.ZERO", "Vector", "Vector2 expression.", "expression"), F.make_param("radians", "String", "0.0", "Radians", "Rotation in radians.", "expression")], "Variables: Vector", "{vector}.rotated({radians})"))
	descriptors.append(F.make_descriptor("Core", "VectorLerp", "Vector Lerp", ACEDescriptor.ACEType.EXPRESSION, "{a}.lerp({b}, {weight})", "", [F.make_param("a", "String", "Vector2.ZERO", "From", "Start vector.", "expression"), F.make_param("b", "String", "Vector2.ZERO", "To", "End vector.", "expression"), F.make_param("weight", "String", "0.5", "Weight", "0..1 blend.", "expression")], "Variables: Vector", "{a}.lerp({b}, {weight})"))
	descriptors.append(F.make_descriptor("Core", "VectorLimitLength", "Clamp Length", ACEDescriptor.ACEType.EXPRESSION, "{vector}.limit_length({max_length})", "", [F.make_param("vector", "String", "Vector2.ZERO", "Vector", "Vector expression.", "expression"), F.make_param("max_length", "String", "1.0", "Max length", "Maximum magnitude.", "expression")], "Variables: Vector", "{vector}.limit_length({max_length})"))

	# ── String helpers (the common manipulations; the long tail stays one fx away) ──
	descriptors.append(F.make_descriptor("Core", "StringContains", "Text Contains", ACEDescriptor.ACEType.CONDITION, "{text}.contains({needle})", "", [F.make_param("text", "String", "\"\"", "Text", "Text to search.", "expression"), F.make_param("needle", "String", "\"\"", "Needle", "Substring to find.", "expression")], "Variables: String", "{text} contains {needle}"))
	descriptors.append(F.make_descriptor("Core", "StringBeginsWith", "Text Begins With", ACEDescriptor.ACEType.CONDITION, "{text}.begins_with({prefix})", "", [F.make_param("text", "String", "\"\"", "Text", "Text to test.", "expression"), F.make_param("prefix", "String", "\"\"", "Prefix", "Expected prefix.", "expression")], "Variables: String", "{text} begins with {prefix}"))
	descriptors.append(F.make_descriptor("Core", "StringEndsWith", "Text Ends With", ACEDescriptor.ACEType.CONDITION, "{text}.ends_with({suffix})", "", [F.make_param("text", "String", "\"\"", "Text", "Text to test.", "expression"), F.make_param("suffix", "String", "\"\"", "Suffix", "Expected suffix.", "expression")], "Variables: String", "{text} ends with {suffix}"))
	descriptors.append(F.make_descriptor("Core", "StringSplit", "Split Text", ACEDescriptor.ACEType.EXPRESSION, "{text}.split({separator})", "", [F.make_param("text", "String", "\"\"", "Text", "Text to split.", "expression"), F.make_param("separator", "String", "\",\"", "Separator", "Delimiter.", "expression")], "Variables: String", "{text}.split({separator})"))
	descriptors.append(F.make_descriptor("Core", "StringToInt", "Text To Int", ACEDescriptor.ACEType.EXPRESSION, "{text}.to_int()", "", [F.make_param("text", "String", "\"0\"", "Text", "Text to parse.", "expression")], "Variables: String", "{text}.to_int()"))
	descriptors.append(F.make_descriptor("Core", "StringToFloat", "Text To Float", ACEDescriptor.ACEType.EXPRESSION, "{text}.to_float()", "", [F.make_param("text", "String", "\"0.0\"", "Text", "Text to parse.", "expression")], "Variables: String", "{text}.to_float()"))
	descriptors.append(F.make_descriptor("Core", "StringPadZeros", "Pad Number", ACEDescriptor.ACEType.EXPRESSION, "str({number}).pad_zeros({digits})", "", [F.make_param("number", "String", "0", "Number", "Number to pad.", "expression"), F.make_param("digits", "String", "2", "Digits", "Minimum digit count.", "expression")], "Variables: String", "pad {number} to {digits} digits"))
	descriptors.append(F.make_descriptor("Core", "StringRepeat", "Repeat Text", ACEDescriptor.ACEType.EXPRESSION, "{text}.repeat({count})", "", [F.make_param("text", "String", "\"#\"", "Text", "Text to repeat.", "expression"), F.make_param("count", "String", "3", "Count", "Number of repetitions.", "expression")], "Variables: String", "{text} x {count}"))

	# ── AnimationTree (C3-style state machines / blends) ──
	descriptors.append(F.make_descriptor("Core", "SetAnimationTreeActive", "Set AnimationTree Active", ACEDescriptor.ACEType.ACTION, "active = {active}", "", [F.make_param("active", "String", "true", "Active", "Enable the animation tree.", "", ["true", "false"])], "Animation", "Set tree active {active}", "AnimationTree"))
	descriptors.append(F.make_descriptor("Core", "TravelToState", "Travel To State", ACEDescriptor.ACEType.ACTION, "get(\"parameters/playback\").travel({state})", "", [F.make_param("state", "String", "\"idle\"", "State", "State-machine node to travel to.")], "Animation", "Travel to state {state}", "AnimationTree"))
	descriptors.append(F.make_descriptor("Core", "SetTreeParam", "Set Tree Parameter", ACEDescriptor.ACEType.ACTION, "set({path}, {value})", "", [F.make_param("path", "String", "\"parameters/TimeScale/scale\"", "Param Path", "AnimationTree parameter path (blend amount / condition / timescale)."), F.make_param("value", "String", "1.0", "Value", "Value (number / Vector2 / bool).", "expression")], "Animation", "Set {path} to {value}", "AnimationTree"))
	descriptors.append(F.make_descriptor("Core", "IsTreeActive", "Is Tree Active", ACEDescriptor.ACEType.CONDITION, "active", "", [], "Animation", "Is tree active", "AnimationTree"))
	descriptors.append(F.make_descriptor("Core", "IsInState", "Is In State", ACEDescriptor.ACEType.CONDITION, "get(\"parameters/playback\").get_current_node() == {state}", "", [F.make_param("state", "String", "\"idle\"", "State", "State-machine node name.")], "Animation", "Is in state {state}", "AnimationTree"))
	descriptors.append(F.make_descriptor("Core", "GetCurrentState", "Current State", ACEDescriptor.ACEType.EXPRESSION, "get(\"parameters/playback\").get_current_node()", "", [], "Animation", "current state", "AnimationTree"))
	descriptors.append(F.make_descriptor("Core", "GetTreeParam", "Tree Parameter", ACEDescriptor.ACEType.EXPRESSION, "get({path})", "", [F.make_param("path", "String", "\"parameters/TimeScale/scale\"", "Param Path", "AnimationTree parameter path.")], "Animation", "param {path}", "AnimationTree"))

	return descriptors
