# EventForge module - Collections (rich variables)
#
# Curated Dictionary/Array/JSON vocabulary - every op a direct GDScript one-liner.
# Module contract: see ace_factory.gd - ace_ids/templates are API (compatibility
# covenant); this file only changes where the descriptors are AUTHORED.
@tool
class_name EventForgeCollectionACEs
extends RefCounted

const F := preload("res://addons/eventforge/registration/ace_factory.gd")

## The named parts a pair, a triple, a colour or a record can be read and written by, shared by
## Part Of and Set Part Of so the two sides can never drift apart. The keys are QUOTED strings
## because the emitted access is a subscript (`velocity["y"]`, `save["score"]`): Godot resolves a
## string subscript as a COMPONENT on Vector2/Vector3/Color and as a FIELD on a Dictionary, which is
## what lets one verb speak about all four. The labels carry the plain-English half ("the up/down
## part" rather than ".y"). An option value can never contain a {param} placeholder - substitution
## is a single left-to-right pass, so a placeholder arriving FROM an option would be emitted
## literally into the user's GDScript.
## The warning the type-guarded fallbacks all owe the author, in the ROW's own help rather than only
## in a code comment: their guard re-reads the value expression, so a value that CHANGES something
## each time it is read (a method that consumes, deals or advances) runs twice per row.
const DOUBLE_READ_NOTE := "The value is read twice in the emitted line, so keep it a plain read and not something that changes the game."

const PART_OPTIONS: Array = [
	{"key": "\"x\"", "label": "X (left / right)"},
	{"key": "\"y\"", "label": "Y (up / down)"},
	{"key": "\"z\"", "label": "Z (forward / back)"},
	{"key": "\"r\"", "label": "Red"},
	{"key": "\"g\"", "label": "Green"},
	{"key": "\"b\"", "label": "Blue"},
	{"key": "\"a\"", "label": "Alpha (see-through)"}
]


static func get_descriptors() -> Array[ACEDescriptor]:
	var descriptors: Array[ACEDescriptor] = []

	# ── Collections (rich variables): curated Dictionary / Array / JSON vocabulary ──
	# Event sheets ship these as capability addons; here every op is a direct GDScript one-liner
	# (parity-safe) and the templates double as GDScript teachers. The long tail stays
	# one fx away. Variable params use "variable_reference:<Type>" so dropdowns offer
	# only matching (or Variant/untyped) variables.
	# Dictionary
	descriptors.append(F.act("DictSetKey", "Set Key", "{var_name}[{key}] = {value}", "Variables: Dictionary", "Set {var_name}[{key}] to {value}", "Stores a value under a key in a dictionary variable, adding or overwriting it.").param("var_name", "dict", "Dictionary", "Dictionary variable to write into.", "variable_reference:Dictionary").param("key", "\"key\"", "Key", "Key expression.", "expression").param("value", "0", "Value", "Value expression.", "expression"))
	descriptors.append(F.act("DictDeleteKey", "Delete Key", "{var_name}.erase({key})", "Variables: Dictionary", "Delete key {key} from {var_name}", "Removes a key and its value from a dictionary variable.").param("var_name", "dict", "Dictionary", "Dictionary variable.", "variable_reference:Dictionary").param("key", "\"key\"", "Key", "Key to remove.", "expression"))
	descriptors.append(F.act("DictClear", "Clear Dictionary", "{var_name}.clear()", "Variables: Dictionary", "Clear {var_name}", "Empties a dictionary variable, removing every key and value.").param("var_name", "dict", "Dictionary", "Dictionary variable.", "variable_reference:Dictionary"))
	descriptors.append(F.act("DictMerge", "Merge Dictionary", "{var_name}.merge({other}, true)", "Variables: Dictionary", "Merge {other} into {var_name}", "Copies another dictionary's keys into this one, overwriting any clashes.").param("var_name", "dict", "Dictionary", "Destination dictionary.", "variable_reference:Dictionary").param("other", "{}", "Other", "Dictionary to merge in (overwrites).", "expression"))
	descriptors.append(F.cond("DictHasKey", "Has Key", "{var_name}.has({key})", "Variables: Dictionary", "{var_name} has key {key}", "True when the dictionary contains the given key.").param("var_name", "dict", "Dictionary", "Dictionary variable.", "variable_reference:Dictionary").param("key", "\"key\"", "Key", "Key to test.", "expression"))
	descriptors.append(F.cond("DictHasAllKeys", "Has All Keys", "{var_name}.has_all({keys})", "Variables: Dictionary", "{var_name} has all {keys}", "True when the dictionary contains every key in the given list.").param("var_name", "dict", "Dictionary", "Dictionary variable.", "variable_reference:Dictionary").param("keys", "[\"a\", \"b\"]", "Keys", "Array of keys that must all be present.", "expression"))
	descriptors.append(F.cond("DictIsEmpty", "Dictionary Is Empty", "{var_name}.is_empty()", "Variables: Dictionary", "{var_name} is empty", "True when the dictionary has no keys at all.").param("var_name", "dict", "Dictionary", "Dictionary variable.", "variable_reference:Dictionary"))
	descriptors.append(F.expr("DictGet", "Get Key (with default)", "{var_name}.get({key}, {default})", "Variables: Dictionary", "{var_name}.get({key})", "Reads a key's value, returning your fallback when the key is missing.").param("var_name", "dict", "Dictionary", "Dictionary variable.", "variable_reference:Dictionary").param("key", "\"key\"", "Key", "Key to read.", "expression").param("default", "0", "Default", "Fallback when the key is missing.", "expression"))
	descriptors.append(F.expr("DictSize", "Dictionary Size", "{var_name}.size()", "Variables: Dictionary", "{var_name}.size()", "Gives how many keys the dictionary currently holds.").param("var_name", "dict", "Dictionary", "Dictionary variable.", "variable_reference:Dictionary"))
	descriptors.append(F.expr("DictKeys", "Dictionary Keys", "{var_name}.keys()", "Variables: Dictionary", "{var_name}.keys()", "Gives a list of all the dictionary's keys.").param("var_name", "dict", "Dictionary", "Dictionary variable.", "variable_reference:Dictionary"))
	descriptors.append(F.expr("DictValues", "Dictionary Values", "{var_name}.values()", "Variables: Dictionary", "{var_name}.values()", "Gives a list of all the dictionary's values.").param("var_name", "dict", "Dictionary", "Dictionary variable.", "variable_reference:Dictionary"))
	# Array
	descriptors.append(F.act("ArrayAppend", "Push Back", "{var_name}.append({value})", "Variables: Array", "Push back {value} to {var_name}", "Adds a value to the end of an array variable.").param("var_name", "list", "Array", "Array variable.", "variable_reference:Array").param("value", "0", "Value", "Value to append.", "expression"))
	descriptors.append(F.act("ArrayInsert", "Insert At", "{var_name}.insert({index}, {value})", "Variables: Array", "Insert {value} at {index} in {var_name}", "Inserts a value into an array at a specific position.").param("var_name", "list", "Array", "Array variable.", "variable_reference:Array").param("index", "0", "Index", "Insertion index.", "expression").param("value", "0", "Value", "Value to insert.", "expression"))
	descriptors.append(F.act("ArrayRemoveAt", "Delete At", "{var_name}.remove_at({index})", "Variables: Array", "Delete at {index} in {var_name}", "Removes the item at a specific position in an array.").param("var_name", "list", "Array", "Array variable.", "variable_reference:Array").param("index", "0", "Index", "Index to remove.", "expression"))
	descriptors.append(F.act("ArrayErase", "Delete Value", "{var_name}.erase({value})", "Variables: Array", "Delete value {value} from {var_name}", "Removes the first item in the array that matches a given value.").param("var_name", "list", "Array", "Array variable.", "variable_reference:Array").param("value", "0", "Value", "First matching value to remove.", "expression"))
	descriptors.append(F.act("ArrayClear", "Clear Array", "{var_name}.clear()", "Variables: Array", "Clear {var_name}", "Empties an array, removing every item.").param("var_name", "list", "Array", "Array variable.", "variable_reference:Array"))
	descriptors.append(F.act("ArraySort", "Sort Array", "{var_name}.sort()", "Variables: Array", "Sort {var_name}", "Sorts an array's items into ascending order.").param("var_name", "list", "Array", "Array variable.", "variable_reference:Array"))
	descriptors.append(F.act("ArrayShuffle", "Shuffle Array", "{var_name}.shuffle()", "Variables: Array", "Shuffle {var_name}", "Randomly reorders the items in an array.").param("var_name", "list", "Array", "Array variable.", "variable_reference:Array"))
	descriptors.append(F.cond("ArrayContains", "Contains", "{var_name}.has({value})", "Variables: Array", "{var_name} contains {value}", "True when the array holds the given value somewhere.").param("var_name", "list", "Array", "Array variable.", "variable_reference:Array").param("value", "0", "Value", "Value to look for.", "expression"))
	descriptors.append(F.cond("ArrayIsEmpty", "Array Is Empty", "{var_name}.is_empty()", "Variables: Array", "{var_name} is empty", "True when the array has no items at all.").param("var_name", "list", "Array", "Array variable.", "variable_reference:Array"))
	descriptors.append(F.expr("ArrayAt", "Value At", "{var_name}[{index}]", "Variables: Array", "{var_name}[{index}]", "Gives the item stored at a specific position in the array.").param("var_name", "list", "Array", "Array variable.", "variable_reference:Array").param("index", "0", "Index", "Index to read.", "expression"))
	descriptors.append(F.expr("ArraySize", "Array Size", "{var_name}.size()", "Variables: Array", "{var_name}.size()", "Gives how many items the array currently holds.").param("var_name", "list", "Array", "Array variable.", "variable_reference:Array"))
	descriptors.append(F.expr("ArrayPickRandom", "Pick Random", "{var_name}.pick_random()", "Variables: Array", "random of {var_name}", "Gives one random item picked from the array.").param("var_name", "list", "Array", "Array variable.", "variable_reference:Array"))
	# JSON moved to its own module (json_aces.gd / EventForgeJsonACEs) so it is its own thing.

	# Time (System: Wait - handlers are implicit coroutines, await is safe anywhere)
	descriptors.append(F.act("Wait", "Wait", "await get_tree().create_timer({seconds}).timeout", "Time", "Wait {seconds} seconds", "Pauses this event for a number of seconds before continuing.").param("seconds", "1.0", "Seconds", "How long to wait before the next action runs.", "expression"))
	descriptors.append(F.act("AwaitSignal", "Wait For Signal", "await {signal_expression}", "Time", "Wait for {signal_expression}", "Pauses this event until a chosen signal fires, like a timer finishing.").param("signal_expression", "get_tree().process_frame", "Signal", "Signal to wait for (e.g. $Timer.timeout).", "expression"))
	# Frame budgeting (ADVANCED - frame-spreading): hand-roll loop spreading.
	# The handler becomes an implicit coroutine, so use these ONLY inside a one-shot trigger
	# (On Ready / On Signal / a custom function) with a run-once guard - NEVER inside a re-firing On
	# Process, where overlapping suspended runs would duplicate work. For the easy path use the Time Slicer pack.
	descriptors.append(F.act("AwaitNextFrame", "Await Next Frame", "await get_tree().process_frame", "Performance", "Wait one tick", "Pauses this event until the next game frame, to spread work out."))
	descriptors.append(F.act("BeginFrameBudget", "Begin Frame Budget", "var __ace_budget_end := Time.get_ticks_usec() + int({ms} * 1000.0)", "Performance", "begin {ms}ms frame budget", "Starts a per-frame time budget for the loop that follows, to avoid stutter.").param("ms", "8.0", "Budget (ms)", "Per-frame millisecond budget for the loop that follows (pair with Await If Over Budget in the SAME handler).", "expression"))
	descriptors.append(F.act("AwaitIfOverBudget", "Await If Over Budget", "if Time.get_ticks_usec() >= __ace_budget_end:\n\t__ace_budget_end = Time.get_ticks_usec() + int({ms} * 1000.0)\n\tawait get_tree().process_frame", "Performance", "await if over {ms}ms budget", "Yields to the next frame only if this frame's time budget is used up.").param("ms", "8.0", "Budget (ms)", "Re-arm budget after yielding (match Begin Frame Budget). Drop at the bottom of a loop body to self-pace it.", "expression"))
	descriptors.append(F.act("CallAfterDelay", "Call After Delay", "get_tree().create_timer({seconds}).timeout.connect({callable})", "Time", "Call {callable} after {seconds}s", "Schedules a method to run later without pausing this event.").param("seconds", "1.0", "Seconds", "Delay before the call fires (does not suspend this event).", "expression").param("callable", "queue_free", "Callable", "Method/Callable to invoke after the delay (e.g. queue_free, _on_done).", "expression"))
	# Repeat With Delay: the drip-feed loop. Written by hand this is a for loop with an await inside,
	# which is exactly the shape beginners get wrong; as one row it stays honest about suspending -
	# the handler becomes a coroutine for the whole burst, same contract as Wait.
	descriptors.append(F.act("RepeatWithDelay", "Repeat With Delay", "for __rep_{uid}: int in maxi({times}, 0):\n\t{do}\n\tawait get_tree().create_timer(maxf({delay}, 0.001)).timeout", "Time", "{times} times, {delay}s apart: {do}", "Runs one statement several times with a pause between each - burst fire, drip-spawns, a ticking countdown. It suspends this event the same way Wait does, so pair it with Once At A Time (Single Flight) when the trigger can fire again mid-burst.").param("times", "5", "Times", "How many repeats to run.", "expression").param("delay", "0.1", "Seconds Apart", "Pause between repeats.", "expression").param("do", "print(\"beat\")", "Do", "One call or statement, run each repeat.", "expression"))
	# ── The waits that can end two ways ───────────────────────────────────────────────────
	# Wait pauses for a clock and Wait For Signal for one signal; these three wait for a CHECK, for
	# ALL of several signals, or for the FIRST of them. Each one ends either way, so each writes its
	# verdict into node metadata keyed by the NAME you give it (1 = succeeded, 2 = timed out, unset =
	# never ran), and the next row reads it back with the ordinary conditions Wait Succeeded / Wait
	# Timed Out. Same store as the cooldowns, so a wait started in one event is readable in another.
	# A timeout ALSO reports the failure on the sheet's verb_failed signal when the sheet declares
	# one, so a loading screen owned by another event can handle it as an On Failure Of trigger.
	# Wait Until POLLS: where a pack already emits a signal for what you are waiting on (Run In
	# Background's On Done, Time Slicer's On Drained), wait for that signal instead - and use Wait
	# For All Of / Wait For Any Of to COMBINE those signals rather than replace them.
	descriptors.append(F.act("WaitUntil", "Wait Until", "var __wait_end_{uid}: int = Time.get_ticks_msec() + int(maxf({seconds}, 0.0) * 1000.0)\nvar __wait_ok_{uid}: bool = true\nwhile not ({check}):\n\tif {seconds} > 0.0 and Time.get_ticks_msec() >= __wait_end_{uid}:\n\t\t__wait_ok_{uid} = false\n\t\tbreak\n\tawait get_tree().process_frame\nset_meta(&\"__ef_wait_\" + str({wait_name}).to_utf8_buffer().hex_encode(), 1 if __wait_ok_{uid} else 2)\nif not __wait_ok_{uid} and has_signal(&\"verb_failed\"):\n\temit_signal(&\"verb_failed\", str({wait_name}), \"timed out after \" + str({seconds}) + \"s\")", "Time", "wait [b]{wait_name}[/b] until [b]{check}[/b], give up after [b]{seconds}[/b]s", "Pauses this event until a check comes true, or until the give-up time passes. Read which happened on the next row with Wait Succeeded / Wait Timed Out, naming this wait. It polls once a frame, so prefer Wait For Signal when a real signal exists for what you are waiting on.").param("wait_name", "\"loading\"", "Named", "A name for this wait, so Wait Succeeded / Wait Timed Out can say which one they mean.", "expression").param("check", "true", "Until", "The check to wait for, tested once a frame.", "expression").param("seconds", "5.0", "Give Up After", "Seconds before giving up. 0 waits forever.", "expression"))
	descriptors.append(F.act("WaitForAllOf", "Wait For All Of", "var __join_left_{uid}: Array[int] = [0]\nvar __join_conns_{uid}: Array = []\nfor __sig_{uid}: Signal in {signals}:\n\tvar __arity_{uid}: int = 0\n\tfor __info_{uid}: Dictionary in __sig_{uid}.get_object().get_signal_list():\n\t\tif str(__info_{uid}.get(\"name\", \"\")) == str(__sig_{uid}.get_name()):\n\t\t\t__arity_{uid} = (__info_{uid}.get(\"args\", []) as Array).size()\n\t__join_left_{uid}[0] += 1\n\tvar __cb_{uid}: Callable = func() -> void: __join_left_{uid}[0] -= 1\n\tif __arity_{uid} > 0:\n\t\t__cb_{uid} = __cb_{uid}.unbind(__arity_{uid})\n\t__sig_{uid}.connect(__cb_{uid}, CONNECT_ONE_SHOT)\n\t__join_conns_{uid}.append([__sig_{uid}, __cb_{uid}])\nvar __join_end_{uid}: int = Time.get_ticks_msec() + int(maxf({seconds}, 0.0) * 1000.0)\nvar __join_ok_{uid}: bool = true\nwhile __join_left_{uid}[0] > 0:\n\tif {seconds} > 0.0 and Time.get_ticks_msec() >= __join_end_{uid}:\n\t\t__join_ok_{uid} = false\n\t\tbreak\n\tawait get_tree().process_frame\nfor __conn_{uid}: Array in __join_conns_{uid}:\n\tif is_instance_valid((__conn_{uid}[0] as Signal).get_object()) and (__conn_{uid}[0] as Signal).is_connected(__conn_{uid}[1] as Callable):\n\t\t(__conn_{uid}[0] as Signal).disconnect(__conn_{uid}[1] as Callable)\nset_meta(&\"__ef_wait_\" + str({wait_name}).to_utf8_buffer().hex_encode(), 1 if __join_ok_{uid} else 2)\nif not __join_ok_{uid} and has_signal(&\"verb_failed\"):\n\temit_signal(&\"verb_failed\", str({wait_name}), \"timed out after \" + str({seconds}) + \"s\")", "Time", "wait [b]{wait_name}[/b] for ALL of [b]{signals}[/b], give up after [b]{seconds}[/b]s", "Pauses this event until every signal in the list has fired at least once, or until the give-up time passes. It connects them ALL up front, one-shot, so nothing can fire into the gap between two waits - the bug a hand-written chain of awaits always has. An empty list succeeds at once.").param("wait_name", "\"gate\"", "Named", "A name for this wait, so Wait Succeeded / Wait Timed Out can say which one they mean.", "expression").param("signals", "[]", "Signals", "The signals to join, as a list: [$Door.opened, $Camera.arrived].", "expression").param("seconds", "8.0", "Give Up After", "Seconds before giving up. 0 waits forever.", "expression"))
	descriptors.append(F.act("WaitForAnyOf", "Wait For Any Of", "var __any_won_{uid}: Array[String] = [\"\"]\nvar __any_conns_{uid}: Array = []\nfor __sig_{uid}: Signal in {signals}:\n\tvar __arity_{uid}: int = 0\n\tfor __info_{uid}: Dictionary in __sig_{uid}.get_object().get_signal_list():\n\t\tif str(__info_{uid}.get(\"name\", \"\")) == str(__sig_{uid}.get_name()):\n\t\t\t__arity_{uid} = (__info_{uid}.get(\"args\", []) as Array).size()\n\tvar __owner_{uid}: Object = __sig_{uid}.get_object()\n\tvar __won_{uid}: String = ((__owner_{uid} as Node).name + \".\" if __owner_{uid} is Node else \"\") + str(__sig_{uid}.get_name())\n\tvar __cb_{uid}: Callable = func() -> void: __any_won_{uid}[0] = __won_{uid} if __any_won_{uid}[0] == \"\" else __any_won_{uid}[0]\n\tif __arity_{uid} > 0:\n\t\t__cb_{uid} = __cb_{uid}.unbind(__arity_{uid})\n\t__sig_{uid}.connect(__cb_{uid}, CONNECT_ONE_SHOT)\n\t__any_conns_{uid}.append([__sig_{uid}, __cb_{uid}])\nvar __any_end_{uid}: int = Time.get_ticks_msec() + int(maxf({seconds}, 0.0) * 1000.0)\nwhile __any_won_{uid}[0] == \"\":\n\tif {seconds} > 0.0 and Time.get_ticks_msec() >= __any_end_{uid}:\n\t\tbreak\n\tawait get_tree().process_frame\nfor __conn_{uid}: Array in __any_conns_{uid}:\n\tif is_instance_valid((__conn_{uid}[0] as Signal).get_object()) and (__conn_{uid}[0] as Signal).is_connected(__conn_{uid}[1] as Callable):\n\t\t(__conn_{uid}[0] as Signal).disconnect(__conn_{uid}[1] as Callable)\nset_meta(&\"__ef_first_\" + str({wait_name}).to_utf8_buffer().hex_encode(), __any_won_{uid}[0])\nset_meta(&\"__ef_wait_\" + str({wait_name}).to_utf8_buffer().hex_encode(), 1 if __any_won_{uid}[0] != \"\" else 2)\nif __any_won_{uid}[0] == \"\" and has_signal(&\"verb_failed\"):\n\temit_signal(&\"verb_failed\", str({wait_name}), \"timed out after \" + str({seconds}) + \"s\")", "Time", "wait [b]{wait_name}[/b] for ANY of [b]{signals}[/b]", "Pauses this event until the first of several signals fires, then carries on - a race, or a sudden-death timer. Read which one won with First To Finish, naming this wait: it answers \"Node.signal\", so racing $Player.died against $Boss.died still tells you which one it was. Every signal is connected one-shot up front, so the winner is whichever really fired first, and the losers are disconnected when the race ends.").param("wait_name", "\"race\"", "Named", "A name for this wait, so First To Finish and the outcome conditions can say which one they mean.", "expression").param("signals", "[]", "Signals", "The signals to race, as a list: [$Player.died, $Boss.died].", "expression").param("seconds", "0.0", "Give Up After", "Seconds before giving up. 0 waits forever.", "expression"))
	descriptors.append(F.cond("WaitSucceeded", "Wait Succeeded", "int(get_meta(&\"__ef_wait_\" + str({wait_name}).to_utf8_buffer().hex_encode(), 0)) == 1", "Run Context", "wait [b]{wait_name}[/b] succeeded", "True when the named wait ended because what it was waiting for happened. A wait that has never run is neither succeeded nor timed out, so nothing fires before the wait does.").param("wait_name", "\"loading\"", "Named", "The name the wait row used.", "expression"))
	descriptors.append(F.cond("WaitTimedOut", "Wait Timed Out", "int(get_meta(&\"__ef_wait_\" + str({wait_name}).to_utf8_buffer().hex_encode(), 0)) == 2", "Run Context", "wait [b]{wait_name}[/b] timed out", "True when the named wait gave up instead of finishing - the recovery branch for a load that never reported in. The same timeout also reports on verb_failed, so another event can handle it as On Failure Of.").param("wait_name", "\"loading\"", "Named", "The name the wait row used.", "expression"))
	descriptors.append(F.expr("FirstToFinish", "First To Finish", "str(get_meta(&\"__ef_first_\" + str({wait_name}).to_utf8_buffer().hex_encode(), \"\"))", "Run Context", "first to finish ( [b]{wait_name}[/b] )", "Which signal a Wait For Any Of was watching finished first, written as \"Node.signal\" (the node's name, a dot, the signal's name), or empty text when it timed out. The node is part of the answer on purpose: a race between $Player.died and $Boss.died is two signals with the same name, and only the owner tells them apart. Compare it in a condition cell to branch on the winner.").param("wait_name", "\"race\"", "Named", "The name the Wait For Any Of row used.", "expression"))
	# ── Retry: the loop that stops the moment it works ────────────────────────────────
	# Repeat With Delay always burns its whole count and has no idea whether the thing worked. This
	# is the loop developers actually write: iteration is a LOOP ROW (a looping condition, so the
	# canvas nesting is the emitted nesting), success is an ordinary nested condition whose action is
	# Stop Retrying, and giving up is the sibling condition Retries Exhausted.
	#
	# The shared record is a THREE-state number on the node, not a flag, because a flag cannot tell
	# "this retry has never run" apart from "it ran and nobody stopped it" - and a give-up branch that
	# fires before a single attempt has happened is worse than having none. 0 or missing = never ran,
	# 1 = the loop started, 2 = a Stop Retrying ended it. Retries Exhausted answers 1 and CONSUMES the
	# record, so the next run of the loop starts clean with nothing to reset beforehand.
	#
	# The name is hex-encoded into the metadata key, the same guard every name-keyed family in this
	# vocabulary uses: Object.set_meta REFUSES a key that is not a valid identifier, so a retry called
	# "save game" would silently store nothing and every read would answer the default forever.
	descriptors.append(F.cond("RetryUpTo", "Retry Up To N Times", "__retry_begin_{uid}(str({retry_name}), int({times}))", "Loops", "retry [b]{retry_name}[/b] up to [b]{times}[/b] times", "Runs this event's actions over and over, up to a number of attempts, so a nested Stop Retrying can end it the moment the thing works. With no waiting inside it stays instant, which makes it the procedural-placement loop as much as the disk retry. Read the try number with Retry Attempt Number.").param("retry_name", "\"save\"", "Named", "A name for this retry, matching its Stop Retrying and Retries Exhausted rows.", "expression").param("times", "5", "Times", "Most attempts before giving up.", "expression").looping("attempt").stateful("func __retry_begin_{uid}(key: String, times: int) -> Array:\n\tset_meta(StringName(\"__ef_retry_\" + key.to_utf8_buffer().hex_encode()), 1)\n\treturn range(maxi(times, 1))"))
	descriptors.append(F.expr("RetryAttemptNumber", "Retry Attempt Number", "({loop_var} + 1)", "Loops", "retry attempt number", "Which try this is, counting from 1 - the number you put in the log line or the HUD. Only readable inside a Retry Up To N Times loop, and it reads that loop's own variable, so change the cell if you renamed it.").param("loop_var", "attempt", "Loop Variable", "The retry loop's own variable. Leave it as attempt unless you renamed the loop variable on the Retry Up To N Times row.", "expression"))
	descriptors.append(F.act("StopRetrying", "Stop Retrying", "set_meta(&\"__ef_retry_\" + str({retry_name}).to_utf8_buffer().hex_encode(), 2)\nbreak", "Loops", "stop retrying [b]{retry_name}[/b]", "Ends the retry loop right now because the attempt worked, and records that it worked so Retries Exhausted below stays false. Put it under the condition that means success.").param("retry_name", "\"save\"", "Name", "The name the Retry Up To N Times row uses.", "expression"))
	descriptors.append(F.cond("RetriesExhausted", "Retries Exhausted", "__exhausted_{uid}(str({retry_name}))", "Loops", "retries for [b]{retry_name}[/b] exhausted", "True when the retry loop above ran out of tries without a Stop Retrying - the give-up branch. Put it in a sibling row directly beneath the retry loop, using the same name; a retry that has never run is not exhausted, so nothing fires before the loop does. Reading it clears the record, so the next run starts clean. When the retry WAITS between tries (Wait Before Next Try) the loop is still running while the rows beneath it are reached, so report that give-up with Report Failure on the last attempt and handle it in an On Failure Of event instead.").param("retry_name", "\"save\"", "Name", "The name the Retry Up To N Times row uses.", "expression").stateful("func __exhausted_{uid}(key: String) -> bool:\n\tvar meta_key: StringName = StringName(\"__ef_retry_\" + key.to_utf8_buffer().hex_encode())\n\tvar state: int = int(get_meta(meta_key, 0))\n\tset_meta(meta_key, 0)\n\treturn state == 1"))
	descriptors.append(F.act("WaitBeforeNextTry", "Wait Before Next Try", "await get_tree().create_timer(maxf({delay}, 0.0) * pow(maxf({growth}, 1.0), maxf(float({attempt}) - 1.0, 0.0))).timeout", "Loops", "wait [b]{delay}[/b]s before try [b]{attempt}[/b] (growing x[b]{growth}[/b])", "Pauses before the next attempt, waiting longer each time when you set a growth above 1 - the polite way to retry a disk or a slow source. It suspends this event like Wait does, so pair the retry with Once At A Time when the trigger can fire again mid-retry.").param("delay", "0.5", "Seconds", "Wait after the first failed try.", "expression").param("growth", "2.0", "Growing By", "1 = the same wait every time, 2 = doubling backoff.", "expression").param("attempt", "1", "On Try", "Which try this is - put Retry Attempt Number here.", "expression"))
	# Input expressions
	descriptors.append(F.expr("GetActionStrength", "Action Strength", "Input.get_action_strength(&{action})", "Input", "strength of {action}", "Gives how hard an input action is pressed, from 0 to 1.").param_built(F.make_param("action", "String", F.default_input_action(), "Action", "Input action (analog strength 0..1).", "input_action", F.input_action_options())))
	descriptors.append(F.expr("GetInputAxis", "Input Axis", "Input.get_axis(&{negative}, &{positive})", "Input", "axis {negative}/{positive}", "Gives a -1 to 1 value from two opposing input actions, like left and right.").param_choice("negative", "\"ui_left\"", "Negative", "Action for the negative direction.", F.input_action_options(), "input_action").param_choice("positive", "\"ui_right\"", "Positive", "Action for the positive direction.", F.input_action_options(), "input_action"))
	# The consuming ACTION for the axis above: read input into a typed float local in one row, so
	# "read input, then move" is two ACE rows instead of a RawCode block (closes the input gap).
	descriptors.append(F.act("SetLocalFromAxis", "Read Input Axis Into", "var {name}: float = Input.get_axis(&{negative}, &{positive})", "Input", "read axis {negative}/{positive} into {name}", "Reads a left/right input axis into a local variable for this event.").param("name", "direction", "Name", "Local variable name (scoped to this event body).").param_choice("negative", "\"ui_left\"", "Negative", "Action for the negative direction.", F.input_action_options(), "input_action").param_choice("positive", "\"ui_right\"", "Positive", "Action for the positive direction.", F.input_action_options(), "input_action"))
	# ── Native-node providers (coverage Lane 1: wrap NATIVE Godot features; the
	# engine maintains the implementation, we only maintain vocabulary). The familiar
	# names are the display names; see the migration guide for the lane mapping.
	# Tween (Tween behavior -> Godot's built-in create_tween)
	descriptors.append(F.act("TweenProperty", "Tween Property", "create_tween().tween_property({target}, {property}, {value}, {duration}).set_trans({transition}).set_ease({ease})", "Tween", "Tween {property} to {value} in {duration} seconds", "Smoothly animates a node's property to a target value over time with an easing curve.").param("target", "self", "Target", "Node whose property tweens.", "expression").param("property", "\"position\"", "Property", "Property path to animate.").param("value", "Vector2(100, 0)", "To", "Final value expression.", "expression").param("duration", "0.5", "Duration", "Seconds.", "expression").param_choice("transition", "Tween.TRANS_SINE", "Transition", "Curve shape.", ["Tween.TRANS_LINEAR", "Tween.TRANS_SINE", "Tween.TRANS_QUAD", "Tween.TRANS_CUBIC", "Tween.TRANS_QUART", "Tween.TRANS_ELASTIC", "Tween.TRANS_BACK", "Tween.TRANS_BOUNCE", "Tween.TRANS_EXPO", "Tween.TRANS_CIRC"]).param_choice("ease", "Tween.EASE_IN_OUT", "Ease", "In / out / in-out.", ["Tween.EASE_IN", "Tween.EASE_OUT", "Tween.EASE_IN_OUT"]))
	descriptors.append(F.act("TweenCallback", "Tween Callback", "create_tween().tween_callback({callable}).set_delay({delay})", "Tween", "Call {callable} after {delay}s", "Waits a delay, then calls a method or function once (handy for timed events).").param("callable", "queue_free", "Callable", "Method/Callable to invoke after the delay (e.g. a node method or a lambda).", "expression").param("delay", "1.0", "Delay", "Seconds before the call fires.", "expression"))
	# Scene flow (System: layouts -> Godot scenes)
	# The scene-flow rows carry the sheet's own action names - layout, restart, quit - and an
	# opened .gd file reads these very lines back in the same words, so the two can never drift.
	descriptors.append(F.act("ChangeScene", "Go To Layout", "get_tree().change_scene_to_file({path})", "Scene", "Go to layout {path}", "Switches the game to a different layout (a scene file), replacing the current one.").param("path", "\"res://main.tscn\"", "Layout", "Scene file to switch to.", "expression"))
	descriptors.append(F.act("ReloadScene", "Restart Layout", "get_tree().reload_current_scene()", "Scene", "Restart layout", "Restarts the current layout from the beginning, useful for retrying a level."))
	descriptors.append(F.act("QuitGame", "Quit Game", "get_tree().quit()", "Scene", "Quit game", "Closes the game and exits to desktop."))
	# The two halves of the pause switch, each as its own row: an author reaches for "pause", not for
	# "set paused to true", and the reading of the same line says exactly this.
	descriptors.append(F.act("PauseGame", "Pause The Game", "get_tree().paused = true", "Scene", "Pause the game", "Freezes the whole game. Nodes set to Always (or a pause menu's Process Mode) keep running, which is how the menu on top stays alive."))
	descriptors.append(F.act("UnpauseGame", "Unpause", "get_tree().paused = false", "Scene", "Unpause", "Lets the game run again after Pause The Game."))
	# Pairs with the On Close Requested trigger: by default the window's X quits instantly, so set this in
	# On Ready to "Intercept" and the close waits for your On Close Requested handler (save / confirm), which
	# then calls Quit Game explicitly. The friendly dropdown shows "Intercept"/"Allow" but inserts false/true.
	descriptors.append(F.act("HandleQuitRequest", "Handle Quit Myself", "get_tree().set_auto_accept_quit({mode})", "Scene", "Handle quit myself: {mode}", "Stops the window's close button from quitting instantly, so On Close Requested can run first (save progress, pop a confirm dialog) and you quit explicitly with Quit Game. Choose \"Allow\" to restore Godot's default immediate quit.").param_choice("mode", "false", "On close", "Whether the app quits instantly or waits for you to handle it.", [{"key": "false", "label": "Intercept (handle it myself)"}, {"key": "true", "label": "Allow (quit immediately)"}]))
	descriptors.append(F.act("SetPaused", "Set Game Paused", "get_tree().paused = {paused}", "Scene", "Set paused to {paused}", "Pauses or resumes the whole game by toggling the scene tree's pause state.").param_choice("paused", "true", "Paused", "Pause state.", ["true", "false"]))
	descriptors.append(F.act("SpawnScene", "Spawn Scene Instance", "add_child(load({path}).instantiate())", "Scene", "Spawn {path}", "Loads a scene file and adds an instance of it as a child (spawning objects).").param("path", "\"res://enemy.tscn\"", "Scene", "Scene file to instance as a child.", "expression"))
	descriptors.append(F.cond("IsPaused", "Is Game Paused", "get_tree().paused", "Scene", "Game is paused", "True when the game is currently paused."))
	# A layout ON TOP of the game rather than instead of it: the pause menu, the inventory, the
	# dialogue box. Three rows, and each one is deliberately NOT a re-saying of a row that already
	# ships:
	#   Go To Layout REPLACES what is running; these three leave it running underneath.
	#   Spawn Scene Instance adds a copy under THIS node with a bare add_child, which is the reading
	#     it has always had and keeps - a spawned enemy belongs to the layout it was spawned in and
	#     dies with it. A menu must not, so these rows add under the tree root instead.
	#   The scene-flow pack parents its fade overlay to that same root for that same survival reason:
	#     anything that has to outlive the scene beneath it cannot be a child of the scene beneath it.
	#   The named-scenes pack owns the idea of addressing a layout by a short name instead of a path;
	#     nothing here keeps a second registry - the name below is the node's own name under the root,
	#     which is what get_node_or_null then answers with.
	#   Pause The Game is the row these pair with, and the params dialog says so at the moment of
	#     need: a layout added over a paused game only runs if its own root node's Process Mode says
	#     it may. Nothing here writes that mode for the author.
	#   THE NAME IS THE WHOLE PROMISE, which is why the add asks first. `add_child` will not take a
	#     name a sibling already has: it renames the newcomer to `@Node@2`, and the two rows below go
	#     on finding the FIRST one - so a second add under one name used to leave a copy nothing could
	#     ever find or remove, under the tree root, for the life of the process. The add therefore
	#     looks the name up and builds nothing when it is already taken. At most one layout is on top
	#     under one name, which is exactly what the other two rows promise to find.
	#   AND THE REMOVAL TAKES IT OFF THE TREE AT ONCE. `queue_free` frees at the end of the frame, so
	#     a node only queued is still a child, still found by name, and still in the way of the next
	#     add. Taking it out of the tree first is what makes the familiar close-then-open pair work in
	#     one frame; the freeing still happens the safe deferred way.
	descriptors.append(F.act("AddLayoutOnTop", "Add Layout On Top", "var __layout_{uid}: Node = get_tree().root.get_node_or_null({layout_name})\nif __layout_{uid} == null:\n\t__layout_{uid} = (load({path}) as PackedScene).instantiate()\n\t__layout_{uid}.name = {layout_name}\n\tget_tree().root.add_child(__layout_{uid})", "Scene", "Add layout {path} on top as {layout_name}", "Puts a layout over the running game instead of replacing it - a pause menu, an inventory, a dialogue box. The copy is added under the tree root, so it outlives a change of layout underneath it, and it takes the name you give so the two rows below can find it again. A name that is already on top is left alone and nothing is loaded, because two layouts under one name would mean one of them could never be found or removed again.").param("path", "\"res://pause_menu.tscn\"", "Layout", "Layout file to put on top. Its root node keeps its own Process Mode, which is what decides whether it runs while the game is paused.", "scene_path").param("layout_name", "\"PauseMenu\"", "Named", "The name the copy is given under the tree root. Remove Layout On Top and Layout Is On Top find it by this name, so keep all three saying the same one.", "expression"))
	descriptors.append(F.act("RemoveLayoutOnTop", "Remove Layout On Top", "var __layout_{uid}: Node = get_tree().root.get_node_or_null({layout_name})\nif __layout_{uid} != null:\n\tget_tree().root.remove_child(__layout_{uid})\n\t__layout_{uid}.queue_free()", "Scene", "Remove layout {layout_name} from on top", "Takes a layout added by Add Layout On Top back off again. It comes off the tree straight away and is freed the deferred way, so Layout Is On Top answers false in the same frame and an add right after it puts the new one up under the same name. A name nothing is under quietly does nothing, so a close row is safe to run twice.").param("layout_name", "\"PauseMenu\"", "Named", "The name Add Layout On Top gave the copy. A name nothing is under removes nothing.", "expression"))
	descriptors.append(F.cond("LayoutIsOnTop", "Layout Is On Top", "get_tree().root.get_node_or_null({layout_name}) != null", "Scene", "layout {layout_name} is on top", "True while a layout added by Add Layout On Top is still there. Use it to stop a menu opening twice, or to answer the same key differently while one is open.").param("layout_name", "\"PauseMenu\"", "Named", "The name Add Layout On Top gave the copy.", "expression"))
	# Audio (AudioStreamPlayer / 2D / 3D share these members).
	#
	# THESE FOUR ARE THE VOCABULARY'S FIRST FORWARDING ADDRESSES, and they are addresses rather than
	# renames because a shipped id is a promise: every one of them keeps its id, its template and its
	# place in the picker for ever, and a sheet written on it compiles to exactly the line it always
	# did. They landed on the general shelf a day before the Audio shelf existed; the Audio module then
	# authored the same four questions on the page a reader looks for them on, against the same node
	# type, with the same parameters and the same emitted call. The two spellings have sat side by side
	# ever since, which is one question with two answers in the picker.
	#
	# The map says the whole of what differs: Play Sound calls its one parameter `from_position` where
	# Play calls it `from`, and the other three name their parameters identically, so nothing is renamed
	# and nothing needs a value invented for it. Playback Position is deliberately NOT addressed - an
	# expression is not a row, so nothing could ever act on the address.
	descriptors.append(F.act("PlayAudio", "Play Sound", "play({from_position})", "General Actions", "Play sound", "Plays the sound on an audio player, optionally starting from a given second.", "AudioStreamPlayer").param("from_position", "0.0", "From", "Start position in seconds.", "expression").succeeded_by("Core::AudioPlay", {"from_position": "from"}))
	descriptors.append(F.act("StopAudio", "Stop Sound", "stop()", "General Actions", "Stop sound", "Stops the sound currently playing on an audio player.", "AudioStreamPlayer").succeeded_by("Core::AudioStop"))
	descriptors.append(F.act("SetVolumeDb", "Set Volume (dB)", "volume_db = {db}", "General Actions", "Set volume to {db} dB", "Sets an audio player's loudness in decibels (0 is full, -80 is silent).", "AudioStreamPlayer").param("db", "0.0", "Decibels", "0 = full volume, -80 = silent.", "expression").succeeded_by("Core::AudioSetVolume"))
	descriptors.append(F.cond("IsAudioPlaying", "Is Playing", "playing", "General Conditions", "Sound is playing", "True while the audio player is currently playing a sound.", "AudioStreamPlayer").succeeded_by("Core::AudioIsPlaying"))
	descriptors.append(F.expr("GetPlaybackPosition", "Playback Position", "get_playback_position()", "General Expressions", "playback position", "Returns how many seconds into the sound the audio player currently is.", "AudioStreamPlayer"))
	# AnimatedSprite2D (Sprite animations)
	descriptors.append(F.act("PlaySpriteAnimation", "Play Sprite Animation", "play(&{anim})", "General Actions", "Play animation {anim}", "Plays a named animation on an animated sprite (e.g. run or jump).", "AnimatedSprite2D").param("anim", "\"default\"", "Animation", "Animation name."))
	descriptors.append(F.act("StopSpriteAnimation", "Stop Sprite Animation", "stop()", "General Actions", "Stop animation", "Stops the animated sprite's current animation on the spot.", "AnimatedSprite2D"))
	descriptors.append(F.act("SetSpriteFrame", "Set Animation Frame", "frame = {frame}", "General Actions", "Set animation frame to {frame}", "Jumps the animated sprite to a specific frame number.", "AnimatedSprite2D").param("frame", "0", "Frame", "Frame index.", "expression"))
	descriptors.append(F.act("SetFlipH", "Set Mirrored", "flip_h = {flipped}", "General Actions", "Set mirrored {flipped}", "Mirrors the sprite horizontally, great for facing left or right.", "AnimatedSprite2D").param_choice("flipped", "true", "Mirrored", "Horizontal flip.", ["true", "false"]))
	descriptors.append(F.cond("IsSpriteAnimationPlaying", "Is Animation Playing", "is_playing()", "General Conditions", "Animation is playing", "True while the animated sprite is currently playing an animation.", "AnimatedSprite2D"))
	descriptors.append(F.expr("GetSpriteAnimation", "Current Animation", "animation", "General Expressions", "current animation", "Returns the name of the animation the sprite is currently using.", "AnimatedSprite2D"))
	# Camera2D - the sheet's camera page. The display names are the words the reading uses for the
	# same lines, so a camera row says the same thing whether it was picked here or typed by hand.
	descriptors.append(F.act("MakeCameraCurrent", "Make Current", "make_current()", "Camera", "Make current", "Makes this camera the active one the player views the game through.", "Camera2D"))
	descriptors.append(F.act("SetCameraZoom", "Set Zoom", "zoom = {zoom}", "Camera", "Set zoom to {zoom}", "Sets how zoomed in or out the camera is.", "Camera2D").param("zoom", "Vector2(1, 1)", "Zoom", "Zoom factor.", "expression"))
	descriptors.append(F.act("SetCameraOffset", "Set Offset", "offset = {offset}", "Camera", "Set offset to {offset}", "Shifts the camera view away from the position it follows.", "Camera2D").param("offset", "Vector2(0, 0)", "Offset", "Offset from the followed position.", "expression"))
	descriptors.append(F.act("SetCameraLimits", "Set Scroll Limits", "limit_left = {left}\nlimit_top = {top}\nlimit_right = {right}\nlimit_bottom = {bottom}", "Camera", "Set scroll limits {left} to {right}", "Sets the boundaries the camera won't scroll past, keeping it inside the level.", "Camera2D").param("left", "0", "Left", "Left bound (px).", "expression").param("top", "0", "Top", "Top bound (px).", "expression").param("right", "1920", "Right", "Right bound (px).", "expression").param("bottom", "1080", "Bottom", "Bottom bound (px).", "expression"))
	descriptors.append(F.act("SetCameraSmoothing", "Set Smoothing", "position_smoothing_enabled = {enabled}", "Camera", "Set smoothing {enabled}", "Turns the camera's smooth catch-up on or off, so it eases toward what it follows instead of snapping.", "Camera2D").param_choice("enabled", "true", "Smoothing", "true / false.", ["true", "false"]))
	descriptors.append(F.act("CameraScrollToward", "Scroll Toward", "global_position = global_position.lerp({toward}.global_position, {rate} * get_process_delta_time())", "Camera", "Scroll toward {toward} at {rate}", "Eases the camera toward another node, closing the gap at the given rate every second.", "Camera2D").param("toward", "self", "Toward", "The node to scroll toward.", "expression").param("rate", "5", "Rate", "How fast to close the gap, per second.", "expression"))
	# Label / text (Text object)
	descriptors.append(F.act("SetLabelText", "Set Text", "text = str({value})", "General Actions", "Set text to {value}", "Sets the text shown on a label, like a score or message.", "Label").param("value", "\"Hello\"", "Text", "Value to display (str()-converted).", "expression"))
	descriptors.append(F.act("AppendLabelText", "Append Text", "text += str({value})", "General Actions", "Append {value}", "Adds more text onto the end of a label's existing text.", "Label").param("value", "\"!\"", "Text", "Value to append.", "expression"))
	descriptors.append(F.expr("GetLabelText", "Get Text", "text", "General Expressions", "text", "Returns the text currently displayed on the label.", "Label"))
	# NavigationAgent2D (Pathfinding behavior)
	descriptors.append(F.act("SetNavTarget", "Find Path To", "target_position = {position}", "General Actions", "Find path to {position}", "Tells a navigation agent to pathfind toward a world position, for AI movement.", "NavigationAgent2D").param("position", "Vector2(0, 0)", "Target", "World position to path toward.", "expression"))
	descriptors.append(F.cond("IsNavFinished", "Has Arrived", "is_navigation_finished()", "General Conditions", "Has arrived", "True once the navigation agent has reached its target destination.", "NavigationAgent2D"))
	descriptors.append(F.expr("GetNextPathPosition", "Next Path Position", "get_next_path_position()", "General Expressions", "next path position", "Returns the next point along the path the agent should move toward.", "NavigationAgent2D"))
	# The step a path walk is made of, as ONE row. Its template is exactly the line the reading
	# recognises: the direction from where the body is to the next waypoint, at the given speed.
	descriptors.append(F.act("MoveAlongPath", "Move Along Path", "velocity = global_position.direction_to({next}) * {speed}", "Movement", "Move along path at {speed}", "Steers the body toward the next point on the path its navigation agent worked out. Follow it with Move so the body actually travels.", "CharacterBody2D").param("next", "Vector2(0, 0)", "Next waypoint", "The agent's next path position - read it into a local first with the Next Path Position expression.", "expression").param("speed", "120.0", "Speed", "How fast to travel along the path, in pixels per second.", "expression"))
	descriptors.append(F.expr("GetNavDistance", "Distance To Target", "distance_to_target()", "General Expressions", "distance to target", "Returns how far the agent still is from its navigation target.", "NavigationAgent2D"))
	# Loading a layout in the background. Three rows cover the whole idiom: the request, the
	# question, and the switch once it is there - so nobody has to type the status enum again. The
	# templates ARE the lines the reading recognises, which is what makes a written and a picked
	# loading screen the same bytes.
	descriptors.append(F.act("LoadLayoutInBackground", "Load Layout In The Background", "ResourceLoader.load_threaded_request({path})", "Scene", "Load layout {path} in the background", "Starts loading a layout on another thread while the game keeps running, so a loading screen can show progress instead of freezing.").param("path", "\"res://main.tscn\"", "Layout", "Scene file to start loading.", "expression"))
	descriptors.append(F.cond("LayoutFinishedLoading", "Layout Has Finished Loading", "ResourceLoader.load_threaded_get_status({path}) == ResourceLoader.THREAD_LOAD_LOADED", "Scene", "layout {path} has finished loading", "True once a layout started with Load Layout In The Background is ready to switch to.").param("path", "\"res://main.tscn\"", "Layout", "The layout being loaded in the background.", "expression"))
	descriptors.append(F.act("GoToLoadedLayout", "Go To Loaded Layout", "get_tree().change_scene_to_packed(ResourceLoader.load_threaded_get({path}))", "Scene", "Go to layout {path}", "Switches to a layout that finished loading in the background, with no second load and no pause.").param("path", "\"res://main.tscn\"", "Layout", "The layout that finished loading.", "expression"))
	# Godot reports progress through an array it FILLS, which no bare expression can hand back. The
	# one-line lambda is what keeps this an expression a row can carry: the array goes in, the status
	# call fills it (its enum is never negative, so the guard only sequences the two), and the share
	# comes out. Every byte of it is plain GDScript with no plugin behind it.
	descriptors.append(F.expr("LoadingProgress", "Loading Progress", "(func(__ef_p: Array) -> float: return float(__ef_p[0]) if ResourceLoader.load_threaded_get_status({path}, __ef_p) >= 0 and __ef_p.size() > 0 else 0.0).call([])", "Scene", "LoadingProgress", "How far a background load has got, from 0 to 1 - multiply by 100 for a percentage bar.").param("path", "\"res://main.tscn\"", "Layout", "The layout being loaded in the background.", "expression"))
	# Visibility / tint (CanvasItem)
	descriptors.append(F.act("ShowNode", "Show", "show()", "General Actions", "Show", "Makes a node visible on screen.", "CanvasItem"))
	descriptors.append(F.act("HideNode", "Hide", "hide()", "General Actions", "Hide", "Hides a node so it no longer shows on screen.", "CanvasItem"))
	descriptors.append(F.act("SetModulate", "Set Color Tint", "modulate = {color}", "General Actions", "Set tint to {color}", "Tints a node and its children with a color, also useful for fading via alpha.", "CanvasItem").param("color", "Color(1, 1, 1, 1)", "Color", "Tint (RGBA).", "color"))
	descriptors.append(F.act("SetSelfModulate", "Set Self Tint", "self_modulate = {color}", "General Actions", "Set self tint to {color}", "Tints just this node with a color without affecting its children.", "CanvasItem").param("color", "Color(1, 1, 1, 1)", "Color", "Tint for this node only (not children).", "color"))
	descriptors.append(F.cond("IsVisible", "Is Visible", "visible", "General Conditions", "Is visible", "True when the node is currently visible on screen.", "CanvasItem"))
	# Math & random (System expressions: random, choose, clamp, lerp, distance, angle)
	descriptors.append(F.expr("RandomRange", "Random", "randf_range({from}, {to})", "Math & Random", "random({from}, {to})", "Returns a random decimal number between the two bounds you give.").param("from", "0.0", "From", "Lower bound.", "expression").param("to", "1.0", "To", "Upper bound.", "expression"))
	descriptors.append(F.expr("RandomInt", "Random Integer", "randi_range({from}, {to})", "Math & Random", "random int({from}, {to})", "Returns a random whole number between the two bounds, both included.").param("from", "0", "From", "Lower bound (inclusive).", "expression").param("to", "9", "To", "Upper bound (inclusive).", "expression"))
	descriptors.append(F.expr("Choose", "Choose", "[{values}].pick_random()", "Math & Random", "choose({values})", "Randomly picks one value from a comma-separated list you provide.").param("values", "1, 2, 3", "Values", "Comma-separated values to pick from.", "expression"))
	descriptors.append(F.expr("ClampValue", "Clamp", "clampf({value}, {min}, {max})", "Math & Random", "clamp({value}, {min}, {max})", "Keeps a value within a min and max, clipping anything outside the range.").param("value", "0.0", "Value", "Value to clamp.", "expression").param("min", "0.0", "Min", "Lower bound.", "expression").param("max", "1.0", "Max", "Upper bound.", "expression"))
	descriptors.append(F.expr("LerpValue", "Lerp", "lerpf({from}, {to}, {weight})", "Math & Random", "lerp({from}, {to}, {weight})", "Blends between two values by a 0-to-1 weight, for smooth interpolation.").param("from", "0.0", "From", "Start value.", "expression").param("to", "1.0", "To", "End value.", "expression").param("weight", "0.5", "Weight", "0..1 blend.", "expression"))
	descriptors.append(F.expr("DistanceTo", "Distance To", "position.distance_to({to})", "Math & Random", "distance to {to}", "Returns the distance in pixels from this node to a target position.", "Node2D").param("to", "Vector2(0, 0)", "To", "Target position.", "expression"))
	descriptors.append(F.expr("AngleToPoint", "Angle Toward", "position.angle_to_point({to})", "Math & Random", "angle toward {to}", "Returns the angle from this node toward a target position, handy for aiming.", "Node2D").param("to", "Vector2(0, 0)", "To", "Target position.", "expression"))
	# More math idioms (movement / animation / AI reach for these constantly).
	descriptors.append(F.expr("Snapped", "Snap To Step", "snappedf({value}, {step})", "Math & Random", "snap {value} to {step}", "Rounds a value to the nearest step, useful for snapping to a grid.").param("value", "0.0", "Value", "Value to snap.", "expression").param("step", "1.0", "Step", "Snap increment (e.g. grid size).", "expression"))
	descriptors.append(F.expr("InverseLerp", "Inverse Lerp", "inverse_lerp({from}, {to}, {value})", "Math & Random", "inverse lerp {value}", "Returns where a value sits within a range as a 0-to-1 fraction.").param("from", "0.0", "From", "Range start.", "expression").param("to", "1.0", "To", "Range end.", "expression").param("value", "0.5", "Value", "Value in the range.", "expression"))
	descriptors.append(F.expr("Smoothstep", "Smoothstep", "smoothstep({from}, {to}, {value})", "Math & Random", "smoothstep({from}, {to}, {value})", "Eases a value between two edges with a smooth S-curve instead of a straight line.").param("from", "0.0", "From", "Edge 0.", "expression").param("to", "1.0", "To", "Edge 1.", "expression").param("value", "0.5", "Value", "Value to ease.", "expression"))
	descriptors.append(F.expr("SmoothLerp", "Smooth Lerp", "lerpf({from}, {to}, smoothstep(0.0, 1.0, {weight}))", "Math & Random", "smooth lerp {from} -> {to}", "Blends between two values like Lerp, but eases the 0-to-1 weight with a smooth S-curve first, so the motion starts and ends gently instead of at a constant speed.").param("from", "0.0", "From", "Start value.", "expression").param("to", "1.0", "To", "End value.", "expression").param("weight", "0.5", "Weight", "0..1 progress (eased with an S-curve before blending).", "expression"))
	descriptors.append(F.expr("Atan2", "Angle Of (atan2)", "atan2({y}, {x})", "Math & Random", "atan2({y}, {x})", "Returns the angle (radians) of the direction (x, y), correct in all four quadrants - the standard way to turn a velocity or offset into a heading.").param("y", "0.0", "Y", "Vertical component.", "expression").param("x", "0.0", "X", "Horizontal component.", "expression"))
	descriptors.append(F.expr("PingPong", "Ping-Pong", "pingpong({value}, {length})", "Math & Random", "pingpong({value}, {length})", "Bounces a value back and forth between 0 and a length, great for looping motion.").param("value", "0.0", "Value", "Input value (often a timer).", "expression").param("length", "1.0", "Length", "Bounce length.", "expression"))
	descriptors.append(F.expr("AngleDifference", "Angle Difference", "angle_difference({from}, {to})", "Math & Random", "angle diff {from} -> {to}", "Returns the shortest signed turn from one angle to another, in radians.").param("from", "0.0", "From", "From angle (radians).", "expression").param("to", "0.0", "To", "To angle (radians).", "expression"))
	descriptors.append(F.expr("RotateTowardAngle", "Rotate Toward (angle)", "rotate_toward({from}, {to}, {delta})", "Math & Random", "rotate {from} toward {to}", "Steps an angle toward a target by a limited amount, for smooth turning.").param("from", "0.0", "From", "Current angle (radians).", "expression").param("to", "0.0", "To", "Target angle (radians).", "expression").param("delta", "0.1", "Delta", "Max step (radians).", "expression"))
	descriptors.append(F.expr("LerpAngle", "Lerp Angle", "lerp_angle({from}, {to}, {weight})", "Math & Random", "lerp angle {from} -> {to}", "Blends between two angles by a 0..1 weight, taking the shortest path.").param("from", "0.0", "From", "From angle (radians).", "expression").param("to", "0.0", "To", "To angle (radians).", "expression").param("weight", "0.5", "Weight", "0..1 blend.", "expression"))
	descriptors.append(F.expr("DegToRad", "Degrees To Radians", "deg_to_rad({degrees})", "Math & Random", "deg2rad({degrees})", "Converts an angle from degrees into radians, which Godot uses internally.").param("degrees", "90.0", "Degrees", "Angle in degrees.", "expression"))
	descriptors.append(F.expr("RadToDeg", "Radians To Degrees", "rad_to_deg({radians})", "Math & Random", "rad2deg({radians})", "Converts an angle from radians back into easy-to-read degrees.").param("radians", "0.0", "Radians", "Angle in radians.", "expression"))
	descriptors.append(F.expr("PosMod", "Positive Modulo", "posmod({a}, {b})", "Math & Random", "posmod({a}, {b})", "Returns a modulo result that stays positive, handy for wrapping indexes.").param("a", "0", "A", "Dividend (int).", "expression").param("b", "1", "B", "Divisor (int).", "expression"))
	descriptors.append(F.cond("IsEqualApprox", "Is Equal (approx)", "is_equal_approx({a}, {b})", "Math & Random", "{a} ≈ {b}", "True when two numbers are nearly equal, avoiding tiny floating-point errors.").param("a", "0.0", "A", "First value.", "expression").param("b", "0.0", "B", "Second value.", "expression"))
	descriptors.append(F.cond("IsZeroApprox", "Is Zero (approx)", "is_zero_approx({value})", "Math & Random", "{value} ≈ 0", "True when a value is essentially zero, ignoring tiny rounding differences.").param("value", "0.0", "Value", "Value to test.", "expression"))
	descriptors.append(F.act("SeedRandom", "Seed Random", "seed({value})", "Math & Random", "seed RNG with {value}", "Sets the random seed so the same number gives a repeatable random sequence.").param("value", "0", "Seed", "Integer seed (same seed = same sequence).", "expression"))
	descriptors.append(F.act("RandomizeSeed", "Randomize Seed", "randomize()", "Math & Random", "randomize seed", "Reseeds randomness from the clock so each playthrough differs."))

	# Color math - hit flashes, fades, and tints without dropping to GDScript. The colour params
	# are full expressions (a literal, `modulate`, or another colour ACE), so they compose.
	descriptors.append(F.expr("ColorLighten", "Lighten Color", "({color}).lightened({amount})", "Color", "lighten {color} by {amount}", "Returns the colour shifted toward white by the given amount.").param("color", "Color(1, 1, 1, 1)", "Color", "Base colour.", "color").param("amount", "0.2", "Amount", "0..1 toward white.", "expression"))
	descriptors.append(F.expr("ColorDarken", "Darken Color", "({color}).darkened({amount})", "Color", "darken {color} by {amount}", "Returns the colour shifted toward black by the given amount.").param("color", "Color(1, 1, 1, 1)", "Color", "Base colour.", "color").param("amount", "0.2", "Amount", "0..1 toward black.", "expression"))
	descriptors.append(F.expr("ColorLerp", "Lerp Color", "({from}).lerp({to}, {weight})", "Color", "lerp {from} -> {to}", "Blends two colours by a 0..1 weight for smooth colour fades.").param("from", "Color(1, 1, 1, 1)", "From", "Start colour.", "color").param("to", "Color(1, 0, 0, 1)", "To", "End colour.", "color").param("weight", "0.5", "Weight", "0..1 blend.", "expression"))
	descriptors.append(F.expr("ColorWithAlpha", "Color With Alpha", "Color({color}, {alpha})", "Color", "{color} @ alpha {alpha}", "Returns the colour with a new transparency, for fade-in or fade-out effects.").param("color", "Color(1, 1, 1, 1)", "Color", "Base colour.", "color").param("alpha", "0.5", "Alpha", "New alpha 0..1.", "expression"))
	descriptors.append(F.expr("ColorFromHSV", "Color From HSV", "Color.from_hsv({h}, {s}, {v}, {a})", "Color", "hsv({h}, {s}, {v})", "Builds a colour from hue, saturation, value and alpha components.").param("h", "0.0", "Hue", "0..1.", "expression").param("s", "1.0", "Saturation", "0..1.", "expression").param("v", "1.0", "Value", "0..1.", "expression").param("a", "1.0", "Alpha", "0..1.", "expression"))
	descriptors.append(F.expr("ColorFromHex", "Color From Hex", "Color.html({hex})", "Color", "color {hex}", "Builds a colour from an HTML hex string like #ff8800.").param("hex", "\"#ff8800\"", "Hex", "HTML colour string.", "expression"))
	descriptors.append(F.expr("ColorInverted", "Invert Color", "({color}).inverted()", "Color", "invert {color}", "Returns the opposite colour, useful for highlight or negative effects.").param("color", "Color(1, 1, 1, 1)", "Color", "Colour to invert.", "color"))

	# ── Variable easing / flipping (the two beginner patterns that always come out wrong by hand) ──
	# Move Toward is the frame-rate INDEPENDENT damping form: the exponential decay means the same
	# Speed lands the same distance per SECOND no matter the frame rate, unlike the naive
	# `lerp(a, b, 0.1)` written straight into a per-frame event.
	descriptors.append(F.act("SmoothMoveToward", "Move Toward (smooth)", "{var_name} = lerp({var_name}, {target}, 1.0 - exp(-maxf({speed}, 0.0) * get_process_delta_time()))", "Variables", "Move {var_name} toward {target} at speed {speed}", "Eases a variable smoothly toward a target instead of snapping to it. Works on numbers, Vector2/Vector3 and Colors alike (lerp is generic). It is frame-rate independent - the exponential form behaves the same at 30 and 144 fps.").param("var_name", "value", "Variable", "Variable to ease.", "variable_reference").param("target", "1.0", "Toward", "The value to approach.", "expression").param("speed", "8.0", "Speed", "How fast it closes the gap - higher is snappier, around 8 feels like a firm camera follow.", "expression"))
	descriptors.append(F.act("ToggleVar", "Toggle boolean", "{var_name} = not {var_name}", "Variables", "Toggle {var_name}", "Flips a true/false variable to its opposite - on becomes off, off becomes on.").param("var_name", "enabled_flag", "Variable", "Boolean variable to flip.", "variable_reference"))
	descriptors.append(F.expr("AsClockTime", "As Clock Time", "(\"%02d:%02d\" % [int(maxf({seconds}, 0.0)) / 60, int(maxf({seconds}, 0.0)) % 60])", "Text", "as clock time ({seconds})", "Turns a number of seconds into minutes:seconds text - 90 seconds reads \"01:30\". For countdown timers, lap times and speedrun clocks.").param("seconds", "90.0", "Seconds", "A duration in seconds.", "expression"))
	# Charge Toward: the hold-to-charge meter. Filling by "reach the maximum in N seconds" (rather than
	# "add X per frame") means the tuning number is the one the designer actually thinks in, and the
	# clamp is baked in so the meter can never overfill however long the button is held.
	descriptors.append(F.act("ChargeToward", "Charge Toward", "{var_name} = minf({var_name} + (maxf({maximum}, 0.0) / maxf({seconds}, 0.001)) * get_process_delta_time(), maxf({maximum}, 0.0))", "Variables", "charge {var_name} to {maximum} over {seconds}s", "Fills a variable while the event runs, reaching the maximum after the given seconds - a hold-to-charge meter. Put it under a while-held input condition; it clamps itself at the top, and the release event just reads the value.").param("var_name", "power", "Variable", "The meter to fill.", "variable_reference").param("maximum", "100.0", "Up To", "The full value the meter tops out at.", "expression").param("seconds", "1.5", "Over Seconds", "How long a full charge takes from empty.", "expression"))
	descriptors.append(F.expr("ProgressOf", "Progress Of", "clampf(inverse_lerp({from}, {to}, {value}), 0.0, 1.0)", "Math & Random", "progress of {value} from {from} to {to}", "Gives how far a value has come through a range, as 0 to 1 - feed it straight into a bar's scale, an alpha, or a colour lerp. This is the inverse_lerp nobody finds, with the clamp already applied.").param("value", "5.0", "Value", "The current value.", "expression").param("from", "0.0", "From", "The value that counts as empty.", "expression").param("to", "10.0", "To", "The value that counts as full.", "expression"))
	descriptors.append(F.expr("PercentOf", "Percent Of", "(clampf(inverse_lerp({from}, {to}, {value}), 0.0, 1.0) * 100.0)", "Math & Random", "percent of {value} from {from} to {to}", "The same reading as Progress Of, but as 0 to 100 - the number you show in text, like \"73%\" health.").param("value", "5.0", "Value", "The current value.", "expression").param("from", "0.0", "From", "The value that counts as empty.", "expression").param("to", "10.0", "To", "The value that counts as full.", "expression"))

	# ── Type-guarded fallbacks: turn "whatever this is" into something a typed variable can take ──
	# Everything LOADED rather than typed arrives as a value that might be the wrong shape, or missing
	# outright: a JSON field, a save slot, a Dictionary read, a method that can return null, a value
	# another sheet handed over. Each of these hands the value back only when it really is that kind of
	# thing, and your own default otherwise, so ONE row replaces a guard row plus a conversion.
	# Three deliberate details, each learned from what GDScript actually accepts:
	#   - the guard is `typeof(x) == TYPE_*`, never `x is String`. The analyzer REFUSES to compile
	#     `i is String` once it knows `i` is an int ("Expression is of type int so it can't be of type
	#     String"), so an `is` guard would turn "pointed the row at the wrong variable" into a build
	#     break. typeof compiles against any type and simply lands on the fallback at runtime.
	#   - a trailing `and {value}` reads "and it is not empty": Godot treats an empty String, Array or
	#     Dictionary as false. `.is_empty()` and a `!= ""` comparison are both unusable here for the
	#     same analyzer reason - each is a parse error against a value of a known other type.
	#   - a zero is NOT missing. Number Or keeps 0 and Value Or keeps 0 and "" alike; only the
	#     emptiness of a text/list/record counts as nothing.
	# The value expression is read two or three times in the emitted line, so keep it a READ (a
	# variable, a .get()), never something that changes the game.
	descriptors.append(F.expr("NumberOr", "Number Or", "({value} if typeof({value}) in [TYPE_INT, TYPE_FLOAT] else {fallback})", "Variables", "{value} as a number, or {fallback}", "The value when it really is a number, or your own default when it is missing, null, text, or anything else. A zero counts as a real number and is kept. Use it to put a loaded value straight into a whole-number or decimal variable without a guard row first. " + DOUBLE_READ_NOTE).param("value", "0", "Value", "The untyped value to check - a save slot read, a JSON field, a Dictionary key.", "expression").param("fallback", "0", "Or", "What you get back when it is not a number.", "expression"))
	descriptors.append(F.expr("TextOr", "Text Or", "({value} if (typeof({value}) == TYPE_STRING and {value}) else {fallback})", "Variables", "{value} as text, or {fallback}", "The value when it really is text with something in it, or your own default when it is missing, null, blank, or another kind of value. The classic use is a saved player name that falls back to \"Player\". " + DOUBLE_READ_NOTE).param("value", "\"\"", "Value", "The untyped value to check - a save slot read, a JSON field, a Dictionary key.", "expression").param("fallback", "\"Player\"", "Or", "What you get back when it is not text, or is blank.", "expression"))
	# TYPE_PACKED_BYTE_ARRAY is the FIRST of the packed families and TYPE_MAX sits past the last, so
	# `typeof(x) >= TYPE_PACKED_BYTE_ARRAY` is "x is one of the packed arrays" without naming nine
	# constants. It earns its place because Split Text hands back a PackedStringArray: without it the
	# single most natural way to build a list here fell straight through to the fallback.
	descriptors.append(F.expr("ListOr", "List Or", "({value} if ((typeof({value}) == TYPE_ARRAY or typeof({value}) >= TYPE_PACKED_BYTE_ARRAY) and {value}) else {fallback})", "Variables", "{value} as a list, or {fallback}", "The value when it really is a list with items in it, or your own default when it is missing, null, empty, or another kind of value. A Split Text result counts as a list. Safe to feed straight into a For Each. " + DOUBLE_READ_NOTE).param("value", "[]", "Value", "The untyped value to check - a loaded inventory, a JSON array, a Split Text result, a Dictionary key.", "expression").param("fallback", "[]", "Or", "What you get back when it is not a list, or is empty.", "expression"))
	descriptors.append(F.expr("RecordOr", "Record Or", "({value} if (typeof({value}) == TYPE_DICTIONARY and {value}) else {fallback})", "Variables", "{value} as a record, or {fallback}", "The value when it really is a record (a dictionary) with keys in it, or your own default when it is missing, null, empty, or another kind of value. Pair it with Get Key so a whole missing settings block reads as defaults. " + DOUBLE_READ_NOTE).param("value", "{}", "Value", "The untyped value to check - a loaded settings block, a JSON object, a Dictionary key.", "expression").param("fallback", "{}", "Or", "What you get back when it is not a record, or is empty.", "expression"))
	descriptors.append(F.expr("ValueOr", "Value Or", "({value} if {value} != null else {fallback})", "Variables", "{value}, or {fallback} when it is nothing", "The value unless it is null, in which case your own default. This one guards nothing else: a zero, a blank text and an empty list all count as real values here. Use it for a method that can hand back null. " + DOUBLE_READ_NOTE).param("value", "null", "Value", "Anything that might be null - a method result, a freed reference, a missing key.", "expression").param("fallback", "0", "Or", "What you get back when it is null.", "expression"))

	# Expressions
	descriptors.append(F.expr("GetVar", "Get Variable", "{var_name}", "Variables", "{var_name}", "Returns the current value stored in the named variable.").param("var_name", "var", "Variable", "Variable to read.", "variable_reference"))
	descriptors.append(F.expr("GetDelta", "Get Delta", "delta", "General Expressions", "delta", "Returns the seconds since last frame, used to make motion frame-rate independent."))
	descriptors.append(F.expr("GetPosition2D", "Get Position", "position", "General Expressions", "position", "Returns the node's 2D position as a Vector2.", "Node2D"))
	descriptors.append(F.expr("GetVelocity2D", "Get Velocity", "velocity", "General Expressions", "velocity", "Returns the character body's current movement velocity.", "CharacterBody2D"))
	descriptors.append(F.expr("GetLinearVelocity2D", "Get Linear Velocity", "linear_velocity", "General Expressions", "linear_velocity", "Returns the rigid body's current linear velocity from physics.", "RigidBody2D"))
	descriptors.append(F.expr("GetMonitoring", "Get Monitoring", "monitoring", "General Expressions", "monitoring", "Returns whether the area is currently watching for overlaps.", "Area2D"))
	descriptors.append(F.expr("GetTimerTimeLeft", "Get Time Left", "time_left", "General Expressions", "time_left", "Returns the seconds remaining before the timer fires.", "Timer"))
	descriptors.append(F.expr("GetCurrentAnimation", "Get Current Animation", "current_animation", "General Expressions", "current_animation", "Returns the name of the animation currently playing.", "AnimationPlayer"))

	# ── More Array helpers (make list manipulation easy without dropping to code) ──
	descriptors.append(F.expr("ArrayFront", "First Item", "{var_name}.front()", "Variables: Array", "{var_name}.front()", "Returns the first item in the array.").param("var_name", "list", "Array", "Array variable.", "variable_reference:Array"))
	descriptors.append(F.expr("ArrayBack", "Last Item", "{var_name}.back()", "Variables: Array", "{var_name}.back()", "Returns the last item in the array.").param("var_name", "list", "Array", "Array variable.", "variable_reference:Array"))
	descriptors.append(F.expr("ArrayFind", "Index Of", "{var_name}.find({value})", "Variables: Array", "{var_name}.find({value})", "Returns the position of a value in the array, or -1 if it's missing.").param("var_name", "list", "Array", "Array variable.", "variable_reference:Array").param("value", "0", "Value", "Value to find (-1 if missing).", "expression"))
	descriptors.append(F.expr("ArrayCount", "Count Of", "{var_name}.count({value})", "Variables: Array", "{var_name}.count({value})", "Returns how many times a value appears in the array.").param("var_name", "list", "Array", "Array variable.", "variable_reference:Array").param("value", "0", "Value", "Value to count.", "expression"))
	descriptors.append(F.act("ArrayReverse", "Reverse Array", "{var_name}.reverse()", "Variables: Array", "Reverse {var_name}", "Flips the array so its items run in the opposite order.").param("var_name", "list", "Array", "Array variable.", "variable_reference:Array"))
	descriptors.append(F.act("ArrayPushFront", "Push Front", "{var_name}.push_front({value})", "Variables: Array", "Push front {value} to {var_name}", "Inserts a value at the start of the array, shifting the rest along.").param("var_name", "list", "Array", "Array variable.", "variable_reference:Array").param("value", "0", "Value", "Value to prepend.", "expression"))
	descriptors.append(F.expr("ArrayPopBack", "Pop Back", "{var_name}.pop_back()", "Variables: Array", "{var_name}.pop_back()", "Removes and returns the last item of the array.").param("var_name", "list", "Array", "Array variable (removes + returns last).", "variable_reference:Array"))
	descriptors.append(F.expr("ArrayPopFront", "Pop Front", "{var_name}.pop_front()", "Variables: Array", "{var_name}.pop_front()", "Removes and returns the first item of the array.").param("var_name", "list", "Array", "Array variable (removes + returns first).", "variable_reference:Array"))
	descriptors.append(F.act("ArrayAppendArray", "Append Array", "{var_name}.append_array({other})", "Variables: Array", "Append {other} to {var_name}", "Adds every item from another array onto the end of this one.").param("var_name", "list", "Array", "Destination array.", "variable_reference:Array").param("other", "[]", "Other", "Array whose items are appended.", "expression"))
	descriptors.append(F.expr("ArraySlice", "Slice", "{var_name}.slice({from}, {to})", "Variables: Array", "{var_name}.slice({from}, {to})", "Returns a sub-section of the array between the start and end indexes.").param("var_name", "list", "Array", "Array variable.", "variable_reference:Array").param("from", "0", "From", "Start index.", "expression").param("to", "1", "To", "End index (exclusive).", "expression"))
	descriptors.append(F.expr("ArrayJoin", "Join To Text", "{separator}.join({var_name})", "Variables: Array", "join {var_name} with {separator}", "Joins an array of strings into one text using a separator.").param("var_name", "list", "Array", "Array of strings.", "variable_reference:Array").param("separator", "\", \"", "Separator", "String between items.", "expression"))
	descriptors.append(F.expr("ArrayMax", "Array Max", "{var_name}.max()", "Variables: Array", "{var_name}.max()", "Returns the largest value found in the array.").param("var_name", "list", "Array", "Array variable.", "variable_reference:Array"))
	descriptors.append(F.expr("ArrayMin", "Array Min", "{var_name}.min()", "Variables: Array", "{var_name}.min()", "Returns the smallest value found in the array.").param("var_name", "list", "Array", "Array variable.", "variable_reference:Array"))
	descriptors.append(F.expr("ArrayDuplicate", "Copy Array", "{var_name}.duplicate()", "Variables: Array", "{var_name}.duplicate()", "Returns an independent copy of the array so edits don't affect the original.").param("var_name", "list", "Array", "Array variable to copy.", "variable_reference:Array"))
	descriptors.append(F.act("ArrayResize", "Resize Array", "{var_name}.resize({size})", "Variables: Array", "Resize {var_name} to {size}", "Changes the array's length, adding empty slots or trimming items.").param("var_name", "list", "Array", "Array variable.", "variable_reference:Array").param("size", "0", "Size", "New length.", "expression"))
	descriptors.append(F.act("ArrayFill", "Fill Array", "{var_name}.fill({value})", "Variables: Array", "Fill {var_name} with {value}", "Sets every slot in the array to the same value.").param("var_name", "list", "Array", "Array variable.", "variable_reference:Array").param("value", "0", "Value", "Value to fill every slot with.", "expression"))

	# ── More Dictionary helpers ──
	descriptors.append(F.expr("DictDuplicate", "Copy Dictionary", "{var_name}.duplicate()", "Variables: Dictionary", "{var_name}.duplicate()", "Returns an independent copy of the dictionary.").param("var_name", "dict", "Dictionary", "Dictionary variable to copy.", "variable_reference:Dictionary"))
	descriptors.append(F.cond("DictHasValue", "Has Value", "{var_name}.values().has({value})", "Variables: Dictionary", "{var_name} has value {value}", "True when the dictionary contains the given value anywhere.").param("var_name", "dict", "Dictionary", "Dictionary variable.", "variable_reference:Dictionary").param("value", "0", "Value", "Value to look for.", "expression"))

	# ── Vector helpers (Vector2/Vector3 manipulation) ──
	descriptors.append(F.expr("MakeVector2", "Make Vector2", "Vector2({x}, {y})", "Variables: Vector", "Vector2({x}, {y})", "Builds a Vector2 from separate x and y numbers, for positions or directions.").param("x", "0.0", "X", "X component.", "expression").param("y", "0.0", "Y", "Y component.", "expression"))
	descriptors.append(F.expr("MakeVector3", "Make Vector3", "Vector3({x}, {y}, {z})", "Variables: Vector", "Vector3({x}, {y}, {z})", "Builds a 3D point or direction from X, Y and Z numbers.").param("x", "0.0", "X", "X component.", "expression").param("y", "0.0", "Y", "Y component.", "expression").param("z", "0.0", "Z", "Z component.", "expression"))
	descriptors.append(F.expr("VectorLength", "Vector Length", "{vector}.length()", "Variables: Vector", "{vector}.length()", "Returns how long a vector is, e.g. a velocity's speed.").param("vector", "Vector2.ZERO", "Vector", "Vector expression.", "expression"))
	descriptors.append(F.expr("VectorNormalized", "Normalized", "{vector}.normalized()", "Variables: Vector", "{vector}.normalized()", "Returns the vector shrunk to length 1, keeping only its direction.").param("vector", "Vector2.ZERO", "Vector", "Vector expression.", "expression"))
	descriptors.append(F.expr("VectorDistanceTo", "Distance Between", "{a}.distance_to({b})", "Variables: Vector", "{a}.distance_to({b})", "Returns the straight-line distance between two points.").param("a", "Vector2.ZERO", "From", "First point.", "expression").param("b", "Vector2.ZERO", "To", "Second point.", "expression"))
	descriptors.append(F.expr("VectorDirectionTo", "Direction To", "{a}.direction_to({b})", "Variables: Vector", "{a}.direction_to({b})", "Returns a unit vector pointing from one point toward another, handy for aiming.").param("a", "Vector2.ZERO", "From", "Start point.", "expression").param("b", "Vector2.ZERO", "To", "Target point.", "expression"))
	descriptors.append(F.expr("VectorAngle", "Vector Angle", "{vector}.angle()", "Variables: Vector", "{vector}.angle()", "Returns a 2D vector's angle in radians, useful for facing direction.").param("vector", "Vector2.ZERO", "Vector", "Vector2 expression (radians).", "expression"))
	descriptors.append(F.expr("VectorDot", "Dot Product", "{a}.dot({b})", "Variables: Vector", "{a}.dot({b})", "Returns the dot product of two vectors, telling how aligned they are.").param("a", "Vector2.ZERO", "A", "First vector.", "expression").param("b", "Vector2.ZERO", "B", "Second vector.", "expression"))
	descriptors.append(F.expr("VectorRotated", "Rotated", "{vector}.rotated({radians})", "Variables: Vector", "{vector}.rotated({radians})", "Returns the vector turned by the given angle in radians.").param("vector", "Vector2.ZERO", "Vector", "Vector2 expression.", "expression").param("radians", "0.0", "Radians", "Rotation in radians.", "expression"))
	descriptors.append(F.expr("VectorLerp", "Vector Lerp", "{a}.lerp({b}, {weight})", "Variables: Vector", "{a}.lerp({b}, {weight})", "Returns a point blended between two vectors, great for smooth movement.").param("a", "Vector2.ZERO", "From", "Start vector.", "expression").param("b", "Vector2.ZERO", "To", "End vector.", "expression").param("weight", "0.5", "Weight", "0..1 blend.", "expression"))
	descriptors.append(F.expr("VectorLimitLength", "Clamp Length", "{vector}.limit_length({max_length})", "Variables: Vector", "{vector}.limit_length({max_length})", "Returns the vector capped to a maximum length, e.g. a speed limit.").param("vector", "Vector2.ZERO", "Vector", "Vector expression.", "expression").param("max_length", "1.0", "Max length", "Maximum magnitude.", "expression"))
	# ── Named parts: ONE verb for a pair, a triple, a colour and a record alike ──
	# Make Vector2/3 BUILD vectors and Length/Angle/Normalized/Direction To read DERIVED values; until
	# now nothing named a single component, so it was Get/Set Property with a typed-in `position.x`.
	# These read as a sentence instead: "the up/down part of velocity", "the see-through part of
	# modulate". The emitted access is a subscript with a quoted key, which Godot resolves as a
	# component on Vector2/Vector3/Color AND as a field on a Dictionary - so the same row also reads
	# and writes a record's named field, and a saved {"x": …, "y": …} position needs no special case.
	# A record key OUTSIDE the seven named parts stays with the shipped Get Key (with default) / Set
	# Key, which is where an arbitrary key (and its own missing-value fallback) belongs.
	# Why a subscript rather than the `.y` a hand would write: `{var_name}.{part} = {value}` is
	# character-for-character the Set Property catch-all, and being authored in an earlier module it
	# would out-rank it in the reverse-lift index and re-label EVERY hand-written `foo.bar = baz` as
	# Set Part Of. The bracket form ties with Set Key instead, which is authored earlier here and so
	# keeps winning; nothing that lifts today changes.
	# THE PRICE of that choice, stated plainly because it is a real one: the emitted `velocity["y"] =
	# 0.0` is character-for-character what Set Key emits, so REOPENING a .gd-backed sheet lifts the
	# row back as Set Key, not as Set Part Of. The code is byte-identical either way (the lossless
	# covenant is untouched) - what is lost on a reopen is the sentence, and that is the deliberate
	# trade for never mis-labelling somebody else's `save["gold"] = 5`. Pinned in fallbacks_test.
	# The target is a PROPERTY reference, not a sheet-variable dropdown: the headline targets are a
	# node's own members (`velocity`, `modulate`), which a closed variables dropdown cannot name at
	# all. The property field is an editable autocomplete over the host class, so a sheet variable is
	# still typed in the same cell.
	descriptors.append(F.expr("PartOf", "Part Of", "({value})[{part}]", "Variables: Vector", "the {part} part of {value}", "One named piece of a pair, a triple, a colour or a record: the up/down part of a velocity (the jump-or-fall test), the see-through part of a tint, the forward/back part of a 3D direction. Reads as a sentence instead of a typed-in .y. Pick a part the value actually has - a record that might be missing the field is the shipped Get Key (with default)'s job, because that one takes a fallback and this one does not.").param("value", "Vector2(1, 2)", "Of", "A Vector2, Vector3, Color or record to read one part of.", "expression").param_built(_part_param("Which named part to read.")))
	descriptors.append(F.act("SetPartOf", "Set Part Of", "{var_name}[{part}] = {value}", "Variables: Vector", "set the {part} part of {var_name} to {value}", "Changes one named part and leaves the rest alone: zero the vertical speed on landing and keep the horizontal, flatten a 3D direction to the ground plane, fade only the see-through part of a tint. Writing a part a record does not have yet ADDS it.").param("var_name", "self.position", "Variable or property", "What to change one part of: a node's own member (velocity, modulate, position) picked from the list, or the name of a sheet variable holding a Vector, Color or record.", "property_reference").param_built(_part_param("Which named part to write.")).param("value", "0.0", "To", "The new value for that one part.", "expression"))

	# ── String helpers (the common manipulations; the long tail stays one fx away) ──
	descriptors.append(F.cond("StringContains", "Text Contains", "{text}.contains({needle})", "Variables: String", "{text} contains {needle}", "True when the text contains the given substring somewhere inside it.").param("text", "\"\"", "Text", "Text to search.", "expression").param("needle", "\"\"", "Needle", "Substring to find.", "expression"))
	descriptors.append(F.cond("StringBeginsWith", "Text Begins With", "{text}.begins_with({prefix})", "Variables: String", "{text} begins with {prefix}", "True when the text starts with the given prefix.").param("text", "\"\"", "Text", "Text to test.", "expression").param("prefix", "\"\"", "Prefix", "Expected prefix.", "expression"))
	descriptors.append(F.cond("StringEndsWith", "Text Ends With", "{text}.ends_with({suffix})", "Variables: String", "{text} ends with {suffix}", "True when the text ends with the given suffix.").param("text", "\"\"", "Text", "Text to test.", "expression").param("suffix", "\"\"", "Suffix", "Expected suffix.", "expression"))
	descriptors.append(F.expr("StringSplit", "Split Text", "{text}.split({separator})", "Variables: String", "{text}.split({separator})", "Returns the text chopped into a list wherever the separator appears.").param("text", "\"\"", "Text", "Text to split.", "expression").param("separator", "\",\"", "Separator", "Delimiter.", "expression"))
	descriptors.append(F.expr("StringToInt", "Text To Int", "{text}.to_int()", "Variables: String", "{text}.to_int()", "Returns the text parsed into a whole number.").param("text", "\"0\"", "Text", "Text to parse.", "expression"))
	descriptors.append(F.expr("StringToFloat", "Text To Float", "{text}.to_float()", "Variables: String", "{text}.to_float()", "Returns the text parsed into a decimal number.").param("text", "\"0.0\"", "Text", "Text to parse.", "expression"))
	descriptors.append(F.expr("StringPadZeros", "Pad Number", "str({number}).pad_zeros({digits})", "Variables: String", "pad {number} to {digits} digits", "Returns the number padded with leading zeros, e.g. for scores like 007.").param("number", "0", "Number", "Number to pad.", "expression").param("digits", "2", "Digits", "Minimum digit count.", "expression"))
	descriptors.append(F.expr("StringRepeat", "Repeat Text", "{text}.repeat({count})", "Variables: String", "{text} x {count}", "Returns the text repeated the given number of times.").param("text", "\"#\"", "Text", "Text to repeat.", "expression").param("count", "3", "Count", "Number of repetitions.", "expression"))

	# ── AnimationTree (event-sheet-style state machines / blends) ──
	descriptors.append(F.act("SetAnimationTreeActive", "Set AnimationTree Active", "active = {active}", "Animation", "Set tree active {active}", "Turns this AnimationTree's playback on or off.", "AnimationTree").param_choice("active", "true", "Active", "Enable the animation tree.", ["true", "false"]))
	descriptors.append(F.act("TravelToState", "Travel To State", "get(\"parameters/playback\").travel({state})", "Animation", "Travel to animation state {state}", "Tells the state machine to transition to the named animation state. This is the tree's ROOT state machine: a machine nested inside another one is not reached.", "AnimationTree").param("state", "\"idle\"", "State", "State-machine node to travel to. The list is the tree's own states.", "animation_state"))
	descriptors.append(F.act("SetTreeParam", "Set Blend", "set({path}, {value})", "Animation", "Set blend {path} to {value}", "Sets an AnimationTree parameter like a blend amount, condition or timescale.", "AnimationTree").param("path", "\"parameters/TimeScale/scale\"", "Param Path", "AnimationTree parameter path (blend amount / condition / timescale).").param("value", "1.0", "Value", "Value (number / Vector2 / bool).", "expression"))
	descriptors.append(F.cond("IsTreeActive", "Is Tree Active", "active", "Animation", "Is tree active", "True when this AnimationTree is currently active and playing.", "AnimationTree"))
	descriptors.append(F.cond("IsInState", "Is In State", "get(\"parameters/playback\").get_current_node() == {state}", "Animation", "Is in state {state}", "True when the state machine is currently in the named animation state.", "AnimationTree").param("state", "\"idle\"", "State", "State-machine node name. The list is the tree's own states.", "animation_state"))
	descriptors.append(F.expr("GetCurrentState", "Current State", "get(\"parameters/playback\").get_current_node()", "Animation", "current state", "Returns the name of the state machine's current animation state.", "AnimationTree"))
	descriptors.append(F.expr("GetTreeParam", "Tree Parameter", "get({path})", "Animation", "param {path}", "Returns the current value of an AnimationTree parameter.", "AnimationTree").param("path", "\"parameters/TimeScale/scale\"", "Param Path", "AnimationTree parameter path."))


	# The difficulty curve as a value: start, drift per minute, hard limit - drops into any
	# number param so a spawner literally accelerates over the run. Zeroed by Start Ramp Clock
	# (otherwise minutes count from engine start).
	descriptors.append(F.expr("RampedValue", "Ramped", "clampf({start} + {per_minute} * (float(Time.get_ticks_msec()) / 60000.0 - float(get_meta(&\"__ramp_zero\", 0.0))), minf({start}, {limit}), maxf({start}, {limit}))", "Math & Random", "ramped from {start} by {per_minute}/min, limit {limit}", "A value that drifts over time and stops at a limit - 'Every Ramped(2, -0.3, 0.5) seconds' is a spawner that speeds up as the run goes on. Call Start Ramp Clock when the run begins.").param("start", "2.0", "Start", "The value at minute zero.", "expression").param("per_minute", "-0.3", "Per Minute", "Drift per minute - negative ramps down.", "expression").param("limit", "0.5", "Limit", "The value never passes this.", "expression"))
	descriptors.append(F.act("StartRampClock", "Start Ramp Clock", "set_meta(&\"__ramp_zero\", float(Time.get_ticks_msec()) / 60000.0)", "Time", "start the ramp clock", "Marks minute zero for this node's Ramped values - call it when the run actually starts, not in menus."))
	# Tiles as a unit: distances in tile counts, sized by ONE project setting - so 'within
	# Tiles(3)' reads the way a grid game thinks.
	descriptors.append(F.expr("TilesUnit", "Tiles", "({count} * float(ProjectSettings.get_setting(\"eventforge/tile_size\", 16.0)))", "Math & Random", "Tiles({count})", "A distance in tiles: Tiles(3) is three tiles in pixels, sized by the eventforge/tile_size project setting (default 16). Set it once and every distance can speak in tiles.").param("count", "3", "Tiles", "How many tiles.", "expression"))
	return descriptors


## The named-part dropdown Part Of and Set Part Of share. `display_option_labels` is what keeps the
## GDScript out of the sentence: the row emits `velocity["y"]` and READS "the Y (up / down) part of
## velocity", because the emitted value here is always exactly one of the seven option keys.
static func _part_param(description: String) -> ACEParam:
	var parameter: ACEParam = F.make_param("part", "String", "\"y\"", "Part", description, "", PART_OPTIONS)
	parameter.display_option_labels = true
	return parameter
