# EventForge module - Developer helper vocabulary (the everyday dev tools).
#
# The small native operations a Godot dev reaches for constantly while building + debugging:
# console output, assertions, scene-tree groups, node metadata, and tree navigation. They compile
# to the exact one-liners you'd hand-write (print(...), add_to_group(...), set_meta(...),
# get_parent()), so picking one keeps logic as an editable row instead of a raw block - and means
# common dev chores never force a drop to GDScript. Grouped under Debug / Groups / Metadata / Nodes.
@tool
class_name EventForgeDevACEs
extends RefCounted

const F := preload("res://addons/eventforge/registration/ace_factory.gd")


static func get_descriptors() -> Array[ACEDescriptor]:
	var descriptors: Array[ACEDescriptor] = []

	# ── Debug: console output + assertions (the #1 thing you do while building) ──
	descriptors.append(F.act("Print", "Print", "print({value})", "Debug", "print {value}", "Prints a value to the Output console, useful for debugging what's happening.").param("value", "\"hello\"", "Value", "Value/expression to print to the Output console.", "expression"))
	descriptors.append(F.act("PrintLabeled", "Print Labeled", "print({label}, {value})", "Debug", "print {label} {value}", "Prints a value preceded by a label so you can tell debug messages apart.").param("label", "\"value:\"", "Label", "Leading label string.", "expression").param("value", "0", "Value", "Value/expression to print after the label.", "expression"))
	descriptors.append(F.act("PrintRich", "Print Rich (BBCode)", "print_rich({value})", "Debug", "print rich {value}", "Prints colored or bold text to the Output console using BBCode formatting.").param("value", "\"[b]done[/b]\"", "Value", "BBCode string (colors/bold) for the Output console. Select text and hit B / I / U / S to format it.", "bbcode_text"))
	descriptors.append(F.act("PushWarning", "Push Warning", "push_warning({message})", "Debug", "warn {message}", "Logs a warning message that appears in Godot's debugger panel.").param("message", "\"check this\"", "Message", "Warning text (shows in the debugger).", "expression"))
	descriptors.append(F.act("PushError", "Push Error", "push_error({message})", "Debug", "error {message}", "Logs an error message that appears in Godot's debugger panel.").param("message", "\"bad state\"", "Message", "Error text (shows in the debugger).", "expression"))
	descriptors.append(F.act("Assert", "Assert", "assert({condition}, {message})", "Debug", "assert {condition}", "Crashes during testing if a condition isn't true, catching bugs early; removed from release.").param("condition", "true", "Condition", "Boolean that must hold (stripped from release builds).", "expression").param("message", "\"assertion failed\"", "Message", "Message if it fails.", "expression"))
	descriptors.append(F.act("PrintTree", "Print Scene Tree", "print_tree_pretty()", "Debug", "print scene tree", "Prints the whole scene's node hierarchy to the output log for debugging."))
	# (Frame Count lives in system_aces.gd under "Time" - no duplicate "Core::GetFrameCount" here.)
	# A manual debugger pause as a pickable row (complements the F9 gutter breakpoints).
	descriptors.append(F.act("Breakpoint", "Breakpoint (pause debugger)", "breakpoint", "Debug", "breakpoint", "Pauses the game in the debugger right here so you can inspect things."))

	# ── Debug: value trails (the last N values of anything, kept and dumpable) ──
	# Every other live surface here shows the CURRENT frame; an intermittent bug lives in the two
	# seconds before the frame you are looking at. A trail is a named rolling history, stored the
	# same stateless way the cooldown family stores its deadlines: in node metadata, so Remember In
	# Trail in one event and Lowest In Trail in another (or in a different sheet on the same node)
	# agree with no wiring, no members and no {uid} slot. Every trail lives inside ONE metadata
	# dictionary rather than one metadata key per name, because a metadata key must be a valid
	# identifier and a trail called "player speed" is not - the name goes in the dictionary, where
	# it is free text. It records SILENTLY: nothing shows until a row logs it, writes it, or reads it.
	descriptors.append(F.act("RememberInTrail", "Remember In Trail", "var __trails_{uid}: Dictionary = get_meta(&\"__ef_trails\", {}) as Dictionary\nvar __trail_{uid}: Array = __trails_{uid}.get({trail}, []) as Array\n__trail_{uid}.append({value})\nif __trail_{uid}.size() > maxi(int({keep}), 1):\n\t__trail_{uid} = __trail_{uid}.slice(__trail_{uid}.size() - maxi(int({keep}), 1))\n__trails_{uid}[{trail}] = __trail_{uid}\nset_meta(&\"__ef_trails\", __trails_{uid})", "Debug", "remember [b]{value}[/b] in trail [b]{trail}[/b], keep [b]{keep}[/b]", "Records a value into a named rolling history you can dump, chart, or check when something goes wrong.").param("value", "0", "Value", "The value to record this tick - a number, a vector, anything printable.", "expression").param("trail", "\"vy\"", "Trail", "Trail name - any label you also use in the trail expressions.", "expression").param("keep", "120", "Keep", "How many recent values to hold (older ones drop off the front).", "expression"))
	descriptors.append(F.expr("TrailValues", "Trail Values", "((get_meta(&\"__ef_trails\", {}) as Dictionary).get({trail}, []) as Array)", "Debug", "trail [b]{trail}[/b] values", "Returns the whole trail as an array, oldest first - feed it to a chart, a table, or an array action.").param("trail", "\"vy\"", "Trail", "Trail name, matching a Remember In Trail action.", "expression"))
	descriptors.append(F.expr("TrailLowest", "Lowest In Trail", "(((get_meta(&\"__ef_trails\", {}) as Dictionary).get({trail}, []) as Array).reduce(func(__acc, __v): return min(__acc, __v), INF))", "Debug", "lowest in trail [b]{trail}[/b]", "The smallest value recorded in a trail, which is the spike a per-frame watch blinked past. An empty trail reads as INF.").param("trail", "\"vy\"", "Trail", "Trail name, matching a Remember In Trail action.", "expression"))
	descriptors.append(F.expr("TrailHighest", "Highest In Trail", "(((get_meta(&\"__ef_trails\", {}) as Dictionary).get({trail}, []) as Array).reduce(func(__acc, __v): return max(__acc, __v), -INF))", "Debug", "highest in trail [b]{trail}[/b]", "The largest value recorded in a trail. An empty trail reads as -INF.").param("trail", "\"vy\"", "Trail", "Trail name, matching a Remember In Trail action.", "expression"))
	descriptors.append(F.expr("TrailAverage", "Average In Trail", "(((get_meta(&\"__ef_trails\", {}) as Dictionary).get({trail}, []) as Array).reduce(func(__acc, __v): return __acc + float(__v), 0.0) / maxf(float(((get_meta(&\"__ef_trails\", {}) as Dictionary).get({trail}, []) as Array).size()), 1.0))", "Debug", "average of trail [b]{trail}[/b]", "The mean of every number recorded in a trail - a rolling average that is as useful in gameplay as in debugging. An empty trail reads as 0.").param("trail", "\"vy\"", "Trail", "Trail name, matching a Remember In Trail action.", "expression"))
	descriptors.append(F.expr("TrailNewest", "Newest In Trail", "(([0] + ((get_meta(&\"__ef_trails\", {}) as Dictionary).get({trail}, []) as Array)).back())", "Debug", "newest in trail [b]{trail}[/b]", "The most recently recorded value in a trail, or 0 when nothing has been recorded yet.").param("trail", "\"vy\"", "Trail", "Trail name, matching a Remember In Trail action.", "expression"))
	descriptors.append(F.expr("TrailLength", "Trail Length", "(((get_meta(&\"__ef_trails\", {}) as Dictionary).get({trail}, []) as Array).size())", "Debug", "length of trail [b]{trail}[/b]", "How many values a trail is currently holding, which tops out at the Keep you gave it.").param("trail", "\"vy\"", "Trail", "Trail name, matching a Remember In Trail action.", "expression"))
	descriptors.append(F.act("LogTrail", "Log Trail", "print(\"trail \", {trail}, \": \", (get_meta(&\"__ef_trails\", {}) as Dictionary).get({trail}, []))", "Debug", "log trail [b]{trail}[/b]", "Prints the whole trail to the Output console, so the seconds before a bug arrive with the bug.").param("trail", "\"vy\"", "Trail", "Trail name, matching a Remember In Trail action.", "expression"))
	descriptors.append(F.act("SaveTrailCsv", "Save Trail To CSV", "var __csv_{uid}: FileAccess = FileAccess.open({path}, FileAccess.WRITE)\nif __csv_{uid} != null:\n\t__csv_{uid}.store_line(\"index,value\")\n\tvar __rows_{uid}: Array = (get_meta(&\"__ef_trails\", {}) as Dictionary).get({trail}, []) as Array\n\tfor __i_{uid}: int in __rows_{uid}.size():\n\t\t__csv_{uid}.store_line(\"%d,%s\" % [__i_{uid}, str(__rows_{uid}[__i_{uid}])])\n\t__csv_{uid}.close()", "Debug", "save trail [b]{trail}[/b] to [b]{path}[/b]", "Writes a trail to a two-column CSV file you can open in a spreadsheet and plot.").param("trail", "\"vy\"", "Trail", "Trail name, matching a Remember In Trail action.", "expression").param("path", "\"user://trail.csv\"", "Path", "Where to write the file. Use user:// so it works in an exported game.", "expression"))
	descriptors.append(F.act("ClearTrail", "Clear Trail", "var __trails_{uid}: Dictionary = get_meta(&\"__ef_trails\", {}) as Dictionary\n__trails_{uid}.erase({trail})\nset_meta(&\"__ef_trails\", __trails_{uid})", "Debug", "clear trail [b]{trail}[/b]", "Forgets everything a trail recorded, so the next run starts from nothing.").param("trail", "\"vy\"", "Trail", "Trail name, matching a Remember In Trail action.", "expression"))

	# ── Debug: frame budget conditions and named stopwatches ──
	# Vocabulary, not chrome: no row gains a margin chip and nothing is displayed anywhere. A
	# measurement becomes visible only where a row sends it (Log Measurements, a label, the Debug
	# Overlay pack). Godot emits no signal for a frame overrun or a sustained FPS drop, so these
	# are honestly CONDITIONS - the one case where polling is the only truth available.
	descriptors.append(F.cond("FrameOverBudget", "Frame Took Longer Than", "(get_process_delta_time() * 1000.0 > {ms})", "Debug", "frame took longer than [b]{ms}[/b] ms", "True on a frame that took longer than your budget, which is the hitch caught as it happens. Needs a per-frame trigger.").param("ms", "20.0", "Milliseconds", "The budget. 16.6 is one frame at 60 FPS.", "expression"))
	# Sustained low FPS: one stuttery frame is not a performance problem, three seconds of them is.
	# A per-instance member remembers WHEN the drop started and the helper clears it the moment the
	# framerate recovers, so the row only fires once the drop has genuinely lasted.
	descriptors.append(F.cond("FpsBelowFor", "FPS Below For", "__fps_below_for_{uid}({fps}, {seconds})", "Debug", "FPS below [b]{fps}[/b] for [b]{seconds}[/b] seconds", "True once the framerate has stayed under your floor for the whole stretch you name, which tells a real performance drop apart from one stuttery frame. Needs a per-frame trigger.").param("fps", "45.0", "FPS", "The framerate floor. Below this counts as a drop.", "expression").param("seconds", "3.0", "For Seconds", "How long the drop must last before this is true.", "expression").stateful("var __fpslow_{uid}: float = -1.0\n\nfunc __fps_below_for_{uid}(limit: float, seconds: float) -> bool:\n\tvar now: float = Time.get_ticks_msec() * 0.001\n\tif Engine.get_frames_per_second() >= limit:\n\t\t__fpslow_{uid} = -1.0\n\t\treturn false\n\tif __fpslow_{uid} < 0.0:\n\t\t__fpslow_{uid} = now\n\t\treturn false\n\treturn now - __fpslow_{uid} >= seconds"))
	# The MOMENT, rather than the state: the pair above answer "is it slow right now", which is true
	# on sixty frames a second and gives a row nowhere to put "and do something about it". These two
	# speak ONCE - the first fires on the frame a run of long frames reaches the length you named and
	# stays quiet until the run breaks; the second fires once the calm has lasted, and only if it saw
	# a long frame first, so a game that started well never hears "recovered" out of nowhere.
	#
	# Two thresholds and two lengths between them is HYSTERESIS, and it is the whole point: one number
	# would have the game flicking its own quality up and down on the boundary forever. Fire long at
	# over 16 ms for 30 frames, recovered at under 12 ms for 300, and the gap is what stops the
	# flapping. Each row carries its own counters, so the pair works with nothing wired between them.
	descriptors.append(F.cond("FrameRunningLong", "On The Frame Running Long", "__frame_long_{uid}({ms}, {frames})", "Debug", "On the frame running long [b]{ms}[/b] ms for [b]{frames}[/b] frames", "True on the ONE frame where the game has been over budget for the whole run you name, and quiet after that until a frame comes in under budget again. This is where a game turns its own effects down. Needs a per-frame trigger.").param("ms", "16.0", "Over Milliseconds", "A frame longer than this counts as a long one. 16.6 is one frame at 60 FPS.", "expression").param("frames", "30", "For Frames", "How many long frames in a row before this fires. One hitch is not a problem; half a second of them is.", "expression").stateful("var __frame_long_run_{uid}: int = 0\nvar __frame_long_said_{uid}: bool = false\n\nfunc __frame_long_{uid}(ms: float, frames: int) -> bool:\n\tif get_process_delta_time() * 1000.0 <= ms:\n\t\t__frame_long_run_{uid} = 0\n\t\t__frame_long_said_{uid} = false\n\t\treturn false\n\t__frame_long_run_{uid} += 1\n\tif __frame_long_said_{uid} or __frame_long_run_{uid} < frames:\n\t\treturn false\n\t__frame_long_said_{uid} = true\n\treturn true"))
	descriptors.append(F.cond("FrameRecovered", "On The Frame Recovered", "__frame_calm_{uid}({ms}, {frames})", "Debug", "On the frame recovered under [b]{ms}[/b] ms for [b]{frames}[/b] frames", "True on the ONE frame where the game has run comfortably for the whole run you name, after having been over budget. This is where the effects go back on. It never fires before a long stretch has happened, so a game that started well hears nothing. Needs a per-frame trigger.").param("ms", "12.0", "Under Milliseconds", "A frame shorter than this counts as calm. Keep it comfortably under the long threshold - the gap between the two is what stops the game flapping.", "expression").param("frames", "300", "For Frames", "How many calm frames in a row before this fires. Long enough that a lull in the action is not mistaken for a fix.", "expression").stateful("var __frame_calm_run_{uid}: int = 0\nvar __frame_was_long_{uid}: bool = false\n\nfunc __frame_calm_{uid}(ms: float, frames: int) -> bool:\n\tif get_process_delta_time() * 1000.0 >= ms:\n\t\t__frame_calm_run_{uid} = 0\n\t\t__frame_was_long_{uid} = true\n\t\treturn false\n\t__frame_calm_run_{uid} += 1\n\tif not __frame_was_long_{uid} or __frame_calm_run_{uid} < frames:\n\t\treturn false\n\t__frame_was_long_{uid} = false\n\treturn true"))
	# Named stopwatches: wrap the work you suspect, then read it back as last / average / peak.
	# Same stateless metadata idiom as the trails above: two dictionaries in node metadata, one
	# holding the open start stamps and one accumulating [total_ms, samples, peak_ms, last_ms] per
	# name. A name is free text (spaces welcome) because it is a dictionary key, never a meta key.
	descriptors.append(F.act("StartMeasuring", "Start Measuring", "var __starts_{uid}: Dictionary = get_meta(&\"__ef_span_starts\", {}) as Dictionary\n__starts_{uid}[{named}] = Time.get_ticks_usec()\nset_meta(&\"__ef_span_starts\", __starts_{uid})", "Debug", "start measuring [b]{named}[/b]", "Starts a named stopwatch. Pair it with Stop Measuring around the work you suspect.").param("named", "\"spawn wave\"", "Name", "The name this measurement is reported under.", "expression"))
	descriptors.append(F.act("StopMeasuring", "Stop Measuring", "var __starts_{uid}: Dictionary = get_meta(&\"__ef_span_starts\", {}) as Dictionary\nvar __span_{uid}: float = float(Time.get_ticks_usec() - int(__starts_{uid}.get({named}, Time.get_ticks_usec()))) / 1000.0\nvar __stats_{uid}: Dictionary = get_meta(&\"__ef_spans\", {}) as Dictionary\nvar __row_{uid}: Array = __stats_{uid}.get({named}, [0.0, 0, 0.0, 0.0]) as Array\n__stats_{uid}[{named}] = [float(__row_{uid}[0]) + __span_{uid}, int(__row_{uid}[1]) + 1, maxf(float(__row_{uid}[2]), __span_{uid}), __span_{uid}]\nset_meta(&\"__ef_spans\", __stats_{uid})", "Debug", "stop measuring [b]{named}[/b]", "Stops a named stopwatch and files the result, keeping the last, the average and the worst reading for that name.").param("named", "\"spawn wave\"", "Name", "The name you gave Start Measuring.", "expression"))
	descriptors.append(F.expr("MeasuredLast", "Last Measured (ms)", "(float(((get_meta(&\"__ef_spans\", {}) as Dictionary).get({named}, [0.0, 0, 0.0, 0.0]) as Array)[3]))", "Debug", "last measured [b]{named}[/b] ms", "How many milliseconds the most recent run of a named measurement took.").param("named", "\"spawn wave\"", "Name", "The name you gave Start Measuring.", "expression"))
	descriptors.append(F.expr("MeasuredAverage", "Average Measured (ms)", "(float(((get_meta(&\"__ef_spans\", {}) as Dictionary).get({named}, [0.0, 0, 0.0, 0.0]) as Array)[0]) / maxf(float(((get_meta(&\"__ef_spans\", {}) as Dictionary).get({named}, [0.0, 0, 0.0, 0.0]) as Array)[1]), 1.0))", "Debug", "average measured [b]{named}[/b] ms", "The mean cost in milliseconds across every run of a named measurement, which is the number to quote when you claim an optimization worked.").param("named", "\"spawn wave\"", "Name", "The name you gave Start Measuring.", "expression"))
	descriptors.append(F.expr("MeasuredPeak", "Peak Measured (ms)", "(float(((get_meta(&\"__ef_spans\", {}) as Dictionary).get({named}, [0.0, 0, 0.0, 0.0]) as Array)[2]))", "Debug", "peak measured [b]{named}[/b] ms", "The worst run of a named measurement in milliseconds, which is usually the one the player felt.").param("named", "\"spawn wave\"", "Name", "The name you gave Start Measuring.", "expression"))
	descriptors.append(F.act("LogMeasurements", "Log Measurements", "for __key_{uid}: Variant in (get_meta(&\"__ef_spans\", {}) as Dictionary):\n\tvar __row_{uid}: Array = (get_meta(&\"__ef_spans\", {}) as Dictionary)[__key_{uid}] as Array\n\tprint(\"%s: last %.2fms avg %.2fms peak %.2fms (%d samples)\" % [str(__key_{uid}), float(__row_{uid}[3]), float(__row_{uid}[0]) / maxf(float(__row_{uid}[1]), 1.0), float(__row_{uid}[2]), int(__row_{uid}[1])])", "Debug", "log measurements", "Prints every named measurement taken so far with its last, average and peak cost - the report you paste into a bug or a devlog."))
	descriptors.append(F.act("ClearMeasurements", "Clear Measurements", "set_meta(&\"__ef_spans\", {})\nset_meta(&\"__ef_span_starts\", {})", "Debug", "clear measurements", "Throws away every measurement recorded so far, so a fresh run starts from a clean slate."))

	# ── Groups: the scene-tree group vocabulary (tag + query + broadcast) ──
	descriptors.append(F.act("AddToGroup", "Add To Group", "{target}.add_to_group({group})", "Groups", "add [i]{target}[/i] to [b]{group}[/b]", "Tags a node into a named group so you can find or affect it later.").param("target", "self", "Target", "Node to tag.", "expression").param("group", "\"enemies\"", "Group", "Group name.", "group_reference"))
	descriptors.append(F.act("RemoveFromGroup", "Remove From Group", "{target}.remove_from_group({group})", "Groups", "remove [i]{target}[/i] from [b]{group}[/b]", "Untags a node from a named group when it should no longer belong.").param("target", "self", "Target", "Node to untag.", "expression").param("group", "\"enemies\"", "Group", "Group name.", "group_reference"))
	descriptors.append(F.cond("IsInGroup", "Is In Group", "{target}.is_in_group({group})", "Groups", "[i]{target}[/i] in [b]{group}[/b]", "True when the given node currently belongs to the named group.").param("target", "self", "Target", "Node to test.", "expression").param("group", "\"enemies\"", "Group", "Group name.", "group_reference"))
	descriptors.append(F.expr("GetFirstNodeInGroup", "Get First Node In Group", "get_tree().get_first_node_in_group({group})", "Groups", "first in {group}", "Returns the first node found in a named group, or nothing if empty.").param("group", "\"enemies\"", "Group", "Group name.", "group_reference"))
	descriptors.append(F.expr("GetNodeCountInGroup", "Count Nodes In Group", "get_tree().get_node_count_in_group({group})", "Groups", "count in {group}", "Returns how many nodes are currently in the named group.").param("group", "\"enemies\"", "Group", "Group name.", "group_reference"))
	# Numeric roll-ups across a group with no loop (the "average health of all enemies" case): each
	# reduces over get_nodes_in_group in one line. Sum/Average start at 0; Min/Max start at +/-INF so
	# an empty group yields that sentinel instead of erroring. {property} is a bare numeric member.
	descriptors.append(F.expr("SumInGroup", "Sum In Group", "get_tree().get_nodes_in_group({group}).reduce(func(__acc, __n): return __acc + __n.{property}, 0.0)", "Groups", "sum of {property} in {group}", "Returns the total of a numeric property added up across every group member.").param("group", "\"enemies\"", "Group", "Group name.", "group_reference").param("property", "health", "Property", "Numeric member to total up across the group, e.g. health.", "expression"))
	descriptors.append(F.expr("AverageInGroup", "Average In Group", "(get_tree().get_nodes_in_group({group}).reduce(func(__acc, __n): return __acc + __n.{property}, 0.0) / maxf(float(get_tree().get_nodes_in_group({group}).size()), 1.0))", "Groups", "average {property} in {group}", "Returns the average of a numeric property across all members of a group.").param("group", "\"enemies\"", "Group", "Group name.", "group_reference").param("property", "health", "Property", "Numeric member to average across the group, e.g. health.", "expression"))
	descriptors.append(F.expr("MinInGroup", "Lowest In Group", "get_tree().get_nodes_in_group({group}).reduce(func(__acc, __n): return min(__acc, __n.{property}), INF)", "Groups", "lowest {property} in {group}", "Returns the smallest value of a property among all group members.").param("group", "\"enemies\"", "Group", "Group name.", "group_reference").param("property", "health", "Property", "Numeric member to take the minimum of, e.g. health.", "expression"))
	descriptors.append(F.expr("MaxInGroup", "Highest In Group", "get_tree().get_nodes_in_group({group}).reduce(func(__acc, __n): return max(__acc, __n.{property}), -INF)", "Groups", "highest {property} in {group}", "Returns the largest value of a property among all group members.").param("group", "\"enemies\"", "Group", "Group name.", "group_reference").param("property", "health", "Property", "Numeric member to take the maximum of, e.g. health.", "expression"))
	descriptors.append(F.act("CallGroup", "Call Method On Group", "get_tree().call_group({group}, {method})", "Groups", "call {method} on {group}", "Calls the named method on every node in a group at once.").param("group", "\"enemies\"", "Group", "Group name.", "group_reference").param("method", "\"reset\"", "Method", "Method name to call on every member.", "expression"))
	# The SEND direction with data: a decoupled broadcast that carries a value to every group member (bare
	# call_group carries none, so passing data used to force get_node(sibling).method(x)). Leave Value blank
	# for a no-arg call - the {, args} optional-comma drops cleanly.
	descriptors.append(F.act("CallGroupWith", "Call Method On Group (with value)", "get_tree().call_group({group}, {method}{, args})", "Groups", "call {method}({args}) on {group}", "Calls a method with a value on every member of a group at once - a decoupled broadcast that carries data.").param("group", "\"enemies\"", "Group", "Group name.", "group_reference").param("method", "\"take_damage\"", "Method", "Method to call on every member.", "expression").param("args", "10", "Value", "Value(s) passed to the method (comma-separated); leave blank for none.", "expression"))

	# ── Metadata: arbitrary key/value on any node (Godot's set_meta/get_meta) ──
	descriptors.append(F.act("SetMeta", "Set Metadata", "{target}.set_meta({name}, {value})", "Metadata", "set meta {name} = {value}", "Stores a custom named value on an object as hidden metadata.").param("target", "self", "Target", "Object to tag.", "expression").param("name", "\"key\"", "Name", "Metadata key.", "expression").param("value", "0", "Value", "Value to store.", "expression"))
	descriptors.append(F.expr("GetMeta", "Get Metadata", "{target}.get_meta({name})", "Metadata", "meta {name}", "Returns a custom metadata value previously stored on an object.").param("target", "self", "Target", "Object to read.", "expression").param("name", "\"key\"", "Name", "Metadata key.", "expression"))
	descriptors.append(F.cond("HasMeta", "Has Metadata", "{target}.has_meta({name})", "Metadata", "has meta {name}", "True when the object has metadata stored under the given key.").param("target", "self", "Target", "Object to test.", "expression").param("name", "\"key\"", "Name", "Metadata key.", "expression"))
	descriptors.append(F.act("RemoveMeta", "Remove Metadata", "{target}.remove_meta({name})", "Metadata", "remove meta {name}", "Deletes a stored metadata value from an object by its key.").param("target", "self", "Target", "Object to edit.", "expression").param("name", "\"key\"", "Name", "Metadata key.", "expression"))

	# ── Nodes: scene-tree navigation (parent / child / find / owner), the everyday tree queries ──
	descriptors.append(F.expr("GetParent", "Get Parent", "{target}.get_parent()", "Nodes", "[i]{target}[/i] parent", "Returns the node directly above this one in the scene tree.").param("target", "self", "Target", "Node whose parent to get.", "expression"))
	descriptors.append(F.expr("GetChildCount", "Get Child Count", "{target}.get_child_count()", "Nodes", "[i]{target}[/i] child count", "Returns how many direct children a node currently has.").param("target", "self", "Target", "Node whose children to count.", "expression"))
	descriptors.append(F.expr("GetChild", "Get Child (by index)", "{target}.get_child({index})", "Nodes", "[i]{target}[/i] child [b]{index}[/b]", "Returns a node's child at the given position number, starting from zero.").param("target", "self", "Target", "Parent node.", "expression").param("index", "0", "Index", "Child index (0-based).", "expression"))
	descriptors.append(F.expr("FindChild", "Find Child (by name)", "{target}.find_child({pattern})", "Nodes", "find [b]{pattern}[/b] in [i]{target}[/i]", "Returns a child node matching a name pattern, useful when paths vary.").param("target", "self", "Target", "Node to search under.", "expression").param("pattern", "\"Enemy*\"", "Pattern", "Name pattern (wildcards allowed).", "expression"))
	descriptors.append(F.expr("GetNodeOrNull", "Get Node Or Null", "{target}.get_node_or_null({path})", "Nodes", "[i]{target}[/i].[b]{path}[/b] or null", "Returns the node at a path, or nothing instead of erroring if missing.").param("target", "self", "Target", "Base node.", "expression").param("path", "\"Sprite2D\"", "Path", "Node path (returns null if missing).", "expression"))
	descriptors.append(F.cond("HasNode", "Has Node", "{target}.has_node({path})", "Nodes", "[i]{target}[/i] has [b]{path}[/b]", "True when a node exists at the given path under this one.").param("target", "self", "Target", "Base node.", "expression").param("path", "\"Sprite2D\"", "Path", "Node path to test.", "expression"))
	descriptors.append(F.expr("GetOwner", "Get Scene Owner", "{target}.owner", "Nodes", "[i]{target}[/i] owner", "Returns the scene that this node was saved as part of.").param("target", "self", "Target", "Node whose scene owner to get.", "expression"))
	# The write half of the read-only row above it. Get Scene Owner answers which scene a node was
	# saved as part of; this is how a node built while the game runs is given that answer, which is
	# the one thing that decides whether it is written out when the branch it sits in is packed.
	# Save Branch As Scene File is the wholesale cousin: it walks a whole branch setting the owner of
	# every part that has none, because packing a branch of nodes made at run time is exactly the case
	# where nothing has one. This row is that same assignment for the one node a reader means.
	descriptors.append(F.act("SetSceneOwner", "Set Scene Owner", "{target}.owner = {root}", "Nodes", "make [i]{target}[/i] part of [i]{root}[/i]", "Says which scene a node belongs to, which is what decides whether it is written out when that scene is packed and saved. A node built while the game runs has no owner at all, so a branch of them packs to an empty scene until this is set.").param("target", "self", "Target", "The node to give an owner to.", "expression").param("root", "get_tree().current_scene", "Owned By", "The node at the top of the scene it belongs to. That node has to be an ancestor of this one, or the assignment is refused.", "expression"))
	descriptors.append(F.cond("IsAncestorOf", "Is Ancestor Of", "{target}.is_ancestor_of({node})", "Nodes", "[i]{target}[/i] is ancestor of [i]{node}[/i]", "True when this node is somewhere above the other node in the tree.").param("target", "self", "Target", "Potential ancestor node.", "expression").param("node", "get_node(\"Child\")", "Node", "Node to test for descendancy.", "expression"))

	return descriptors
