# EventForge module - Device input (Keyboard/Mouse/Gamepad/Touch)
#
# Polling + event-scoped conditions; key params use the press-a-key capture hint.
# Module contract: see ace_factory.gd - ace_ids/templates are API (compatibility
# covenant); this file only changes where the descriptors are AUTHORED.
@tool
class_name EventForgeDeviceACEs
extends RefCounted

const F := preload("res://addons/eventforge/registration/ace_factory.gd")


static func get_descriptors() -> Array[ACEDescriptor]:
	var descriptors: Array[ACEDescriptor] = []

	# ── Device input (Keyboard/Mouse/Gamepad/Touch, Godot-style). Key params use
	# the press-a-key capture workflow (hint key_capture). Event-scoped conditions are
	# for On Input events, where `event` exists.
	descriptors.append(F.cond("KeyIsDown", "Key Is Down", "Input.is_physical_key_pressed({key})", "Keyboard", "Key {key} is down", "True while the given keyboard key is being held down.").param("key", "KEY_SPACE", "Key", "Press a key to capture it.", "key_capture"))
	descriptors.append(F.cond("KeyEventPressed", "On Key Pressed (event)", "(event is InputEventKey and event.pressed and not event.echo and event.physical_keycode == {key})", "Keyboard", "On {key} pressed", "True the moment a key is pressed, used inside an input event.").param("key", "KEY_SPACE", "Key", "Use inside an On Input event.", "key_capture"))
	descriptors.append(F.cond("KeyEventReleased", "On Key Released (event)", "(event is InputEventKey and not event.pressed and event.physical_keycode == {key})", "Keyboard", "On {key} released", "True the moment a key is released, used inside an input event.").param("key", "KEY_SPACE", "Key", "Use inside an On Input event.", "key_capture"))
	descriptors.append(F.cond("MouseButtonDown", "Mouse Button Is Down", "Input.is_mouse_button_pressed({button})", "Mouse", "{button} is down", "True while the given mouse button is being held down.").param_choice("button", "MOUSE_BUTTON_LEFT", "Button", "Mouse button.", ["MOUSE_BUTTON_LEFT", "MOUSE_BUTTON_RIGHT", "MOUSE_BUTTON_MIDDLE"]))
	descriptors.append(F.expr("GetMouseWorldPosition", "Mouse Position (world)", "get_global_mouse_position()", "Mouse", "mouse position", "Returns the mouse position in world coordinates, matching where things sit in the level.", "Node2D"))
	descriptors.append(F.expr("GetMouseScreenPosition", "Mouse Position (screen)", "get_viewport().get_mouse_position()", "Mouse", "mouse screen position", "Returns the mouse position in screen pixels relative to the window."))
	descriptors.append(F.act("SetMouseMode", "Set Mouse Mode", "Input.mouse_mode = {mode}", "Mouse", "Set mouse mode {mode}", "Changes whether the cursor is visible, hidden, or locked to the window.").param_choice("mode", "Input.MOUSE_MODE_VISIBLE", "Mode", "Cursor visibility/capture.", ["Input.MOUSE_MODE_VISIBLE", "Input.MOUSE_MODE_HIDDEN", "Input.MOUSE_MODE_CAPTURED", "Input.MOUSE_MODE_CONFINED"]))
	descriptors.append(F.cond("JoyButtonDown", "Gamepad Button Is Down", "Input.is_joy_button_pressed({device}, {button})", "Gamepad", "Gamepad {button} is down", "True while the given gamepad button is being held down.").param("device", "0", "Gamepad", "Device index (0 = first).", "expression").param_choice("button", "JOY_BUTTON_A", "Button", "Gamepad button.", ["JOY_BUTTON_A", "JOY_BUTTON_B", "JOY_BUTTON_X", "JOY_BUTTON_Y", "JOY_BUTTON_LEFT_SHOULDER", "JOY_BUTTON_RIGHT_SHOULDER", "JOY_BUTTON_START", "JOY_BUTTON_BACK", "JOY_BUTTON_DPAD_UP", "JOY_BUTTON_DPAD_DOWN", "JOY_BUTTON_DPAD_LEFT", "JOY_BUTTON_DPAD_RIGHT"]))
	descriptors.append(F.expr("GetJoyAxis", "Gamepad Axis", "Input.get_joy_axis({device}, {axis})", "Gamepad", "gamepad axis {axis}", "Returns how far a gamepad stick or trigger is pushed, from -1 to 1.").param("device", "0", "Gamepad", "Device index.", "expression").param_choice("axis", "JOY_AXIS_LEFT_X", "Axis", "Stick/trigger axis.", ["JOY_AXIS_LEFT_X", "JOY_AXIS_LEFT_Y", "JOY_AXIS_RIGHT_X", "JOY_AXIS_RIGHT_Y", "JOY_AXIS_TRIGGER_LEFT", "JOY_AXIS_TRIGGER_RIGHT"]))
	descriptors.append(F.cond("GamepadConnected", "Gamepad Is Connected", "Input.get_connected_joypads().has({device})", "Gamepad", "gamepad {device} connected", "True when a gamepad at the given device slot is plugged in.").param("device", "0", "Gamepad", "Device index.", "expression"))
	descriptors.append(F.act("StartJoyVibration", "Vibrate Gamepad", "Input.start_joy_vibration({device}, {weak}, {strong}, {duration})", "Gamepad", "Vibrate gamepad {duration}s", "Rumbles a connected gamepad at chosen strength for a set duration.").param("device", "0", "Gamepad", "Device index.", "expression").param("weak", "0.5", "Weak", "Weak motor 0..1.", "expression").param("strong", "0.5", "Strong", "Strong motor 0..1.", "expression").param("duration", "0.3", "Seconds", "Duration.", "expression"))
	# ── Mouse focus: the one-word capture/release pair (Set Mouse Mode is the parameterised
	# version; these are the verbs a sheet reads naturally).
	descriptors.append(F.act("CaptureMouse", "Capture Mouse", "Input.mouse_mode = Input.MOUSE_MODE_CAPTURED", "Mouse", "Capture the mouse", "Focuses the mouse into the window: the pointer locks and hides, and motion feeds your look/aim (FPS style). Release Mouse undoes it.").featured())
	descriptors.append(F.act("ReleaseMouse", "Release Mouse", "Input.mouse_mode = Input.MOUSE_MODE_VISIBLE", "Mouse", "Release the mouse", "Unfocuses the mouse: the pointer is visible and free again - pause menus, dialogs, quitting to the map."))
	# ── Mouse helpers beyond position/mode: pointer control, wheel + click events, cursor art.
	descriptors.append(F.expr("MouseMotionDelta", "Mouse Move Delta (event)", "event.relative", "Mouse", "mouse move delta", "How far the mouse moved THIS event (a Vector2 in pixels), used inside an On Input event - the raw aim delta while the mouse is captured."))
	descriptors.append(F.expr("MouseLocalPosition", "Mouse Position (local)", "get_local_mouse_position()", "Mouse", "mouse local position", "The mouse position relative to THIS node (its own coordinate space) - is the cursor inside me, and where?", "Node2D"))
	descriptors.append(F.expr("MouseRayOrigin", "Mouse Ray Origin (3D)", "get_viewport().get_camera_3d().project_ray_origin(get_viewport().get_mouse_position())", "Mouse", "mouse ray origin (3D)", "Where the cursor's picking ray starts in 3D world space (needs an active Camera3D) - pair with Mouse Ray Direction for click-to-select and click-to-move.", "Node3D"))
	descriptors.append(F.expr("MouseRayDirection", "Mouse Ray Direction (3D)", "get_viewport().get_camera_3d().project_ray_normal(get_viewport().get_mouse_position())", "Mouse", "mouse ray direction (3D)", "The direction the cursor's picking ray travels in 3D world space (needs an active Camera3D) - cast it with a raycast to find what the mouse is over.", "Node3D"))
	descriptors.append(F.act("WarpMouse", "Move Mouse Pointer", "Input.warp_mouse({position})", "Mouse", "Move mouse to {position}", "Teleports the mouse pointer to a window position - snap it to a menu item or re-centre after a cutscene.").param("position", "Vector2(100, 100)", "Position", "Window position in pixels to move the pointer to.", "expression"))
	descriptors.append(F.expr("GetMouseVelocity", "Mouse Velocity", "Input.get_last_mouse_velocity()", "Mouse", "mouse velocity", "How fast the mouse is moving (a Vector2 in pixels per second) - flick gestures, aim sway, spin-the-wheel minigames."))
	descriptors.append(F.cond("IsMouseCaptured", "Mouse Is Captured", "Input.mouse_mode == Input.MOUSE_MODE_CAPTURED", "Mouse", "mouse is captured", "True while the cursor is locked to the window (the FPS look mode) - gate pause menus and hints on it."))
	descriptors.append(F.cond("MouseButtonEventPressed", "On Mouse Button Pressed (event)", "(event is InputEventMouseButton and event.pressed and event.button_index == {button})", "Mouse", "On {button} pressed", "True the moment a mouse button goes down, used inside an On Input event (the click-y partner of Mouse Button Is Down).").param_choice("button", "MOUSE_BUTTON_LEFT", "Button", "Mouse button.", ["MOUSE_BUTTON_LEFT", "MOUSE_BUTTON_RIGHT", "MOUSE_BUTTON_MIDDLE"]))
	descriptors.append(F.cond("MouseButtonEventReleased", "On Mouse Button Released (event)", "(event is InputEventMouseButton and not event.pressed and event.button_index == {button})", "Mouse", "On {button} released", "True the moment a mouse button is let go, used inside an On Input event.").param_choice("button", "MOUSE_BUTTON_LEFT", "Button", "Mouse button.", ["MOUSE_BUTTON_LEFT", "MOUSE_BUTTON_RIGHT", "MOUSE_BUTTON_MIDDLE"]))
	descriptors.append(F.cond("MouseWheelUpEvent", "On Mouse Wheel Up (event)", "(event is InputEventMouseButton and event.pressed and event.button_index == MOUSE_BUTTON_WHEEL_UP)", "Mouse", "On mouse wheel up", "True on a wheel-up tick, used inside an On Input event - zoom in, next weapon, scroll a list."))
	descriptors.append(F.cond("MouseWheelDownEvent", "On Mouse Wheel Down (event)", "(event is InputEventMouseButton and event.pressed and event.button_index == MOUSE_BUTTON_WHEEL_DOWN)", "Mouse", "On mouse wheel down", "True on a wheel-down tick, used inside an On Input event."))
	descriptors.append(F.act("SetCustomCursor", "Set Custom Cursor", "Input.set_custom_mouse_cursor(load({image_path}))", "Mouse", "Set cursor to {image_path}", "Swaps the mouse pointer for your own image - a crosshair, a sword, a hand.").param("image_path", "\"res://cursor.png\"", "Image", "Path to the cursor image (png).", "expression"))
	descriptors.append(F.act("ClearCustomCursor", "Clear Custom Cursor", "Input.set_custom_mouse_cursor(null)", "Mouse", "Clear custom cursor", "Restores the system's normal mouse pointer."))

	# ── Keyboard helpers for options menus and rebind screens.
	descriptors.append(F.cond("IsAnythingPressed", "Anything Is Pressed", "Input.is_anything_pressed()", "Keyboard", "any input is pressed", "True while ANY key, mouse button, or gamepad input is held - press-any-key screens and idle detection."))
	descriptors.append(F.expr("KeyName", "Key Name", "OS.get_keycode_string({key})", "Keyboard", "name of key {key}", "The readable name of a key (\"Space\", \"Escape\") - show current bindings on a rebind screen.").param("key", "KEY_SPACE", "Key", "Press a key to capture it.", "key_capture"))
	descriptors.append(F.expr("KeycodeFromName", "Keycode From Name", "OS.find_keycode_from_string({name})", "Keyboard", "keycode of {name}", "The keycode for a key name - turn saved binding text back into a key.").param("name", "\"Space\"", "Name", "A key name like \"Space\" or \"A\".", "expression"))

	# ── Gamepad helpers for detection and UI.
	descriptors.append(F.expr("GamepadCount", "Gamepad Count", "Input.get_connected_joypads().size()", "Gamepad", "connected gamepad count", "How many gamepads are plugged in - local-multiplayer joins and control-hint switching."))
	descriptors.append(F.expr("GamepadName", "Gamepad Name", "Input.get_joy_name({device})", "Gamepad", "gamepad {device} name", "The connected gamepad's product name (\"Xbox Series Controller\") - show the right button glyphs.").param("device", "0", "Gamepad", "Device index (0 = first).", "expression"))
	descriptors.append(F.cond("GamepadIsKnown", "Gamepad Is Recognized", "Input.is_joy_known({device})", "Gamepad", "gamepad {device} is recognized", "True when the gamepad matches a known mapping (its buttons mean what you expect).").param("device", "0", "Gamepad", "Device index.", "expression"))
	descriptors.append(F.cond("JoyButtonEventPressed", "On Gamepad Button Pressed (event)", "(event is InputEventJoypadButton and event.pressed and event.button_index == {button})", "Gamepad", "On gamepad {button} pressed", "True the moment a gamepad button goes down, used inside an On Input event.").param_choice("button", "JOY_BUTTON_A", "Button", "Gamepad button.", ["JOY_BUTTON_A", "JOY_BUTTON_B", "JOY_BUTTON_X", "JOY_BUTTON_Y", "JOY_BUTTON_LEFT_SHOULDER", "JOY_BUTTON_RIGHT_SHOULDER", "JOY_BUTTON_START", "JOY_BUTTON_BACK", "JOY_BUTTON_DPAD_UP", "JOY_BUTTON_DPAD_DOWN", "JOY_BUTTON_DPAD_LEFT", "JOY_BUTTON_DPAD_RIGHT"]))

	descriptors.append(F.cond("IsTouchscreen", "Touchscreen Available", "DisplayServer.is_touchscreen_available()", "Touch", "device has a touchscreen", "True when the device running the game has a touchscreen."))
	descriptors.append(F.cond("TouchEventPressed", "On Touch (event)", "(event is InputEventScreenTouch and event.pressed)", "Touch", "On touch", "True the moment a finger touches the screen, used inside an input event."))
	descriptors.append(F.cond("TouchEventReleased", "On Touch Released (event)", "(event is InputEventScreenTouch and not event.pressed)", "Touch", "On touch released", "True the moment a finger lifts off the screen, used inside an input event."))
	descriptors.append(F.expr("GetTouchPosition", "Touch Position (event)", "event.position", "Touch", "touch position", "Returns the screen position of a touch from the current input event."))

	# Runtime input remapping (settings-menu rebinding). Capture an event in On Input (the
	# in-scope `event`), Erase then Add to rebind - two visual steps, no multi-statement
	# template. The action param reuses the InputMap dropdown like the polling ACEs above.
	descriptors.append(F.act("ActionAddEvent", "Bind Event To Action", "InputMap.action_add_event(&{action}, {event})", "InputMap", "Bind {event} to {action}", "Binds a new key, button, or input to a named action at runtime, for remapping.").param_built(F.make_param("action", "String", F.default_input_action(), "Action", "Input action to bind to.", "input_action", F.input_action_options())).param("event", "event", "Event", "InputEvent to add (e.g. the captured `event`).", "expression"))
	descriptors.append(F.act("ActionEraseEvents", "Clear Action Bindings", "InputMap.action_erase_events(&{action})", "InputMap", "Clear bindings for {action}", "Removes all key and button bindings from a named input action.").param_built(F.make_param("action", "String", F.default_input_action(), "Action", "Input action to clear.", "input_action", F.input_action_options())))
	descriptors.append(F.cond("ActionHasEvents", "Action Is Bound", "not InputMap.action_get_events(&{action}).is_empty()", "InputMap", "{action} is bound", "True when the named input action has at least one key or button bound.").param_built(F.make_param("action", "String", F.default_input_action(), "Action", "Input action to test.", "input_action", F.input_action_options())))
	descriptors.append(F.expr("ActionEventCount", "Action Binding Count", "InputMap.action_get_events(&{action}).size()", "InputMap", "{action} binding count", "Returns how many keys or buttons are bound to a named action.").param_built(F.make_param("action", "String", F.default_input_action(), "Action", "Input action.", "input_action", F.input_action_options())))
	descriptors.append(F.cond("EventMatchesAction", "Event Matches Action", "{event}.is_action(&{action})", "InputMap", "{event} matches {action}", "True when an input event matches the named action, like checking for jump.").param("event", "event", "Event", "InputEvent to test.", "expression").param_built(F.make_param("action", "String", F.default_input_action(), "Action", "Input action.", "input_action", F.input_action_options())))
	descriptors.append(F.expr("EventAsText", "Event As Text", "{event}.as_text()", "InputMap", "{event} as text", "Returns a readable label for an input event, like Space or Left Mouse.").param("event", "event", "Event", "InputEvent to describe.", "expression"))

	return descriptors
