# EventForge module - Node manipulation + picking (build, rearrange, and select scene-tree nodes).
#
# The everyday scene-tree operations: parent/reorder/free/rename nodes, and PICK nodes (children,
# by name pattern, or by group) so common tree work never forces a drop to GDScript. Complements
# the Nodes navigation set in dev_aces (Get Parent / Child / Find Child …) and the Groups set.
# Each compiles to the exact native call. Grouped under Nodes / Nodes: Picking.
@tool
class_name EventForgeNodeACEs
extends RefCounted

const F := preload("res://addons/eventforge/registration/ace_factory.gd")


static func get_descriptors() -> Array[ACEDescriptor]:
	var descriptors: Array[ACEDescriptor] = []

	# ── Nodes: manipulation (build + rearrange the tree at runtime; act on self or a {target}) ──
	descriptors.append(F.act("AddChild", "Add Child", "add_child({node})", "Nodes", "add child [i]{node}[/i]", "Attaches another node as a child of this one at runtime, e.g. spawning a bullet.").param("node", "Node.new()", "Node", "Node to add as a child of this node.", "expression"))
	descriptors.append(F.act("RemoveChild", "Remove Child", "remove_child({node})", "Nodes", "remove child [i]{node}[/i]", "Detaches a child node from this one without deleting it, so you can reattach it later.").param("node", "get_child(0)", "Node", "Child to detach (by index here - no hardcoded name; pick one or use a scene-unique node). Not freed.", "expression"))
	# ── The Hierarchy: moving an EXISTING node between parents ────────────────────────────────────
	# Add Child above builds a NEW node under this one. These move a node that is already in the
	# layout, and they say the one thing that decides whether it lands where the mover expected: does
	# it keep the place it had in the world, or snap to its new parent? Godot spells that as
	# `reparent`'s second argument, which is why these rows emit exactly that call - and why the
	# same call typed by hand reads as the same row.
	descriptors.append(F.act("HierarchyAddChild", "Add Child (existing node)", "{child}.reparent({parent}{, keep})", "Nodes: Hierarchy", "add child [i]{child}[/i] to [i]{parent}[/i]", "Moves a node that is already in the layout under a new parent - picking an item up into a hand, mounting a rider on a saddle, holstering a weapon on a back. Keeping its place leaves it exactly where it looks; snapping to it puts it at the parent's own spot.").param("child", "get_child(0)", "Child", "The node that becomes a child. It keeps everything it is - only its parent changes.", "scene_node").param("parent", "self", "Parent", "The node it goes under.", "scene_node").param_choice("keep", "", "Its place", "Whether the child stays where it is in the world, or snaps to its new parent.", [{"key": "", "label": "keeping its place"}, {"key": "false", "label": "snapping to it"}]))
	descriptors.append(F.act("HierarchyRemoveFromParent", "Remove From Parent", "{child}.reparent(get_tree().current_scene)", "Nodes: Hierarchy", "remove [i]{child}[/i] from its parent", "Takes a node off whatever it is under and puts it back at the top of the layout, keeping the place it has in the world - dropping a carried item, dismounting a rider. The node is not freed and nothing else about it changes.").param("child", "self", "Child", "The node to take off its parent. It stays in the layout, at the top level.", "scene_node"))
	descriptors.append(F.act("SetIgnoreParentMovement", "Set Ignore Parent's Movement", "{target}.top_level = {ignore}", "Nodes: Hierarchy", "set ignore parent's movement [b]{ignore}[/b] on [i]{target}[/i]", "Stops a child moving, turning and scaling with its parent while leaving it a child in every other way - it is still freed with the parent and still picked as one of its children. The answer for a muzzle flash that should not swing with the gun, or a health bar that should not tilt with the enemy.").param("target", "self", "On", "The child that should stop (or start) following its parent.", "scene_node").param_choice("ignore", "true", "Ignore", "On: the child stays where it is when the parent moves.", [{"key": "true", "label": "on"}, {"key": "false", "label": "off"}]))
	descriptors.append(F.act("CopyPlaceTo", "Copy Place To", "{follower}.remote_path = NodePath({path})", "Nodes: Hierarchy", "copy [i]{follower}[/i] place to [b]{path}[/b]", "Points a RemoteTransform at the node it should drive, so that node follows this one without being its child at all. Which parts follow - position, angle, size - are the RemoteTransform's own switches.").param("follower", "$RemoteTransform2D", "Follower", "The RemoteTransform2D / RemoteTransform3D doing the copying.", "scene_node").param("path", "\"../Target\"", "To", "Path to the node its place is copied onto.", "expression"))
	descriptors.append(F.act("StopCopyingPlace", "Stop Copying Place", "{follower}.remote_path = NodePath(\"\")", "Nodes: Hierarchy", "stop [i]{follower}[/i] copying", "Clears a RemoteTransform's target, so whatever it was driving stops following immediately. The node it drove keeps the place it had.").param("follower", "$RemoteTransform2D", "Follower", "The RemoteTransform2D / RemoteTransform3D to switch off.", "scene_node"))
	# The loop over ANOTHER object's children, as the picking row a squad heal, an inventory sweep or
	# a socket check is written with. Emits the plain `for child in target.get_children():` a reader
	# would have typed, which is why the typed line reads as this row.
	descriptors.append(F.cond("ForEachChildOf", "For Each Child", "{target}.get_children()", "Nodes: Hierarchy", "for each child of [i]{target}[/i]", "Runs this event's actions once per direct child of a node - healing a squad, totting up an inventory, checking every socket. Read the current one as `child`. Children added while it runs are not visited by this pass.").param("target", "self", "Of", "The node whose children the actions run once for.", "scene_node").looping("child"))
	descriptors.append(F.act("MoveChild", "Move Child To Index", "move_child({node}, {index})", "Nodes", "move [i]{node}[/i] to index [b]{index}[/b]", "Reorders a child to a new sibling index, changing its draw and process order.").param("node", "get_child(0)", "Node", "Child to reorder (by index here - no hardcoded name; pick one or use a scene-unique node).", "expression").param("index", "0", "Index", "New sibling index (draw / process order).", "expression"))
	descriptors.append(F.act("QueueFreeNode", "Free Node", "{target}.queue_free()", "Nodes", "free [i]{target}[/i]", "Safely deletes a node at the end of the frame, e.g. removing a dead enemy.").param("target", "self", "Target", "Node to free at the end of the frame.", "expression"))
	descriptors.append(F.act("SetNodeName", "Set Node Name", "{target}.name = {name}", "Nodes", "rename [i]{target}[/i] to [b]{name}[/b]", "Renames a node at runtime, handy for tracking or finding it later.").param("target", "self", "Target", "Node to rename.", "expression").param("name", "\"Renamed\"", "Name", "New node name.", "expression"))
	descriptors.append(F.expr("DuplicateNode", "Duplicate Node", "{target}.duplicate()", "Nodes", "duplicate [i]{target}[/i]", "Clones a node so you can add the copy elsewhere, e.g. mass-spawning identical objects.").param("target", "self", "Target", "Node to clone (add the clone with Add Child).", "expression"))
	# The copy with the three questions asked out loud. Duplicate Node above is Godot's own default -
	# signals, groups and scripts all come along - and that default is right often enough that it
	# stays exactly as it is. This one is for the times it is not: a pooled copy that must NOT inherit
	# the original's connections, a template node cloned without its script. Each box is one of the
	# engine's own duplicate flags, and the emitted line spells them by name rather than as the number
	# they add up to, so the copy a reader asked for is legible in the file afterwards. A flag is turned
	# on by MULTIPLYING it by its box rather than by a conditional, which matters for a reason that is
	# not about the code at all: a conditional inside a parameter is read by the sheet as the branch it
	# is and unfolds into if/else rows, so the row a reader dropped would stop looking like one row.
	descriptors.append(F.expr("DuplicateNodeChoosing", "Duplicate Node (choosing)", "{target}.duplicate(Node.DUPLICATE_SIGNALS * int({signals}) | Node.DUPLICATE_GROUPS * int({groups}) | Node.DUPLICATE_SCRIPTS * int({scripts}))", "Nodes", "duplicate [i]{target}[/i] ( signals [b]{signals}[/b], groups [b]{groups}[/b], scripts [b]{scripts}[/b] )", "Clones a node, choosing which of the three things a copy usually inherits come with it: its signal connections, its groups and its scripts. All three on is exactly what plain Duplicate Node does, so reach for this one only when the answer to one of them is no.").param("target", "self", "Target", "Node to clone (add the clone with Add Child).", "expression").param_typed("bool", "signals", "true", "Signals", "Copy the connections the original makes to other nodes. Off for a pooled copy that should wire itself up.").param_typed("bool", "groups", "true", "Groups", "Copy the groups the original belongs to. Off when the copy is not one of them yet.").param_typed("bool", "scripts", "true", "Scripts", "Copy the scripts on the original and its children. Off when the copy is meant to be plain nodes."))
	descriptors.append(F.expr("GetNodeName", "Node Name", "{target}.name", "Nodes", "[i]{target}[/i] name", "Returns the node's name as text, useful for labels or matching.").param("target", "self", "Target", "Node to read the name of.", "expression"))
	descriptors.append(F.expr("GetNodePath", "Node Path", "{target}.get_path()", "Nodes", "[i]{target}[/i] path", "Returns the node's full path in the scene tree as a reference.").param("target", "self", "Target", "Node to read its scene-tree path.", "expression"))
	descriptors.append(F.expr("GetIndexInParent", "Index In Parent", "{target}.get_index()", "Nodes", "[i]{target}[/i] index", "Returns the node's position among its siblings as a number.").param("target", "self", "Target", "Node to read its sibling index.", "expression"))
	descriptors.append(F.cond("IsInsideTree", "Is Inside Tree", "{target}.is_inside_tree()", "Nodes", "[i]{target}[/i] is inside tree", "True when the node is currently part of the active scene tree.").param("target", "self", "Target", "Node to test for scene-tree membership.", "expression"))
	descriptors.append(F.expr("GetSceneRoot", "Current Scene Root", "get_tree().current_scene", "Nodes", "current scene root", "Returns the root node of the currently running scene."))

	# ── Nodes: Picking - find / select nodes (children, by name pattern, by group) ──
	descriptors.append(F.expr("GetChildren", "Get Children", "{target}.get_children()", "Nodes: Picking", "[i]{target}[/i] children", "Returns the list of a node's direct children to loop over or pick from.").param("target", "self", "Target", "Node whose direct children to list.", "expression"))
	descriptors.append(F.expr("FindChildrenByPattern", "Find Children (by name)", "{target}.find_children({pattern}, \"\", true, false)", "Nodes: Picking", "find [b]{pattern}[/b] in [i]{target}[/i]", "Returns all descendant nodes whose name matches a pattern, wildcards allowed.").param("target", "self", "Target", "Node to search beneath.", "expression").param("pattern", "\"Enemy*\"", "Pattern", "Name pattern (wildcards allowed).", "expression"))
	# By TYPE - the answer to Godot's node-heavy objects: reach "the AnimationPlayer / Area2D / Sprite2D of
	# this object" WITHOUT a brittle deep path ($A/B/C/D) or a GDScript block. find_children("*", Type,
	# recursive=true, owned=false) walks the whole subtree by class. Pairs with For Each (Find Children Of
	# Type), With-node / expressions (First Child Of Type), and gating (Has Child Of Type).
	descriptors.append(F.expr("FindChildrenOfType", "Find Children Of Type", "{target}.find_children(\"*\", {type}, true, false)", "Nodes: Picking", "[b]{type}[/b] nodes in [i]{target}[/i]", "Returns all descendant nodes of a given class, e.g. every Area2D beneath this one.").param("target", "self", "Target", "Node to search beneath.", "expression").param("type", "\"AnimationPlayer\"", "Type", "Node class name to find - AnimationPlayer, Area2D, Sprite2D, … (every descendant of that type).", "expression"))
	descriptors.append(F.expr("FirstChildOfType", "First Child Of Type", "{target}.find_children(\"*\", {type}, true, false).pop_front()", "Nodes: Picking", "first [b]{type}[/b] in [i]{target}[/i]", "Returns the first descendant node of a given class, or nothing if none exist.").param("target", "self", "Target", "Node to search beneath.", "expression").param("type", "\"AnimationPlayer\"", "Type", "Node class name to find - the first match in the subtree (null if none; pop_front is null-safe on empty).", "expression"))
	descriptors.append(F.cond("HasChildOfType", "Has Child Of Type", "not {target}.find_children(\"*\", {type}, true, false).is_empty()", "Nodes: Picking", "[i]{target}[/i] has a [b]{type}[/b]", "True when at least one descendant node of the given class exists beneath this node.").param("target", "self", "Target", "Node to search beneath.", "expression").param("type", "\"Area2D\"", "Type", "Node class name to test for anywhere in the subtree.", "expression"))

	# ── Object-level component verbs (the object-level mental model: act on the OBJECT, not its deep node) ──
	# The animation ACEs above this file's peers are host-scoped to the AnimationPlayer/AnimatedSprite2D, so
	# they force you to TARGET that deep child by path. These take the object and AUTO-RESOLVE its player by
	# type, so "Play Animation walk on Player" needs no path and no GDScript block. Null-safe (guarded) and
	# collision-safe (the {uid}-baked temp var is unique per row, exactly like the audio Play Sound ACEs).
	descriptors.append(F.act("PlayAnimationInObject", "Play Animation (in object)", "var __ap_{uid} := {target}.find_children(\"*\", \"AnimationPlayer\", true, false).pop_front() as AnimationPlayer\nif __ap_{uid}:\n\t__ap_{uid}.play(&{anim})", "Animation", "play animation [b]{anim}[/b] in [i]{target}[/i]", "Plays a named animation by auto-finding the object's AnimationPlayer for you.").param("target", "self", "Target", "The OBJECT (its AnimationPlayer is found automatically anywhere beneath it).", "expression").param("anim", "\"idle\"", "Animation", "Name of the animation to play."))
	descriptors.append(F.act("StopAnimationInObject", "Stop Animation (in object)", "var __ap_{uid} := {target}.find_children(\"*\", \"AnimationPlayer\", true, false).pop_front() as AnimationPlayer\nif __ap_{uid}:\n\t__ap_{uid}.stop()", "Animation", "stop animation in [i]{target}[/i]", "Stops the object's animation by auto-finding its AnimationPlayer.").param("target", "self", "Target", "The OBJECT whose AnimationPlayer to stop (found automatically).", "expression"))
	descriptors.append(F.act("PlaySpriteAnimationInObject", "Play Sprite Animation (in object)", "var __as_{uid} := {target}.find_children(\"*\", \"AnimatedSprite2D\", true, false).pop_front() as AnimatedSprite2D\nif __as_{uid}:\n\t__as_{uid}.play(&{anim})", "Animation", "play sprite animation [b]{anim}[/b] in [i]{target}[/i]", "Plays a named sprite animation via the object's AnimatedSprite2D, found automatically.").param("target", "self", "Target", "The OBJECT (its AnimatedSprite2D is found automatically).", "expression").param("anim", "\"default\"", "Animation", "Animation name."))
	descriptors.append(F.cond("IsObjectAnimating", "Is Animating (in object)", "{target}.find_children(\"*\", \"AnimationPlayer\", true, false).any(func(__p): return __p.is_playing())", "Animation", "[i]{target}[/i] is animating", "True when any AnimationPlayer beneath the object is currently playing.").param("target", "self", "Target", "The OBJECT to test - true if any AnimationPlayer beneath it is playing.", "expression"))
	# More object-level verbs (same auto-resolve-by-type pattern): the everyday sprite/effect ops a designer
	# expects on an object, without targeting the deep child by path or dropping to a GDScript block.
	descriptors.append(F.act("FlipSpriteInObject", "Flip Sprite (in object)", "var __as_{uid} := {target}.find_children(\"*\", \"AnimatedSprite2D\", true, false).pop_front() as AnimatedSprite2D\nif __as_{uid}:\n\t__as_{uid}.flip_h = {mirrored}", "Animation", "flip sprite [b]{mirrored}[/b] in [i]{target}[/i]", "Mirrors the object's sprite horizontally, e.g. flipping to face left or right.").param("target", "self", "Target", "The OBJECT (its AnimatedSprite2D is found automatically).", "expression").param_choice("mirrored", "true", "Mirrored", "Mirror the sprite horizontally (e.g. facing direction).", ["true", "false"]))
	descriptors.append(F.act("SetSpriteFrameInObject", "Set Sprite Frame (in object)", "var __as_{uid} := {target}.find_children(\"*\", \"AnimatedSprite2D\", true, false).pop_front() as AnimatedSprite2D\nif __as_{uid}:\n\t__as_{uid}.frame = {frame}", "Animation", "set sprite frame [b]{frame}[/b] in [i]{target}[/i]", "Shows a specific frame on the object's AnimatedSprite2D, found automatically.").param("target", "self", "Target", "The OBJECT (its AnimatedSprite2D is found automatically).", "expression").param("frame", "0", "Frame", "Frame index to show.", "expression"))
	descriptors.append(F.act("RestartAnimationInObject", "Restart Animation (in object)", "var __ap_{uid} := {target}.find_children(\"*\", \"AnimationPlayer\", true, false).pop_front() as AnimationPlayer\nif __ap_{uid}:\n\t__ap_{uid}.stop()\n\t__ap_{uid}.play(&{anim})", "Animation", "restart animation [b]{anim}[/b] in [i]{target}[/i]", "Replays a named animation from the very start, e.g. retriggering an attack.").param("target", "self", "Target", "The OBJECT (its AnimationPlayer is found automatically).", "expression").param("anim", "\"idle\"", "Animation", "Animation to (re)play from the start."))
	descriptors.append(F.act("EmitParticlesInObject", "Emit Particles (in object)", "var __pp_{uid} := {target}.find_children(\"*\", \"GPUParticles2D\", true, false).pop_front() as GPUParticles2D\nif __pp_{uid}:\n\t__pp_{uid}.emitting = {emitting}", "Effects", "set particles emitting [b]{emitting}[/b] in [i]{target}[/i]", "Turns the object's particle emitter on or off, found automatically.").param("target", "self", "Target", "The OBJECT (its GPUParticles2D is found automatically).", "expression").param_choice("emitting", "true", "Emitting", "Turn the particle emitter on or off.", ["true", "false"]))
	descriptors.append(F.expr("GetNodesInGroup", "Nodes In Group", "get_tree().get_nodes_in_group({group})", "Nodes: Picking", "nodes in group {group}", "Returns every node belonging to a named group to loop over or count.").param("group", "\"enemies\"", "Group", "Group name.", "group_reference"))
	descriptors.append(F.expr("GetRandomNodeInGroup", "Random Node In Group", "get_tree().get_nodes_in_group({group}).pick_random()", "Nodes: Picking", "random node in group {group}", "Returns a randomly chosen member of a named group, e.g. a random spawn point.").param("group", "\"enemies\"", "Group", "Group to pick a random member from.", "group_reference"))
	# Nearest / Furthest by distance from THIS node - the auto-attack / targeting primitives. reduce()
	# (Godot 4 Array has no min_by/max_by) over the group, comparing global_position.distance_to: one
	# template needs global_position, so these register for Node2D hosts (a 3D game can paste the same
	# reduce() into a GDScript block). Empty group → null.
	descriptors.append(F.expr("NearestInGroup", "Nearest Node In Group", "get_tree().get_nodes_in_group({group}).reduce(func(__acc, __n): return __n if __acc == null or global_position.distance_to(__n.global_position) < global_position.distance_to(__acc.global_position) else __acc, null)", "Nodes: Picking", "nearest node in group {group}", "Returns the closest member of a group to this node, e.g. the nearest enemy.", "Node2D").param("group", "\"enemies\"", "Group", "Group to pick the closest member of (by distance to this node). Returns null if the group is empty.", "group_reference"))
	descriptors.append(F.expr("FurthestInGroup", "Furthest Node In Group", "get_tree().get_nodes_in_group({group}).reduce(func(__acc, __n): return __n if __acc == null or global_position.distance_to(__n.global_position) > global_position.distance_to(__acc.global_position) else __acc, null)", "Nodes: Picking", "furthest node in group {group}", "Returns the farthest member of a group from this node by distance.", "Node2D").param("group", "\"enemies\"", "Group", "Group to pick the farthest member of (by distance to this node). Returns null if the group is empty.", "group_reference"))
	# The empty-safe sibling of Random Node In Group: Array.pick_random() ERRORS on an empty array, so
	# this one asks first and hands back nothing instead. Plain Node host - no distance math involved.
	descriptors.append(F.expr("RandomInGroup", "Random Node In Group (empty-safe)", "get_tree().get_nodes_in_group({group}).pick_random() if not get_tree().get_nodes_in_group({group}).is_empty() else null", "Nodes: Picking", "random node in group {group} (or nothing)", "Returns a random member of a group, or nothing at all when the group is empty.").param("group", "\"enemies\"", "Group", "Group to pick a random member from. Returns nothing when the group is empty (instead of erroring).", "group_reference"))
	# Pick by a PROPERTY rather than by distance: lowest health, highest score, cheapest item. Same
	# reduce() idiom (Godot 4 Array has no min_by/max_by); get() reads the named property off each
	# member, so any group of nodes that carries it works. Empty group → null.
	descriptors.append(F.expr("SmallestInGroup", "Group Member With Smallest Property", "get_tree().get_nodes_in_group({group}).reduce(func(__acc, __n): return __n if __acc == null or __n.get({property}) < __acc.get({property}) else __acc, null)", "Nodes: Picking", "group {group} member with smallest {property}", "Returns the group member whose named property is lowest, e.g. the weakest enemy.").param("group", "\"enemies\"", "Group", "Group to search. Returns nothing if the group is empty.", "group_reference").param("property", "\"hp\"", "Property", "Name of the property to compare, e.g. hp or score."))
	descriptors.append(F.expr("LargestInGroup", "Group Member With Largest Property", "get_tree().get_nodes_in_group({group}).reduce(func(__acc, __n): return __n if __acc == null or __n.get({property}) > __acc.get({property}) else __acc, null)", "Nodes: Picking", "group {group} member with largest {property}", "Returns the group member whose named property is highest, e.g. the toughest enemy.").param("group", "\"enemies\"", "Group", "Group to search. Returns nothing if the group is empty.", "group_reference").param("property", "\"hp\"", "Property", "Name of the property to compare, e.g. hp or score."))

	# ── 2D spatial patterns (the everyday distance / aim / screen-wrap / hover verbs) ──
	# Four things a 2D game asks for constantly and that otherwise force a GDScript block: "is that
	# thing close enough?", "aim at it over time", "come back on the other side", "hover in place".
	# All four register for Node2D hosts (they read global_position / position / the viewport rect).
	# The `other` / `target` defaults are get_parent() so the row stands on its own the moment it is
	# dropped - a bare identifier like `player` would not exist on a plain Node2D. The proximity test
	# is NODE-to-node (the point-to-point "Is Within Distance" under Vectors takes two positions).
	descriptors.append(F.cond("IsNodeWithinDistance", "Is Within Distance (of a node)", "global_position.distance_to({other}.global_position) <= maxf({distance}, 0.0)", "Movement", "is within {distance} px of {other}", "True when another node is closer than the given number of pixels. The proximity test behind prompts, pickups and aggro ranges - pick the node, type the pixels, no parentheses-math to write.", "Node2D").param("other", "get_parent()", "Of", "The other node.", "expression").param("distance", "64.0", "Distance", "In pixels.", "expression"))
	descriptors.append(F.act("TurnToward", "Turn Toward", "rotation = rotate_toward(rotation, ({target}.global_position - global_position).angle(), deg_to_rad(maxf({degrees_per_second}, 0.0)) * get_process_delta_time())", "Movement", "turn toward {target} at {degrees_per_second} deg/s", "Aims this node at another one, turning at a real speed instead of snapping - the turret and the chasing enemy. Frame-rate independent; for an instant snap, give it a huge turn speed.", "Node2D").param("target", "get_parent()", "Target", "Node to aim at.", "expression").param("degrees_per_second", "180.0", "Turn Speed", "Degrees per second.", "expression"))
	# Screen wrap: get_viewport_rect().size read once into a {uid} local (unique per row, baked by the
	# dock at apply time) so both axes share one measurement. The leading `var` line means this
	# template is never given an "On node" prefix - a self-verb, which is exactly right here.
	descriptors.append(F.act("WrapInsideScreen", "Wrap Inside The Screen", "var __wrap_size_{uid}: Vector2 = get_viewport_rect().size\nposition = Vector2(wrapf(position.x, 0.0, __wrap_size_{uid}.x), wrapf(position.y, 0.0, __wrap_size_{uid}.y))", "Movement", "wrap inside the screen", "The Asteroids rule: leave the right edge and come back on the left, off the top and back at the bottom. Nothing ever escapes the screen.", "Node2D"))
	# Bob: the resting height is remembered in node metadata on the first run (the stateless-state
	# trick the cooldown ACEs use), so the sine rides the position the node already had - no exported
	# var, no _ready wiring, and dropping the row anywhere just works.
	descriptors.append(F.act("BobUpAndDown", "Bob Up And Down", "if not has_meta(&\"__bob_base_{uid}\"):\n\tset_meta(&\"__bob_base_{uid}\", position.y)\nposition.y = float(get_meta(&\"__bob_base_{uid}\")) + sin(Time.get_ticks_msec() / 1000.0 * TAU / maxf({period}, 0.01)) * {height}", "Movement", "bob up and down {height} px every {period}s", "Floats the node gently up and down around wherever it was resting - pickups, idle hover, a breathing menu icon. No sin() to write; run it under a per-frame trigger.", "Node2D").param("height", "6.0", "Height", "Pixels above and below the resting point.", "expression").param("period", "2.0", "Period", "Seconds for one full bob.", "expression"))

	# ── 2D spatial patterns, second set (knockback, vacuum pickup, orbit) ──
	# The same rule as above: Node2D hosts, defaults that stand on their own (get_parent() exists on
	# every node in a scene), and node metadata for the little bit of state each one needs, so a row
	# works the moment it is dropped - no exported var, no _ready wiring.
	# Push / Apply is deliberately a PAIR: one row sets the impulse where the hit happens, one row
	# under a per-frame trigger spends it. That split is what makes knockback readable as two rows.
	descriptors.append(F.act("PushAwayFrom", "Push Away From", "set_meta(&\"__ef_push\", (global_position - {source}.global_position).normalized() * maxf({strength}, 0.0))", "Movement", "push away from {source} with strength {strength}", "Sets the impulse; pair with Apply Pushes under a per-frame trigger, which moves and decays it.", "Node2D").param("source", "get_parent()", "Away From", "Node to be pushed away from - the explosion, the attacker, the shove.", "expression").param("strength", "300.0", "Strength", "Pixels per second of starting push.", "expression"))
	# The spending half. exp(-friction * delta) is the frame-rate independent decay (multiplying by a
	# flat factor per frame ties the feel to the frame rate); the length check stops the leftover from
	# jittering forever. A leading `var` line keeps this off the "On node" prefix pass - a self-verb.
	descriptors.append(F.act("ApplyPushes", "Apply Pushes", "var __push_{uid}: Vector2 = get_meta(&\"__ef_push\", Vector2.ZERO)\nif __push_{uid}.length_squared() > 0.01:\n\tposition += __push_{uid} * get_process_delta_time()\n\tset_meta(&\"__ef_push\", __push_{uid} * exp(-maxf({friction}, 0.0) * get_process_delta_time()))", "Movement", "apply pushes ( friction {friction} )", "Knockback that decays honestly (the exp form, frame-rate independent) - one row under Every Frame.", "Node2D").param("friction", "8.0", "Friction", "How fast the push dies away; bigger stops sooner.", "expression"))
	descriptors.append(F.act("PullGroupToward", "Pull Group Toward", "for __pull_{uid}: Node in get_tree().get_nodes_in_group({group}):\n\tif __pull_{uid} is Node2D and (__pull_{uid} as Node2D).global_position.distance_to(global_position) <= maxf({radius}, 0.0):\n\t\t(__pull_{uid} as Node2D).global_position = (__pull_{uid} as Node2D).global_position.move_toward(global_position, maxf({speed}, 0.0) * get_process_delta_time())", "Movement", "pull group {group} toward me within {radius} px at {speed}/s", "The vacuum-pickup loop - coins fly to the player, one row.", "Node2D").param("group", "\"coins\"", "Group", "Group whose members get pulled in.", "group_reference").param("radius", "96.0", "Within", "Only members closer than this many pixels are pulled.", "expression").param("speed", "400.0", "Speed", "Pixels per second they travel toward this node.", "expression"))
	# Orbit keeps its angle in node metadata (Bob's resting-point trick) rather than deriving it from
	# the clock, so the speed can change mid-run without the node snapping to a new place on the ring.
	descriptors.append(F.act("OrbitAround", "Orbit Around", "var __orbit_{uid}: float = float(get_meta(&\"__orbit_{uid}\", 0.0)) + deg_to_rad({degrees_per_second}) * get_process_delta_time()\nset_meta(&\"__orbit_{uid}\", __orbit_{uid})\nglobal_position = {center}.global_position + Vector2(cos(__orbit_{uid}), sin(__orbit_{uid})) * maxf({radius}, 0.0)", "Movement", "orbit around {center} at radius {radius}, {degrees_per_second} deg/s", "Circles this node around another one - a shield satellite, a moon, a spinning hazard. Run it under a per-frame trigger.", "Node2D").param("center", "get_parent()", "Around", "Node to circle.", "expression").param("radius", "40.0", "Radius", "Pixels from the center of the circle.").param("degrees_per_second", "90.0", "Speed", "Degrees per second; negative orbits the other way."))


	# Pickups that come back: hide + stop sensing, wait, restore, and call reset() if the node
	# has one - the same wake seam the Object Pool and Checkpoint respawn use.
	descriptors.append(F.act("VanishRespawnIn", "Vanish, Respawn In", "visible = false\nif \"monitoring\" in self:\n\tset_deferred(&\"monitoring\", false)\nawait get_tree().create_timer(maxf({seconds}, 0.0)).timeout\nvisible = true\nif \"monitoring\" in self:\n\tset_deferred(&\"monitoring\", true)\nif has_method(&\"reset\"):\n\tcall(&\"reset\")", "Time", "vanish, respawn in {seconds}s", "Hides this pickup (and pauses its Area sensing when it has any), waits, then brings it back - calling its reset() if it defines one. The health-pack-respawns-in-10s pattern as one row; it awaits, so it suspends like Wait.", "CanvasItem").param("seconds", "10.0", "Seconds", "How long the pickup stays gone.", "expression"))
	# Distance with a CHOICE of geometry: the dropdown's key IS the index into five measures,
	# computed inline (all five are a handful of float ops) so the emitted line stays plain code
	# with zero helpers - the parity contract allows no runtime library.
	descriptors.append(F.cond("IsWithinDistanceMetric", "Is Within Distance (choose metric)", "([global_position.distance_to({other}.global_position), absf(global_position.x - {other}.global_position.x), absf(global_position.y - {other}.global_position.y), absf(global_position.x - {other}.global_position.x) + absf(global_position.y - {other}.global_position.y), maxf(absf(global_position.x - {other}.global_position.x), absf(global_position.y - {other}.global_position.y))][{metric}]) <= maxf({distance}, 0.0)", "Movement", "is within {distance} of {other}, measured as {metric}", "Is Within Distance with a geometry dropdown: straight line, horizontal or vertical only, grid steps (Manhattan), or king moves (Chebyshev) - one condition that fits platformers, roguelikes and strategy games alike.", "Node2D").param("other", "get_parent()", "Of", "The other node.", "expression").param("distance", "64.0", "Distance", "In pixels (or use Tiles(n)).", "expression").param_choice("metric", "0", "Measured As", "How the distance is counted - the platformer leash wants Horizontal only, the roguelike wants Grid steps.", [{"key": "0", "label": "Straight line"}, {"key": "1", "label": "Horizontal only"}, {"key": "2", "label": "Vertical only"}, {"key": "3", "label": "Grid steps"}, {"key": "4", "label": "King moves"}]))

	# ── Ask the tree: named services + capability lookup (the answer to the fragile node path) ──
	# A node publishes itself under a ROLE name ("player", "audio_director") and every other row asks
	# for that name instead of walking $../../. The shelf is metadata on the SceneTree itself, which
	# is the one object every node can reach and which dies with the run - no autoload, no singleton,
	# and nothing left over between two runs of the game. A name never answers with a freed node
	# because BOTH readers test is_instance_valid, which is also why registering deliberately hangs no
	# tree_exiting eraser on the node: a node that has already been replaced under its name would then
	# delete its replacement's live registration on the way out - the ordinary scene-reload order.
	descriptors.append(F.act("RegisterAsService", "Register As Service", "var __svc_{uid}: Dictionary = get_tree().get_meta(&\"__ef_services\", {})\n__svc_{uid}[{service_name}] = self\nget_tree().set_meta(&\"__ef_services\", __svc_{uid})", "Nodes", "register this as service [b]{service_name}[/b]", "Publishes this node under a short name anything can ask for, so no other row needs a path to it. Run it under On Ready. Registering the same name again replaces it, and a freed node answers as nothing at all, so a scene reload leaves no dangling reference behind.").param("service_name", "\"player\"", "Named", "A role, not a class - \"player\", \"audio_director\", \"wallet\". Registering the same name again replaces it.", "expression"))
	descriptors.append(F.expr("ServiceNamed", "Service Named", "(get_tree().get_meta(&\"__ef_services\", {}).get({service_name}, null) if is_instance_valid(get_tree().get_meta(&\"__ef_services\", {}).get({service_name}, null)) else null)", "Nodes", "service named [b]{service_name}[/b]", "The node published under a name, or nothing at all when nobody registered it or it has been freed. Drop it wherever a node is asked for - it never crashes and never needs a path.").param("service_name", "\"player\"", "Named", "The name the node registered itself under.", "expression"))
	descriptors.append(F.cond("HasService", "Has Service", "is_instance_valid(get_tree().get_meta(&\"__ef_services\", {}).get({service_name}, null))", "Nodes", "service [b]{service_name}[/b] exists", "True when a node is registered under this name and is still alive. Guard an optional system with it - a missing audio director then costs you a skipped row instead of a crash.").param("service_name", "\"audio_director\"", "Named", "The service name to test for.", "expression"))
	# The duck-typed seam as vocabulary: the shutdown sweep, the save sweep, the pause sweep. A loop
	# ROW (the actions run once per node), so nothing is hidden in an action's parameter.
	descriptors.append(F.cond("ForEachNodeThatCan", "For Each Node That Can", "([get_tree().get_root()] + Array(get_tree().get_root().find_children(\"*\", \"\", true, false))).filter(func(__can_{uid}): return __can_{uid}.has_method({method_name}))", "Nodes: Picking", "for each node that can [b]{method_name}[/b]", "Runs this event's actions once per node ANYWHERE in the tree that answers to a method name - the save sweep, the pause sweep, the shutdown sweep, with no list to keep in step. It walks the whole tree, so run it on an event, not every frame. Read the current one as `node`.").param("method_name", "\"save_state\"", "Answers To", "The method name a node must have to be picked up, e.g. save_state or on_game_paused.", "expression").looping("node"))

	# ── Later, once, and after this frame (Godot's oldest beginner trap as three readable rows) ──
	# None of these suspend, which is what separates them from Wait / Await Next Frame: a suspended
	# event cannot fix the crash it was reached from, and cannot coalesce anything.
	descriptors.append(F.act("DoAfterFrame", "Do After This Frame", "(func(): {do}).call_deferred()", "Time", "after this frame: [b]{do}[/b]", "Runs one action once the frame's physics and signal storm has finished, which is the only safe moment to add, free or reparent nodes. The number one crash a beginner hits is doing that from inside a collision callback; this is the fix, and the rows below it still run immediately.").param("do", "queue_free()", "Do", "The action to run once this frame's work is finished - the only safe moment to add, free or reparent a node.", "expression"))
	descriptors.append(F.act("CallLater", "Call Later", "get_tree().create_timer(maxf({seconds}, 0.0)).timeout.connect(func(): {do}, CONNECT_ONE_SHOT)", "Time", "call later ([b]{seconds}[/b]s): [b]{do}[/b]", "Runs one action after a delay, with no Timer node and WITHOUT suspending - the rows below it keep running. The connection is one-shot, so a delayed beat can neither leak nor fire twice. The readable form of the small follow-up: eject the shell, close the door, play the second thud.").param("seconds", "0.15", "After", "Seconds to wait before the action runs.", "expression").param("do", "queue_free()", "Do", "The action to run when the delay is up.", "expression"))
	descriptors.append(F.act("SetPropertyDeferred", "Set Property (after this frame)", "{target}.set_deferred({property}, {value})", "Time", "set [b]{property}[/b] of [i]{target}[/i] to [b]{value}[/b] after this frame", "Sets a property at the end of the frame instead of right now. The one Godot insists on for collision shapes and monitoring: flipping those mid-physics is the error every beginner meets, and deferring is the documented answer.").param("target", "self", "On", "Node whose property to set.", "expression").param("property", "\"visible\"", "Property", "Name of the property to set.").param("value", "true", "To", "The value to set it to.", "expression"))
	# A run-once QUESTION, so it guards actions rather than swallowing one into a parameter - the same
	# shape as the shipped Trigger Once and Only Once Ever, and evaluated last for the same reason.
	descriptors.append(F.cond("OnceThisFrame", "Only Once This Frame", "__once_frame_{uid}({key_id})", "Run Context", "only once this frame ( [b]{key_id}[/b] )", "True the FIRST time it is reached in a frame under this name, and false for every other time that frame - counting a physics tick as its own frame, so a row under On Physics Process is not folded in with the drawn frame around it. Fifty inventory changes then rebuild the panel once instead of fifty times. Give two rows the same name and they share one run per frame.").param("key_id", "\"rebuild_bag\"", "Named", "The gate's name. Every row using the same name folds into one run per frame.", "expression").stateful("var __once_frames_{uid}: Dictionary = {}\n\nfunc __once_frame_{uid}(key: String) -> bool:\n\tvar stamp: String = str(Engine.get_process_frames()) + \":\" + str(Engine.get_physics_frames())\n\tif str(__once_frames_{uid}.get(key, \"\")) == stamp:\n\t\treturn false\n\t__once_frames_{uid}[key] = stamp\n\treturn true").evaluated_last())
	return descriptors
