# EventForge module - raycasting vocabulary (2D and 3D)
#
# Godot casts rays four different ways, and a sheet can now reach all of them:
#   1. RayCast2D / RayCast3D nodes  - a persistent ray the physics server updates for you.
#   2. ShapeCast2D / ShapeCast3D    - the same idea with THICKNESS (a swept shape, not a hairline),
#                                     which reports every hit along the sweep, not just the first.
#   3. Direct space-state queries   - one-off casts from anywhere: intersect_ray (a ray), intersect_point
#                                     (a pinprick), intersect_shape (a volume), cast_motion (how far a
#                                     shape can travel before it hits).
#   4. Camera picking               - the screen-to-world ray under the mouse, for click-to-select in 3D.
#
# Two shapes of verb, deliberately:
#   - SINGLE-SHOT expressions ("World Raycast Point") read well in one cell but re-cast the ray on every
#     use, so asking for the point AND the collider costs two casts.
#   - CAST INTO A VARIABLE actions fire ONE cast and store the result Dictionary, which the "Ray Result …"
#     conditions and expressions then read for free. Reach for these whenever you want more than one
#     fact about the same hit.
#
# Module contract: see ace_factory.gd - ace_ids/templates are API (compatibility
# covenant); this file only changes where the descriptors are AUTHORED.
@tool
class_name EventForgeRaycastACEs
extends RefCounted

const F := preload("res://addons/eventforge/registration/ace_factory.gd")

const CAT_2D := "Raycast 2D"
const CAT_3D := "Raycast 3D"
const CAT_OVERLAP_3D := "Overlap 3D"


static func get_descriptors() -> Array[ACEDescriptor]:
	var descriptors: Array[ACEDescriptor] = []
	_add_raycast_node_2d(descriptors)
	_add_raycast_node_3d(descriptors)
	_add_shapecast_2d(descriptors)
	_add_shapecast_3d(descriptors)
	_add_world_queries_2d(descriptors)
	_add_world_queries_3d(descriptors)
	_add_ray_result_readers(descriptors)
	_add_camera_picking(descriptors)
	return descriptors


# ── 1. RayCast2D node: the existing vocabulary could only READ one. These aim and configure it,
# so a sheet can swing a ray around (melee arcs, ledge probes, aim assist) without any GDScript. ──
static func _add_raycast_node_2d(descriptors: Array[ACEDescriptor]) -> void:
	descriptors.append(F.make_descriptor("Core", "RayCast2DSetTarget", "Point RayCast At (2D)", ACEDescriptor.ACEType.ACTION, "target_position = {reach}", "", [F.make_param("reach", "String", "Vector2(0, 100)", "Target", "Where the ray reaches, RELATIVE to the RayCast2D node (its own local space) - not a world position.", "expression")], CAT_2D, "Point raycast at {reach}", "RayCast2D")
		.described("Aims the ray and sets how far it reaches. The target is measured from the raycast itself, so Vector2(0, 100) points 100 pixels down."))
	descriptors.append(F.make_descriptor("Core", "RayCast2DSetEnabled", "Enable RayCast (2D)", ACEDescriptor.ACEType.ACTION, "enabled = {on}", "", [F.make_param("on", "String", "true", "Enabled", "true to cast every physics frame, false to switch it off.", "", ["true", "false"])], CAT_2D, "Set raycast enabled to {on}", "RayCast2D")
		.described("Turns the ray on or off. A disabled raycast costs nothing and always reports no hit."))
	descriptors.append(F.make_descriptor("Core", "RayCast2DSetMask", "Set RayCast Mask (2D)", ACEDescriptor.ACEType.ACTION, "collision_mask = {mask}", "", [F.make_param("mask", "String", "1", "Mask", "Collision mask as a number - each layer is a bit, so layers 1 and 3 are 1 + 4 = 5.", "expression")], CAT_2D, "Set raycast mask to {mask}", "RayCast2D")
		.described("Chooses which collision layers the ray can see, all at once."))
	descriptors.append(F.make_descriptor("Core", "RayCast2DSetMaskLayer", "Set RayCast Mask Layer (2D)", ACEDescriptor.ACEType.ACTION, "set_collision_mask_value({layer}, {on})", "", [F.make_param("layer", "String", "1", "Layer", "Layer number, starting at 1.", "expression"), F.make_param("on", "String", "true", "Detect", "true to notice this layer, false to ignore it.", "", ["true", "false"])], CAT_2D, "Set raycast mask layer {layer} to {on}", "RayCast2D")
		.described("Switches ONE collision layer on or off for the ray, leaving the others alone - easier than working out the mask number."))
	descriptors.append(F.make_descriptor("Core", "RayCast2DAddException", "Ignore Node In RayCast (2D)", ACEDescriptor.ACEType.ACTION, "add_exception({node})", "", [F.make_param("node", "Node", "get_parent() as CollisionObject2D", "Node", "The physics body or area the ray should pass through. Must be a CollisionObject2D - a plain Node will not compile.", "expression")], CAT_2D, "Ignore {node} in raycast", "RayCast2D")
		.described("Makes the ray pass straight through one specific object - the usual way to stop a gun's ray hitting the shooter."))
	descriptors.append(F.make_descriptor("Core", "RayCast2DRemoveException", "Stop Ignoring Node In RayCast (2D)", ACEDescriptor.ACEType.ACTION, "remove_exception({node})", "", [F.make_param("node", "Node", "get_parent() as CollisionObject2D", "Node", "The object that should be hittable again. Must be a CollisionObject2D.", "expression")], CAT_2D, "Stop ignoring {node} in raycast", "RayCast2D")
		.described("Undoes Ignore Node In RayCast for one object, so the ray can hit it again."))
	descriptors.append(F.make_descriptor("Core", "RayCast2DClearExceptions", "Clear RayCast Exceptions (2D)", ACEDescriptor.ACEType.ACTION, "clear_exceptions()", "", [], CAT_2D, "Clear raycast exceptions", "RayCast2D")
		.described("Forgets every ignored object, so the ray hits everything on its mask again."))
	descriptors.append(F.make_descriptor("Core", "RayCast2DSetHitAreas", "RayCast Detects Areas (2D)", ACEDescriptor.ACEType.ACTION, "collide_with_areas = {on}", "", [F.make_param("on", "String", "true", "Detect Areas", "true to notice Area2D nodes.", "", ["true", "false"])], CAT_2D, "Set raycast detects areas to {on}", "RayCast2D")
		.described("Lets the ray notice Area2D nodes. Godot IGNORES areas by default, which is the usual reason a ray seems to miss a trigger zone."))
	descriptors.append(F.make_descriptor("Core", "RayCast2DSetHitBodies", "RayCast Detects Bodies (2D)", ACEDescriptor.ACEType.ACTION, "collide_with_bodies = {on}", "", [F.make_param("on", "String", "true", "Detect Bodies", "true to notice physics bodies.", "", ["true", "false"])], CAT_2D, "Set raycast detects bodies to {on}", "RayCast2D")
		.described("Lets the ray notice solid physics bodies (on by default). Turn it off for a ray that should only see trigger areas."))
	descriptors.append(F.make_descriptor("Core", "RayCast2DSetHitFromInside", "RayCast Hits From Inside (2D)", ACEDescriptor.ACEType.ACTION, "hit_from_inside = {on}", "", [F.make_param("on", "String", "true", "Hit From Inside", "true to report a shape the ray STARTS inside.", "", ["true", "false"])], CAT_2D, "Set raycast hits from inside to {on}", "RayCast2D")
		.described("Reports a hit even when the ray begins inside the shape. Off by default, which is why a ray starting inside a wall reads as clear."))
	descriptors.append(F.make_descriptor("Core", "RayCast2DSetExcludeParent", "RayCast Ignores Its Parent (2D)", ACEDescriptor.ACEType.ACTION, "exclude_parent = {on}", "", [F.make_param("on", "String", "true", "Ignore Parent", "true to pass through the body it hangs from.", "", ["true", "false"])], CAT_2D, "Set raycast ignores parent to {on}", "RayCast2D")
		.described("Passes through the body the raycast is parented to (on by default), so a character's own ray never hits the character."))
	descriptors.append(F.make_descriptor("Core", "RayCast2DHitsGroup", "RayCast Hits Group (2D)", ACEDescriptor.ACEType.CONDITION, "(is_colliding() and get_collider() != null and get_collider().is_in_group({group}))", "", [F.make_param("group", "String", "\"enemies\"", "Group", "Group name to test the hit object against.", "expression")], CAT_2D, "RayCast hits something in {group}", "RayCast2D")
		.described("True when the ray is hitting something that belongs to a group - \"did I shoot an enemy?\" in one cell."))
	descriptors.append(F.make_descriptor("Core", "RayCast2DColliderShape", "RayCast Hit Shape Index (2D)", ACEDescriptor.ACEType.EXPRESSION, "get_collider_shape()", "", [], CAT_2D, "raycast hit shape index", "RayCast2D")
		.described("Which of the hit object's collision shapes was struck, as an index - for bodies built from several shapes (a head shape versus a body shape)."))
	descriptors.append(F.make_descriptor("Core", "RayCast2DTarget", "RayCast Target (2D)", ACEDescriptor.ACEType.EXPRESSION, "target_position", "", [], CAT_2D, "raycast target", "RayCast2D")
		.described("Returns where the ray currently reaches, relative to the raycast node."))


# ── 2. RayCast3D node: the same aiming and configuring, plus the two options only 3D has
# (which triangle of a mesh was hit, and whether back faces count). ──
static func _add_raycast_node_3d(descriptors: Array[ACEDescriptor]) -> void:
	descriptors.append(F.make_descriptor("Core", "RayCast3DSetTarget", "Point RayCast At (3D)", ACEDescriptor.ACEType.ACTION, "target_position = {reach}", "", [F.make_param("reach", "String", "Vector3(0, 0, -10)", "Target", "Where the ray reaches, RELATIVE to the RayCast3D node (its own local space) - not a world position.", "expression")], CAT_3D, "Point raycast at {reach}", "RayCast3D")
		.described("Aims the ray and sets how far it reaches. The target is measured from the raycast itself, so Vector3(0, 0, -10) points 10 metres forward."))
	descriptors.append(F.make_descriptor("Core", "RayCast3DSetEnabled", "Enable RayCast (3D)", ACEDescriptor.ACEType.ACTION, "enabled = {on}", "", [F.make_param("on", "String", "true", "Enabled", "true to cast every physics frame, false to switch it off.", "", ["true", "false"])], CAT_3D, "Set raycast enabled to {on}", "RayCast3D")
		.described("Turns the ray on or off. A disabled raycast costs nothing and always reports no hit."))
	descriptors.append(F.make_descriptor("Core", "RayCast3DSetMask", "Set RayCast Mask (3D)", ACEDescriptor.ACEType.ACTION, "collision_mask = {mask}", "", [F.make_param("mask", "String", "1", "Mask", "Collision mask as a number - each layer is a bit, so layers 1 and 3 are 1 + 4 = 5.", "expression")], CAT_3D, "Set raycast mask to {mask}", "RayCast3D")
		.described("Chooses which collision layers the ray can see, all at once."))
	descriptors.append(F.make_descriptor("Core", "RayCast3DSetMaskLayer", "Set RayCast Mask Layer (3D)", ACEDescriptor.ACEType.ACTION, "set_collision_mask_value({layer}, {on})", "", [F.make_param("layer", "String", "1", "Layer", "Layer number, starting at 1.", "expression"), F.make_param("on", "String", "true", "Detect", "true to notice this layer, false to ignore it.", "", ["true", "false"])], CAT_3D, "Set raycast mask layer {layer} to {on}", "RayCast3D")
		.described("Switches ONE collision layer on or off for the ray, leaving the others alone - easier than working out the mask number."))
	descriptors.append(F.make_descriptor("Core", "RayCast3DAddException", "Ignore Node In RayCast (3D)", ACEDescriptor.ACEType.ACTION, "add_exception({node})", "", [F.make_param("node", "Node", "get_parent() as CollisionObject3D", "Node", "The physics body or area the ray should pass through. Must be a CollisionObject3D - a plain Node will not compile.", "expression")], CAT_3D, "Ignore {node} in raycast", "RayCast3D")
		.described("Makes the ray pass straight through one specific object - the usual way to stop a gun's ray hitting the shooter."))
	descriptors.append(F.make_descriptor("Core", "RayCast3DRemoveException", "Stop Ignoring Node In RayCast (3D)", ACEDescriptor.ACEType.ACTION, "remove_exception({node})", "", [F.make_param("node", "Node", "get_parent() as CollisionObject3D", "Node", "The object that should be hittable again. Must be a CollisionObject3D.", "expression")], CAT_3D, "Stop ignoring {node} in raycast", "RayCast3D")
		.described("Undoes Ignore Node In RayCast for one object, so the ray can hit it again."))
	descriptors.append(F.make_descriptor("Core", "RayCast3DClearExceptions", "Clear RayCast Exceptions (3D)", ACEDescriptor.ACEType.ACTION, "clear_exceptions()", "", [], CAT_3D, "Clear raycast exceptions", "RayCast3D")
		.described("Forgets every ignored object, so the ray hits everything on its mask again."))
	descriptors.append(F.make_descriptor("Core", "RayCast3DSetHitAreas", "RayCast Detects Areas (3D)", ACEDescriptor.ACEType.ACTION, "collide_with_areas = {on}", "", [F.make_param("on", "String", "true", "Detect Areas", "true to notice Area3D nodes.", "", ["true", "false"])], CAT_3D, "Set raycast detects areas to {on}", "RayCast3D")
		.described("Lets the ray notice Area3D nodes. Godot IGNORES areas by default, which is the usual reason a ray seems to miss a trigger zone."))
	descriptors.append(F.make_descriptor("Core", "RayCast3DSetHitBodies", "RayCast Detects Bodies (3D)", ACEDescriptor.ACEType.ACTION, "collide_with_bodies = {on}", "", [F.make_param("on", "String", "true", "Detect Bodies", "true to notice physics bodies.", "", ["true", "false"])], CAT_3D, "Set raycast detects bodies to {on}", "RayCast3D")
		.described("Lets the ray notice solid physics bodies (on by default). Turn it off for a ray that should only see trigger areas."))
	descriptors.append(F.make_descriptor("Core", "RayCast3DSetHitFromInside", "RayCast Hits From Inside (3D)", ACEDescriptor.ACEType.ACTION, "hit_from_inside = {on}", "", [F.make_param("on", "String", "true", "Hit From Inside", "true to report a shape the ray STARTS inside.", "", ["true", "false"])], CAT_3D, "Set raycast hits from inside to {on}", "RayCast3D")
		.described("Reports a hit even when the ray begins inside the shape. Off by default, which is why a ray starting inside geometry reads as clear."))
	descriptors.append(F.make_descriptor("Core", "RayCast3DSetHitBackFaces", "RayCast Hits Back Faces (3D)", ACEDescriptor.ACEType.ACTION, "hit_back_faces = {on}", "", [F.make_param("on", "String", "true", "Hit Back Faces", "true to hit the inside surface of concave collision shapes.", "", ["true", "false"])], CAT_3D, "Set raycast hits back faces to {on}", "RayCast3D")
		.described("Decides whether the ray hits a surface from behind - matters for concave level geometry, where the inside of a wall faces you."))
	descriptors.append(F.make_descriptor("Core", "RayCast3DSetExcludeParent", "RayCast Ignores Its Parent (3D)", ACEDescriptor.ACEType.ACTION, "exclude_parent = {on}", "", [F.make_param("on", "String", "true", "Ignore Parent", "true to pass through the body it hangs from.", "", ["true", "false"])], CAT_3D, "Set raycast ignores parent to {on}", "RayCast3D")
		.described("Passes through the body the raycast is parented to (on by default), so a character's own ray never hits the character."))
	descriptors.append(F.make_descriptor("Core", "RayCast3DHitsGroup", "RayCast Hits Group (3D)", ACEDescriptor.ACEType.CONDITION, "(is_colliding() and get_collider() != null and get_collider().is_in_group({group}))", "", [F.make_param("group", "String", "\"enemies\"", "Group", "Group name to test the hit object against.", "expression")], CAT_3D, "RayCast hits something in {group}", "RayCast3D")
		.described("True when the ray is hitting something that belongs to a group - \"did I shoot an enemy?\" in one cell."))
	descriptors.append(F.make_descriptor("Core", "RayCast3DColliderShape", "RayCast Hit Shape Index (3D)", ACEDescriptor.ACEType.EXPRESSION, "get_collider_shape()", "", [], CAT_3D, "raycast hit shape index", "RayCast3D")
		.described("Which of the hit object's collision shapes was struck, as an index - for bodies built from several shapes (a head shape versus a body shape)."))
	descriptors.append(F.make_descriptor("Core", "RayCast3DFaceIndex", "RayCast Hit Face Index (3D)", ACEDescriptor.ACEType.EXPRESSION, "get_collision_face_index()", "", [], CAT_3D, "raycast hit face index", "RayCast3D")
		.described("Which triangle of a concave mesh the ray hit, as an index (-1 for other shape types) - useful for reading per-face surface data."))
	descriptors.append(F.make_descriptor("Core", "RayCast3DTarget", "RayCast Target (3D)", ACEDescriptor.ACEType.EXPRESSION, "target_position", "", [], CAT_3D, "raycast target", "RayCast3D")
		.described("Returns where the ray currently reaches, relative to the raycast node."))


# ── 3. ShapeCast2D: a ray with THICKNESS. A hairline ray slips between fast-moving objects and
# through gaps; a swept shape does not, and it reports EVERY object along the sweep. ──
static func _add_shapecast_2d(descriptors: Array[ACEDescriptor]) -> void:
	descriptors.append(F.make_descriptor("Core", "ShapeCast2DIsColliding", "ShapeCast Is Colliding (2D)", ACEDescriptor.ACEType.CONDITION, "is_colliding()", "", [], CAT_2D, "ShapeCast is colliding", "ShapeCast2D")
		.described("True when the swept shape is touching anything along its path.").featured())
	descriptors.append(F.make_descriptor("Core", "ShapeCast2DForceUpdate", "Force ShapeCast Update (2D)", ACEDescriptor.ACEType.ACTION, "force_shapecast_update()", "", [], CAT_2D, "Force shapecast update", "ShapeCast2D")
		.described("Re-runs the sweep immediately instead of waiting for the next physics frame - do this after moving or re-aiming it in the same frame you read it."))
	descriptors.append(F.make_descriptor("Core", "ShapeCast2DSetTarget", "Point ShapeCast At (2D)", ACEDescriptor.ACEType.ACTION, "target_position = {reach}", "", [F.make_param("reach", "String", "Vector2(0, 100)", "Target", "How far and in which direction to sweep, RELATIVE to the ShapeCast2D node.", "expression")], CAT_2D, "Point shapecast at {reach}", "ShapeCast2D")
		.described("Aims the sweep and sets its length, measured from the shapecast itself."))
	descriptors.append(F.make_descriptor("Core", "ShapeCast2DSetEnabled", "Enable ShapeCast (2D)", ACEDescriptor.ACEType.ACTION, "enabled = {on}", "", [F.make_param("on", "String", "true", "Enabled", "true to sweep every physics frame.", "", ["true", "false"])], CAT_2D, "Set shapecast enabled to {on}", "ShapeCast2D")
		.described("Turns the sweep on or off."))
	descriptors.append(F.make_descriptor("Core", "ShapeCast2DCount", "ShapeCast Hit Count (2D)", ACEDescriptor.ACEType.EXPRESSION, "get_collision_count()", "", [], CAT_2D, "shapecast hit count", "ShapeCast2D")
		.described("How many objects the sweep is touching. Unlike a plain ray, a shapecast can report several at once."))
	descriptors.append(F.make_descriptor("Core", "ShapeCast2DColliderAt", "ShapeCast Collider At (2D)", ACEDescriptor.ACEType.EXPRESSION, "get_collider({index})", "", [F.make_param("index", "String", "0", "Index", "Which hit to read, starting at 0 (see ShapeCast Hit Count).", "expression")], CAT_2D, "shapecast collider at {index}", "ShapeCast2D")
		.described("Returns one of the objects the sweep is touching, by position in the hit list."))
	descriptors.append(F.make_descriptor("Core", "ShapeCast2DPointAt", "ShapeCast Hit Point At (2D)", ACEDescriptor.ACEType.EXPRESSION, "get_collision_point({index})", "", [F.make_param("index", "String", "0", "Index", "Which hit to read, starting at 0.", "expression")], CAT_2D, "shapecast hit point at {index}", "ShapeCast2D")
		.described("The world point where one of the sweep's hits touches."))
	descriptors.append(F.make_descriptor("Core", "ShapeCast2DNormalAt", "ShapeCast Hit Normal At (2D)", ACEDescriptor.ACEType.EXPRESSION, "get_collision_normal({index})", "", [F.make_param("index", "String", "0", "Index", "Which hit to read, starting at 0.", "expression")], CAT_2D, "shapecast hit normal at {index}", "ShapeCast2D")
		.described("The surface direction at one of the sweep's hits - bounce and slide maths start here."))
	descriptors.append(F.make_descriptor("Core", "ShapeCast2DSafeFraction", "ShapeCast Safe Fraction (2D)", ACEDescriptor.ACEType.EXPRESSION, "get_closest_collision_safe_fraction()", "", [], CAT_2D, "shapecast safe fraction", "ShapeCast2D")
		.described("How far along the sweep the shape can travel WITHOUT touching anything, from 0 (blocked immediately) to 1 (path is clear). Multiply the target by it to stop just short of the wall."))
	descriptors.append(F.make_descriptor("Core", "ShapeCast2DUnsafeFraction", "ShapeCast Unsafe Fraction (2D)", ACEDescriptor.ACEType.EXPRESSION, "get_closest_collision_unsafe_fraction()", "", [], CAT_2D, "shapecast unsafe fraction", "ShapeCast2D")
		.described("How far along the sweep the shape is first touching something, from 0 to 1 - the contact point to the safe fraction's stopping point."))
	descriptors.append(F.make_descriptor("Core", "ShapeCast2DSetMask", "Set ShapeCast Mask (2D)", ACEDescriptor.ACEType.ACTION, "collision_mask = {mask}", "", [F.make_param("mask", "String", "1", "Mask", "Collision mask as a number - each layer is a bit.", "expression")], CAT_2D, "Set shapecast mask to {mask}", "ShapeCast2D")
		.described("Chooses which collision layers the sweep can see."))
	descriptors.append(F.make_descriptor("Core", "ShapeCast2DSetMargin", "Set ShapeCast Margin (2D)", ACEDescriptor.ACEType.ACTION, "margin = {margin}", "", [F.make_param("margin", "String", "0.0", "Margin", "Extra padding around the shape, in pixels.", "expression")], CAT_2D, "Set shapecast margin to {margin}", "ShapeCast2D")
		.described("Pads the swept shape slightly. A small margin makes contact detection steadier when the shape slides along a surface."))
	descriptors.append(F.make_descriptor("Core", "ShapeCast2DSetMaxResults", "Set ShapeCast Max Results (2D)", ACEDescriptor.ACEType.ACTION, "max_results = {max_results}", "", [F.make_param("max_results", "String", "32", "Max Results", "Most hits to collect in one sweep.", "expression")], CAT_2D, "Set shapecast max results to {max_results}", "ShapeCast2D")
		.described("Caps how many objects one sweep will report, which bounds its cost in a crowd."))
	descriptors.append(F.make_descriptor("Core", "ShapeCast2DAddException", "Ignore Node In ShapeCast (2D)", ACEDescriptor.ACEType.ACTION, "add_exception({node})", "", [F.make_param("node", "Node", "get_parent() as CollisionObject2D", "Node", "The object the sweep should pass through. Must be a CollisionObject2D.", "expression")], CAT_2D, "Ignore {node} in shapecast", "ShapeCast2D")
		.described("Makes the sweep pass straight through one specific object."))
	descriptors.append(F.make_descriptor("Core", "ShapeCast2DClearExceptions", "Clear ShapeCast Exceptions (2D)", ACEDescriptor.ACEType.ACTION, "clear_exceptions()", "", [], CAT_2D, "Clear shapecast exceptions", "ShapeCast2D")
		.described("Forgets every ignored object, so the sweep hits everything on its mask again."))


# ── 4. ShapeCast3D: the same swept shape in three dimensions - the standard fix for a bullet
# that tunnels through a thin wall, and for a character probe that a hairline ray would thread. ──
static func _add_shapecast_3d(descriptors: Array[ACEDescriptor]) -> void:
	descriptors.append(F.make_descriptor("Core", "ShapeCast3DIsColliding", "ShapeCast Is Colliding (3D)", ACEDescriptor.ACEType.CONDITION, "is_colliding()", "", [], CAT_3D, "ShapeCast is colliding", "ShapeCast3D")
		.described("True when the swept shape is touching anything along its path.").featured())
	descriptors.append(F.make_descriptor("Core", "ShapeCast3DForceUpdate", "Force ShapeCast Update (3D)", ACEDescriptor.ACEType.ACTION, "force_shapecast_update()", "", [], CAT_3D, "Force shapecast update", "ShapeCast3D")
		.described("Re-runs the sweep immediately instead of waiting for the next physics frame - do this after moving or re-aiming it in the same frame you read it."))
	descriptors.append(F.make_descriptor("Core", "ShapeCast3DSetTarget", "Point ShapeCast At (3D)", ACEDescriptor.ACEType.ACTION, "target_position = {reach}", "", [F.make_param("reach", "String", "Vector3(0, 0, -10)", "Target", "How far and in which direction to sweep, RELATIVE to the ShapeCast3D node.", "expression")], CAT_3D, "Point shapecast at {reach}", "ShapeCast3D")
		.described("Aims the sweep and sets its length, measured from the shapecast itself."))
	descriptors.append(F.make_descriptor("Core", "ShapeCast3DSetEnabled", "Enable ShapeCast (3D)", ACEDescriptor.ACEType.ACTION, "enabled = {on}", "", [F.make_param("on", "String", "true", "Enabled", "true to sweep every physics frame.", "", ["true", "false"])], CAT_3D, "Set shapecast enabled to {on}", "ShapeCast3D")
		.described("Turns the sweep on or off."))
	descriptors.append(F.make_descriptor("Core", "ShapeCast3DCount", "ShapeCast Hit Count (3D)", ACEDescriptor.ACEType.EXPRESSION, "get_collision_count()", "", [], CAT_3D, "shapecast hit count", "ShapeCast3D")
		.described("How many objects the sweep is touching. Unlike a plain ray, a shapecast can report several at once."))
	descriptors.append(F.make_descriptor("Core", "ShapeCast3DColliderAt", "ShapeCast Collider At (3D)", ACEDescriptor.ACEType.EXPRESSION, "get_collider({index})", "", [F.make_param("index", "String", "0", "Index", "Which hit to read, starting at 0 (see ShapeCast Hit Count).", "expression")], CAT_3D, "shapecast collider at {index}", "ShapeCast3D")
		.described("Returns one of the objects the sweep is touching, by position in the hit list."))
	descriptors.append(F.make_descriptor("Core", "ShapeCast3DPointAt", "ShapeCast Hit Point At (3D)", ACEDescriptor.ACEType.EXPRESSION, "get_collision_point({index})", "", [F.make_param("index", "String", "0", "Index", "Which hit to read, starting at 0.", "expression")], CAT_3D, "shapecast hit point at {index}", "ShapeCast3D")
		.described("The world point where one of the sweep's hits touches."))
	descriptors.append(F.make_descriptor("Core", "ShapeCast3DNormalAt", "ShapeCast Hit Normal At (3D)", ACEDescriptor.ACEType.EXPRESSION, "get_collision_normal({index})", "", [F.make_param("index", "String", "0", "Index", "Which hit to read, starting at 0.", "expression")], CAT_3D, "shapecast hit normal at {index}", "ShapeCast3D")
		.described("The surface direction at one of the sweep's hits - bounce and slide maths start here."))
	descriptors.append(F.make_descriptor("Core", "ShapeCast3DSafeFraction", "ShapeCast Safe Fraction (3D)", ACEDescriptor.ACEType.EXPRESSION, "get_closest_collision_safe_fraction()", "", [], CAT_3D, "shapecast safe fraction", "ShapeCast3D")
		.described("How far along the sweep the shape can travel WITHOUT touching anything, from 0 (blocked immediately) to 1 (path is clear). Multiply the target by it to stop just short of the wall."))
	descriptors.append(F.make_descriptor("Core", "ShapeCast3DUnsafeFraction", "ShapeCast Unsafe Fraction (3D)", ACEDescriptor.ACEType.EXPRESSION, "get_closest_collision_unsafe_fraction()", "", [], CAT_3D, "shapecast unsafe fraction", "ShapeCast3D")
		.described("How far along the sweep the shape is first touching something, from 0 to 1 - the contact point to the safe fraction's stopping point."))
	descriptors.append(F.make_descriptor("Core", "ShapeCast3DSetMask", "Set ShapeCast Mask (3D)", ACEDescriptor.ACEType.ACTION, "collision_mask = {mask}", "", [F.make_param("mask", "String", "1", "Mask", "Collision mask as a number - each layer is a bit.", "expression")], CAT_3D, "Set shapecast mask to {mask}", "ShapeCast3D")
		.described("Chooses which collision layers the sweep can see."))
	descriptors.append(F.make_descriptor("Core", "ShapeCast3DSetMargin", "Set ShapeCast Margin (3D)", ACEDescriptor.ACEType.ACTION, "margin = {margin}", "", [F.make_param("margin", "String", "0.0", "Margin", "Extra padding around the shape, in metres.", "expression")], CAT_3D, "Set shapecast margin to {margin}", "ShapeCast3D")
		.described("Pads the swept shape slightly. A small margin makes contact detection steadier when the shape slides along a surface."))
	descriptors.append(F.make_descriptor("Core", "ShapeCast3DSetMaxResults", "Set ShapeCast Max Results (3D)", ACEDescriptor.ACEType.ACTION, "max_results = {max_results}", "", [F.make_param("max_results", "String", "32", "Max Results", "Most hits to collect in one sweep.", "expression")], CAT_3D, "Set shapecast max results to {max_results}", "ShapeCast3D")
		.described("Caps how many objects one sweep will report, which bounds its cost in a crowd."))
	descriptors.append(F.make_descriptor("Core", "ShapeCast3DAddException", "Ignore Node In ShapeCast (3D)", ACEDescriptor.ACEType.ACTION, "add_exception({node})", "", [F.make_param("node", "Node", "get_parent() as CollisionObject3D", "Node", "The object the sweep should pass through. Must be a CollisionObject3D.", "expression")], CAT_3D, "Ignore {node} in shapecast", "ShapeCast3D")
		.described("Makes the sweep pass straight through one specific object."))
	descriptors.append(F.make_descriptor("Core", "ShapeCast3DClearExceptions", "Clear ShapeCast Exceptions (3D)", ACEDescriptor.ACEType.ACTION, "clear_exceptions()", "", [], CAT_3D, "Clear shapecast exceptions", "ShapeCast3D")
		.described("Forgets every ignored object, so the sweep hits everything on its mask again."))


# ── 5. One-off 2D space-state queries: cast from anywhere, no node required. Cast Ray Into fires
# ONCE and stores the result, so asking for the point AND the collider is a single cast. ──
static func _add_world_queries_2d(descriptors: Array[ACEDescriptor]) -> void:
	descriptors.append(F.make_descriptor("Core", "CastRayInto2D", "Cast Ray Into (2D)", ACEDescriptor.ACEType.ACTION, "var __rq_{uid} := PhysicsRayQueryParameters2D.create({from}, {to}, {mask}, {exclude})\n__rq_{uid}.collide_with_areas = {hit_areas}\n{into} = get_world_2d().direct_space_state.intersect_ray(__rq_{uid})", "", [F.make_param("into", "String", "hit", "Into Variable", "Variable receiving the hit as a Dictionary (empty when the ray hit nothing). Read it with the Ray Result ACEs.", "variable_reference"), F.make_param("from", "String", "global_position", "From", "World point the ray starts at (Vector2 expression).", "expression"), F.make_param("to", "String", "global_position + Vector2(0, 100)", "To", "World point the ray ends at (Vector2 expression).", "expression"), F.make_param("mask", "String", "4294967295", "Mask", "Collision layers to test against. The default sees every layer.", "expression"), F.make_param("exclude", "String", "[]", "Ignore", "Array of physics RIDs to skip, e.g. [get_rid()] to ignore yourself.", "expression"), F.make_param("hit_areas", "String", "false", "Detect Areas", "true to notice Area2D nodes as well as bodies.", "", ["true", "false"])], CAT_2D, "Cast ray {from} -> {to} into {into}", "Node2D")
		.described("Fires one ray through the world and stores everything it learned in a variable. Use this instead of the single-shot expressions when you want more than one fact about the hit - they each re-cast the ray.").featured())
	descriptors.append(F.make_descriptor("Core", "WorldRaycastNormal2D", "World Raycast Normal (2D)", ACEDescriptor.ACEType.EXPRESSION, "get_world_2d().direct_space_state.intersect_ray(PhysicsRayQueryParameters2D.create({from}, {to})).get(\"normal\", Vector2.ZERO)", "", [F.make_param("from", "String", "Vector2(0, 0)", "From", "Ray start (Vector2 expression).", "expression"), F.make_param("to", "String", "Vector2(0, 0)", "To", "Ray end (Vector2 expression).", "expression")], CAT_2D, "world raycast normal {from} -> {to}", "Node2D")
		.described("The surface direction where a one-off ray hits, or a zero vector when it hits nothing."))
	descriptors.append(F.make_descriptor("Core", "QueryBodiesUnderMouse2D", "Query Bodies Under Mouse (2D)", ACEDescriptor.ACEType.ACTION, "var __pq_{uid} := PhysicsPointQueryParameters2D.new()\n__pq_{uid}.position = get_global_mouse_position()\n__pq_{uid}.collide_with_areas = {hit_areas}\n{into} = []\nfor __hit_{uid} in get_world_2d().direct_space_state.intersect_point(__pq_{uid}, {max_results}):\n\t{into}.append(__hit_{uid}.get(\"collider\"))", "", [F.make_param("into", "String", "picked", "Into Variable", "Variable receiving the Array of objects under the cursor.", "variable_reference"), F.make_param("hit_areas", "String", "true", "Detect Areas", "true to notice Area2D nodes as well as bodies.", "", ["true", "false"]), F.make_param("max_results", "String", "32", "Max Results", "Most objects to collect.", "expression")], CAT_2D, "Query bodies under mouse into {into}", "Node2D")
		.described("Collects everything the mouse cursor is over into a variable - click-to-select for 2D games, without any coordinate maths.").featured())
	descriptors.append(F.make_descriptor("Core", "CastCircleMotion2D", "Cast Circle Motion Into (2D)", ACEDescriptor.ACEType.ACTION, "var __cs_{uid} := CircleShape2D.new()\n__cs_{uid}.radius = {radius}\nvar __sq_{uid} := PhysicsShapeQueryParameters2D.new()\n__sq_{uid}.shape = __cs_{uid}\n__sq_{uid}.transform = Transform2D(0.0, {from})\n__sq_{uid}.motion = {motion}\n__sq_{uid}.collision_mask = {mask}\nvar __cm_{uid} := get_world_2d().direct_space_state.cast_motion(__sq_{uid})\n{into} = __cm_{uid}[0] if __cm_{uid}.size() > 0 else 1.0", "", [F.make_param("into", "String", "travel", "Into Variable", "Variable receiving how much of the move is clear, from 0 to 1.", "variable_reference"), F.make_param("from", "String", "global_position", "From", "Where the circle starts (Vector2 expression).", "expression"), F.make_param("motion", "String", "Vector2(0, 100)", "Motion", "The move to test, as an offset from the start.", "expression"), F.make_param("radius", "String", "16.0", "Radius", "Circle radius in pixels.", "expression"), F.make_param("mask", "String", "4294967295", "Mask", "Collision layers to test against.", "expression")], CAT_2D, "Cast circle motion {motion} into {into}", "Node2D")
		.described("Asks how far a circle could travel before something stops it, as a fraction of the move (1 means the whole path is clear). Multiply the motion by it to move right up to the obstacle."))


# ── 6. One-off 3D space-state queries: the 3D world had no point or volume query at all, and its
# one-off ray could only report hit/point - not what it hit, or which way the surface faces. ──
static func _add_world_queries_3d(descriptors: Array[ACEDescriptor]) -> void:
	descriptors.append(F.make_descriptor("Core", "CastRayInto3D", "Cast Ray Into (3D)", ACEDescriptor.ACEType.ACTION, "var __rq_{uid} := PhysicsRayQueryParameters3D.create({from}, {to}, {mask}, {exclude})\n__rq_{uid}.collide_with_areas = {hit_areas}\n{into} = get_world_3d().direct_space_state.intersect_ray(__rq_{uid})", "", [F.make_param("into", "String", "hit", "Into Variable", "Variable receiving the hit as a Dictionary (empty when the ray hit nothing). Read it with the Ray Result ACEs.", "variable_reference"), F.make_param("from", "String", "global_position", "From", "World point the ray starts at (Vector3 expression).", "expression"), F.make_param("to", "String", "global_position + Vector3(0, -10, 0)", "To", "World point the ray ends at (Vector3 expression).", "expression"), F.make_param("mask", "String", "4294967295", "Mask", "Collision layers to test against. The default sees every layer.", "expression"), F.make_param("exclude", "String", "[]", "Ignore", "Array of physics RIDs to skip, e.g. [get_rid()] to ignore yourself.", "expression"), F.make_param("hit_areas", "String", "false", "Detect Areas", "true to notice Area3D nodes as well as bodies.", "", ["true", "false"])], CAT_3D, "Cast ray {from} -> {to} into {into}", "Node3D")
		.described("Fires one ray through the world and stores everything it learned in a variable. Use this instead of the single-shot expressions when you want more than one fact about the hit - they each re-cast the ray.").featured())
	descriptors.append(F.make_descriptor("Core", "WorldRaycastCollider3D", "World Raycast Collider (3D)", ACEDescriptor.ACEType.EXPRESSION, "get_world_3d().direct_space_state.intersect_ray(PhysicsRayQueryParameters3D.create({from}, {to})).get(\"collider\", null)", "", [F.make_param("from", "String", "Vector3(0, 0, 0)", "From", "Ray start (Vector3 expression).", "expression"), F.make_param("to", "String", "Vector3(0, 0, 0)", "To", "Ray end (Vector3 expression).", "expression")], CAT_3D, "world raycast collider {from} -> {to}", "Node3D")
		.described("The object a one-off ray hits, or nothing when the path is clear."))
	descriptors.append(F.make_descriptor("Core", "WorldRaycastNormal3D", "World Raycast Normal (3D)", ACEDescriptor.ACEType.EXPRESSION, "get_world_3d().direct_space_state.intersect_ray(PhysicsRayQueryParameters3D.create({from}, {to})).get(\"normal\", Vector3.ZERO)", "", [F.make_param("from", "String", "Vector3(0, 0, 0)", "From", "Ray start (Vector3 expression).", "expression"), F.make_param("to", "String", "Vector3(0, 0, 0)", "To", "Ray end (Vector3 expression).", "expression")], CAT_3D, "world raycast normal {from} -> {to}", "Node3D")
		.described("The surface direction where a one-off ray hits, or a zero vector when it hits nothing - what you reflect a bounce around."))
	descriptors.append(F.make_descriptor("Core", "QueryBodiesAtPoint3D", "Query Bodies At Point (3D)", ACEDescriptor.ACEType.ACTION, "var __pq_{uid} := PhysicsPointQueryParameters3D.new()\n__pq_{uid}.position = {point}\n__pq_{uid}.collide_with_areas = {hit_areas}\n{into} = []\nfor __hit_{uid} in get_world_3d().direct_space_state.intersect_point(__pq_{uid}, {max_results}):\n\t{into}.append(__hit_{uid}.get(\"collider\"))", "", [F.make_param("into", "String", "data", "Into Variable", "Variable receiving the Array of overlapping objects.", "variable_reference"), F.make_param("point", "String", "global_position", "Point", "World position to test (Vector3 expression).", "expression"), F.make_param("hit_areas", "String", "false", "Detect Areas", "true to notice Area3D nodes as well as bodies.", "", ["true", "false"]), F.make_param("max_results", "String", "32", "Max Results", "Most objects to collect.", "expression")], CAT_OVERLAP_3D, "query bodies at {point} into {into}", "Node3D")
		.described("Collects every physics object at a world point into a variable - like tapping the world with a finger."))
	descriptors.append(F.make_descriptor("Core", "QueryBodiesInSphere3D", "Query Bodies In Sphere (3D)", ACEDescriptor.ACEType.ACTION, "var __ss_{uid} := SphereShape3D.new()\n__ss_{uid}.radius = {radius}\nvar __sq_{uid} := PhysicsShapeQueryParameters3D.new()\n__sq_{uid}.shape = __ss_{uid}\n__sq_{uid}.transform = Transform3D(Basis(), {center})\n__sq_{uid}.collision_mask = {mask}\n{into} = []\nfor __hit_{uid} in get_world_3d().direct_space_state.intersect_shape(__sq_{uid}, {max_results}):\n\t{into}.append(__hit_{uid}.get(\"collider\"))", "", [F.make_param("into", "String", "data", "Into Variable", "Variable receiving the Array of overlapping objects.", "variable_reference"), F.make_param("center", "String", "global_position", "Center", "Sphere center in world space (Vector3 expression).", "expression"), F.make_param("radius", "String", "5.0", "Radius", "Sphere radius in metres.", "expression"), F.make_param("mask", "String", "4294967295", "Mask", "Collision layers to test against.", "expression"), F.make_param("max_results", "String", "32", "Max Results", "Most objects to collect.", "expression")], CAT_OVERLAP_3D, "query bodies within {radius} of {center} into {into}", "Node3D")
		.described("Collects every physics object inside a sphere into a variable - explosion radii, pickup magnets, proximity checks.").featured())
	descriptors.append(F.make_descriptor("Core", "QueryBodiesInBox3D", "Query Bodies In Box (3D)", ACEDescriptor.ACEType.ACTION, "var __bs_{uid} := BoxShape3D.new()\n__bs_{uid}.size = {size}\nvar __sq_{uid} := PhysicsShapeQueryParameters3D.new()\n__sq_{uid}.shape = __bs_{uid}\n__sq_{uid}.transform = Transform3D(Basis(), {center})\n__sq_{uid}.collision_mask = {mask}\n{into} = []\nfor __hit_{uid} in get_world_3d().direct_space_state.intersect_shape(__sq_{uid}, {max_results}):\n\t{into}.append(__hit_{uid}.get(\"collider\"))", "", [F.make_param("into", "String", "data", "Into Variable", "Variable receiving the Array of overlapping objects.", "variable_reference"), F.make_param("center", "String", "global_position", "Center", "Box center in world space (Vector3 expression).", "expression"), F.make_param("size", "String", "Vector3(4, 4, 4)", "Size", "Full width, height and depth of the box.", "expression"), F.make_param("mask", "String", "4294967295", "Mask", "Collision layers to test against.", "expression"), F.make_param("max_results", "String", "32", "Max Results", "Most objects to collect.", "expression")], CAT_OVERLAP_3D, "query bodies in box {size} at {center} into {into}", "Node3D")
		.described("Collects every physics object inside a box into a variable - room triggers, rectangular blast zones, selection volumes."))
	descriptors.append(F.make_descriptor("Core", "CastSphereMotion3D", "Cast Sphere Motion Into (3D)", ACEDescriptor.ACEType.ACTION, "var __ss_{uid} := SphereShape3D.new()\n__ss_{uid}.radius = {radius}\nvar __sq_{uid} := PhysicsShapeQueryParameters3D.new()\n__sq_{uid}.shape = __ss_{uid}\n__sq_{uid}.transform = Transform3D(Basis(), {from})\n__sq_{uid}.motion = {motion}\n__sq_{uid}.collision_mask = {mask}\nvar __cm_{uid} := get_world_3d().direct_space_state.cast_motion(__sq_{uid})\n{into} = __cm_{uid}[0] if __cm_{uid}.size() > 0 else 1.0", "", [F.make_param("into", "String", "travel", "Into Variable", "Variable receiving how much of the move is clear, from 0 to 1.", "variable_reference"), F.make_param("from", "String", "global_position", "From", "Where the sphere starts (Vector3 expression).", "expression"), F.make_param("motion", "String", "Vector3(0, -10, 0)", "Motion", "The move to test, as an offset from the start.", "expression"), F.make_param("radius", "String", "0.5", "Radius", "Sphere radius in metres.", "expression"), F.make_param("mask", "String", "4294967295", "Mask", "Collision layers to test against.", "expression")], CAT_3D, "Cast sphere motion {motion} into {into}", "Node3D")
		.described("Asks how far a sphere could travel before something stops it, as a fraction of the move (1 means the whole path is clear) - the reliable way to move a fast object without tunnelling through walls."))


# ── 7. Reading a stored cast result. Cast Ray Into hands back the raw Dictionary Godot produced;
# these name its keys so a sheet never has to know them, and read a variable rather than re-casting. ──
static func _add_ray_result_readers(descriptors: Array[ACEDescriptor]) -> void:
	descriptors.append(F.make_descriptor("Core", "RayResultHit2D", "Ray Result Hit Something (2D)", ACEDescriptor.ACEType.CONDITION, "not {result}.is_empty()", "", [F.make_param("result", "String", "hit", "Result", "The variable a Cast Ray Into filled.", "variable_reference")], CAT_2D, "{result} hit something", "Node2D")
		.described("True when the stored cast found something. An empty result means the ray reached its end without touching anything.").featured())
	descriptors.append(F.make_descriptor("Core", "RayResultCollider2D", "Ray Result Collider (2D)", ACEDescriptor.ACEType.EXPRESSION, "{result}.get(\"collider\", null)", "", [F.make_param("result", "String", "hit", "Result", "The variable a Cast Ray Into filled.", "variable_reference")], CAT_2D, "{result} collider", "Node2D")
		.described("The object the stored cast hit, or nothing when it hit thin air."))
	descriptors.append(F.make_descriptor("Core", "RayResultPoint2D", "Ray Result Point (2D)", ACEDescriptor.ACEType.EXPRESSION, "{result}.get(\"position\", Vector2.ZERO)", "", [F.make_param("result", "String", "hit", "Result", "The variable a Cast Ray Into filled.", "variable_reference")], CAT_2D, "{result} point", "Node2D")
		.described("Where in the world the stored cast struck - spawn the impact spark here."))
	descriptors.append(F.make_descriptor("Core", "RayResultNormal2D", "Ray Result Normal (2D)", ACEDescriptor.ACEType.EXPRESSION, "{result}.get(\"normal\", Vector2.ZERO)", "", [F.make_param("result", "String", "hit", "Result", "The variable a Cast Ray Into filled.", "variable_reference")], CAT_2D, "{result} normal", "Node2D")
		.described("Which way the surface faces at the hit - reflect the velocity around it to bounce, or align a decal to it."))
	descriptors.append(F.make_descriptor("Core", "RayResultShape2D", "Ray Result Shape Index (2D)", ACEDescriptor.ACEType.EXPRESSION, "{result}.get(\"shape\", -1)", "", [F.make_param("result", "String", "hit", "Result", "The variable a Cast Ray Into filled.", "variable_reference")], CAT_2D, "{result} shape index", "Node2D")
		.described("Which of the hit object's collision shapes was struck, as an index - tell a headshot from a body shot."))
	descriptors.append(F.make_descriptor("Core", "RayResultInGroup2D", "Ray Result Is In Group (2D)", ACEDescriptor.ACEType.CONDITION, "({result}.get(\"collider\", null) != null and {result}[\"collider\"].is_in_group({group}))", "", [F.make_param("result", "String", "hit", "Result", "The variable a Cast Ray Into filled.", "variable_reference"), F.make_param("group", "String", "\"enemies\"", "Group", "Group name to test the hit object against.", "expression")], CAT_2D, "{result} is in {group}", "Node2D")
		.described("True when the stored cast hit something belonging to a group, checking for nothing-hit first so it is safe on a clear ray."))
	descriptors.append(F.make_descriptor("Core", "RayResultHit3D", "Ray Result Hit Something (3D)", ACEDescriptor.ACEType.CONDITION, "not {result}.is_empty()", "", [F.make_param("result", "String", "hit", "Result", "The variable a Cast Ray Into filled.", "variable_reference")], CAT_3D, "{result} hit something", "Node3D")
		.described("True when the stored cast found something. An empty result means the ray reached its end without touching anything.").featured())
	descriptors.append(F.make_descriptor("Core", "RayResultCollider3D", "Ray Result Collider (3D)", ACEDescriptor.ACEType.EXPRESSION, "{result}.get(\"collider\", null)", "", [F.make_param("result", "String", "hit", "Result", "The variable a Cast Ray Into filled.", "variable_reference")], CAT_3D, "{result} collider", "Node3D")
		.described("The object the stored cast hit, or nothing when it hit thin air."))
	descriptors.append(F.make_descriptor("Core", "RayResultPoint3D", "Ray Result Point (3D)", ACEDescriptor.ACEType.EXPRESSION, "{result}.get(\"position\", Vector3.ZERO)", "", [F.make_param("result", "String", "hit", "Result", "The variable a Cast Ray Into filled.", "variable_reference")], CAT_3D, "{result} point", "Node3D")
		.described("Where in the world the stored cast struck - spawn the impact effect or bullet hole here."))
	descriptors.append(F.make_descriptor("Core", "RayResultNormal3D", "Ray Result Normal (3D)", ACEDescriptor.ACEType.EXPRESSION, "{result}.get(\"normal\", Vector3.ZERO)", "", [F.make_param("result", "String", "hit", "Result", "The variable a Cast Ray Into filled.", "variable_reference")], CAT_3D, "{result} normal", "Node3D")
		.described("Which way the surface faces at the hit - reflect the velocity around it to bounce, or lay a decal flat against it."))
	descriptors.append(F.make_descriptor("Core", "RayResultShape3D", "Ray Result Shape Index (3D)", ACEDescriptor.ACEType.EXPRESSION, "{result}.get(\"shape\", -1)", "", [F.make_param("result", "String", "hit", "Result", "The variable a Cast Ray Into filled.", "variable_reference")], CAT_3D, "{result} shape index", "Node3D")
		.described("Which of the hit object's collision shapes was struck, as an index - tell a headshot from a body shot."))
	descriptors.append(F.make_descriptor("Core", "RayResultFaceIndex3D", "Ray Result Face Index (3D)", ACEDescriptor.ACEType.EXPRESSION, "{result}.get(\"face_index\", -1)", "", [F.make_param("result", "String", "hit", "Result", "The variable a Cast Ray Into filled.", "variable_reference")], CAT_3D, "{result} face index", "Node3D")
		.described("Which triangle of a concave mesh was hit, as an index (-1 for other shape types) - for reading per-face surface data like footstep materials."))
	descriptors.append(F.make_descriptor("Core", "RayResultInGroup3D", "Ray Result Is In Group (3D)", ACEDescriptor.ACEType.CONDITION, "({result}.get(\"collider\", null) != null and {result}[\"collider\"].is_in_group({group}))", "", [F.make_param("result", "String", "hit", "Result", "The variable a Cast Ray Into filled.", "variable_reference"), F.make_param("group", "String", "\"enemies\"", "Group", "Group name to test the hit object against.", "expression")], CAT_3D, "{result} is in {group}", "Node3D")
		.described("True when the stored cast hit something belonging to a group, checking for nothing-hit first so it is safe on a clear ray."))


# ── 8. Camera picking: the screen-to-world ray. Mouse Ray Origin/Direction already gave the two
# halves; these do the whole job, so "what is under the cursor" is one row instead of vector maths. ──
static func _add_camera_picking(descriptors: Array[ACEDescriptor]) -> void:
	descriptors.append(F.make_descriptor("Core", "CastMouseRayInto3D", "Cast Ray From Mouse Into (3D)", ACEDescriptor.ACEType.ACTION, "var __cam_{uid} := get_viewport().get_camera_3d()\nvar __mouse_{uid} := get_viewport().get_mouse_position()\nvar __from_{uid} := __cam_{uid}.project_ray_origin(__mouse_{uid})\nvar __to_{uid} := __from_{uid} + __cam_{uid}.project_ray_normal(__mouse_{uid}) * {distance}\nvar __rq_{uid} := PhysicsRayQueryParameters3D.create(__from_{uid}, __to_{uid}, {mask}, {exclude})\n__rq_{uid}.collide_with_areas = {hit_areas}\n{into} = get_world_3d().direct_space_state.intersect_ray(__rq_{uid})", "", [F.make_param("into", "String", "hit", "Into Variable", "Variable receiving the hit as a Dictionary (empty when nothing is under the cursor). Read it with the Ray Result ACEs.", "variable_reference"), F.make_param("distance", "String", "1000.0", "Distance", "How far into the scene to reach, in metres.", "expression"), F.make_param("mask", "String", "4294967295", "Mask", "Collision layers to test against. The default sees every layer.", "expression"), F.make_param("exclude", "String", "[]", "Ignore", "Array of physics RIDs to skip.", "expression"), F.make_param("hit_areas", "String", "false", "Detect Areas", "true to notice Area3D nodes as well as bodies.", "", ["true", "false"])], CAT_3D, "Cast ray from mouse into {into}", "Node3D")
		.described("Shoots a ray from the camera through the mouse cursor and stores what it finds - the whole of click-to-select in 3D, in one row. Needs an active Camera3D.").featured())
	descriptors.append(F.make_descriptor("Core", "MouseRayHits3D", "Mouse Ray Hits Something (3D)", ACEDescriptor.ACEType.CONDITION, "not get_world_3d().direct_space_state.intersect_ray(PhysicsRayQueryParameters3D.create(get_viewport().get_camera_3d().project_ray_origin(get_viewport().get_mouse_position()), get_viewport().get_camera_3d().project_ray_origin(get_viewport().get_mouse_position()) + get_viewport().get_camera_3d().project_ray_normal(get_viewport().get_mouse_position()) * {distance})).is_empty()", "", [F.make_param("distance", "String", "1000.0", "Distance", "How far into the scene to reach, in metres.", "expression")], CAT_3D, "mouse ray hits something within {distance}", "Node3D")
		.described("True when the cursor is over something solid. Casts on the spot - for more than a yes/no answer, use Cast Ray From Mouse Into and read the result."))
	descriptors.append(F.make_descriptor("Core", "MouseRayCollider3D", "Mouse Ray Collider (3D)", ACEDescriptor.ACEType.EXPRESSION, "get_world_3d().direct_space_state.intersect_ray(PhysicsRayQueryParameters3D.create(get_viewport().get_camera_3d().project_ray_origin(get_viewport().get_mouse_position()), get_viewport().get_camera_3d().project_ray_origin(get_viewport().get_mouse_position()) + get_viewport().get_camera_3d().project_ray_normal(get_viewport().get_mouse_position()) * {distance})).get(\"collider\", null)", "", [F.make_param("distance", "String", "1000.0", "Distance", "How far into the scene to reach, in metres.", "expression")], CAT_3D, "mouse ray collider within {distance}", "Node3D")
		.described("The object under the mouse cursor, or nothing when the cursor is over empty space."))
	descriptors.append(F.make_descriptor("Core", "MouseRayPoint3D", "Mouse Ray Point (3D)", ACEDescriptor.ACEType.EXPRESSION, "get_world_3d().direct_space_state.intersect_ray(PhysicsRayQueryParameters3D.create(get_viewport().get_camera_3d().project_ray_origin(get_viewport().get_mouse_position()), get_viewport().get_camera_3d().project_ray_origin(get_viewport().get_mouse_position()) + get_viewport().get_camera_3d().project_ray_normal(get_viewport().get_mouse_position()) * {distance})).get(\"position\", Vector3.ZERO)", "", [F.make_param("distance", "String", "1000.0", "Distance", "How far into the scene to reach, in metres.", "expression")], CAT_3D, "mouse ray point within {distance}", "Node3D")
		.described("The world point the cursor is pointing at - where to place a build ghost, a move order marker, or a decal."))
