# EventForge module - raycasting vocabulary (2D and 3D)
#
# Godot casts rays four different ways, and a sheet can now reach all of them:
#   1. RayCast2D / RayCast3D nodes  - a persistent ray the physics server updates for you.
#   2. ShapeCast2D / ShapeCast3D    - the same idea with THICKNESS (a swept shape, not a hairline),
#                                     which reports every hit along the sweep, not just the first.
#   3. Direct space-state queries   - one-off casts from anywhere: intersect_ray (a ray), intersect_point
#                                     (a pinprick), intersect_shape (a volume), cast_motion (how far a
#                                     shape can travel before it hits).
#   4. Camera picking               - the screen-to-world ray under the mouse, for click-to-select in 3D.
#
# Two shapes of verb, deliberately:
#   - SINGLE-SHOT expressions ("World Raycast Point") read well in one cell but re-cast the ray on every
#     use, so asking for the point AND the collider costs two casts.
#   - CAST INTO A VARIABLE actions fire ONE cast and store the result Dictionary, which the "Ray Result …"
#     conditions and expressions then read for free. Reach for these whenever you want more than one
#     fact about the same hit.
#
# Module contract: see ace_factory.gd - ace_ids/templates are API (compatibility
# covenant); this file only changes where the descriptors are AUTHORED.
@tool
class_name EventForgeRaycastACEs
extends RefCounted

const F := preload("res://addons/eventforge/registration/ace_factory.gd")

const CAT_2D := "Raycast 2D"
const CAT_3D := "Raycast 3D"
const CAT_OVERLAP_3D := "Overlap 3D"


static func get_descriptors() -> Array[ACEDescriptor]:
	var descriptors: Array[ACEDescriptor] = []
	_add_raycast_node_2d(descriptors)
	_add_raycast_node_3d(descriptors)
	_add_shapecast_2d(descriptors)
	_add_shapecast_3d(descriptors)
	_add_world_queries_2d(descriptors)
	_add_world_queries_3d(descriptors)
	_add_ray_result_readers(descriptors)
	_add_camera_picking(descriptors)
	return descriptors


# ── 1. RayCast2D node: the existing vocabulary could only READ one. These aim and configure it,
# so a sheet can swing a ray around (melee arcs, ledge probes, aim assist) without any GDScript. ──
static func _add_raycast_node_2d(descriptors: Array[ACEDescriptor]) -> void:
	descriptors.append(F.act("RayCast2DSetTarget", "Point RayCast At (2D)", "target_position = {reach}", CAT_2D, "Point raycast at {reach}", "Aims the ray and sets how far it reaches. The target is measured from the raycast itself, so Vector2(0, 100) points 100 pixels down.", "RayCast2D").param("reach", "Vector2(0, 100)", "Target", "Where the ray reaches, RELATIVE to the RayCast2D node (its own local space) - not a world position.", "expression"))
	descriptors.append(F.act("RayCast2DSetEnabled", "Enable RayCast (2D)", "enabled = {on}", CAT_2D, "Set raycast enabled to {on}", "Turns the ray on or off. A disabled raycast costs nothing and always reports no hit.", "RayCast2D").param_choice("on", "true", "Enabled", "true to cast every physics frame, false to switch it off.", ["true", "false"]))
	descriptors.append(F.act("RayCast2DSetMask", "Set RayCast Mask (2D)", "collision_mask = {mask}", CAT_2D, "Set raycast mask to {mask}", "Chooses which collision layers the ray can see, all at once.", "RayCast2D").param("mask", "1", "Mask", "Collision mask as a number - each layer is a bit, so layers 1 and 3 are 1 + 4 = 5.", "expression"))
	descriptors.append(F.act("RayCast2DSetMaskLayer", "Set RayCast Mask Layer (2D)", "set_collision_mask_value({layer}, {on})", CAT_2D, "Set raycast mask layer {layer} to {on}", "Switches ONE collision layer on or off for the ray, leaving the others alone - easier than working out the mask number.", "RayCast2D").param("layer", "1", "Layer", "Layer number, starting at 1.", "expression").param_choice("on", "true", "Detect", "true to notice this layer, false to ignore it.", ["true", "false"]))
	descriptors.append(F.act("RayCast2DAddException", "Ignore Node In RayCast (2D)", "add_exception({node})", CAT_2D, "Ignore {node} in raycast", "Makes the ray pass straight through one specific object - the usual way to stop a gun's ray hitting the shooter.", "RayCast2D").param_typed("Node", "node", "get_parent() as CollisionObject2D", "Node", "The physics body or area the ray should pass through. Must be a CollisionObject2D - a plain Node will not compile.", "expression"))
	descriptors.append(F.act("RayCast2DRemoveException", "Stop Ignoring Node In RayCast (2D)", "remove_exception({node})", CAT_2D, "Stop ignoring {node} in raycast", "Undoes Ignore Node In RayCast for one object, so the ray can hit it again.", "RayCast2D").param_typed("Node", "node", "get_parent() as CollisionObject2D", "Node", "The object that should be hittable again. Must be a CollisionObject2D.", "expression"))
	descriptors.append(F.act("RayCast2DClearExceptions", "Clear RayCast Exceptions (2D)", "clear_exceptions()", CAT_2D, "Clear raycast exceptions", "Forgets every ignored object, so the ray hits everything on its mask again.", "RayCast2D"))
	descriptors.append(F.act("RayCast2DSetHitAreas", "RayCast Detects Areas (2D)", "collide_with_areas = {on}", CAT_2D, "Set raycast detects areas to {on}", "Lets the ray notice Area2D nodes. Godot IGNORES areas by default, which is the usual reason a ray seems to miss a trigger zone.", "RayCast2D").param_choice("on", "true", "Detect Areas", "true to notice Area2D nodes.", ["true", "false"]))
	descriptors.append(F.act("RayCast2DSetHitBodies", "RayCast Detects Bodies (2D)", "collide_with_bodies = {on}", CAT_2D, "Set raycast detects bodies to {on}", "Lets the ray notice solid physics bodies (on by default). Turn it off for a ray that should only see trigger areas.", "RayCast2D").param_choice("on", "true", "Detect Bodies", "true to notice physics bodies.", ["true", "false"]))
	descriptors.append(F.act("RayCast2DSetHitFromInside", "RayCast Hits From Inside (2D)", "hit_from_inside = {on}", CAT_2D, "Set raycast hits from inside to {on}", "Reports a hit even when the ray begins inside the shape. Off by default, which is why a ray starting inside a wall reads as clear.", "RayCast2D").param_choice("on", "true", "Hit From Inside", "true to report a shape the ray STARTS inside.", ["true", "false"]))
	descriptors.append(F.act("RayCast2DSetExcludeParent", "RayCast Ignores Its Parent (2D)", "exclude_parent = {on}", CAT_2D, "Set raycast ignores parent to {on}", "Passes through the body the raycast is parented to (on by default), so a character's own ray never hits the character.", "RayCast2D").param_choice("on", "true", "Ignore Parent", "true to pass through the body it hangs from.", ["true", "false"]))
	descriptors.append(F.cond("RayCast2DHitsGroup", "RayCast Hits Group (2D)", "(is_colliding() and get_collider() != null and get_collider().is_in_group({group}))", CAT_2D, "RayCast hits something in {group}", "True when the ray is hitting something that belongs to a group - \"did I shoot an enemy?\" in one cell.", "RayCast2D").param("group", "\"enemies\"", "Group", "Group name to test the hit object against.", "expression"))
	descriptors.append(F.expr("RayCast2DColliderShape", "RayCast Hit Shape Index (2D)", "get_collider_shape()", CAT_2D, "raycast hit shape index", "Which of the hit object's collision shapes was struck, as an index - for bodies built from several shapes (a head shape versus a body shape).", "RayCast2D"))
	descriptors.append(F.expr("RayCast2DTarget", "RayCast Target (2D)", "target_position", CAT_2D, "raycast target", "Returns where the ray currently reaches, relative to the raycast node.", "RayCast2D"))


# ── 2. RayCast3D node: the same aiming and configuring, plus the two options only 3D has
# (which triangle of a mesh was hit, and whether back faces count). ──
static func _add_raycast_node_3d(descriptors: Array[ACEDescriptor]) -> void:
	descriptors.append(F.act("RayCast3DSetTarget", "Point RayCast At (3D)", "target_position = {reach}", CAT_3D, "Point raycast at {reach}", "Aims the ray and sets how far it reaches. The target is measured from the raycast itself, so Vector3(0, 0, -10) points 10 metres forward.", "RayCast3D").param("reach", "Vector3(0, 0, -10)", "Target", "Where the ray reaches, RELATIVE to the RayCast3D node (its own local space) - not a world position.", "expression"))
	descriptors.append(F.act("RayCast3DSetEnabled", "Enable RayCast (3D)", "enabled = {on}", CAT_3D, "Set raycast enabled to {on}", "Turns the ray on or off. A disabled raycast costs nothing and always reports no hit.", "RayCast3D").param_choice("on", "true", "Enabled", "true to cast every physics frame, false to switch it off.", ["true", "false"]))
	descriptors.append(F.act("RayCast3DSetMask", "Set RayCast Mask (3D)", "collision_mask = {mask}", CAT_3D, "Set raycast mask to {mask}", "Chooses which collision layers the ray can see, all at once.", "RayCast3D").param("mask", "1", "Mask", "Collision mask as a number - each layer is a bit, so layers 1 and 3 are 1 + 4 = 5.", "expression"))
	descriptors.append(F.act("RayCast3DSetMaskLayer", "Set RayCast Mask Layer (3D)", "set_collision_mask_value({layer}, {on})", CAT_3D, "Set raycast mask layer {layer} to {on}", "Switches ONE collision layer on or off for the ray, leaving the others alone - easier than working out the mask number.", "RayCast3D").param("layer", "1", "Layer", "Layer number, starting at 1.", "expression").param_choice("on", "true", "Detect", "true to notice this layer, false to ignore it.", ["true", "false"]))
	descriptors.append(F.act("RayCast3DAddException", "Ignore Node In RayCast (3D)", "add_exception({node})", CAT_3D, "Ignore {node} in raycast", "Makes the ray pass straight through one specific object - the usual way to stop a gun's ray hitting the shooter.", "RayCast3D").param_typed("Node", "node", "get_parent() as CollisionObject3D", "Node", "The physics body or area the ray should pass through. Must be a CollisionObject3D - a plain Node will not compile.", "expression"))
	descriptors.append(F.act("RayCast3DRemoveException", "Stop Ignoring Node In RayCast (3D)", "remove_exception({node})", CAT_3D, "Stop ignoring {node} in raycast", "Undoes Ignore Node In RayCast for one object, so the ray can hit it again.", "RayCast3D").param_typed("Node", "node", "get_parent() as CollisionObject3D", "Node", "The object that should be hittable again. Must be a CollisionObject3D.", "expression"))
	descriptors.append(F.act("RayCast3DClearExceptions", "Clear RayCast Exceptions (3D)", "clear_exceptions()", CAT_3D, "Clear raycast exceptions", "Forgets every ignored object, so the ray hits everything on its mask again.", "RayCast3D"))
	descriptors.append(F.act("RayCast3DSetHitAreas", "RayCast Detects Areas (3D)", "collide_with_areas = {on}", CAT_3D, "Set raycast detects areas to {on}", "Lets the ray notice Area3D nodes. Godot IGNORES areas by default, which is the usual reason a ray seems to miss a trigger zone.", "RayCast3D").param_choice("on", "true", "Detect Areas", "true to notice Area3D nodes.", ["true", "false"]))
	descriptors.append(F.act("RayCast3DSetHitBodies", "RayCast Detects Bodies (3D)", "collide_with_bodies = {on}", CAT_3D, "Set raycast detects bodies to {on}", "Lets the ray notice solid physics bodies (on by default). Turn it off for a ray that should only see trigger areas.", "RayCast3D").param_choice("on", "true", "Detect Bodies", "true to notice physics bodies.", ["true", "false"]))
	descriptors.append(F.act("RayCast3DSetHitFromInside", "RayCast Hits From Inside (3D)", "hit_from_inside = {on}", CAT_3D, "Set raycast hits from inside to {on}", "Reports a hit even when the ray begins inside the shape. Off by default, which is why a ray starting inside geometry reads as clear.", "RayCast3D").param_choice("on", "true", "Hit From Inside", "true to report a shape the ray STARTS inside.", ["true", "false"]))
	descriptors.append(F.act("RayCast3DSetHitBackFaces", "RayCast Hits Back Faces (3D)", "hit_back_faces = {on}", CAT_3D, "Set raycast hits back faces to {on}", "Decides whether the ray hits a surface from behind - matters for concave level geometry, where the inside of a wall faces you.", "RayCast3D").param_choice("on", "true", "Hit Back Faces", "true to hit the inside surface of concave collision shapes.", ["true", "false"]))
	descriptors.append(F.act("RayCast3DSetExcludeParent", "RayCast Ignores Its Parent (3D)", "exclude_parent = {on}", CAT_3D, "Set raycast ignores parent to {on}", "Passes through the body the raycast is parented to (on by default), so a character's own ray never hits the character.", "RayCast3D").param_choice("on", "true", "Ignore Parent", "true to pass through the body it hangs from.", ["true", "false"]))
	descriptors.append(F.cond("RayCast3DHitsGroup", "RayCast Hits Group (3D)", "(is_colliding() and get_collider() != null and get_collider().is_in_group({group}))", CAT_3D, "RayCast hits something in {group}", "True when the ray is hitting something that belongs to a group - \"did I shoot an enemy?\" in one cell.", "RayCast3D").param("group", "\"enemies\"", "Group", "Group name to test the hit object against.", "expression"))
	descriptors.append(F.expr("RayCast3DColliderShape", "RayCast Hit Shape Index (3D)", "get_collider_shape()", CAT_3D, "raycast hit shape index", "Which of the hit object's collision shapes was struck, as an index - for bodies built from several shapes (a head shape versus a body shape).", "RayCast3D"))
	descriptors.append(F.expr("RayCast3DFaceIndex", "RayCast Hit Face Index (3D)", "get_collision_face_index()", CAT_3D, "raycast hit face index", "Which triangle of a concave mesh the ray hit, as an index (-1 for other shape types) - useful for reading per-face surface data.", "RayCast3D"))
	descriptors.append(F.expr("RayCast3DTarget", "RayCast Target (3D)", "target_position", CAT_3D, "raycast target", "Returns where the ray currently reaches, relative to the raycast node.", "RayCast3D"))


# ── 3. ShapeCast2D: a ray with THICKNESS. A hairline ray slips between fast-moving objects and
# through gaps; a swept shape does not, and it reports EVERY object along the sweep. ──
static func _add_shapecast_2d(descriptors: Array[ACEDescriptor]) -> void:
	descriptors.append(F.cond("ShapeCast2DIsColliding", "ShapeCast Is Colliding (2D)", "is_colliding()", CAT_2D, "ShapeCast is colliding", "True when the swept shape is touching anything along its path.", "ShapeCast2D").featured())
	descriptors.append(F.act("ShapeCast2DForceUpdate", "Force ShapeCast Update (2D)", "force_shapecast_update()", CAT_2D, "Force shapecast update", "Re-runs the sweep immediately instead of waiting for the next physics frame - do this after moving or re-aiming it in the same frame you read it.", "ShapeCast2D"))
	descriptors.append(F.act("ShapeCast2DSetTarget", "Point ShapeCast At (2D)", "target_position = {reach}", CAT_2D, "Point shapecast at {reach}", "Aims the sweep and sets its length, measured from the shapecast itself.", "ShapeCast2D").param("reach", "Vector2(0, 100)", "Target", "How far and in which direction to sweep, RELATIVE to the ShapeCast2D node.", "expression"))
	descriptors.append(F.act("ShapeCast2DSetEnabled", "Enable ShapeCast (2D)", "enabled = {on}", CAT_2D, "Set shapecast enabled to {on}", "Turns the sweep on or off.", "ShapeCast2D").param_choice("on", "true", "Enabled", "true to sweep every physics frame.", ["true", "false"]))
	descriptors.append(F.expr("ShapeCast2DCount", "ShapeCast Hit Count (2D)", "get_collision_count()", CAT_2D, "shapecast hit count", "How many objects the sweep is touching. Unlike a plain ray, a shapecast can report several at once.", "ShapeCast2D"))
	descriptors.append(F.expr("ShapeCast2DColliderAt", "ShapeCast Collider At (2D)", "get_collider({index})", CAT_2D, "shapecast collider at {index}", "Returns one of the objects the sweep is touching, by position in the hit list.", "ShapeCast2D").param("index", "0", "Index", "Which hit to read, starting at 0 (see ShapeCast Hit Count).", "expression"))
	descriptors.append(F.expr("ShapeCast2DPointAt", "ShapeCast Hit Point At (2D)", "get_collision_point({index})", CAT_2D, "shapecast hit point at {index}", "The world point where one of the sweep's hits touches.", "ShapeCast2D").param("index", "0", "Index", "Which hit to read, starting at 0.", "expression"))
	descriptors.append(F.expr("ShapeCast2DNormalAt", "ShapeCast Hit Normal At (2D)", "get_collision_normal({index})", CAT_2D, "shapecast hit normal at {index}", "The surface direction at one of the sweep's hits - bounce and slide maths start here.", "ShapeCast2D").param("index", "0", "Index", "Which hit to read, starting at 0.", "expression"))
	descriptors.append(F.expr("ShapeCast2DSafeFraction", "ShapeCast Safe Fraction (2D)", "get_closest_collision_safe_fraction()", CAT_2D, "shapecast safe fraction", "How far along the sweep the shape can travel WITHOUT touching anything, from 0 (blocked immediately) to 1 (path is clear). Multiply the target by it to stop just short of the wall.", "ShapeCast2D"))
	descriptors.append(F.expr("ShapeCast2DUnsafeFraction", "ShapeCast Unsafe Fraction (2D)", "get_closest_collision_unsafe_fraction()", CAT_2D, "shapecast unsafe fraction", "How far along the sweep the shape is first touching something, from 0 to 1 - the contact point to the safe fraction's stopping point.", "ShapeCast2D"))
	descriptors.append(F.act("ShapeCast2DSetMask", "Set ShapeCast Mask (2D)", "collision_mask = {mask}", CAT_2D, "Set shapecast mask to {mask}", "Chooses which collision layers the sweep can see.", "ShapeCast2D").param("mask", "1", "Mask", "Collision mask as a number - each layer is a bit.", "expression"))
	descriptors.append(F.act("ShapeCast2DSetMargin", "Set ShapeCast Margin (2D)", "margin = {margin}", CAT_2D, "Set shapecast margin to {margin}", "Pads the swept shape slightly. A small margin makes contact detection steadier when the shape slides along a surface.", "ShapeCast2D").param("margin", "0.0", "Margin", "Extra padding around the shape, in pixels.", "expression"))
	descriptors.append(F.act("ShapeCast2DSetMaxResults", "Set ShapeCast Max Results (2D)", "max_results = {max_results}", CAT_2D, "Set shapecast max results to {max_results}", "Caps how many objects one sweep will report, which bounds its cost in a crowd.", "ShapeCast2D").param("max_results", "32", "Max Results", "Most hits to collect in one sweep.", "expression"))
	descriptors.append(F.act("ShapeCast2DAddException", "Ignore Node In ShapeCast (2D)", "add_exception({node})", CAT_2D, "Ignore {node} in shapecast", "Makes the sweep pass straight through one specific object.", "ShapeCast2D").param_typed("Node", "node", "get_parent() as CollisionObject2D", "Node", "The object the sweep should pass through. Must be a CollisionObject2D.", "expression"))
	descriptors.append(F.act("ShapeCast2DClearExceptions", "Clear ShapeCast Exceptions (2D)", "clear_exceptions()", CAT_2D, "Clear shapecast exceptions", "Forgets every ignored object, so the sweep hits everything on its mask again.", "ShapeCast2D"))


# ── 4. ShapeCast3D: the same swept shape in three dimensions - the standard fix for a bullet
# that tunnels through a thin wall, and for a character probe that a hairline ray would thread. ──
static func _add_shapecast_3d(descriptors: Array[ACEDescriptor]) -> void:
	descriptors.append(F.cond("ShapeCast3DIsColliding", "ShapeCast Is Colliding (3D)", "is_colliding()", CAT_3D, "ShapeCast is colliding", "True when the swept shape is touching anything along its path.", "ShapeCast3D").featured())
	descriptors.append(F.act("ShapeCast3DForceUpdate", "Force ShapeCast Update (3D)", "force_shapecast_update()", CAT_3D, "Force shapecast update", "Re-runs the sweep immediately instead of waiting for the next physics frame - do this after moving or re-aiming it in the same frame you read it.", "ShapeCast3D"))
	descriptors.append(F.act("ShapeCast3DSetTarget", "Point ShapeCast At (3D)", "target_position = {reach}", CAT_3D, "Point shapecast at {reach}", "Aims the sweep and sets its length, measured from the shapecast itself.", "ShapeCast3D").param("reach", "Vector3(0, 0, -10)", "Target", "How far and in which direction to sweep, RELATIVE to the ShapeCast3D node.", "expression"))
	descriptors.append(F.act("ShapeCast3DSetEnabled", "Enable ShapeCast (3D)", "enabled = {on}", CAT_3D, "Set shapecast enabled to {on}", "Turns the sweep on or off.", "ShapeCast3D").param_choice("on", "true", "Enabled", "true to sweep every physics frame.", ["true", "false"]))
	descriptors.append(F.expr("ShapeCast3DCount", "ShapeCast Hit Count (3D)", "get_collision_count()", CAT_3D, "shapecast hit count", "How many objects the sweep is touching. Unlike a plain ray, a shapecast can report several at once.", "ShapeCast3D"))
	descriptors.append(F.expr("ShapeCast3DColliderAt", "ShapeCast Collider At (3D)", "get_collider({index})", CAT_3D, "shapecast collider at {index}", "Returns one of the objects the sweep is touching, by position in the hit list.", "ShapeCast3D").param("index", "0", "Index", "Which hit to read, starting at 0 (see ShapeCast Hit Count).", "expression"))
	descriptors.append(F.expr("ShapeCast3DPointAt", "ShapeCast Hit Point At (3D)", "get_collision_point({index})", CAT_3D, "shapecast hit point at {index}", "The world point where one of the sweep's hits touches.", "ShapeCast3D").param("index", "0", "Index", "Which hit to read, starting at 0.", "expression"))
	descriptors.append(F.expr("ShapeCast3DNormalAt", "ShapeCast Hit Normal At (3D)", "get_collision_normal({index})", CAT_3D, "shapecast hit normal at {index}", "The surface direction at one of the sweep's hits - bounce and slide maths start here.", "ShapeCast3D").param("index", "0", "Index", "Which hit to read, starting at 0.", "expression"))
	descriptors.append(F.expr("ShapeCast3DSafeFraction", "ShapeCast Safe Fraction (3D)", "get_closest_collision_safe_fraction()", CAT_3D, "shapecast safe fraction", "How far along the sweep the shape can travel WITHOUT touching anything, from 0 (blocked immediately) to 1 (path is clear). Multiply the target by it to stop just short of the wall.", "ShapeCast3D"))
	descriptors.append(F.expr("ShapeCast3DUnsafeFraction", "ShapeCast Unsafe Fraction (3D)", "get_closest_collision_unsafe_fraction()", CAT_3D, "shapecast unsafe fraction", "How far along the sweep the shape is first touching something, from 0 to 1 - the contact point to the safe fraction's stopping point.", "ShapeCast3D"))
	descriptors.append(F.act("ShapeCast3DSetMask", "Set ShapeCast Mask (3D)", "collision_mask = {mask}", CAT_3D, "Set shapecast mask to {mask}", "Chooses which collision layers the sweep can see.", "ShapeCast3D").param("mask", "1", "Mask", "Collision mask as a number - each layer is a bit.", "expression"))
	descriptors.append(F.act("ShapeCast3DSetMargin", "Set ShapeCast Margin (3D)", "margin = {margin}", CAT_3D, "Set shapecast margin to {margin}", "Pads the swept shape slightly. A small margin makes contact detection steadier when the shape slides along a surface.", "ShapeCast3D").param("margin", "0.0", "Margin", "Extra padding around the shape, in metres.", "expression"))
	descriptors.append(F.act("ShapeCast3DSetMaxResults", "Set ShapeCast Max Results (3D)", "max_results = {max_results}", CAT_3D, "Set shapecast max results to {max_results}", "Caps how many objects one sweep will report, which bounds its cost in a crowd.", "ShapeCast3D").param("max_results", "32", "Max Results", "Most hits to collect in one sweep.", "expression"))
	descriptors.append(F.act("ShapeCast3DAddException", "Ignore Node In ShapeCast (3D)", "add_exception({node})", CAT_3D, "Ignore {node} in shapecast", "Makes the sweep pass straight through one specific object.", "ShapeCast3D").param_typed("Node", "node", "get_parent() as CollisionObject3D", "Node", "The object the sweep should pass through. Must be a CollisionObject3D.", "expression"))
	descriptors.append(F.act("ShapeCast3DClearExceptions", "Clear ShapeCast Exceptions (3D)", "clear_exceptions()", CAT_3D, "Clear shapecast exceptions", "Forgets every ignored object, so the sweep hits everything on its mask again.", "ShapeCast3D"))


# ── 5. One-off 2D space-state queries: cast from anywhere, no node required. Cast Ray Into fires
# ONCE and stores the result, so asking for the point AND the collider is a single cast. ──
static func _add_world_queries_2d(descriptors: Array[ACEDescriptor]) -> void:
	descriptors.append(F.act("CastRayInto2D", "Cast Ray Into (2D)", "var __rq_{uid} := PhysicsRayQueryParameters2D.create({from}, {to}, {mask}, {exclude})\n__rq_{uid}.collide_with_areas = {hit_areas}\n{into} = get_world_2d().direct_space_state.intersect_ray(__rq_{uid})", CAT_2D, "Cast ray {from} -> {to} into {into}", "Fires one ray through the world and stores everything it learned in a variable. Use this instead of the single-shot expressions when you want more than one fact about the hit - they each re-cast the ray.", "Node2D").param("into", "hit", "Into Variable", "Variable receiving the hit as a Dictionary (empty when the ray hit nothing). Read it with the Ray Result ACEs.", "variable_reference").param("from", "global_position", "From", "World point the ray starts at (Vector2 expression).", "expression").param("to", "global_position + Vector2(0, 100)", "To", "World point the ray ends at (Vector2 expression).", "expression").param("mask", "4294967295", "Mask", "Collision layers to test against. The default sees every layer.", "expression").param("exclude", "[]", "Ignore", "Array of physics RIDs to skip, e.g. [get_rid()] to ignore yourself.", "expression").param_choice("hit_areas", "false", "Detect Areas", "true to notice Area2D nodes as well as bodies.", ["true", "false"]).featured())
	descriptors.append(F.expr("WorldRaycastNormal2D", "World Raycast Normal (2D)", "get_world_2d().direct_space_state.intersect_ray(PhysicsRayQueryParameters2D.create({from}, {to})).get(\"normal\", Vector2.ZERO)", CAT_2D, "world raycast normal {from} -> {to}", "The surface direction where a one-off ray hits, or a zero vector when it hits nothing.", "Node2D").param("from", "Vector2(0, 0)", "From", "Ray start (Vector2 expression).", "expression").param("to", "Vector2(0, 0)", "To", "Ray end (Vector2 expression).", "expression"))
	descriptors.append(F.act("QueryBodiesUnderMouse2D", "Query Bodies Under Mouse (2D)", "var __pq_{uid} := PhysicsPointQueryParameters2D.new()\n__pq_{uid}.position = get_global_mouse_position()\n__pq_{uid}.collide_with_areas = {hit_areas}\n{into} = []\nfor __hit_{uid} in get_world_2d().direct_space_state.intersect_point(__pq_{uid}, {max_results}):\n\t{into}.append(__hit_{uid}.get(\"collider\"))", CAT_2D, "Query bodies under mouse into {into}", "Collects everything the mouse cursor is over into a variable - click-to-select for 2D games, without any coordinate maths.", "Node2D").param("into", "picked", "Into Variable", "Variable receiving the Array of objects under the cursor.", "variable_reference").param_choice("hit_areas", "true", "Detect Areas", "true to notice Area2D nodes as well as bodies.", ["true", "false"]).param("max_results", "32", "Max Results", "Most objects to collect.", "expression").featured())
	descriptors.append(F.act("CastCircleMotion2D", "Cast Circle Motion Into (2D)", "var __cs_{uid} := CircleShape2D.new()\n__cs_{uid}.radius = {radius}\nvar __sq_{uid} := PhysicsShapeQueryParameters2D.new()\n__sq_{uid}.shape = __cs_{uid}\n__sq_{uid}.transform = Transform2D(0.0, {from})\n__sq_{uid}.motion = {motion}\n__sq_{uid}.collision_mask = {mask}\nvar __cm_{uid} := get_world_2d().direct_space_state.cast_motion(__sq_{uid})\n{into} = __cm_{uid}[0] if __cm_{uid}.size() > 0 else 1.0", CAT_2D, "Cast circle motion {motion} into {into}", "Asks how far a circle could travel before something stops it, as a fraction of the move (1 means the whole path is clear). Multiply the motion by it to move right up to the obstacle.", "Node2D").param("into", "travel", "Into Variable", "Variable receiving how much of the move is clear, from 0 to 1.", "variable_reference").param("from", "global_position", "From", "Where the circle starts (Vector2 expression).", "expression").param("motion", "Vector2(0, 100)", "Motion", "The move to test, as an offset from the start.", "expression").param("radius", "16.0", "Radius", "Circle radius in pixels.", "expression").param("mask", "4294967295", "Mask", "Collision layers to test against.", "expression"))


# ── 6. One-off 3D space-state queries: the 3D world had no point or volume query at all, and its
# one-off ray could only report hit/point - not what it hit, or which way the surface faces. ──
static func _add_world_queries_3d(descriptors: Array[ACEDescriptor]) -> void:
	descriptors.append(F.act("CastRayInto3D", "Cast Ray Into (3D)", "var __rq_{uid} := PhysicsRayQueryParameters3D.create({from}, {to}, {mask}, {exclude})\n__rq_{uid}.collide_with_areas = {hit_areas}\n{into} = get_world_3d().direct_space_state.intersect_ray(__rq_{uid})", CAT_3D, "Cast ray {from} -> {to} into {into}", "Fires one ray through the world and stores everything it learned in a variable. Use this instead of the single-shot expressions when you want more than one fact about the hit - they each re-cast the ray.", "Node3D").param("into", "hit", "Into Variable", "Variable receiving the hit as a Dictionary (empty when the ray hit nothing). Read it with the Ray Result ACEs.", "variable_reference").param("from", "global_position", "From", "World point the ray starts at (Vector3 expression).", "expression").param("to", "global_position + Vector3(0, -10, 0)", "To", "World point the ray ends at (Vector3 expression).", "expression").param("mask", "4294967295", "Mask", "Collision layers to test against. The default sees every layer.", "expression").param("exclude", "[]", "Ignore", "Array of physics RIDs to skip, e.g. [get_rid()] to ignore yourself.", "expression").param_choice("hit_areas", "false", "Detect Areas", "true to notice Area3D nodes as well as bodies.", ["true", "false"]).featured())
	descriptors.append(F.expr("WorldRaycastCollider3D", "World Raycast Collider (3D)", "get_world_3d().direct_space_state.intersect_ray(PhysicsRayQueryParameters3D.create({from}, {to})).get(\"collider\", null)", CAT_3D, "world raycast collider {from} -> {to}", "The object a one-off ray hits, or nothing when the path is clear.", "Node3D").param("from", "Vector3(0, 0, 0)", "From", "Ray start (Vector3 expression).", "expression").param("to", "Vector3(0, 0, 0)", "To", "Ray end (Vector3 expression).", "expression"))
	descriptors.append(F.expr("WorldRaycastNormal3D", "World Raycast Normal (3D)", "get_world_3d().direct_space_state.intersect_ray(PhysicsRayQueryParameters3D.create({from}, {to})).get(\"normal\", Vector3.ZERO)", CAT_3D, "world raycast normal {from} -> {to}", "The surface direction where a one-off ray hits, or a zero vector when it hits nothing - what you reflect a bounce around.", "Node3D").param("from", "Vector3(0, 0, 0)", "From", "Ray start (Vector3 expression).", "expression").param("to", "Vector3(0, 0, 0)", "To", "Ray end (Vector3 expression).", "expression"))
	descriptors.append(F.act("QueryBodiesAtPoint3D", "Query Bodies At Point (3D)", "var __pq_{uid} := PhysicsPointQueryParameters3D.new()\n__pq_{uid}.position = {point}\n__pq_{uid}.collide_with_areas = {hit_areas}\n{into} = []\nfor __hit_{uid} in get_world_3d().direct_space_state.intersect_point(__pq_{uid}, {max_results}):\n\t{into}.append(__hit_{uid}.get(\"collider\"))", CAT_OVERLAP_3D, "query bodies at {point} into {into}", "Collects every physics object at a world point into a variable - like tapping the world with a finger.", "Node3D").param("into", "data", "Into Variable", "Variable receiving the Array of overlapping objects.", "variable_reference").param("point", "global_position", "Point", "World position to test (Vector3 expression).", "expression").param_choice("hit_areas", "false", "Detect Areas", "true to notice Area3D nodes as well as bodies.", ["true", "false"]).param("max_results", "32", "Max Results", "Most objects to collect.", "expression"))
	descriptors.append(F.act("QueryBodiesInSphere3D", "Query Bodies In Sphere (3D)", "var __ss_{uid} := SphereShape3D.new()\n__ss_{uid}.radius = {radius}\nvar __sq_{uid} := PhysicsShapeQueryParameters3D.new()\n__sq_{uid}.shape = __ss_{uid}\n__sq_{uid}.transform = Transform3D(Basis(), {center})\n__sq_{uid}.collision_mask = {mask}\n{into} = []\nfor __hit_{uid} in get_world_3d().direct_space_state.intersect_shape(__sq_{uid}, {max_results}):\n\t{into}.append(__hit_{uid}.get(\"collider\"))", CAT_OVERLAP_3D, "query bodies within {radius} of {center} into {into}", "Collects every physics object inside a sphere into a variable - explosion radii, pickup magnets, proximity checks.", "Node3D").param("into", "data", "Into Variable", "Variable receiving the Array of overlapping objects.", "variable_reference").param("center", "global_position", "Center", "Sphere center in world space (Vector3 expression).", "expression").param("radius", "5.0", "Radius", "Sphere radius in metres.", "expression").param("mask", "4294967295", "Mask", "Collision layers to test against.", "expression").param("max_results", "32", "Max Results", "Most objects to collect.", "expression").featured())
	descriptors.append(F.act("QueryBodiesInBox3D", "Query Bodies In Box (3D)", "var __bs_{uid} := BoxShape3D.new()\n__bs_{uid}.size = {size}\nvar __sq_{uid} := PhysicsShapeQueryParameters3D.new()\n__sq_{uid}.shape = __bs_{uid}\n__sq_{uid}.transform = Transform3D(Basis(), {center})\n__sq_{uid}.collision_mask = {mask}\n{into} = []\nfor __hit_{uid} in get_world_3d().direct_space_state.intersect_shape(__sq_{uid}, {max_results}):\n\t{into}.append(__hit_{uid}.get(\"collider\"))", CAT_OVERLAP_3D, "query bodies in box {size} at {center} into {into}", "Collects every physics object inside a box into a variable - room triggers, rectangular blast zones, selection volumes.", "Node3D").param("into", "data", "Into Variable", "Variable receiving the Array of overlapping objects.", "variable_reference").param("center", "global_position", "Center", "Box center in world space (Vector3 expression).", "expression").param("size", "Vector3(4, 4, 4)", "Size", "Full width, height and depth of the box.", "expression").param("mask", "4294967295", "Mask", "Collision layers to test against.", "expression").param("max_results", "32", "Max Results", "Most objects to collect.", "expression"))
	descriptors.append(F.act("CastSphereMotion3D", "Cast Sphere Motion Into (3D)", "var __ss_{uid} := SphereShape3D.new()\n__ss_{uid}.radius = {radius}\nvar __sq_{uid} := PhysicsShapeQueryParameters3D.new()\n__sq_{uid}.shape = __ss_{uid}\n__sq_{uid}.transform = Transform3D(Basis(), {from})\n__sq_{uid}.motion = {motion}\n__sq_{uid}.collision_mask = {mask}\nvar __cm_{uid} := get_world_3d().direct_space_state.cast_motion(__sq_{uid})\n{into} = __cm_{uid}[0] if __cm_{uid}.size() > 0 else 1.0", CAT_3D, "Cast sphere motion {motion} into {into}", "Asks how far a sphere could travel before something stops it, as a fraction of the move (1 means the whole path is clear) - the reliable way to move a fast object without tunnelling through walls.", "Node3D").param("into", "travel", "Into Variable", "Variable receiving how much of the move is clear, from 0 to 1.", "variable_reference").param("from", "global_position", "From", "Where the sphere starts (Vector3 expression).", "expression").param("motion", "Vector3(0, -10, 0)", "Motion", "The move to test, as an offset from the start.", "expression").param("radius", "0.5", "Radius", "Sphere radius in metres.", "expression").param("mask", "4294967295", "Mask", "Collision layers to test against.", "expression"))


# ── 7. Reading a stored cast result. Cast Ray Into hands back the raw Dictionary Godot produced;
# these name its keys so a sheet never has to know them, and read a variable rather than re-casting. ──
static func _add_ray_result_readers(descriptors: Array[ACEDescriptor]) -> void:
	descriptors.append(F.cond("RayResultHit2D", "Ray Result Hit Something (2D)", "not {result}.is_empty()", CAT_2D, "{result} hit something", "True when the stored cast found something. An empty result means the ray reached its end without touching anything.", "Node2D").param("result", "hit", "Result", "The variable a Cast Ray Into filled.", "variable_reference").featured())
	descriptors.append(F.expr("RayResultCollider2D", "Ray Result Collider (2D)", "{result}.get(\"collider\", null)", CAT_2D, "{result} collider", "The object the stored cast hit, or nothing when it hit thin air.", "Node2D").param("result", "hit", "Result", "The variable a Cast Ray Into filled.", "variable_reference"))
	descriptors.append(F.expr("RayResultPoint2D", "Ray Result Point (2D)", "{result}.get(\"position\", Vector2.ZERO)", CAT_2D, "{result} point", "Where in the world the stored cast struck - spawn the impact spark here.", "Node2D").param("result", "hit", "Result", "The variable a Cast Ray Into filled.", "variable_reference"))
	descriptors.append(F.expr("RayResultNormal2D", "Ray Result Normal (2D)", "{result}.get(\"normal\", Vector2.ZERO)", CAT_2D, "{result} normal", "Which way the surface faces at the hit - reflect the velocity around it to bounce, or align a decal to it.", "Node2D").param("result", "hit", "Result", "The variable a Cast Ray Into filled.", "variable_reference"))
	descriptors.append(F.expr("RayResultShape2D", "Ray Result Shape Index (2D)", "{result}.get(\"shape\", -1)", CAT_2D, "{result} shape index", "Which of the hit object's collision shapes was struck, as an index - tell a headshot from a body shot.", "Node2D").param("result", "hit", "Result", "The variable a Cast Ray Into filled.", "variable_reference"))
	descriptors.append(F.cond("RayResultInGroup2D", "Ray Result Is In Group (2D)", "({result}.get(\"collider\", null) != null and {result}[\"collider\"].is_in_group({group}))", CAT_2D, "{result} is in {group}", "True when the stored cast hit something belonging to a group, checking for nothing-hit first so it is safe on a clear ray.", "Node2D").param("result", "hit", "Result", "The variable a Cast Ray Into filled.", "variable_reference").param("group", "\"enemies\"", "Group", "Group name to test the hit object against.", "expression"))
	descriptors.append(F.cond("RayResultHit3D", "Ray Result Hit Something (3D)", "not {result}.is_empty()", CAT_3D, "{result} hit something", "True when the stored cast found something. An empty result means the ray reached its end without touching anything.", "Node3D").param("result", "hit", "Result", "The variable a Cast Ray Into filled.", "variable_reference").featured())
	descriptors.append(F.expr("RayResultCollider3D", "Ray Result Collider (3D)", "{result}.get(\"collider\", null)", CAT_3D, "{result} collider", "The object the stored cast hit, or nothing when it hit thin air.", "Node3D").param("result", "hit", "Result", "The variable a Cast Ray Into filled.", "variable_reference"))
	descriptors.append(F.expr("RayResultPoint3D", "Ray Result Point (3D)", "{result}.get(\"position\", Vector3.ZERO)", CAT_3D, "{result} point", "Where in the world the stored cast struck - spawn the impact effect or bullet hole here.", "Node3D").param("result", "hit", "Result", "The variable a Cast Ray Into filled.", "variable_reference"))
	descriptors.append(F.expr("RayResultNormal3D", "Ray Result Normal (3D)", "{result}.get(\"normal\", Vector3.ZERO)", CAT_3D, "{result} normal", "Which way the surface faces at the hit - reflect the velocity around it to bounce, or lay a decal flat against it.", "Node3D").param("result", "hit", "Result", "The variable a Cast Ray Into filled.", "variable_reference"))
	descriptors.append(F.expr("RayResultShape3D", "Ray Result Shape Index (3D)", "{result}.get(\"shape\", -1)", CAT_3D, "{result} shape index", "Which of the hit object's collision shapes was struck, as an index - tell a headshot from a body shot.", "Node3D").param("result", "hit", "Result", "The variable a Cast Ray Into filled.", "variable_reference"))
	descriptors.append(F.expr("RayResultFaceIndex3D", "Ray Result Face Index (3D)", "{result}.get(\"face_index\", -1)", CAT_3D, "{result} face index", "Which triangle of a concave mesh was hit, as an index (-1 for other shape types) - for reading per-face surface data like footstep materials.", "Node3D").param("result", "hit", "Result", "The variable a Cast Ray Into filled.", "variable_reference"))
	descriptors.append(F.cond("RayResultInGroup3D", "Ray Result Is In Group (3D)", "({result}.get(\"collider\", null) != null and {result}[\"collider\"].is_in_group({group}))", CAT_3D, "{result} is in {group}", "True when the stored cast hit something belonging to a group, checking for nothing-hit first so it is safe on a clear ray.", "Node3D").param("result", "hit", "Result", "The variable a Cast Ray Into filled.", "variable_reference").param("group", "\"enemies\"", "Group", "Group name to test the hit object against.", "expression"))


# ── 8. Camera picking: the screen-to-world ray. Mouse Ray Origin/Direction already gave the two
# halves; these do the whole job, so "what is under the cursor" is one row instead of vector maths. ──
static func _add_camera_picking(descriptors: Array[ACEDescriptor]) -> void:
	descriptors.append(F.act("CastMouseRayInto3D", "Cast Ray From Mouse Into (3D)", "var __cam_{uid} := get_viewport().get_camera_3d()\nvar __mouse_{uid} := get_viewport().get_mouse_position()\nvar __from_{uid} := __cam_{uid}.project_ray_origin(__mouse_{uid})\nvar __to_{uid} := __from_{uid} + __cam_{uid}.project_ray_normal(__mouse_{uid}) * {distance}\nvar __rq_{uid} := PhysicsRayQueryParameters3D.create(__from_{uid}, __to_{uid}, {mask}, {exclude})\n__rq_{uid}.collide_with_areas = {hit_areas}\n{into} = get_world_3d().direct_space_state.intersect_ray(__rq_{uid})", CAT_3D, "Cast ray from mouse into {into}", "Shoots a ray from the camera through the mouse cursor and stores what it finds - the whole of click-to-select in 3D, in one row. Needs an active Camera3D.", "Node3D").param("into", "hit", "Into Variable", "Variable receiving the hit as a Dictionary (empty when nothing is under the cursor). Read it with the Ray Result ACEs.", "variable_reference").param("distance", "1000.0", "Distance", "How far into the scene to reach, in metres.", "expression").param("mask", "4294967295", "Mask", "Collision layers to test against. The default sees every layer.", "expression").param("exclude", "[]", "Ignore", "Array of physics RIDs to skip.", "expression").param_choice("hit_areas", "false", "Detect Areas", "true to notice Area3D nodes as well as bodies.", ["true", "false"]).featured())
	descriptors.append(F.cond("MouseRayHits3D", "Mouse Ray Hits Something (3D)", "not get_world_3d().direct_space_state.intersect_ray(PhysicsRayQueryParameters3D.create(get_viewport().get_camera_3d().project_ray_origin(get_viewport().get_mouse_position()), get_viewport().get_camera_3d().project_ray_origin(get_viewport().get_mouse_position()) + get_viewport().get_camera_3d().project_ray_normal(get_viewport().get_mouse_position()) * {distance})).is_empty()", CAT_3D, "mouse ray hits something within {distance}", "True when the cursor is over something solid. Casts on the spot - for more than a yes/no answer, use Cast Ray From Mouse Into and read the result.", "Node3D").param("distance", "1000.0", "Distance", "How far into the scene to reach, in metres.", "expression"))
	descriptors.append(F.expr("MouseRayCollider3D", "Mouse Ray Collider (3D)", "get_world_3d().direct_space_state.intersect_ray(PhysicsRayQueryParameters3D.create(get_viewport().get_camera_3d().project_ray_origin(get_viewport().get_mouse_position()), get_viewport().get_camera_3d().project_ray_origin(get_viewport().get_mouse_position()) + get_viewport().get_camera_3d().project_ray_normal(get_viewport().get_mouse_position()) * {distance})).get(\"collider\", null)", CAT_3D, "mouse ray collider within {distance}", "The object under the mouse cursor, or nothing when the cursor is over empty space.", "Node3D").param("distance", "1000.0", "Distance", "How far into the scene to reach, in metres.", "expression"))
	descriptors.append(F.expr("MouseRayPoint3D", "Mouse Ray Point (3D)", "get_world_3d().direct_space_state.intersect_ray(PhysicsRayQueryParameters3D.create(get_viewport().get_camera_3d().project_ray_origin(get_viewport().get_mouse_position()), get_viewport().get_camera_3d().project_ray_origin(get_viewport().get_mouse_position()) + get_viewport().get_camera_3d().project_ray_normal(get_viewport().get_mouse_position()) * {distance})).get(\"position\", Vector3.ZERO)", CAT_3D, "mouse ray point within {distance}", "The world point the cursor is pointing at - where to place a build ghost, a move order marker, or a decal.", "Node3D").param("distance", "1000.0", "Distance", "How far into the scene to reach, in metres.", "expression"))
