# EventForge module - Spatial vocabulary (screen/world, random geometry, surfaces, grids, falloff).
#
# Five families of pure spatial maths the repo kept asking developers to hand-write:
#
#   1. SCREEN AND WORLD - the plugin could already put the mouse INTO the world and had no way to
#      put the world ONTO the screen, so every nameplate, damage number and off-screen arrow was a
#      hand-written canvas-transform line. World Point To Screen and its twins close the loop, plus
#      the 3D projection pair and the frustum wrap that is the missing sibling of the 2D
#      Wrap Inside The Screen in node_aces.
#   2. RANDOM GEOMETRY - randomness here was entirely scalar, so scatter was written as
#      "random angle + random radius", which bunches everything at the centre. Every shape verb
#      below is area-correct (the sqrt / cube-root weighting is baked in).
#   3. SURFACES - the repo hands out surface normals generously (Ray Result Normal, Wall Normal,
#      the Bullet pack's On Bullet Hit payload) and nothing consumed them. Bounce, slide,
#      depenetrate, face-along-motion, safe Look At, and lead-aim are the verbs that consume them.
#   4. GRID MATHS - cell coordinates only existed if you owned a TileMapLayer, because Local To Map
#      is its method. These make the grid a plain idea usable with no tilemap in sight, including a
#      looping condition so "once per cell in range" lands in the loop lane like every other loop.
#   5. FALLOFF - the blast COLLECTORS ship (Query Bodies In Circle, In Sphere) and every body then
#      took identical damage, because nothing said "less the further away".
#
# Everything compiles to plain, dependency-free GDScript. Expressions are single expressions and
# null-safe on their own (a missing 3D camera reads as a zero, never a crash). Templates that must
# NOT be retargeted to another node either lead with a statement keyword or open with a bracket, so
# the builtin "On node" pass leaves them alone - retargeting maths that reads this node's own
# position would silently answer for the wrong node.
#
#   6. THE 3D PAGE - moving, turning, placing and seeing, in the words a reader uses. Every template
#      in that family is EXACTLY the spelling the opened-script reading recognises, which is what
#      makes a line typed by hand and the same line dropped from the picker one row:
#
#        Move In Direction        global_position += -basis.z * speed * delta
#        Rotate Clockwise         rotate_y(deg_to_rad(90.0 * delta))
#        Rotate Toward Facing     basis = basis.slerp(facing, 5.0 * delta)
#        Set Position To Object   global_position = spawn.global_position
#        Align To The Slope       basis = Basis(Quaternion(Vector3.UP, n)) * basis
#        Is Within Angle Of Facing  forward.dot(to_target) > cos(deg_to_rad(45))
#        Point At Angle           Vector2.from_angle(deg_to_rad(a)) * d
#
#      Its DIRECTION parameter is a dropdown of the six words an object's own axes point in, and
#      what it writes is the basis expression - so the reader picks "forward" and the file says
#      `-basis.z`.
# Module contract: see ace_factory.gd - ace_ids/templates are API (compatibility covenant).
@tool
class_name EventForgeSpatialACEs
extends RefCounted

const F := preload("res://addons/eventforge/registration/ace_factory.gd")

const MATH := "Math & Random"
const MOVE := "Movement"
const LOOPS := "Loops"

## The canonical five-geometry dropdown, shared verbatim with Is Within Distance (choose metric)
## in node_aces so a player never meets two different spellings of "how is distance counted".
const CELL_METRIC_OPTIONS: Array = [
	{"key": "0", "label": "Straight line"},
	{"key": "1", "label": "Horizontal only"},
	{"key": "2", "label": "Vertical only"},
	{"key": "3", "label": "Grid steps"},
	{"key": "4", "label": "King moves"}
]

## The two shapes an "everything within N cells" set can take. Kept to two on purpose: these index
## a live branch, and an option the branch cannot answer crashes only when the row is reached.
const RADIUS_SHAPE_OPTIONS: Array = [
	{"key": "0", "label": "Grid steps (diamond)"},
	{"key": "1", "label": "King moves (square)"}
]

## The falloff profile dropdown. "Sharp (squared)" squares the NEARNESS reading, which eases in
## from the rim and holds strength near the centre; it is deliberately not named after the inverse
## square law, which is a different curve (and one that has no finite value at the centre at all).
## The falloff profile dropdown. The key IS the index into the inline array of the three profiles,
## the shipped Is Within Distance (choose metric) idiom - one plain expression, no helper function,
## no runtime library. A fourth "draw your own" profile is deliberately absent: feed this number
## into the shipped Sample Curve expression instead and a designer draws the blast in the Inspector.
const FALLOFF_SHAPE_OPTIONS: Array = [
	{"key": "0", "label": "Linear"},
	{"key": "1", "label": "Sharp (squared)"},
	{"key": "2", "label": "Smooth (ease out)"}
]

## Written out once because it appears three times inside the falloff array (single-pass
## substitution means an option value can never reference another parameter, so the distance
## reading is repeated rather than stored in a local an expression cannot declare).
const _NEARNESS := "clampf(1.0 - {center}.distance_to({point}) / maxf({radius}, 0.001), 0.0, 1.0)"

## The visible rectangle in WORLD space, spelled once. The canvas transform maps world to screen,
## so its inverse maps the screen rectangle back out into the world.
const _WORLD_RECT := "(get_viewport().get_canvas_transform().affine_inverse() * get_viewport().get_visible_rect())"

## The world point a fraction of the way along a curve. Repeated by the two cell-set builders.
const _CELL_STEPS := "maxi(absi({to_cell}.x - {from_cell}.x), absi({to_cell}.y - {from_cell}.y))"


## The picker page these rows are filed on, and its three sections. Written as "page: section" so the
## picker files them the way it files an unscoped row, rather than in one flat list keyed on the node
## type they are scoped to.
const PAGE_MOVE := "3D: Move & Turn"
const PAGE_PLACE := "3D: Place"
const PAGE_SEE := "3D: See"

## The six directions an object's own axes point in, as the dropdown a direction parameter offers:
## the reader picks the WORD, and the file is written the basis expression it is. Kept in the same
## order the sheet says them in - the way you go first, then the way you came, then the sides.
const DIRECTION_OPTIONS: Array = [
	{"key": "-basis.z", "label": "forward"},
	{"key": "basis.z", "label": "backward"},
	{"key": "basis.x", "label": "right"},
	{"key": "-basis.x", "label": "left"},
	{"key": "basis.y", "label": "up"},
	{"key": "-basis.y", "label": "down"}
]


static func get_descriptors() -> Array[ACEDescriptor]:
	var descriptors: Array[ACEDescriptor] = []
	_append_screen_and_world(descriptors)
	_append_random_geometry(descriptors)
	_append_surfaces(descriptors)
	_append_grid(descriptors)
	_append_falloff(descriptors)
	_append_move(descriptors)
	_append_place(descriptors)
	_append_see(descriptors)
	_append_polar(descriptors)
	return descriptors


# ── 1. Screen and world, both ways ────────────────────────────────────────────────────────────
# The canvas transform is the whole story in 2D: it maps world space to screen space, so one
# multiplication goes out and its inverse comes back. In 3D the camera owns the projection, and
# every 3D verb here guards a missing camera rather than faulting in a scene that has none yet.
static func _append_screen_and_world(descriptors: Array[ACEDescriptor]) -> void:
	descriptors.append(F.expr("WorldPointToScreen", "World Point To Screen", "(get_viewport().get_canvas_transform() * {world_point})", MATH, "screen position of [b]{world_point}[/b]", "Where a world point sits on screen right now, camera zoom and scroll included - pin a nameplate, a health bar or a damage number to something that moves. Put the answer on a node that lives on a CanvasLayer and it will track its target without lagging behind the camera.").param_typed("Vector2", "world_point", "Vector2.ZERO", "World Point", "A position in the game world.", "expression").featured())
	descriptors.append(F.expr("ScreenPointToWorld", "Screen Point To World", "(get_viewport().get_canvas_transform().affine_inverse() * {screen_point})", MATH, "world position of screen point [b]{screen_point}[/b]", "The world position under a screen pixel - click-to-place, a gamepad cursor, a HUD marker dragged onto the map. The exact opposite of World Point To Screen, so the two round-trip.").param_typed("Vector2", "screen_point", "Vector2.ZERO", "Screen Point", "A position in screen pixels, with 0,0 at the top-left of the view.", "expression"))
	descriptors.append(F.expr("ProjectToScreen3D", "Project To Screen (3D)", "(get_viewport().get_camera_3d().unproject_position({world_point}) if get_viewport().get_camera_3d() != null else Vector2.ZERO)", MATH, "screen position of 3D point [b]{world_point}[/b]", "Where a 3D world point lands on screen - nameplates over 3D characters, damage numbers, objective pins drawn on a CanvasLayer. Reads as 0,0 while there is no active 3D camera, so it never faults during a scene change. Check Is Behind Camera (3D) first: a point behind you still projects to a number.").param_typed("Vector3", "world_point", "Vector3.ZERO", "World Point", "A position in the 3D world.", "expression"))
	descriptors.append(F.cond("IsPointOnScreen", "Is Point On Screen", "get_viewport().get_visible_rect().grow({margin}).has_point(get_viewport().get_canvas_transform() * {world_point})", MATH, "[b]{world_point}[/b] is on screen (margin [b]{margin}[/b])", "True while a world point is inside the visible view - the honest gate for spawning, culling, showing an off-screen arrow, or holding a tutorial callout until its subject is actually visible.").param_typed("Vector2", "world_point", "Vector2.ZERO", "World Point", "The world position being tested.", "expression").param_typed("float", "margin", "0.0", "Margin", "Pixels of slack outside the view that still count as on screen. Negative pulls the test inward.", "expression").featured())
	descriptors.append(F.cond("IsBehindCamera3D", "Is Behind Camera (3D)", "(get_viewport().get_camera_3d() == null or get_viewport().get_camera_3d().is_position_behind({world_point}))", MATH, "[b]{world_point}[/b] is behind the camera", "True when a 3D point sits behind the camera plane, where its projected screen position is a mirrored lie. The guard every 3D waypoint marker needs before it draws. With no camera in the scene it reads true, so nothing is drawn into a view that does not exist.").param_typed("Vector3", "world_point", "Vector3.ZERO", "World Point", "The 3D position being tested.", "expression"))
	descriptors.append(F.expr("ScreenEdgePositionFor", "Screen Edge Position For", "((get_viewport().get_canvas_transform() * {world_point}).clamp(Vector2({margin}, {margin}), get_viewport().get_visible_rect().size - Vector2({margin}, {margin})))", MATH, "screen edge position for [b]{world_point}[/b] (margin [b]{margin}[/b])", "A screen position that follows a target while it is visible and sticks to the edge of the view once it is not - the off-screen objective arrow, the radar blip, the \"your teammate is over there\" chevron. Pair it with Marker Angle Toward for the rotation.").param_typed("Vector2", "world_point", "Vector2.ZERO", "World Point", "The thing being pointed at.", "expression").param_typed("float", "margin", "48.0", "Margin", "How far in from the edge the marker is parked.", "expression"))
	descriptors.append(F.expr("MarkerAngleToward", "Marker Angle Toward", "rad_to_deg(((get_viewport().get_canvas_transform() * {world_point}) - get_viewport().get_visible_rect().size * 0.5).angle())", MATH, "marker angle toward [b]{world_point}[/b]", "The rotation in degrees an on-screen arrow needs so it points from the middle of the view at a world thing - the other half of the off-screen marker, and it stays right while the camera zooms or rotates.").param_typed("Vector2", "world_point", "Vector2.ZERO", "World Point", "The thing being pointed at.", "expression"))
	descriptors.append(F.expr("VisibleWorldRect", "Visible World Rect", _WORLD_RECT, MATH, "visible world rect", "The rectangle of the world the camera can currently see, in world coordinates - spawn just outside it, cull outside it, clamp a node inside it, or size a minimap to it. Follows the camera's zoom and position with nothing to keep in sync."))
	descriptors.append(F.act("WrapInsideView3D", "Wrap Inside The View (3D)", "var __view_cam_{uid}: Camera3D = get_viewport().get_camera_3d()\nif __view_cam_{uid} != null:\n\tvar __view_size_{uid}: Vector2 = get_viewport().get_visible_rect().size\n\tvar __view_at_{uid}: Vector2 = __view_cam_{uid}.unproject_position(global_position)\n\tif not Rect2(Vector2.ZERO, __view_size_{uid}).has_point(__view_at_{uid}):\n\t\tglobal_position = __view_cam_{uid}.project_position(Vector2(wrapf(__view_at_{uid}.x, 0.0, __view_size_{uid}.x), wrapf(__view_at_{uid}.y, 0.0, __view_size_{uid}.y)), __view_cam_{uid}.global_position.distance_to(global_position))", MOVE, "wrap inside the view", "The Asteroids rule in 3D: leave the right of the view and come back on the left, off the top and back at the bottom, at the same distance from the camera. The missing twin of the 2D Wrap Inside The Screen, for a wrap-around arena or an endless shoal. Does nothing while there is no 3D camera.", "Node3D"))


# ── 2. A random point in a shape ──────────────────────────────────────────────────────────────
# Every one of these is AREA-correct. The obvious spelling - a random angle and a random radius -
# bunches points at the centre, because the outer rings of a circle hold more area than the inner
# ones; sqrt(randf()) in 2D and cbrt in 3D undo that, and this is where that knowledge lives so
# nobody has to remember it at three in the morning.
static func _append_random_geometry(descriptors: Array[ACEDescriptor]) -> void:
	descriptors.append(F.expr("RandomPointInCircle", "Random Point In Circle", "({center} + Vector2.RIGHT.rotated(randf() * TAU) * (sqrt(randf()) * {radius}))", MATH, "random point within [b]{radius}[/b] of [b]{center}[/b]", "An evenly spread random point inside a circle - the sqrt weighting is done for you, so scatter does not bunch up in the middle the way the obvious version does.").param_typed("Vector2", "center", "Vector2.ZERO", "Center", "Middle of the circle.", "expression").param_typed("float", "radius", "100.0", "Radius", "In pixels.", "expression").featured())
	descriptors.append(F.expr("RandomPointOnCircle", "Random Point On Circle", "({center} + Vector2.RIGHT.rotated(randf() * TAU) * {radius})", MATH, "random point on a circle of [b]{radius}[/b] around [b]{center}[/b]", "A random point exactly ON the rim of a circle, never inside it - a spawn ring around the player, orbiting decor, a radial menu slot, the starting point of a homing shot.").param_typed("Vector2", "center", "Vector2.ZERO", "Center", "Middle of the circle.", "expression").param_typed("float", "radius", "300.0", "Radius", "In pixels.", "expression"))
	descriptors.append(F.expr("RandomPointInRing", "Random Point In Ring", "({center} + Vector2.RIGHT.rotated(randf() * TAU) * sqrt(lerpf({inner_radius} * {inner_radius}, {outer_radius} * {outer_radius}, randf())))", MATH, "random point between [b]{inner_radius}[/b] and [b]{outer_radius}[/b] of [b]{center}[/b]", "A random point in the doughnut between two radii - the off-screen spawner that never drops an enemy in the player's lap, and never so far away it never arrives. Evenly spread across the whole band, not crowded against the inner edge.").param_typed("Vector2", "center", "Vector2.ZERO", "Center", "Middle of the ring.", "expression").param_typed("float", "inner_radius", "500.0", "Inner Radius", "Nothing spawns closer than this.", "expression").param_typed("float", "outer_radius", "800.0", "Outer Radius", "Nothing spawns further than this.", "expression").featured())
	descriptors.append(F.expr("RandomPointInRectangle", "Random Point In Rectangle", "({top_left} + Vector2(randf() * {size}.x, randf() * {size}.y))", MATH, "random point in the rect at [b]{top_left}[/b] sized [b]{size}[/b]", "A random point inside an axis-aligned rectangle - loot scatter across a room, prop placement, confetti over a banner, a patrol target inside a zone. Feed it Visible World Rect's position and size to scatter across whatever the camera can see.").param_typed("Vector2", "top_left", "Vector2.ZERO", "Top Left", "Corner the rectangle starts at.", "expression").param_typed("Vector2", "size", "Vector2(400, 240)", "Size", "Width and height in pixels.", "expression"))
	descriptors.append(F.expr("RandomPointInCone", "Random Point In Cone", "({center} + Vector2.RIGHT.rotated(deg_to_rad({facing_degrees}) + randf_range(-deg_to_rad({spread_degrees}) * 0.5, deg_to_rad({spread_degrees}) * 0.5)) * (sqrt(randf()) * {radius}))", MATH, "random point in a [b]{spread_degrees}[/b] cone facing [b]{facing_degrees}[/b] from [b]{center}[/b]", "A random point inside a wedge - shotgun spread, cone attacks, directional scatter, a spray of sparks away from a wall. Facing and spread are in degrees, so the row reads the way you think about it.").param_typed("Vector2", "center", "Vector2.ZERO", "Tip", "Where the wedge starts.", "expression").param_typed("float", "facing_degrees", "0.0", "Facing", "Direction the wedge points, in degrees.", "expression").param_typed("float", "spread_degrees", "30.0", "Spread", "Total width of the cone in degrees, half either side of facing.", "expression").param_typed("float", "radius", "200.0", "Reach", "How far the wedge extends.", "expression"))
	descriptors.append(F.expr("RandomPointAround", "Random Point Around", "({node}.global_position + Vector2.RIGHT.rotated(randf() * TAU) * sqrt(lerpf({min_radius} * {min_radius}, {max_radius} * {max_radius}, randf())))", MATH, "random point [b]{min_radius}[/b] to [b]{max_radius}[/b] around [i]{node}[/i]", "Random scatter around a node that is already in the scene - blood splats around a hit, footprints around a stomp, sparkles around a pickup, a wander target around home. Pick the node instead of typing its position, and the scatter follows it as it moves.").param("node", "get_parent()", "Around", "Node the point is scattered around.", "expression").param_typed("float", "min_radius", "0.0", "Nearest", "Nothing lands closer than this.", "expression").param_typed("float", "max_radius", "24.0", "Furthest", "Nothing lands further than this.", "expression"))
	descriptors.append(F.expr("RandomDirection2D", "Random Direction (2D)", "Vector2.RIGHT.rotated(randf() * TAU)", MATH, "random direction", "A random unit direction in 2D - multiply it by a speed for a random shove, by a distance for a random offset. Always exactly one unit long, so the strength stays where you set it."))
	descriptors.append(F.expr("RandomDirection3D", "Random Direction (3D)", "Vector3.UP.rotated(Vector3.RIGHT, acos(randf_range(-1.0, 1.0))).rotated(Vector3.UP, randf() * TAU)", MATH, "random direction (3D)", "A random unit direction in 3D, evenly spread over the whole sphere. The naive three-random-numbers version crowds the corners of a cube; this one does not, so debris and shrapnel fly out honestly."))
	descriptors.append(F.expr("RandomPointInSphere", "Random Point In Sphere", "({center} + Vector3.UP.rotated(Vector3.RIGHT, acos(randf_range(-1.0, 1.0))).rotated(Vector3.UP, randf() * TAU) * (pow(randf(), 1.0 / 3.0) * {radius}))", MATH, "random point within [b]{radius}[/b] of [b]{center}[/b] (3D)", "An evenly spread random point inside a 3D sphere - spawn clouds, debris fields, flocking targets. The cube-root weighting keeps the middle from filling up first.").param_typed("Vector3", "center", "Vector3.ZERO", "Center", "Middle of the sphere.", "expression").param_typed("float", "radius", "5.0", "Radius", "In metres.", "expression"))
	descriptors.append(F.expr("RandomPointInBox", "Random Point In Box", "({center} + Vector3(randf_range(-1.0, 1.0) * {size}.x, randf_range(-1.0, 1.0) * {size}.y, randf_range(-1.0, 1.0) * {size}.z) * 0.5)", MATH, "random point in a [b]{size}[/b] box at [b]{center}[/b]", "A random point inside an axis-aligned 3D box - scatter trees over a chunk, spawn enemies in a room volume, place ambient audio emitters. Size is the FULL box, measured around the centre.").param_typed("Vector3", "center", "Vector3.ZERO", "Center", "Middle of the box.", "expression").param_typed("Vector3", "size", "Vector3(10, 4, 10)", "Size", "Full width, height and depth.", "expression"))
	descriptors.append(F.expr("RandomPointOnScreenEdge", "Random Point On Screen Edge", "(%s.position + %s.size * [Vector2(randf(), 0.0), Vector2(randf(), 1.0), Vector2(0.0, randf()), Vector2(1.0, randf())][randi() %% 4])" % [_WORLD_RECT, _WORLD_RECT], MATH, "random point on the screen edge", "A random WORLD position on the border of what the camera can see - the wave spawner that comes in from a random side, ambient wildlife entering the frame, a meteor starting its run. Grow it with Visible World Rect if you want them to appear from just outside."))
	descriptors.append(F.expr("JitterValue", "Jitter", "({value} + {amount} * randf_range(-1.0, 1.0))", MATH, "[b]{value}[/b] jittered by [b]{amount}[/b]", "Nudges a value by a random amount up to the size you give - pitch variation on a sound, a pixel or two of scatter on a decal, a shade of variation on a tint. Works on numbers, vectors and colors as long as the amount is the same kind of value.").param("value", "0.0", "Value", "The number, vector or color being nudged.", "expression").param("amount", "1.0", "By", "The most it can move, as the SAME kind of value - a number for a number, a Vector2 for a position, a Color for a tint.", "expression"))


# ── 3. Bounce, slide and aim (the verbs that CONSUME a normal) ────────────────────────────────
# Every hit trigger and every cast in this plugin hands back a surface normal, and until now
# nothing took one. These are the three lines a developer writes next, always from memory and
# usually wrong the first time: reflect it, slide along it, push out of it. The two Look At
# variants are a crash fix, not a nicety: Godot's own look_at faults when the target is directly
# overhead, because the direction and the up vector are then parallel.
static func _append_surfaces(descriptors: Array[ACEDescriptor]) -> void:
	descriptors.append(F.expr("BounceOffSurface", "Bounce Off Surface", "({velocity}.bounce({normal}.normalized()) * {bounciness})", MOVE, "[b]{velocity}[/b] bounced off [b]{normal}[/b]", "The velocity a moving thing has AFTER hitting a surface - feed it the normal any hit trigger or raycast hands you. Ricochets, pinball, breakout, deflect shields.").param_typed("Vector2", "velocity", "Vector2(300, 0)", "Velocity", "How the thing was moving when it hit.", "expression").param_typed("Vector2", "normal", "Vector2.UP", "Surface Normal", "The normal any hit trigger or raycast hands you.", "expression").param_typed("float", "bounciness", "1.0", "Bounciness", "1 keeps all the speed, 0.6 is a rubber ball, 0 is a dead stop.", "expression").featured())
	descriptors.append(F.expr("SlideAlongSurface", "Slide Along Surface", "({velocity}.slide({normal}.normalized()))", MOVE, "[b]{velocity}[/b] slid along [b]{normal}[/b]", "The velocity left over once the part pushing INTO a surface is removed - a wall slide that keeps you moving along the wall instead of sticking to it, slope movement, a dash that grazes a corner rather than stopping dead.").param_typed("Vector2", "velocity", "Vector2(300, 0)", "Velocity", "How the thing was moving when it met the surface.", "expression").param_typed("Vector2", "normal", "Vector2.UP", "Surface Normal", "The normal any hit trigger or raycast hands you.", "expression"))
	descriptors.append(F.expr("AngleReflected", "Angle Reflected", "rad_to_deg(Vector2.RIGHT.rotated(deg_to_rad({degrees})).bounce({normal}.normalized()).angle())", MOVE, "[b]{degrees}[/b] reflected off [b]{normal}[/b]", "The heading in degrees a thing travels on after bouncing off a surface - the answer to feed straight back into Set Angle Of Motion when a bullet should ricochet instead of dying.").param_typed("float", "degrees", "0.0", "Angle", "The heading it was travelling on, in degrees.", "expression").param_typed("Vector2", "normal", "Vector2.UP", "Surface Normal", "The normal the hit reported.", "expression"))
	descriptors.append(F.expr("PushOutOfSurface", "Push Out Of Surface", "({point} + {normal}.normalized() * {distance})", MOVE, "[b]{point}[/b] pushed [b]{distance}[/b] out of [b]{normal}[/b]", "A position just clear of a surface instead of exactly on it - park a ricocheting bullet, a decal or a spawned effect here. Landing exactly on a surface is how a thing ends up stuck inside it on the next frame, because a ray that starts inside a shape does not report it.").param_typed("Vector2", "point", "Vector2.ZERO", "Hit Point", "Where the hit happened.", "expression").param_typed("Vector2", "normal", "Vector2.UP", "Surface Normal", "The normal the hit reported.", "expression").param_typed("float", "distance", "2.0", "Clearance", "Pixels of daylight to leave between the thing and the surface.", "expression"))
	descriptors.append(F.act("FaceAlongVelocity", "Face Along Velocity", "if {velocity}.length_squared() > 0.0001:\n\trotation = {velocity}.angle()", MOVE, "face along [b]{velocity}[/b]", "Turns this node to point the way it is travelling, and leaves it alone while it is standing still so a stopped thing never snaps back to facing right. Arrows, fish, cars, thrown knives, a camera that leads the motion.", "Node2D").param_typed("Vector2", "velocity", "Vector2.RIGHT", "Velocity", "How this node is moving - Get Velocity on a body, or the direction you are driving it with.", "expression"))
	descriptors.append(F.act("LookAtSafeUp", "Look At (safe up)", "var __look_to_{uid}: Vector3 = {target} - global_position\nif __look_to_{uid}.length_squared() > 0.000001:\n\tlook_at({target}, Vector3.UP if absf(__look_to_{uid}.normalized().y) < 0.999 else Vector3.FORWARD)", MOVE, "look at [b]{target}[/b] (safe up)", "Turns a 3D node to face a point WITHOUT the crash the plain Look At has: when the target is directly overhead or underfoot, the usual up vector points the same way as the look direction and Godot cannot build a rotation from that. This one swaps the up vector at the last moment, and does nothing at all when the target is where the node already is.", "Node3D").param_typed("Vector3", "target", "Vector3.ZERO", "Look At", "The world position to face.", "expression").featured())
	descriptors.append(F.act("LookAtFlat", "Look At (flat)", "var __flat_{uid}: Vector3 = Vector3({target}.x, global_position.y, {target}.z)\nif __flat_{uid}.distance_squared_to(global_position) > 0.000001:\n\tlook_at(__flat_{uid}, Vector3.UP)", MOVE, "look at [b]{target}[/b] (flat)", "Turns a 3D node to face a point but only around the up axis, so a character looks at the player without tipping over to stare at their feet. The rotation every humanoid, turret base and standing NPC actually wants.", "Node3D").param_typed("Vector3", "target", "Vector3.ZERO", "Look At", "The world position to face.", "expression"))
	descriptors.append(F.expr("AimAtMovingTarget", "Aim At Moving Target", "({target_position} + {target_velocity} * ({target_position}.distance_to({shooter_position}) / maxf({projectile_speed}, 0.001)) if {projectile_speed} > {target_velocity}.length() else {target_position})", MOVE, "aim at [b]{target_position}[/b] moving [b]{target_velocity}[/b]", "Where to aim so a shot MEETS a moving target instead of trailing it - the interception point every turret and archer needs. When the target is faster than the shot no lead exists, and it falls back to the target's current spot rather than pointing somewhere absurd.").param_typed("Vector2", "shooter_position", "Vector2.ZERO", "Shooting From", "Where the shot starts.", "expression").param_typed("Vector2", "target_position", "Vector2(200, 0)", "Target At", "Where the target is right now.", "expression").param_typed("Vector2", "target_velocity", "Vector2.ZERO", "Target Moving At", "How the target is moving, in pixels per second.", "expression").param_typed("float", "projectile_speed", "600.0", "Shot Speed", "How fast your shot travels, in pixels per second.", "expression").featured())
	descriptors.append(F.expr("LaunchAngleForArc", "Launch Angle For Arc", "(rad_to_deg(atan2({speed} * {speed} - sqrt(maxf({speed} * {speed} * {speed} * {speed} - {gravity} * ({gravity} * {distance} * {distance} + 2.0 * {height} * {speed} * {speed}), 0.0)), {gravity} * {distance})) if {distance} != 0.0 and {gravity} != 0.0 else 45.0)", MOVE, "launch angle to reach [b]{distance}[/b] away, [b]{height}[/b] up", "The angle in degrees to fire something so it ARCS onto a target - grenades, mortars, catapults, a coin tossed into a counter. Picks the flatter of the two possible arcs, and reads as 45 degrees when the shot cannot reach at all, so a row never produces a number that is not a number.").param_typed("float", "distance", "300.0", "Distance", "How far away the target is, along the ground.", "expression").param_typed("float", "height", "0.0", "Height Difference", "How much higher the target is than the launcher; negative is downhill.", "expression").param_typed("float", "speed", "600.0", "Launch Speed", "How fast the thing leaves the launcher.", "expression").param_typed("float", "gravity", "980.0", "Gravity", "Pull downward, in the same units as the speed.", "expression"))
	descriptors.append(F.expr("TimeToReach", "Time To Reach", "({from_position}.distance_to({to_position}) / maxf({speed}, 0.001))", MOVE, "time for [b]{speed}[/b] to cross [b]{from_position}[/b] to [b]{to_position}[/b]", "How many seconds something moving at a steady speed needs to cover a distance - time a warning before the missile lands, size a tween to match a walk, decide whether the interceptor can get there first.").param_typed("Vector2", "from_position", "Vector2.ZERO", "From", "Where it starts.", "expression").param_typed("Vector2", "to_position", "Vector2(200, 0)", "To", "Where it is going.", "expression").param_typed("float", "speed", "300.0", "Speed", "Pixels per second.", "expression"))


# ── 4. Grid maths without a TileMap ───────────────────────────────────────────────────────────
# Cell coordinates are a plain idea: divide by the cell size and take the floor. The only reason
# they were locked behind a TileMapLayer is that Local To Map is its method. Build grids, inventory
# grids, puzzle boards, chunk keys and tower placement all reason in cells with no tilemap in
# sight. Cell Distance reuses the five-geometry dropdown verbatim from Is Within Distance, and
# For Each Cell In Radius is a real looping condition, so it lands in the loop lane with frame
# spreading and round-trip behaving exactly like the built-in For Each.
static func _append_grid(descriptors: Array[ACEDescriptor]) -> void:
	descriptors.append(F.expr("CellOfPoint", "Cell Of Point", "Vector2i(floori({point}.x / maxf({cell_size}, 0.001)), floori({point}.y / maxf({cell_size}, 0.001)))", MATH, "cell of [b]{point}[/b] on a [b]{cell_size}[/b] grid", "Which grid cell a world position falls in - no TileMapLayer needed, so build grids, inventory slots and chunk keys all speak the same language. Negative positions land in negative cells, which is what a grid that extends left and up actually wants.").param_typed("Vector2", "point", "Vector2.ZERO", "Point", "A world position.", "expression").param_typed("float", "cell_size", "64.0", "Cell Size", "Pixels across one cell. Type Tiles(1) to read your project's own tile size instead.", "expression").featured())
	descriptors.append(F.expr("CenterOfCell", "Center Of Cell", "(Vector2({cell}) * {cell_size} + Vector2({cell_size}, {cell_size}) * 0.5)", MATH, "center of cell [b]{cell}[/b] on a [b]{cell_size}[/b] grid", "The world position at the middle of a grid cell - where the placement ghost sits, where the tower is built, where the piece lands. The exact partner of Cell Of Point, so the pair round-trips.").param_typed("Vector2i", "cell", "Vector2i(0, 0)", "Cell", "The grid cell.", "expression").param_typed("float", "cell_size", "64.0", "Cell Size", "Pixels across one cell.", "expression").featured())
	descriptors.append(F.expr("SnapPointToGrid", "Snap Point To Grid", "{point}.snapped(Vector2({cell_size}, {cell_size}))", MATH, "[b]{point}[/b] snapped to a [b]{cell_size}[/b] grid", "The nearest grid intersection to a loose position - a dragged card falling into its slot, a level editor brush, a UI element clicking onto a column. Rounds to the nearest, so a thing dropped just past halfway moves forward rather than back.").param_typed("Vector2", "point", "Vector2.ZERO", "Point", "The loose world position.", "expression").param_typed("float", "cell_size", "64.0", "Cell Size", "Pixels across one cell.", "expression"))
	descriptors.append(F.expr("SnapPointToGrid3D", "Snap Point To Grid (3D)", "{point}.snapped(Vector3({cell_size}, {cell_size}, {cell_size}))", MATH, "[b]{point}[/b] snapped to a [b]{cell_size}[/b] grid (3D)", "The nearest point on a 3D grid - voxel placement, modular level pieces clicking together, a build cursor that lines up with the floor tiles.").param_typed("Vector3", "point", "Vector3.ZERO", "Point", "The loose world position.", "expression").param_typed("float", "cell_size", "1.0", "Cell Size", "Metres across one cell.", "expression"))
	descriptors.append(F.expr("CellDistance", "Cell Distance", "([Vector2({from_cell}).distance_to(Vector2({to_cell})), float(absi({from_cell}.x - {to_cell}.x)), float(absi({from_cell}.y - {to_cell}.y)), float(absi({from_cell}.x - {to_cell}.x) + absi({from_cell}.y - {to_cell}.y)), float(maxi(absi({from_cell}.x - {to_cell}.x), absi({from_cell}.y - {to_cell}.y)))][{metric}])", MATH, "distance from cell [b]{from_cell}[/b] to [b]{to_cell}[/b], measured as [b]{metric}[/b]", "How far apart two grid cells are, with the same geometry dropdown the rest of the plugin uses: straight line, horizontal or vertical only, grid steps (Manhattan) or king moves (Chebyshev). One expression that fits a roguelike, a strategy game and a puzzle board alike.").param_typed("Vector2i", "from_cell", "Vector2i(0, 0)", "From Cell", "One cell.", "expression").param_typed("Vector2i", "to_cell", "Vector2i(3, 4)", "To Cell", "The other cell.", "expression").param_choice("metric", "3", "Measured As", "How the distance is counted - a roguelike wants Grid steps, a chess board wants King moves.", CELL_METRIC_OPTIONS))
	descriptors.append(F.expr("NeighboursOfCell", "Neighbours Of Cell", "([[{cell} + Vector2i(1, 0), {cell} + Vector2i(-1, 0), {cell} + Vector2i(0, 1), {cell} + Vector2i(0, -1)], [{cell} + Vector2i(1, 0), {cell} + Vector2i(-1, 0), {cell} + Vector2i(0, 1), {cell} + Vector2i(0, -1), {cell} + Vector2i(1, 1), {cell} + Vector2i(1, -1), {cell} + Vector2i(-1, 1), {cell} + Vector2i(-1, -1)], [{cell} + Vector2i(1, 0), {cell} + Vector2i(-1, 0), {cell} + Vector2i(0, 1), {cell} + Vector2i(0, -1), {cell} + Vector2i(1, -1), {cell} + Vector2i(-1, 1)]][{shape}])", MATH, "neighbours of cell [b]{cell}[/b] ([b]{shape}[/b])", "The cells touching a cell, as a list - flood fill, path search, \"is anything next to me\", spreading fire, match-three clearing. Choose four sides, eight including diagonals, or the six neighbours of an axial hex board.").param_typed("Vector2i", "cell", "Vector2i(0, 0)", "Cell", "The cell whose neighbours you want.", "expression").param_choice("shape", "0", "Shape", "How cells touch on this board.", [{"key": "0", "label": "4 sides"}, {"key": "1", "label": "8 including diagonals"}, {"key": "2", "label": "6 hex (axial)"}]))
	descriptors.append(F.expr("CellsInLine", "Cells In Line", "range(%s + 1).map(func(__step: int) -> Vector2i: return Vector2i(roundi(lerpf({from_cell}.x, {to_cell}.x, float(__step) / maxf(float(%s), 1.0))), roundi(lerpf({from_cell}.y, {to_cell}.y, float(__step) / maxf(float(%s), 1.0)))))" % [_CELL_STEPS, _CELL_STEPS, _CELL_STEPS], MATH, "cells in the line from [b]{from_cell}[/b] to [b]{to_cell}[/b]", "Every cell a straight line passes through, in order from one cell to the other - a laser beam's path, tile-based line of sight, a corridor carved between two rooms, a ruler for a ranged attack. Both ends are included.").param_typed("Vector2i", "from_cell", "Vector2i(0, 0)", "From Cell", "Where the line starts.", "expression").param_typed("Vector2i", "to_cell", "Vector2i(4, 2)", "To Cell", "Where the line ends.", "expression"))
	descriptors.append(F.make_descriptor("Core", "CellsInRadius", "Cells In Radius", ACEDescriptor.ACEType.EXPRESSION, _cells_in_radius_template(), "", _cells_in_radius_params(), MATH, "cells within [b]{radius}[/b] of [b]{center}[/b] ([b]{shape}[/b])")
		.described("Every cell within a step radius of a centre cell, as a list - a blast footprint, a range preview, a fog reveal, the tiles a tower covers. Choose the diamond (counting grid steps) or the square (counting king moves)."))
	descriptors.append(F.expr("CellsInRectangle", "Cells In Rectangle", "range({top_left}.y, {top_left}.y + maxi({size}.y, 0)).reduce(func(__rows: Array, __y: int) -> Array: return __rows + range({top_left}.x, {top_left}.x + maxi({size}.x, 0)).map(func(__x: int) -> Vector2i: return Vector2i(__x, __y)), [])", MATH, "cells in the [b]{size}[/b] block at [b]{top_left}[/b]", "Every cell in a rectangular block, row by row - stamping a room, laying out an inventory grid, placing a multi-cell building, clearing a region of fog. An empty or negative size walks nothing rather than looping backwards.").param_typed("Vector2i", "top_left", "Vector2i(0, 0)", "Top Left Cell", "Corner the block starts at.", "expression").param_typed("Vector2i", "size", "Vector2i(3, 3)", "Size In Cells", "How many cells across and down.", "expression"))
	descriptors.append(F.cond("IsCellInBounds", "Is Cell In Bounds", "({cell}.x >= 0 and {cell}.y >= 0 and {cell}.x < {size}.x and {cell}.y < {size}.y)", MATH, "cell [b]{cell}[/b] is inside a [b]{size}[/b] board", "True while a cell is on the board - the guard before every placement, every move and every array lookup keyed by cell. Counting starts at 0,0 in the top-left, so a 20 by 12 board's last cell is 19,11.").param_typed("Vector2i", "cell", "Vector2i(0, 0)", "Cell", "The cell being tested.", "expression").param_typed("Vector2i", "size", "Vector2i(20, 12)", "Board Size", "How many cells the board is across and down.", "expression").featured())
	descriptors.append(F.make_descriptor("Core", "ForEachCellInRadius", "For Each Cell In Radius", ACEDescriptor.ACEType.CONDITION, _cells_in_radius_template(), "", _cells_in_radius_params(), LOOPS, "for each cell within [b]{radius}[/b] of [b]{center}[/b]")
		.described("Runs this event's actions once per cell within a step radius of a centre cell - range previews, blast footprints, fog reveal, area-of-effect highlights. Read the current one as `cell`.").looping("cell").featured())


## The cell-set template, shared by the Cells In Radius EXPRESSION and the For Each Cell In Radius
## LOOPING CONDITION so the two can never drift into disagreeing about what "within 2" means.
## Built as a reduce over rows because an expression cannot declare a local to accumulate into.
static func _cells_in_radius_template() -> String:
	return "(range(-{radius}, {radius} + 1).reduce(func(__rows: Array, __dy: int) -> Array: return __rows + range(-{radius}, {radius} + 1).map(func(__dx: int) -> Vector2i: return {center} + Vector2i(__dx, __dy)), []) as Array).filter(func(__cell: Vector2i) -> bool: return {shape} == 1 or absi(__cell.x - {center}.x) + absi(__cell.y - {center}.y) <= {radius})"


## The parameters both cell-set verbs take. Rebuilt per call: descriptors own their ACEParam
## resources, and two descriptors sharing one param instance would share every later edit.
static func _cells_in_radius_params() -> Array[ACEParam]:
	return [
		F.make_param("center", "Vector2i", "Vector2i(0, 0)", "Center Cell", "The middle of the area.", "expression"),
		F.make_param("radius", "int", "2", "Radius In Cells", "How many steps out from the middle.", "expression"),
		F.make_param("shape", "String", "1", "Shape", "Whether the corners count.", "", RADIUS_SHAPE_OPTIONS)
	]


# ── 5. Falloff and radial force ───────────────────────────────────────────────────────────────
# Distance-weighted strength is the single most reused number in game code, and the repo could
# already COLLECT everything in a blast while giving every body identical damage. Falloff At
# Distance is one number from 1 at the centre to 0 at the edge, safe to multiply straight into
# damage, knockback, screen shake or volume - and reading the same number for all of them is what
# makes an explosion feel like one event instead of four unrelated ones.
static func _append_falloff(descriptors: Array[ACEDescriptor]) -> void:
	descriptors.append(F.expr("FalloffAtDistance", "Falloff At Distance", "([%s, %s * %s, smoothstep(0.0, 1.0, %s)][{shape}])" % [_NEARNESS, _NEARNESS, _NEARNESS, _NEARNESS], MATH, "falloff from [b]{center}[/b] at [b]{point}[/b] within [b]{radius}[/b]", "How strong an effect is at a distance, from 1 at the centre to 0 at the edge - the one number that makes an explosion, a sound, a magnet or a screen shake care how close it was. Anything past the radius reads as 0, so it is safe to multiply straight into damage. For a hand-drawn profile, feed this number into Sample Curve.").param_typed("Vector2", "center", "Vector2.ZERO", "Center", "Where the effect comes from.", "expression").param_typed("Vector2", "point", "Vector2(100, 0)", "Point", "What is being affected.", "expression").param_typed("float", "radius", "200.0", "Radius", "Past this it reads 0.", "expression").param_choice("shape", "2", "Profile", "How quickly the strength drops off with distance.", FALLOFF_SHAPE_OPTIONS).featured())
	descriptors.append(F.expr("StrengthToward", "Strength Toward", "(clampf(1.0 - global_position.distance_to({node}.global_position) / maxf({radius}, 0.001), 0.0, 1.0))", MATH, "strength toward [i]{node}[/i] within [b]{radius}[/b]", "Falloff between THIS node and another one, without spelling out either position - guard suspicion that builds faster the closer you are, a magnet that pulls harder up close, a sound that ducks as you approach. Reads 0 once the other node is out of range.", "Node2D").param("node", "get_parent()", "Toward", "The node the strength is measured against.", "expression").param_typed("float", "radius", "600.0", "Radius", "Past this it reads 0.", "expression"))
	descriptors.append(F.act("ApplyRadialImpulse", "Apply Radial Impulse", "var __blast_{uid}: Vector2 = global_position - {center}\napply_impulse(__blast_{uid}.normalized() * {strength} * clampf(1.0 - __blast_{uid}.length() / maxf({radius}, 0.001), 0.0, 1.0))", MOVE, "apply radial impulse [b]{strength}[/b] from [b]{center}[/b]", "Throws this physics body away from a blast, weaker the further it was - barrels, crates, ragdolls and debris flung by an explosion. One row on the body; the blast only has to say where it happened.", "RigidBody2D").param_typed("Vector2", "center", "Vector2.ZERO", "Blast Center", "Where the explosion went off.", "expression").param_typed("float", "strength", "900.0", "Strength", "The push at the very centre, in impulse units.", "expression").param_typed("float", "radius", "240.0", "Radius", "Past this the push is nothing.", "expression"))
	descriptors.append(F.act("PushGroupAwayFrom", "Push Group Away From", "for __blast_{uid}: Node in get_tree().get_nodes_in_group({group}):\n\tif __blast_{uid} is Node2D and (__blast_{uid} as Node2D).global_position.distance_to({center}) <= maxf({radius}, 0.001):\n\t\t(__blast_{uid} as Node2D).global_position += ((__blast_{uid} as Node2D).global_position - {center}).normalized() * {strength} * clampf(1.0 - (__blast_{uid} as Node2D).global_position.distance_to({center}) / maxf({radius}, 0.001), 0.0, 1.0)", MOVE, "push group [b]{group}[/b] away from [b]{center}[/b] within [b]{radius}[/b]", "Shoves every member of a group away from a point, hardest at the centre and not at all past the radius - the mirror of Pull Group Toward. A shockwave clearing a crowd, a repulsor field, a dash that parts the enemies it passes through.", "Node2D").param("group", "\"enemies\"", "Group", "Group whose members get shoved.", "group_reference").param_typed("Vector2", "center", "global_position", "Away From", "Where the shove comes from.", "expression").param_typed("float", "radius", "240.0", "Radius", "Only members inside this are shoved.", "expression").param_typed("float", "strength", "60.0", "Strength", "Pixels the closest member is moved.", "expression"))
	descriptors.append(F.cond("IsWithinConeOf", "Is Within Cone Of", "({point}.distance_to({origin}) <= maxf({range_px}, 0.0) and absf(angle_difference(deg_to_rad({facing_degrees}), ({point} - {origin}).angle())) <= deg_to_rad({fov_degrees}) * 0.5)", MATH, "[b]{point}[/b] is within a [b]{fov_degrees}[/b] cone of [b]{origin}[/b] facing [b]{facing_degrees}[/b]", "True while a point sits inside a facing wedge - guard vision, spotlight checks, melee arcs, directional blasts. The cheap test to put in front of an expensive raycast: if it is not in the cone, there is nothing to trace.").param_typed("Vector2", "origin", "Vector2.ZERO", "Cone From", "Tip of the wedge - the guard, the spotlight, the blast.", "expression").param_typed("float", "facing_degrees", "0.0", "Facing", "Which way the wedge points, in degrees.", "expression").param_typed("Vector2", "point", "Vector2(100, 0)", "Point", "The position being tested.", "expression").param_typed("float", "fov_degrees", "70.0", "Cone Width", "Total width of the wedge in degrees.", "expression").param_typed("float", "range_px", "600.0", "Reach", "How far the wedge extends, in pixels.", "expression").featured())


## Moving and turning: one of six directions at a speed, the three turns in degrees a second, and
## turning toward a facing rather than snapping to it.
static func _append_move(descriptors: Array[ACEDescriptor]) -> void:
	descriptors.append(F.act("MoveInDirection3D", "Move In Direction", "global_position += {direction} * {speed} * {delta_t}", PAGE_MOVE, "Move [b]{direction}[/b] at [i]{speed}[/i]", "Moves a 3D node along one of its own directions - forward, back, right, left, up or down - at a speed a second.", "Node3D").param_choice("direction", "-basis.z", "Direction", "Which of its own six directions to move along.", DIRECTION_OPTIONS).param("speed", "6.0", "Speed", "Units a second.", "expression").param("delta_t", "delta", "Delta", "Frame time; defaults to `delta`.", "expression"))
	# The minus is the whole point of this row: a POSITIVE `rotate_y` turns an object to its own left,
	# which is counter-clockwise seen from above, so a row that says clockwise has to write the turn
	# the other way round or its words would be a lie. It sits outside `deg_to_rad` so a reader who
	# types a negative amount gets `-deg_to_rad(-30.0 * delta)` rather than `--30.0`.
	descriptors.append(F.act("RotateClockwise3D", "Rotate Clockwise", "rotate_y(-deg_to_rad({degrees_per_second} * {delta_t}))", PAGE_MOVE, "Rotate [b]clockwise[/b] at [i]{degrees_per_second}[/i]°/s", "Turns a 3D node about its up axis - the yaw a character or a turret turns with.", "Node3D").param("degrees_per_second", "90.0", "Degrees per second", "Degrees a second, turning clockwise seen from above; a negative number turns the other way.", "expression").param("delta_t", "delta", "Delta", "Frame time; defaults to `delta`.", "expression"))
	descriptors.append(F.act("RotatePitch3D", "Rotate Up Or Down", "rotate_x(deg_to_rad({degrees_per_second} * {delta_t}))", PAGE_MOVE, "Rotate [b]up[/b] at [i]{degrees_per_second}[/i]°/s", "Tilts a 3D node's nose up or down - the pitch a plane or a camera arm moves with.", "Node3D").param("degrees_per_second", "45.0", "Degrees per second", "Degrees a second; a negative number tilts the other way.", "expression").param("delta_t", "delta", "Delta", "Frame time; defaults to `delta`.", "expression"))
	descriptors.append(F.act("Roll3D", "Roll", "rotate_z(deg_to_rad({degrees_per_second} * {delta_t}))", PAGE_MOVE, "Roll [b]left[/b] at [i]{degrees_per_second}[/i]°/s", "Rolls a 3D node about the way it faces - the bank a plane or a ship leans with.", "Node3D").param("degrees_per_second", "45.0", "Degrees per second", "Degrees a second; a negative number rolls the other way.", "expression").param("delta_t", "delta", "Delta", "Frame time; defaults to `delta`.", "expression"))
	descriptors.append(F.act("RotateToward3DFacing", "Rotate Toward Facing", "basis = basis.slerp({facing}, {rate} * {delta_t})", PAGE_MOVE, "Rotate toward [i]{facing}[/i] at [i]{rate}[/i]", "Turns a 3D node smoothly toward a facing instead of snapping to it - the way a turret leads its target.", "Node3D").param("facing", "Basis.IDENTITY", "Facing", "The facing to turn toward - Facing Along a direction gives you one.", "expression").param("rate", "5.0", "Rate", "How fast it closes the gap, per second. Bigger turns harder.", "expression").param("delta_t", "delta", "Delta", "Frame time; defaults to `delta`.", "expression"))
	# Not scoped to a node on purpose: it reads a DIRECTION and gives a facing back, touching no
	# object at all, and a node-scoped expression would be handed a `<node>.` prefix that cannot
	# parse in front of `Basis.looking_at`.
	descriptors.append(F.expr("FacingAlong3D", "Facing Along", "Basis.looking_at({direction})", PAGE_MOVE, "facing along {direction}", "The facing that looks along a direction - what Rotate Toward Facing turns toward.").param("direction", "Vector3.FORWARD", "Direction", "The direction to face along.", "expression"))


## Placing things in the world: on another object, and tilted onto the ground's slope.
static func _append_place(descriptors: Array[ACEDescriptor]) -> void:
	descriptors.append(F.act("SetPositionToObject3D", "Set Position To Another Object", "global_position = {other}.global_position", PAGE_PLACE, "Set position to [b]{other}[/b]", "Puts a 3D node exactly where another one is - how a spawn point, a socket or a respawn marker is used.", "Node3D").param("other", "self", "Other", "The object to stand where - a spawn marker, a socket, another character.", "expression"))
	# The snap-to-floor run, written exactly as the reading recognises it - the ray straight down
	# from where the object is, the cast, the is-empty guard and the hit taken back. Four lines,
	# because that is what Godot needs; one row, because that is what it means.
	descriptors.append(F.act("PlaceOnGround3D", "Place On The Ground", "var __drop_query_{uid} := PhysicsRayQueryParameters3D.create(" + "global_position, global_position + Vector3.DOWN * {reach})\n" + "var __drop_hit_{uid} := get_world_3d().direct_space_state.intersect_ray(__drop_query_{uid})\n" + "if not __drop_hit_{uid}.is_empty():\n" + "\tglobal_position = __drop_hit_{uid}.position", PAGE_PLACE, "Place on the [b]ground[/b] [i]reach {reach}[/i]", "Drops a 3D node straight down onto whatever is under it - the snap-to-floor every spawn, item drop and building placement ends with. Leaves it where it is when nothing is within reach.", "Node3D").param("reach", "100.0", "Reach", "How far down to look for ground, in units. Nothing moves when there is none within reach.", "expression"))
	descriptors.append(F.act("AlignToGroundSlope3D", "Align To The Ground's Slope", "basis = Basis(Quaternion(Vector3.UP, {normal})) * basis", PAGE_PLACE, "Align to the ground's [b]slope[/b]", "Tilts a 3D node so its up points the way the ground does - the line that makes a dropped crate sit flat on a hill.", "Node3D").param("normal", "Vector3.UP", "Ground normal", "The way the surface faces - a ray hit gives you one as its `normal`.", "expression"))


## The facing questions: how far off facing something is, and which side of an object it is on.
static func _append_see(descriptors: Array[ACEDescriptor]) -> void:
	descriptors.append(F.cond("IsWithinAngleOfFacing3D", "Is Within Angle Of Facing", "{forward}.dot({direction}) > cos(deg_to_rad({angle}))", PAGE_SEE, "Is within [b]{angle}[/b]° of facing [i]{direction}[/i]", "Asks whether something is inside the cone this object is looking down - a vision cone, a backstab check, an aim assist.", "Node3D").param("forward", "-basis.z", "Facing", "The way this object faces. Its own forward, unless you say otherwise.", "expression").param("direction", "Vector3.FORWARD", "Toward", "The direction to the thing being looked for - Direction To gives you one.", "expression").param("angle", "45.0", "Within", "Half the width of the cone, in degrees. 45 is a 90-degree field of view.", "expression"))
	descriptors.append(F.cond("IsBehindObject3D", "Is Behind", "to_local({point}).z > 0.0", PAGE_SEE, "[i]{point}[/i] is [b]behind[/b] it", "Asks whether a place is behind this object - the backstab half of a facing test.", "Node3D").param("point", "Vector3.ZERO", "Point", "The place being asked about.", "expression"))
	descriptors.append(F.cond("IsInFrontOfObject3D", "Is In Front Of", "to_local({point}).z < 0.0", PAGE_SEE, "[i]{point}[/i] is [b]in front of[/b] it", "Asks whether a place is in front of this object, whichever way it happens to be turned.", "Node3D").param("point", "Vector3.ZERO", "Point", "The place being asked about.", "expression"))
	descriptors.append(F.cond("IsToTheRightOfObject3D", "Is To The Right Of", "to_local({point}).x > 0.0", PAGE_SEE, "[i]{point}[/i] is [b]to the right of[/b] it", "Asks whether a place is off this object's right side - which way to lean, dodge or steer.", "Node3D").param("point", "Vector3.ZERO", "Point", "The place being asked about.", "expression"))
	descriptors.append(F.cond("IsToTheLeftOfObject3D", "Is To The Left Of", "to_local({point}).x < 0.0", PAGE_SEE, "[i]{point}[/i] is [b]to the left of[/b] it", "Asks whether a place is off this object's left side - the twin of Is To The Right Of.", "Node3D").param("point", "Vector3.ZERO", "Point", "The place being asked about.", "expression"))


## Angle and distance, both ways: the point an angle and a distance name, a ring of things placed
## evenly around a circle, and the pair of locals that reads a place back as an angle and a distance.
static func _append_polar(descriptors: Array[ACEDescriptor]) -> void:
	descriptors.append(F.expr("PointAtAngle", "Point At Angle", "Vector2.from_angle(deg_to_rad({angle})) * {distance}", "Math & Random", "the point at angle {angle}, distance {distance}", "The point an angle and a distance name. Add it to a centre for a place on a circle; grow the distance every tick and it draws a spiral.").param("angle", "0.0", "Angle", "The angle, in degrees.", "expression").param("distance", "100.0", "Distance", "How far out to go.", "expression"))
	descriptors.append(F.act("CreateAroundCircle", "Create Evenly Around A Circle", "for __ring_{uid} in {count}:\n" + "\tvar __ring_angle_{uid} := TAU * float(__ring_{uid}) / float({count})\n" + "\tvar __ring_node_{uid} = load({scene}).instantiate()\n" + "\tadd_child(__ring_node_{uid})\n" + "\t__ring_node_{uid}.position = {centre}" + " + Vector2(cos(__ring_angle_{uid}), sin(__ring_angle_{uid})) * {radius}", "Scene", "Create [b]{count}[/b] of {scene} evenly around a circle of [i]{radius}[/i]", "Places a number of copies evenly around a circle - the bullet-hell ring, the radial menu, the circle of pillars.").param("count", "8", "How many", "How many to place.", "expression").param("scene", "\"res://bullet.tscn\"", "Scene", "The scene to place.", "scene_path").param("centre", "Vector2.ZERO", "Centre", "The middle of the circle.", "expression").param("radius", "120.0", "Radius", "How far out from the centre they sit.", "expression"))
	descriptors.append(F.act("StoreAsAngleAndDistance", "Store As Angle And Distance", "var {angle_name} := {from}.angle_to_point({to})\n" + "var {distance_name} := {from}.distance_to({to})", "Math & Random", "Store [i]{from}[/i] to [i]{to}[/i] as [b]{angle_name}[/b] and [b]{distance_name}[/b]", "Reads a place back the other way - as the angle from one point to another and how far apart they are, both named in one drop.").param("from", "Vector2.ZERO", "From", "The place to measure from.", "expression").param("to", "Vector2(100, 0)", "To", "The place to measure to.", "expression").param("angle_name", "aim_angle", "Angle name", "What to call the angle.", "expression").param("distance_name", "aim_distance", "Distance name", "What to call the distance.", "expression"))
