# EventForge module - System (event-sheet System parity)
#
# Time/engine, display, text expressions, comparisons, shader/date/platform info,
# stateful Every X Seconds and the multi-line Spawn Scene At.
# Module contract: see ace_factory.gd - ace_ids/templates are API (compatibility
# covenant); this file only changes where the descriptors are AUTHORED.
@tool
class_name EventForgeSystemACEs
extends RefCounted

const F := preload("res://addons/eventforge/registration/ace_factory.gd")


static func get_descriptors() -> Array[ACEDescriptor]:
	var descriptors: Array[ACEDescriptor] = []

	# ── Event-sheet System coverage: time/engine, display, text expressions, comparisons ──
	descriptors.append(F.act("SetTimeScale", "Set Time Scale", "Engine.time_scale = {scale}", "Time", "Set time scale to {scale}", "Speeds up or slows the whole game; use for slow-motion or pausing.").param("scale", "1.0", "Scale", "1 = normal, 0.5 = slow motion, 0 = paused physics/process.", "expression"))
	descriptors.append(F.expr("GetTimeScale", "Time Scale", "Engine.time_scale", "Time", "time scale", "Gives the current game speed (1 = normal, below 1 = slow motion)."))
	descriptors.append(F.expr("GetGameTime", "Game Time", "(Time.get_ticks_msec() / 1000.0)", "Time", "game time (seconds)", "Gives seconds elapsed since the game started, handy for timers."))
	descriptors.append(F.expr("GetFps", "FPS", "Engine.get_frames_per_second()", "Time", "fps", "Gives the current frames per second, useful for performance checks."))
	descriptors.append(F.expr("GetFrameCount", "Frame Count", "Engine.get_process_frames()", "Time", "frame count", "Gives how many frames have run since startup."))
	descriptors.append(F.act("SetFullscreen", "Set Fullscreen Mode", "DisplayServer.window_set_mode({mode})", "Display", "Set window mode to {mode}", "Switches the game window between windowed, fullscreen and other display modes.").param_choice("mode", "DisplayServer.WINDOW_MODE_FULLSCREEN", "Mode", "Window mode.", ["DisplayServer.WINDOW_MODE_FULLSCREEN", "DisplayServer.WINDOW_MODE_EXCLUSIVE_FULLSCREEN", "DisplayServer.WINDOW_MODE_WINDOWED", "DisplayServer.WINDOW_MODE_MAXIMIZED"]))
	descriptors.append(F.act("SetWindowSize", "Set Window Size", "DisplayServer.window_set_size({size})", "Display", "Set window size to {size}", "Resizes the game window to a chosen pixel width and height.").param("size", "Vector2i(1280, 720)", "Size", "Window size in pixels.", "expression"))
	descriptors.append(F.expr("GetWindowWidth", "Window Width", "DisplayServer.window_get_size().x", "Display", "window width", "Gives the current window width in pixels."))
	descriptors.append(F.expr("GetWindowHeight", "Window Height", "DisplayServer.window_get_size().y", "Display", "window height", "Gives the current window height in pixels."))
	# Text (event-sheet System string expressions -> direct String methods)
	# The beginner text-building hero: {name} placeholders, no printf codes to learn ("%d" never
	# appears). Compiles to String.format with a Dictionary - plain GDScript, zero runtime.
	descriptors.append(F.expr("TextFromPattern", "Text From Pattern", "{pattern}.format({values})", "Text", "text from {pattern}", "Builds text by filling {name} slots in a pattern - \"{player} scored {score}!\" becomes \"Ada scored 300!\". The friendly way to mix words and values, no format codes.").param("pattern", "\"{score} points\"", "Pattern", "Text with {name} slots, e.g. \"{player} scored {score}!\".", "expression").param("values", "{\"score\": 100}", "Values", "What fills the slots: {\"name\": value, ...} - e.g. {\"player\": player_name, \"score\": score}.", "expression").featured())
	descriptors.append(F.expr("TextTokenAt", "Token At", "{text}.get_slice({separator}, {index})", "Text", "tokenat({text}, {index})", "Splits text by a separator and gives the chosen piece, like a CSV column.").param("text", "text", "Text", "Source string.", "expression").param("separator", "\",\"", "Separator", "Token separator.", "expression").param("index", "0", "Index", "Token index.", "expression"))
	descriptors.append(F.expr("TextTokenCount", "Token Count", "{text}.get_slice_count({separator})", "Text", "tokencount({text})", "Gives how many pieces text breaks into when split by a separator.").param("text", "text", "Text", "Source string.", "expression").param("separator", "\",\"", "Separator", "Token separator.", "expression"))
	descriptors.append(F.expr("TextFind", "Find In Text", "{text}.find({needle})", "Text", "find({needle})", "Gives where a substring first appears in text, or -1 if it's missing.").param("text", "text", "Text", "Source string.", "expression").param("needle", "\"a\"", "Find", "Substring to find (-1 when missing).", "expression"))
	descriptors.append(F.expr("TextLeft", "Left", "{text}.left({count})", "Text", "left({text}, {count})", "Gives the first few characters from the start of some text.").param("text", "text", "Text", "Source string.", "expression").param("count", "3", "Count", "Characters from the left.", "expression"))
	descriptors.append(F.expr("TextRight", "Right", "{text}.right({count})", "Text", "right({text}, {count})", "Gives the last few characters from the end of some text.").param("text", "text", "Text", "Source string.", "expression").param("count", "3", "Count", "Characters from the right.", "expression"))
	descriptors.append(F.expr("TextMid", "Mid", "{text}.substr({from}, {count})", "Text", "mid({text}, {from}, {count})", "Gives a chunk of text starting at a position for a set length.").param("text", "text", "Text", "Source string.", "expression").param("from", "0", "From", "Start index.", "expression").param("count", "3", "Count", "Length.", "expression"))
	descriptors.append(F.expr("TextUpper", "Uppercase", "{text}.to_upper()", "Text", "uppercase({text})", "Gives the text converted to all uppercase letters.").param("text", "text", "Text", "Source string.", "expression"))
	descriptors.append(F.expr("TextLower", "Lowercase", "{text}.to_lower()", "Text", "lowercase({text})", "Gives the text converted to all lowercase letters.").param("text", "text", "Text", "Source string.", "expression"))
	descriptors.append(F.expr("TextLength", "Text Length", "{text}.length()", "Text", "len({text})", "Gives how many characters are in some text.").param("text", "text", "Text", "Source string.", "expression"))
	descriptors.append(F.expr("TextReplace", "Replace In Text", "{text}.replace({what}, {with})", "Text", "replace({text})", "Gives the text with every match of one substring swapped for another.").param("text", "text", "Text", "Source string.", "expression").param("what", "\"a\"", "Find", "Substring to replace.", "expression").param("with", "\"b\"", "With", "Replacement.", "expression"))
	descriptors.append(F.expr("TextTrim", "Trim", "{text}.strip_edges()", "Text", "trim({text})", "Gives the text with leading and trailing whitespace removed.").param("text", "text", "Text", "Source string.", "expression"))
	descriptors.append(F.expr("TextZeroPad", "Zero Pad", "(\"%0*d\" % [{digits}, {value}])", "Text", "zeropad({value}, {digits})", "Gives a number padded with leading zeros to a fixed width, like 007.").param("digits", "3", "Digits", "Total width.", "expression").param("value", "7", "Value", "Integer to pad.", "expression"))
	descriptors.append(F.expr("ToText", "To Text", "str({value})", "Text", "str({value})", "Gives any value as text, for joining into messages and labels.").param("value", "42", "Value", "Any value to turn into text.", "expression"))

	# Math expressions (the everyday number toolkit - degree-based trig included so angles read
	# the way sheet authors expect, no radians required)
	descriptors.append(F.expr("MathAbs", "Absolute Value", "absf({value})", "Math & Random", "abs({value})", "Gives the number without its sign: abs(-5) is 5.").param("value", "-5.0", "Value", "Number to strip the sign from.", "expression"))
	descriptors.append(F.expr("MathSqrt", "Square Root", "sqrt({value})", "Math & Random", "sqrt({value})", "Gives the square root of a number.").param("value", "9.0", "Value", "Number to take the root of.", "expression"))
	descriptors.append(F.expr("MathPow", "Power", "pow({base}, {exponent})", "Math & Random", "{base} ^ {exponent}", "Gives a number raised to a power: 2 ^ 8 is 256.").param("base", "2.0", "Base", "The number to raise.", "expression").param("exponent", "8.0", "Exponent", "The power to raise it to.", "expression"))
	descriptors.append(F.expr("MathExp", "Exponential", "exp({value})", "Math & Random", "exp({value})", "Gives e raised to a power, the natural growth curve.").param("value", "1.0", "Value", "The exponent for e.", "expression"))
	descriptors.append(F.expr("MathPi", "Pi", "PI", "Math & Random", "pi", "Gives the circle constant 3.14159…"))
	descriptors.append(F.expr("SinDegrees", "Sin (degrees)", "sin(deg_to_rad({degrees}))", "Math & Random", "sin({degrees})", "Gives the sine of an angle given in degrees - waves, bobbing, circular motion.").param("degrees", "90.0", "Degrees", "Angle in degrees.", "expression"))
	descriptors.append(F.expr("CosDegrees", "Cos (degrees)", "cos(deg_to_rad({degrees}))", "Math & Random", "cos({degrees})", "Gives the cosine of an angle given in degrees.").param("degrees", "0.0", "Degrees", "Angle in degrees.", "expression"))
	descriptors.append(F.expr("TanDegrees", "Tan (degrees)", "tan(deg_to_rad({degrees}))", "Math & Random", "tan({degrees})", "Gives the tangent of an angle given in degrees.").param("degrees", "45.0", "Degrees", "Angle in degrees.", "expression"))
	descriptors.append(F.expr("ToInteger", "To Integer", "int({value})", "Math & Random", "int({value})", "Gives the value as a whole number: int(\"42\") is 42, int(3.9) is 3.").param("value", "\"42\"", "Value", "Text or number to convert.", "expression"))
	descriptors.append(F.expr("ToDecimal", "To Decimal", "float({value})", "Math & Random", "float({value})", "Gives the value as a decimal number: float(\"3.5\") is 3.5.").param("value", "\"3.5\"", "Value", "Text or number to convert.", "expression"))

	# System actions (engine/frame control + the screenshot verb)
	descriptors.append(F.act("TakeScreenshot", "Take Screenshot", "get_viewport().get_texture().get_image().save_png({path})", "General Actions", "Take screenshot to {path}", "Saves what's on screen right now as a PNG file.").param("path", "\"user://screenshot.png\"", "Path", "Where to save the PNG (user:// is the writable folder).", "expression"))
	descriptors.append(F.act("SetMaxFps", "Set Max FPS", "Engine.max_fps = int({fps})", "Time", "Set max fps to {fps}", "Caps how many frames per second the game renders - save battery or steady the pace.").param("fps", "60", "FPS", "Frame cap (0 = uncapped).", "expression"))
	descriptors.append(F.act("SetPhysicsRate", "Set Physics Rate", "Engine.physics_ticks_per_second = int({fps})", "Time", "Set physics rate to {fps}", "Changes how often physics steps per second (default 60).").param("fps", "60", "Ticks", "Physics updates per second.", "expression"))
	descriptors.append(F.act("SetRandomSeed", "Set Random Seed", "seed(int({seed}))", "Math & Random", "Set random seed to {seed}", "Pins the global randomness so a run replays identically - daily challenges, replays, tests.").param("seed", "12345", "Seed", "Any integer - the same seed replays the same randomness.", "expression"))

	# System conditions (angle tests, value-type tests, fullscreen state)
	descriptors.append(F.cond("IsWithinAngle", "Is Within Angle", "absf(rad_to_deg(angle_difference(deg_to_rad({angle}), deg_to_rad({target})))) <= {within}", "Math & Random", "[b]{angle}[/b] is within [b]{within}[/b] of [i]{target}[/i]", "True when two angles are close, taking wrap-around into account (350 is within 20 of 10).").param("angle", "0.0", "Angle", "The angle to test (degrees).", "expression").param("within", "10.0", "Within", "Allowed difference in degrees.", "expression").param("target", "90.0", "Of Angle", "The angle to compare against (degrees).", "expression"))
	descriptors.append(F.cond("IsClockwiseFrom", "Is Clockwise From", "angle_difference(deg_to_rad({from}), deg_to_rad({angle})) >= 0.0", "Math & Random", "{angle} is clockwise from {from}", "True when the shortest turn from the reference angle to this one is clockwise (in 2D screen space, where +Y points down).").param("angle", "45.0", "Angle", "The angle to test (degrees).", "expression").param("from", "0.0", "From", "The reference angle (degrees).", "expression"))
	descriptors.append(F.cond("ValueIsNumber", "Value Is A Number", "(typeof({value}) == TYPE_FLOAT or typeof({value}) == TYPE_INT)", "Math & Random", "{value} is a number", "True when the value holds a number - guard untyped variables and loaded JSON before math.").param("value", "0", "Value", "The value to type-test.", "expression"))
	descriptors.append(F.cond("ValueIsText", "Value Is Text", "typeof({value}) == TYPE_STRING", "Text", "{value} is text", "True when the value holds text - guard untyped variables and loaded JSON before string work.").param("value", "\"text\"", "Value", "The value to type-test.", "expression"))
	descriptors.append(F.cond("IsNaNValue", "Is NaN", "is_nan({value})", "Math & Random", "{value} is NaN", "True when a calculation broke and produced not-a-number (like dividing zero by zero).").param("value", "0.0", "Value", "The number to test.", "expression"))
	descriptors.append(F.cond("IsFullscreen", "Is Fullscreen", "(DisplayServer.window_get_mode() == DisplayServer.WINDOW_MODE_FULLSCREEN or DisplayServer.window_get_mode() == DisplayServer.WINDOW_MODE_EXCLUSIVE_FULLSCREEN)", "Display", "is fullscreen", "True while the game window is in fullscreen mode - pair with Set Fullscreen Mode for a toggle."))

	# Shader params (event-sheet effects -> Godot materials), date & time, platform info
	descriptors.append(F.act("SetShaderParameter", "Set Effect Parameter", "material.set_shader_parameter(&{param}, {value})", "Effects", "Set effect parameter {param} to {value}", "Feeds a value into one of an effect's parameters to drive it at runtime.", "CanvasItem").param("param", "\"strength\"", "Parameter", "The effect parameter's name.").param("value", "1.0", "Value", "Value expression.", "expression"))
	descriptors.append(F.expr("GetDatetimeString", "Date & Time Text", "Time.get_datetime_string_from_system()", "Time", "datetime string", "Gives the system's current date and time as readable text."))
	descriptors.append(F.expr("GetUnixTime", "Date: Now", "Time.get_unix_time_from_system()", "Time", "Date.Now", "Gives the current Unix timestamp in seconds, useful for saving real-world time."))
	# ── the Date object ──────────────────────────────────────────────────────────────────────────
	# The calendar and the wall clock, one expression per field, so a clock label is written the way
	# it reads: `Date.Hour & ":" & Date.Minute`. Each one asks the system clock afresh, which is what
	# a row that shows the time needs; a whole timestamp to compare against is Date.Now.
	descriptors.append(F.expr("DateHour", "Date: Hour", "Time.get_datetime_dict_from_system().hour", "Time", "Date.Hour", "The hour on the system clock right now, 0 to 23."))
	descriptors.append(F.expr("DateMinute", "Date: Minute", "Time.get_datetime_dict_from_system().minute", "Time", "Date.Minute", "The minute on the system clock right now, 0 to 59."))
	descriptors.append(F.expr("DateSecond", "Date: Second", "Time.get_datetime_dict_from_system().second", "Time", "Date.Second", "The second on the system clock right now, 0 to 59."))
	descriptors.append(F.expr("DateYear", "Date: Year", "Time.get_datetime_dict_from_system().year", "Time", "Date.Year", "The year on the system calendar right now."))
	descriptors.append(F.expr("DateMonth", "Date: Month", "Time.get_datetime_dict_from_system().month", "Time", "Date.Month", "The month on the system calendar right now, 1 to 12."))
	descriptors.append(F.expr("DateDay", "Date: Day", "Time.get_datetime_dict_from_system().day", "Time", "Date.Day", "The day of the month on the system calendar right now, 1 to 31."))
	descriptors.append(F.expr("DateWeekday", "Date: Weekday", "Time.get_datetime_dict_from_system().weekday", "Time", "Date.Weekday", "Which day of the week it is right now, 0 for Sunday through 6 for Saturday - what a daily-reward or weekend-bonus row asks."))
	descriptors.append(F.expr("GetOSName", "OS Name", "OS.get_name()", "Platform", "os name", "Gives the name of the operating system the game is running on."))
	# Feature tags upgraded from a fixed 8-entry dropdown to an editable suggest combo: the
	# full curated tag set is one pick away, and a CUSTOM tag (export presets can define
	# any) is typeable - same ace_id, same template, same quoted-value shape, so every
	# existing sheet compiles and lifts unchanged.
	descriptors.append(F.cond("HasOSFeature", "Platform Has Feature", "OS.has_feature({feature})", "Platform", "platform has {feature}", "True when the current platform supports the given feature tag - mobile, web, editor, debug/release, a specific OS, or any custom tag your export preset defines.").param_suggesting("feature", "\"mobile\"", "Feature", "Feature tag to test - pick a common one or type a custom tag from your export preset.", [ "\"mobile\"", "\"pc\"", "\"web\"", "\"android\"", "\"ios\"", "\"windows\"", "\"linux\"", "\"macos\"", "\"editor\"", "\"debug\"", "\"release\"", "\"template\"", "\"template_debug\"", "\"template_release\"", "\"movie\"", "\"threads\"", "\"touchscreen\"", "\"etc2\"", "\"s3tc\"" ], "feature_tag"))
	# Stateful conditions (the Every X seconds pattern): each applied instance owns a member;
	# the prelude accumulates frame time (get_process_delta_time, defined on any Node) before the
	# if, on_true rebases inside it. Compiles under any trigger; best used under a per-frame one.
	descriptors.append(F.cond("EveryXSeconds", "Every X Seconds", "__every_{uid} >= maxf({seconds}, 0.001)", "Time", "Every {seconds} seconds", "True once each time the chosen number of seconds passes, for repeating timers.").param("seconds", "1.0", "Seconds", "Interval between runs (needs a per-frame trigger).", "expression").stateful("var __every_{uid}: float = 0.0", "__every_{uid} += get_process_delta_time()", "__every_{uid} = fmod(__every_{uid}, maxf({seconds}, 0.001))"))
	# Every X To Y Seconds: the varied-cadence sibling of Every X Seconds. Two members per instance -
	# the accumulator and the interval that was rolled for THIS wait - so the helper can fire and
	# immediately re-roll the next gap. The -1 sentinel means "no interval rolled yet", which keeps the
	# very first wait random too instead of always using the minimum.
	descriptors.append(F.cond("EveryRandomSeconds", "Every X To Y Seconds", "__everyr_{uid}(maxf({min_seconds}, 0.001), maxf({max_seconds}, 0.001))", "Time", "Every {min_seconds} to {max_seconds} seconds", "True once each time a random wait between the two lengths passes - spawner and idle-chatter cadence that never looks metronomic. Needs a per-frame trigger, like Every X Seconds; each firing re-rolls the next wait.").param("min_seconds", "2.0", "From", "Shortest wait between runs.", "expression").param("max_seconds", "5.0", "To", "Longest wait between runs.", "expression").stateful("var __everyr_time_{uid}: float = 0.0\nvar __everyr_next_{uid}: float = -1.0\n\nfunc __everyr_{uid}(min_seconds: float, max_seconds: float) -> bool:\n\tif __everyr_next_{uid} < 0.0:\n\t\t__everyr_next_{uid} = randf_range(min_seconds, maxf(max_seconds, min_seconds))\n\tif __everyr_time_{uid} < __everyr_next_{uid}:\n\t\treturn false\n\t__everyr_time_{uid} = 0.0\n\t__everyr_next_{uid} = randf_range(min_seconds, maxf(max_seconds, min_seconds))\n\treturn true", "__everyr_time_{uid} += get_process_delta_time()"))
	# Trigger Once: run the event only on the FIRST tick of each stretch where the row's OTHER conditions
	# hold, re-arming once they go false again. .evaluated_last() HOISTS the term to the end of the emitted
	# `and` chain no matter which condition cell it sits in, so short-circuiting guarantees it is reached
	# exactly when everything else is true - which makes "was I reached on the previous tick?" exactly the
	# question "were the other conditions already true last tick?". The prelude ages a per-instance tick
	# counter every tick; the helper reads it and zeroes it the moment the term is reached, so a gap wider
	# than one tick is the rising edge. On its own (no other conditions) it fires exactly once.
	descriptors.append(F.cond("TriggerOnce", "Trigger Once", "__trigger_once_{uid}()", "Run Context", "Trigger once while true", "True only on the first tick each time the event's other conditions become true, and again after they have gone false. Works in any condition slot.").stateful("var __once_{uid}: int = 1\n\nfunc __trigger_once_{uid}() -> bool:\n\tvar ticks_since_last: int = __once_{uid}\n\t__once_{uid} = 0\n\treturn ticks_since_last > 1", "__once_{uid} += 1").evaluated_last())
	# Has Changed: the "value watcher" edge gate. A per-instance previous-value slot plus a helper
	# that compares and rebases in one call, so the term is a plain bool expression usable in any
	# condition cell. The first tick after the row starts running only SEEDS the slot (returns false),
	# which is why a value that starts different from null does not fire spuriously on frame one.
	descriptors.append(F.cond("HasChanged", "Has Changed", "__has_changed_{uid}({value})", "Run Context", "{value} has changed", "True on any tick where the watched value differs from the tick before (needs a per-frame trigger).").param("value", "0", "Value", "The value to watch - true on the tick it becomes different.", "expression").stateful("var __changed_prev_{uid}: Variant = null\nvar __changed_seen_{uid}: bool = false\n\nfunc __has_changed_{uid}(current: Variant) -> bool:\n\tif not __changed_seen_{uid}:\n\t\t__changed_seen_{uid} = true\n\t\t__changed_prev_{uid} = current\n\t\treturn false\n\tif current == __changed_prev_{uid}:\n\t\treturn false\n\t__changed_prev_{uid} = current\n\treturn true"))
	# Cooldowns: named, stateless, and shared across every row on the host - the deadline lives in
	# node metadata keyed by name, so Start Cooldown here and Cooldown Is Ready in a different event
	# (or a different sheet on the same node) agree without any wiring. No members, no {uid}.
	descriptors.append(F.act("StartCooldown", "Start Cooldown", "set_meta(&\"__ef_cool_\" + str({name}), Time.get_ticks_msec() + int(maxf({seconds}, 0.0) * 1000.0))", "Time", "start cooldown {name} for {seconds}s", "Starts (or restarts) a named cooldown that lasts the given number of seconds.").param("name", "\"dash\"", "Name", "Cooldown name - any label you also use in Cooldown Is Ready.", "expression").param("seconds", "1.0", "Seconds", "How long the cooldown lasts.", "expression"))
	descriptors.append(F.cond("CooldownReady", "Cooldown Is Ready", "Time.get_ticks_msec() >= int(get_meta(&\"__ef_cool_\" + str({name}), 0))", "Time", "cooldown {name} is ready", "True when the named cooldown has finished. A cooldown that was never started counts as ready, so the first use is always allowed.").param("name", "\"dash\"", "Name", "Cooldown name, matching a Start Cooldown action.", "expression"))
	descriptors.append(F.expr("CooldownTimeLeft", "Cooldown Time Left", "(maxf(0.0, float(int(get_meta(&\"__ef_cool_\" + str({name}), 0)) - Time.get_ticks_msec()) / 1000.0))", "Time", "cooldown {name} time left", "Gives the seconds left on a named cooldown, or 0 when it is ready - handy for a HUD readout.").param("name", "\"dash\"", "Name", "Cooldown name, matching a Start Cooldown action.", "expression"))
	# Input buffering: the same name-keyed metadata trick as the cooldowns above, read the other way
	# round - a deadline in the FUTURE means the press still counts. Stateless and shared across the
	# host, so the buffer is written in the input event and read wherever the act actually happens.
	descriptors.append(F.act("BufferPress", "Buffer Press", "set_meta(&\"__ef_buffer_\" + str({name}), Time.get_ticks_msec() + int(maxf({seconds}, 0.0) * 1000.0))", "Time", "buffer press {name} for {seconds}s", "Remembers a press for a fraction of a second, so an input made slightly too early still counts. Record it when the button goes down, check Press Is Buffered where the act happens, then Clear Buffer.").param("name", "\"jump\"", "Name", "Buffer name - any label you also use in Press Is Buffered.", "expression").param("seconds", "0.12", "Seconds", "How long the press stays remembered.", "expression"))
	descriptors.append(F.cond("PressIsBuffered", "Press Is Buffered", "Time.get_ticks_msec() <= int(get_meta(&\"__ef_buffer_\" + str({name}), 0))", "Time", "press {name} is buffered", "True while a recently buffered press is still valid - the player pressed jump just before landing, and it should still fire.").param("name", "\"jump\"", "Name", "Buffer name, matching a Buffer Press action.", "expression"))
	descriptors.append(F.act("ClearBuffer", "Clear Buffer", "set_meta(&\"__ef_buffer_\" + str({name}), 0)", "Time", "clear buffered press {name}", "Forgets a buffered press. Consume the buffer right after acting on it so one press never fires twice.").param("name", "\"jump\"", "Name", "Buffer name, matching a Buffer Press action.", "expression"))
	# Was Recently True: coyote time, said plainly. The helper stamps the moment the watched value was
	# last true and answers "recently?" for the window after it - so "is_on_floor() was true within
	# 0.1s" IS the forgiving jump, with no hand-rolled timer member in the sheet.
	descriptors.append(F.cond("WasRecentlyTrue", "Was Recently True", "__recent_{uid}(bool({value}), maxf({window}, 0.0))", "Run Context", "{value} was true within {window}s", "True while the watched condition is true, and for a moment after it stops. This is coyote time: \"is_on_floor() was true within 0.1s\" lets a player jump just after walking off a ledge. Needs a per-frame trigger so the moment gets stamped.").param("value", "true", "Value", "The condition to remember, e.g. is_on_floor().", "expression").param("window", "0.1", "For Seconds", "How long after it goes false it still counts.", "expression").stateful("var __recent_at_{uid}: int = -1000000\n\nfunc __recent_{uid}(current: bool, window: float) -> bool:\n\tif current:\n\t\t__recent_at_{uid} = Time.get_ticks_msec()\n\t\treturn true\n\treturn Time.get_ticks_msec() - __recent_at_{uid} <= int(window * 1000.0)"))
	# Group population edges: one member remembers last tick's count, so the helper can answer "did
	# this group just empty / just fill?" - the wave director's two triggers. The -1 start means a group
	# that is already empty on the first tick does NOT count as having just emptied.
	#
	# THESE TWO ANSWER THE GROUP AS A WHOLE, which is what separates them from the arrival triggers
	# (On Node Joins Group / On Node Leaves Group). Those ride the tree's own node_added/node_removed
	# signals and say WHICH node, at the moment it happens; these compare a count with last tick's on a
	# per-frame trigger and say "the wave is over" or "combat started". Aggregate here, member there.
	descriptors.append(F.cond("OnGroupEmptied", "On Group Emptied", "__group_emptied_{uid}({group})", "Run Context", "on group {group} emptied", "True on the single tick a watched group's last member leaves or dies - the wave director's trigger, without counting nodes by hand. A group that is already empty at startup never fires it. Needs a per-frame trigger.").param("group", "\"enemies\"", "Group", "Group to watch.", "group_reference").stateful("var __gcount_{uid}: int = -1\n\nfunc __group_emptied_{uid}(group_name: String) -> bool:\n\tvar count: int = get_tree().get_nodes_in_group(group_name).size()\n\tvar previous: int = __gcount_{uid}\n\t__gcount_{uid} = count\n\treturn previous > 0 and count == 0"))
	descriptors.append(F.cond("OnGroupFirstMember", "On Group Gains First Member", "__group_first_{uid}({group})", "Run Context", "on group {group} gains its first member", "True on the single tick a watched group goes from empty to holding something - the wave STARTED, the first pickup spawned, combat just began. Needs a per-frame trigger.").param("group", "\"enemies\"", "Group", "Group to watch.", "group_reference").stateful("var __gfirst_{uid}: int = -1\n\nfunc __group_first_{uid}(group_name: String) -> bool:\n\tvar count: int = get_tree().get_nodes_in_group(group_name).size()\n\tvar previous: int = __gfirst_{uid}\n\t__gfirst_{uid} = count\n\treturn previous == 0 and count > 0"))
	# Once At A Time (single-flight, the async-events re-entry gate): a busy latch set on entry
	# and cleared by the on_exit hook AFTER the whole body - in a coroutine body that reset runs
	# when the last await completes, so a per-frame trigger with a Wait can't stack overlapping
	# runs. The answer GDevelop's async events leave to "be careful".
	descriptors.append(F.cond("SingleFlight", "Once At A Time", "not __busy_{uid}", "Run Context", "Once at a time (skip while still running)", "Skips the event while a previous run is still going. A run that awaits (Wait, Wait For Signal) counts as still going until it finishes - so a per-frame event with a Wait runs one copy at a time instead of stacking a new one every frame.").stateful("var __busy_{uid}: bool = false", "", "__busy_{uid} = true", "__busy_{uid} = false").evaluated_last())
	# Multi-statement template: spawns AND positions (locals get a per-instance uid).
	descriptors.append(F.act("SpawnSceneAt", "Spawn Scene At", "var __spawn_{uid} = load({path}).instantiate()\n__spawn_{uid}.position = {position}\nadd_child(__spawn_{uid})", "Scene", "Spawn {path} at {position}", "Loads a scene and drops a copy into the world at a position.").param("path", "\"res://enemy.tscn\"", "Scene", "Scene file to instance.", "scene_path").param("position", "Vector2(0, 0)", "Position", "Spawn position.", "expression"))
	# Spawn + position + rotation + an optional group tag in one row (replaces a raw load/instantiate block).
	descriptors.append(F.act("SpawnSceneFull", "Spawn Scene (Full)", "var __spawn_{uid} = load({path}).instantiate()\n__spawn_{uid}.position = {position}\n__spawn_{uid}.rotation_degrees = {rotation}\nadd_child(__spawn_{uid})\nif {group} != \"\": __spawn_{uid}.add_to_group({group})", "Scene", "Spawn {path} (rot {rotation}, group {group})", "Spawns a scene copy with position, rotation and an optional group in one step.").param("path", "\"res://enemy.tscn\"", "Scene", "Scene file to instance.", "scene_path").param("position", "Vector2(0, 0)", "Position", "Spawn position.", "expression").param("rotation", "0.0", "Rotation", "Rotation in degrees.", "expression").param("group", "\"\"", "Group", "Optional group to add the spawned node to (blank = none).", "group_reference"))
	# Generic comparisons (event-sheet System: compare two values / is between values)
	descriptors.append(F.cond("CompareValues", "Compare Values", "{a} {op} {b}", "General Conditions", "{a} {op} {b}", "True when two values match your chosen comparison, like equal, greater or less than.").param("a", "0", "First", "Left value.", "expression").param_choice("op", "==", "Operator", "Comparison.", F.COMPARISON_OPTIONS).param("b", "0", "Second", "Right value.", "expression"))
	descriptors.append(F.cond("IsBetween", "Is Between Values", "({min} <= {value} and {value} <= {max})", "General Conditions", "{value} is between {min} and {max}", "True when a value falls within a low and high range, bounds included.").param("value", "0", "Value", "Value to test.", "expression").param("min", "0", "Min", "Lower bound (inclusive).", "expression").param("max", "10", "Max", "Upper bound (inclusive).", "expression"))
	# ── the questions an opened script reads in these same words ───────────────────────
	# Every template here is the exact line the reading claims, so a row picked in the editor and a
	# line typed in a .gd file are the same line, and the sheet says the same sentence about both.
	descriptors.append(F.cond("IsBetweenAngles", "Is Between Angles", "(wrapf({angle}, 0.0, 360.0) >= {low} and wrapf({angle}, 0.0, 360.0) <= {high})", "Math & Random", "{angle} is between angles {low} and {high}", "True when an angle falls inside a window of directions - a firing arc, a sight cone, a slope band. The angle is wrapped into one turn first, so 370 counts as 10.").param("angle", "0.0", "Angle", "The angle to test, in degrees.", "expression").param("low", "30.0", "From", "Start of the window, in degrees.", "expression").param("high", "60.0", "To", "End of the window, in degrees.", "expression"))
	descriptors.append(F.cond("IsAbout", "Is About", "is_equal_approx({a}, {b})", "Math & Random", "{a} is about {b}", "True when two decimal numbers are near enough to count as the same. Any arithmetic leaves a tiny remainder, so this is the comparison you want wherever == would be a coin flip.").param("a", "0.0", "Value", "Value to test.", "expression").param("b", "0.0", "Is About", "What it should be near.", "expression").featured())
	descriptors.append(F.cond("SecondsPassedSince", "Seconds Have Passed Since", "(Time.get_ticks_msec() - {since} > {seconds} * 1000.0)", "Time", "{seconds} seconds have passed since {since}", "True once a stretch of time has gone by since a moment you stamped with Now - the cooldown every shooting, dashing or spawning row needs, without a timer node.").param("seconds", "0.5", "Seconds", "How long has to have gone by.", "expression").param("since", "0", "Since", "A variable holding the moment you last set to Now.", "expression").featured())
	descriptors.append(F.expr("TimeNow", "Now", "Time.get_ticks_msec()", "Time", "now", "The moment right now, as the game's own running clock. Store it in a variable and ask Seconds Have Passed Since about it later. It restarts with the game."))
	descriptors.append(F.expr("ClockTimeNow", "Date: Now (Clock Time)", "Time.get_unix_time_from_system()", "Time", "Date.Now", "The moment right now by the system clock, in seconds. Unlike Now, this keeps counting while the game is closed - which is what a daily reward or an idle-earnings sum needs."))
	descriptors.append(F.cond("Chance", "Chance", "randf() < {percent} / 100.0", "Math & Random", "{percent}% chance", "True for the given share of the times it is asked - a 30% chance is true roughly three times in ten. The roll is fresh every time the row runs.").param("percent", "30", "Percent", "Chance from 0 to 100.", "expression").featured())
	descriptors.append(F.expr("ViewportWidth", "Viewport Width", "get_viewport_rect().size.x", "Display", "ViewportWidth", "How wide the visible layout is, in pixels - the right edge to spawn at, wrap around, or clamp to.", "CanvasItem"))
	descriptors.append(F.expr("ViewportHeight", "Viewport Height", "get_viewport_rect().size.y", "Display", "ViewportHeight", "How tall the visible layout is, in pixels - the bottom edge to spawn at, wrap around, or clamp to.", "CanvasItem"))
	descriptors.append(F.cond("IsOutsideLayout", "Is Outside Layout", "not get_viewport_rect().has_point({point})", "General Conditions", "Is outside layout", "True when a point has left the visible layout on any side - the bullet-culling and stray-enemy question, in one row instead of four edge comparisons.", "Node2D").param("point", "position", "Point", "The place being tested - usually this object's own position.", "expression").featured())
	descriptors.append(F.cond("IsOnScreen", "Is On-Screen", "get_viewport_rect().has_point({point})", "General Conditions", "Is on-screen", "True while a point is inside the visible layout - the guard that keeps off-screen things from doing expensive work.", "Node2D").param("point", "position", "Point", "The place being tested - usually this object's own position.", "expression"))
	descriptors.append(F.cond("IsInsideArea", "Is Inside Area", "{area}.has_point({point})", "General Conditions", "{point} is inside area {area}", "True when a point falls inside a rectangle - a zone, a safe area, a spawn band - without needing an Area2D node in the scene.", "Node2D").param("area", "Rect2(0, 0, 640, 360)", "Area", "The rectangle to test against: corner, then size.", "expression").param("point", "position", "Point", "The place being tested - usually this object's own position.", "expression"))
	# Generic boolean escape hatch (the code-free fallback): use any GDScript that returns a bool as a
	# condition - e.g. a behavior method like $Player/WeaponKit.can_fire() - without dropping the whole
	# row to a raw GDScript block. Emitted verbatim (opaque param), so the expression is the user's to
	# get right; it inverts to `not (...)` for free. Prefer a named pack condition where one exists.
	descriptors.append(F.cond("ExpressionIsTrue", "Expression Is True", "{expr}", "General Conditions", "{expr}", "True when your custom GDScript expression evaluates to true; an escape hatch for advanced checks.").param("expr", "true", "Expression", "Any GDScript boolean expression, e.g. $Player/WeaponKit.can_fire() or health > 0.", "expression"))

	# Runtime group toggling (event-sheet Set Group Active): targets the opt-in "runtime
	# toggleable" flag members. The group param is the snake-cased group name.
	descriptors.append(F.act("SetGroupActive", "Set Group Active", "set(\"__group_\" + {group} + \"_active\", {active})", "General Actions", "Set group {group} {active}", "Turns a runtime-toggleable group on or off to enable or disable its behaviour.").param_built(_group_param(F)).param_built(_group_state_param(F)))
	descriptors.append(F.cond("IsGroupActive", "Is Group Active", "bool(get(\"__group_\" + {group} + \"_active\"))", "General Conditions", "Group {group} is active", "True when the named runtime group is currently switched on.").param_built(_group_param(F)))

	# Shader materials (assign / swap / clear / read uniforms - completes the one-uniform
	# SetShaderParameter above into a usable visual-effects surface).
	descriptors.append(F.act("SetShaderMaterial", "Set Effect", "material = {material}", "Effects", "Set effect to {material}", "Puts an effect on this object, changing how it draws.", "CanvasItem").param("material", "null", "Effect", "ShaderMaterial / CanvasItemMaterial resource - e.g. preload(\"res://your_material.tres\") once that file exists. Defaults to null (no effect).", "expression"))
	descriptors.append(F.act("ClearMaterial", "Remove Effect", "material = null", "Effects", "Remove effect", "Takes the effect off this object, returning it to how it normally draws.", "CanvasItem"))
	descriptors.append(F.expr("GetShaderParameter", "Effect Parameter", "material.get_shader_parameter(&{param})", "Effects", "effect parameter {param}", "Gives the current value of one of this object's effect parameters.", "CanvasItem").param("param", "\"strength\"", "Parameter", "The effect parameter's name."))
	# The one tween shape an effect has a sentence for: a parameter driven from one value to another
	# over time, which is how a dissolve, a wipe and a hit flash are all written.
	descriptors.append(F.act("TweenEffectParameter", "Tween Effect Parameter", "create_tween().tween_method(func(v): material.set_shader_parameter(&{param}, v), {from}, {to}, {seconds})", "Effects", "Tween effect parameter {param} from {from} to {to} in {seconds} seconds", "Drives one of an effect's parameters from one value to another over time.", "CanvasItem").param("param", "\"dissolve\"", "Parameter", "The effect parameter's name.").param("from", "0.0", "From", "Starting value.", "expression").param("to", "1.0", "To", "Ending value.", "expression").param("seconds", "0.5", "Seconds", "How long the change takes.", "expression"))


	# Trigger Once, but across RUNS: the first true ever (per key, per machine) - tutorial hints
	# and first-time cutscenes. State lives in the same user://remembered.cfg Remember Between
	# Runs uses, cached in a member after the first read so the file is touched once per session.
	descriptors.append(F.cond("OnlyOnceEver", "Only Once Ever", "__once_ever_{uid}({key})", "Run Context", "only once ever ( {key} )", "True exactly once, ever - even across closing the game. Show a tutorial hint the first time and never again; Forget First Time resets it for testing (takes effect next run). This one is per COMPUTER, in a file beside the game; First Time In This Save asks the same question of the SAVE SLOT, so a second save sees it again.").param("key", "\"hint_dash\"", "Name", "The memory's name - one true per name, ever.", "expression").stateful("var __onceever_{uid}: int = -1\n\nfunc __once_ever_{uid}(key: String) -> bool:\n\tif __onceever_{uid} == -1:\n\t\tvar __cfg: ConfigFile = ConfigFile.new()\n\t\t__cfg.load(\"user://remembered.cfg\")\n\t\t__onceever_{uid} = 1 if bool(__cfg.get_value(\"OnceEver\", key, false)) else 0\n\tif __onceever_{uid} == 1:\n\t\treturn false\n\t__onceever_{uid} = 1\n\tvar __save: ConfigFile = ConfigFile.new()\n\t__save.load(\"user://remembered.cfg\")\n\t__save.set_value(\"OnceEver\", key, true)\n\t__save.save(\"user://remembered.cfg\")\n\treturn true"))
	descriptors.append(F.act("ForgetOnce", "Forget First Time", "var __forget_{uid}: ConfigFile = ConfigFile.new()\n__forget_{uid}.load(\"user://remembered.cfg\")\n__forget_{uid}.set_value(\"OnceEver\", {key}, false)\n__forget_{uid}.save(\"user://remembered.cfg\")", "Run Context", "forget first time ( {key} )", "Resets an Only Once Ever memory so it fires again - for testing, or for New Game+. Rows already running this session keep their cached answer until the next run.").param("key", "\"hint_dash\"", "Name", "The Only Once Ever name to reset.", "expression"))

	# ── First time in THIS SAVE ──
	#
	# Only Once Ever above is per COMPUTER, in a file beside the game. A first kill, a codex
	# entry and a tutorial a second playthrough should see again all belong to the SAVE SLOT
	# instead, so these four ask the save. Each row carries the same two-store choice: the
	# SaveSystem autoload when the Save System pack is registered, and the remembered file when
	# it is not. The store is found through Engine.get_main_loop() rather than get_tree(), so a
	# sheet whose host is not a Node still compiles.
	#
	# The key is asked ONCE per key per row and the answer is kept, because the key is an
	# expression - "kill:" + kind is the shape these rows are for - and a store read per frame
	# per key would be a file read per frame.
	descriptors.append(F.cond("FirstTimeInSave", "First Time In This Save", "__first_time_in_save_{uid}(str({key}))", "Run Context", "first time in this save ( {key} )", "True the FIRST time this save slot reaches this name, and never again for that save - the first kill of a kind, the first visit to a room, a tutorial a new game should show again. The memory lives in the SAVE SLOT when the Save System pack is in the tree, so each save answers for itself and Start New Run clears it; without that pack it falls back to the same user://remembered.cfg the per-machine rows use, which means one answer for the whole computer. Has Seen asks the same question without using it up.").param("key", "\"first_boss\"", "Name", "The memory's name - one true per name, per save. An expression is fine: \"kill:\" + kind gives one memory per kind.", "expression").stateful("var __seenkeys_{uid}: Dictionary = {}\n\nfunc __seen_store_{uid}() -> Node:\n\tvar __tree: SceneTree = Engine.get_main_loop() as SceneTree\n\treturn __tree.root.get_node_or_null(^\"SaveSystem\") if __tree != null else null\n\nfunc __seen_in_save_{uid}(key: String) -> bool:\n\tvar __store: Node = __seen_store_{uid}()\n\tif __store != null and __store.has_method(&\"load_value\"):\n\t\treturn bool(__store.call(&\"load_value\", \"seen:\" + key, false))\n\tvar __cfg: ConfigFile = ConfigFile.new()\n\t__cfg.load(\"user://remembered.cfg\")\n\treturn bool(__cfg.get_value(\"SeenInSave\", key, false))\n\nfunc __mark_seen_{uid}(key: String) -> void:\n\tvar __store: Node = __seen_store_{uid}()\n\tif __store != null and __store.has_method(&\"save_value\"):\n\t\t__store.call(&\"save_value\", \"seen:\" + key, true)\n\t\treturn\n\tvar __cfg: ConfigFile = ConfigFile.new()\n\t__cfg.load(\"user://remembered.cfg\")\n\t__cfg.set_value(\"SeenInSave\", key, true)\n\t__cfg.save(\"user://remembered.cfg\")\n\nfunc __first_time_in_save_{uid}(key: String) -> bool:\n\tif __seenkeys_{uid}.has(key):\n\t\treturn false\n\t__seenkeys_{uid}[key] = true\n\tif __seen_in_save_{uid}(key):\n\t\treturn false\n\t__mark_seen_{uid}(key)\n\treturn true").evaluated_last())
	descriptors.append(F.cond("HasSeenInSave", "Has Seen", "__seen_in_save_{uid}(str({key}))", "Run Context", "has seen ( {key} )", "Whether this save has already met that name - the question First Time In This Save answers by USING it up, asked without using it up. Show the codex page, grey out the entry, skip the intro. The memory lives in the SAVE SLOT when the Save System pack is in the tree, so each save answers for itself and Start New Run clears it; without that pack it falls back to the same user://remembered.cfg the per-machine rows use, which means one answer for the whole computer.").param("key", "\"first_boss\"", "Name", "The memory's name, the same one the row that marks it uses.", "expression").stateful("func __seen_store_{uid}() -> Node:\n\tvar __tree: SceneTree = Engine.get_main_loop() as SceneTree\n\treturn __tree.root.get_node_or_null(^\"SaveSystem\") if __tree != null else null\n\nfunc __seen_in_save_{uid}(key: String) -> bool:\n\tvar __store: Node = __seen_store_{uid}()\n\tif __store != null and __store.has_method(&\"load_value\"):\n\t\treturn bool(__store.call(&\"load_value\", \"seen:\" + key, false))\n\tvar __cfg: ConfigFile = ConfigFile.new()\n\t__cfg.load(\"user://remembered.cfg\")\n\treturn bool(__cfg.get_value(\"SeenInSave\", key, false))"))
	descriptors.append(F.act("MarkSeenInSave", "Mark Seen", "var __seentree_{uid}: SceneTree = Engine.get_main_loop() as SceneTree\nvar __seenstore_{uid}: Node = __seentree_{uid}.root.get_node_or_null(^\"SaveSystem\") if __seentree_{uid} != null else null\nif __seenstore_{uid} != null and __seenstore_{uid}.has_method(&\"save_value\"):\n\t__seenstore_{uid}.call(&\"save_value\", \"seen:\" + str({key}), true)\nelse:\n\tvar __seencfg_{uid}: ConfigFile = ConfigFile.new()\n\t__seencfg_{uid}.load(\"user://remembered.cfg\")\n\t__seencfg_{uid}.set_value(\"SeenInSave\", str({key}), true)\n\t__seencfg_{uid}.save(\"user://remembered.cfg\")", "Run Context", "mark seen ( {key} )", "Marks a name as met in this save without any row having asked first - unlocking a page from a cheat menu, carrying a story flag over, skipping a tutorial the player has turned off. The memory lives in the SAVE SLOT when the Save System pack is in the tree, so each save answers for itself and Start New Run clears it; without that pack it falls back to the same user://remembered.cfg the per-machine rows use, which means one answer for the whole computer.").param("key", "\"first_boss\"", "Name", "The memory's name to mark.", "expression"))
	descriptors.append(F.act("ForgetSeenInSave", "Forget Seen", "var __seentree_{uid}: SceneTree = Engine.get_main_loop() as SceneTree\nvar __seenstore_{uid}: Node = __seentree_{uid}.root.get_node_or_null(^\"SaveSystem\") if __seentree_{uid} != null else null\nif __seenstore_{uid} != null and __seenstore_{uid}.has_method(&\"save_value\"):\n\t__seenstore_{uid}.call(&\"save_value\", \"seen:\" + str({key}), false)\nelse:\n\tvar __seencfg_{uid}: ConfigFile = ConfigFile.new()\n\t__seencfg_{uid}.load(\"user://remembered.cfg\")\n\t__seencfg_{uid}.set_value(\"SeenInSave\", str({key}), false)\n\t__seencfg_{uid}.save(\"user://remembered.cfg\")", "Run Context", "forget seen ( {key} )", "Clears a name in this save so First Time In This Save fires for it again - testing, or a chapter that resets its own flags. A row that has already answered for that name this session keeps its answer until the next run. The memory lives in the SAVE SLOT when the Save System pack is in the tree, so each save answers for itself and Start New Run clears it; without that pack it falls back to the same user://remembered.cfg the per-machine rows use, which means one answer for the whole computer.").param("key", "\"first_boss\"", "Name", "The memory's name to clear.", "expression"))

	# ── Spawn And Configure: a spawn you can name, and therefore talk about later ──
	#
	# Spawn Scene At and Spawn Scene (Full) build into a hidden `__spawn_<uid>` local, so the row
	# after them cannot reach the thing that was just made - setting its health, its target or its
	# tier means dropping into GDScript. These three close that in the smallest possible way:
	#
	#   * The NAME is the address. The new node is stored in host metadata under the name the row
	#     typed - the same stateless, name-keyed trick the cooldowns and the input buffer use - so
	#     The Spawned "boss" reads it back from any later row, in any event, on the same host. No
	#     class member is involved, which matters because an ACTION cannot declare one.
	#   * The "with" record sets values ON THE WAY IN, before the node enters the tree, so a
	#     projectile has its damage and its owner before its first physics frame.
	#   * The spawn HAPPENING is handed on as a real Godot signal, not as a "last spawned" side
	#     channel that a loop spawning six things in one frame would corrupt. Declare
	#     `signal scene_spawned(spawn_name: String, node: Node)` on the sheet (Add ▸ Signal) and the
	#     row's On Signal trigger receives both as its own captured payload - the name that was
	#     spawned and the node itself. A sheet that declares no such signal skips the emit, so the
	#     action still stands alone anywhere (has_signal is the whole guard).
	#
	# Reading it back is ALWAYS guarded by has_meta first, never by get_meta's default argument:
	# Object.get_meta treats a `null` default as "no default given" and pushes an error, so the
	# obvious `get_meta(key, null)` prints an engine error every time a row asks about a name that
	# was never spawned - which is exactly the case the expression exists to answer.
	var spawn_key: String = "&\"__ef_spawn_\" + str({spawn_name}).to_utf8_buffer().hex_encode()"
	var spawn_alive: String = "(has_meta(%s) and is_instance_valid(get_meta(%s)))" % [spawn_key, spawn_key]
	descriptors.append(F.act("SpawnSceneAs", "Spawn Scene As", "var __spawn_{uid} = load({path}).instantiate()\n__spawn_{uid}.position = {position}\nvar __values_{uid}: Dictionary = {values}\nfor __field_{uid}: Variant in __values_{uid}:\n\t__spawn_{uid}.set(__field_{uid}, __values_{uid}[__field_{uid}])\nvar __parent_{uid}: Node = {parent}\n(__parent_{uid} if __parent_{uid} != null else self).add_child(__spawn_{uid})\nset_meta(&\"__ef_spawn_\" + str({spawn_name}).to_utf8_buffer().hex_encode(), __spawn_{uid})\nif has_signal(&\"scene_spawned\"):\n\temit_signal(&\"scene_spawned\", {spawn_name}, __spawn_{uid})", "Scene", "Spawn [b]{path}[/b] as [b]{spawn_name}[/b] with [i]{values}[/i]", "Spawns a scene under a name, sets a record of values on it before it enters the tree, and remembers it under that name so every later row can say The Spawned. If the sheet declares a scene_spawned(spawn_name, node) signal, this fires it with both, so another event can react to the new node without ever asking what was spawned last.").param("path", "\"res://enemy.tscn\"", "Scene", "Scene file to instance.", "scene_path").param("spawn_name", "\"boss\"", "As", "A name for this spawn, so later rows can say The Spawned \"boss\".", "expression").param("values", "{}", "With", "Values to set as it arrives, as a record: {\"max_health\": 200, \"tier\": 3}. Names the scene does not have are set anyway, so keep to its own fields.", "expression").param("parent", "null", "Into", "The node to add it under. Leave as nothing to add it under this one.", "expression").param("position", "Vector2(0, 0)", "At", "Spawn position.", "expression").featured())
	descriptors.append(F.expr("TheSpawned", "The Spawned", "(get_meta(%s) if %s else null)" % [spawn_key, spawn_alive], "Scene", "the spawned [b]{spawn_name}[/b]", "The node a Spawn Scene As row made under this name, or nothing at all when it was never spawned or has since been freed - so a row that reaches for a dead boss gets nothing instead of a crash.").param("spawn_name", "\"boss\"", "Name", "The name a Spawn Scene As row used.", "expression"))
	descriptors.append(F.cond("SpawnIsAlive", "Spawn Is Alive", spawn_alive, "Scene", "the spawned [b]{spawn_name}[/b] is alive", "True while the node spawned under this name still exists - the guard to put in front of any row that talks to a named spawn, and the honest way to ask 'is the boss still up?'.").param("spawn_name", "\"boss\"", "Name", "The name a Spawn Scene As row used.", "expression"))
	# The trigger half. "signal:<name>" is the id convention that binds a row to a real signal: the
	# sheet declares `scene_spawned(spawn_name: String, node: Node)` with a Signal row, and the
	# compiler emits the handler plus its _ready connection. The two arguments arrive as the row's
	# OWN captured payload, which is why no "last spawned node" expression exists - a loop spawning
	# six things in one frame would make that answer wrong, and this one stays right.
	descriptors.append(F.trig("signal:scene_spawned", "On Scene Spawned", "scene_spawned", "Scene", "On scene spawned {spawn_name} ( {node} )", "Runs when a Spawn Scene As row spawns something. The name and the new node arrive on the row as spawn_name and node, so a reaction can configure or announce the node without asking what was spawned last - correct even when one loop spawns six things in a frame. Needs a Signal row for scene_spawned(spawn_name: String, node: Node) - without one the sheet still compiles, but nothing connects this event, so it never runs. The Project Doctor flags that.").param("spawn_name", "", "Name", "The name the Spawn Scene As row gave this spawn.").param_typed("Node", "node", "", "Node", "The node that was just spawned, carried by the signal itself."))

	# ── Outcome triggers: the shared shape for "the action refused" ───────────────────────
	# GDScript has no exceptions, so every pack used to mint a private failure trigger. These two
	# generalize the shipped On Save Failed / On Purchase Refused: ONE signal per outcome, with the
	# action's name and the reason as the signal's ARGUMENTS - so the reason arrives as the trigger
	# row's own captured payload instead of a "last failure" expression somebody has to read.
	# The ace_ids use the compiler's "signal:<name>" convention, which is what binds the row to a
	# real signal: the sheet declares `verb_failed(verb_id: String, reason: String)` with a Declare
	# Signal row, and the compiler emits the handler plus the _ready connection. Report Failure /
	# Report Success are guarded by has_signal, so a sheet that has NOT declared the signal still
	# compiles and simply does nothing - the row is always droppable. The signal and parameter names
	# are frozen public API from the first release, which is why the identifiers still read `verb_*`
	# while every word the reader sees says "action".
	descriptors.append(F.trig("signal:verb_failed", "On Failure Of", "verb_failed", "Run Context", "On failure of {verb_id} ( {reason} )", "Runs when an action reports that it refused. The action's name and the reason arrive on the row as verb_id and reason, so recovery lives in its own event - add a condition under it to handle one action only. Needs a Declare Signal row for verb_failed(verb_id: String, reason: String) - without one the sheet still compiles, but nothing connects this event, so it never runs. The Project Doctor flags that.").param("verb_id", "", "Action", "Which action refused - the name the Report Failure row used.").param("reason", "", "Reason", "Why it refused, carried by the signal itself."))
	descriptors.append(F.trig("signal:verb_succeeded", "On Success Of", "verb_succeeded", "Run Context", "On success of {verb_id}", "Runs when an action reports that it finished. The action's name arrives on the row as verb_id. Needs a Declare Signal row for verb_succeeded(verb_id: String) - without one the sheet still compiles, but nothing connects this event, so it never runs. The Project Doctor flags that.").param("verb_id", "", "Action", "Which action finished - the name the Report Success row used."))
	descriptors.append(F.act("ReportFailure", "Report Failure", "if has_signal(&\"verb_failed\"):\n\temit_signal(&\"verb_failed\", str({verb}), str({reason}))", "Run Context", "Report failure of [b]{verb}[/b]: [b]{reason}[/b]", "Announces that an action refused, so every On Failure Of event for that action runs. Use it inside an action you publish yourself, or after a check that found a null resource or an empty result.").param("verb", "\"save_game\"", "Action", "Name of the action that refused - the same name the On Failure Of row picks.", "expression").param("reason", "\"disk write refused\"", "Reason", "Plain words a player or a log line can read.", "expression"))
	descriptors.append(F.act("ReportSuccess", "Report Success", "if has_signal(&\"verb_succeeded\"):\n\temit_signal(&\"verb_succeeded\", str({verb}))", "Run Context", "Report success of [b]{verb}[/b]", "Announces that an action finished, so every On Success Of event for that action runs. The confirmation twin of Report Failure.").param("verb", "\"save_game\"", "Action", "Name of the action that finished - the same name the On Success Of row picks.", "expression"))

	# ── Rate limits: the leading edge (throttle) and the trailing edge (debounce) ─────────
	# At Most Every is stateful and uses the SAME .evaluated_last() hoist that makes Trigger Once
	# correct - the term is pushed to the end of the emitted `and` chain, so the window is only
	# consumed once every other condition on the row has already held.
	descriptors.append(F.cond("AtMostEvery", "At Most Every", "__throttle_{uid}(maxf({seconds}, 0.0))", "Run Context", "at most every [b]{seconds}[/b]s", "Lets this event run at most once every so many seconds, however often it is reached. The rate limit for a search box, an expensive readout, or forty hit sounds landing in one frame.").param("seconds", "0.25", "Seconds", "Shortest gap between two runs of this event.", "expression").stateful("var __throttle_at_{uid}: int = -1000000\n\nfunc __throttle_{uid}(window: float) -> bool:\n\tif Time.get_ticks_msec() - __throttle_at_{uid} < int(window * 1000.0):\n\t\treturn false\n\t__throttle_at_{uid} = Time.get_ticks_msec()\n\treturn true").evaluated_last())
	# The debounce pair is stateless name-keyed node metadata, copying Start Cooldown / Cooldown Is
	# Ready exactly, so a Poke in one event and the quiet check in another agree with no wiring. A
	# name that was never poked is never quiet, so nothing fires at startup. The name is HEX-ENCODED
	# into the metadata key because Object.set_meta refuses a key that is not a valid identifier: a
	# poke called "search box" would otherwise store nothing at all and read wrong forever, silently.
	descriptors.append(F.act("Poke", "Poke", "set_meta(&\"__ef_poke_\" + str({poke_name}).to_utf8_buffer().hex_encode(), Time.get_ticks_msec())", "Time", "poke [b]{poke_name}[/b]", "Marks that something just happened, by name. Poke on every keystroke or every change, then let Has Been Quiet For notice when it stops.").param("poke_name", "\"search\"", "Name", "Poke name - any label you also use in Has Been Quiet For.", "expression"))
	descriptors.append(F.act("ClearPoke", "Clear Poke", "set_meta(&\"__ef_poke_\" + str({poke_name}).to_utf8_buffer().hex_encode(), 0)", "Time", "clear poke [b]{poke_name}[/b]", "Forgets a poke so Has Been Quiet For stops firing. Clear it right after acting on the quiet, the same way you consume a buffered press.").param("poke_name", "\"search\"", "Name", "Poke name, matching a Poke action.", "expression"))
	descriptors.append(F.cond("HasBeenQuiet", "Has Been Quiet For", "(int(get_meta(&\"__ef_poke_\" + str({poke_name}).to_utf8_buffer().hex_encode(), 0)) > 0 and Time.get_ticks_msec() - int(get_meta(&\"__ef_poke_\" + str({poke_name}).to_utf8_buffer().hex_encode(), 0)) >= int(maxf({seconds}, 0.0) * 1000.0))", "Run Context", "[b]{poke_name}[/b] has been quiet for [b]{seconds}[/b]s", "True once a poked name has stopped being poked for this long - the settle-down check. Autosave after the player stops editing, search after they stop typing. Needs a per-frame trigger, and stays true until you Clear Poke.").param("poke_name", "\"search\"", "Name", "Poke name, matching a Poke action.", "expression").param("seconds", "0.6", "Seconds", "How long the quiet has to last.", "expression"))

	# ── Once per THING: the middle ground between Trigger Once and Only Once Ever ─────────
	# Trigger Once is per ROW instance, so inside a For Each it fires for the first item and never
	# for the rest. These key the memory by the thing instead: the node (metadata under the
	# hex-encoded name, since a metadata key must be a valid identifier and "first hit" is not, so the memory
	# travels with it and a pool's reset seam can clear it with Forget Once For), a name, or this
	# scene load (a plain member, so reloading the scene starts over).
	descriptors.append(F.cond("OnlyOncePerNode", "Only Once Per Node", "__once_node_{uid}({node}, str({label}))", "Run Context", "only once per node ( [b]{node}[/b] / [b]{label}[/b] )", "True the first time this row is reached for each node, and never again for that node. The initialiser you want when the row sits inside a For Each over spawned things; the memory lives on the node, so Forget Once For clears it.").param("node", "self", "Node", "The node the memory belongs to - inside a For Each, the loop item.", "expression").param("label", "\"init\"", "Memory", "Name the memory so one node can hold several.", "expression").stateful("func __once_node_{uid}(node: Object, label: String) -> bool:\n\tif node == null:\n\t\treturn false\n\tvar key: StringName = StringName(\"__ef_once_\" + label.to_utf8_buffer().hex_encode())\n\tif node.has_meta(key):\n\t\treturn false\n\tnode.set_meta(key, true)\n\treturn true"))
	descriptors.append(F.cond("OnlyOncePerName", "Only Once Per Name", "__once_name_{uid}(str({key}))", "Run Context", "only once per name ( [b]{key}[/b] )", "True the first time this row is reached for each name, and never again for that name. One discovery line per item type, one loot roll per chest id - with no flag variable each. Kept on this node, so Forget Once For clears it.").param("key", "\"discovered\"", "Name", "The memory's name - one true per name on this node.", "expression").stateful("func __once_name_{uid}(key: String) -> bool:\n\tvar meta_key: StringName = StringName(\"__ef_once_\" + key.to_utf8_buffer().hex_encode())\n\tif has_meta(meta_key):\n\t\treturn false\n\tset_meta(meta_key, true)\n\treturn true"))
	descriptors.append(F.cond("OnlyOnceThisSceneLoad", "Only Once This Scene Load", "__once_scene_{uid}(str({key}))", "Run Context", "only once this scene load ( [b]{key}[/b] )", "True the first time this row is reached for each name in this scene load, and again after the scene is reloaded or changed. The welcome line, the per-level check - forgotten on Restart Scene rather than remembered forever.").param("key", "\"welcome\"", "Name", "The memory's name - one true per name until the scene reloads.", "expression").stateful("var __once_load_{uid}: Dictionary = {}\n\nfunc __once_scene_{uid}(key: String) -> bool:\n\tif __once_load_{uid}.has(key):\n\t\treturn false\n\t__once_load_{uid}[key] = true\n\treturn true"))
	descriptors.append(F.act("ForgetOnceFor", "Forget Once For", "if {node} != null and {node}.has_meta(&\"__ef_once_\" + str({label}).to_utf8_buffer().hex_encode()):\n\t{node}.remove_meta(&\"__ef_once_\" + str({label}).to_utf8_buffer().hex_encode())", "Run Context", "forget once ( [b]{label}[/b] ) for [b]{node}[/b]", "Clears an Only Once Per Node / Per Name memory so the row fires again for that node. Drop it in an Object Pool's reset seam and a recycled instance initialises like a fresh one.").param("node", "self", "Node", "The node holding the memory.", "expression").param("label", "\"init\"", "Memory", "The Only Once Per Node / Per Name memory to clear.", "expression"))

	return descriptors


## The group Set/Is Group Active name. Its hint is `group_reference`, but the value is one of
## the SHEET's own groups rather than a node group: the params dialog decides which list to offer
## from what the template does with the value, so nothing here has to declare it twice.
static func _group_param(factory: Variant) -> ACEParam:
	return factory.make_param(
		"group", "String", "\"combat\"", "Group",
		"The group to switch, picked from this sheet's runtime-toggleable groups.",
		"group_reference"
	)


## The on/off half of Set Group Active. The value stays the GDScript `true` / `false` the template
## emits; the LABELS are what the row reads with, so the sentence says "Set group Tutorial inactive"
## instead of spelling a boolean out loud.
static func _group_state_param(factory: Variant) -> ACEParam:
	var parameter: ACEParam = factory.make_param(
		"active", "String", "true", "Active", "Whether the group runs.", "",
		[{"key": "true", "label": "active"}, {"key": "false", "label": "inactive"}]
	)
	parameter.display_option_labels = true
	return parameter
