# AUTO-GENERATED by EventForge v0.1.0
# Source: res://eventsheet_addons/save_system/save_system_addon.tres
# DO NOT EDIT — this file is regenerated on every compile.

## @ace_tags(persistence)
class_name SaveSystemAddon
extends Node

## Active save slot (each slot is its own file).
@export_range(0, 9, 1) var slot: int = 0

## @ace_trigger
## @ace_name("On Save Written")
## @ace_category("Save System")
signal save_written(slot: int)

func _slot_path() -> String:
	return "user://save_%d.cfg" % slot

func _open_slot() -> ConfigFile:
	var config: ConfigFile = ConfigFile.new()
	config.load(_slot_path())
	return config

## @ace_action
## @ace_name("Save Number")
## @ace_category("Save System")
## @ace_description("Writes a number under the key (active slot).")
## @ace_codegen_template("SaveSystem.save_number({key}, {value})")
func save_number(key: String, value: float) -> void:
	var config: ConfigFile = _open_slot()
	config.set_value("save", key, value)
	config.save(_slot_path())
	save_written.emit(slot)

## @ace_action
## @ace_name("Save Text")
## @ace_category("Save System")
## @ace_description("Writes a string under the key (active slot).")
## @ace_codegen_template("SaveSystem.save_text({key}, {value})")
func save_text(key: String, value: String) -> void:
	var config: ConfigFile = _open_slot()
	config.set_value("save", key, value)
	config.save(_slot_path())
	save_written.emit(slot)

## @ace_action
## @ace_name("Load Number")
## @ace_category("Save System")
## @ace_description("Reads a number (0 when missing).")
## @ace_codegen_template("SaveSystem.load_number({key})")
func load_number(key: String) -> float:
	return float(_open_slot().get_value("save", key, 0.0))

## @ace_action
## @ace_name("Load Text")
## @ace_category("Save System")
## @ace_description("Reads a string ("" when missing).")
## @ace_codegen_template("SaveSystem.load_text({key})")
func load_text(key: String) -> String:
	return str(_open_slot().get_value("save", key, ""))

## @ace_action
## @ace_name("Has Save Key")
## @ace_category("Save System")
## @ace_description("Whether the key exists in the active slot.")
## @ace_codegen_template("SaveSystem.has_save_key({key})")
func has_save_key(key: String) -> bool:
	return _open_slot().has_section_key("save", key)

## @ace_action
## @ace_name("Delete Slot")
## @ace_category("Save System")
## @ace_description("Removes the active slot's save file.")
## @ace_codegen_template("SaveSystem.delete_slot()")
func delete_slot() -> void:
	if FileAccess.file_exists(_slot_path()):
		DirAccess.remove_absolute(_slot_path())

# Save System: register as the SaveSystem autoload, then Save/Load Number/Text from any sheet. Slot-based (user://save_<slot>.cfg), human-readable ConfigFile underneath.
