# AUTO-GENERATED by EventForge v0.1.0
# Source: res://tests/fixtures/translation_matrix_slice.tres
# DO NOT EDIT — this file is regenerated on every compile.

extends Node2D

@export var health: int = 3

func _ready() -> void:
	if true:
		print("ready")

func _process(delta: float) -> void:
	if health > 0:
		health = health - 1

func _physics_process(delta: float) -> void:
	print("physics")

func _on_damage_taken() -> void:
	print("signal")
