# AUTO-GENERATED by EventForge v0.8.0
# Source: res://eventsheet_addons/sine_3d/sine_3d_behavior.tres
# DO NOT EDIT — this file is regenerated on every compile.

class_name Sine3DBehavior
extends Node

## The node this behavior acts on (its parent). Required host: Node3D.
var host: Node3D = null

func _enter_tree() -> void:
	host = get_parent() as Node3D
	if host == null:
		push_warning("Sine3DBehavior behavior requires a Node3D parent.")

@export var active: bool = true
var base_captured: bool = false
var base_rot_y: float = 0.0
var base_x: float = 0.0
var base_y: float = 0.0
var base_z: float = 0.0
@export var magnitude: float = 2.0
@export_enum("x", "y", "z", "rotation-y") var movement: String = "y"
@export var period: float = 4.0
@export var phase_degrees: float = 0.0
var time: float = 0.0
@export_enum("sine", "triangle", "sawtooth", "reverse-sawtooth", "square") var wave: String = "sine"

## @ace_hidden
func _wave(t: float) -> float:
	var cycle := fposmod(t, 1.0)
	match wave:
		"triangle":
			return 1.0 - 4.0 * absf(cycle - 0.5)
		"sawtooth":
			return 2.0 * cycle - 1.0
		"reverse-sawtooth":
			return 1.0 - 2.0 * cycle
		"square":
			return 1.0 if cycle < 0.5 else -1.0
	return sin(cycle * TAU)

func _process(delta: float) -> void:
	if not active or host == null:
		return
	if not base_captured:
		base_x = host.position.x
		base_y = host.position.y
		base_z = host.position.z
		base_rot_y = host.rotation.y
		base_captured = true
	time += delta
	var t := time / maxf(period, 0.001) + phase_degrees / 360.0
	var offset := _wave(t) * magnitude
	if movement == "x":
		host.position.x = base_x + offset
	elif movement == "y":
		host.position.y = base_y + offset
	elif movement == "z":
		host.position.z = base_z + offset
	elif movement == "rotation-y":
		host.rotation.y = base_rot_y + offset * 0.0174533

## @ace_action
## @ace_name("Set Sine 3D Active")
## @ace_category("Sine 3D")
## @ace_description("Pauses or resumes the oscillation.")
## @ace_codegen_template("$Sine3DBehavior.set_sine3d_active({is_active})")
func set_sine3d_active(is_active: bool) -> void:
	active = is_active

## @ace_action
## @ace_name("Set Phase")
## @ace_category("Sine 3D")
## @ace_description("Phase offset in degrees.")
## @ace_codegen_template("$Sine3DBehavior.set_sine3d_phase({degrees})")
func set_sine3d_phase(degrees: float) -> void:
	phase_degrees = degrees

## @ace_action
## @ace_name("Reset Sine 3D")
## @ace_category("Sine 3D")
## @ace_description("Restarts the wave from the current state.")
## @ace_codegen_template("$Sine3DBehavior.reset_sine3d()")
func reset_sine3d() -> void:
	time = 0.0
	base_captured = false

# Sine 3D behavior (C3-style): oscillates the host along an axis (x, y, z) or around the Y axis (rotation-y), with the full wave set.
