# EventForge — Event sheet compiler
# Compiles EventSheetResource assets into deterministic GDScript output.
@tool
extends RefCounted
class_name SheetCompiler

const VERSION: String = "0.1.0"

## Compiles an event sheet resource to a GDScript output file.
static func compile(sheet: EventSheetResource, output_path: String = "") -> Dictionary:
	var result: Dictionary = {
		"success": true,
		"errors": [] as Array[String],
		"warnings": [] as Array[String],
		"output": "",
		# Provenance: [{uid: String (resource instance id), start: int, end: int, kind: String}]
		# with 1-based inclusive line numbers into "output". Lets the editor highlight the
		# generated lines for a selected sheet row.
		"source_map": [] as Array
	}

	if sheet == null:
		result["success"] = false
		(result["errors"] as Array[String]).append("Sheet is null")
		return result

	# GDScript-backed sheets (opened FROM a .gd file) compile via the order-preserving
	# external path: no generated header, no synthesized extends, rows emit in sheet order
	# so an untouched file reproduces byte-identically. See GDSCRIPT-PAIRING-SPEC.
	if not sheet.external_source_path.is_empty():
		return _compile_external(sheet, result, output_path)

	var lines: PackedStringArray = PackedStringArray()
	lines.append("# AUTO-GENERATED by EventForge v%s" % VERSION)
	lines.append("# Source: %s" % sheet.resource_path)
	lines.append("# DO NOT EDIT — this file is regenerated on every compile.")
	lines.append("")
	# A named sheet defines a custom node type: `@icon` + `class_name` make the generated
	# script register in the Create Node dialog exactly like hand-written GDScript.
	if not sheet.custom_class_name.strip_edges().is_empty():
		if not sheet.custom_class_icon.strip_edges().is_empty():
			lines.append("@icon(\"%s\")" % sheet.custom_class_icon)
		lines.append("class_name %s" % sheet.custom_class_name.strip_edges())
	# Behavior sheets compile to attachable Node components that act on their PARENT (the
	# host) — Godot's component idiom standing in for Construct 3 behaviors. host_class is
	# the declared required host type, not the script's base.
	if sheet.behavior_mode:
		lines.append("extends Node")
	else:
		lines.append("extends %s" % sheet.host_class)

	var source_map: Array = result["source_map"]
	if sheet.behavior_mode:
		var host_type: String = sheet.host_class if ClassDB.class_exists(sheet.host_class) else "Node"
		var behavior_label: String = sheet.custom_class_name.strip_edges()
		if behavior_label.is_empty():
			behavior_label = "This"
		lines.append("")
		lines.append("## The node this behavior acts on (its parent). Required host: %s." % host_type)
		lines.append("var host: %s = null" % host_type)
		lines.append("")
		lines.append("func _enter_tree() -> void:")
		lines.append("\thost = get_parent() as %s" % host_type)
		lines.append("\tif host == null:")
		lines.append("\t\tpush_warning(\"%s behavior requires a %s parent.\")" % [behavior_label, host_type])
	var tree_variables: Array = []
	_collect_tree_variables(sheet.events, tree_variables)
	var variable_lines: PackedStringArray = _emit_variables(sheet.variables)
	if variable_lines.size() > 0:
		lines.append("")
		for line: String in variable_lines:
			lines.append(line)
	if not tree_variables.is_empty():
		if variable_lines.is_empty():
			lines.append("")
		for tree_entry: Variant in tree_variables:
			var declaration: String = _emit_tree_variable_line(tree_entry as LocalVariable)
			if declaration.is_empty():
				continue
			lines.append(declaration)
			source_map.append({"uid": str((tree_entry as LocalVariable).get_instance_id()), "start": lines.size(), "end": lines.size(), "kind": "variable"})

	# Tree-placed GDScript blocks (top level / inside groups) are emitted verbatim at class
	# level — helper functions, @onready vars, signal declarations, etc.
	var raw_blocks: Array = []
	_collect_class_level_raw_rows(sheet.events, raw_blocks)
	for raw_entry: Variant in raw_blocks:
		var raw_block: RawCodeRow = raw_entry as RawCodeRow
		if raw_block == null or not raw_block.enabled or raw_block.code.strip_edges().is_empty():
			continue
		lines.append("")
		var raw_start: int = lines.size() + 1
		for code_line: String in raw_block.code.split("\n"):
			lines.append(code_line)
		source_map.append({"uid": str(raw_block.get_instance_id()), "start": raw_start, "end": lines.size(), "kind": "raw"})

	var deferred_rows: PackedStringArray = PackedStringArray()
	var top_level_events: Array = []
	for row: Variant in sheet.events:
		if not (row is Resource):
			continue
		if row is LocalVariable:
			continue  # emitted above as a class-level variable
		if row is RawCodeRow:
			continue  # emitted above as a class-level GDScript block
		if row is CommentRow:
			# Top-level comments compile to real comment lines (emitted after the trigger
			# sections — position is approximate, content is preserved).
			if (row as CommentRow).enabled and not (row as CommentRow).text.strip_edges().is_empty():
				for comment_line: String in (row as CommentRow).text.split("\n"):
					deferred_rows.append("# %s" % comment_line)
			continue
		if row.has_method("get_row_kind") and str(row.call("get_row_kind")) != "event":
			deferred_rows.append("# TODO: row type not yet implemented in Phase 1")
			continue
		if not (row is EventRow):
			continue
		var event_row: EventRow = row
		if not event_row.enabled:
			continue
		if event_row.trigger_id.is_empty():
			(result["warnings"] as Array[String]).append("Skipping event %s with no trigger" % event_row.event_uid)
			continue
		top_level_events.append(event_row)
	var connect_context: Dictionary = {
		"self_class": "Node" if sheet.behavior_mode else (sheet.host_class if ClassDB.class_exists(sheet.host_class) else "Node"),
		"declared_signals": _scan_declared_signals(raw_blocks)
	}
	_emit_grouped_trigger_functions(top_level_events, lines, source_map, result, connect_context)

	# Emit sheet functions as callable GDScript methods (after the trigger handlers).
	for function_resource: Variant in sheet.functions:
		if not (function_resource is EventFunction):
			continue
		var event_function: EventFunction = function_resource as EventFunction
		if not event_function.enabled or event_function.function_name.strip_edges().is_empty():
			continue
		lines.append("")
		var function_start: int = lines.size() + 1
		_emit_expose_annotations(event_function, sheet, lines)
		lines.append("func %s(%s) -> void:" % [event_function.function_name, _emit_function_params(event_function)])
		var function_events: Array = event_function.events if not event_function.events.is_empty() else event_function.rows
		var function_had_body: bool = _emit_event_body(function_events, lines, source_map, 1, result["warnings"])
		if not function_had_body:
			lines.append("\tpass")
		source_map.append({"uid": str(event_function.get_instance_id()), "start": function_start, "end": lines.size(), "kind": "function"})

	for deferred: String in deferred_rows:
		lines.append("")
		lines.append(deferred)

	_insert_provider_member_declarations(lines, result)
	var output: String = "\n".join(lines) + "\n"
	result["output"] = output

	var final_output_path: String = _resolve_output_path(sheet, output_path)
	var file: FileAccess = FileAccess.open(final_output_path, FileAccess.WRITE)
	if file == null:
		result["success"] = false
		(result["errors"] as Array[String]).append("Failed to open output path: %s" % final_output_path)
		return result

	file.store_string(output)
	file.flush()
	file.close()
	return result

## Order-preserving emission for GDScript-backed sheets: rows reproduce the original file
## (verbatim blocks + verify-lifted variables) in sheet order; events/groups the user adds
## afterwards append as standard trigger functions at the end. Disabled blocks still emit —
## external mode is lossless, never a filter.
static func _compile_external(sheet: EventSheetResource, result: Dictionary, output_path: String) -> Dictionary:
	var lines: PackedStringArray = PackedStringArray()
	var source_map: Array = result["source_map"]
	var added_event_rows: Array = []
	var deferred_comment_lines_external: PackedStringArray = PackedStringArray()
	for entry: Variant in sheet.events:
		if entry is LocalVariable:
			var declaration: String = _emit_tree_variable_line(entry as LocalVariable)
			lines.append(declaration)
			source_map.append({"uid": str((entry as LocalVariable).get_instance_id()), "start": lines.size(), "end": lines.size(), "kind": "variable"})
		elif entry is RawCodeRow:
			var block_start: int = lines.size() + 1
			for code_line: String in (entry as RawCodeRow).code.split("\n"):
				lines.append(code_line)
			source_map.append({"uid": str((entry as RawCodeRow).get_instance_id()), "start": block_start, "end": lines.size(), "kind": "raw"})
		elif entry is EventRow or entry is EventGroup:
			added_event_rows.append(entry)
		elif entry is CommentRow and (entry as CommentRow).enabled and not (entry as CommentRow).text.strip_edges().is_empty():
			deferred_comment_lines_external.append_array((entry as CommentRow).text.split("\n"))
	# External sheets: raw rows include the original file's verbatim segments, so signals
	# declared anywhere in the source validate self-connections.
	var external_raw_rows: Array = []
	for entry: Variant in sheet.events:
		if entry is RawCodeRow:
			external_raw_rows.append(entry)
	var external_connect_context: Dictionary = {
		"self_class": sheet.host_class if ClassDB.class_exists(sheet.host_class) else "Node",
		"declared_signals": _scan_declared_signals(external_raw_rows)
	}
	_emit_grouped_trigger_functions(added_event_rows, lines, source_map, result, external_connect_context)
	for function_resource: Variant in sheet.functions:
		if not (function_resource is EventFunction):
			continue
		var event_function: EventFunction = function_resource as EventFunction
		if not event_function.enabled or event_function.function_name.strip_edges().is_empty():
			continue
		lines.append("")
		var function_start: int = lines.size() + 1
		_emit_expose_annotations(event_function, sheet, lines)
		lines.append("func %s(%s) -> void:" % [event_function.function_name, _emit_function_params(event_function)])
		var function_events: Array = event_function.events if not event_function.events.is_empty() else event_function.rows
		if not _emit_event_body(function_events, lines, source_map, 1, result["warnings"]):
			lines.append("\tpass")
		source_map.append({"uid": str(event_function.get_instance_id()), "start": function_start, "end": lines.size(), "kind": "function"})

	# Top-level comments emit last, one blank before each line (main path's deferred format).
	for comment_line: String in deferred_comment_lines_external:
		lines.append("")
		lines.append("# %s" % comment_line)
	_insert_provider_member_declarations(lines, result)
	var output: String = "\n".join(lines) + "\n"
	result["output"] = output
	var final_output_path: String = output_path if not output_path.is_empty() else sheet.external_source_path
	var file: FileAccess = FileAccess.open(final_output_path, FileAccess.WRITE)
	if file == null:
		result["success"] = false
		(result["errors"] as Array[String]).append("Failed to open output path: %s" % final_output_path)
		return result
	file.store_string(output)
	file.flush()
	file.close()
	return result

## Instance-backed addon ACEs: baked templates may call through a per-provider member
## (`__eventsheet_provider_<Class>.method(...)`). This pass scans the emitted lines for
## those members and declares each one ONCE as a plain owned instance of the addon class —
## a direct, typed call path with zero EventForge dependency in the output (the addon
## script ships with the game like any other class). Providers extending Node should
## prefer behaviors/autoloads; RefCounted providers are the intended shape.
static func _insert_provider_member_declarations(lines: PackedStringArray, result: Dictionary) -> void:
	var member_regex: RegEx = RegEx.new()
	if member_regex.compile("__eventsheet_provider_([A-Za-z_][A-Za-z0-9_]*)") != OK:
		return
	var providers: Dictionary = {}  # member name -> class name, deduped
	for line: String in lines:
		for regex_match: RegExMatch in member_regex.search_all(line):
			providers[regex_match.get_string(0)] = regex_match.get_string(1)
	if providers.is_empty():
		return
	# Members are declared right before the first function (GDScript allows members
	# anywhere at class level; this placement keeps the generated file readable).
	var insert_index: int = -1
	for index in range(lines.size()):
		if lines[index].begins_with("func ") or lines[index].begins_with("## @ace"):
			insert_index = index
			break
	if insert_index < 0:
		return
	if insert_index > 0 and lines[insert_index - 1].is_empty():
		insert_index -= 1
	var member_names: Array = providers.keys()
	member_names.sort()
	var declarations: PackedStringArray = PackedStringArray()
	declarations.append("")
	declarations.append("# Owned addon-provider instances (instance-backed ACEs; see GDSCRIPT-PAIRING-SPEC).")
	for member_name: Variant in member_names:
		var provider_class: String = str(providers[member_name])
		declarations.append("var %s := %s.new()" % [str(member_name), provider_class])
	for offset in range(declarations.size()):
		lines.insert(insert_index + offset, declarations[offset])

## Signal names declared in class-level GDScript blocks, so self-connections to
## block-declared signals validate at compile time.
static func _scan_declared_signals(raw_blocks: Array) -> Array:
	var declared: Array = []
	var regex: RegEx = RegEx.new()
	regex.compile("(?m)^\\s*signal\\s+([A-Za-z_][A-Za-z0-9_]*)")
	for entry: Variant in raw_blocks:
		if not (entry is RawCodeRow):
			continue
		for regex_match in regex.search_all((entry as RawCodeRow).code):
			declared.append(regex_match.get_string(1))
	return declared

## Groups event rows by trigger and emits one handler function per trigger (the standard
## trigger sections), plus the `_ready` connections signal-backed triggers need. Shared by
## the main compile path and the external (GDScript-backed sheet) path.
## connect_context: {self_class: String, declared_signals: Array} — self-connections are
## validated against these at compile time (emitting a connect to a missing signal would
## make the whole generated script fail to parse).
static func _emit_grouped_trigger_functions(event_rows: Array, lines: PackedStringArray, source_map: Array, result: Dictionary, connect_context: Dictionary = {}) -> void:
	var grouped: Dictionary = {}
	var trigger_order: PackedStringArray = PackedStringArray()
	for entry: Variant in event_rows:
		if not (entry is EventRow):
			continue
		var event_row: EventRow = entry as EventRow
		if not event_row.enabled or event_row.trigger_id.is_empty():
			continue
		var key: String = TriggerResolver.get_trigger_key(event_row)
		if not grouped.has(key):
			grouped[key] = []
			trigger_order.append(key)
		(grouped[key] as Array).append(event_row)

	# Resolve all signatures first so signal-backed triggers' `_ready` connections are
	# known up front (handlers used to be generated but never connected — they only fired
	# when the user wired the signal manually in the scene).
	var signatures: Dictionary = {}
	var ready_connections: PackedStringArray = PackedStringArray()
	for key: String in trigger_order:
		var events: Array = grouped.get(key, [])
		if events.is_empty():
			continue
		var signature: Dictionary = TriggerResolver.resolve_trigger(events[0])
		signatures[key] = signature
		var signal_name: String = str(signature.get("signal_name", ""))
		var function_name: String = str(signature.get("function_name", ""))
		if signal_name.is_empty() or function_name.is_empty():
			continue
		var source_path: String = str(signature.get("source_path", ""))
		if source_path.is_empty():
			# Self-connection: the signal must exist on the script's base class or be
			# declared in a class-level GDScript block, or the generated script would not
			# parse. Skipped connections keep the old behavior (wire it in the scene).
			var self_class: String = str(connect_context.get("self_class", "Node"))
			var declared_signals: Array = connect_context.get("declared_signals", [])
			if not ClassDB.class_has_signal(self_class, signal_name) and not declared_signals.has(signal_name):
				(result["warnings"] as Array[String]).append(
					"Trigger %s: %s has no signal \"%s\" — connection skipped (connect it in the scene or declare the signal in a GDScript block)." % [key, self_class, signal_name]
				)
				continue
		var source_prefix: String = "" if source_path.is_empty() else "get_node(\"%s\")." % source_path
		ready_connections.append("\t%s%s.connect(%s)" % [source_prefix, signal_name, function_name])

	var has_ready_group: bool = false
	for key: String in trigger_order:
		if str((signatures.get(key, {}) as Dictionary).get("function_name", "")) == "_ready":
			has_ready_group = true
	# No OnReady events but connections needed → synthesize a `_ready` for them.
	if not has_ready_group and not ready_connections.is_empty():
		lines.append("")
		lines.append("func _ready() -> void:")
		for connection_line: String in ready_connections:
			lines.append(connection_line)

	for key: String in trigger_order:
		var events: Array = grouped.get(key, [])
		if events.is_empty():
			continue
		var signature: Dictionary = signatures.get(key, {})
		var function_name: String = str(signature.get("function_name", ""))
		if function_name.is_empty():
			(result["warnings"] as Array[String]).append("Unsupported trigger %s" % key)
			continue
		var args: String = str(signature.get("args", ""))
		lines.append("")
		if args.is_empty():
			lines.append("func %s() -> void:" % function_name)
		else:
			lines.append("func %s(%s) -> void:" % [function_name, args])
		var had_body: bool = false
		if function_name == "_ready" and not ready_connections.is_empty():
			# Signal connections run before the user's OnReady logic.
			for connection_line: String in ready_connections:
				lines.append(connection_line)
			had_body = true
		had_body = _emit_event_body(events, lines, source_map, 1, result["warnings"]) or had_body
		if not had_body:
			lines.append("\tpass")

## Emits the condition/action body for a list of event rows, appending to lines.
## Shared by trigger handlers, sheet functions, and (recursively) sub-events.
##
## Semantics, mirroring Construct 3:
## - Each event's conditions emit one `if` at `depth`; its actions and sub-events nest one
##   level deeper. Sub-events therefore run only when the parent's conditions held.
## - An ELSE/ELIF sibling chains onto the previous sibling's `if` (`else:` / `elif c:`).
##   ELSE with conditions is the same thing as ELIF. A chain row without a preceding `if`
##   degrades to a plain event and a warning is recorded.
## - Comments compile to `#` comment lines; GDScript blocks emit with adaptive indentation
##   (pre-indented imported code keeps its own tabs; flat user code is indented for them);
##   variables dropped into an event's flow become function-local `var` declarations.
##
## When source_map is provided, records {uid, start, end, kind} (1-based inclusive lines)
## per emitted row so the editor can highlight a row's generated code.
static func _emit_event_body(
	events: Array,
	lines: PackedStringArray,
	source_map: Array = [],
	depth: int = 1,
	warnings: Array = []
) -> bool:
	var had_body: bool = false
	var indent: String = "\t".repeat(depth)
	# True while the previous sibling ended an if/elif block at this depth, meaning an
	# ELSE/ELIF sibling may legally chain onto it.
	var chain_open: bool = false
	for event_item: Variant in events:
		if event_item is RawCodeRow:
			var raw_row: RawCodeRow = event_item as RawCodeRow
			if raw_row.enabled and not raw_row.code.is_empty():
				var raw_start: int = lines.size() + 1
				for code_line: String in _indent_raw_lines(raw_row.code, depth):
					lines.append(code_line)
					had_body = true
				source_map.append({"uid": str(raw_row.get_instance_id()), "start": raw_start, "end": lines.size(), "kind": "raw"})
			chain_open = false
			continue
		if event_item is CommentRow:
			var comment_row: CommentRow = event_item as CommentRow
			if comment_row.enabled and not comment_row.text.strip_edges().is_empty():
				var comment_start: int = lines.size() + 1
				for comment_line: String in comment_row.text.split("\n"):
					lines.append("%s# %s" % [indent, comment_line])
					had_body = true
				source_map.append({"uid": str(comment_row.get_instance_id()), "start": comment_start, "end": lines.size(), "kind": "comment"})
			# Comments are transparent to else-chaining (annotating a chain shouldn't break it).
			continue
		if event_item is LocalVariable:
			# A variable inside an event's flow is a function-local declaration. @export is
			# meaningless locally and const is not allowed in function scope, so both emit
			# as plain locals (with a warning so the author knows).
			var local_variable: LocalVariable = event_item as LocalVariable
			if not local_variable.name.strip_edges().is_empty():
				if local_variable.exported or local_variable.is_constant:
					warnings.append("Variable '%s' inside an event compiles as a plain local var." % local_variable.name)
				lines.append("%svar %s: %s = %s" % [indent, local_variable.name, local_variable.type_name, _to_code_literal(local_variable.default_value)])
				source_map.append({"uid": str(local_variable.get_instance_id()), "start": lines.size(), "end": lines.size(), "kind": "variable"})
				had_body = true
			chain_open = false
			continue
		if not (event_item is EventRow):
			continue
		var event_row: EventRow = event_item as EventRow
		if not event_row.enabled:
			continue
		var event_start_line: int = lines.size() + 1
		var condition_texts: PackedStringArray = PackedStringArray()
		for condition: ACECondition in event_row.conditions:
			var condition_line: String = ConditionCodegen.generate_condition(condition)
			if not condition_line.is_empty():
				condition_texts.append(condition_line)
		var joiner: String = " or " if event_row.condition_mode == EventRow.ConditionMode.OR else " and "
		var joined_conditions: String = joiner.join(condition_texts)

		# Resolve the block header: if / elif / else, per the chaining rules above.
		var wants_chain: bool = event_row.else_mode != EventRow.ElseMode.NONE
		if wants_chain and not chain_open:
			warnings.append("Else/Else-If event has no preceding conditioned event to chain onto; emitted standalone.")
			wants_chain = false
		var emitted_block: bool = false
		if wants_chain:
			if condition_texts.size() > 0:
				lines.append("%selif %s:" % [indent, joined_conditions])
			else:
				lines.append("%selse:" % indent)
			emitted_block = true
			had_body = true
		elif condition_texts.size() > 0:
			lines.append("%sif %s:" % [indent, joined_conditions])
			emitted_block = true
			had_body = true

		var body_depth: int = depth + (1 if emitted_block else 0)
		# Pick filters (C3 "for each" picking, the Godot way): each enabled filter wraps the
		# event's body in a direct `for` loop — group members, children, or any GDScript
		# iterable — with an optional predicate and first-N cap. Conditions gate the whole
		# loop; multiple filters nest in order. Plain loops keep the parity contract.
		var pick_start_size: int = lines.size()
		body_depth = _emit_pick_filters(event_row, lines, body_depth, warnings)
		var emitted_pick_loop: bool = lines.size() > pick_start_size
		had_body = had_body or emitted_pick_loop
		var body_indent: String = "\t".repeat(body_depth)
		var body_start_size: int = lines.size()

		for action_item: Variant in event_row.actions:
			if action_item is ACEAction:
				var action_line: String = ActionCodegen.generate_action(action_item)
				if action_line.is_empty():
					continue
				if action_item.is_awaited or action_item.await_call:
					action_line = "await %s" % action_line
				lines.append(body_indent + action_line)
				had_body = true
			elif action_item is RawCodeRow:
				# In-flow GDScript block (C3 inline scripting): emitted verbatim inside the
				# event body at the body indent (inner indentation preserved beneath it).
				var inline_raw: RawCodeRow = action_item as RawCodeRow
				if not inline_raw.enabled or inline_raw.code.strip_edges().is_empty():
					continue
				var inline_start: int = lines.size() + 1
				for inline_line: String in inline_raw.code.split("\n"):
					lines.append(body_indent + inline_line)
				had_body = true
				source_map.append({"uid": str(inline_raw.get_instance_id()), "start": inline_start, "end": lines.size(), "kind": "raw"})
			elif action_item is CommentRow:
				# Action-cell comment: annotates the flow, compiles to comment lines.
				var action_comment: CommentRow = action_item as CommentRow
				if action_comment.enabled and not action_comment.text.strip_edges().is_empty():
					var action_comment_start: int = lines.size() + 1
					for comment_line: String in action_comment.text.split("\n"):
						lines.append("%s# %s" % [body_indent, comment_line])
					had_body = true
					source_map.append({"uid": str(action_comment.get_instance_id()), "start": action_comment_start, "end": lines.size(), "kind": "comment"})
			elif action_item is Resource and action_item.has_method("get_row_kind"):
				lines.append(body_indent + "# TODO: row type not yet implemented in Phase 1")
				had_body = true

		# Sub-events run inside the parent's block (under its conditions).
		if not event_row.sub_events.is_empty():
			had_body = _emit_event_body(event_row.sub_events, lines, source_map, body_depth, warnings) or had_body

		# An if/elif/else block (or pick loop) whose body emitted nothing needs `pass` to
		# stay valid GDScript (e.g. a condition-only event, or one whose actions all
		# compiled to nothing).
		if (emitted_block or emitted_pick_loop) and lines.size() == body_start_size:
			lines.append(body_indent + "pass")
			had_body = true
		if lines.size() >= event_start_line:
			source_map.append({"uid": str(event_row.get_instance_id()), "start": event_start_line, "end": lines.size(), "kind": "event"})
		chain_open = emitted_block
	return had_body

## Emits the `for` loop headers for an event's pick filters and returns the new body depth.
## Supported per filter: collection (GROUP → get_nodes_in_group, CHILDREN → get_children,
## EXPRESSION/ARRAY → verbatim GDScript iterable), predicate_expression (iterator-scoped
## GDScript), pick_first_n. order_by is not compiled yet (warning); filter_conditions use
## host-context templates and are likewise warned — write the predicate instead.
static func _emit_pick_filters(event_row: EventRow, lines: PackedStringArray, body_depth: int, warnings: Array) -> int:
	var loop_index: int = 0
	for filter_entry: Variant in event_row.pick_filters:
		if not (filter_entry is PickFilter) or not (filter_entry as PickFilter).enabled:
			continue
		var pick: PickFilter = filter_entry as PickFilter
		var collection: String = _pick_collection_expression(pick)
		if collection.is_empty():
			warnings.append("Pick filter skipped: no collection for kind %d (set collection_value)." % pick.collection_kind)
			continue
		if not pick.order_by_expression.strip_edges().is_empty():
			warnings.append("Pick filter order_by is not compiled yet; iterating in collection order.")
		if not pick.filter_conditions.is_empty():
			warnings.append("Pick filter conditions are not compiled yet; use predicate_expression (iterator-scoped GDScript).")
		var iterator: String = pick.iterator_name.strip_edges()
		if iterator.is_empty():
			iterator = "item"
		var indent: String = "\t".repeat(body_depth)
		var counter_name: String = "__pick_count_%d" % loop_index
		if pick.pick_first_n > 0:
			lines.append("%svar %s: int = 0" % [indent, counter_name])
		lines.append("%sfor %s in %s:" % [indent, iterator, collection])
		body_depth += 1
		indent = "\t".repeat(body_depth)
		var predicate: String = pick.predicate_expression.strip_edges()
		if not predicate.is_empty():
			lines.append("%sif not (%s):" % [indent, predicate])
			lines.append("%s\tcontinue" % indent)
		if pick.pick_first_n > 0:
			lines.append("%s%s += 1" % [indent, counter_name])
			lines.append("%sif %s > %d:" % [indent, counter_name, pick.pick_first_n])
			lines.append("%s\tbreak" % indent)
		loop_index += 1
	return body_depth

## The GDScript iterable a pick filter loops over ("" = unsupported configuration).
static func _pick_collection_expression(pick: PickFilter) -> String:
	var value: String = pick.collection_value.strip_edges()
	if value.is_empty():
		value = pick.source_expression.strip_edges()
	match pick.collection_kind:
		PickFilter.CollectionKind.GROUP:
			return "get_tree().get_nodes_in_group(\"%s\")" % value if not value.is_empty() else ""
		PickFilter.CollectionKind.CHILDREN:
			return "get_children()"
		PickFilter.CollectionKind.EXPRESSION, PickFilter.CollectionKind.ARRAY:
			return value
		_:
			# NODE_PATH_ARRAY / NODE_TREE / CUSTOM: honor an explicit expression, else skip.
			return value

## Indents a sibling GDScript block's lines for `depth`. Imported code already carries its
## own leading tab (function bodies arrive pre-indented for depth 1), while code written in
## the block editor is flat — detect which and prepend accordingly so both emit correctly.
static func _indent_raw_lines(code: String, depth: int) -> PackedStringArray:
	var raw_lines: PackedStringArray = code.split("\n")
	var self_indented: bool = false
	for raw_line: String in raw_lines:
		if not raw_line.strip_edges().is_empty():
			self_indented = raw_line.begins_with("\t")
			break
	var prefix: String = "\t".repeat(depth - 1 if self_indented else depth)
	var output: PackedStringArray = PackedStringArray()
	for raw_line: String in raw_lines:
		output.append(prefix + raw_line if not raw_line.strip_edges().is_empty() else raw_line)
	return output

## Emits the `@ace_*` annotation block above an exposed sheet function. The annotations are
## parsed back by EventSheetSemanticAnalyzer when the compiled script is registered as a
## provider (drop it into res://eventsheet_addons/), publishing the function as an ACE in
## every sheet — the sheet → script → addon loop behaviors and custom nodes build on.
static func _emit_expose_annotations(event_function: EventFunction, sheet: EventSheetResource, lines: PackedStringArray) -> void:
	if not event_function.expose_as_ace:
		# Reflection publishes any public method of a provider script, so unexposed sheet
		# functions are explicitly hidden — expose_as_ace is the single publication switch.
		lines.append("## @ace_hidden")
		return
	lines.append("## @ace_action")
	var display_name: String = event_function.ace_display_name.strip_edges()
	if not display_name.is_empty():
		lines.append("## @ace_name(\"%s\")" % display_name)
	var category: String = event_function.ace_category.strip_edges()
	if not category.is_empty():
		lines.append("## @ace_category(\"%s\")" % category)
	if not event_function.description.strip_edges().is_empty():
		lines.append("## @ace_description(\"%s\")" % event_function.description.strip_edges())
	# The sheet's icon flows to the published ACE (one icon, set once, shown everywhere).
	if not sheet.custom_class_icon.strip_edges().is_empty():
		lines.append("## @ace_icon(\"%s\")" % sheet.custom_class_icon.strip_edges())
	# Default codegen template so consumer sheets compile a direct call: behaviors are
	# child nodes (default node name = class name) → `$Class.fn({args})`; custom-node /
	# plain sheets expose self methods → `fn({args})`. Authors can refine via re-annotation.
	var argument_tokens: PackedStringArray = PackedStringArray()
	for param in event_function.params:
		if param is ACEParam and not (param as ACEParam).id.strip_edges().is_empty():
			argument_tokens.append("{%s}" % (param as ACEParam).id)
	var call_prefix: String = ""
	if sheet.behavior_mode and not sheet.custom_class_name.strip_edges().is_empty():
		call_prefix = "$%s." % sheet.custom_class_name.strip_edges()
	lines.append("## @ace_codegen_template(\"%s%s(%s)\")" % [call_prefix, event_function.function_name, ", ".join(argument_tokens)])

## Builds the typed parameter list for a sheet function (e.g. "amount: int, label: String").
static func _emit_function_params(event_function: EventFunction) -> String:
	var parts: PackedStringArray = PackedStringArray()
	if not event_function.params.is_empty():
		for param: ACEParam in event_function.params:
			if param == null:
				continue
			var param_id: String = param.id if not param.id.is_empty() else param.name
			if param_id.is_empty():
				continue
			var type_name: String = param.type_name
			if type_name.is_empty() or type_name == "Variant":
				parts.append(param_id)
			else:
				parts.append("%s: %s" % [param_id, type_name])
	else:
		for param_name: Variant in event_function.parameters:
			var clean_name: String = str(param_name).strip_edges()
			if not clean_name.is_empty():
				parts.append(clean_name)
	return ", ".join(parts)

## Emits `@export var` lines from the sheet variables dictionary.
static func _emit_variables(variables: Dictionary) -> PackedStringArray:
	var lines: PackedStringArray = PackedStringArray()
	var keys: Array = variables.keys()
	keys.sort()

	for key: Variant in keys:
		var var_name: String = str(key)
		var descriptor: Variant = variables[key]
		if descriptor is Dictionary:
			var type_name: String = str(descriptor.get("type", "Variant"))
			var default_value: Variant = descriptor.get("default", "null")
			var exported: bool = bool(descriptor.get("exported", true))
			var export_prefix: String = "@export " if exported else ""
			lines.append("%svar %s: %s = %s" % [export_prefix, var_name, type_name, _to_code_literal(default_value)])
		else:
			lines.append("@export var %s: Variant = %s" % [var_name, _to_code_literal(descriptor)])

	return lines

## Recursively gathers tree-placed GDScript blocks from the top level and groups (sub-event
## raw blocks stay deferred until sub-events compile).
static func _collect_class_level_raw_rows(entries: Array, into: Array) -> void:
	for entry: Variant in entries:
		if entry is RawCodeRow:
			into.append(entry)
		elif entry is EventGroup:
			var group: EventGroup = entry as EventGroup
			_collect_class_level_raw_rows(group.events if not group.events.is_empty() else group.rows, into)

## Recursively gathers tree-placed LocalVariable rows from the event tree (top level, groups
## and sub-events) so they can be emitted as class-level declarations.
static func _collect_tree_variables(entries: Array, into: Array) -> void:
	for entry: Variant in entries:
		if entry is LocalVariable:
			into.append(entry)
		elif entry is EventGroup:
			var group: EventGroup = entry as EventGroup
			_collect_tree_variables(group.events if not group.events.is_empty() else group.rows, into)
		elif entry is EventRow:
			_collect_tree_variables((entry as EventRow).sub_events, into)

## Emits the class-level declaration for one tree-placed variable (const / @export var / var).
static func _emit_tree_variable_line(local_var: LocalVariable) -> String:
	if local_var == null or local_var.name.strip_edges().is_empty():
		return ""
	if local_var.is_constant:
		return "const %s: %s = %s" % [local_var.name, local_var.type_name, _to_code_literal(local_var.default_value)]
	var export_prefix: String = "@export " if local_var.exported else ""
	return "%svar %s: %s = %s" % [export_prefix, local_var.name, local_var.type_name, _to_code_literal(local_var.default_value)]

## Converts a Variant to a deterministic code literal.
static func _to_code_literal(value: Variant) -> String:
	match typeof(value):
		TYPE_STRING:
			var text: String = str(value)
			if text.begins_with("\"") and text.ends_with("\""):
				return text
			return "\"%s\"" % text.replace("\\", "\\\\").replace("\"", "\\\"")
		TYPE_BOOL:
			return "true" if bool(value) else "false"
		TYPE_FLOAT:
			var float_text: String = str(float(value))
			var normalized_float_text: String = float_text.to_lower()
			if float_text.find(".") == -1 and normalized_float_text.find("e") == -1:
				float_text += ".0"
			return float_text
		TYPE_NIL:
			return "null"
		_:
			return str(value)

## Resolves output path from explicit input or sheet resource path.
static func _resolve_output_path(sheet: EventSheetResource, output_path: String) -> String:
	if not output_path.is_empty():
		return output_path
	if not sheet.resource_path.is_empty():
		var base_name: String = sheet.resource_path.get_file().get_basename()
		return "%s/%s_generated.gd" % [sheet.resource_path.get_base_dir(), base_name]
	return "res://event_sheet_generated.gd"
