# EventForge — Event sheet compiler
# Compiles EventSheetResource assets into deterministic GDScript output.
#
# THE PIPELINE (main path, in emission order — each phase is a "## …" section below):
#   1. includes merge (C3-style; policy-gated — see _merge_includes/_addon_policy)
#   2. header comments, @tool, @ace_tags, @icon, class_name, extends
#   3. behavior host accessor (behavior_mode)
#   4. enums → signals → variables (with Inspector attributes) → tree variables
#      → group locals → stateful-condition members → Lane B uses-instances
#   5. class-level raw GDScript blocks
#   6. trigger sections (events grouped per trigger; _emit_event_body does rows,
#      pick filters/loops, stateful preludes, breakpoints, actions, sub-events)
#   7. sheet functions, deferred comments, provider/stateful member insertion
# The EXTERNAL path (_compile_external) is order-preserving instead: rows re-emit in
# file order so untouched GDScript-backed sheets reproduce byte-identically.
# CONTRACTS: parity (plain GDScript, no runtime indirection), lossless round-trips,
# bake-at-apply (templates), policy-gates-never-bytes (composition).
@tool
extends RefCounted
class_name SheetCompiler

const VERSION: String = "0.8.0"

# Set per-compile from sheet.emit_breakpoints (single-threaded compiles).
static var _emit_breakpoints_flag: bool = false

# Live-values payload for the current compile (same single-threaded pattern as the
# breakpoints flag — the trigger-section helper injects it into _process).
static var _live_values_payload: String = ""
# Whether the current debug compile still needs the edit-back receiver emitted (the
# Live Values window's value edits arrive through it). Cleared once injected.
static var _live_values_receiver_pending: bool = false

# Runtime-toggleable groups: event -> "__group_<snake>_active" guard (per-compile).
static var _runtime_group_guards: Dictionary = {}
# [group snake-name, initially_active] pairs for member emission, in encounter order.
static var _runtime_group_members: Array = []

## Compiles an event sheet resource to a GDScript output file.
static func compile(sheet: EventSheetResource, output_path: String = "") -> Dictionary:
	var result: Dictionary = {
		"success": true,
		"errors": [] as Array[String],
		"warnings": [] as Array[String],
		"output": "",
		# Provenance: [{uid: String (resource instance id), start: int, end: int, kind: String}]
		# with 1-based inclusive line numbers into "output". Lets the editor highlight the
		# generated lines for a selected sheet row.
		"source_map": [] as Array
	}

	if sheet == null:
		result["success"] = false
		(result["errors"] as Array[String]).append("Sheet is null")
		return result

	# GDScript-backed sheets (opened FROM a .gd file) compile via the order-preserving
	# external path: no generated header, no synthesized extends, rows emit in sheet order
	# so an untouched file reproduces byte-identically. See GDSCRIPT-PAIRING-SPEC.
	if not sheet.external_source_path.is_empty():
		return _compile_external(sheet, result, output_path)

	_emit_breakpoints_flag = sheet.emit_breakpoints
	_runtime_group_guards = {}
	_runtime_group_members = []
	# C3-style includes: merge included sheets' rows/variables/functions (compile-time
	# only; the root sheet wins collisions, cycles are skipped with warnings).
	var all_events: Array = sheet.events.duplicate()
	var all_functions: Array = sheet.functions.duplicate()
	var merged_variables: Dictionary = sheet.variables.duplicate(true)
	if not sheet.includes.is_empty():
		var visited: Dictionary = {}
		if not sheet.resource_path.is_empty():
			visited[sheet.resource_path] = true
		_merge_includes(sheet, all_events, all_functions, merged_variables, visited, result["warnings"], result["errors"], 1)
		if not (result["errors"] as Array).is_empty():
			result["success"] = false
			return result

	var lines: PackedStringArray = PackedStringArray()
	lines.append("# AUTO-GENERATED by EventForge v%s" % VERSION)
	lines.append("# Source: %s" % sheet.resource_path)
	lines.append("# DO NOT EDIT — this file is regenerated on every compile.")
	lines.append("")
	# Tool sheets (EXPERIMENTAL): @tool must precede class_name/extends.
	if sheet.tool_mode:
		lines.append("@tool")
	# A named sheet defines a custom node type: `@icon` + `class_name` make the generated
	# script register in the Create Node dialog exactly like hand-written GDScript.
	if not sheet.custom_class_name.strip_edges().is_empty():
		if not sheet.addon_tags.is_empty():
			lines.append("## @ace_tags(%s)" % ", ".join(sheet.addon_tags))
		if not sheet.custom_class_icon.strip_edges().is_empty():
			lines.append("@icon(\"%s\")" % sheet.custom_class_icon)
		lines.append("class_name %s" % sheet.custom_class_name.strip_edges())
	# Behavior sheets compile to attachable Node components that act on their PARENT (the
	# host) — Godot's component idiom standing in for Construct 3 behaviors. host_class is
	# the declared required host type, not the script's base.
	if sheet.behavior_mode:
		lines.append("extends Node")
	else:
		lines.append("extends %s" % sheet.host_class)

	var source_map: Array = result["source_map"]
	if sheet.behavior_mode:
		var host_type: String = sheet.host_class if ClassDB.class_exists(sheet.host_class) else "Node"
		var behavior_label: String = sheet.custom_class_name.strip_edges()
		if behavior_label.is_empty():
			behavior_label = "This"
		lines.append("")
		lines.append("## The node this behavior acts on (its parent). Required host: %s." % host_type)
		lines.append("var host: %s = null" % host_type)
		lines.append("")
		lines.append("func _enter_tree() -> void:")
		lines.append("\thost = get_parent() as %s" % host_type)
		lines.append("\tif host == null:")
		lines.append("\t\tpush_warning(\"%s behavior requires a %s parent.\")" % [behavior_label, host_type])
		# Lane B.2: declared sibling dependencies surface as the editor's ⚠ badge.
		var required_behaviors: PackedStringArray = PackedStringArray()
		for required_entry: String in sheet.requires_behaviors:
			if EventSheetIdentifierRules.is_valid(required_entry.strip_edges()):
				required_behaviors.append("\"%s\"" % required_entry.strip_edges())
			elif not required_entry.strip_edges().is_empty():
				(result["warnings"] as Array).append("Requires entry \"%s\" isn't a valid class name — skipped." % required_entry.strip_edges())
		if not required_behaviors.is_empty():
			lines.append("")
			lines.append("## Declared sibling dependencies (attach these to the same parent).")
			lines.append("func _get_configuration_warnings() -> PackedStringArray:")
			lines.append("\tvar dependency_warnings: PackedStringArray = PackedStringArray()")
			lines.append("\tfor required_class: String in [%s]:" % ", ".join(required_behaviors))
			lines.append("\t\tvar dependency_found: bool = false")
			lines.append("\t\tfor sibling: Node in (get_parent().get_children() if get_parent() != null else []):")
			lines.append("\t\t\tif sibling.is_class(required_class) or (sibling.get_script() != null and str(sibling.get_script().get_global_name()) == required_class):")
			lines.append("\t\t\t\tdependency_found = true")
			lines.append("\t\t\t\tbreak")
			lines.append("\t\tif not dependency_found:")
			lines.append("\t\t\tdependency_warnings.append(\"Requires a %s sibling behavior.\" % required_class)")
			lines.append("\treturn dependency_warnings")
	# Enums emit FIRST so enum-typed variable declarations below can reference them.
	var enum_rows: Array = []
	_collect_enum_rows(all_events, enum_rows)
	if not enum_rows.is_empty():
		lines.append("")
		for enum_entry: Variant in enum_rows:
			var enum_line: String = _emit_enum_line(enum_entry as EnumRow)
			if enum_line.is_empty():
				continue
			lines.append(enum_line)
			source_map.append({"uid": str((enum_entry as EnumRow).get_instance_id()), "start": lines.size(), "end": lines.size(), "kind": "enum"})
	var signal_rows: Array = []
	_collect_signal_rows(all_events, signal_rows)
	if not signal_rows.is_empty():
		lines.append("")
		for signal_entry: Variant in signal_rows:
			var signal_line: String = _emit_signal_line(signal_entry as SignalRow)
			if signal_line.is_empty():
				continue
			lines.append(signal_line)
			source_map.append({"uid": str((signal_entry as SignalRow).get_instance_id()), "start": lines.size(), "end": lines.size(), "kind": "signal"})
	var tree_variables: Array = []
	_collect_tree_variables(all_events, tree_variables)
	var sheet_function_names: Dictionary = {}
	for known_function: Variant in all_functions:
		if known_function is EventFunction:
			sheet_function_names[(known_function as EventFunction).function_name] = true
	var variable_lines: PackedStringArray = _emit_variables(merged_variables, result["warnings"], sheet_function_names)
	if variable_lines.size() > 0:
		lines.append("")
		for line: String in variable_lines:
			lines.append(line)
	if not tree_variables.is_empty():
		if variable_lines.is_empty():
			lines.append("")
		for tree_entry: Variant in tree_variables:
			var declaration: String = _emit_tree_variable_line(tree_entry as LocalVariable)
			if declaration.is_empty():
				continue
			lines.append(declaration)
			source_map.append({"uid": str((tree_entry as LocalVariable).get_instance_id()), "start": lines.size(), "end": lines.size(), "kind": "variable"})

	# C3 group-local variables: class members under a per-group header comment.
	var group_local_sets: Array = []
	_collect_group_locals(all_events, group_local_sets)
	for group_set: Dictionary in group_local_sets:
		lines.append("")
		lines.append("# %s — group locals" % str(group_set.get("group", "Group")))
		for local_entry: Variant in group_set.get("locals", []):
			var local_line: String = _emit_tree_variable_line(local_entry as LocalVariable)
			if not local_line.is_empty():
				lines.append(local_line)
				source_map.append({"uid": str((local_entry as LocalVariable).get_instance_id()), "start": lines.size(), "end": lines.size(), "kind": "variable"})

	# Runtime-toggleable group flags (Set Group Active targets these members). Collected
	# in a dedicated early pass — the flatten that ALSO maps guards runs later, in the
	# trigger-section phase, after this member block has already emitted.
	_collect_runtime_group_members(all_events)
	if not _runtime_group_members.is_empty():
		if variable_lines.is_empty() and tree_variables.is_empty():
			lines.append("")
		for group_member: Array in _runtime_group_members:
			lines.append("var %s: bool = %s" % [str(group_member[0]), "true" if bool(group_member[1]) else "false"])

	# Stateful-condition members (Every X Seconds…): one class member per applied instance.
	var stateful_members: Array = []
	_collect_stateful_members(all_events, stateful_members)
	for function_entry: Variant in all_functions:
		if function_entry is EventFunction:
			_collect_stateful_members((function_entry as EventFunction).events if not (function_entry as EventFunction).events.is_empty() else (function_entry as EventFunction).rows, stateful_members)
	if not stateful_members.is_empty():
		if variable_lines.is_empty() and tree_variables.is_empty():
			lines.append("")
		for member_line: String in stateful_members:
			lines.append(member_line)

	# Live values (debugging rung 2): a throttle timer member; the send block itself
	# lands inside _process below. Variables list is baked at compile time.
	_live_values_payload = ""
	_live_values_receiver_pending = false
	if sheet.emit_live_values:
		var live_keys: Array = merged_variables.keys()
		live_keys.sort()
		var payload_parts: PackedStringArray = PackedStringArray()
		for live_key: Variant in live_keys:
			payload_parts.append("\"%s\", %s" % [str(live_key), str(live_key)])
		if payload_parts.is_empty():
			(result["warnings"] as Array).append("Live values: this sheet has no variables to stream — add some or turn the toggle off.")
		else:
			_live_values_payload = ", ".join(payload_parts)
			_live_values_receiver_pending = true
			if variable_lines.is_empty() and tree_variables.is_empty():
				lines.append("")
			lines.append("var __live_values_timer: float = 0.0")

	# Lane B composition (has-a): owned helper instances for the declared addon classes.
	if not sheet.uses_addons.is_empty():
		if variable_lines.is_empty() and tree_variables.is_empty():
			lines.append("")
		for uses_class: String in sheet.uses_addons:
			var trimmed_class: String = uses_class.strip_edges()
			if trimmed_class.is_empty():
				continue
			if not EventSheetIdentifierRules.is_valid(trimmed_class):
				(result["warnings"] as Array).append("Uses entry \"%s\" isn't a valid class name — skipped." % trimmed_class)
				continue
			lines.append("var __uses_%s := %s.new()" % [trimmed_class.to_snake_case(), trimmed_class])

	# Tool buttons (Inspector-attributes spec, Tier 2): one Callable export per labeled
	# sheet function. The Callable resolves at class scope, so emitting before the
	# function bodies is fine.
	var emitted_tool_button: bool = false
	for button_function: Variant in all_functions:
		if button_function is EventFunction and not (button_function as EventFunction).tool_button_label.strip_edges().is_empty():
			var button_label: String = (button_function as EventFunction).tool_button_label.strip_edges()
			var button_target: String = (button_function as EventFunction).function_name
			if not emitted_tool_button:
				lines.append("")
				emitted_tool_button = true
			lines.append("@export_tool_button(\"%s\") var _btn_%s: Callable = %s" % [button_label.c_escape(), button_target, button_target])
	if emitted_tool_button and not sheet.tool_mode:
		(result["warnings"] as Array).append("Tool buttons need a @tool sheet to run in the editor — enable Tool in the Sheet Type dialog.")

	# Tree-placed GDScript blocks (top level / inside groups) are emitted verbatim at class
	# level — helper functions, @onready vars, signal declarations, etc.
	var raw_blocks: Array = []
	_collect_class_level_raw_rows(all_events, raw_blocks)
	for raw_entry: Variant in raw_blocks:
		var raw_block: RawCodeRow = raw_entry as RawCodeRow
		if raw_block == null or not raw_block.enabled or raw_block.code.strip_edges().is_empty():
			continue
		lines.append("")
		var raw_start: int = lines.size() + 1
		for code_line: String in raw_block.code.split("\n"):
			lines.append(code_line)
		source_map.append({"uid": str(raw_block.get_instance_id()), "start": raw_start, "end": lines.size(), "kind": "raw"})

	for hook_name: String in ["_validate_property", "_get_configuration_warnings", "_process", "_ready", "_physics_process"]:
		var hook_generated: bool = false
		for emitted_line: String in lines:
			if emitted_line.begins_with("func %s(" % hook_name):
				hook_generated = true
				break
		if hook_generated:
			for raw_entry2: Variant in raw_blocks:
				if raw_entry2 is RawCodeRow and (raw_entry2 as RawCodeRow).code.contains("func %s(" % hook_name):
					(result["warnings"] as Array).append("A GDScript block also defines %s() — remove it or clear the Inspector/Requires settings (duplicate functions don't compile)." % hook_name)

	var deferred_rows: PackedStringArray = PackedStringArray()
	var top_level_events: Array = []
	for row: Variant in all_events:
		if not (row is Resource):
			continue
		if row is LocalVariable:
			continue  # emitted above as a class-level variable
		if row is RawCodeRow:
			continue  # emitted above as a class-level GDScript block
		if row is CommentRow:
			# Top-level comments compile to real comment lines (emitted after the trigger
			# sections — position is approximate, content is preserved).
			if (row as CommentRow).enabled and not (row as CommentRow).text.strip_edges().is_empty():
				for comment_line: String in (row as CommentRow).text.split("\n"):
					deferred_rows.append("# %s" % comment_line)
			continue
		if row is EventGroup:
			# Groups are organizational: their events compile inline (the helper flattens,
			# honoring C3 semantics — a DISABLED group drops all of its children).
			top_level_events.append(row)
			continue
		if row is EnumRow or row is SignalRow:
			continue  # emitted above as class-level declarations
		if row.has_method("get_row_kind") and str(row.call("get_row_kind")) != "event":
			deferred_rows.append("# (unknown row type — preserved as a comment so nothing is silently dropped)")
			continue
		if not (row is EventRow):
			continue
		var event_row: EventRow = row
		if not event_row.enabled:
			continue
		if event_row.trigger_id.is_empty():
			(result["warnings"] as Array[String]).append("Skipping event %s with no trigger" % event_row.event_uid)
			continue
		top_level_events.append(event_row)
	var declared_signals: Array = _scan_declared_signals(raw_blocks)
	for signal_entry: Variant in signal_rows:
		if signal_entry is SignalRow and (signal_entry as SignalRow).enabled:
			declared_signals.append((signal_entry as SignalRow).signal_name)
	var connect_context: Dictionary = {
		"self_class": "Node" if sheet.behavior_mode else (sheet.host_class if ClassDB.class_exists(sheet.host_class) else "Node"),
		"declared_signals": declared_signals
	}
	var group_comment_lines: PackedStringArray = PackedStringArray()
	_emit_grouped_trigger_functions(top_level_events, lines, source_map, result, connect_context, group_comment_lines)
	for group_comment_line: String in group_comment_lines:
		deferred_rows.append("# %s" % group_comment_line)

	if not _live_values_payload.is_empty():
		lines.append("")
		lines.append("func _process(delta: float) -> void:")
		lines.append("\t__live_values_timer += delta")
		lines.append("\tif __live_values_timer >= 0.25 and EngineDebugger.is_active():")
		lines.append("\t\t__live_values_timer = 0.0")
		lines.append("\t\tEngineDebugger.send_message(\"eventsheets:live_values\", [%s])" % _live_values_payload)
		_live_values_payload = ""

	if sheet.emit_live_values and not sheet.variables.is_empty():
		lines.append("")
		lines.append("## Live Values edit-back receiver (debug sessions only).")
		lines.append("func _eventsheets_debug_set(message: String, data: Array) -> bool:")
		lines.append("\tif message != \"set_value\" or data.size() < 2:")
		lines.append("\t\treturn false")
		lines.append("\tset(str(data[0]), data[1])")
		lines.append("\treturn true")

	# Emit sheet functions as callable GDScript methods (after the trigger handlers).
	for function_resource: Variant in all_functions:
		if not (function_resource is EventFunction):
			continue
		var event_function: EventFunction = function_resource as EventFunction
		if not event_function.enabled or event_function.function_name.strip_edges().is_empty():
			continue
		lines.append("")
		var function_start: int = lines.size() + 1
		_emit_expose_annotations(event_function, sheet, lines)
		lines.append("func %s(%s) -> %s:" % [event_function.function_name, _emit_function_params(event_function), _function_return_type_name(event_function)])
		var function_events: Array = event_function.events if not event_function.events.is_empty() else event_function.rows
		var function_had_body: bool = _emit_event_body(function_events, lines, source_map, 1, result["warnings"])
		if not function_had_body:
			lines.append("\tpass")
		source_map.append({"uid": str(event_function.get_instance_id()), "start": function_start, "end": lines.size(), "kind": "function"})

	for deferred: String in deferred_rows:
		lines.append("")
		lines.append(deferred)

	_insert_stateful_member_declarations(lines, sheet)
	_insert_provider_member_declarations(lines, result)
	var output: String = "\n".join(lines) + "\n"
	result["output"] = output

	var final_output_path: String = _resolve_output_path(sheet, output_path)
	var file: FileAccess = FileAccess.open(final_output_path, FileAccess.WRITE)
	if file == null:
		result["success"] = false
		(result["errors"] as Array[String]).append("Failed to open output path: %s" % final_output_path)
		return result

	file.store_string(output)
	file.flush()
	file.close()
	return result

## Order-preserving emission for GDScript-backed sheets: rows reproduce the original file
## (verbatim blocks + verify-lifted variables) in sheet order; events/groups the user adds
## afterwards append as standard trigger functions at the end. Disabled blocks still emit —
## external mode is lossless, never a filter.
static func _compile_external(sheet: EventSheetResource, result: Dictionary, output_path: String) -> Dictionary:
	_live_values_receiver_pending = false
	_emit_breakpoints_flag = sheet.emit_breakpoints
	_live_values_payload = ""
	if not sheet.includes.is_empty() or not sheet.uses_addons.is_empty() or not sheet.requires_behaviors.is_empty():
		(result["warnings"] as Array).append("GDScript-backed sheets ignore Includes/Uses/Requires — the .gd file is the source of truth (write the equivalent code directly).")
	var lines: PackedStringArray = PackedStringArray()
	var source_map: Array = result["source_map"]
	var added_event_rows: Array = []
	var deferred_comment_lines_external: PackedStringArray = PackedStringArray()
	for entry: Variant in sheet.events:
		if entry is LocalVariable:
			var declaration: String = _emit_tree_variable_line(entry as LocalVariable)
			lines.append(declaration)
			source_map.append({"uid": str((entry as LocalVariable).get_instance_id()), "start": lines.size(), "end": lines.size(), "kind": "variable"})
		elif entry is RawCodeRow:
			var block_start: int = lines.size() + 1
			for code_line: String in (entry as RawCodeRow).code.split("\n"):
				lines.append(code_line)
			source_map.append({"uid": str((entry as RawCodeRow).get_instance_id()), "start": block_start, "end": lines.size(), "kind": "raw"})
		elif entry is EventRow or entry is EventGroup:
			added_event_rows.append(entry)
		elif entry is CommentRow and (entry as CommentRow).enabled and not (entry as CommentRow).text.strip_edges().is_empty():
			deferred_comment_lines_external.append_array((entry as CommentRow).text.split("\n"))
		elif entry is EnumRow:
			var external_enum_line: String = _emit_enum_line(entry as EnumRow)
			if not external_enum_line.is_empty():
				lines.append(external_enum_line)
				source_map.append({"uid": str((entry as EnumRow).get_instance_id()), "start": lines.size(), "end": lines.size(), "kind": "enum"})
		elif entry is SignalRow:
			var external_signal_line: String = _emit_signal_line(entry as SignalRow)
			if not external_signal_line.is_empty():
				lines.append(external_signal_line)
				source_map.append({"uid": str((entry as SignalRow).get_instance_id()), "start": lines.size(), "end": lines.size(), "kind": "signal"})
	# External sheets: raw rows include the original file's verbatim segments, so signals
	# declared anywhere in the source validate self-connections.
	var external_raw_rows: Array = []
	for entry: Variant in sheet.events:
		if entry is RawCodeRow:
			external_raw_rows.append(entry)
	var external_connect_context: Dictionary = {
		"self_class": sheet.host_class if ClassDB.class_exists(sheet.host_class) else "Node",
		"declared_signals": _scan_declared_signals(external_raw_rows)
	}
	_emit_grouped_trigger_functions(added_event_rows, lines, source_map, result, external_connect_context, deferred_comment_lines_external)
	for function_resource: Variant in sheet.functions:
		if not (function_resource is EventFunction):
			continue
		var event_function: EventFunction = function_resource as EventFunction
		if not event_function.enabled or event_function.function_name.strip_edges().is_empty():
			continue
		lines.append("")
		var function_start: int = lines.size() + 1
		_emit_expose_annotations(event_function, sheet, lines)
		lines.append("func %s(%s) -> %s:" % [event_function.function_name, _emit_function_params(event_function), _function_return_type_name(event_function)])
		var function_events: Array = event_function.events if not event_function.events.is_empty() else event_function.rows
		if not _emit_event_body(function_events, lines, source_map, 1, result["warnings"]):
			lines.append("\tpass")
		source_map.append({"uid": str(event_function.get_instance_id()), "start": function_start, "end": lines.size(), "kind": "function"})

	# Top-level comments emit last, one blank before each line (main path's deferred format).
	for comment_line: String in deferred_comment_lines_external:
		lines.append("")
		lines.append("# %s" % comment_line)
	_insert_stateful_member_declarations(lines, sheet)
	_insert_provider_member_declarations(lines, result)
	var output: String = "\n".join(lines) + "\n"
	result["output"] = output
	var final_output_path: String = output_path if not output_path.is_empty() else sheet.external_source_path
	var file: FileAccess = FileAccess.open(final_output_path, FileAccess.WRITE)
	if file == null:
		result["success"] = false
		(result["errors"] as Array[String]).append("Failed to open output path: %s" % final_output_path)
		return result
	file.store_string(output)
	file.flush()
	file.close()
	return result

## Instance-backed addon ACEs: baked templates may call through a per-provider member
## (`__eventsheet_provider_<Class>.method(...)`). This pass scans the emitted lines for
## those members and declares each one ONCE as a plain owned instance of the addon class —
## a direct, typed call path with zero EventForge dependency in the output (the addon
## script ships with the game like any other class). Providers extending Node should
## prefer behaviors/autoloads; RefCounted providers are the intended shape.
## External-path counterpart of the main path's stateful-member emission: declares the
## members baked onto stateful conditions (Every X Seconds…) before the first function,
## skipping any already present verbatim (untouched files stay byte-identical).
static func _insert_stateful_member_declarations(lines: PackedStringArray, sheet: EventSheetResource) -> void:
	var members: Array = []
	_collect_stateful_members(sheet.events, members)
	for function_entry: Variant in sheet.functions:
		if function_entry is EventFunction:
			_collect_stateful_members((function_entry as EventFunction).events if not (function_entry as EventFunction).events.is_empty() else (function_entry as EventFunction).rows, members)
	var missing: PackedStringArray = PackedStringArray()
	for member_line: Variant in members:
		if not lines.has(str(member_line)):
			missing.append(str(member_line))
	if missing.is_empty():
		return
	var insert_index: int = -1
	for index in range(lines.size()):
		if lines[index].begins_with("func ") or lines[index].begins_with("## @ace"):
			insert_index = index
			break
	if insert_index < 0:
		insert_index = lines.size()
	for offset in range(missing.size()):
		lines.insert(insert_index + offset, missing[offset])
	lines.insert(insert_index + missing.size(), "")

static func _insert_provider_member_declarations(lines: PackedStringArray, result: Dictionary) -> void:
	var member_regex: RegEx = RegEx.new()
	if member_regex.compile("__eventsheet_provider_([A-Za-z_][A-Za-z0-9_]*)") != OK:
		return
	var providers: Dictionary = {}  # member name -> class name, deduped
	for line: String in lines:
		for regex_match: RegExMatch in member_regex.search_all(line):
			providers[regex_match.get_string(0)] = regex_match.get_string(1)
	if providers.is_empty():
		return
	# Members are declared right before the first function (GDScript allows members
	# anywhere at class level; this placement keeps the generated file readable).
	var insert_index: int = -1
	for index in range(lines.size()):
		if lines[index].begins_with("func ") or lines[index].begins_with("## @ace"):
			insert_index = index
			break
	if insert_index < 0:
		return
	if insert_index > 0 and lines[insert_index - 1].is_empty():
		insert_index -= 1
	var member_names: Array = providers.keys()
	member_names.sort()
	var declarations: PackedStringArray = PackedStringArray()
	declarations.append("")
	declarations.append("# Owned addon-provider instances (instance-backed ACEs; see GDSCRIPT-PAIRING-SPEC).")
	for member_name: Variant in member_names:
		var provider_class: String = str(providers[member_name])
		declarations.append("var %s := %s.new()" % [str(member_name), provider_class])
	for offset in range(declarations.size()):
		lines.insert(insert_index + offset, declarations[offset])

## Recursively merges included sheets (see EventSheetResource.includes): variables and
## functions skip name collisions with a warning (root wins), rows append in include
## order. Compile-time only — included rows never enter the editing model.
## Composition policy (docs/ADDON-COMPOSITION-SPEC.md): ProjectSettings gates under
## "eventsheets/addons/*". THE INVARIANT: policy never changes emitted bytes — it only
## decides allowed (error), flagged (warning) or clean. Defaults are permissive so jams
## never meet the policy system.
static func _addon_policy(key: String, default_value: Variant) -> Variant:
	var setting_name: String = "eventsheets/addons/%s" % key
	if ProjectSettings.has_setting(setting_name):
		return ProjectSettings.get_setting(setting_name)
	return default_value

static func _merge_includes(sheet: EventSheetResource, all_events: Array, all_functions: Array, merged_variables: Dictionary, visited: Dictionary, warnings: Array, errors: Array = [], depth: int = 1) -> void:
	var composition_mode: String = str(_addon_policy("composition_mode", "allowed"))
	var max_depth: int = int(_addon_policy("max_include_depth", 2))
	var collision_policy: String = str(_addon_policy("collision_policy", "warn"))
	var include_sources: String = str(_addon_policy("include_sources", "anywhere"))
	var deprecated_blocks: String = str(_addon_policy("deprecated_tag_blocks", "warn"))
	for include_entry: Variant in sheet.includes:
		var include_path: String = str(include_entry).strip_edges()
		if include_path.is_empty():
			continue
		if composition_mode == "off" and sheet.behavior_mode:
			var sheet_label: String = sheet.resource_path.get_file() if not sheet.resource_path.is_empty() else (sheet.custom_class_name if not sheet.custom_class_name.is_empty() else "this sheet")
			errors.append("Policy: addon composition is off (eventsheets/addons/composition_mode) — %s can't include %s." % [sheet_label, include_path.get_file()])
			continue
		if depth > max_depth:
			var depth_message: String = "Include chain deeper than policy max (%d): %s. Deep chains are where addon ecosystems rot — consider flattening." % [max_depth, include_path.get_file()]
			if str(_addon_policy("depth_overflow", "warn")) == "error":
				errors.append(depth_message)
				continue
			warnings.append(depth_message)
		if visited.has(include_path):
			warnings.append("Include skipped (cycle or duplicate): %s" % include_path)
			continue
		visited[include_path] = true
		if not ResourceLoader.exists(include_path):
			warnings.append("Include not found: %s" % include_path)
			continue
		var included: EventSheetResource = load(include_path) as EventSheetResource
		if included == null:
			warnings.append("Include is not an EventSheetResource: %s" % include_path)
			continue
		if include_sources.begins_with("tagged:"):
			var required_tag: String = include_sources.trim_prefix("tagged:").strip_edges()
			if not included.addon_tags.has(required_tag):
				errors.append("Policy: includes must be tagged \"%s\" (eventsheets/addons/include_sources) — %s isn't." % [required_tag, include_path.get_file()])
				continue
		if included.addon_tags.has("deprecated") and deprecated_blocks != "off":
			var deprecated_message: String = "Include %s is tagged deprecated." % include_path.get_file()
			if deprecated_blocks == "error":
				errors.append(deprecated_message)
				continue
			warnings.append(deprecated_message)
		for variable_name: Variant in included.variables.keys():
			if merged_variables.has(variable_name):
				if collision_policy == "error":
					errors.append("Include %s: variable \"%s\" already defined (collision_policy = error)." % [include_path.get_file(), variable_name])
				elif collision_policy != "silent":
					warnings.append("Include %s: variable \"%s\" already defined — root wins." % [include_path.get_file(), variable_name])
			else:
				merged_variables[variable_name] = included.variables[variable_name]
		var existing_function_names: Dictionary = {}
		for existing: Variant in all_functions:
			if existing is EventFunction:
				existing_function_names[(existing as EventFunction).function_name] = true
		for function_resource: Variant in included.functions:
			if function_resource is EventFunction and existing_function_names.has((function_resource as EventFunction).function_name):
				if collision_policy == "error":
					errors.append("Include %s: function \"%s\" already defined (collision_policy = error)." % [include_path.get_file(), (function_resource as EventFunction).function_name])
					continue
				warnings.append("Include %s: function \"%s\" already defined — root wins." % [include_path.get_file(), (function_resource as EventFunction).function_name])
			else:
				all_functions.append(function_resource)
		all_events.append_array(included.events)
		_merge_includes(included, all_events, all_functions, merged_variables, visited, warnings, errors, depth + 1)

## Flattens trigger-bearing rows for emission: EventRows kept, ENABLED groups recursed
## (a disabled group drops all of its children — C3 group-disable semantics), and group
## comments collected as deferred comment lines.
static func _flatten_trigger_rows(rows: Array, into_events: Array, deferred_comment_lines: PackedStringArray, runtime_guard: String = "") -> void:
	for row: Variant in rows:
		if row is EventRow:
			if not runtime_guard.is_empty():
				_runtime_group_guards[row] = runtime_guard
			into_events.append(row)
		elif row is EventGroup:
			var group: EventGroup = row as EventGroup
			if group.enabled:
				# Runtime-toggleable groups guard their events (nested groups inherit the
				# INNERMOST toggleable guard — toggling the inner group wins, C3-style).
				var child_guard: String = runtime_guard
				if group.runtime_toggleable:
					var guard_token: String = group.group_name.to_snake_case() if not group.group_name.is_empty() else "group"
					child_guard = "__group_%s_active" % guard_token
					var already_known: bool = false
					for member_pair: Array in _runtime_group_members:
						if str(member_pair[0]) == child_guard:
							already_known = true
					if not already_known:
						_runtime_group_members.append([child_guard, group.enabled])
				_flatten_trigger_rows(group.events if not group.events.is_empty() else group.rows, into_events, deferred_comment_lines, child_guard)
		elif row is CommentRow and (row as CommentRow).enabled and not (row as CommentRow).text.strip_edges().is_empty():
			deferred_comment_lines.append_array((row as CommentRow).text.split("
"))

## Signal names declared in class-level GDScript blocks, so self-connections to
## block-declared signals validate at compile time.
static func _scan_declared_signals(raw_blocks: Array) -> Array:
	var declared: Array = []
	var regex: RegEx = RegEx.new()
	regex.compile("(?m)^\\s*signal\\s+([A-Za-z_][A-Za-z0-9_]*)")
	for entry: Variant in raw_blocks:
		if not (entry is RawCodeRow):
			continue
		for regex_match in regex.search_all((entry as RawCodeRow).code):
			declared.append(regex_match.get_string(1))
	return declared

## Groups event rows by trigger and emits one handler function per trigger (the standard
## trigger sections), plus the `_ready` connections signal-backed triggers need. Shared by
## the main compile path and the external (GDScript-backed sheet) path.
## connect_context: {self_class: String, declared_signals: Array} — self-connections are
## validated against these at compile time (emitting a connect to a missing signal would
## make the whole generated script fail to parse).
static func _emit_grouped_trigger_functions(event_rows: Array, lines: PackedStringArray, source_map: Array, result: Dictionary, connect_context: Dictionary = {}, deferred_comment_lines: PackedStringArray = PackedStringArray()) -> void:
	var flattened: Array = []
	_flatten_trigger_rows(event_rows, flattened, deferred_comment_lines)
	var grouped: Dictionary = {}
	var trigger_order: PackedStringArray = PackedStringArray()
	for entry: Variant in flattened:
		if not (entry is EventRow):
			continue
		var event_row: EventRow = entry as EventRow
		if not event_row.enabled or event_row.trigger_id.is_empty():
			continue
		var key: String = TriggerResolver.get_trigger_key(event_row)
		if not grouped.has(key):
			grouped[key] = []
			trigger_order.append(key)
		(grouped[key] as Array).append(event_row)

	# Resolve all signatures first so signal-backed triggers' `_ready` connections are
	# known up front (handlers used to be generated but never connected — they only fired
	# when the user wired the signal manually in the scene).
	var signatures: Dictionary = {}
	var ready_connections: PackedStringArray = PackedStringArray()
	for key: String in trigger_order:
		var events: Array = grouped.get(key, [])
		if events.is_empty():
			continue
		var signature: Dictionary = TriggerResolver.resolve_trigger(events[0])
		signatures[key] = signature
		var signal_name: String = str(signature.get("signal_name", ""))
		var function_name: String = str(signature.get("function_name", ""))
		if signal_name.is_empty() or function_name.is_empty():
			continue
		var source_path: String = str(signature.get("source_path", ""))
		if source_path.is_empty():
			# Self-connection: the signal must exist on the script's base class or be
			# declared in a class-level GDScript block, or the generated script would not
			# parse. Skipped connections keep the old behavior (wire it in the scene).
			var self_class: String = str(connect_context.get("self_class", "Node"))
			var declared_signals: Array = connect_context.get("declared_signals", [])
			if not ClassDB.class_has_signal(self_class, signal_name) and not declared_signals.has(signal_name):
				(result["warnings"] as Array[String]).append(
					"Trigger %s: %s has no signal \"%s\" — connection skipped (connect it in the scene or declare the signal in a GDScript block)." % [key, self_class, signal_name]
				)
				continue
		var source_prefix: String = ""
		if source_path.begins_with("autoload:"):
			# Bus triggers: autoloads are global — connect by name, no node paths.
			source_prefix = "%s." % source_path.trim_prefix("autoload:")
		elif not source_path.is_empty():
			source_prefix = "get_node(\"%s\")." % source_path
		ready_connections.append("\t%s%s.connect(%s)" % [source_prefix, signal_name, function_name])

	var has_ready_group: bool = false
	for key: String in trigger_order:
		if str((signatures.get(key, {}) as Dictionary).get("function_name", "")) == "_ready":
			has_ready_group = true
	# No OnReady events but connections/receiver needed → synthesize a `_ready`.
	if not has_ready_group and (not ready_connections.is_empty() or _live_values_receiver_pending):
		lines.append("")
		lines.append("func _ready() -> void:")
		if _live_values_receiver_pending:
			lines.append("\tif EngineDebugger.is_active() and not EngineDebugger.has_capture(\"eventsheets\"):")
			lines.append("\t\tEngineDebugger.register_message_capture(&\"eventsheets\", _eventsheets_debug_set)")
			_live_values_receiver_pending = false
		for connection_line: String in ready_connections:
			lines.append(connection_line)

	for key: String in trigger_order:
		var events: Array = grouped.get(key, [])
		if events.is_empty():
			continue
		var signature: Dictionary = signatures.get(key, {})
		var function_name: String = str(signature.get("function_name", ""))
		if function_name.is_empty():
			(result["warnings"] as Array[String]).append("Unsupported trigger %s" % key)
			continue
		var args: String = str(signature.get("args", ""))
		lines.append("")
		if args.is_empty():
			lines.append("func %s() -> void:" % function_name)
		else:
			lines.append("func %s(%s) -> void:" % [function_name, args])
		var had_body: bool = false
		if function_name == "_ready" and _live_values_receiver_pending:
			# Edit-back channel: the Live Values window's edits arrive as
			# "eventsheets:set_value" messages (debug sessions only; one receiver per
			# game — the first streaming sheet wins, noted in the window).
			lines.append("\tif EngineDebugger.is_active() and not EngineDebugger.has_capture(\"eventsheets\"):")
			lines.append("\t\tEngineDebugger.register_message_capture(&\"eventsheets\", _eventsheets_debug_set)")
			had_body = true
			_live_values_receiver_pending = false
		if function_name == "_process" and not _live_values_payload.is_empty():
			# Live-values stream: throttled, debug-session-only, before user logic.
			lines.append("\t__live_values_timer += delta")
			lines.append("\tif __live_values_timer >= 0.25 and EngineDebugger.is_active():")
			lines.append("\t\t__live_values_timer = 0.0")
			lines.append("\t\tEngineDebugger.send_message(\"eventsheets:live_values\", [%s])" % _live_values_payload)
			had_body = true
			_live_values_payload = ""
		if function_name == "_ready" and not ready_connections.is_empty():
			# Signal connections run before the user's OnReady logic.
			for connection_line: String in ready_connections:
				lines.append(connection_line)
			had_body = true
		had_body = _emit_event_body(events, lines, source_map, 1, result["warnings"]) or had_body
		if not had_body:
			lines.append("\tpass")

## Emits the condition/action body for a list of event rows, appending to lines.
## Shared by trigger handlers, sheet functions, and (recursively) sub-events.
##
## Semantics, mirroring Construct 3:
## - Each event's conditions emit one `if` at `depth`; its actions and sub-events nest one
##   level deeper. Sub-events therefore run only when the parent's conditions held.
## - An ELSE/ELIF sibling chains onto the previous sibling's `if` (`else:` / `elif c:`).
##   ELSE with conditions is the same thing as ELIF. A chain row without a preceding `if`
##   degrades to a plain event and a warning is recorded.
## - Comments compile to `#` comment lines; GDScript blocks emit with adaptive indentation
##   (pre-indented imported code keeps its own tabs; flat user code is indented for them);
##   variables dropped into an event's flow become function-local `var` declarations.
##
## When source_map is provided, records {uid, start, end, kind} (1-based inclusive lines)
## per emitted row so the editor can highlight a row's generated code.
static func _emit_event_body(
	events: Array,
	lines: PackedStringArray,
	source_map: Array = [],
	depth: int = 1,
	warnings: Array = []
) -> bool:
	var had_body: bool = false
	var indent: String = "\t".repeat(depth)
	# True while the previous sibling ended an if/elif block at this depth, meaning an
	# ELSE/ELIF sibling may legally chain onto it.
	var chain_open: bool = false
	for event_item: Variant in events:
		if event_item is RawCodeRow:
			var raw_row: RawCodeRow = event_item as RawCodeRow
			if raw_row.enabled and not raw_row.code.is_empty():
				var raw_start: int = lines.size() + 1
				for code_line: String in _indent_raw_lines(raw_row.code, depth):
					lines.append(code_line)
					had_body = true
				source_map.append({"uid": str(raw_row.get_instance_id()), "start": raw_start, "end": lines.size(), "kind": "raw"})
			chain_open = false
			continue
		if event_item is CommentRow:
			var comment_row: CommentRow = event_item as CommentRow
			if comment_row.enabled and not comment_row.text.strip_edges().is_empty():
				var comment_start: int = lines.size() + 1
				for comment_line: String in comment_row.text.split("\n"):
					lines.append("%s# %s" % [indent, comment_line])
					had_body = true
				source_map.append({"uid": str(comment_row.get_instance_id()), "start": comment_start, "end": lines.size(), "kind": "comment"})
			# Comments are transparent to else-chaining (annotating a chain shouldn't break it).
			continue
		if event_item is LocalVariable:
			# A variable inside an event's flow is a function-local declaration. @export is
			# meaningless locally and const is not allowed in function scope, so both emit
			# as plain locals (with a warning so the author knows).
			var local_variable: LocalVariable = event_item as LocalVariable
			if not local_variable.name.strip_edges().is_empty():
				if local_variable.exported or local_variable.is_constant:
					warnings.append("Variable '%s' inside an event compiles as a plain local var." % local_variable.name)
				lines.append("%svar %s: %s = %s" % [indent, local_variable.name, local_variable.type_name, _to_code_literal(local_variable.default_value)])
				source_map.append({"uid": str(local_variable.get_instance_id()), "start": lines.size(), "end": lines.size(), "kind": "variable"})
				had_body = true
			chain_open = false
			continue
		if not (event_item is EventRow):
			continue
		var event_row: EventRow = event_item as EventRow
		if not event_row.enabled:
			continue
		var event_start_line: int = lines.size() + 1
		var condition_texts: PackedStringArray = PackedStringArray()
		var runtime_group_guard: String = str(_runtime_group_guards.get(event_row, ""))
		for condition: ACECondition in event_row.conditions:
			var condition_line: String = ConditionCodegen.generate_condition(condition)
			if not condition_line.is_empty():
				condition_texts.append(condition_line)
		var joiner: String = " or " if event_row.condition_mode == EventRow.ConditionMode.OR else " and "
		var joined_conditions: String = joiner.join(condition_texts)
		# Runtime-group guards AND-wrap the whole condition — joining a guard into an
		# OR list would silently disable the gate (`guard or a or b`).
		if not runtime_group_guard.is_empty():
			if condition_texts.is_empty():
				joined_conditions = runtime_group_guard
			elif event_row.condition_mode == EventRow.ConditionMode.OR and condition_texts.size() > 1:
				joined_conditions = "%s and (%s)" % [runtime_group_guard, joined_conditions]
			else:
				joined_conditions = "%s and %s" % [runtime_group_guard, joined_conditions]
			condition_texts.append(runtime_group_guard)

		# Stateful conditions: prelude lines run every tick BEFORE the if (so they must
		# not sit between an if and its elif — stateful events never chain).
		var stateful_preludes: PackedStringArray = PackedStringArray()
		var stateful_on_true: PackedStringArray = PackedStringArray()
		for condition: ACECondition in event_row.conditions:
			if not condition.enabled:
				continue
			if not condition.codegen_prelude.is_empty():
				stateful_preludes.append(_substitute_params(condition.codegen_prelude, condition.params))
			if not condition.codegen_on_true.is_empty():
				stateful_on_true.append(_substitute_params(condition.codegen_on_true, condition.params))
		for prelude_line: String in stateful_preludes:
			lines.append(indent + prelude_line)
			had_body = true
		# Resolve the block header: if / elif / else, per the chaining rules above.
		var wants_chain: bool = event_row.else_mode != EventRow.ElseMode.NONE
		if wants_chain and not stateful_preludes.is_empty():
			warnings.append("Stateful conditions (Every X Seconds…) can't chain as Else/Else-If; emitted standalone.")
			wants_chain = false
		if not stateful_on_true.is_empty() and event_row.condition_mode == EventRow.ConditionMode.OR and event_row.conditions.size() > 1:
			warnings.append("Stateful conditions in OR events rebase whenever ANY condition passes — consider a dedicated event.")
		if wants_chain and not chain_open:
			warnings.append("Else/Else-If event has no preceding conditioned event to chain onto; emitted standalone.")
			wants_chain = false
		var emitted_block: bool = false
		if wants_chain:
			if condition_texts.size() > 0:
				lines.append("%selif %s:" % [indent, joined_conditions])
			else:
				lines.append("%selse:" % indent)
			emitted_block = true
			had_body = true
		elif condition_texts.size() > 0:
			lines.append("%sif %s:" % [indent, joined_conditions])
			emitted_block = true
			had_body = true

		var body_depth: int = depth + (1 if emitted_block else 0)
		if emitted_block:
			for on_true_line: String in stateful_on_true:
				lines.append("\t".repeat(body_depth) + on_true_line)
		# Pick filters (C3 "for each" picking, the Godot way): each enabled filter wraps the
		# event's body in a direct `for` loop — group members, children, or any GDScript
		# iterable — with an optional predicate and first-N cap. Conditions gate the whole
		# loop; multiple filters nest in order. Plain loops keep the parity contract.
		var pick_start_size: int = lines.size()
		body_depth = _emit_pick_filters(event_row, lines, body_depth, warnings)
		var emitted_pick_loop: bool = lines.size() > pick_start_size
		had_body = had_body or emitted_pick_loop
		var body_indent: String = "\t".repeat(body_depth)
		if _emit_breakpoints_flag and event_row.debug_break:
			lines.append(body_indent + "breakpoint")
			had_body = true
		var body_start_size: int = lines.size()

		for action_item: Variant in event_row.actions:
			if action_item is ACEAction:
				var action_line: String = ActionCodegen.generate_action(action_item)
				if action_line.is_empty():
					continue
				if action_item.is_awaited or action_item.await_call:
					action_line = "await %s" % action_line
				# Multi-statement templates (Spawn Scene At…) emit one line each.
				for action_template_line: String in action_line.split("\n"):
					lines.append(body_indent + action_template_line)
				had_body = true
			elif action_item is RawCodeRow:
				# In-flow GDScript block (C3 inline scripting): emitted verbatim inside the
				# event body at the body indent (inner indentation preserved beneath it).
				var inline_raw: RawCodeRow = action_item as RawCodeRow
				if not inline_raw.enabled or inline_raw.code.strip_edges().is_empty():
					continue
				var inline_start: int = lines.size() + 1
				for inline_line: String in inline_raw.code.split("\n"):
					lines.append(body_indent + inline_line)
				had_body = true
				source_map.append({"uid": str(inline_raw.get_instance_id()), "start": inline_start, "end": lines.size(), "kind": "raw"})
			elif action_item is MatchRow:
				# A GDScript `match` as a structured action row (C3's switch): subject +
				# verbatim branch lines, one level deeper.
				var match_row: MatchRow = action_item as MatchRow
				if not match_row.enabled or match_row.match_expression.strip_edges().is_empty():
					continue
				var match_start: int = lines.size() + 1
				lines.append(body_indent + "match %s:" % match_row.match_expression.strip_edges())
				for branch_line: String in match_row.branches_text.split("\n"):
					lines.append(body_indent + "\t" + branch_line)
				had_body = true
				source_map.append({"uid": str(match_row.get_instance_id()), "start": match_start, "end": lines.size(), "kind": "match"})
			elif action_item is CommentRow:
				# Action-cell comment: annotates the flow, compiles to comment lines.
				var action_comment: CommentRow = action_item as CommentRow
				if action_comment.enabled and not action_comment.text.strip_edges().is_empty():
					var action_comment_start: int = lines.size() + 1
					for comment_line: String in action_comment.text.split("\n"):
						lines.append("%s# %s" % [body_indent, comment_line])
					had_body = true
					source_map.append({"uid": str(action_comment.get_instance_id()), "start": action_comment_start, "end": lines.size(), "kind": "comment"})
			elif action_item is Resource and action_item.has_method("get_row_kind"):
				lines.append(body_indent + "# (unknown row type — preserved as a comment so nothing is silently dropped)")
				had_body = true

		# Sub-events run inside the parent's block (under its conditions).
		if not event_row.sub_events.is_empty():
			had_body = _emit_event_body(event_row.sub_events, lines, source_map, body_depth, warnings) or had_body

		# An if/elif/else block (or pick loop) whose body emitted nothing needs `pass` to
		# stay valid GDScript (e.g. a condition-only event, or one whose actions all
		# compiled to nothing).
		if (emitted_block or emitted_pick_loop) and lines.size() == body_start_size:
			lines.append(body_indent + "pass")
			had_body = true
		if lines.size() >= event_start_line:
			source_map.append({"uid": str(event_row.get_instance_id()), "start": event_start_line, "end": lines.size(), "kind": "event"})
		chain_open = emitted_block
	return had_body

## Emits the `for` loop headers for an event's pick filters and returns the new body depth.
## Supported per filter: collection (GROUP → get_nodes_in_group, CHILDREN → get_children,
## EXPRESSION/ARRAY → verbatim GDScript iterable), predicate_expression (iterator-scoped
## GDScript), pick_first_n. order_by is not compiled yet (warning); filter_conditions use
## host-context templates and are likewise warned — write the predicate instead.
static func _emit_pick_filters(event_row: EventRow, lines: PackedStringArray, body_depth: int, warnings: Array) -> int:
	var loop_index: int = 0
	for filter_entry: Variant in event_row.pick_filters:
		if not (filter_entry is PickFilter) or not (filter_entry as PickFilter).enabled:
			continue
		var pick: PickFilter = filter_entry as PickFilter
		var collection: String = _pick_collection_expression(pick)
		if collection.is_empty():
			warnings.append("Pick filter skipped: no collection for kind %d (set collection_value)." % pick.collection_kind)
			continue
		var iterator: String = pick.iterator_name.strip_edges()
		if iterator.is_empty():
			iterator = "item"
		var indent: String = "\t".repeat(body_depth)
		var counter_name: String = "__pick_count_%d" % loop_index
		if pick.pick_first_n > 0:
			lines.append("%svar %s: int = 0" % [indent, counter_name])
		if pick.collection_kind == PickFilter.CollectionKind.WHILE:
			# While loops reuse the picking pipeline (predicate/first-N still apply).
			lines.append("%swhile %s:" % [indent, collection])
		else:
			# Ordered picking (C3 pick nearest/furthest): sort a copy by the order
			# expression (written in terms of the iterator) before looping.
			if not pick.order_by_expression.strip_edges().is_empty():
				var sorted_name: String = "__pick_sorted_%d" % loop_index
				var iterator_regex: RegEx = RegEx.new()
				iterator_regex.compile("\\b%s\\b" % iterator)
				var key_a: String = iterator_regex.sub(pick.order_by_expression.strip_edges(), "__pick_a", true)
				var key_b: String = iterator_regex.sub(pick.order_by_expression.strip_edges(), "__pick_b", true)
				lines.append("%svar %s: Array = Array(%s)" % [indent, sorted_name, collection])
				lines.append("%s%s.sort_custom(func(__pick_a, __pick_b): return (%s) %s (%s))" % [indent, sorted_name, key_a, ">" if pick.order_descending else "<", key_b])
				collection = sorted_name
			lines.append("%sfor %s in %s:" % [indent, iterator, collection])
		body_depth += 1
		indent = "\t".repeat(body_depth)
		var predicate: String = pick.predicate_expression.strip_edges()
		if not predicate.is_empty():
			lines.append("%sif not (%s):" % [indent, predicate])
			lines.append("%s\tcontinue" % indent)
		var filter_guard: String = _compile_filter_conditions(pick, iterator)
		if not filter_guard.is_empty():
			lines.append("%sif not (%s):" % [indent, filter_guard])
			lines.append("%s\tcontinue" % indent)
		if pick.pick_first_n > 0:
			lines.append("%s%s += 1" % [indent, counter_name])
			lines.append("%sif %s > %d:" % [indent, counter_name, pick.pick_first_n])
			lines.append("%s\tbreak" % indent)
		loop_index += 1
	return body_depth

## Compiles a pick filter's structured conditions into one iterator-scoped boolean guard.
## Node-typed conditions are called on the picked instance ({iterator}.<expr>); global
## templates (Input.*, variable compares) stay as-is. AND (filter_mode 0) or OR (1).
static func _compile_filter_conditions(pick: PickFilter, iterator: String) -> String:
	var parts: PackedStringArray = PackedStringArray()
	for entry: Variant in pick.filter_conditions:
		if not (entry is ACECondition) or not (entry as ACECondition).enabled:
			continue
		var cond: ACECondition = entry as ACECondition
		var base: String = _condition_base_expr(cond)
		if base.strip_edges().is_empty():
			continue
		if _condition_is_node_scoped(cond):
			base = "%s.%s" % [iterator, base]
		var part: String = "not (%s)" % base if cond.negated else base
		parts.append("(%s)" % part)
	if parts.is_empty():
		return ""
	var joiner: String = " or " if pick.filter_mode == 1 else " and "
	return joiner.join(parts)

## The condition's boolean template with params applied, WITHOUT negation (so a node scope
## can be inserted before the `not`). Mirrors ConditionCodegen.generate_condition lookup.
static func _condition_base_expr(condition: ACECondition) -> String:
	var template: String = condition.codegen_template.strip_edges()
	if template.is_empty():
		var descriptor: ACEDescriptor = ACERegistry.find_descriptor(condition.provider_id, condition.ace_id)
		if descriptor == null:
			return ""
		template = descriptor.codegen_template
	var params: Dictionary = condition.params if not condition.params.is_empty() else condition.parameters
	return ActionCodegen._apply_template(template, params)

## True when a condition targets the implicit node (node_type set), so in a pick loop it
## must be scoped to the picked instance.
static func _condition_is_node_scoped(condition: ACECondition) -> bool:
	var descriptor: ACEDescriptor = ACERegistry.find_descriptor(condition.provider_id, condition.ace_id)
	return descriptor != null and not descriptor.node_type.strip_edges().is_empty()

## The GDScript iterable a pick filter loops over ("" = unsupported configuration).
static func _pick_collection_expression(pick: PickFilter) -> String:
	var value: String = pick.collection_value.strip_edges()
	if value.is_empty():
		value = pick.source_expression.strip_edges()
	match pick.collection_kind:
		PickFilter.CollectionKind.REPEAT:
			return "range(%s)" % value
		PickFilter.CollectionKind.WHILE:
			return value
		PickFilter.CollectionKind.GROUP:
			return "get_tree().get_nodes_in_group(\"%s\")" % value if not value.is_empty() else ""
		PickFilter.CollectionKind.CHILDREN:
			return "get_children()"
		PickFilter.CollectionKind.EXPRESSION, PickFilter.CollectionKind.ARRAY:
			return value
		_:
			# NODE_PATH_ARRAY / NODE_TREE / CUSTOM: honor an explicit expression, else skip.
			return value

## Indents a sibling GDScript block's lines for `depth`. Imported code already carries its
## own leading tab (function bodies arrive pre-indented for depth 1), while code written in
## the block editor is flat — detect which and prepend accordingly so both emit correctly.
static func _indent_raw_lines(code: String, depth: int) -> PackedStringArray:
	var raw_lines: PackedStringArray = code.split("\n")
	var self_indented: bool = false
	for raw_line: String in raw_lines:
		if not raw_line.strip_edges().is_empty():
			self_indented = raw_line.begins_with("\t")
			break
	var prefix: String = "\t".repeat(depth - 1 if self_indented else depth)
	var output: PackedStringArray = PackedStringArray()
	for raw_line: String in raw_lines:
		output.append(prefix + raw_line if not raw_line.strip_edges().is_empty() else raw_line)
	return output

## Emits the `@ace_*` annotation block above an exposed sheet function. The annotations are
## parsed back by EventSheetSemanticAnalyzer when the compiled script is registered as a
## provider (drop it into res://eventsheet_addons/), publishing the function as an ACE in
## every sheet — the sheet → script → addon loop behaviors and custom nodes build on.
static func _emit_expose_annotations(event_function: EventFunction, sheet: EventSheetResource, lines: PackedStringArray) -> void:
	if not event_function.expose_as_ace:
		# Reflection publishes any public method of a provider script, so unexposed sheet
		# functions are explicitly hidden — expose_as_ace is the single publication switch.
		lines.append("## @ace_hidden")
		return
	lines.append("## @ace_action")
	var display_name: String = event_function.ace_display_name.strip_edges()
	if not display_name.is_empty():
		lines.append("## @ace_name(\"%s\")" % display_name)
	var category: String = event_function.ace_category.strip_edges()
	if not category.is_empty():
		lines.append("## @ace_category(\"%s\")" % category)
	if not event_function.description.strip_edges().is_empty():
		lines.append("## @ace_description(\"%s\")" % event_function.description.strip_edges())
	# The sheet's icon flows to the published ACE (one icon, set once, shown everywhere).
	if not sheet.custom_class_icon.strip_edges().is_empty():
		lines.append("## @ace_icon(\"%s\")" % sheet.custom_class_icon.strip_edges())
	# Default codegen template so consumer sheets compile a direct call: behaviors are
	# child nodes (default node name = class name) → `$Class.fn({args})`; custom-node /
	# plain sheets expose self methods → `fn({args})`. Authors can refine via re-annotation.
	var argument_tokens: PackedStringArray = PackedStringArray()
	for param in event_function.params:
		if param is ACEParam and not (param as ACEParam).id.strip_edges().is_empty():
			argument_tokens.append("{%s}" % (param as ACEParam).id)
	var call_prefix: String = ""
	if sheet.behavior_mode and not sheet.custom_class_name.strip_edges().is_empty():
		call_prefix = "$%s." % sheet.custom_class_name.strip_edges()
	elif sheet.autoload_mode and not sheet.autoload_name.strip_edges().is_empty():
		# Singletons are addressed by their autoload name — works from every scene,
		# no node paths (the whole point of an autoload).
		call_prefix = "%s." % sheet.autoload_name.strip_edges()
	lines.append("## @ace_codegen_template(\"%s%s(%s)\")" % [call_prefix, event_function.function_name, ", ".join(argument_tokens)])

## Builds the typed parameter list for a sheet function (e.g. "amount: int, label: String").
## "-> void" unless the function declares a Variant.Type return (TYPE_NIL = void).
static func _function_return_type_name(event_function: EventFunction) -> String:
	if event_function.return_type == TYPE_NIL:
		return "void"
	# TYPE_MAX is the "returns Variant" sentinel (there is no Variant.Type for Variant).
	if event_function.return_type == TYPE_MAX:
		return "Variant"
	return type_string(event_function.return_type)

static func _emit_function_params(event_function: EventFunction) -> String:
	var parts: PackedStringArray = PackedStringArray()
	if not event_function.params.is_empty():
		for param: ACEParam in event_function.params:
			if param == null:
				continue
			var param_id: String = param.id if not param.id.is_empty() else param.name
			if param_id.is_empty():
				continue
			var type_name: String = param.type_name
			if type_name.is_empty() or type_name == "Variant":
				parts.append(param_id)
			else:
				parts.append("%s: %s" % [param_id, type_name])
	else:
		for param_name: Variant in event_function.parameters:
			var clean_name: String = str(param_name).strip_edges()
			if not clean_name.is_empty():
				parts.append(clean_name)
	return ", ".join(parts)

## Emits `@export var` lines from the sheet variables dictionary.
static func _emit_variables(variables: Dictionary, warnings: Array = [], function_names: Dictionary = {}) -> PackedStringArray:
	var lines: PackedStringArray = PackedStringArray()
	var keys: Array = variables.keys()
	keys.sort()
	# Tier 2 conditions (Show If / Lock Unless) aggregate into ONE generated
	# _validate_property below, in variable order — canonical shape, dialog-edited.
	var property_conditions: Array = []

	for key: Variant in keys:
		var var_name: String = str(key)
		var descriptor: Variant = variables[key]
		if descriptor is Dictionary:
			var type_name: String = str(descriptor.get("type", "Variant"))
			var default_value: Variant = descriptor.get("default", "null")
			var exported: bool = bool(descriptor.get("exported", true))
			var combo_options: PackedStringArray = PackedStringArray(descriptor.get("options", []))
			# Inspector attributes (Tier 1 — see docs/INSPECTOR-ATTRIBUTES-SPEC.md):
			# canonical order is tooltip doc-comment, group, then the export line. The
			# doc comment is Godot's native Inspector tooltip.
			var attributes: Dictionary = descriptor.get("attributes") if descriptor.get("attributes") is Dictionary else {}
			if exported and not str(attributes.get("tooltip", "")).strip_edges().is_empty():
				lines.append("## %s" % str(attributes.get("tooltip")).strip_edges())
			if exported and not str(attributes.get("group", "")).strip_edges().is_empty():
				lines.append("@export_group(\"%s\")" % str(attributes.get("group")).strip_edges())
			if exported and type_name == "String" and not combo_options.is_empty():
				for unsupported_key: String in ["clamp", "on_changed", "read_only", "show_if", "lock_unless", "drawer"]:
					if attributes.has(unsupported_key):
						warnings.append("Variable \"%s\": combo variables don't support the %s attribute yet — ignored." % [var_name, unsupported_key])
				lines.append("%s var %s: String = %s" % [_export_enum_prefix(combo_options), var_name, _to_code_literal(default_value)])
				continue
			var export_prefix: String = "@export " if exported else ""
			if exported and attributes.get("range") is Dictionary and (type_name == "int" or type_name == "float"):
				var range_spec: Dictionary = attributes.get("range")
				export_prefix = "@export_range(%s, %s, %s) " % [str(range_spec.get("min", "0")), str(range_spec.get("max", "100")), str(range_spec.get("step", "1"))]
			elif exported and bool(attributes.get("multiline", false)) and type_name == "String":
				export_prefix = "@export_multiline "
			# Tier 3 drawers: the marker rides an @export_custom hint string; without the
			# editor plugin the property degrades to a plain field (parity preserved).
			if exported and str(attributes.get("drawer", "")) == "progress_bar" and (type_name == "int" or type_name == "float"):
				var drawer_range: Dictionary = attributes.get("range") if attributes.get("range") is Dictionary else {}
				export_prefix = "@export_custom(PROPERTY_HINT_NONE, \"eventsheet:progress_bar:%s:%s\") " % [str(drawer_range.get("min", "0")), str(drawer_range.get("max", "100"))]
			# Read-only wins over range/multiline/drawers (a locked field needs no slider).
			if exported and bool(attributes.get("read_only", false)):
				export_prefix = "@export_custom(PROPERTY_HINT_NONE, \"\", PROPERTY_USAGE_DEFAULT | PROPERTY_USAGE_READ_ONLY) "
			# Tier 2 setters: Clamp (needs Range + numeric) and/or On Changed (a sheet
			# function called after assignment). Canonical multi-line shape.
			var on_changed: String = str(attributes.get("on_changed", "")).strip_edges() if exported else ""
			var clamp_enabled: bool = exported and bool(attributes.get("clamp", false)) and attributes.get("range") is Dictionary and (type_name == "int" or type_name == "float")
			# Warn on typos even when the sheet has no functions at all (the empty-dict
			# guard used to silently skip exactly the case most likely to be a mistake).
			if not on_changed.is_empty() and not function_names.has(on_changed):
				warnings.append("Variable \"%s\": On Changed targets unknown function \"%s\" — check the spelling." % [var_name, on_changed])
			if not on_changed.is_empty() or clamp_enabled:
				lines.append("%svar %s: %s = %s:" % [export_prefix, var_name, type_name, _to_code_literal(default_value)])
				lines.append("\tset(value):")
				if clamp_enabled:
					var clamp_range: Dictionary = attributes.get("range")
					var clamp_call: String = "clampi" if type_name == "int" else "clampf"
					lines.append("\t\t%s = %s(value, %s, %s)" % [var_name, clamp_call, str(clamp_range.get("min", "0")), str(clamp_range.get("max", "100"))])
				else:
					lines.append("\t\t%s = value" % var_name)
				if not on_changed.is_empty():
					lines.append("\t\t%s()" % on_changed)
			else:
				lines.append("%svar %s: %s = %s" % [export_prefix, var_name, type_name, _to_code_literal(default_value)])
			for condition_key: String in ["show_if", "lock_unless"]:
				var condition_predicate: String = str(attributes.get(condition_key, "")).strip_edges()
				if exported and not condition_predicate.is_empty():
					if not variables.has(condition_predicate):
						warnings.append("Variable \"%s\": %s targets unknown variable \"%s\" — check the spelling." % [var_name, condition_key, condition_predicate])
					property_conditions.append({"name": var_name, "predicate": condition_predicate, "kind": condition_key})
		else:
			lines.append("@export var %s: Variant = %s" % [var_name, _to_code_literal(descriptor)])

	if not property_conditions.is_empty():
		lines.append("")
		lines.append("## Inspector conditions (Show If / Lock Unless) — generated; edit via the Variable dialog.")
		lines.append("func _validate_property(property: Dictionary) -> void:")
		for condition: Dictionary in property_conditions:
			lines.append("\tif str(property.name) == \"%s\" and not bool(%s):" % [str(condition.get("name")), str(condition.get("predicate"))])
			if str(condition.get("kind")) == "show_if":
				lines.append("\t\tproperty.usage &= ~PROPERTY_USAGE_EDITOR")
			else:
				lines.append("\t\tproperty.usage |= PROPERTY_USAGE_READ_ONLY")

	return lines

## Recursively gathers tree-placed GDScript blocks from the top level and groups (sub-event
## raw blocks stay deferred until sub-events compile).
## Canonical single-line enum emission ("" when unnamed/empty/disabled). The importer's
## verify-lift depends on this exact form — change it only with a lifter update.
static func _emit_enum_line(enum_row: EnumRow) -> String:
	if enum_row == null or not enum_row.enabled or enum_row.enum_name.strip_edges().is_empty():
		return ""
	var members: PackedStringArray = PackedStringArray()
	for member: String in enum_row.members:
		if not member.strip_edges().is_empty():
			members.append(member.strip_edges())
	if members.is_empty():
		return ""
	return "enum %s { %s }" % [enum_row.enum_name.strip_edges(), ", ".join(members)]

## Canonical single-line signal emission ("" when unnamed/disabled). The importer's
## verify-lift depends on this exact form.
static func _emit_signal_line(signal_row: SignalRow) -> String:
	if signal_row == null or not signal_row.enabled or signal_row.signal_name.strip_edges().is_empty():
		return ""
	var params: PackedStringArray = PackedStringArray()
	for param: String in signal_row.params:
		if not param.strip_edges().is_empty():
			params.append(param.strip_edges())
	if params.is_empty():
		return "signal %s" % signal_row.signal_name.strip_edges()
	return "signal %s(%s)" % [signal_row.signal_name.strip_edges(), ", ".join(params)]

## Recursively gathers SignalRow rows (top level and inside groups).
static func _collect_signal_rows(entries: Array, into: Array) -> void:
	for entry: Variant in entries:
		if entry is SignalRow:
			into.append(entry)
		elif entry is EventGroup:
			var group: EventGroup = entry as EventGroup
			_collect_signal_rows(group.events if not group.events.is_empty() else group.rows, into)

## Recursively gathers EnumRow rows (top level and inside groups).
static func _collect_enum_rows(entries: Array, into: Array) -> void:
	for entry: Variant in entries:
		if entry is EnumRow:
			into.append(entry)
		elif entry is EventGroup:
			var group: EventGroup = entry as EventGroup
			_collect_enum_rows(group.events if not group.events.is_empty() else group.rows, into)

## Gathers stateful-condition member declarations (deduped) from the event tree.
## Gathers group-local variables: [{group: name, locals: [LocalVariable…]}] in order.
static func _collect_group_locals(entries: Array, into: Array) -> void:
	for entry: Variant in entries:
		if entry is EventGroup:
			var group: EventGroup = entry as EventGroup
			var locals: Array = []
			for local_entry: Variant in group.local_variables:
				if local_entry is LocalVariable:
					locals.append(local_entry)
			if not locals.is_empty():
				into.append({"group": group.group_name if not group.group_name.is_empty() else group.name, "locals": locals})
			_collect_group_locals(group.events if not group.events.is_empty() else group.rows, into)

## Early pass for the flag members of runtime-toggleable groups (nested included).
static func _collect_runtime_group_members(rows: Array) -> void:
	for row: Variant in rows:
		if row is EventGroup:
			var group: EventGroup = row as EventGroup
			if group.enabled and group.runtime_toggleable:
				var guard_token: String = group.group_name.to_snake_case() if not group.group_name.is_empty() else "group"
				var guard_name: String = "__group_%s_active" % guard_token
				var already_known: bool = false
				for member_pair: Array in _runtime_group_members:
					if str(member_pair[0]) == guard_name:
						already_known = true
				if not already_known:
					_runtime_group_members.append([guard_name, group.enabled])
			if group.enabled:
				_collect_runtime_group_members(group.events if not group.events.is_empty() else group.rows)

static func _collect_stateful_members(entries: Array, into: Array) -> void:
	for entry: Variant in entries:
		if entry is EventRow:
			for condition: Variant in (entry as EventRow).conditions:
				if condition is ACECondition and (condition as ACECondition).enabled and not (condition as ACECondition).member_declaration.is_empty():
					if not into.has((condition as ACECondition).member_declaration):
						into.append((condition as ACECondition).member_declaration)
			_collect_stateful_members((entry as EventRow).sub_events, into)
		elif entry is EventGroup:
			var group: EventGroup = entry as EventGroup
			_collect_stateful_members(group.events if not group.events.is_empty() else group.rows, into)

## Substitutes {param} tokens with the row's param values (plain str(), like codegen).
static func _substitute_params(template: String, params: Dictionary) -> String:
	var output: String = template
	for key: Variant in params.keys():
		output = output.replace("{%s}" % str(key), str(params[key]))
	return output

static func _collect_class_level_raw_rows(entries: Array, into: Array) -> void:
	for entry: Variant in entries:
		if entry is RawCodeRow:
			into.append(entry)
		elif entry is EventGroup:
			var group: EventGroup = entry as EventGroup
			_collect_class_level_raw_rows(group.events if not group.events.is_empty() else group.rows, into)

## Recursively gathers tree-placed LocalVariable rows from the event tree (top level, groups
## and sub-events) so they can be emitted as class-level declarations.
static func _collect_tree_variables(entries: Array, into: Array) -> void:
	for entry: Variant in entries:
		if entry is LocalVariable:
			into.append(entry)
		elif entry is EventGroup:
			var group: EventGroup = entry as EventGroup
			_collect_tree_variables(group.events if not group.events.is_empty() else group.rows, into)
		elif entry is EventRow:
			_collect_tree_variables((entry as EventRow).sub_events, into)

## Emits the class-level declaration for one tree-placed variable (const / @export var / var).
static func _emit_tree_variable_line(local_var: LocalVariable) -> String:
	if local_var == null or local_var.name.strip_edges().is_empty():
		return ""
	if local_var.is_constant:
		return "const %s: %s = %s" % [local_var.name, local_var.type_name, _to_code_literal(local_var.default_value)]
	# Combo (C3): exported String with options -> @export_enum dropdown in the Inspector.
	if local_var.exported and local_var.type_name == "String" and not local_var.options.is_empty():
		return "%s var %s: String = %s" % [_export_enum_prefix(local_var.options), local_var.name, _to_code_literal(local_var.default_value)]
	var export_prefix: String = "@export " if local_var.exported else ""
	return "%svar %s: %s = %s" % [export_prefix, local_var.name, local_var.type_name, _to_code_literal(local_var.default_value)]

## Canonical @export_enum prefix ("@export_enum(\"a\", \"b\")") — verify-lift relies on
## this exact form.
static func _export_enum_prefix(options: PackedStringArray) -> String:
	var quoted: PackedStringArray = PackedStringArray()
	for option: String in options:
		if not option.strip_edges().is_empty():
			quoted.append("\"%s\"" % option.strip_edges())
	return "@export_enum(%s)" % ", ".join(quoted)

## Converts a Variant to a deterministic code literal.
static func _to_code_literal(value: Variant) -> String:
	match typeof(value):
		TYPE_STRING:
			var text: String = str(value)
			if text.begins_with("\"") and text.ends_with("\""):
				return text
			return "\"%s\"" % text.replace("\\", "\\\\").replace("\"", "\\\"")
		TYPE_BOOL:
			return "true" if bool(value) else "false"
		TYPE_FLOAT:
			var float_text: String = str(float(value))
			var normalized_float_text: String = float_text.to_lower()
			if float_text.find(".") == -1 and normalized_float_text.find("e") == -1:
				float_text += ".0"
			return float_text
		TYPE_NIL:
			return "null"
		TYPE_ARRAY:
			# Canonical container literals (recursive, deterministic, str_to_var-parseable):
			# verify-lift depends on this exact spacing — change only with a lifter update.
			var parts: PackedStringArray = PackedStringArray()
			for item: Variant in (value as Array):
				parts.append(_to_code_literal(item))
			return "[%s]" % ", ".join(parts)
		TYPE_DICTIONARY:
			var entries: PackedStringArray = PackedStringArray()
			var dictionary_value: Dictionary = value as Dictionary
			for key: Variant in dictionary_value.keys():
				entries.append("%s: %s" % [_to_code_literal(key), _to_code_literal(dictionary_value[key])])
			return "{%s}" % ", ".join(entries)
		_:
			return str(value)

## Resolves output path from explicit input or sheet resource path. With no explicit
## path the sheet's EXISTING pair wins: the conventional <name>_generated.gd when
## present, else a sibling <name>.gd — but only when its header proves the compiler
## wrote it for THIS sheet (the pack builder's take_over_path convention); a
## hand-written same-name script is never adopted as an output target. This keeps
## compile-on-save and the export-integrity pass refreshing the committed pair
## instead of inventing a parallel *_generated.gd next to it.
static func _resolve_output_path(sheet: EventSheetResource, output_path: String) -> String:
	if not output_path.is_empty():
		return output_path
	if not sheet.resource_path.is_empty():
		# get_basename() (full path minus extension) — building from get_base_dir()
		# yields user:///… triple slashes for root-level paths.
		var base: String = sheet.resource_path.get_basename()
		var generated: String = base + "_generated.gd"
		if FileAccess.file_exists(generated):
			return generated
		var sibling: String = base + ".gd"
		if FileAccess.file_exists(sibling) and FileAccess.get_file_as_string(sibling).left(400).contains("# Source: %s" % sheet.resource_path):
			return sibling
		return generated
	return "res://event_sheet_generated.gd"
