# EventForge — Event sheet compiler
# Compiles EventSheetResource assets into deterministic GDScript output.
@tool
extends RefCounted
class_name SheetCompiler

const VERSION: String = "0.1.0"

## Compiles an event sheet resource to a GDScript output file.
static func compile(sheet: EventSheetResource, output_path: String = "") -> Dictionary:
	var result: Dictionary = {
		"success": true,
		"errors": [] as Array[String],
		"warnings": [] as Array[String],
		"output": ""
	}

	if sheet == null:
		result["success"] = false
		(result["errors"] as Array[String]).append("Sheet is null")
		return result

	var lines: PackedStringArray = PackedStringArray()
	lines.append("# AUTO-GENERATED by EventForge v%s" % VERSION)
	lines.append("# Source: %s" % sheet.resource_path)
	lines.append("# DO NOT EDIT — this file is regenerated on every compile.")
	lines.append("")
	lines.append("extends %s" % sheet.host_class)

	var variable_lines: PackedStringArray = _emit_variables(sheet.variables)
	if variable_lines.size() > 0:
		lines.append("")
		for line: String in variable_lines:
			lines.append(line)

	var grouped: Dictionary = {}
	var trigger_order: PackedStringArray = PackedStringArray()
	var deferred_rows: PackedStringArray = PackedStringArray()

	for row: Variant in sheet.events:
		if not (row is Resource):
			continue
		if row.has_method("get_row_kind") and str(row.call("get_row_kind")) != "event":
			deferred_rows.append("# TODO: row type not yet implemented in Phase 1")
			continue
		if not (row is EventRow):
			continue

		var event_row: EventRow = row
		if not event_row.enabled:
			continue

		var key: String = TriggerResolver.get_trigger_key(event_row)
		if not grouped.has(key):
			grouped[key] = []
			trigger_order.append(key)
		(grouped[key] as Array).append(event_row)

	var function_order: PackedStringArray = PackedStringArray()
	var function_bodies: Dictionary = {}
	var ready_setup_lines: PackedStringArray = PackedStringArray()

	for key: String in trigger_order:
		var events: Array = grouped.get(key, [])
		if events.is_empty():
			continue

		var signature: Dictionary = TriggerResolver.resolve_trigger(events[0])
		var function_name: String = str(signature.get("function_name", ""))
		if function_name.is_empty():
			(result["warnings"] as Array[String]).append("Unsupported trigger %s" % key)
			continue

		var args: String = str(signature.get("args", ""))
		if bool(signature.get("connect_in_ready", false)):
			var connection_line: String = str(signature.get("connection_line", ""))
			if not connection_line.is_empty():
				var ready_line: String = "	" + connection_line
				if not ready_setup_lines.has(ready_line):
					ready_setup_lines.append(ready_line)

		_append_function_body(
			function_bodies,
			function_order,
			function_name,
			args,
			_build_event_body_lines(events)
		)

	if ready_setup_lines.size() > 0:
		if not function_bodies.has("_ready"):
			function_bodies["_ready"] = {"args": "", "lines": PackedStringArray()}
			function_order.insert(0, "_ready")
		var ready_function: Dictionary = function_bodies["_ready"]
		var ready_lines: PackedStringArray = PackedStringArray()
		for ready_setup_line: String in ready_setup_lines:
			ready_lines.append(ready_setup_line)
		for existing_line: String in ready_function.get("lines", PackedStringArray()):
			ready_lines.append(existing_line)
		ready_function["lines"] = ready_lines
		function_bodies["_ready"] = ready_function

	for function_name: String in function_order:
		var function_data: Dictionary = function_bodies.get(function_name, {})
		var args: String = str(function_data.get("args", ""))
		var body_lines: PackedStringArray = function_data.get("lines", PackedStringArray())
		lines.append("")
		if args.is_empty():
			lines.append("func %s() -> void:" % function_name)
		else:
			lines.append("func %s(%s) -> void:" % [function_name, args])

		if body_lines.is_empty():
			lines.append("	pass")
			continue
		for body_line: String in body_lines:
			lines.append(body_line)

	for deferred: String in deferred_rows:
		lines.append("")
		lines.append(deferred)

	var output: String = "\n".join(lines) + "\n"
	result["output"] = output

	var final_output_path: String = _resolve_output_path(sheet, output_path)
	var file: FileAccess = FileAccess.open(final_output_path, FileAccess.WRITE)
	if file == null:
		result["success"] = false
		(result["errors"] as Array[String]).append("Failed to open output path: %s" % final_output_path)
		return result

	file.store_string(output)
	file.flush()
	file.close()
	return result

static func _append_function_body(function_bodies: Dictionary, function_order: PackedStringArray, function_name: String, args: String, body_lines: PackedStringArray) -> void:
	if not function_bodies.has(function_name):
		function_bodies[function_name] = {
			"args": args,
			"lines": PackedStringArray()
		}
		function_order.append(function_name)
	var function_data: Dictionary = function_bodies[function_name]
	var lines: PackedStringArray = function_data.get("lines", PackedStringArray())
	for body_line: String in body_lines:
		lines.append(body_line)
	function_data["lines"] = lines
	function_bodies[function_name] = function_data

static func _build_event_body_lines(events: Array) -> PackedStringArray:
	var lines: PackedStringArray = PackedStringArray()
	for event_row: EventRow in events:
		for row_line: String in _build_single_event_body(event_row, "	"):
			lines.append(row_line)
	return lines

static func _build_single_event_body(event_row: EventRow, base_indent: String) -> PackedStringArray:
	var lines: PackedStringArray = PackedStringArray()
	var condition_texts: PackedStringArray = PackedStringArray()
	for condition: ACECondition in event_row.conditions:
		var condition_line: String = ConditionCodegen.generate_condition(condition)
		if not condition_line.is_empty():
			condition_texts.append(condition_line)

	var body_indent: String = base_indent
	if condition_texts.size() > 0:
		lines.append("%sif %s:" % [base_indent, " and ".join(condition_texts)])
		body_indent = base_indent + "	"

	for action_item: Variant in event_row.actions:
		if action_item is ACEAction:
			var action_line: String = ActionCodegen.generate_action(action_item)
			if action_line.is_empty():
				continue
			if action_item.is_awaited or action_item.await_call:
				action_line = "await %s" % action_line
			lines.append(body_indent + action_line)
		elif action_item is Resource and action_item.has_method("get_row_kind"):
			lines.append(body_indent + "# TODO: row type not yet implemented in Phase 1")

	if event_row.else_mode != EventRow.ElseMode.NONE or event_row.sub_events.size() > 0 or event_row.pick_filters.size() > 0:
		lines.append(body_indent + "# TODO: row type not yet implemented in Phase 1")

	if condition_texts.size() > 0 and lines.size() == 1:
		lines.append(body_indent + "pass")

	return lines

## Emits `@export var` lines from the sheet variables dictionary.
static func _emit_variables(variables: Dictionary) -> PackedStringArray:
	var lines: PackedStringArray = PackedStringArray()
	var keys: Array = variables.keys()
	keys.sort()

	for key: Variant in keys:
		var var_name: String = str(key)
		var descriptor: Variant = variables[key]
		if descriptor is Dictionary:
			var type_name: String = str(descriptor.get("type", "Variant"))
			var default_value: Variant = descriptor.get("default", "null")
			var exported: bool = bool(descriptor.get("exported", true))
			var export_prefix: String = "@export " if exported else ""
			lines.append("%svar %s: %s = %s" % [export_prefix, var_name, type_name, _to_code_literal(default_value)])
		else:
			lines.append("@export var %s: Variant = %s" % [var_name, _to_code_literal(descriptor)])

	return lines

## Converts a Variant to a deterministic code literal.
static func _to_code_literal(value: Variant) -> String:
	match typeof(value):
		TYPE_STRING:
			var text: String = str(value)
			if text.begins_with("\"") and text.ends_with("\""):
				return text
			return "\"%s\"" % text.replace("\\", "\\\\").replace("\"", "\\\"")
		TYPE_BOOL:
			return "true" if bool(value) else "false"
		TYPE_NIL:
			return "null"
		_:
			return str(value)

## Resolves output path from explicit input or sheet resource path.
static func _resolve_output_path(sheet: EventSheetResource, output_path: String) -> String:
	if not output_path.is_empty():
		return output_path
	if not sheet.resource_path.is_empty():
		var base_name: String = sheet.resource_path.get_file().get_basename()
		return "%s/%s_generated.gd" % [sheet.resource_path.get_base_dir(), base_name]
	return "res://event_sheet_generated.gd"
