# AUTO-GENERATED by EventForge v0.1.0
# Source: res://eventsheet_addons/tile_movement/tile_movement_behavior.tres
# DO NOT EDIT — this file is regenerated on every compile.

class_name TileMovementBehavior
extends Node

## The node this behavior acts on (its parent). Required host: Node2D.
var host: Node2D = null

func _enter_tree() -> void:
	host = get_parent() as Node2D
	if host == null:
		push_warning("TileMovementBehavior behavior requires a Node2D parent.")

var from_x: float = 0.0
var from_y: float = 0.0
@export var move_time: float = 0.15
var moving: bool = false
var progress: float = 0.0
@export var tile_size: float = 64.0
var to_x: float = 0.0
var to_y: float = 0.0

## @ace_trigger
## @ace_name("On Step Finished")
## @ace_category("Tile Movement")
signal step_finished

func _process(delta: float) -> void:
	if host == null:
		return
	if moving:
		progress += delta / move_time
		if progress >= 1.0:
			host.position = Vector2(to_x, to_y)
			moving = false
			step_finished.emit()
		else:
			host.position = Vector2(from_x, from_y).lerp(Vector2(to_x, to_y), progress)
		return
	var step := Vector2(Input.get_axis(&"ui_left", &"ui_right"), Input.get_axis(&"ui_up", &"ui_down"))
	if step.x != 0.0:
		step.y = 0.0
	if step != Vector2.ZERO:
		from_x = host.position.x
		from_y = host.position.y
		to_x = from_x + signf(step.x) * tile_size
		to_y = from_y + signf(step.y) * tile_size
		progress = 0.0
		moving = true

## @ace_action
## @ace_name("Teleport To Tile")
## @ace_category("Tile Movement")
## @ace_description("Snaps to a tile coordinate instantly.")
## @ace_codegen_template("$TileMovementBehavior.teleport_to_tile({tile_x}, {tile_y})")
func teleport_to_tile(tile_x: float, tile_y: float) -> void:
	if host != null:
		host.position = Vector2(tile_x, tile_y) * tile_size
	moving = false

# Tile Movement behavior (C3-style): grid-locked stepping with the arrow keys; fires On Step Finished per tile.
