# EventForge - the maintainability campaign's LEDGER, printed from git (dev tool, Windows).
#
# One number decided every estimate in this campaign and nobody could reproduce it. This tool is
# that number's definition, executable: run it and get the same figures on any machine with this
# repository checked out, at any pair of commits.
#
# THE DEFINITION, PINNED. Two figures are quoted whenever a step claims a shrink, and both are
# `git diff --numstat` over a pathspec - no wc, no editor, no counting of files by hand:
#
#   HAND-WRITTEN GDSCRIPT  '*.gd' minus the two generated trees that are compiler output
#                          (eventsheet_addons/ and demo/showcase/). This is the campaign's
#                          universe: every line a person wrote and a person maintains.
#   THE SHIPPED PLUGIN     the same filter narrowed to addons/, minus the generated doc bundle
#                          (addons/eventsheet/help/). This is what a user installs, and it is
#                          the figure a shrink must not grow.
#
# A dev tool under tools/ is hand-written and counts against the first figure in full - the campaign
# pays for its own instruments. It is not part of the second, because it does not ship.
#
# WHY BOTH A SIZE AND A DELTA. A delta alone cannot say whether -900 lines is a rout or a rounding
# error, and a size alone hides which direction a wave went. Every row carries the files and lines
# at HEAD, then the added, removed and net between BASE and HEAD. Sizes come from
# `git grep -c "^"`, which counts the lines of every tracked file matching the pathspec at a commit;
# deltas come from `--numstat` over the identical pathspec, so the two halves of a row always
# describe the same set of files.
#
# THE AREAS are the campaign's own map, and each is a pathspec rather than a list of files, so a
# file added tomorrow is measured the day it exists. Areas OVERLAP on purpose (the two mega-files
# are also part of the shipped plugin) - they are readings of the same tree, not a partition, and
# they are not meant to sum.
#
# A NOTE ON `*` IN A GIT PATHSPEC: without `:(glob)` magic it crosses directory separators, so
# `addons/eventforge/registration/*.gd` reaches the modules folder underneath. That is deliberate
# here and the reason no pattern needs a second, nested spelling.
#
# USAGE (from the repository root)
#   powershell -File tools/measure_ledger.ps1                       # the wave-2 base .. HEAD
#   powershell -File tools/measure_ledger.ps1 -Base v0.17.0
#   powershell -File tools/measure_ledger.ps1 -Base <sha> -Head <sha>
#   powershell -File tools/measure_ledger.ps1 -Csv                  # the same rows, comma separated
param(
	[string]$Base = "57588286e362ae7961f234f17572681d597c5249",
	[string]$Head = "HEAD",
	[switch]$Csv
)

# Bumped only when the ROW SHAPE or an area's pathspec changes, so two ledgers quoted side by side
# in the changelog can be checked for comparability rather than assumed to be comparable.
$FormatVersion = 1

# The exclusions that define "hand-written": the trees that are compiler output, regenerated by
# tools and drift-gated, so their lines are nobody's maintenance burden.
$Generated = @(':(exclude)eventsheet_addons/**', ':(exclude)demo/showcase/**')

$Areas = @(
	@{ Name = 'registration modules'; Spec = @('addons/eventforge/registration/*.gd') },
	@{ Name = 'pack builders';        Spec = @('tools/pack_builders/*.gd') },
	@{ Name = 'dialogs';              Spec = @('addons/eventsheet/editor/*dialog*.gd', 'addons/eventsheet/editor/popup_ui.gd') },
	@{ Name = 'doctors';              Spec = @('addons/eventforge/*_doctor.gd', 'addons/eventsheet/editor/*doctor*.gd') },
	@{ Name = 'lift matchers';        Spec = @('addons/eventforge/importer/*_lift.gd', 'addons/eventforge/importer/lift_*.gd') },
	@{ Name = 'tests';                Spec = @('tests/*.gd') },
	@{ Name = 'the two mega-files';   Spec = @('addons/eventsheet/editor/interaction/viewport_row_builder.gd', 'addons/eventsheet/editor/interaction/sentence_grammar.gd') },
	@{ Name = 'hand-written total';   Spec = @('*.gd') },
	@{ Name = 'shipped plugin';       Spec = @('addons/*.gd', ':(exclude)addons/eventsheet/help/**') }
)


# Files and lines matching $Spec at commit $Rev. `git grep -c "^"` prints one `rev:path:count` per
# file; a file with no lines at all prints nothing and correctly contributes nothing.
function Get-Size($Rev, $Spec) {
	$rows = & git grep -I -c "^" $Rev -- @Spec 2>$null
	$files = 0
	$lines = 0
	foreach ($row in $rows) {
		if ([string]::IsNullOrWhiteSpace($row)) { continue }
		$fields = $row.Split(':')
		$files += 1
		$lines += [int]$fields[$fields.Length - 1]
	}
	return @{ Files = $files; Lines = $lines }
}


# Added and removed lines between two commits over $Spec. `-` in a numstat column means a binary
# file, which a `*.gd` pathspec cannot produce, and is skipped rather than guessed at.
function Get-Delta($From, $To, $Spec) {
	$rows = & git diff --numstat "$From..$To" -- @Spec 2>$null
	$added = 0
	$removed = 0
	foreach ($row in $rows) {
		if ([string]::IsNullOrWhiteSpace($row)) { continue }
		$fields = $row.Split("`t")
		if ($fields.Length -lt 3) { continue }
		if ($fields[0] -eq '-' -or $fields[1] -eq '-') { continue }
		$added += [int]$fields[0]
		$removed += [int]$fields[1]
	}
	return @{ Added = $added; Removed = $removed }
}


$baseShort = & git rev-parse --short $Base
$headShort = & git rev-parse --short $Head

if (-not $Csv) {
	Write-Output "# eventsheets maintainability ledger $FormatVersion"
	Write-Output "# $baseShort..$headShort"
	Write-Output ""
	Write-Output ("{0,-22} {1,7} {2,10} {3,10} {4,10} {5,10}" -f 'area', 'files', 'lines', 'added', 'removed', 'net')
} else {
	Write-Output "area,files,lines,added,removed,net"
}

foreach ($area in $Areas) {
	$spec = @()
	$spec += $area.Spec
	$spec += $Generated
	$size = Get-Size $Head $spec
	$delta = Get-Delta $Base $Head $spec
	$net = $delta.Added - $delta.Removed
	if ($Csv) {
		Write-Output ("{0},{1},{2},{3},{4},{5}" -f $area.Name, $size.Files, $size.Lines, $delta.Added, $delta.Removed, $net)
	} else {
		Write-Output ("{0,-22} {1,7} {2,10} {3,10} {4,10} {5,10}" -f $area.Name, $size.Files, $size.Lines, ("+" + $delta.Added), ("-" + $delta.Removed), $net)
	}
}
