# AUTO-GENERATED by EventForge v0.9.0
# Source: res://demo/showcase/platformer_shooter.tres
# DO NOT EDIT — this file is regenerated on every compile.

class_name PlatformerShooter
extends Node2D

## Targets destroyed.
@export var score: int = 0
var __every_ps_spawn: float = 0.0

func _physics_process(delta: float) -> void:
	if Input.is_action_just_pressed(&"ui_up"):
		$Player/PlatformerMovement.jump()
	if Input.is_action_just_released(&"ui_up"):
		$Player/PlatformerMovement.jump_released()
	if Input.is_action_pressed(&"ui_accept") and $Player/WeaponKit.can_fire():
		$Player/WeaponKit.fire()
		var __spawn_shot = load("res://demo/showcase/shot.tscn").instantiate()
		__spawn_shot.position = $Player.position + Vector2(32.0 * $Player/PlatformerMovement.facing_direction(), -6.0)
		__spawn_shot.rotation_degrees = 0.0 if $Player/PlatformerMovement.facing_direction() >= 0 else 180.0
		add_child(__spawn_shot)
		if "shots" != "": __spawn_shot.add_to_group("shots")
	$Player.position.x = clampf($Player.position.x, 40.0, 1112.0)
	__every_ps_spawn += delta
	if __every_ps_spawn >= maxf(1.5, 0.001):
		__every_ps_spawn = fmod(__every_ps_spawn, maxf(1.5, 0.001))
		var __spawn_shot = load("res://demo/showcase/target.tscn").instantiate()
		__spawn_shot.position = Vector2(1240.0, randf_range(120.0, 540.0))
		__spawn_shot.rotation_degrees = 180.0
		add_child(__spawn_shot)
		if "targets" != "": __spawn_shot.add_to_group("targets")
	for __shot in get_tree().get_nodes_in_group("shots"):
		for __target in get_tree().get_nodes_in_group("targets"):
			if is_instance_valid(__shot) and is_instance_valid(__target) and __shot.global_position.distance_to(__target.global_position) < 42.0:
				__shot.queue_free()
				__target.queue_free()
				score += 1
				break
	for __node in get_tree().get_nodes_in_group("shots") + get_tree().get_nodes_in_group("targets"):
		if __node.global_position.x < -60.0 or __node.global_position.x > 1300.0:
			__node.queue_free()

func _process(delta: float) -> void:
	$Hud.text = "Score %d    Ammo %d/%d    %s" % [score, $Player/WeaponKit.current_ammo, $Player/WeaponKit.max_ammo, ("RELOADING..." if $Player/WeaponKit.is_reloading() else "A/D move   Up jump   hold Space fire")]

# [b]Platformer-Shooter[/b] — the new Platformer + Weapon Kit packs working together. Run with A/D, jump with Up (double jump + coyote time + variable height from the Platformer pack), and hold Space to shoot (fire-rate, ammo and auto-reload from the Weapon Kit). Shots destroy the red targets drifting in from the right.
