# AUTO-GENERATED by EventForge v0.1.0
# Source: res://demo/showcase/showcase_v060.tres
# DO NOT EDIT — this file is regenerated on every compile.

class_name ShowcaseV060
extends Node2D

## How hard the spring kicks.
@export_range(1, 3, 0.05) var pulse_scale: float = 1.35:
	set(value):
		pulse_scale = clampf(value, 1, 3)
## How many juice pulses have fired (watch it in Live Values — and edit it!).
@export_range(0, 999, 1) var pulses: int = 0
var __group_juice_active: bool = true
var __every_5c0wca5e: float = 0.0
var __live_values_timer: float = 0.0

func _ready() -> void:
	if EngineDebugger.is_active() and not EngineDebugger.has_capture("eventsheets"):
		EngineDebugger.register_message_capture(&"eventsheets", _eventsheets_debug_set)

func _process(delta: float) -> void:
	__live_values_timer += delta
	if __live_values_timer >= 0.25 and EngineDebugger.is_active():
		__live_values_timer = 0.0
		EngineDebugger.send_message("eventsheets:live_values", ["pulse_scale", pulse_scale, "pulses", pulses])
	__every_5c0wca5e += delta
	if __group_juice_active and __every_5c0wca5e >= maxf(2.0, 0.001):
		__every_5c0wca5e = fmod(__every_5c0wca5e, maxf(2.0, 0.001))
		pulses += 1
		$SpringBehavior.set_spring("__scale", 1.0)
		$SpringBehavior.spring_host_scale(1.0)
		$SpringBehavior.add_impulse("__scale", pulse_scale * 4.0)
		$TweenBehavior.tween_rotation(rotation_degrees + 90.0, 0.6)

## Live Values edit-back receiver (debug sessions only).
func _eventsheets_debug_set(message: String, data: Array) -> bool:
	if message != "set_value" or data.size() < 2:
		return false
	set(str(data[0]), data[1])
	return true

# [b]v0.6.0 showcase[/b] — a runtime-toggleable [i]Juice[/i] group pulses the host every 2s through the Spring behavior while Tween spins it. Run with Live Values on: watch [b]pulses[/b] climb, double-click to rewrite it live, and flip the group off with Set Group Active.
